Few improvements on Privacy Tools page
privacyguides/privacyguides.org pull request #1003
Opened 2022-04-13 16:31 UTC by elitejake

## Description

WIP

2022-04-13 17:37 UTC, lx-is commented
I wonder if it would be possible to implement an icon as a link to the footnote. As they stand right now, the links are hardly visible.

I think a little `i` info icon would look nice, though I'm not sure if it's even possible to link an icon to a footer note.

Maybe this would work?

```md
[:material-information-outline:]([^1)
```

2022-04-13 18:09 UTC, realguyman commented
While I do like footnotes, there isn't enough contrast between the two links, which causes it to blend in:

![image](https://user-images.githubusercontent.com/93285774/163242695-1103154b-4921-4b49-bf06-5f62910c543d.png)

![image](https://user-images.githubusercontent.com/93285774/163242777-092f0d0c-cbc8-4483-984e-6500d931bcbe.png)

Ideally links should be underlined for accessibility. This is one of the cases where it would be extremely beneficial to differentiate between separate links.

---

Why did you add arrows to the "Learn more ..." links? I'm not sure if it was needed, or improves anything significantly. Is this just for aesthetics?

2022-04-13 18:11 UTC, lx-is commented
> Why did you add arrows to the "Learn more ..." links? I'm not sure if it was needed, or improves anything significantly. Is this just for aesthetics?

I'm a fan of that addition personally. Nothing wrong with spending time on aesthetics 😛

2022-04-13 21:18 UTC, flexagoon commented
I think you shouldn't use footnotes. That's some pretty important information, it would probably be better if it was closer to the actual recommendation card. Because when you use footnotes, there's a high chance that the user will not notice it or think that it's something not important

2022-04-13 21:43 UTC, lx-is commented
Yeah I'm still mixed on the idea of footnotes for this too. If I'm being honest, I'm a bit mixed on the overview page as a whole. I feel it disregards a lot of important info that people should be seeing but most likely aren't. I'd personally like to see all the tools link to their card on pg, not the tool's homepage.

2022-04-13 22:13 UTC, jonaharagon commented
I'm of the same opinion as @flexagoon, I think footnotes are more suited for linking sources and providing additional clarification, but not for important explanatory content (which is why I didn't use them originally). 

I'm mixed on the linking to homepages vs linking to cards thing, I could see utility for either decision. 

I do like the arrows on the learn more links.

2022-04-13 22:17 UTC, jonaharagon requested changes
I'm not sure about this change. I wonder if annotations make more sense than footnotes: https://squidfunk.github.io/mkdocs-material/reference/annotations/

2022-04-13 22:17 UTC, jonaharagon commented on docs/tools.md
> +[^1]: We do not recommend installing ToS;DR as a browser extension. The same information is provided on their website.
This text should still be outside of the `div` element.

2022-04-14 00:25 UTC, realguyman commented
@jonaharagon I checked out the annotations feature and it seems to work wonderfully. Without JS, too. Seems to be an experimental feature, though.

2022-04-14 00:27 UTC, jonaharagon commented
I think all "insiders" features are marked experimental, but we make heavy use of them in this project.

2022-04-14 03:26 UTC, jonaharagon commented
I'm splitting this into two separate PRs, #1015 with your right arrow enhancement, and #1016 replacing the current notes with annotations; I'm not into the footnotes solution.

Thanks :)

2022-04-14 03:26 UTC, closed without merging

2022-04-14 07:22 UTC, elitejake commented
I wasn't into footnotes solution myself, but `*` was really ugly, IMO. Anyway, I completely agree with replacing it with annotations.