Add cryptocurrency recommendations
privacyguides/privacyguides.org pull request #1068
Opened 2022-04-21 22:25 UTC by jonaharagon

todo:

- [x] List Monero
- [ ] Explain CryptoNote
- [ ] Add Monero logo
- [ ] Add paragraph about why Bitcoin etc. are not private

Not sure if we want to mention Zcash and how it is not private by default or just leave it off.

2022-04-22 05:01 UTC, dngray commented
Not sure I see any point in listing zcash. I think privacy-by-default should be the standard.

2022-05-09 16:26 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
maybe mention https://localmonero.co/? U can get XMR without KYC and its a very trusted platform

2022-05-10 15:38 UTC, dngray commented
> maybe mention https://localmonero.co/? U can get XMR without KYC and its a very trusted platform

We're unlikely endorse any particular exchange, due to the nature of predictability. Would suggest visiting active communities surrounding Monero, like perhaps [/r/monero](https://www.reddit.com/r/Monero/) and/or [#monero:monero.social](https://matrix.to/#/#monero:monero.social).

2022-05-15 08:28 UTC, flexagoon commented
@dngray maybe you can link to https://web.getmonero.org/community/merchants/#exchanges then?

2022-05-15 23:02 UTC, jonaharagon commented
@flexagoon in the current iteration of this PR we don't actually recommend Monero at all, so we probably wouldn't. I don't know if that will change yet, Monero's privacy seems questionable, or at best merely unproven.

2023-03-02 18:07 UTC, SamsungGalaxyPlayer commented on docs/advanced/payments.md
> +In August 2021, CipherTrace [announced](https://finance.yahoo.com/news/ciphertrace-announces-enhanced-monero-tracing-160000275.html) enhanced Monero tracing capabilities for government agencies.
Add:

> Public postings show show that FinCEN [licensed](https://sam.gov/opp/d12cbe9afbb94ca68006d0f006d355ac/view) their "Monero Module" in late 2022.

 https://sam.gov/opp/d12cbe9afbb94ca68006d0f006d355ac/view

2023-03-02 18:07 UTC, SamsungGalaxyPlayer commented on docs/advanced/payments.md
> +Due to the high price of CipherTrace's solution ($16,000/user/year to select government agents) and the unavailability of more information surrounding Chainalysis and/or Integra Fec's solution(s), ==
I recommend rewriting as follows:

> Monero transaction graph privacy is limited by its relatively small ring signatures, especially against targeted attacks. Monero's privacy features have been [called into question](https://web.archive.org/web/20180331203053/https://www.wired.com/story/monero-privacy/) by some security researchers, and a number of severe vulnerabilities have been found and patched in the past, so the claims made by these organizations are not out of the question. While it's unlikely that Monero mass surveillance tools exist like they do for Bitcoin and others, it's certain that tracing tools assist with targeted investigations.

2023-03-02 18:18 UTC, jonaharagon commented on docs/advanced/payments.md
> +In 2020, [the IRS published a $625,000 bounty](https://www.forbes.com/sites/kellyphillipserb/2020/09/14/irs-will-pay-up-to-625000-if-you-can-crack-monero-other-privacy-coins/?sh=2e9808a085cc) for bre
> Contractors may choose to submit solutions to address Monero or Lightning transactions, or both as all approaches will be considered.

Oh yeah, fair enough.

2023-03-02 18:22 UTC, jonaharagon commented on docs/advanced/payments.md
> +In August 2021, CipherTrace [announced](https://finance.yahoo.com/news/ciphertrace-announces-enhanced-monero-tracing-160000275.html) enhanced Monero tracing capabilities for government agencies.
Very good to know, that happened well after I originally wrote this section 😅

2023-03-02 19:47 UTC, blacklight447 commented
@jonaharagon I like the changes you made. I do think this article could do with some more tooltips, as it contains a few technical terms that not every person would be familiar with.

Also, how do we feel about z-cash?

2023-03-03 02:44 UTC, mfwmyfacewhen requested changes

2023-03-03 02:44 UTC, mfwmyfacewhen commented on docs/financial-services.md
> +### Privacy.com (US, Free)
Privacy.com requires your [SSN](https://support.privacy.com/hc/en-us/articles/7969856996759-What-do-I-need-to-sign-up-for-a-Privacy-Account-), which to me should be a instant disqualification.

2023-03-03 02:44 UTC, mfwmyfacewhen commented on docs/financial-services.md
> +- No ID requirement.
```suggestion
- No ID requirement.
- No SSN or other identifying information requirement.
```

2023-03-03 02:44 UTC, mfwmyfacewhen commented on docs/advanced/payments.md
> +Making payments online while retaining your privacy is a difficult challenge. The traditional banking infrastructure is intentionally designed in an anti-privacy manner to enable banks, other compani
```suggestion
There's a reason data about your buying habits is considered the [holy grail](https://www.retaildive.com/ex/mobilecommercedaily/holy-grail-of-purchase-data-are-we-there-yet) of ad targeting: your purchases can leak a veritable treasure trove of data about you. Unfortunately, the current financial system is anti-privacy by design, enabling banks, other companies, and governments to easily trace transactions. Nevertheless, you have plenty of options when it comes to private payments.
```

2023-03-03 02:44 UTC, mfwmyfacewhen commented on docs/advanced/payments.md
> +Despite this, when you can use cash it’s typically the best option.
```suggestion
## Cash

For centuries, **cash** has functioned as the primary form of private payment. Cash has excellent privacy properties in most cases, is widely accepted in most countries, and is **fungible**, meaning it is non-unique and completely interchangable.

Cash payment laws vary by country. In the United States, special disclosure is required for cash payments over $10,000 to the IRS on [Form 8300](https://www.irs.gov/businesses/small-businesses-self-employed/form-8300-and-reporting-cash-payments-of-over-10000). The receiving business is required to ID verify the payee’s name, address, occupation, date of birth, and Social Security Number or other TIN (with some exceptions). Lower limits without ID such as $3,000 or less exist for exchanges and money transmission. Cash also contains serial numbers. These are almost never tracked by merchants, but they can be used by law enforcement in targeted investigations.

Despite this, it’s typically the best option.
```

2023-03-03 02:44 UTC, mfwmyfacewhen commented on docs/advanced/payments.md
> +There are also a number of services which provide "virtual debit cards" which you can use with online merchants while masking your actual banking or billing information in most cases. It's important
```suggestion
There are also a number of services which provide "virtual debit cards" which you can use with online merchants while masking your actual banking or billing information in most cases. It's important to note that these financial services are **not** anonymous and are subject to "Know Your Customer" (KYC) laws and may require your ID or other identifying information. For this reason, you should check and see if your bank supports virtual cards and prefer those over any third-party service. This way, you won't have to give your information to a new party. These services are primarily useful for protecting you from merchant data breaches, less sophisticated tracking or purchase correlation by marketing agencies, and online data theft; and **not** for making a purchase completely anonymously.
```

2023-03-03 03:30 UTC, jonaharagon commented on docs/financial-services.md
> +### Privacy.com (US, Free)
This has nothing to do with any threat models that would be relevant here? 🤔

2023-03-03 03:30 UTC, jonaharagon commented on docs/financial-services.md
> +- No ID requirement.
Wrong criteria section?

2023-03-03 03:41 UTC, jonaharagon commented on docs/advanced/payments.md
> +There are also a number of services which provide "virtual debit cards" which you can use with online merchants while masking your actual banking or billing information in most cases. It's important
That's just repeating information? Although this could be re-written.

```suggestion
Another way to protect your information from merchants online is to use virtual, single-use cards which mask your actual banking or billing information. This is primarily useful for protecting you from merchant data breaches, less sophisticated tracking or purchase correlation by marketing agencies, and online data theft. They do **not** assist you in making a purchase completely anonymously, nor do they hide any information from the banking institution themselves. Regular financial institutions which offer virtual cards are subject to "Know Your Customer" (KYC) laws, meaning they may require your ID or other identifying information.
```

2023-03-03 03:46 UTC, jonaharagon commented on docs/advanced/payments.md
> +Making payments online while retaining your privacy is a difficult challenge. The traditional banking infrastructure is intentionally designed in an anti-privacy manner to enable banks, other compani
Buying habits being useful for ad targeting feels self-explanatory, I don't think we need to link to another (random?) site to justify saying that.

2023-03-03 03:47 UTC, mfwmyfacewhen commented on docs/financial-services.md
> +### Privacy.com (US, Free)
What's the point of no ID if you're giving your SSN anyway? Not very comfortable with it.

2023-03-03 03:49 UTC, mfwmyfacewhen commented on docs/advanced/payments.md
> +There are also a number of services which provide "virtual debit cards" which you can use with online merchants while masking your actual banking or billing information in most cases. It's important
Yeah looks good

2023-03-03 03:50 UTC, jonaharagon commented on docs/financial-services.md
> +### Privacy.com (US, Free)
?

https://github.com/privacyguides/privacyguides.org/pull/1068/files/57a04a5ca1f3078a3f988716a1b617af542125df#diff-10619880222a87160686a7c01631376479e7c096e72102f4c4a75a851af5db00R50-R59

2023-03-03 03:52 UTC, mfwmyfacewhen commented on docs/advanced/payments.md
> +Making payments online while retaining your privacy is a difficult challenge. The traditional banking infrastructure is intentionally designed in an anti-privacy manner to enable banks, other compani
Yeah fair

2023-03-04 03:23 UTC, dngray commented on docs/advanced/payments.md
> +Privacy coins have been subject to increasing scrutiny by government agencies. In 2020, [the IRS published a $625,000 bounty](https://www.forbes.com/sites/kellyphillipserb/2020/09/14/irs-will-pay-up-
> Generally speaking however

Doesn't add anything to the paragraph. I like to avoid English-isms that sometimes are said in verbal speech.

2023-03-04 06:47 UTC, dngray commented
> todo:
> 
>     *

I've added the logos, and reached out to Cake pay for a SVG.

2023-03-04 06:47 UTC, dngray commented
I've added the logos, and reached out to Cake pay for a SVG.

2023-03-04 07:14 UTC, dngray requested changes

2023-03-04 07:14 UTC, dngray commented on docs/cryptocurrency.md
> +- [Official Monero GUI/CLI](https://getmonero.org/downloads) (Desktop)
We should make sure to add GUI/CLI to the abbreviations file, or maybe figure out a better way to write that.

2023-03-04 07:16 UTC, dngray commented
> Also, how do we feel about z-cash?

iirc that's not private by default, which is one of the requirements.

2023-03-04 07:24 UTC, dngray commented on docs/advanced/payments.md
> +When buying gift cards online, there is usually a slight discount. Prepaid cards are usually sold online at face value or with a fee. If you buy prepaid cards and gift cards with cryptocurrencies, yo
```suggestion
When buying gift cards online, there is usually a slight discount. Prepaid cards are usually sold online at face value or with a fee. If you buy prepaid cards and gift cards with cryptocurrencies, you should strongly prefer to pay with Monero which provides strong privacy, more on this below. Paying for a gift card with a traceable payment method negates the benefits a gift card can provide when purchased with cash or Monero.
```

```suggestion
When buying gift cards online, there is usually a slight discount. Prepaid cards are usually sold online at face value or with a fee. If you buy prepaid cards and gift cards with cryptocurrencies, you should strongly prefer to pay with [Monero](../cryptocurrency.md#monero) which provides strong privacy, more on this below. Paying for a gift card with a traceable payment method negates the benefits a gift card can provide when purchased with cash or Monero.
```

2023-03-04 22:19 UTC, jonaharagon commented on docs/advanced/payments.md
> +When buying gift cards online, there is usually a slight discount. Prepaid cards are usually sold online at face value or with a fee. If you buy prepaid cards and gift cards with cryptocurrencies, yo
we link to cryptocurrency.md in the preceding paragraph already

2023-03-04 22:23 UTC, jonaharagon commented
@dngray I don't really have an issue with how the CoinCards logo looks as-is, the other services have mobile apps with icons that would look better. Privacy.com uses this square logo on their social media for example. 

https://play-lh.googleusercontent.com/xcIH2rg95sUMnhLZiQmMMuuj-GL2VuKtDjfmbvGbf5ODUCTob2DyxOoc_ZRCp9s96w

2023-03-04 22:24 UTC, jonaharagon commented on docs/financial-services.md
> +### Revolut
is this more information than any other banking service in the EU would require?

2023-03-04 22:25 UTC, jonaharagon commented on docs/advanced/payments.md
> +Cash payment laws vary by country. In the United States, special disclosure is required for cash payments over $10,000 to the IRS on [Form 8300](https://www.irs.gov/businesses/small-businesses-self-e
i think it's just an example, we can't enumerate laws in every jurisdiction worldwide because:

> Cash payment laws vary by country.

2023-03-05 12:54 UTC, dngray commented
> have mobile apps with icons that would look better

Oh yeah, I do agree. I wonder if privacy.com have a light version?

2023-03-05 12:55 UTC, dngray commented on docs/advanced/payments.md
> +When buying gift cards online, there is usually a slight discount. Prepaid cards are usually sold online at face value or with a fee. If you buy prepaid cards and gift cards with cryptocurrencies, yo
That's fair.

2023-03-05 12:58 UTC, dngray commented on docs/advanced/payments.md
> +Privacy coins have been subject to increasing scrutiny by government agencies. In 2020, [the IRS published a $625,000 bounty](https://www.forbes.com/sites/kellyphillipserb/2020/09/14/irs-will-pay-up-
```suggestion
Privacy coins have been subject to increasing scrutiny by government agencies. In 2020, [the IRS published a $625,000 bounty](https://www.forbes.com/sites/kellyphillipserb/2020/09/14/irs-will-pay-up-to-625000-if-you-can-crack-monero-other-privacy-coins/?sh=2e9808a085cc) for tools which can break Bitcoin Lightning Network and/or Monero's transaction privacy. They ultimately [paid two companies](https://sam.gov/opp/5ab94eae1a8d422e88945b64181c6018/view) (Chainalysis and Integra Fec) a combined $1.25 million for tools which purport to do so (it is unknown which cryptocurrency network these tools target). Due to the secrecy surrounding tools like these, ==none of these methods of tracing cryptocurrencies have been independently confirmed.== Tools which assist targeted investigations into private coin transactions almost certainly exist, even if privacy coins successfully thwart mass surveillance.
```

2023-03-05 12:59 UTC, dngray commented on docs/cryptocurrency.md
> +- [Official Monero GUI/CLI](https://getmonero.org/downloads) (Desktop)
```suggestion
- [Official Monero client](https://getmonero.org/downloads) (Desktop)
```

I think I'd just leave out it has CLI, they say that on their website anyway.

2023-03-05 15:42 UTC, jonaharagon commented
@dngray there is an SVG light version of their full logo in their website footer which is just inverted.

2023-03-05 15:45 UTC, jonaharagon commented on docs/advanced/payments.md
> +Privacy coins have been subject to increasing scrutiny by government agencies. In 2020, [the IRS published a $625,000 bounty](https://www.forbes.com/sites/kellyphillipserb/2020/09/14/irs-will-pay-up-
doesn't read right to me without at least starting with "However,"

2023-03-05 17:06 UTC, dngray commented
> @dngray there is an SVG light version of their full logo in their website footer which is just inverted.

> there is an SVG light version of their full logo in their website footer which is just inverted.

Oh, I thought you wanted to use the [square logo](https://github.com/privacyguides/privacyguides.org/pull/1068#issuecomment-1454906016).

2023-03-05 17:11 UTC, dngray commented on docs/advanced/payments.md
> +Privacy coins have been subject to increasing scrutiny by government agencies. In 2020, [the IRS published a $625,000 bounty](https://www.forbes.com/sites/kellyphillipserb/2020/09/14/irs-will-pay-up-
We could I guess use "however,". I just really hate *generally speaking*, as an opening to a sentence because it feels superfluous.

2023-03-05 17:19 UTC, dngray commented
> Oh, I thought you wanted to use the [square logo](https://github.com/privacyguides/privacyguides.org/pull/1068#issuecomment-1454906016).

Now that all the logos are there I think we should maybe just leave them as is. If you start using icons for some of them you'll find that it will look weird.

2023-03-07 15:23 UTC, mfwmyfacewhen approved these changes

2023-03-07 20:32 UTC, jonaharagon commented
It occurs to me that we should probably consider MobileCoin as a cryptocurrency recommendation.

2023-03-07 22:00 UTC, blacklight447 approved these changes

2023-03-09 03:58 UTC, dngray approved these changes

2023-03-09 04:27 UTC, mfwmyfacewhen commented on docs/financial-services.md
> +### Revolut
Gonna remove it for now and it can be revisited later.

2023-03-09 04:28 UTC, mfwmyfacewhen requested changes

2023-03-09 04:28 UTC, mfwmyfacewhen commented on docs/financial-services.md
> +Revolut is [available](https://help.revolut.com/en-MT/help/profile-and-plan/profile-plan/verifying-identity/what-countries-are-supported) to legal residents of the European Economic Area (EEA), Austr
```suggestion
```

2023-03-09 04:31 UTC, mfwmyfacewhen approved these changes

2023-03-09 04:50 UTC, merged

2023-03-09 07:59 UTC, noClaps commented on docs/financial-services.md
> +### Revolut
Revolut is however the only one that I know of that allows virtual cards in the rest of the world, especially the UK and EU. N26 is another one but I believe they pulled out of the UK post-Brexit.
https://discuss.privacyguides.net/t/uk-virtual-card-service/11670/2

2023-03-09 16:30 UTC, noClaps commented on docs/financial-services.md
> +### Revolut
N26 is not available in the UK. They pulled out post-Brexit.