Update the android sections to be more consistent
privacyguides/privacyguides.org pull request #1086
Opened 2022-04-23 10:19 UTC by tommytran732

2022-04-23 15:00 UTC, dngray commented
Initial proof reading, I do want to give these pages another look when I'm less tired

2022-04-23 15:54 UTC, jonaharagon requested changes

2022-04-23 15:54 UTC, jonaharagon commented on docs/android.en.md
> +    GrapheneOS is recommended for users who want the best security and privacy features. The Sandboxed Play Services offer [superior](android/grapheneos-vs-calyxos.md#sandboxed-google-play-vs-privile
This seems redundant, we already mention this earlier.

2022-04-23 15:54 UTC, jonaharagon commented on docs/android.en.md
> +    This problem is somewhat mitigated when you install a custom operating system such as CalyxOS or DivestOS and trust the developer's signing keys rather than the stock system keys. **To reiterate,
Not really explaining why it's only "somewhat" mitigated in this change.

2022-04-23 15:54 UTC, jonaharagon commented on docs/android.en.md
> +If you have to choose between a OnePlus 8T/9 or a Fairphone 4 to use with CalyxOS, we highly recommend that you buy a OnePlus phone. If you already have a Fairphone 4, it might be a good idea to sell
This line seems unnecessary, we say we don't recommend either earlier on the page, so this is just confusing.

2022-04-23 15:54 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +The only threat model we can think of where you might want to use MicroG is one where you do not trust Google but instead trust Mozilla and other third parties with with the MAC addresses of the devi
I would probably just remove these "when threat modeling" paragraphs entirely, they make no sense. This is not what threat modeling even is. _Clearly_ this threat model _does_ exist, and _we're not trying to tell people what their threat models are_, so this is a decision best left to the reader.

2022-04-23 15:54 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +In conclusion, we do not believe MicroG provides any privacy or usability advantages over Sandboxed Google Play.
Adding a conclusion statement just makes it sound like you don't think the reader could grasp whatever you just said.

```suggestion
```

> Omit these phrases. “In conclusion” or “To conclude” may be appropriate for an oral presentation, but in writing are considered redundant or overly mechanical.

https://www.lib.sfu.ca/about/branches-depts/slc/writing/organization/conclusions

2022-04-23 15:54 UTC, jonaharagon commented on docs/android/overview.en.md
> +If you have a Google account we suggest enrolling in the [Advanced Protection Program](https://landing.google.com/advancedprotection/). It is available at no cost to anyone with two or more hardware
This is a regression #1025 
```suggestion
If you have a Google account we suggest enrolling in the [Advanced Protection Program](https://landing.google.com/advancedprotection/). It is available at no cost to anyone with two or more hardware security keys with [FIDO](../security/multi-factor-authentication.md#fido-fast-identity-online) support.
```

2022-04-23 15:54 UTC, jonaharagon commented on docs/android/overview.en.md
> +If you have an end of life (EOL) device shipped with Android 10 or above and are unable to run any of the recommended operating systems on your device, you are likely going to be better off sticking
```suggestion
In the past, Android security updates had to be shipped by the operating system vendor. Android has become more modular beginning with Android 10, and Google can push security updates for **some** system components via the privileged Play Services.

If you have an end of life (EOL) device shipped with Android 10 or above and are unable to run any of our recommended operating systems on your device, you are likely going to be better off sticking with your OEM Android installation (as opposed to an operating system not listed here such as LineageOS or /e/ OS). This will allow you to receive **some** security fixes from Google, while not violating the Android security model by using an insecure Android derivative and increasing your attack surface. We would still recommend upgrading to a supported device as soon as possible.
```

2022-04-23 16:01 UTC, dngray commented on docs/android.en.md
> +    GrapheneOS is recommended for users who want the best security and privacy features. The Sandboxed Play Services offer [superior](android/grapheneos-vs-calyxos.md#sandboxed-google-play-vs-privile
I was thinking that myself.

2022-04-23 16:04 UTC, jonaharagon commented on docs/android.en.md
> +    DivestOS firmware update [status](https://gitlab.com/divested-mobile/firmware-empty/-/blob/master/STATUS) and quality control varies across the devices it supports. For Pixel phones, we still rec
```suggestion
    DivestOS firmware update [status](https://gitlab.com/divested-mobile/firmware-empty/-/blob/master/STATUS) and quality control varies across the devices it supports. We still recommend GrapheneOS or CalyxOS depending on your device's compatibility. For other devices, DivestOS is a good alternative.
```

2022-04-23 16:04 UTC, jonaharagon commented on docs/android.en.md
> +Unless you have a specific need for specific [CalyxOS features](https://calyxos.org/features/) that are unavailable on GrapheneOS, we strongly recommend GrapheneOS over other operating system choices
```suggestion
Unless you have a need for specific [CalyxOS features](https://calyxos.org/features/) that are unavailable on GrapheneOS, we strongly recommend GrapheneOS over other operating system choices on Pixel devices.
```

2022-04-23 16:04 UTC, jonaharagon commented on docs/android.en.md
> +    The following phones are only mentioned as they are compatible with the operating systems recommended by us. They are **not** recommended devices, and you should only buy them if you do not have
```suggestion
    The following OEMs are only mentioned as they have phones compatible with the operating systems recommended by us. If you are purchasing a new device, we only recommend purchasing a Google Pixel.
```

2022-04-23 16:04 UTC, jonaharagon commented on docs/android.en.md
> +If you are unable to obtain a Google Pixel, recent OnePlus devices is the next best option if you still want to run a custom OS without privileged Play Services. The OnePlus 8 and later devices are r
```suggestion
If you are unable to obtain a Google Pixel, recent OnePlus devices is the next best option if you still want to run a custom OS without privileged Play Services. OnePlus 8 and later devices will receive 4 years of security updates from their initial launch date. CalyxOS has [experimental support](https://calyxos.org/news/2022/04/01/fairphone4-oneplus8t-oneplus9-test-builds/) for the **OnePlus 8T** and **9**.
```

2022-04-23 16:05 UTC, jonaharagon commented on docs/android.en.md
> +    The Fairphone by default is not secure as the [stock bootloader trusts the public AVB signing key](https://forum.fairphone.com/t/bootloader-avb-keys-used-in-roms-for-fairphone-3-4/83448/11), mean
```suggestion
    The Fairphone is not secure by default, as the [stock bootloader trusts the public AVB signing key](https://forum.fairphone.com/t/bootloader-avb-keys-used-in-roms-for-fairphone-3-4/83448/11). This means that any operating system can be installed, and the phone will trust it as if it is the stock system. This breaks verified boot on a stock Fairphone device.
```

2022-04-23 16:10 UTC, jonaharagon commented on docs/android.en.md
> +    This problem is somewhat mitigated when you install a custom operating system such as CalyxOS or DivestOS and trust the developer's signing keys rather than the stock system keys. **To reiterate,
```suggestion
    This problem is somewhat mitigated when you install a custom operating system such as CalyxOS or DivestOS and trust the developer's signing keys rather than the stock system keys, however a vulnerability in CalyxOS or DivestOS's recovery environments could still potentially allow an attacker to bypass AVB. **To reiterate, you must install a custom operating system with custom boot keys to use Fairphone devices in a secure manner.**
```

2022-04-23 16:15 UTC, dngray commented on docs/android/grapheneos-vs-calyxos.en.md
> +The only threat model we can think of where you might want to use MicroG is one where you do not trust Google but instead trust Mozilla and other third parties with with the MAC addresses of the devi
Agreed.

2022-04-23 16:16 UTC, dngray commented on docs/android/grapheneos-vs-calyxos.en.md
> +In conclusion, we do not believe MicroG provides any privacy or usability advantages over Sandboxed Google Play.
Agreed, and it also shouldn't be required if the sentence is succinct.

2022-04-23 17:16 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +When evaluating ease of use, we believe Sandboxed Google Play also works well with far more applications than microG, due to its support for services like [Google Play Games](https://play.google.com/
Not really an opinion, don't state it as such:
```suggestion
In terms of application compatibility, Sandboxed Google Play outperforms microG due to its support for many services which microG has not yet implemented, like [Google Play Games](https://play.google.com/googleplaygames) and [In-app Billing API](https://android-doc.github.io/google/play/billing/api.html). Authentication using [FIDO](security/multi-factor-authentication#fido-fast-identity-online) with online services on Android also relies on Play Services, and the feature is not yet implemented in microG.
```

2022-04-23 17:16 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +microG is a reimplementation of Google Play Services. This means it needs to be updated every time Android has a major version update (or the Android API changes). It also needs to run in the highly
```suggestion
microG is an open-source re-implementation of Google Play Services. This means it needs to be updated every time Android has a major version update (or the Android API changes). It also needs to run in the highly privileged [`system_app`](https://source.android.com/security/selinux/concepts) SELinux domain like regular Google Play Services, and it requires an operating system that allows [signature spoofing](https://github.com/microg/GmsCore/wiki/Signature-Spoofing), which allows system apps to insecurely masquerade as other apps. This is less secure than Sandboxed Google Play's approach, which does not need access to sensitive system APIs.
```

2022-04-23 17:16 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +The only threat model we can think of where you might want to use microG is one where you do not trust Google but instead trust Mozilla and other third parties with with the MAC addresses of the devi
```suggestion
When using Sandboxed Play Services, you have the option to reroute location requests to the Play Services API back to the OS location API which uses satellite based location services. With microG, you have the option to either not use a network location backend at all, or to *shift trust* to another location backend like Mozilla or Dejavu. Using an alternative location backend still submits location data to these third-party providers, just not Google's own location services.
```

2022-04-23 17:16 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +The only threat model we can think of where you might want to use MicroG is one where you do not trust Google but instead trust Mozilla and other third parties with with the MAC addresses of the devi
https://github.com/privacyguides/privacyguides.org/pull/1086#discussion_r856941910

2022-04-23 17:21 UTC, dngray submitted a review, later dismissed

2022-04-23 17:23 UTC, dngray commented on docs/android/grapheneos-vs-calyxos.en.md
> +The only threat model we can think of where you might want to use MicroG is one where you do not trust Google but instead trust Mozilla and other third parties with with the MAC addresses of the devi
I do think that fixes things.

2022-04-23 17:33 UTC, dngray commented on docs/android.en.md
> +If you have to choose between a OnePlus 8T/9 or a Fairphone 4 to use with CalyxOS, we highly recommend that you buy a OnePlus phone. If you already have a Fairphone 4, it might be a good idea to sell
I deleted that second sentence.

2022-04-23 17:54 UTC, jonaharagon requested changes

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +GrapheneOS supports [Sandboxed Google Play](https://grapheneos.org/usage#sandboxed-google-play). Google Play Services can be run fully sandboxed like a regular user app and contained in a work profil
```suggestion
GrapheneOS supports [Sandboxed Google Play](https://grapheneos.org/usage#sandboxed-google-play), which runs [Google Play Services](https://en.wikipedia.org/wiki/Google_Play_Services) fully sandboxed like a regular user app. This means you can take advantage of most Google Play Services, such as [push notifications](https://firebase.google.com/docs/cloud-messaging/), while having full user control over their permissions and access, and while containing them to a specific work profile or user [profile](android/overview.md#user-profiles) of your choice.```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +[Pixel phones](https://grapheneos.org/faq#device-support) are the only devices that currently meet the hardware security requirements to be supported.
```suggestion
Google Pixel phones are the only devices that currently meet GrapheneOS's [hardware security requirements](https://grapheneos.org/faq#device-support).
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +CalyxOS only supports [Pixel phones](https://calyxos.org/docs/guide/device-support/), however, support for the OnePlus 8T/9 and Fairphone 4 is [currently in beta](https://calyxos.org/news/2022/04/01/
```suggestion
CalyxOS only [supports](https://calyxos.org/docs/guide/device-support/) Google Pixel phones. However, support for the OnePlus 8T/9 and Fairphone 4 is [currently in beta](https://calyxos.org/news/2022/04/01/fairphone4-oneplus8t-oneplus9-test-builds/).
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
```suggestion
DivestOS implements some system hardening patches originally developed for GrapheneOS. DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.com/GrapheneOS/hardened_malloc), [exec-spawning](android/grapheneos-vs-calyxos.md#additional-hardening), [JNI](https://en.wikipedia.org/wiki/Java_Native_Interface) [constification](https://en.wikipedia.org/wiki/Const_(computer_programming)), and partial [bionic](https://en.wikipedia.org/wiki/Bionic_(software)) hardening patchsets. 17.1 and 18.1 feature GrapheneOS's per-network full [MAC randomization](https://en.wikipedia.org/wiki/MAC_address#Randomization) option, and [`ptrace_scope`](https://www.kernel.org/doc/html/latest/admin-guide/LSM/Yama.html) control, and automatic reboot/Wi-Fi/Bluetooth [timeout options](https://grapheneos.org/features).
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +    Google Pixel phones are the **only** devices recommended by us. Pixel phones have stronger hardware security than any other Android devices currently on the market, due to proper AVB support for
```suggestion
    Google Pixel phones are the **only** devices we recommend for purchase. Pixel phones have stronger hardware security than any other Android devices currently on the market, due to proper AVB support for third party operating systems and Google's custom [Titan](https://security.googleblog.com/2021/10/pixel-6-setting-new-standard-for-mobile.html) security chips acting as the Secure Element.
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +If you are unable to obtain a Google Pixel, recent OnePlus devices is the next best option if you still want to run a custom OS without privileged Play Services. OnePlus 8 and later devices will rece
```suggestion
If you are unable to obtain a Google Pixel, recent OnePlus devices are the next best option if you want to run a custom OS without privileged Play Services. OnePlus 8 and later devices will receive 4 years of security updates from their initial launch date. CalyxOS has [experimental support](https://calyxos.org/news/2022/04/01/fairphone4-oneplus8t-oneplus9-test-builds/) for the **OnePlus 8T** and **9**.
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +    On the Fairphone 3 and 4, there is effectively no verified boot as the system will boot alternative Android operating systems such (such as /e/) [without any warning](https://source.android.com/s
Repeating ourselves?
```suggestion
    The Fairphone is not secure by default, as the [stock bootloader trusts the public AVB signing key](https://forum.fairphone.com/t/bootloader-avb-keys-used-in-roms-for-fairphone-3-4/83448/11). This breaks verified boot on a stock Fairphone device, as the system will boot alternative Android operating systems such (such as /e/) [without any warning](https://source.android.com/security/verifiedboot/boot-flow#locked-devices-with-custom-root-of-trust) about custom operating system usage.
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android.en.md
> +Fairphone markets their devices as receiving 6 years of support however, the SOC (Qualcomm Snapdragon 750G on the Fairphone 4) has a considerably shorter EOL date. This means that firmware security u
```suggestion
Fairphone markets their devices as receiving 6 years of support. However, the SoC (Qualcomm Snapdragon 750G on the Fairphone 4) has a considerably shorter EOL date. This means that firmware security updates from Qualcomm for the Fairphone 4 will end in September 2023, regardless of whether Fairphone continues to release software security updates.
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android/overview.en.md
> +Each user's data is encrypted using their own unique encryption key, and the operating system files are left unencrypted. Verified Boot ensures the integrity of the operating system files preventing
```suggestion
Android 10 and above has moved away from full-disk encryption to more flexible [file-based encryption](https://source.android.com/security/encryption/file-based). Each user's data is encrypted using their own unique encryption key, and the operating system files are left unencrypted. Verified Boot ensures the integrity of the operating system files, thereby preventing an adversary with physical access from tampering or installing malware on the device. In the unlikely case that malware is able to exploit other parts of the system and gain higher privileged access, Verified Boot will prevent and revert changes to the system partition upon rebooting the device.
```

2022-04-23 17:54 UTC, jonaharagon commented on docs/android/overview.en.md
> +Unfortunately, OEMs are only obliged to support Verified Boot on their stock Android distribution. Only a few OEMs such as Google support custom AVB key enrollment on their devices. Some AOSP derivat
```suggestion
Unfortunately, OEMs are only obliged to support Verified Boot on their stock Android distribution. Only a few OEMs such as Google support custom AVB key enrollment on their devices. Additionally, some AOSP derivatives such as LineageOS or /e/ OS do not support Verified Boot even on hardware with Verified Boot support for third party operating systems. We recommend that you check for support **before** purchasing a new device. AOSP derivatives which do not support Verified Boot are **not** recommended.
```

2022-04-23 17:58 UTC, jonaharagon commented on docs/android/overview.en.md
> +Each user's data is encrypted using their own unique encryption key, and the operating system files are left unencrypted. Verified Boot ensures the integrity of the operating system files preventing
or (which sounds better?) 
```suggestion
Android 10 and above has moved away from full-disk encryption to more flexible [file-based encryption](https://source.android.com/security/encryption/file-based). Each user's data is encrypted using their own unique encryption key, and the operating system files are left unencrypted. 

Verified Boot ensures the integrity of the operating system files preventing an adversary with physical access from tampering or installing malware on the device. In the unlikely case that malware is able to exploit other parts of the system and gain higher privileged access, Verified Boot will prevent and revert changes to the system partition upon reboot of the device.
```

2022-04-24 02:28 UTC, jonaharagon approved these changes

2022-04-24 04:50 UTC, jonaharagon requested changes

2022-04-24 04:50 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +When using Sandboxed Play Services, you have the option to reroute location requests to the Play Services API back to the OS location API which uses satellite based location services. With microG, yo
```suggestion
When using Sandboxed Play Services, you have the option to reroute location requests to the Play Services API back to the OS location API which uses satellite based location services. With microG, you have the option to either not use a network location backend at all, *shift trust* to another location backend like Mozilla, or use [DejaVu](https://github.com/n76/DejaVu), a location backend that locally collects and saves RF-based location data to an offline database which can be used when GPS is not available.
```

2022-04-24 05:23 UTC, jonaharagon submitted a review, later dismissed

2022-04-24 15:18 UTC, dngray approved these changes

2022-04-24 15:18 UTC, merged