Add context to browser configuration options
privacyguides/privacyguides.org pull request #1177
Opened 2022-05-04 18:34 UTC by jonaharagon

2022-05-04 20:03 UTC, lx-is requested changes

2022-05-04 20:03 UTC, lx-is commented on docs/browsers.en.md
> +[Firefox Sync](https://hacks.mozilla.org/2018/11/firefox-sync-privacy/) allows your browsing data (history, bookmarks, etc.) to be accessible on all your devices. It is fully E2EE, so it should be sa
It's the first time the abbreviation is used on this page.

```suggestion
[Firefox Sync](https://hacks.mozilla.org/2018/11/firefox-sync-privacy/) allows your browsing data (history, bookmarks, etc.) to be accessible on all your devices. It is fully end-to-end encrypted (E2EE), so it should be safe to use.
```

2022-05-04 20:03 UTC, lx-is commented on docs/browsers.en.md
> +This prevents you from unintentionally connecting to a website in plain-text HTTP. The HTTP protocol is extremely uncommon nowadays, so this should have little impact on your day to day browsing.
```suggestion
This prevents you from unintentionally connecting to a website in plain-text HTTP. The HTTP protocol is extremely uncommon nowadays, so this should have little to no impact on your day to day browsing.
```

2022-05-04 20:25 UTC, lx-is commented
I'm going to do the Safari section later tn

2022-05-04 22:14 UTC, jonaharagon commented on docs/browsers.en.md
> +This protects you from persistent cookies, but does not protect you against cookies acquired during any one browsing session. When this is enabled you know you can easily clear your browser of all co
so:
```suggestion
This protects you from persistent cookies, but does not protect you against cookies acquired during any one browsing session. When this is enabled, it becomes possible to easily cleanse your browser cookies by simply restarting Firefox. You can set exceptions on a per-site basis, if you wish to stay logged in to a particular site you visit often.
```

2022-05-04 22:22 UTC, jonaharagon commented on docs/browsers.en.md
> +[Firefox Sync](https://hacks.mozilla.org/2018/11/firefox-sync-privacy/) allows your browsing data (history, bookmarks, etc.) to be accessible on all your devices. It is fully E2EE, so it should be sa
Gonna think about this... I am leaning towards leaving it as-is and changing the rule for very common abbreviations like E2EE, because the reader is *probably* familiar with it after reading enough of the site, and the glossary functionality includes the full text on hover regardless.

2022-05-04 22:36 UTC, lx-is commented on docs/browsers.en.md
> +[Firefox Sync](https://hacks.mozilla.org/2018/11/firefox-sync-privacy/) allows your browsing data (history, bookmarks, etc.) to be accessible on all your devices. It is fully E2EE, so it should be sa
I actually thought about that too. I figured the browser page is one of the highest trafficked pages, and so the highest chance of someone not being confident with the term is higher. There is the contextual definition, but I've found it doesn't work well on mobile, which is the platform statistically most readers view the site from. For example, if the definition is near the screen edge, it won't wrap and will instead be cut off. So, I've been avoiding relying on the definition popups in my PRs.

2022-05-05 04:27 UTC, lx-is requested changes

2022-05-05 04:27 UTC, lx-is commented on docs/browsers.en.md
> +- [x] Select **Privacy Preserving Ad Measurement**
```suggestion
- [ ] Uncheck **Privacy Preserving Ad Measurement**

Ad click measurement has traditionally used tracking technology that infringes on user privacy. [Private Click Measurement](https://webkit.org/blog/11529/introducing-private-click-measurement-pcm/) is a WebKit feature and proposed web standard aimed towards allowing advertisers to measure the effectiveness of web campaigns without compromising on user privacy.

The feature has little privacy concerns on its own, so while you can choose to leave it on, we consider the fact that it's automatically disabled in Private Browsing to be an indicator for disabling the feature.
```

2022-05-05 04:27 UTC, lx-is commented on docs/browsers.en.md
>  This is WebKit's own [implementation](https://webkit.org/blog/8943/privacy-preserving-ad-click-attribution-for-the-web/) of privacy preserving ad click attribution. If you do not wish to participate,
```suggestion
```

2022-05-05 05:15 UTC, lx-is commented on docs/browsers.en.md
> +- [ ] Uncheck **Allow websites to check for Apple Pay and Apple Card**
I wrote an email to Apple asking whether or not this should be enabled or not. My fear is that, by disabling it, it's creating another "do not track" setting scenario where it just makes it easier to identify a browser.

> Hi, I'm reaching out to see if your team could answer a question I had about the "Check for Apple Pay" feature in Safari.
> 
> As the Safari specific privacy policy states, "When you are in an app or on a website that uses Apple Pay, ... they can check if you have Apple Pay enabled on that device." The takeaway being: sites are able to probe the browser for whether or not the "Check for Apple Pay" feature is enabled.
> 
> My concern is that, by *disabling* this feature, it can harm privacy by potentially making the browser more identifiable as most Safari users likely do not disable the feature.
> 
> This scenario would be akin to the infamous "ask website to not track" setting, that is considered a flop as it created yet another data point to identify browsers.
> 
> I get that fingerprinting is pretty inevitable unless you're using the Tor browser, but the goal isn't to make fingerprinting easier either.
> 
> So my question is — should I keep the "Check for Apple Pay" setting enabled in an effort to blend in with other Safari users, or is that a misguided effort?
> 
> Thanks for your time.

2022-05-05 17:25 UTC, jonaharagon commented
@lx-is I think I'm going to merge this as-is, because I believe the information about Apple Pay is accurate. If you receive something to the contrary from Apple we can open another PR.

2022-05-05 17:25 UTC, merged