How Tor Works article
privacyguides/privacyguides.org pull request #1219
Opened 2022-05-13 17:46 UTC by dngray

This is the How Tor Works article that we used to have on the blog.

2022-05-13 22:33 UTC, lx-is requested changes
All of my suggestions are semantic changes. The content itself looks great 👍

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +Tor works by sending your traffic over a network of thousands of voluntarily run nodes (sometimes referred to as relays). Each node is a server that is run by volunteers to help you improve your priv
These changes improve the overall flow of the sentences.

> Each node is a server that is run by volunteers to help you improve your privacy and anonymity.

This sentence is redundant.

I split up the sentences as it helps visually separate the different ideas. Idea 1 being how Tor works and it's decentralized nature. Idea 2 being what happens when you connect to Tor and the transition to the node descriptions.

```suggestion
Tor works by routing your traffic through a network comprised of thousands of voluntarily run servers called nodes (or relays).

Every time you connect to Tor, it will choose three nodes to build a path to the internet—this path is called a circuit. Each of these nodes has its own function:
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +  - **The Entry Node**: often called the guard node, this is the first node your computer connects to. The entry node sees your IP address, but does not see what you are connecting to. Unlike the oth
```suggestion
  - **The Entry Node**: Often called the guard node, this is the first node your computer connects to. The entry node sees your IP address, but does not see what you are connecting to. Unlike the other nodes, the Tor client will randomly select an entry node, and stick with it for 2 to 3 months to protect you from certain attacks.
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +  - **The Middle Node**: the second node to which your Tor client connects. This node can see which node traffic came from (the entry node) and which it goes to next. It does not, however, see your I
```suggestion
  - **The Middle Node**: The second node to which your Tor client connects. This node can see which node traffic came from (the entry node) and which it goes to next. It does not, however, see your IP address, or the domain you are connecting to. This node is randomly picked from all Tor nodes for each circuit.
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +  - **The Exit Node**: is where your traffic leaves the Tor network and is forwarded to the destination domain. The exit node does not know your IP (who you are) but it knows what you are connecting
Some more info on what a "exit flag" is might be useful.

```suggestion
  - **The Exit Node**: This is where your traffic leaves the Tor network and is forwarded to your desired destination. The exit node does not know your IP (who you are) but it knows what you are connecting to. The exit node will, like the middle node, be chosen at random from the Tor nodes (if it runs with an exit flag).
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +The Encryption Tor will encrypt each packet three times, with each key in turn from the exit, middle and entry node in that order. Once Tor has built a circuit, browsing is done as follows:
> The Encryption Tor will encrypt

I'm not 100% sure what this is trying to say, but I took a shot at making it clearer.

It might also be helpful to include a popup on what a packet is. I feel like most people don't know what a packet is by name, but maybe I'm wrong.

```suggestion
The encryption method Tor uses will encrypt each packet three times. The encryption keys are derived from the exit, middle, and entry node—in that order.

Once Tor has built a circuit, browsing is done as follows:
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +1. When the packet arrives at the entry node the first layer of encryption is removed. In this encrypted packet it will find another encrypted packet with the middle node’s address. The entry node wi
```suggestion
1. When the packet arrives at the entry node, the first layer of encryption is removed. The entry node will see another encrypted packet with the middle node’s address, and, in turn, will forward it to the middle node.
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +2. When the middle node receives the packet from the entry node, it too will remove a layer of encryption with its key, and find an encrypted packet with the exit nodes address. The middle node will
```suggestion
2. When the middle node receives the packet from the entry node, it too will remove a layer of encryption with its key. The middle node will then see an encrypted packet with the exit node's address and forward it to the exit node.
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +3. When the exit node receives its packet, it will remove the last layer of encryption with its key, and find the destination address that the user wanted to connect to, and forward the packet to tha
```suggestion
3. When the exit node receives its packet, it will remove the last layer of encryption with its key. The exit node will see the destination address and forward the packet to that address.
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +Here is an alternative visualization of the process. Note how each node removes its own layer of encryption, and when the destination website returns data, the same process happens entirely in revers
```suggestion
Here is an alternative visualization of the process. Note how each node removes its own layer of encryption, and when the destination website returns data, the same process happens entirely in reverse. For example, the exit node does not know who you are, but it does know which node it came from, and so it adds its own layer of encryption and sends it back.
```

2022-05-13 22:33 UTC, lx-is commented on docs/how-tor-works.md
> +So what do we learn from this? Well we learn that Tor allows us to connect to a website without any single party knowing the entire path. The entry node knows who you are, but not where you are going
```suggestion
So, what do we learn from this? We learn that Tor allows us to connect to a website without any single party knowing the entire path. The entry node knows who you are, but not where you are going; the middle node doesn’t know who you are or where you are going; and the exit node knows where you are going, but not who you are. Because the exit node makes the connection, the destination website will never know who you are (your IP address).
```

2022-05-14 12:41 UTC, dngray commented
I think we should also make sure to link to https://tb-manual.torproject.org. I'm also not keen on duplicating too much of that either.

2022-05-15 14:01 UTC, blacklight447 commented
@dngray  yeah my focus for this page is mostly to give users a understanding of how tor works. Most users know how a vpn works, and that tor users a network of nodes, but most don't have a clue of how to really works. This page gives them an understanding in how tor protects your privacy.

2022-05-15 14:07 UTC, dngray commented
Fair enough, nobody merge this until we squash and change the author the original commit to you.

2022-05-16 00:02 UTC, flawedworld commented
copy+paste from matrix:

>add the tor threat model
>explain what it can and cannot do
>notably, explain how it isnt bulletproof, and its not a magic wand solution
>ex. outline that a global adversary with access to all global netflow could probably figure out what you are doing

and

>A page on operational security that ties into this should eventually be made as well
>Even if Tor fits your threat model, if you dox yourself, it ain't gonna be too useful

2022-05-16 00:35 UTC, d4rklynk commented
I think we should also explain the differences between Tor Browser and tor network

2022-05-25 18:51 UTC, jonaharagon requested changes

2022-05-25 18:51 UTC, jonaharagon commented on docs/basics/how-tor-works.md
> +</figure>
why do you keep adding images like this? lol
```suggestion
![Tor path](../assets/img/how-tor-works/tor-path.svg#only-light)
![Tor path](../assets/img/how-tor-works/tor-path-dark.svg#only-dark)
```

2022-05-25 18:51 UTC, jonaharagon commented on docs/basics/how-tor-works.md
> +</figure>
```suggestion
![Tor encryption](../assets/img/how-tor-works/tor-encryption.svg#only-light)
![Tor encryption](../assets/img/how-tor-works/tor-encryption-dark.svg#only-dark)
```

2022-05-26 03:07 UTC, dngray commented on docs/basics/how-tor-works.md
> +</figure>
> why do you keep adding images like this? lol

Because it centers it nicely.

2022-05-26 03:14 UTC, lx-is commented on docs/basics/how-tor-works.md
> +</figure>
@jonaharagon [blame mkdoc](https://squidfunk.github.io/mkdocs-material/reference/images/?h=centered#image-alignment)

2022-06-01 20:40 UTC, blacklight447 approved these changes

2022-06-01 22:47 UTC, jonaharagon approved these changes

2022-06-01 22:48 UTC, merged

2022-06-02 03:00 UTC, SkewedZeppelin commented
> If you share to much data

s/to/too/