Add account deletion page
privacyguides/privacyguides.org pull request #1224
Opened 2022-05-14 03:35 UTC by mfwmyfacewhen

Adding a guide on deleting old accounts.

Resolves: #1203

2022-05-14 04:01 UTC, lx-is requested changes

2022-05-14 04:01 UTC, lx-is commented on docs/security/account-deletion.en.md
> +It's an unfortunate fact that over time we will accumulate online accounts, many of which we may no longer use. Most people simply forget about them and leave them to rot; however, deleting your old
Here's my take on the beginning except. You can decide if you like it better or not

```suggestion
It can prove easy to accumulate a number of online accounts, but it can prove difficult to eventually delete any forgotten accounts. While deleting past accounts is an important step in reclaiming your privacy, it is often made difficult by [deceptive design](https://www.deceptive.design/) patterns.
```

2022-05-14 04:07 UTC, mfwmyfacewhen commented on docs/security/account-deletion.en.md
> +It's an unfortunate fact that over time we will accumulate online accounts, many of which we may no longer use. Most people simply forget about them and leave them to rot; however, deleting your old
I like "It can prove easy to accumulate a number of online accounts" bc I think keeping a positive tone is a good thing. I don't really want to say it's going to be difficult right at the start of the guide because I don't want people to get demoralized before they even start.

2022-05-14 04:14 UTC, lx-is commented on docs/security/account-deletion.en.md
> +It's an unfortunate fact that over time we will accumulate online accounts, many of which we may no longer use. Most people simply forget about them and leave them to rot; however, deleting your old
Excellent point. I edited it to make it sound more welcoming, if you'd like to take another look.

2022-05-14 04:19 UTC, mfwmyfacewhen commented on docs/security/account-deletion.en.md
> +It's an unfortunate fact that over time we will accumulate online accounts, many of which we may no longer use. Most people simply forget about them and leave them to rot; however, deleting your old
How about "It can prove easy to accumulate a number of online accounts,  many of which we may no longer use. Deleting unused accounts is an important step in reclaiming your privacy, as these often contain personal information. While [deceptive design](https://www.deceptive.design/) patterns can often introduce inconveniences along the way, this guide aims to navigate you through the process."

2022-05-14 04:28 UTC, lx-is commented on docs/security/account-deletion.en.md
> +It's an unfortunate fact that over time we will accumulate online accounts, many of which we may no longer use. Most people simply forget about them and leave them to rot; however, deleting your old
Each iteration keeps getting better lol.

How about:

> It can prove easy to accumulate a number of online accounts, many of which may no longer be useful. Deleting those past accounts is an important step in reclaiming your privacy, as dormant accounts are especially vulnerable. While [deceptive design](https://www.deceptive.design/) patterns can often introduce inconveniences along the way, this guide aims to navigate you through the account deletion process.

2022-05-14 04:30 UTC, mfwmyfacewhen commented on docs/security/account-deletion.en.md
> +It's an unfortunate fact that over time we will accumulate online accounts, many of which we may no longer use. Most people simply forget about them and leave them to rot; however, deleting your old
Nice

2022-05-15 08:25 UTC, dngray requested changes

2022-05-15 08:25 UTC, dngray commented on docs/security/account-deletion.en.md
> +It can be easy to accumulate a number of online accounts over time, many of which you may no longer use. Deleting these unused accounts is an important step in reclaiming your privacy, as dormant acc
I'd say we can elaborate here without using third party links to describe these things.

I'd elaborate and say data breaches do happen regularly and use https://haveibeenpwned.com/PwnedWebsites a reference to *how often* it occurs.

2022-05-15 08:25 UTC, dngray commented on docs/security/account-deletion.en.md
> +If you have a password manager that you've used for your entire digital life, this part will be very easy. You might not think you've had one, but many people used the password manager in their brows
Might mention tools like keepassxc 2.6 allow for [comprehensive reports](https://keepassxc.org/blog/2020-07-07-2.6.0-released/) to be checked with Have I Been Pwned [as does Bitwarden](https://bitwarden.com/help/reports/)

2022-05-15 08:25 UTC, dngray commented on docs/security/account-deletion.en.md
> +For the account email, either create a new burner email account via your provider of choice or create an alias using an [email aliasing service](/email/#email-aliasing-services). Do not use temporary
I think we can avoid mentioning specific products here.

2022-05-15 12:19 UTC, mfwmyfacewhen commented on docs/security/account-deletion.en.md
> +If you have a password manager that you've used for your entire digital life, this part will be very easy. You might not think you've had one, but many people used the password manager in their brows
Even the google password manager and the apple one have something like this so I might just mention it generally without talking about specific products, watchu think?

2022-05-15 13:53 UTC, dngray commented on docs/security/account-deletion.en.md
> +If you have a password manager that you've used for your entire digital life, this part will be very easy. You might not think you've had one, but many people used the password manager in their brows
Yeah that might be a better way to go about it, maybe show the Bitwarden one off because it has good documentation.

2022-05-15 17:07 UTC, blacklight447 approved these changes

2022-05-15 17:08 UTC, dngray approved these changes

2022-05-15 17:09 UTC, merged