Edit ubo to not recommend installing all filter lists
privacyguides/privacyguides.org pull request #1238
Opened 2022-05-15 18:15 UTC by mfwmyfacewhen

Recommend to only use UBO in its default configuration.

Resolves: #1237

2022-05-15 19:49 UTC, lx-is requested changes

2022-05-15 19:49 UTC, lx-is commented on docs/browsers.en.md
> +While synchronization of Safari History, Tab Groups, and iCloud Tabs uses E2EE, bookmarks sync does [not](https://support.apple.com/en-us/HT202303); they are only encrypted in transit and stored in a
```suggestion
Synchronization of Safari History, Tab Groups, iCloud Tabs, and saved passwords are E2EE. However, bookmarks are [not](https://support.apple.com/en-us/HT202303). Apple can decrypt and access them in accordance with their [privacy policy](https://www.apple.com/legal/privacy/en-ww/).
```

2022-05-15 19:49 UTC, lx-is commented on docs/browsers.en.md
> +    Additional filter lists do slow things down and may increase your attack surface, so only apply what you need. If there is a vulnerability in uBlockOrigin, third party filters can provide malicio
```suggestion
    Additional filter lists do slow things down and may increase your attack surface, so only apply what you need. If there is a vulnerability in uBlock Origin, third party filters can provide malicious rules to exploit it.
```

2022-05-15 19:51 UTC, lx-is commented on docs/browsers.en.md
> +    We suggest leaving the extension in its default configuration, as extra filter lists can add additional [attack surface](https://portswigger.net/research/ublock-i-exfiltrate-exploiting-ad-blocker
Would it be good to mention the uBO's [blocking modes](https://github.com/gorhill/uBlock/wiki/Blocking-mode)?

2022-05-15 21:17 UTC, mfwmyfacewhen commented on docs/browsers.en.md
> +    We suggest leaving the extension in its default configuration, as extra filter lists can add additional [attack surface](https://portswigger.net/research/ublock-i-exfiltrate-exploiting-ad-blocker
There's no mention of this in the actual ui so I don't see a point, it will probably just confuse people.

2022-05-16 05:06 UTC, Lostname777 commented
What do you think about enabling "uBlock filters – Annoyances" under annoyances column as it is an ublock filter but not enabled by default.

2022-05-16 08:09 UTC, blacklight447 approved these changes

2022-05-16 15:13 UTC, merged