Add article about erasing data securely
privacyguides/privacyguides.org pull request #1256
Opened 2022-05-17 01:05 UTC by mfwmyfacewhen

Add an article about how to erase data securely.

Resolves: #1120

2022-05-17 05:17 UTC, dngray commented
I think for this one there are two main tools to suggest. [nwipe](https://en.wikipedia.org/wiki/Nwipe) for magnetic disks, and [Secure ATA erase](https://ata.wiki.kernel.org/index.php/ATA_Secure_Erase).

The second one might would be cool if we could show some screenshots from a BIOS menu as an example.

2022-05-17 07:47 UTC, d4rklynk commented
There is the shred command in Linux for HDD

2022-05-17 09:21 UTC, dngray commented
> There is the shred command in Linux for HDD

The only thing that should be mentioned is that `shred` does not work very wall/at all for journaled/CoW filesystems, see https://en.wikipedia.org/wiki/Shred_(Unix)#Limitations

2022-05-17 14:53 UTC, EdwardLangdon requested changes

2022-05-17 14:53 UTC, EdwardLangdon commented on docs/basics/erasing-data.md
I think that, Using FDE and Wiping it normally would do that thing. If you also state, How to clear the Keys from Device's Memory.

2022-05-17 19:48 UTC, mfwmyfacewhen commented on docs/basics/erasing-data.md
Can you elaborate? Not sure what you mean.

2022-05-18 04:34 UTC, lx-is submitted a review, later dismissed
I think it would be helpful to have a very brief paragraph on why SSDs and HDDs require different file removal options. The individual files section briefly covers it, but there should also be some dedicated info at the top of the article.

Overall though looks really good from what I can tell

2022-05-18 04:34 UTC, lx-is commented on docs/basics/erasing-data.md
> +##:material-harddisk-remove:Erasing Your Entire Drive
Not sure if I'm a fan of the icons in the headers. Looks a little funky imo and isn't consistent with the rest of the site

2022-05-18 04:34 UTC, lx-is commented on docs/basics/erasing-data.md
> +For an unencrypted drive, pressing ++del++ on a file isn't enough; this will tell the drive to allow this space to be overwritten, but the data will still be there. You don't know when the data will
```suggestion
For an unencrypted drive, simply emptying your recycle bin isn't enough—this will allow the drive to overwrite the data, but until it does the data will still be there. You don't know when the data will be overwritten, or even if it will at all. To ensure your files cannot be recovered, you will need to follow these steps:
```

2022-05-18 04:34 UTC, lx-is commented on docs/basics/erasing-data.md
> +For an **HDD**, we recommend you use `nwipe`. Install [Balena Etcher](https://www.balena.io/etcher/) and make sure you have a usb flash drive (it will be wiped so make sure there aren't any important
You should provide some more information on what nwipe is. Starter example:

> nwipe is a program that will securely erase the entire contents of disks. It can wipe a single drive or multiple disks simultaneously and can operate as both a command line tool or with a basic GUI.

and nice use of the ++ it looks good.

It might also be better to split up the instructions instead of having it all in a blob of a paragraph.

2022-05-18 05:52 UTC, subatomic-honda-civic commented on docs/basics/erasing-data.md
> +##:material-harddisk-remove:Erasing Your Entire Drive
Yeah looks a bit out of place

2022-05-19 08:27 UTC, elitejake requested changes

2022-05-19 08:27 UTC, elitejake commented on docs/basics/erasing-data.md
> +For an unencrypted drive, pressing ++del++ on a file isn't enough; this will tell the drive to allow this space to be overwritten, but the data will still be there. You don't know when the data will
Using a more proper term. Not too advanced for naïve users, I hope.
```suggestion
For an unencrypted drive, pressing ++del++ on a file isn't enough; this will tell the filesystem to allow this space to be overwritten, but the data will still be recoverable. You don't know when the data will be overwritten, or even if it will at all. To ensure your files cannot be recovered, you will need to follow these steps:
```

2022-05-19 08:27 UTC, elitejake commented on docs/basics/erasing-data.md
> +    The data on your drive will not be recoverable. You should make sure you have any files you need backed up before performing this action!
I think this is fairly obvious and this warning is not needed.

2022-05-19 17:55 UTC, jonaharagon commented on docs/basics/erasing-data.md
> +![Example of UEFI Settings](../assets/img/erasing-data/uefi.png)
I'm not convinced this is the most helpful screenshot for people here. A screenshot of the ShredOS interface after booting to it might make more sense, as well as additional pointers as to what onscreen prompts people should click (unless it really is dead obvious, I haven't looked)

2022-05-20 12:56 UTC, mfwmyfacewhen commented on docs/basics/erasing-data.md
> +![Example of UEFI Settings](../assets/img/erasing-data/uefi.png)
Yeah agree

2022-05-20 15:17 UTC, mfwmyfacewhen commented on docs/basics/erasing-data.md
> +![Example of UEFI Settings](../assets/img/erasing-data/uefi.png)
I think it's fairly obvious what to do once you boot into it though.

2022-05-21 04:56 UTC, mfwmyfacewhen commented
> These probably should link back to the article:
> 
> https://www.privacyguides.org/linux-desktop/#drive-encryption
> 
> > When securely erasing storage devices such as a Solid-state drive (SSD) you should use the ATA Secure Erase command. This command can be issued from your UEFI setup. If the storage device is a regular hard drive (HDD), consider using `nwipe`.

If anything that should probably be edited to link back to my guide.

2022-05-25 04:43 UTC, dngray commented
> When securely erasing storage devices such as a Solid-state drive (SSD) you should use the [ATA Secure Erase](https://ata.wiki.kernel.org/index.php/ATA_Secure_Erase) command. This command can be issued from your UEFI setup
screen although instructions do vary. If the storage device is a regular hard drive (HDD), consider using [`nwipe`](https://en.wikipedia.org/wiki/Nwipe).

Was mentioned in https://github.com/privacyguides/privacyguides.org/pull/1307. I don't really want to mention it in multiple places, so we might add that to this article.

2022-05-25 07:05 UTC, dngray commented
I removed the thing about SLC drives, and just referred to that as "caching" because it isn't the only kind of caching that exists.

Additionally most consumer drives are TLC/MLC type anyway.

2022-05-25 08:02 UTC, tommytran732 approved these changes

2022-05-25 08:06 UTC, dngray approved these changes

2022-05-25 08:08 UTC, merged