TM Example
privacyguides/privacyguides.org pull request #1310
Opened 2022-05-24 03:12 UTC by dngray

A few things I noticed, that I didn't have a chance to review, and a threat model example.

2022-05-24 03:12 UTC, dngray commented
One thing I did notice is that acronyms like `TPM` don't seem to be showing the abbreviation.

2022-05-24 04:00 UTC, lx-is commented
> One thing I did notice is that acronyms like `TPM` don't seem to be showing the abbreviation.

I think I recall Jonah saying he wants to avoid putting privacy or security terms in the abbreviations file, opting to describe them directly on the page instead. I can't remember where he said this though since it's not in the style guide.

2022-05-24 12:47 UTC, mfwmyfacewhen approved these changes

2022-05-24 13:42 UTC, blacklight447 approved these changes

2022-05-24 13:50 UTC, jonaharagon requested changes
smh @ people approving PRs without reviewing what they actually look like.

2022-05-24 13:50 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +Security and privacy are often conflated, because you need security to obtain any semblance of privacy: Using tools which appear private is futile if they could easily be exploited by attackers to re
I wouldn't make this change, I'm not sure what it adds to the article outside of unnecessary over-explanation.
```suggestion
Security and privacy are often conflated, because you need security to obtain any semblance of privacy: Using tools which appear private is futile if they could easily be exploited by attackers to release your data later. However, the inverse is not necessarily true; the most secure service in the world *isn't necessarily* private. The best example of this is trusting data to Google, who, given their scale, have had minimal security incidents by employing industry-leading security experts to secure their infrastructure. Even though Google provides a very secure service, very few would consider their data private in their hands.
```

2022-05-24 13:50 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +If you are concerned about **physical attacks** you should use an operating system with a secure verified boot implementation, such as Android, iOS, macOS, [Windows (with TPM)](https://docs.microsoft
Need to check the accuracy of this, AFAIK Windows does not have a secure verified boot implementation (for a number of reasons, probably most importantly because Microsoft has signed shims that allow the loading of any operating system).

2022-05-24 13:50 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +Best doesn't always necessarily mean a person is after an infallible solution with dozens of conditions, these solutions are often difficult to work with realistically, for the reason we said above,
```suggestion
Finding the "best" solution for yourself doesn't always necessarily mean you are after an infallible solution with dozens of conditions, these solutions are often difficult to work with realistically. As we discussed previously, security often comes at the cost of convenience. Below we provide some tips:
```

2022-05-24 13:50 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +    If buying an item the use of a [parcel locker](https://en.wikipedia.org/wiki/Parcel_locker) may help keep your physical address private.
```suggestion
1. **Known identity** - A known identity is used for things where you must declare your name. There are many such legal documents and contracts where a legal identity is required. This could range from opening a bank account, signing a property lease, obtaining a passport, a customs declaration when importing an item or otherwise dealing with your Government. These things will usually always lead back credentials such as credit cards, credit rating checks, account numbers and possibly physical addresses.

   We don't suggest using a VPN or Tor for any of these things as your identity is already known through other means.

   !!! tip
       If buying an item the use of a [parcel locker](https://en.wikipedia.org/wiki/Parcel_locker) may help keep your physical address private.
```

2022-05-24 13:50 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +You may wish to use a VPN for this to mask your IP address. Financial transactions are more difficult and for this we'd suggest using anonymous cryptocurrencies such as Monero. Employing alt-coin shi
```suggestion
2. **Unknown identity** - An unknown identity could be a stable pseudonym that you regularly use. It is not anonymous because it doesn't change. If you're a part of an online community you may wish to retain persona that others know. The reason this is not anonymous is because if monitored over a period of time details about the owner may reveal further information, such as the way they write (lingustics), general knowledge about topics of interest etc.

   You may wish to use a VPN for this to mask your IP address. Financial transactions are more difficult and for this we'd suggest using anonymous cryptocurrencies such as Monero. Employing alt-coin shifting may also help disguise where your currency originated. Typically exchanges require KYC (know your customer) to be completed before they will allow you to exchange fiat currency into any kind of cryptocurrency. Local meet-up options may also be a solution, however those often are more expensive and sometimes also require KYC.
```

2022-05-24 13:50 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +Using Tor can help with this, it's also worth noting greater anonymity is possible through asynchronous (not real time communication). Real time communication is vulnerable to typing analysis pattern
```suggestion
3. **Anonymous identity** - Anonymous identities are difficult to maintain over long periods of time for even the most experienced. They should be short-term and short lived identities which are rotated regularly.

   Using Tor can help with this, it's also worth noting greater anonymity is possible through asynchronous (not real time communication). Real time communication is vulnerable to typing analysis patterns more than a slab of text distributed on a forum, email) etc that you've had time to think about, maybe even put through a translator and back again.
```

2022-05-24 19:45 UTC, lx-is reviewed
I think this "Complicated is better" misconception should be the first one listed, given it's probably the most important.

2022-05-28 05:46 UTC, dngray commented on docs/basics/common-threats.en.md
> +Security and privacy are often conflated, because you need security to obtain any semblance of privacy: Using tools which appear private is futile if they could easily be exploited by attackers to re
> I wouldn't make this change, I'm not sure what it adds to the article outside of unnecessary over-explanation.

The point that I am stressing there is that not all Google products are equal and they have different Privacy Policies.

2022-06-01 22:52 UTC, jonaharagon approved these changes

2022-06-01 23:03 UTC, merged