Add Windscribe
privacyguides/privacyguides.org pull request #1312
Opened 2022-05-24 10:16 UTC by dngray

Progression of the discussion at https://github.com/privacyguides/privacyguides.org/discussions/372#discussioncomment-1691190

2022-05-24 10:33 UTC, blacklight447 commented
Does windscribe pass our criteria?

2022-05-24 11:43 UTC, dngray commented
> Does windscribe pass our criteria?

Yes.

2022-05-24 13:36 UTC, blacklight447 commented
Just checked it all, seems to be good to go.

2022-05-29 06:54 UTC, Dyrimon commented on docs/vpn.en.md
> +??? check "Independently Audited"
There should be a link to the audit report and details of the audit

2022-05-29 06:55 UTC, Dyrimon commented on docs/vpn.en.md
> +    In addition to accepting credit/debit cards and PayPal, Windscribe accepts Bitcoin as payment.
Description doesn't explain if they accept Cash/Moneo or not

2022-05-29 06:56 UTC, Dyrimon commented on docs/vpn.en.md
> +
I guess there are no additional functionality? Maybe mention R.O.B.E.R.T

2022-05-29 06:56 UTC, Dyrimon requested changes
I've left my opinions on comments

2022-05-30 03:23 UTC, dngray commented
Yes, this one is an early draft, nowhere near finished.

2022-06-01 12:51 UTC, EdwardLangdon commented
I think @yegors could help us out here.

2022-06-02 01:48 UTC, jonaharagon commented on docs/vpn.en.md
> +    We also think it's better for the security of the VPN provider's private keys if they use [dedicated servers](https://en.wikipedia.org/wiki/Dedicated_hosting_service), instead of cheaper shared s
Why do we say this in the countries admonition of every provider? It doesn't even make sense in this context?

2022-06-02 05:20 UTC, dngray commented on docs/vpn.en.md
> +    We also think it's better for the security of the VPN provider's private keys if they use [dedicated servers](https://en.wikipedia.org/wiki/Dedicated_hosting_service), instead of cheaper shared s
It was something that was always there. Not sure it makes a lot of sense no.

2022-08-19 08:38 UTC, purtual requested changes

2022-08-19 13:42 UTC, yegors commented
Just FYI, Windscribe is now running on a RAM-disk based infrastructure. We silently finished the deployment of this last week to  99% of servers.  

Expect a detailed writeup on how it works in the coming weeks. Audit has been scheduled for end of November by Cure53 (earliest they could do).

2023-03-02 17:32 UTC, jonaharagon commented
@yegors last update we've heard was that an audit was scheduled for Nov 2022, and before that it was June 2022; has any progress been made on this front?

https://rus.windscribe.com/knowledge-base/articles/has-windscribe-been-audited says your desktop and mobile apps have been audited, which would be great if those were published.

2023-03-02 17:40 UTC, yegors commented
@jonaharagon We did indeed conduct a **pre-production** audit of our new infrastructure in Dec of 2022. As this stack is not yet in production, publishing it is pointless. Once 2.0 stack is actually deployed, the results of this audit and a new production audit will be published. 

Our Android source code has been made public as well: https://github.com/Windscribe/Android-App

iOS will follow in a several weeks. 

The code audits for Desktop, iOS and Android were done a while ago, ahead of open sourcing. We may link them in the relevant repos soon.

2023-03-02 17:47 UTC, jonaharagon commented
Thanks @yegors, good to hear! I think we are *most* concerned about the code audits for your clients, which it sounds like are already completed anyways? When those are published I would be fine with merging this PR and adding Windscribe to the site, and then publishing your infrastructure updates/audits as a future update.

2023-03-04 11:34 UTC, jermanuts commented
Thanks @yegors for listening to PG's feedback. I hope you [fix](https://github.com/Windscribe/Desktop-App) mirroring bug. Also, there are 2 protocols (WStunnel and Stealth) are they open source?

2023-05-25 19:08 UTC, yegors commented
> Thanks @yegors for listening to PG's feedback. I hope you [fix](https://github.com/Windscribe/Desktop-App) mirroring bug. Also, there are 2 protocols (WStunnel and Stealth) are they open source?

What mirroring bug are you referring to? The fact that Github was behind what's actually released? yeah, we addressed that. 

As for WStunnel/Stunnel, everything is open sourced, including those 2 projects themselves

https://github.com/erebe/wstunnel
https://www.stunnel.org/

2024-04-21 11:27 UTC, freddy-m commented
What is the status of this @dngray @privacyguides/team?

2024-05-24 03:52 UTC, jonaharagon commented
This is going on 2 years this weekend. Closing since nothing has changed, we can reopen if it's ever actually ready.

2024-05-24 03:52 UTC, closed without merging

2024-07-11 00:58 UTC, IkelAtomig commented
https://blog.windscribe.com/freshscribe-next-generation-vpn-infrastructure-2/ - Time to reopen, I guess.