Fixes for the Linux Page
privacyguides/privacyguides.org pull request #1331
Opened 2022-05-25 20:53 UTC by tommytran732

I don't like polarbears. 

On a serious note though, the without the last sentence, the GRSecurity part sounds weird. As for the LKRG kernel module, the point here is not that it is available on KickSecure, the point here is that if you use Debian you should just add the KickSecure repo and install it since it is fairly easy anyways. Same for Arch and possibly Fedora in the future.

I also updated the mountpoint hardening section since `noexec` on /home and /root breaks a lot of stuff.

2022-05-25 20:58 UTC, blacklight447 approved these changes

2022-05-26 03:04 UTC, dngray requested changes

2022-05-26 03:04 UTC, dngray commented on docs/linux-desktop/hardening.en.md
> +GRSecurity is a set of kernel patches that attempt to improve security of the Linux kernel.  It requires [payment to access]((https://github.com/QubesOS/qubes-issues/issues/5461) the code. If you hav
> If you have access to GRSecurity, it is recommended that you use it.

I kinda want to avoid writing "if you can do this do it", everywhere because it is superfluous. It is implied by the fact it is on our hardening page.

The hardening guide was never intended to be a "you must do all these things or else" kind of language, the reason is because the vast majority won't, and that's fine, hardening systems is often a lot of work and requires continued maintenance and effort.

2022-05-26 03:55 UTC, hook9 requested changes
GRSecurity should be in a separate discussion/PR in my opinion.

2022-05-27 03:19 UTC, dngray approved these changes

2022-05-27 03:20 UTC, merged