add grid layout to download links
privacyguides/privacyguides.org pull request #1349
Opened 2022-05-28 18:35 UTC by noClaps

Updated download links

Resolves: # 

- Added text to download links
- Now uses grid layout

2022-05-28 18:39 UTC, jonaharagon requested changes
Plus we'll have to go through and do the rest of the pages.

2022-05-28 18:39 UTC, jonaharagon commented on docs/cloud.en.md
> +        [:fontawesome-brands-app-store-ios: App Store](https://apps.apple.com/app/id1125420102){ .card-link title=App Store }
```suggestion
        [:fontawesome-brands-windows: Windows](https://nextcloud.com/install/#install-clients)
        [:fontawesome-brands-apple: macOS](https://nextcloud.com/install/#install-clients)
        [:fontawesome-brands-linux: Linux](https://nextcloud.com/install/#install-clients)
        [:fontawesome-brands-freebsd: FreeBSD](https://www.freshports.org/www/nextcloud)
        [:pg-openbsd: OpenBSD](https://openports.se/www/nextcloud)
        [:pg-netbsd: NetBSD](https://pkgsrc.se/www/php-nextcloud)
        [:fontawesome-brands-google-play: Google Play](https://play.google.com/store/apps/details?id=com.nextcloud.client)
        [:pg-f-droid: F-Droid](https://f-droid.org/packages/com.nextcloud.client)
        [:fontawesome-brands-app-store-ios: App Store](https://apps.apple.com/app/id1125420102)
```

2022-05-28 18:39 UTC, jonaharagon commented on docs/cloud.en.md
> +        [:pg-netbsd: NetBSD](https://tahoe-lafs.readthedocs.io/en/latest/Installation/install-tahoe.html#linux-bsd-or-macos){ .card-link title=NetBSD }
```suggestion
        [:fontawesome-brands-windows: Windows](https://tahoe-lafs.readthedocs.io/en/latest/Installation/install-tahoe.html#microsoft-windows)
        [:fontawesome-brands-apple: macOS](https://tahoe-lafs.readthedocs.io/en/latest/Installation/install-tahoe.html#linux-bsd-or-macos)
        [:fontawesome-brands-linux: Linux](https://tahoe-lafs.readthedocs.io/en/latest/Installation/install-tahoe.html#linux-bsd-or-macos)
        [:pg-netbsd: NetBSD](https://tahoe-lafs.readthedocs.io/en/latest/Installation/install-tahoe.html#linux-bsd-or-macos)
```

2022-05-29 06:00 UTC, noClaps commented on docs/cloud.en.md
> +        [:fontawesome-brands-app-store-ios: App Store](https://apps.apple.com/app/id1125420102){ .card-link title=App Store }
I think you'll need the `{.card-link}` since the CSS refers to it. The `title=" "` can be removed though.

2022-06-01 09:08 UTC, closed without merging

2022-06-01 12:39 UTC, dngray commented
You know you can sync, https://help.github.com/articles/syncing-a-fork/

2022-06-01 14:10 UTC, noClaps commented
I tried that, but it kept giving me errors and not working, so after a while I just gave up and re-did the whole thing. Sorry, I'm not very good with git and working with forks.

2022-06-01 15:31 UTC, dngray commented
i tend to find i have less issues with `git rebase main` than `git merge`. Rebase "re-plays" your changes on top of the main repo.

Of course if there's been major changes you'll get merge conflicts that need to be resolved first, before you can `git rebase --continue`.

2022-06-01 15:55 UTC, noClaps commented
The thing is, after my changes, the entire directory structure was changed, and the files I was working on were moved. For instance, `extra.css` was moved from `docs/stylesheets/extra.css` to `docs/assets/stylesheets/extra.css`, so doing `git rebase` wouldn't help since the file on which I'm "re-playing" changes doesn't exist at that location anymore.

Honestly, there probably was a way I could have done it, but remaking the fork and PR just seemed a lot easier.