Minify HTML & CSS
privacyguides/privacyguides.org pull request #1351
Opened 2022-05-28 19:00 UTC by jonaharagon

Closes #1343

2022-05-28 19:08 UTC, 27lx commented on mkdocs.yml
> +          - assets/stylesheets/extra.css
```suggestion
          - assets/stylesheets/extra.css
          - overrides/home.css
```

2022-05-28 19:18 UTC, jonaharagon commented on mkdocs.yml
> +          - assets/stylesheets/extra.css
Minifying this file breaks the homepage for some reason.

2022-05-29 05:43 UTC, dngray requested changes
I spotted a bug with the downloads button.

Before:

![3764658777](https://user-images.githubusercontent.com/48640805/170854041-f2f549d1-9449-4d40-91b0-aee4f73eae34.png)

After:

![287626374](https://user-images.githubusercontent.com/48640805/170854045-0f95ca4b-d62a-437a-88a7-a809824b2d0d.png)

2022-05-29 17:19 UTC, jonaharagon commented
Oh, that is the same issue we had with minifying the homepage CSS. I don't think we'll be able to minify CSS in this PR then, only HTML. I'll push a change later.

2022-05-29 17:53 UTC, dngray approved these changes

2022-05-29 17:53 UTC, merged