Add Windows Guide
privacyguides/privacyguides.org pull request #1380
Opened 2022-06-02 14:02 UTC by EdwardLangdon

Resolves: #166 

Currently Added choosing edition, post-installation, And using FDE.

To-Do :

- [ ] Write about changing settings via settings app that are better for Privacy and Security
- [ ] Add Group Policy Edits that reduce Telemtry increase Secuirty and Privacy
- [ ] Do's and Dont's that increase attack surface

2022-06-02 14:49 UTC, kigoh1 commented
Good resources:
https://github.com/beerisgood/Windows11_Hardening
https://hardenwindows11forsecurity.com/

2022-06-05 09:43 UTC, EdwardLangdon commented
I need to add What are the issues present in Windows and some references for it.

I would like to talk more about pros and cons of Windows as compared to other OSes like macOS, GNU/Linux, BSD, etc., and why. But I am an avid windows user from start and don't have a bigger taste over other OSes. So, Enlighten me here.

cc @noClaps

2022-06-05 14:10 UTC, EdwardLangdon commented
This PR will be ready within a month and be complete about 70% within a couple of weeks.

Just need some resources and Guides. If anybody could make the Windows Issue popular on Reddit, I might think of adding more info by the redditors comment.

@dngray Don't rebase again. Please. I will ask you to do so, When I am ready.

2022-06-09 08:32 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Only use your account for you, if someone needs to use your computer **ALWAYS** create another standard account, even if it's for a one-time use, even if it's your family or someone you trust. This
```suggestion
- Only use your account for you, if someone needs to use your computer **ALWAYS** create another standard account, even if it's for a one-time use, even if it's your family or someone you trust. This person can plug a malicious USB, can connect to malicious Wi-Fi network, download infectious file, etc... without you knowing about it.
```

2022-06-09 08:49 UTC, d4rklynk commented on docs/windows/hardening.md
> +    You should ALWAYS do the quick shortcut ++win+l++ to lock your device when your away to prevent Unautorized access.
```suggestion
    You should ALWAYS do the quick shortcut ++win+l++ to lock your device when you are away to prevent unauthorized access.
```

2022-06-09 08:49 UTC, d4rklynk commented on docs/windows/hardening.md
> +        Disable automatic Sample Submission in Windows defender Settings as Windows defender will send your files as a samples for Signature Database and might leak your data.
```suggestion
        Disable automatic Sample Submission in Windows defender Settings as Windows defender will send your files as a samples for Signature Database and might leak your data.
        **Enable** the Group Policy `Computer Configuration > Administrative Templates > Windows Components > Microsoft Defender Antivirus > MAPS > Send file samples when further analysis is required to Never Send.`
```

2022-06-09 08:49 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Create another `administrator` account and change your current account to a `standard` user account to reduce the attack surface enormously as Most vulnerabilities today come from the fact that the
```suggestion
- Create another `administrator` account and change your current account to a `standard` user account to reduce the attack surface enormously as most vulnerabilities today come from the fact that the user is always in `administrator` mode.
```

2022-06-09 13:40 UTC, EdwardLangdon commented
I am busy in real life. After June 22, I will be back working on this PR with Further research by actively investigating things deeply about Windows and This PR will be updated rapidly within the end of this month.

In the meantime, You are welcome to submit PRs to my Branch or add more resource or content to the actual issue. So, I will investigate and write on my own.

2022-06-17 05:37 UTC, tommytran732 commented
> However, it has own privacy and security issues.

Either elaborate or remove this sentence. When I say Linux is insecure, I have to prove it. Same thing here.

> We recommend you choose Windows 11 over Windows 10 as it is the latest version, and brings many security-related improvements with it. Windows 10 will stop getting updates after [October 14, 2025](https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro).

Stress that the user should **at least** get Pro, because home's device encryption uploads the key to M$ server, doesn't have preboot auth (I could be wrong on this one so double check), and no group pol access.

Also stress that custom windows builds, especially AME are to be avoided at all cost.

> Both the Enterprise and Education Edition can be installed using the ISO provided by Microsoft for Installing Windows. But activating them is different because for Enterprise Edition it needs to be a part of an Enterprise Network & for Education Edition it needs to be managed by a School Administrator. It's better you find a way on your own about activation.

How about linking them to a reller and telling them to buy 1 windows license + 4 other cheap products?

> This guide will be mostly focused on Windows 11 but you can apply this to Windows 10 too as both share the same at the Source code just differences in UI.

Objectively false. Delete this.

> "Microsoft is pushing users to use Microsoft accounts for other editions except Education and Enterprise after installation. But you can bypass it by searching for guides online."

Link the guide or a video.

> While setting up, it is recommended to use a generic names such as user and host and avoid identifying terms such as your name or operating system. This can make it more difficult for privileged Win32 apps or attackers to discern your identity.

False. The default user is ADMINISTRATOR, which is already set. The host name is DESKTOP-SOMETHING, not `host`. Also, the DESKTOP-SOMETHING part is randomly generated, so maybe we could recommend a common value to set to. IDK if thats a good idea cuz only a few PG readers will do it anyways, so its something to consider.

> It is recommended to use only the Control Panel because if you go to encrypt via Settings, Microsoft designed it in a way that the encryption keys for BitLocker would be stored on Microsoft's server which is attached to your Micrsoft account. This can be dangerous to your privacy and security as Microsoft could easily view your encrypted files, as could an attacker if they were able to gain access to Microsoft's servers or any Law Enforcement could by a Gag order.

The thing that auto uploads to MS server is windows home's "device encryption", not Bitlocker. We edit the group pol cuz we wanna add the PIN unlock, as we dont want the TPM to just auto release the secret at boot.

> Make sure you store it in a safe place, such as a password manager, and keep backups of your Recovery Key. 

Recommend an encrypted USB disk instead.

> Set UAC Settings to maximum by just search for User Account Control in Windows Search, Enter set the slider to the top.

Actually links to Microsoft docs and recommend what to switch here. There are a bunch of options to choose from. Some are nuanced.

> Only use your account for you, if someone needs to use your computer ALWAYS create another standard account, even if it's for a one-time use, even if it's your family or someone you trust. This person can plug an malicious USB, can connect to malicious Wi-Fi Netowrk, download infectious file, etc... without you knowing about it.

Should probably copy this to Linux for consistency ngl.

2022-06-19 10:34 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +*[FDE]: Full Disk Encryption
I will check the Privacy Section manually and add it later.

2022-06-19 11:01 UTC, d4rklynk requested changes

2022-06-19 11:01 UTC, d4rklynk commented on docs/windows/hardening.md
> +    It is recommended to use only the Control Panel because if you go to encrypt via Settings, Microsoft named it as `Device Encryption` and designed it in a way that the encryption keys for BitLocke
```suggestion
    It is recommended to use only the Control Panel because if you go to encrypt via the settings app, Microsoft named it as `Device Encryption` and designed it in a way that the encryption keys for BitLocker would be stored on Microsoft's server which is attached to your Micrsoft account. This can be dangerous to your privacy and security as Microsoft could easily view your encrypted files, as could an attacker if they were able to gain access to Microsoft's servers or any Law Enforcement could by a Gag order. 
```

2022-06-19 11:01 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Set [UAC](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings) Settings to the [Highest Privelege](https://suppo
```suggestion
- Set [UAC](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-security-policy-settings) settings to the [Highest Privelege](https://support.microsoft.com/en-us/windows/about-user-account-control-settings-d5b2046b-dcb8-54eb-f732-059f321afe18).
```

2022-06-19 11:01 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Enable [Memory Integrity](https://support.microsoft.com/en-us/windows/core-isolation-e30ed737-17d8-42f3-a2a9-87521df09b78) (also called Hypervisor-Protected Code Integrity) in Windows Defender Sett
```suggestion
- Enable [Memory Integrity](https://support.microsoft.com/en-us/windows/core-isolation-e30ed737-17d8-42f3-a2a9-87521df09b78) (also called Hypervisor-Protected Code Integrity) in Windows Defender settings.
```

2022-06-19 11:01 UTC, d4rklynk commented on docs/windows/hardening.md
> +    Just Open the File Explorer's Settings and change it to show File Extensions by clicking on `View` > `Show`
```suggestion
    Just Open the File Explorer's settings and change it to show File Extensions by clicking on `View` > `Show`
```

2022-06-19 13:53 UTC, d4rklynk requested changes

2022-06-19 13:53 UTC, d4rklynk commented on docs/windows/hardening.md
> +
```suggestion
After enabling these policies, you need to create your PIN by opening **Windows Terminal** as an **administrator**.
You can copy paste `manage-bde -protectors -add c: -TPMAndPIN` and it will prompt you to enter a new PIN.
You can check if it's enabled by typing `manage-bde -status`. It will normally show in **Key Protectors** : Numerical Password (it's the recovery key) and TPM And PIN.

!!! info
If you want to disable pre-boot PIN requirements. Set the 2 policies we did to **Not configured**, open **Windows Terminal** as an administrator and copy/paste this command `manage-bde -protectors -add c: -TPM`. You can again check if it worked by typing `manage-bde -status c:` and it will show you **Numerical Password** and **TPM**
```

2022-06-19 14:30 UTC, d4rklynk requested changes

2022-06-19 14:30 UTC, d4rklynk commented on docs/windows/hardening.md
> +You can check if it's enabled by typing `manage-bde -status`. It will normally show in **Key Protectors** : Numerical Password (it's the recovery key) and TPM And PIN.
```suggestion
You can check if it's enabled by typing `manage-bde -status`. It will normally show in **Key Protectors** : **Numerical Password** (it's the recovery key) and **TPM And PIN**.
```

2022-06-24 16:25 UTC, dngray commented
We might consider incorporating https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-countermeasures#attacker-with-skill-and-lengthy-physical-access into this, as a possible recommendation

2022-06-29 16:02 UTC, noClaps requested changes

2022-06-29 16:02 UTC, noClaps commented on docs/windows/privacy.md
> +You should rather login to that specific app if you need that only.
Change to:
> You should log in to that specific app only if you need to.

or:
> You should only log in to that specific app if you need to.

or:
> You should log in only to that specific app if you need to.

Any one of those would work here, depending on which one you mean to say.

Also, explain or link to an explanation of what a dark pattern is.

2022-06-29 16:09 UTC, noClaps commented on docs/windows/hardening.md
> +    From : [beerisgood](https://github.com/beerisgood/Windows11_Hardening/blob/master/always%20display%20file%20typ%20extension)
Missed this earlier, but you can make the title of the container a link by using:
```markdown
!!! example "[Source: beerisgood](https://github.com/beerisgood/Windows11_Hardening/blob/master/always%20display%20file%20typ%20extension)"
    <enter text here>
```
or something similar.

2022-06-30 02:01 UTC, EdwardLangdon commented on docs/windows/overview.md
> +We recommend you choose Windows 11 over Windows 10 as it is the latest version, and brings many security-related improvements with it by default such as Secure Boot, VBS, HVCI, etc. Windows 10 will s
I have added Abbreviation, Admonitions at last. Perhpas, It would be right. I think.

2022-06-30 02:02 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +    From : [beerisgood](https://github.com/beerisgood/Windows11_Hardening/blob/master/always%20display%20file%20typ%20extension)
Explain about the first one.

2022-06-30 04:46 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +    It is recommended to stick to Driver Updates given via Optional Updates as it is thoroughly vetted by Microsoft for Stability of your Device not rely on third Party apps for updating. So that, yo
I am gonna add yours. It is better.

2022-06-30 04:48 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +    To get know about information about updates that arrive monthly. It is recommended that you follow [Windows Latest](https://windowslatest.com).
I never knew it existed. Thanks.

2022-06-30 05:00 UTC, noClaps commented on docs/windows/overview.md
> +We recommend you choose Windows 11 over Windows 10 as it is the latest version, and brings many security-related improvements with it by default such as Secure Boot, VBS, HVCI, etc. Windows 10 will s
I was suggesting it because it would save readers having to manually search for it and potentially finding incorrect information. If we link to the documentation directly then there's no risk of that.

2022-06-30 05:08 UTC, EdwardLangdon commented on docs/windows/overview.md
> +We recommend you choose Windows 11 over Windows 10 as it is the latest version, and brings many security-related improvements with it by default such as Secure Boot, VBS, HVCI, etc. Windows 10 will s
I could do that. But the Admonitions doesn't work which I added at last in my local build. What do you think ?

2022-06-30 05:32 UTC, noClaps requested changes

2022-06-30 05:32 UTC, noClaps commented on docs/windows/overview.md
> +While using Windows it is better to select either Windows **Enterprise** Edition or **Education** Edition because it gives more control over hardening it for privacy and security by giving refined ac
`Diagnostic` -> `diagnostic`

2022-06-30 05:32 UTC, noClaps commented on docs/windows/privacy.md
> +You should never sign-in to Windows with a Microsoft account. Signing-in to applications like Microsoft Office (which some users are required to do for their school or company) will trigger a dark pa
`Whole Device` -> `whole device`

Overall:
> ... will trigger a dark pattern offering you to sign in to Windows, which will connect your device to your Microsoft account, and make it easier to send data to Microsoft servers.

^ That can be refined further, but it's a good starting point

2022-06-30 18:34 UTC, noatsecure commented on docs/windows/hardening.md
> +You should select the offline account instead of a Microsoft account as shown below. With the release of Windows 11, Microsoft changed the UI to make users to use a Microsoft account by default, but
```suggestion
If you wish to limit the amount of data Microsoft obtains from your device, an offline/local account is recommended. Instructions on how to create a local Windows account are here: [How to Create a Local or Offline Account in Windows 11 or Windows 10](https://answers.microsoft.com/en-us/windows/forum/all/how-to-create-a-local-or-offline-account-in/95097c32-40c4-48c0-8f3b-3bcb67afaf7c). For security, it's recommended to set up Windows Hello on all of your accounts because it utilizes the trusted platform module (TPM) if applicable, which protects against brute-force attacks; see the documentation here: [How Windows Uses the TPM](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/how-windows-uses-the-tpm#windows-hello-for-business)
```

2022-06-30 18:34 UTC, noatsecure commented on docs/windows/hardening.md
> +After you have installed Windows, turn on Full Disk Encryption (FDE) using BitLocker via Control Panel.
```suggestion
After you have installed Windows, turn on full disk encryption (FDE) using BitLocker via the Control Panel. 
```

2022-07-01 18:20 UTC, noClaps requested changes

2022-07-01 18:20 UTC, noClaps commented on docs/windows/hardening.md
> +- [x] Enable [Microsoft Defender Application Guard](https://docs.microsoft.com/en-us/windows/security threat-protection/microsoft-defender-application-guard/md-app-guard-overview). After installing b
I don't think you need to say `**This is specific to Microsoft Edge only**` since you've already removed the `and other **Microsoft** Apps such as MS office,etc` part. You're basically just saying the same thing twice.

2022-07-01 18:32 UTC, noClaps commented
I think you should reduce your dependence on images to explain your content. This is because in certain situations, images may be slow to load, or may not load at all. One situation I can think of is when you have a very slow internet connection. Another is those using text-only browsers, like Lynx or Emacs.

Having images can certainly help explain stuff, but we have to accomodate for those who may not have the luxury of a fast internet connection. You can keep the images as they are, but maybe have a way for those who cannot view images to still understand the content and guide.

2022-07-02 02:22 UTC, EdwardLangdon commented on docs/windows/hardening.md
> +- [x] Enable [Microsoft Defender Application Guard](https://docs.microsoft.com/en-us/windows/security threat-protection/microsoft-defender-application-guard/md-app-guard-overview). After installing b
I understand what you mean. If the readers read the Microsoft documentation. They will know it.

2022-07-02 02:25 UTC, EdwardLangdon commented
I only `.webp` images which are small in size and optimized for Web Browsers for faster loading performance. And the case of Lynx or Emacs is mostly rare or only a small amount of users.

Most probably they would have an alternative broswer. This ain't a concern I think.

2022-07-14 13:27 UTC, Cuddle0456 commented
Hello, I think it is worth mentioning you can make BitLocker to have a stronger cipher you can make XTS-AES 128 bit (default) same but 256 bit. What do you guys think ?

https://i.imgur.com/LmG4ggf.png

2022-07-18 16:16 UTC, d4rklynk requested changes

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +Over the years, Microsoft has demonstrated a lot of privacy-invasive behaviour with their software and services. They have continually taken advantage of the fact that Windows is the most widely-used
```suggestion
Over the years, Microsoft has demonstrated a lot of privacy-invasive behaviour with their software and services. They have continually taken advantage of the fact that Windows is the most wide-used desktop OS, and that most people don't change the default settings, in order to collect users' personal information.
```

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +At launch, telemetry could not be disabled in non-enterprise editions of Windows 10. Only after [criticism](https://www.theverge.com/2016/7/21/12246266/france-microsoft-privacy-windows-10-cnil) from
```suggestion
At launch, telemetry could not be disabled in non-enterprise editions of Windows 10. Only after [criticism](https://www.theverge.com/2016/7/21/12246266/france-microsoft-privacy-windows-10-cnil) from the France data protection commission, the [Electronic Frontier Foundation](https://www.eff.org/deeplinks/2016/08/windows-10-microsoft-blatantly-disregards-user-choice-and-privacy-deep-dive) and the [European Union](https://www.reuters.com/article/us-microsoft-dataprotection-eu-idUSKBN15Z1UI), Microsoft changed the way they collect telemetry, allowing users to choose between "Basic" and "Full", with "Basic" mode collecting [much less telemetry](https://www.extremetech.com/computing/243079-upcoming-windows-update-reduces-spying-microsoft-still-mum-data-collects). Along with that, Microsoft collects a [lot more data from Windows 10](https://web.archive.org/web/20210711143017/https://privacytools.io/operating-systems/#win10).
```

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +## Choosing your Edition of Windows
```suggestion
## Choosing your Windows edition
```

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +While using Windows it is better to select either Windows **Enterprise** Edition or **Education** Edition because it gives more control over hardening it for privacy and security by giving refined ac
```suggestion
While using Windows, it is better to select either Windows **Enterprise** Edition or **Education** Edition because it gives more control over hardening it for privacy and security by giving refined access such as disabling full diagnostic data using GP Editor.
```

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +If you cannot get the above you must opt for **Professional** Edition.
```suggestion
If you cannot get what's above, you must opt for **Professional** Edition.
```

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +- Windows **Home** edition is **not** recommended as it do not have many advantages that Professional edition provide such as Bitlocker Drive Encryption, Hyper-V, Windows Sandbox, etc it also uploads
```suggestion
- Windows **Home** edition is **not** recommended as it does not have many advantages that Professional edition provides such as Bitlocker Drive Encryption, Hyper-V, Windows Sandbox, etc. It also uploads Bitlocker Encryption keys to Microsoft servers which actually defies the aspect of encrypting implemented in a different way.
```

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +We recommend you choose Windows 11 over Windows 10 as it is the latest version, and brings many security-related improvements with it by default such as [Secure Boot](https://docs.microsoft.com/en-us
```suggestion
We recommend you choose Windows 11 over Windows 10 as it is the latest version and brings many security-related improvements with it by default such as [Secure Boot](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-secure-boot), [VBS](https://docs.microsoft.com/en-us/windows-hardware/design/device-experiences/oem-vbs), [HVCI](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/device-guard-and-credential-guard), etc. Windows 10 will stop getting updates after [October 14, 2025](https://docs.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro).
```

2022-07-18 16:16 UTC, d4rklynk commented on docs/windows/overview.md
> +You should opt-for Multi edition ISO so that you can install Education or Enterprise edition.
```suggestion
You should opt for multi-edition ISO so that you can install Education or Enterprise edition.
```

2022-07-18 16:48 UTC, d4rklynk requested changes

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +If you wish to limit the amount of data Microsoft obtains from your device, an offline/local account is **recommended**. Instructions on how to create a local Windows account are here: [How to Create
```suggestion
If you wish to limit the amount of data Microsoft obtains from your device, an [offline/local account](https://answers.microsoft.com/en-us/windows/forum/all/how-to-create-a-local-or-offline-account-in/95097c32-40c4-48c0-8f3b-3bcb67afaf7c) is **recommended**. https://answers.microsoft.com/en-us/windows/forum/all/how-to-create-a-local-or-offline-account-in/95097c32-40c4-48c0-8f3b-3bcb67afaf7c. For security, it's recommended to set up Windows Hello on all of your accounts because it uses the trusted platform module (TPM) if applicable, which protects against brute-force attacks; see the documentation: [How Windows Uses the TPM](https://docs.microsoft.com/en-us/windows/security/information-protection/tpm/how-windows-uses-the-tpm#windows-hello-for-business)
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +While setting up, it is recommended to use a generic names such as `user` and `host` and avoid identifying terms such as your name or operating system. This can make it more difficult for privileged
```suggestion
While setting up, it is recommended to use a generic name such as `user` and `host` and avoid identifying terms such as your name or operating system. This can make it more difficult for privileged `Win32` apps or attackers to discern your identity.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +- [ ] Toggle off all privacy related settings as shown in the image :
```suggestion
- [ ] Toggle off all privacy related settings as shown in the image:
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +Perfect way to do is go to Control Panel by searching for it in the Start Menu or from the context menu (right-click) in File Explorer and set it up for all of the drives that you have.
```suggestion
The best way is to go to the Control Panel by searching for it in the Start Menu or from the context menu (right-click) in File Explorer and set it up for all of the drives that you have.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +This will allow to you use alphanumeric characters for the pre-boot PIN.
```suggestion
This will allow you to use alphanumeric characters for the pre-boot PIN.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +You can copy/paste this command `manage-bde -protectors -add c: -TPMAndPIN` in terminal and it will prompt you to enter a new PIN.
```suggestion
You can copy/paste this command `manage-bde -protectors -add c: -TPMAndPIN` in the terminal and it will prompt you to enter a new PIN.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +You can check if it's enabled by typing `manage-bde -status`. It will normally show in **Key Protectors** : **Numerical Password** (it's the recovery key) and **TPM And PIN**.
```suggestion
You can check if it's enabled by typing `manage-bde -status`. It will normally show in **Key Protectors**: **Numerical Password** (it's the recovery key) and **TPM And PIN**.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +    If you want to disable pre-boot PIN requirements if it doesn't fit in your threat model. Set the 2 policies back to **Not configured**.
```suggestion
    If you want to disable pre-boot PIN requirements if it doesn't fit in your threat model. Set the two policies back to **Not configured**.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Don't use admin account for any of your personal tasks !
```suggestion
- Don't use admin account for any of your personal tasks!
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Windows 11 secures it bootloader by default by using Secure boot with the usage of TPM.
```suggestion
- Windows 11 secures its bootloader by default by using Secure boot with the usage of TPM.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Windows 10 on the other hand doesn't come with Secure boot enabled by default except new Devices.
```suggestion
- Windows 10, on the other hand, doesn't come with Secure boot enabled by default except for new devices. 
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +Visit : [https://docs.microsoft.com/en-us/mem/intune/user-help/you-need-to-enable-secure-boot-windows#check-secure-boot-status](https://docs.microsoft.com/en-us/mem/intune/user-help/you-need-to-enabl
```suggestion
Visit: [https://docs.microsoft.com/en-us/mem/intune/user-help/you-need-to-enable-secure-boot-windows#check-secure-boot-status](https://docs.microsoft.com/en-us/mem/intune/user-help/you-need-to-enable-secure-boot-windows#check-secure-boot-status) on how to verify if enabled after enabling secure boot.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +- Just use the built-in Windows Defender Security to protect against threats and stick to it. Don't use anyother Antivirus or Anti-Malware software.
```suggestion
- Just use the built-in Windows Defender Security to protect against threats and stick to it. Don't use any other Antivirus or Anti-Malware software [as it can weaken your security and your privacy](https://wonderfall.space/windows-hardening/#microsoft-defender-antivirus).
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +!!! warning
```suggestion
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +    Enabling Controlled Folder Access will result in delayed startup of Video playback or result in someother videoplayback issues.
```suggestion
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/hardening.md
> +
```suggestion
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/privacy.md
> +Go to this configuration :
```suggestion
Go to this configuration:
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +|UWAs run as restricted, containerized `AppContainer` processes that run by accessing the WinRT API, a subset of COM functionalities and the Win32 API. They have specific properties that define proce
```suggestion
|UWAs run as restricted, containerized `AppContainer` processes that run by accessing the WinRT API, a subset of COM functionalities and the Win32 API. They have specific properties that define process restrictions in terms of the system resources that processes can access.| Win32 applications run as Windows native, traditional processes that run by accessing the Win32 API and COM functionalities to their full extent and a subset of the WinRT API to directly access all system resources. They do not run as restricted processes, all system functionalities are by design directly available to them.|
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +|Only a single instance of a given UWA may run at a given time |Any number of instances of a given Win32 application may run simultaneously
```suggestion
|Only a single instance of a given UWA may run at a given time. | Any number of instances of a given Win32 application may run simultaneously.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +When you see an app in store and scroll down to *Additional Information*  section and see if it asks for certain permissions like in the image below :
```suggestion
When you see an app in store and scroll down to *Additional Information*  section and see if it asks for certain permissions like in the image below:
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +If the Win32 App, Microsoft store will explicitly state that `Provided and Updated by `****` ` as in the image below and it will also state that `Uses all System resources` as in the image below :
```suggestion
If the Win32 App, Microsoft store will explicitly state that `Provided and Updated by `****` ` as in the image below and it will also state that `Uses all System resources` as in the image below:
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +At this point, it is difficult to differentiate between Win32 and UWP apps. To find which is UWP or Win32. Read below :
```suggestion
At this point, it is difficult to differentiate between Win32 and UWP apps. To find which is UWP or Win32. Read below:
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +    Most apps will ask that if the app needs to be used for all users or just for your user account. It is best you keep the app to your user Account. So, We acheive better sandboxing between differe
```suggestion
    Most apps will ask that if the app needs to be used for all users or just for your user account. It is best you keep the app to your user Account. So, We achieve better sandboxing between different user accounts.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +**Use case of Sandbox :** The Windows Sandbox can be used to run unknown software or if you want to isolate your Workspace from the host with only Specific set of apps, etc.
```suggestion
**Use case of Sandbox:** The Windows Sandbox can be used to run unknown software or if you want to isolate your Workspace from the host with only Specific set of apps, etc.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +So, On opening the file, sandbox opens with the Configurations you had set up in your file.
```suggestion
So, when opening the file, sandbox opens with the Configurations you had set up in your file.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +If you do not understand the documentation, you can use [Windows Sandbox Editor](https://github.com/damienvanrobaeys/Windows_Sandbox_Editor) instead which is a GUI application that can be used to cre
```suggestion
If you do not understand the documentation, you can use [Windows Sandbox Editor](https://github.com/damienvanrobaeys/Windows_Sandbox_Editor) instead. It is a GUI application that can be used to create configuration files easily.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +    The Repository doesn't provide a package. So, You need to download the whole codebase. After, extracting the Zip Windows Defender or other Antivirus software may flag the [exe](https://github.com
```suggestion
    The repository doesn't provide a package. So, you need to download the whole codebase. After, extracting the Zip Windows Defender or other Antivirus software may flag the [exe](https://github.com/damienvanrobaeys/Windows_Sandbox_Editor/tree/master/EXE) file as a malware. So, it is recommended to install it via the [Powershell Script](https://github.com/damienvanrobaeys/Windows_Sandbox_Editor/tree/master/Install%20on%20desktop%20(in%20case%20of%20issue%20with%20EXE)) they provide.
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +A full guide on How to use it can be found here : [https://www.systanddeploy.com/2021/11/run-in-sandbox-quick-way-to-runextract.html](https://www.systanddeploy.com/2021/11/run-in-sandbox-quick-way-to
```suggestion
A full guide on How to use it can be found here: [https://www.systanddeploy.com/2021/11/run-in-sandbox-quick-way-to-runextract.html](https://www.systanddeploy.com/2021/11/run-in-sandbox-quick-way-to-runextract.html)
```

2022-07-18 16:48 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +Note : The same note of installing sandbox editor via PowerShell also applies here except this doesn't provide an `exe` at all.
```suggestion
Note: The same note of installing sandbox editor via PowerShell also applies here except this doesn't provide an `exe` at all.
```

2022-07-18 17:08 UTC, d4rklynk requested changes

2022-07-18 17:08 UTC, d4rklynk commented on docs/windows/hardening.md
> +
#### Address Space Layout Randomization

[ASLR](https://wonderfall.space/buffer-overflow#au-niveau-du-syst%C3%A8me-aslr) is a feature that prevents [memory corruption](https://en.wikipedia.org/wiki/Memory_corruption) like [buffer overflow](https://en.wikipedia.org/wiki/Buffer_overflow).
You can enable `ASLR mandatory` & `Bottom-up-ASLR` by going in the Defender Exploit Guard settings. 

![ASLR](/assets/img/windows/aslr.webp)

2022-07-19 07:32 UTC, d4rklynk requested changes

2022-07-19 07:32 UTC, d4rklynk commented on docs/windows/sandboxing.md
> +We recommend you to use this software as it is Convenient and easy to use.
```suggestion
We recommend you to use this software as it is convenient and easy to use. 
```

2022-07-20 12:55 UTC, d4rklynk requested changes

2022-07-22 14:46 UTC, pterocles commented
https://github.com/privacyguides/privacyguides.org/blob/4e8009a911089c635cfaf6c3b7cabce1f59eb6c1/docs/windows/hardening.md?plain=1#L25

Detail this for the reader?
```
**Control Panel** > **System and Security** > **BitLocker Drive Encryption** > **Turn on BitLocker**
```

See: [Microsoft: Writing step-by-step instructions](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/writing-step-by-step-instructions#simple-instructions-with-right-angle-brackets)

2022-07-23 11:13 UTC, d4rklynk commented
> https://github.com/privacyguides/privacyguides.org/blob/4e8009a911089c635cfaf6c3b7cabce1f59eb6c1/docs/windows/hardening.md?plain=1#L106
> 
> Windows 11 secures its bootloader by default using **Secure Boot** through the TPM

https://github.com/privacyguides/privacyguides.org/pull/1380#discussion_r923572433

2022-07-24 02:57 UTC, EdwardLangdon commented
I will fix all the grammar errors today and will continue working on this further.

2022-08-12 20:03 UTC, d4rklynk commented
>     2. We may also like to recommend the use of open-source VeraCrypt instead of proprietary (and possibly backdoored) Bitlocker.

No, we should only use BItlocker for Windows imo. As it is native app.

2022-08-12 20:54 UTC, pterocles commented
For FDE I'd prefer to see listed:
 - Hardware Accelerated: AES (Rijndael) 256 Bits with HMAC-SHA-2 or HMAC-SHA-3 
   - (This is what Veracrypt, Bitlocker, Filevault 2, KeepassXC, and LUKS use by default). Prefer SHA-3.
 - Non-Hardware Accelerated: Same as accelerated above or if available consider:
   - ChaCha20 or XChaCha20
   - Serpent

2022-08-13 05:02 UTC, EdwardLangdon commented
@uranuspucksaxophone LTSC Edition is used in Industries such as Healthcare, hospitals, etc. cuz they don't want unstable software when helping people on their health or fail them when a New Update breaks down.

LTSC edition is mostly stability and security. Not Security Improvements, that doesn't mean security improvements don't come. It's late. I need to know about LTSC and will think on it.

This is just a PR on my own. Things might change by the PG team.

----

For FDE, Bitlocker is the only thing that is best in several ways compared to Veracrypt. Veracrypt is suggested when the device doesn't have Secure boot or it is a Older device.

We are going mainly for Win11 and 10 at times. So, I think sticking to the latest and telling things for the fore-seeing the future would be better idea.

---

I am very busy IRL. So, I can't work. I am hoping to finish this atleast within the end of this year. Contributions are welcome.

2022-08-13 05:59 UTC, closed without merging

2022-08-13 06:05 UTC, EdwardLangdon commented
I closed my PR due to many conflicts using git at the same time. So, I reset branch to Main which closed this PR. I will work on the guide locally and reopen this PR later at sometime.

If anybody is keen to work on the PR. Here is the copy of the Branch before it is reset.

[privacyguides.org-Windows.zip](https://github.com/privacyguides/privacyguides.org/files/9330917/privacyguides.org-Windows.zip)

If you are gonna work, Please do tell me. I would stop working if you are more interested. I am looking forward to hand this over to an individual who has high knowledge in this.