Fix Search Engine Ordering
privacyguides/privacyguides.org pull request #1405
Opened 2022-06-07 07:51 UTC by tommytran732

DDG > Brave > SearcXNG > Startpage.

The reasoning for this is literally already listed for most of them. DDG supports no JS mode, making it the best of the bunch. Brave has anonymous analytics enabled by default so it's worse than DDG.

The only thing that's not mentioned is that StartPage sometimes block VPN or Tor IPs, so it is not as friendly and therefore is put at the bottom. This PR added that.

2022-06-07 22:19 UTC, 27lx requested changes
look at the preview lol. the page is all messed up

duckduckgo is on there twice and the startpage card is improperly formatted

2022-06-07 22:19 UTC, 27lx commented on docs/search-engines.en.md
> +!!! information
> The only thing that's not mentioned is that StartPage sometimes block VPN or Tor IPs, so it is not as friendly and therefore is put at the bottom. This PR added that.

This was/is already mentioned in the Startpage card.

2022-06-08 05:43 UTC, dngray requested changes

2022-06-08 05:43 UTC, dngray commented on docs/search-engines.en.md
> -    Startpage has been known to refuse access to those using a VPN service or Tor, so your mileage may vary.
I've not known them to refuse outright, though they do sometimes require a captcha.

I think this can be integrated with the note below.

2022-06-08 05:49 UTC, dngray commented on docs/search-engines.en.md
> +!!! information
Hah same as below https://github.com/privacyguides/privacyguides.org/pull/1405#pullrequestreview-999143798

2022-06-08 06:14 UTC, 27lx approved these changes

2022-06-08 07:07 UTC, dngray approved these changes

2022-06-08 07:07 UTC, merged

2022-06-08 07:08 UTC, hook9 commented
I honestly think what DuckDuckGo saves is worse than Brave's usage metrics.

[DuckDuckGo](https://duckduckgo.com/privacy#s4):
> We also save searches, but again, not in a personally identifiable way, as we do not store IP addresses or unique User agent strings. We use aggregate, non-personal search data to improve things like misspellings.

[Brave](https://search.brave.com/help/usage-metrics):
> Number of daily/weekly/monthly visits
> Number of returning visits
> Number of search queries per day
> How long you’ve been using Brave Search
> Average query length
> How many users have chosen to leave feedback about Brave Search
> The operating systems people use when they visit (e.g. macOS, Windows, etc)
> The browser you’ve visited from (e.g. Brave, Chrome, Safari, etc)

For search queries that only works for some queries, and it can get really murky, for example if the search query contains personal information or anything that can tie it back to the user.

2022-06-08 07:15 UTC, 27lx commented
> I honestly think what DuckDuckGo saves is worse than Brave's usage metrics.

I do agree with this.

2022-06-08 07:19 UTC, dngray commented
Oh, damn I didn't see this before I merged.

Hmm, I think with Brave/DDG though it might be pretty close because they both have .onion, Brave Search does have [anonymous usage metrics](https://search.brave.com/help/usage-metrics) that you have to disable.

2022-06-08 07:27 UTC, 27lx commented
> Brave Search does have [anonymous usage metrics](https://search.brave.com/help/usage-metrics) that you have to disable.

The usage metrics are still better, I'd argue, than saving every search. And at least the usage metrics can be disabled, whereas Duck's search logs are mandatory.

2022-06-08 07:32 UTC, dngray commented
Point taken, I put in a PR https://github.com/privacyguides/privacyguides.org/pull/1405.

Opt out is better than no opt out.

2022-06-19 16:31 UTC, evil-user commented
Heard duckduckgo favors microsoft's trackers, https://www.theregister.com/2022/06/17/brave_duckduckgo/