Update location of Bromite always-incognito option.
privacyguides/privacyguides.org pull request #1444
Opened 2022-06-15 13:23 UTC by ferodevs

Bromite changed where its always open in incognito option was located. It's currently in a separate section titled "Incognito mode".

The guide was unclear of where to find this option, so this small correction should clear up confusion.

2022-06-18 11:00 UTC, jonaharagon approved these changes

2022-06-18 19:57 UTC, dngray requested changes

2022-06-18 19:57 UTC, dngray commented on docs/browsers.en.md
> +- [x] In **Incognito mode**, select **Always open links in incognito**
I actually had trouble finding this, looks like they've moved things around.

Will need to keep that in line with the [writing style](https://github.com/privacyguides/privacyguides.org/issues/908#issuecomment-1092812825) we've been using for these kinds of instructions.

2022-06-25 12:46 UTC, dngray commented
So it seems I had an old version of Bromite. The Droid-ify repo for Bromite was not updating.

The incognito change occured in version [101.0.4951.53](https://github.com/bromite/bromite/blob/master/CHANGELOG.md#1010495153)

2022-06-25 12:46 UTC, dngray approved these changes

2022-06-25 12:47 UTC, merged