Reorder cloud/local password managers
privacyguides/privacyguides.org pull request #1488
Opened 2022-06-23 19:45 UTC by d4rklynk

The password managers section is the only one to have local-based on top. I think cloud is generally the most usable and should be first.
And I think Bitwarden should be at the top of the page anyway.

I changed Cloud Sync to Cloud based to be in line with other section in the website (like in notebooks section)

2022-06-24 03:32 UTC, dngray commented
On the password manager topic, there's a few things @tommytran732 and I discussed expanding on here:

For passwords page:

1. I'd mention that the 2 local password managers are Keepass and thus are compatible with each other.
2. I'd mention that KeepassXC supports the "Challenge-Response Authentication" as a second factor, which could be used with something like a Yubikey for extra privacy assurance

In this case it basically increases the "entropy" of your master password. It does come with risk however if you lose your yubikey, you cannot access your passwords, so you should have a second one or the challenge response secret backed up.

4. I'd note that Bitwarden server can be replaced with Vaultwarden, then add a scroll down

This one I think we already did

7. I'd embed this video and explain the e2ee mechanism with cloud based password managers https://www.youtube.com/watch?v=w68BBPDAWr8
   Say that despite of the fact that we only recommend 2 password managers, all cloud based password managers are generally safe so long as they follow the architectural design mentioned in the video
8. Mention that with cloud based password managers, if you are using a web client, then you are having implicit trust in the server to not give you malicious javascript to steal your encryption key, and that
using the actual clients are preferable
9. You could look into Nextcloud based pass managers like Passman, tho idk how they work in depth

2022-06-24 07:50 UTC, d4rklynk commented
For e2ee, there's also this video from Computerphile
https://youtu.be/jkV1KEJGKRA

2022-06-24 11:02 UTC, tommytran732 commented
I am in favor of also removing Psono. I cannot justify ever using it at least for personal usage. Web E2EE / browser extension is just bad. There is no reason to use it over Bitwarden which has proper clients.

2022-07-03 14:09 UTC, mfwmyfacewhen requested changes

2022-07-03 14:09 UTC, mfwmyfacewhen commented on docs/passwords.en.md
> +    **KeePassDX** is a lightweight password manager for Android, allows editing encrypted data in a single file in KeePass format and can fill in the forms in a secure way. [Contributor Pro](https://
maybe "**KeePassDX** is a lightweight password manager for Android that allows you to edit encrypted data in KeePass format. It can also fill in forms in a secure way."

2022-07-03 14:09 UTC, mfwmyfacewhen commented on docs/passwords.en.md
> +    **KeePassXC** is a community fork of KeePassX, a native cross-platform port of KeePass Password Safe, with the goal to extend and improve it with new features and bugfixes to provide a feature-ri
split this up into multiple sentences. "**KeePassXC** is a community for of KeePassX, a native cross-platform port of KeePass Password Safe. Its goal is to extend and improve on its predecessor with new features and bug fixes." No need to say cross-platform twice, and feature-rich is already covered by new features.

2022-07-03 14:09 UTC, mfwmyfacewhen commented on docs/passwords.en.md
> +KeePassXC stores its export data as [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) files. This may mean data loss if you import this file into another password manager. We advise you che
change it to "You may lose data if you import this file into another password manager."

2022-07-30 23:12 UTC, mfwmyfacewhen commented
I don't think the computerphile video is needed here.

2022-07-31 10:08 UTC, mfwmyfacewhen approved these changes

2022-07-31 10:18 UTC, mfwmyfacewhen requested changes

2022-07-31 10:18 UTC, mfwmyfacewhen commented on docs/passwords.en.md
> +- [How Password Managers Work - Computerphile](https://www.youtube-nocookie.com/embed/w68BBPDAWr8) (YouTube)
Let's just get rid of this.

2022-08-02 09:09 UTC, d4rklynk commented on docs/passwords.en.md
> +- [How Password Managers Work - Computerphile](https://www.youtube-nocookie.com/embed/w68BBPDAWr8) (YouTube)
Why's that ?

2022-08-06 16:37 UTC, mfwmyfacewhen commented on docs/passwords.en.md
> +- [How Password Managers Work - Computerphile](https://www.youtube-nocookie.com/embed/w68BBPDAWr8) (YouTube)
Don't need to add an additional resources section.

2022-08-12 18:04 UTC, mfwmyfacewhen requested changes

2022-08-12 18:04 UTC, mfwmyfacewhen commented on docs/passwords.en.md
> +- [How Password Managers Work - Computerphile](https://www.youtube-nocookie.com/embed/w68BBPDAWr8) (YouTube)
```suggestion
```

2022-08-12 20:12 UTC, matchboxbananasynergy commented
We are currently discussing a few changes that may come to the password manager page in the near future, which will address the ordering issue that this PR mainly raises, as well as other things.

I'll be closing this PR for now, as we iron out these details.

After those changes, if you still feel like we missed something, please let us know!

2022-08-12 20:12 UTC, closed without merging