Add Signal Configuration and Molly Knowledge Base article
privacyguides/privacyguides.org pull request #1494
Opened 2022-06-24 17:08 UTC by matchboxbananasynergy

Resolves: https://github.com/privacyguides/privacyguides.org/discussions/1448

2022-06-26 10:35 UTC, valldrac commented on docs/advanced/signal-configuration-hardening.en.md
> +Signal will occasionally nudge you with a prompt to re-enter your PIN to ensure you still remember it.
I would mention that the registration lock expires after 7 days of inactivity. Inactivity means the app not connecting to the service for a week. After expiration, the user can reset the PIN at registration. Resetting the PIN will cause the data stored in the account (encrypted by the PIN) to be lost, but still the user is able to register with a new PIN.

2022-06-26 10:35 UTC, valldrac commented on docs/advanced/signal-configuration-hardening.en.md
> +It is best practice to always compare safety numbers with your contacts. This can be done in a couple of ways:
Please note that:
- Comparing safety numbers in the 1:1 chat in Signal with the contact is useless.
- Safety numbers only ensures the messages are delivered securely between the verified devices.
- To make safety numbers to also "verify the person" you need a secondary communication channel where you can authenticate the person that is holding the device. For example, in a meeting or during a video call.

2022-06-26 10:35 UTC, valldrac commented on docs/advanced/signal-configuration-hardening.en.md
> +If a safety number changes frequently or unexpectedly it may be a sign that something is wrong.
This is a bit misleading. A change may be the one and only indicator of an account compromise. It's up to the user to decide what to do. One way of dealing with it, is just to ask the contact what happened and verify the safety numbers again.
For higher threat models, it is a good idea to agree on a protocol with the contact in advance, about what to do if the safety numbers ever change.

2022-06-26 10:35 UTC, valldrac commented on docs/advanced/signal-configuration-hardening.en.md
> +This makes direct requests to the websites in question, which in turn leaks the websites you share in your conversations to those websites.
Clarification: it is the person who is sending the link who does the request, and it attaches an screenshot of the website to the message with the link. The recipient doesn't leak the website unless it opens the link.

2022-06-26 21:37 UTC, valldrac commented on docs/real-time-communication.en.md
> +Signal supports [private groups](https://signal.org/blog/signal-private-group-system/). It has no record of your group memberships, group titles, group avatars, or group attributes.
The subject in the phrase "It has no record..." is confusing to me. Replace it by "The server has no record..." ?

2022-06-27 17:35 UTC, valldrac commented on docs/advanced/signal-configuration-hardening.en.md
> +There is also the ability to tunnel Molly's traffic through a proxy or Tor (via [Orbot](/android/#orbot)).
Suggestion: add "When enabled, all traffic is routed through the proxy and there are no IP or DNS leaks".

2022-06-27 19:37 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind, and thus make much better options for harboring private comm
it's either _many better options_, or _much better option_

2022-06-27 19:38 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind, and thus make much better options for harboring private comm
And shouldn't we say `and thus make it a much better option ?`

2022-06-27 19:54 UTC, matchboxbananasynergy commented on docs/advanced/signal-configuration-hardening.en.md
> +You can also override this global setting for specific contacts:
not sure I agree here, doesn't fit with the way the rest of the page is laid out

2022-06-27 20:53 UTC, d4rklynk requested changes

2022-06-27 20:53 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Select **Settings** > **Account** > **Signal PIN**
```suggestion
- Select **Settings** > **Account** > **Signal PIN**
```

2022-06-27 20:53 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Under **Disappearing messages**, select **Default timer for new chats**
```suggestion
- Under **Disappearing messages**, select **Default timer for new chats**
```

2022-06-27 20:53 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +    Select the three vertical dots on the top right
```suggestion
    - Select the three vertical dots on the top right
```

2022-06-27 20:53 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +    Select **Disappearing messages**
```suggestion
    - Select **Disappearing messages**
```

2022-06-27 20:53 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Select **Settings** > **Notifications**
```suggestion
- Select **Settings** > **Notifications**
```

2022-06-27 20:53 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Select **Settings** > **Notifications**
```suggestion
- Select **Settings** > **Notifications**
```

2022-06-27 21:19 UTC, d4rklynk approved these changes

2022-06-28 16:59 UTC, d4rklynk requested changes

2022-06-28 16:59 UTC, d4rklynk commented on docs/real-time-communication.en.md
> +[:octicons-home-16: Homepage](https://molly.im/){ .md-button .md-button--primary }
```suggestion
[:octicons-home-16: Homepage](https://molly.im/){ .md-button }
```

2022-06-28 21:57 UTC, d4rklynk requested changes

2022-06-28 21:57 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +    - Select the desired amount of time, and select **Save**
```suggestion
    - Select the desired amount of time and hit **Save**
```

2022-06-28 21:57 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Signal allows you to see your call history from your regular phone app. This allows your iOS device to sync your call history with iCloud, including who you spoke to, when, and for how long.
```suggestion
Signal allows you to see your call history from your regular phone app. This allows your iOS device to sync your call history with iCloud, including who you spoke to, when and for how long.
```

2022-06-28 21:57 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind and thus make much better options for harboring private commu
```suggestion
Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind and thus make it a much better option for harboring private communication.
```

2022-06-28 21:57 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +For the dabatase encryption feature to be useful, two conditions must be met:
```suggestion
For the database encryption feature to be useful, two conditions must be met:
```

2022-06-28 21:57 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +This can include a physical attack in which the attacker seizes your device and manages to unlock the device itself, or a remote attack, in which the device is compromised and manages to elevate priv
```suggestion
This can include a physical attack in which the attacker seizes your device and manages to unlock the device itself or a remote attack, in which the device is compromised and manages to elevate privileges to root.
```

2022-06-29 07:22 UTC, matchboxbananasynergy commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind and thus make much better options for harboring private commu
I use options because it's "mobile operating systems" and "Android and iOS"

2022-06-29 07:24 UTC, matchboxbananasynergy commented on docs/advanced/signal-configuration-hardening.en.md
> +This can include a physical attack in which the attacker seizes your device and manages to unlock the device itself, or a remote attack, in which the device is compromised and manages to elevate priv
I think a comma is needed here, any reason why it should be removed?

2022-06-29 07:25 UTC, matchboxbananasynergy commented on docs/advanced/signal-configuration-hardening.en.md
> +Signal allows you to see your call history from your regular phone app. This allows your iOS device to sync your call history with iCloud, including who you spoke to, when, and for how long.
I believe the comma is needed there to differentiate between the 3 things (who, when, how long)

2022-06-29 11:00 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Signal allows you to see your call history from your regular phone app. This allows your iOS device to sync your call history with iCloud, including who you spoke to, when, and for how long.
Well now, you speaking about the same thing, and you listing it, so it needs a comma

2022-06-29 11:02 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind and thus make much better options for harboring private commu
But it can't have an S with much, as much is used for uncountable things

2022-06-29 11:08 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +This can include a physical attack in which the attacker seizes your device and manages to unlock the device itself, or a remote attack, in which the device is compromised and manages to elevate priv
No, you right I think, I think you can let this comma, or maybe put a `;` as you listing 2 different examples, so you need to separate them by a semi-column.

2022-06-29 11:11 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind and thus make much better options for harboring private commu
Or it is `many better options`

2022-06-29 11:13 UTC, d4rklynk commented on docs/advanced/signal-configuration-hardening.en.md
> +This can include a physical attack in which the attacker seizes your device and manages to unlock the device itself, or a remote attack, in which the device is compromised and manages to elevate priv
I'm changing the comment for the `;`

2022-06-29 17:59 UTC, mfwmyfacewhen commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind and thus make much better options for harboring private commu
Matchbox is right here, it should be plural since it is referring to mobile operating systems.

2022-07-07 05:13 UTC, lx-is requested changes

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +[Signal](../real-time-communication.md#signal) is widely accepted as one of the best options when it comes to instant messaging that is both private and secure. Thanks to its E2EE, you can be sure th
```suggestion
[Signal](../real-time-communication.md#signal) is widely regarded instant messaging service that is not only easy to use but is also private and secure. Signal's strong E2EE implementation and metadata protections provide a level of assurance that only you and the intended recipients are able to read communications.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +This page includes things you can do to configure and set up Signal according to your [threat model](../basics/threat-modeling.md).
```suggestion
This guide details actions you can take to configure and set up Signal in accordance with your [threat model](../basics/threat-modeling.md).
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +!!! Important
```suggestion
!!! attention "Registration Lock"
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +Signal will prompt you to enter a PIN. We suggest a strong alphanumeric PIN that you can store in your [password manager](https://www.privacyguides.org/passwords/).
```suggestion
Signal will prompt you to enter a PIN. We suggest using a strong alphanumeric PIN that can be stored in a [password manager](https://www.privacyguides.org/passwords/).
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +This will make it so someone cannot register with your phone number as long as you're active.
```suggestion
```

duplicate info

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +Safety numbers are a feature in Signal that allows you to ensure that messages are delivered securely between the verified devices.
```suggestion
Safety numbers are a feature in Signal that allows you to ensure that messages are delivered securely between verified devices.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +On Android/iOS:
Just to clarify, are these features not available on the desktop apps?

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +We recommend setting up a reasonable timer by default (1 week should be fine for most people), and adjusting it per contact as you see fit.
```suggestion
We recommend setting up a reasonable timer by default, such as one week, and adjusting it per contact as you see fit.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +!!! tip
```suggestion
!!! tip "Snapchat-like Functionality"
```

I think it could be handy to directly mention Snapchat here, in case people don't make the connection. idk

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +This means that when you send a link, a request will be sent to that website so that the screenshot of the website can be attached to the link.
```suggestion
This means that when you send a link, a request will be sent to that website so that a preview of the website can be displayed alongside the link. Thus, we recommend disabling link previews.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +We recommend disabling link previews.
```suggestion
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +Signal allows you to prevent a preview of the app being shown unless you explicitly open it.
```suggestion
Signal allows you to prevent a preview of the app being shown (i.e., in the app switcher) unless you explicitly open it.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +To mitigate this, you can leverage the Screen Lock option to require additional authentication before you can access the Signal app.
```suggestion
To mitigate this, you can leverage the Screen Lock option to require additional authentication before Signal can be accessed.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +Desktop operating system security is far behind Android and iOS. Modern mobile operating systems have been designed with security in mind and thus make much better options for harboring private commu
```suggestion
```

I think the other sentences get the point across clearly. Beyond just being redundant, this phrasing just seems quite threatening and a bit outside the scope of Signal explicitly.

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +While it may be tempting to link your Signal account to your desktop device for convenience, keep in mind that this extends your trust to an additional operating system, and one that often has signif
```suggestion
While it may be tempting to link your Signal account to your desktop device for convenience, keep in mind that this extends your trust to an additional and potentially less secure operating system.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +While Signal takes security very seriously, there is only so much an app can do to protect you.
```suggestion
Signal takes security very seriously, however there is only so much an app can do to protect you.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +Molly offers two variants of the app; **Molly** and **Molly-FOSS**.
```suggestion
Molly offers two variants of the app: **Molly** and **Molly-FOSS**.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +The former is identical to Signal with the addition of Molly's improvements and security features. Molly-FOSS removes Google's proprietary code which is used for some key features, in an effort to ma
```suggestion
The former is identical to Signal with the addition of Molly's improvements and security features. The latter, Molly-FOSS, removes Google's proprietary code, which is used for some key features, in an effort to make it fully open-source.
```

Maybe provide an example of what Google's code is used for, instead of just generalizing as "key features."

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +Both versions of the app support [reproducible builds](https://github.com/mollyim/mollyim-android/tree/main/reproducible-builds) so that you can confirm that the compiled APKs match the source code.
```suggestion
Both versions of Molly support [reproducible builds](https://github.com/mollyim/mollyim-android/tree/main/reproducible-builds), meaning it's possible to confirm that the compiled APKs match the source code.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +Molly has implemented database encryption at rest, which means that you can encrypt the app's database with a passphrase to ensure that none of its data is accessible without it. We recommend a stron
```suggestion
Molly has implemented database encryption at rest, which means that you can encrypt the app's database with a passphrase to ensure that none of its data is accessible without it.
```

kinda self explanatory imo

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +!!! Information
```suggestion
!!! note
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +- Molly has to be locked at the time an attacker gains access to the device.
```suggestion
1. Molly has to be locked at the time an attacker gains access to the device.
```

2022-07-07 05:13 UTC, lx-is commented on docs/advanced/signal-configuration-hardening.en.md
> +- If you become aware that your device has been compromised, you should not unlock Molly's database.
```suggestion
2. If you become aware that your device has been compromised, you should not unlock Molly's database.
```

2022-07-07 07:04 UTC, dngray commented on docs/advanced/signal-configuration-hardening.en.md
> +This will make it so someone cannot register with your phone number as long as you're active.
Agreed.

2022-07-07 07:10 UTC, dngray commented on docs/advanced/signal-configuration-hardening.en.md
> +!!! tip
Fair enough.

2022-07-07 08:04 UTC, matchboxbananasynergy commented on docs/advanced/signal-configuration-hardening.en.md
> +On Android/iOS:
Most of them are, but you can't have Signal on desktop unless you also have it on your phone, so I went with the Android/iOS steps.

2022-07-07 13:38 UTC, merged