Update Linux pages
privacyguides/privacyguides.org pull request #1502
Opened 2022-06-30 10:45 UTC by tommytran732

- Rewrite the Secure Boot section
- Add sysfs access restriction
- Add SUID permission hardener
- Add secure timesync
- Update info about LKRG
- Elaborate a bit more on Tails

2022-06-30 17:54 UTC, SkewedZeppelin commented
/proc and /sys restrictions can easily be done on any distro:
https://github.com/divestedcg/Brace/tree/master/brace/usr/lib/tmpfiles.d

2022-07-01 01:03 UTC, tommytran732 commented
> /proc and /sys restrictions can easily be done on any distro: https://github.com/divestedcg/Brace/tree/master/brace/usr/lib/tmpfiles.d

This looks more like a blacklist than whitelist though?

2022-07-03 04:08 UTC, mfwmyfacewhen requested changes

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +- As noted in Madaidan's guide, disabling access to `/sys` without a proper whitelist will lead to various applications breaking. This will unfortunately be an extremely tedious trial and error proce
should be "minimal Kicksecure installations"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +If you can get LKRG and maintain module updates it provides a worthwhile improvement to security. Debian based distributions can get the LKRG DKMS package from KickSecure's secure repository - the [K
change "could" to "can"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +It is desirable to remove SUID from as many binaries as possible. However, this takes substantial effort and trial and errors on the user's part, as some applications require SUID to function.
change to "trial and error"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +Users of other distributions could adapt the permission hardener to their own system based on the source code linked above.
change "could" to "can"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +There are 2 ways to solve this problem:
change "2" to "two"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +One of the problems with Secure Boot particularly on Linux is that only the [chainloader](https://en.wikipedia.org/wiki/Chain_loading#Chain_loading_in_boot_manager_programs) (shim), the [boot loader]
should be "One of the problems with Secure Boot, particularly on Linux, is"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +One of the problems with Secure Boot particularly on Linux is that only the [chainloader](https://en.wikipedia.org/wiki/Chain_loading#Chain_loading_in_boot_manager_programs) (shim), the [boot loader]
should be "The firmware on most devices is also configured"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +To eliminate the the need to trust Microsoft's keys, follow the "Using your own keys" section on the [Arch Wiki](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot). T
fix "the the"

2022-07-03 04:08 UTC, mfwmyfacewhen commented on docs/linux-desktop/overview.en.md
> +While we strongly recommend against using outdated distributions like Debian, if you insist on using it, we highly recommend that you [convert](https://www.kicksecure.com/wiki/Debian) it into [Kickse
change "reduces" to "reduce"

2022-07-04 10:59 UTC, dngray commented on docs/linux-desktop/hardening.en.md
> +It is desirable to remove SUID from as many binaries as possible. However, this takes substantial effort and trial and errors on the user's part, as some applications require SUID to function.
I think i removed this and it fixed that sentence.

2022-07-04 11:06 UTC, dngray approved these changes

2022-07-04 13:24 UTC, mfwmyfacewhen requested changes

2022-07-04 13:24 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +Kicksecure, and by extension, Whonix has an experimental [permission hardening service](https://github.com/Kicksecure/security-misc/blob/master/lib/systemd/system/permission-hardening.service) and [a
should be "Kicksecure, and by extension, Whonix, has an experimental"

2022-07-04 13:24 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +Security of [PAM](https://en.wikipedia.org/wiki/Linux_PAM) can be [hardened to secure](https://madaidans-insecurities.github.io/guides/linux-hardening.html#pam) authentication to your system.
Change to "The security of PAM can be hardened to allow secure authentication to your system." or another wording

2022-07-04 13:24 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +- If you enroll your own keys as described above, and your distribution supports Secure Boot by default, you can add your distribution's EFI Key into the list of trusted keys (db keys). It can then b
should be "It can then be enrolled into the firmware. Then, you should move all of your keys off your local storage device."

2022-07-04 13:24 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +The second option is to creating an [EFI Boot Stub](https://wiki.archlinux.org/title/Unified_kernel_image) that contains the [kernel](https://en.wikipedia.org/wiki/Kernel_(operating_system)), [initra
Oxford comma

2022-07-04 13:24 UTC, mfwmyfacewhen commented on docs/linux-desktop/hardening.en.md
> +The second option is to creating an [EFI Boot Stub](https://wiki.archlinux.org/title/Unified_kernel_image) that contains the [kernel](https://en.wikipedia.org/wiki/Kernel_(operating_system)), [initra
should be "This option also requires you to leave the keys on the disk to setup automatic signing, which weakens the security model."

2022-07-04 13:24 UTC, mfwmyfacewhen commented on docs/linux-desktop/overview.en.md
> +While we strongly recommend against using outdated distributions like Debian if you are using it, we suggest that you [convert](https://www.kicksecure.com/wiki/Debian) it into [Kicksecure](https://ww
should be "While we strongly recommend against using outdated distributions like Debian, if you decide to use it, we suggest that you"

2022-07-04 13:24 UTC, mfwmyfacewhen commented on docs/linux-desktop/overview.en.md
> +While we strongly recommend against using outdated distributions like Debian if you are using it, we suggest that you [convert](https://www.kicksecure.com/wiki/Debian) it into [Kicksecure](https://ww
Oxford comma

2022-07-04 13:24 UTC, mfwmyfacewhen commented on includes/abbreviations.en.md
> +*[hypervisor]: A hypervisor is computer software, firmware or hardware that allows partitioning the resource of a CPU among multiple operating systems or independent programs.
Oxford comma

2022-07-04 13:44 UTC, dngray commented on docs/linux-desktop/hardening.en.md
> +Encrypting `/boot` however have its own issues, one being that [GRUB](https://en.wikipedia.org/wiki/GNU_GRUB) only supports [LUKS1](https://en.wikipedia.org/wiki/Linux_Unified_Key_Setup) and not the
Looks like GRUB supports LUKS2 https://www.phoronix.com/scan.php?page=news_item&px=GRUB-Boots-LUKS2-Disk-Encrypt


This [comment](https://libredd.it/r/PrivacyGuides/comments/timghp/new_linux_desktop_page/i1h30je/?context=3) seems to suggest systemd-boot can also boot an encrypted LUKS2 partition, but I've not seen any information about that.

2022-07-04 16:36 UTC, dngray commented
I'm going to merge this for now, but this needs a new a new PR addressing https://github.com/privacyguides/privacyguides.org/pull/1502#discussion_r913020111 which will require research/testing.

2022-07-04 16:41 UTC, dngray commented
> The PG site recommends disabling smb and mdns services.

> Why not just change the default zone to "block"?

> According to RedHat documentation in the block zone: "Any incoming network connections are rejected with an icmp-host-prohibited message for IPv4 and icmp6-adm-prohibited for IPv6. Only network connections initiated from within the system are possible."

> So one can

> ```
> firewall-cmd --set-default-zone block
> ```

> And block all incoming connections. Isn't this better than the default configuration?

https://old.reddit.com/r/PrivacyGuides/comments/tkj0xv/firewalld_configuration/

2022-07-04 16:57 UTC, SkewedZeppelin commented
Instead of block you can use this:
https://github.com/divestedcg/Brace/blob/master/brace/usr/bin/brace-supplemental-changes#L22-L24

2022-07-06 13:37 UTC, merged