Remove CalyxOS
privacyguides/privacyguides.org pull request #1518
Opened 2022-07-08 01:13 UTC by tommytran732

Broader device support than GrapheneOS was the one reason Calyx was still recommended. However, even that doesn't seem to hold up anymore: https://calyxos.org/news/2022/07/06/oneplus-android-12-relock-issue/

At it stands, Calyx being outclassed by GrapheneOS on the Pixel, verified boot being broken on the OnePlus devices, and the Fairphone 4 being very broken itself, I see little reasons to keep the CalyxOS recommendation.

2022-07-08 01:26 UTC, mfwmyfacewhen approved these changes

2022-07-08 07:27 UTC, matchboxbananasynergy commented
Agreed. These latest developments, along with major historical delays when it comes to updates (which are *paramount* to the security of the device), I do not think it is a sane choice for Privacy Guides at all anymore.

2022-07-08 07:39 UTC, d4rklynk commented
Agreed to. I don't see the point of using CalyxOS. Just stick to the stock OS for these smartphones if people want to have Google Play Services. Or they should switch to DivestOS.

2022-07-08 07:41 UTC, d4rklynk commented
Remove image of CalyxOS @tommytran732 btw.
And shouldn't we remove GrapheneOS vs CalyxOS too ?

2022-07-08 07:47 UTC, matchboxbananasynergy commented
> Remove image of CalyxOS @tommytran732 btw. And shouldn't we remove GrapheneOS vs CalyxOS too ?

People commonly compare the two, so if people don't see CalyxOS as a recommendation on the website, they'll start wondering why it's not there. I think that it makes sense to contrast the privacy and security features of GrapheneOS against CalyxOS (which again, is usually compared to GrapheneOS with no good reason) in order for people to have more context as to *why* we recommend GrapheneOS.

2022-07-08 07:51 UTC, d4rklynk commented
> > Remove image of CalyxOS @tommytran732 btw. And shouldn't we remove GrapheneOS vs CalyxOS too ?
> 
> People commonly compare the two, so if people don't see CalyxOS as a recommendation on the website, they'll start wondering why it's not there. I think that it makes sense to contrast the privacy and security features of GrapheneOS against CalyxOS (which again, is usually compared to GrapheneOS with no good reason) in order for people to have more context as to _why_ we recommend GrapheneOS.

Yeah ok I understand. Then yeah the title should be something like "Why is GrapheneOS over CalyxOS ?".

2022-07-08 14:09 UTC, dngray commented
To be listed, we currently require:

- Regular security updates
- Lockable bootloader

Having a look at the [Calyx feature page](https://calyxos.org/features/) and assuming one has a Pixel (there is no compelling reason to buy a OnePlus or Fairphone), I don't see a whole lot of reasons to choose this over GrapheneOS.

There's the Datura Firewall, but on GrapheneOS you've got the `INTERNET` permission you can revoke, which seems more robust than a stateful firewall. There is [microG](https://calyxos.org/docs/guide/microg/), but I think [sandboxed play services](https://grapheneos.org/usage#sandboxed-google-play) is a better option if you're afraid about Google seeing your unique identifiers (IMSI/IMEI etc).

I suppose there is the shifting trust from Google location services, to Mozilla and DejaVu. There is no reason you can't change that on GrapheneOS though if you wanted. As for the other features, about the only thing I see there is the panic button - [Ripple](https://guardianproject.info/apps/info.guardianproject.ripple/), and there's no reason you couldn't install that as you can with Signal and Whatsapp on GrapheneOS.

Are there any really stand out privacy features on Calyx that are not just bundled apps?

2022-07-09 15:10 UTC, ph00lt0 commented
Fully agree with all above, but probably good to put this sum up of reasons why CalyxOS is inferior to GrapheneOS on the website. Still i see many people in the privacy world picking / recommending it over grapheneOS for no good reason and I think this can be educated.

2022-07-09 17:57 UTC, dngray approved these changes

2022-07-09 18:01 UTC, dngray requested changes
Will approve for merging, once https://github.com/privacyguides/privacyguides.org/pull/1518#issuecomment-1178671593 is sorted.

2022-07-10 18:18 UTC, dngray approved these changes

2022-07-10 18:20 UTC, merged