Add Gitlab Syntax For RSS Feed
privacyguides/privacyguides.org pull request #1611
Opened 2022-08-08 20:00 UTC by matchboxbananasynergy

This PR adds the necessary syntax to track app updates on Gitlab for android apps. It also removes the screenshots of gfeeds showing the RSS feed as I believe we should eventually replace those with screenshots of an Android RSS reader such as Feeder or Read You, as that makes a lot more sense (you should be tracking app updates with an android RSS feeder so that you can click and download the update on that same device).

2022-08-08 20:08 UTC, mfwmyfacewhen requested changes

2022-08-08 20:08 UTC, mfwmyfacewhen commented on docs/android.en.md
> +#### Github
```suggestion
#### GitHub
```

2022-08-08 20:08 UTC, mfwmyfacewhen commented on docs/android.en.md
> +For apps that are released on platforms like Github and Gitlab, you may be able to add an RSS feed to your [news aggregator](/news-aggregators) that will help you keep track of new releases.
```suggestion
For apps that are released on platforms like GitHub and GitLab, you may be able to add an RSS feed to your [news aggregator](/news-aggregators) that will help you keep track of new releases.
```

2022-08-08 20:08 UTC, mfwmyfacewhen commented on docs/android.en.md
> +On Github, using [Secure Camera](#secure-camera) as an example, you would navigate to its [releases page](https://github.com/GrapheneOS/Camera/releases) and append `.atom` to the URL:
```suggestion
On GitHub, using [Secure Camera](#secure-camera) as an example, you would navigate to its [releases page](https://github.com/GrapheneOS/Camera/releases) and append `.atom` to the URL:
```

2022-08-08 20:08 UTC, mfwmyfacewhen commented on docs/android.en.md
> +#### Gitlab
```suggestion
#### GitLab
```

2022-08-08 20:08 UTC, mfwmyfacewhen commented on docs/android.en.md
> +On Gitlab, using [Aurora Store](#aurora-store) as an example, you would navigate to its [project repository](https://gitlab.com/AuroraOSS/AuroraStore) and append `/-/tags?format=atom` to the URL:
```suggestion
On GitLab, using [Aurora Store](#aurora-store) as an example, you would navigate to its [project repository](https://gitlab.com/AuroraOSS/AuroraStore) and append `/-/tags?format=atom` to the URL:
```

2022-08-08 20:27 UTC, mfwmyfacewhen approved these changes

2022-08-10 23:00 UTC, jonaharagon approved these changes

2022-08-11 09:54 UTC, dngray approved these changes

2022-08-11 16:07 UTC, dngray commented
@matchboxbananasynergy if you think that looks okay we can merge.

2022-08-11 16:12 UTC, matchboxbananasynergy commented
> @matchboxbananasynergy if you think that looks okay we can merge.

LGTM, we can merge

2022-08-12 06:06 UTC, merged