Health and Fitness
privacyguides/privacyguides.org pull request #1628
Opened 2022-08-11 03:32 UTC by jonaharagon

Closes #1562

2022-08-12 10:49 UTC, d4rklynk commented
You can add the fact that Apple health has [e2ee support](https://support.apple.com/en-us/HT202303)

2022-08-12 13:23 UTC, TrashPandaCodingGarbage commented
Why is Sleep as Android recommended? Privacy policy of the service looks not so good on the first glance. I recommend replacing it with [plees](https://f-droid.org/en/packages/hu.vmiklos.plees_tracker/).

2022-08-15 09:18 UTC, KaiTebay commented
> Why is Sleep as Android recommended? Privacy policy of the service looks not so good on the first glance. I recommend replacing it with [plees](https://f-droid.org/en/packages/hu.vmiklos.plees_tracker/).

**Tl;dr: I think the privacy policy seems reasonable for what I expect the majority of user's threat models to be. I've summarized as best I can, and my main notables are opt-out defaults for anonymous usage analytics and personalized ads. I haven't tested it, but I suspect that disabling network access would be also be effective.**

I'm not an expert but Urbandroid's privacy policy seems to commit them to:
- User-identifying information for bug reports; user-generated app data for backups; anonymous usage analytics; coarse geo location data (+/- 10km), stored locally (except for inclusion with user-approved backup via SleepCloud).
- Ability to delete user data (varies for third-parties). Usage analytics cannot be deleted (although they can be turned off) because Urbandroid claims that they are anonymous data.
- No transfer of personally identifiable information to third parties, except those necessary for services (i.e. the ones listed) or for legal compliance.

- **Third-parties:**

**Opt-out:**

1. _Facebook Audience Network_, via the Device Advertising ID.
2. _Google Analytics for Firebase_, for anonymous usage analytics.

---

**Opt-in:**

1. _Gmail_ and _Help Scout_ for bug reports.
2. Data backup via _Google Drive_.
3. Data backup via _Dropbox_.
4. Data backup via _SleepCloud_, owned and maintained by Urbandroid; uses _Google Cloud Platform_ (Datastore).
5. _Google Fit_.

### Summary:
The majority of data usage seems to be opt-in integrations with third-party services. Two usages stood out to me: personalized ads, and anonymous usage analytics. It sounds like they are enabled by default but it seems that they can be disabled in the app's settings. The coarse geo location data seems to be stored locally, unless the user approves backup via SleepCloud.

2022-08-19 08:54 UTC, purtual requested changes

2022-08-19 08:54 UTC, purtual commented on docs/health-and-fitness.en.md
> +Apple Watch users should consider using WatchOS' native sleep tracking functionality. Using native, locally-based solutions instead of third-party apps reduces your attack surface by limiting the num
```suggestion
Apple Watch users should consider using watchOS' native sleep tracking functionality. Using native, locally-based solutions instead of third-party apps reduces your attack surface by limiting the number of parties that may have access to or be responsible for protecting your data.
```

2023-04-17 14:16 UTC, jonaharagon commented
a mention I don't want to forget https://www.reddit.com/r/PrivacyGuides/comments/11lhyzl/comment/jd4kgap/?utm_source=share&utm_medium=web2x&context=3

2024-04-04 11:58 UTC, freddy-m commented
@privacyguides/team what is the status of this PR? Are we still interested in adding this page or...

2024-04-04 13:28 UTC, dngray commented
> what is the status of this PR? Are we still interested in adding this page or...

Yes we're going to add it, though it has not been reviewed yet. Working through the pages in queue.

2025-01-04 16:54 UTC, friadev commented
> @friadev @redoomed1 you mind also having a look at this one. I do really hope to have this added one day.

Yeah I’d love to, I don’t have access to Android at the moment.

2025-01-24 18:43 UTC, closed without merging