Windows hardening guide
privacyguides/privacyguides.org pull request #1659
Opened 2022-08-19 14:03 UTC by EdwardLangdon

This is a successor to #1380 Pull request by me. Things that are there will follow here but in a paced manner with concise information.

I have stated the reason in the old one for its closure.

If you are suggesting big Changes, make a PR other than that do Code reviews.

Do not comment about your suggestions in this PR as I want it clean and don't want it confusing either for me or to the contributors. So, Suggest them in Issue #166. I am following it.

There will be no ETA for this. I will work on this in my Free time and try finish ASAP.

2022-11-13 09:42 UTC, IkelAtomig commented
This will be reopened shortly.

2022-11-13 15:26 UTC, IkelAtomig commented
Thanks to @d4rklynk, @noClaps, @namazso and many more who helped on this.

2022-11-26 05:07 UTC, evil-user commented
@IkelAtomig the link to bsi.de is not working

2022-11-26 05:09 UTC, evil-user commented
Also windows sandbox is compared to tails os in pendrive but tails os has antiforensics properties which i dont think is guranteed by windows sandbox

2022-11-26 05:12 UTC, evil-user commented
The page says run in a sandbox is credited by microsoft can you please share any links to confirm it by viewers themselves.( just for paranoid users who like transparency)

2022-11-26 05:21 UTC, jonaharagon commented
Please don't ping a bunch of contributors or leave multiple consecutive comments on this PR. This guide is a work in progress.

2022-11-27 03:27 UTC, IkelAtomig commented
Okay, Jonah. But in my Opinion I have finished what I could do.So, Merging is totally upto you. I could add stuff if wanted.

2023-02-11 14:05 UTC, pixincreate requested changes

2023-02-11 14:05 UTC, pixincreate commented on docs/windows/privacy.md
> +- [ ] Disable Windows spotlight by navigating to `User Configuration` > `Administrative Templates` > `Windows Components` > `Cloud Content` and setting **Turn off all Windows Spotlight features** pol
If you disable this, it will get enabled. If you enable the option, it will get disabled.  Basically the statement here says that you're enabling the spotlight features.   
It is better to read the policy description to not get confused by the options given in the `gpedit.msc`

2023-02-15 07:36 UTC, dngray commented
I am at some point going to have another look at this, we should incorporate https://github.com/privacyguides/privacyguides.org/pull/1979/files into it as an tip.

2023-02-15 08:01 UTC, dngray commented
This discussion https://github.com/privacyguides/privacyguides.org/discussions/1281 brought up that we should remind users to update their systems.

We should probably have some mention about BIOS updates too, https://github.com/privacyguides/privacyguides.org/discussions/1280 as not all systems this comes through Windows Update. Of course there will only be only general instructions as different vendors use different update tools on Windows.

2023-02-26 22:40 UTC, noClaps commented on docs/windows/overview.md
> +    - The ISO will consists **only** of Professional, Education & Enterprise edition with a size of ~4.2 GB (Instead of >5.5GB when you download the Multi-Edition ISO) when you download using the abo
```suggestion
    - The ISO will consist **only** of Professional, Education & Enterprise editions with a size of ~4.2 GB (Instead of >5.5GB when you download the Multi-Edition ISO). When you download using the above way, no other editions such as Home are included in it.
```

2023-02-26 22:40 UTC, noClaps commented on docs/windows/overview.md
> +    - If you want to change the Language of the ISO file, Just change the `en-US` part with the appropriate language and country code as per your needs.
```suggestion
    - If you want to change the language of the ISO file, Just change the `en-US` part with the appropriate language and country code as per your needs.
```

2023-02-26 22:42 UTC, noClaps commented on docs/windows/overview.md
> +    Never download **Pirated ISO Files**
I feel like the emphasis here should be on **Never**

2023-02-26 22:43 UTC, noClaps commented on docs/windows/overview.md
> +    If you are going to install Windows 11, Then install it only on supported devices and it is not recommended to use tools/scripts that are available online to bypass the requirements which totally
```suggestion
    If you are going to install Windows 11, then install it only on supported devices. It is not recommended to use tools/scripts that are available online to bypass the requirements which would break the security of Windows 11.
```

2023-02-26 22:43 UTC, noClaps commented on docs/windows/privacy.md
> +You should never sign-in to Windows with a Microsoft account. Signing-in to applications like Microsoft Office (which some users are required to do for their school or company) will trigger a dark pa
```suggestion
You should never sign in to Windows with a Microsoft account. Signing in to applications like Microsoft Office (which some users are required to do for their school or company) will trigger a dark pattern offering you to sign in to Windows, which will connect your device to your Microsoft account, and make it easier to send data to Microsoft servers and it is critical to reject this offer.
```

2023-02-26 22:44 UTC, noClaps commented on docs/windows/privacy.md
> +You should never sign-in to Windows with a Microsoft account. Signing-in to applications like Microsoft Office (which some users are required to do for their school or company) will trigger a dark pa
I think the "make it easier to send data to Microsoft servers and it is critical to reject this offer." can be rephrased and expanded upon a bit

2023-02-26 23:30 UTC, noClaps commented on docs/windows/privacy.md
> +![Disable telemtry](/assets/img/windows/disable-telemetry.webp)
```suggestion
![Disable telemetry](/assets/img/windows/disable-telemetry.webp)
```

2023-02-26 23:31 UTC, noClaps commented on docs/windows/privacy.md
> +Disabling full telemtry or sending basic data to Microsoft is totally upto the user's threat model.
```suggestion
Disabling full telemetry or sending basic data to Microsoft is totally up to the user's threat model.
```

2023-02-26 23:32 UTC, noClaps commented on docs/windows/privacy.md
> +- [ ] Disable `Automatic Sample Submission` in Windows Defender will send your files as a sample for Signature Database and might leak your data. You can do it via the below Group Policy so to not pr
This makes it sound like disabling the option in Defender will send the files.

2023-02-26 23:33 UTC, noClaps commented on docs/windows/privacy.md
> +        This explicitly disables Windows spotlight features in Lockscreen and Desktop to severe unnecessary between Microsoft servers and the device.
```suggestion
        This explicitly disables Windows spotlight features in Lockscreen and Desktop to sever unnecessary connections between Microsoft servers and the device.
```

2023-02-26 23:34 UTC, noClaps commented on docs/windows/privacy.md
> +- [ ] Disable in Bing integration in Windows search, by navigating to `Computer Configuration\Administrative Templates\Windows Components\Search\Don't search the web or display web results`. This way
```suggestion
- [ ] Disable Bing integration in Windows search, by navigating to `Computer Configuration\Administrative Templates\Windows Components\Search\Don't search the web or display web results`. This way your search queries for local indexed data is not sent to Microsoft.
```

2023-02-26 23:36 UTC, namazso commented
Please just use the review feature, suggesting changes separately sends an email to every watcher every single time

![image](https://user-images.githubusercontent.com/8676443/221444278-19c34c00-43a8-4e6a-92b8-7935d689379c.png)

2023-02-26 23:41 UTC, noClaps commented
Okay will do, sorry

2023-03-05 13:21 UTC, IkelAtomig commented
Will work on this later. Currently working on another repo.

2023-05-10 16:24 UTC, IkelAtomig commented
Update : https://discuss.privacyguides.net/t/windows-guide/250/90?u=ikel

2024-02-05 14:27 UTC, dngray commented
We should make sure [the PIN preboot authentication option](https://discuss.privacyguides.net/t/breaking-bitlocker-bypassing-the-windows-disk-encryption/16643/4) is mentioned within this PR 

https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/countermeasures#preboot-authentication

2024-02-06 12:18 UTC, IkelAtomig commented
@dngray I actually did mention about this is. Maybe messed up. That is why I uploaded the archive of the branch. I don't have to time to work on to be honest.

2024-03-18 10:48 UTC, dngray commented
@oppressor1761 this one kind of stalled, and we didn't get back to it, if you want to you can create another PR (with your changes) and just look over this one to see if there's anything worth taking from it.

2024-03-22 02:07 UTC, IkelAtomig commented
@oppressor1761 I didn't have the time really to work on it later. You are welcome to use contents from here. Meanwhile, I am planning to work on this during the Month of May during which I am absolutely free to work on this.

2024-03-24 12:08 UTC, jermanuts commented
@IkelAtomig Great guide, thanks for compiling it.

>- Windows **Home** edition is **not** recommended as it does not have many advantages that Professional edition provides such as BitLocker Drive Encryption, Hyper-V, Windows Sandbox, etc. It also uploads Bitlocker Encryption keys to Microsoft servers which actually defies the aspect of the encryption implemented as the key was supposed to be hold by the user.

Isn't that only when you use a Microsoft account? And it is not specific to one Windows Edition, all the same?

https://portswigger.net/daily-swig/bitlocker-encryption-clear-text-key-storage-prompts-security-debate-online

2024-03-26 02:39 UTC, IkelAtomig commented
@jermanuts My most probable and firm guess is it's the automatic Drive encryption which holds it in Plain text. Maybe I forget to say turn off the Bitlocker and do it again or Maybe I did. I dunno, Will check on it when I work on it.

2024-04-14 12:09 UTC, IkelAtomig commented
New things incoming, ETA - May 30th. Stay tuned.

2024-04-15 04:18 UTC, dngray commented
> New things incoming, ETA - May 30th. Stay tuned.

We should probably decide which PR is going to be merged into main, whether this one or https://github.com/privacyguides/privacyguides.org/pull/2452 and merge these two together.

I have not read over either closely yet. Intention was to clear https://github.com/privacyguides/privacyguides.org/pull/2268 https://github.com/privacyguides/privacyguides.org/pull/2437 first.

2024-04-16 01:40 UTC, IkelAtomig commented
@dngray - Not a problem. I have to rework a lot on this as I haven't updated it more than a year and I haven't made my writing visible yet on the preview. Need to add it in mkdocs.yml

If you merge the other one first, Maybe I will modify this one as some suggestions to it. 

Let's see. I hope, I could start working on this before you come back to Windows section.

@oppressor1761 - Shall we two work on this together or separately - Totally your choice ?

2024-04-17 04:39 UTC, IkelAtomig commented on docs/windows/privacy.md
> +- [ ] Disable Windows spotlight by navigating to `User Configuration` > `Administrative Templates` > `Windows Components` > `Cloud Content` and setting **Turn off all Windows Spotlight features** pol
Yeah, My bad. Thanks for pointing it out. I was experimenting Group Policies back then. So, didn't know what did what.

2024-06-13 06:23 UTC, dngray commented
I'm working on merging this one together, it will be based off https://github.com/privacyguides/privacyguides.org/pull/2606 (then when that is merged we can look at merging this one).

2024-06-13 10:55 UTC, IkelAtomig commented
@dngray - I will update this branch now. After then, you shall merge it.

2024-06-13 12:44 UTC, dngray commented
I pushed to it, before, but haven't made any changes, it will require some time to go over. I haven't read it in detail

2024-06-13 18:20 UTC, redoomed1 commented
Since #2591 added a dedicated [page](https://www.privacyguides.org/en/os/windows/group-policies/) for Group Policies, I suggest moving the instructions in "Security policies for Bitlocker" to the aforementioned page, and adding an internal link to the [BitLocker section](https://www.privacyguides.org/en/os/windows/group-policies/#bitlocker-drive-encryption) of the GP page in its place.

Other group policy settings introduced in this PR can also be moved to the dedicated GP page.

2024-06-14 04:36 UTC, dngray commented
> I suggest moving the GP instructions in "Security policies for Bitlocker" to the aforementioned page

That's exactly what I had in mind in regard to https://github.com/privacyguides/privacyguides.org/pull/2437#issuecomment-2030178327. I haven't yet gone over this PR and read it, in entirety just getting the structure right of what should be where as it is huge.

2024-06-19 04:32 UTC, redoomed1 reviewed
I haven't used Windows for quite a while now so, for this PR, I can offer suggestions only regarding grammar, formatting, and consistency with other parts of the Privacy Guides site.

Aside from my earlier suggestion about consolidating Group Policy recommendations, other parts of the PR caught my eye, which I commented on below.

2024-06-19 04:32 UTC, redoomed1 commented on docs/os/windows/hardening.md
> +- Using MS edge or brave over Firefox. Edge is recommended with MDAG mode for secure browsing if security is your priority. Brave is recommeded if content blocking is important for you (Brave shields
There's already a page for desktop browser recommendations on the site.

2024-06-19 04:32 UTC, redoomed1 commented on docs/os/windows/hardening.md
> +- Avoid any types of Cleaning software at all cost. As Microsoft is working on its own implementation specfically designed for windows.
Including a brief explanation of _why_ people using Windows should avoid cleaning software would be useful here.

---
Also, is the native implementation of cleaning software you're referring to called "[Microsoft PC Manager](https://apps.microsoft.com/en-us/detail/9pm860492szd)"? From these forum posts, it looks like Windows users have to download it from the Microsoft Store themselves and it is not available in all geographical regions.

https://answers.microsoft.com/en-us/windows/forum/all/when-will-the-pc-manager-app-be-available-to-uk/e9325c52-2f56-402e-8a5d-1c220ed00e45

https://answers.microsoft.com/en-us/windows/forum/all/microsoft-pc-manager-is-not-available-in-windows/669e4c67-eff6-46d6-9863-a5c36dedd6ba

2024-07-01 05:00 UTC, IkelAtomig commented on docs/os/windows/hardening.md
> +- Use [PeaZip](https://peazip.github.io/) archiver instead of 7-zip as it disables [Mark of the Web(MoW)](https://nolongerset.com/mark-of-the-web-details/) [support by default](https://github.com/nma
Well, At then time, 7Zip or Windows didn't preserve MoTW. I don't remember quite well.

2024-07-01 05:01 UTC, IkelAtomig commented on docs/os/windows/hardening.md
> +- Using MS edge or brave over Firefox. Edge is recommended with MDAG mode for secure browsing if security is your priority. Brave is recommeded if content blocking is important for you (Brave shields
You are right. Will remove it since MDAG is gonna be killed by microsoft afaik.

2024-07-01 05:01 UTC, IkelAtomig commented on docs/os/windows/hardening.md
> +- Avoid any types of Cleaning software at all cost. As Microsoft is working on its own implementation specfically designed for windows.
Yeah, It is.

2024-07-28 15:28 UTC, redoomed1 commented on docs/os/windows/windows-overview.md
A lot of the information from this page was adapted to the [current Windows Overview](https://www.privacyguides.org/en/os/windows/) in #2591.

Unless someone has specific suggestions on information in this drafted page that should be added to the current Windows Overview on the site, I think this page should be removed from the PR to reduce the size of this PR and make it easier for reviewers to go over the PR.

2024-08-05 11:46 UTC, IkelAtomig commented
Ah, Should I do anything because of I kind of orphaned this PR. I would be glad if some parts of it are made into the site and my name is in the footer. That's it.

2024-08-05 13:46 UTC, dngray commented
don't close it. The other one will do that when it is merged, and yes you're on it as co-author, so you'd get the same credit in your git activity.

2024-08-05 14:25 UTC, IkelAtomig commented
I want to be on the privacyguides site. Greedy me.

2024-08-05 15:03 UTC, dngray commented
> I want it to be on the privacyguides site. Greedy me.

Oh I was talking about https://github.com/privacyguides/privacyguides.org/pull/1380. Yes the intention is to merge this, it may need some refactoring to fit in with  https://github.com/privacyguides/privacyguides.org/pull/2591 and https://github.com/privacyguides/privacyguides.org/pull/2606

2024-08-05 15:06 UTC, dngray commented on docs/os/windows/windows-overview.md
I haven't looked at this PR in detail, but it should be possible to create several PRs for [those various sections](https://github.com/privacyguides/privacyguides.org/blob/main/docs/os/windows/index.md?plain=1#L13-L17) from this one.

We can always give @IkelAtomig credit for the ones which were heavily based on this one, perhaps splitting them up would make it more workable?

2024-08-05 15:13 UTC, dngray commented
@IkelAtomig on second thoughts, I think it might be better if we split this off onto three PRs, one for each page (sandboxing, privacy, hardening), as long as you're the author, of each it will show your name at the bottom of the page.

We need to then just check whether `windows-overview.md` contains anything we want to keep that isn't already in `docs/os/windows/index.md`. As long as the commit has you as the author it should show you as the contributor.

2024-08-06 01:31 UTC, IkelAtomig commented
Alright, just say what to do when you are ready.

2025-05-06 20:45 UTC, jonaharagon commented
The guides written by the OP are officially published here: https://discuss.privacyguides.net/tags/c/community-wiki/9411/windows (where you are credited as the author @IkelAtomig 😄)

I am closing this PR to align with our current plan for Windows-related guides at https://discuss.privacyguides.net/t/windows-guide/250/370

2025-05-06 20:45 UTC, closed without merging