Update GrapheneOS
privacyguides/privacyguides.org pull request #1690
Opened 2022-08-24 19:29 UTC by d4rklynk

Prior to my old PR #1688 : 
- I just added some links

2022-08-24 23:19 UTC, jonaharagon requested changes

2022-08-24 23:19 UTC, jonaharagon commented on docs/android.en.md
> +GrapheneOS supports [Sandboxed Google Play](https://grapheneos.org/usage#sandboxed-google-play), which runs [Google Play Services](https://en.wikipedia.org/wiki/Google_Play_Services) fully sandboxed
```suggestion
GrapheneOS supports [Sandboxed Google Play](https://grapheneos.org/usage#sandboxed-google-play), which runs [Google Play Services](https://en.wikipedia.org/wiki/Google_Play_Services) fully sandboxed like any other regular app. This means you can take advantage of most Google Play Services, such as [push notifications](https://firebase.google.com/docs/cloud-messaging/), while giving you full control over their permissions and access, and while containing them to a specific [work profile](android/overview.md#work-profile) or [user profile](android/overview.md#user-profiles) of your choice.
```
Makes more sense tbh. We need to be reducing the number of external links we have on the site as a long-term goal, not increasing them.

2022-08-25 19:21 UTC, TrashPandaCodingGarbage commented
A13 stable is already pushed by Graphene

2022-08-25 19:23 UTC, jonaharagon commented
What does that have to do with this PR?

2022-08-25 19:28 UTC, d4rklynk commented
> A13 stable is already pushed by Graphene

wut

2022-08-28 14:05 UTC, mfwmyfacewhen approved these changes

2022-08-28 14:14 UTC, dngray approved these changes

2022-08-28 14:15 UTC, merged