Multi-Factor Authentication Article
privacyguides/privacyguides.org pull request #17
Opened 2021-05-03 01:35 UTC by jonaharagon

Resolves #10

2021-05-12 14:17 UTC, jonaharagon commented
err... oops

2022-02-18 19:08 UTC, ph00lt0 commented
Probably a good thing to just link the page with current recommendations for OTP apps, instead of duplicating the information. That would reduce maintenance. So f.x. state: current recommended apps can be found on the website LINK.

2022-03-09 13:37 UTC, dngray commented
This one will work better now. We can have an article and then mention the specific apps on the specific pages. Still need to finish MacOS/iOS/Windows pages.

2022-03-09 14:05 UTC, flexagoon requested changes

2022-03-09 14:05 UTC, flexagoon commented on collections/_evergreen/two-factor-authentication.md
> +The idea behind 2FA is that even if a hacker is able to figure out your password (something you *know*), they will still need a device you own like your phone (something you *have*) in order to gener
```suggestion
The idea behind 2FA is that even if a hacker is able to figure out your password (something you *know*), they will still need a device you own like your phone (something you *have*) in order to generate the code needed to log in to your account. 2FA methods vary in security based on this premise: The more difficult it is for an attacker to gain access to your 2FA method, the better. Examples of 2FA methods from weakest to strongest are Email or SMS codes, Push Notifications, Software (TOTP) Code-Generating Apps, and Hardware Keys.
```

2022-03-26 13:37 UTC, dngray commented
I think this one will need finishing  before we can finish https://github.com/privacyguides/privacyguides.org/pull/795

The main reason is I want to mention, although apps like Bitwarden, KeepassXC have TOTP code generation, you will achieve maximum security using something like Aegis to store your TOTP codes.

Otherwise everything is behind "single password" and you've just reduced your multi factor to a single factor locally.

As far as recommendation, I'm only comfortable mentioning products for TOTP that are on Android and iOS, because these are most secure and sandboxed environments. Additionally that is the whole point, you might copy a password from your password manager but the code is only available for a limited time, and if your pc/mac is compromised in some way the shared secret will still be secured.

The other thing I also want to mention is Yubikeys, and how they can be used.

2022-03-29 12:56 UTC, ph00lt0 requested changes

2022-03-29 12:56 UTC, ph00lt0 commented on _data/hardware/multi-factor-authentication-security-key/2_nitrokey.yml
> +  **Nitrokey** make a security key capable of [Universal 2nd Factor (U2F)](https://en.wikipedia.org/wiki/Universal_2nd_Factor) called the **Nitrokey FIDO2**.
You are referring to U2F here. U2F is the depreciated standard. We should refer to FIDO2 WebAuthn instead.

2022-03-29 12:57 UTC, ph00lt0 commented on collections/_evergreen/multi-factor-authentication.md
> +The ultimate form of multi-factor security are **hardware keys**. These are devices that implement a standard such as **FIDO2** or **U2F** that you need to physically attach to your computer to log i
Change FIDO2 -> FIDO2 WebAuthn

2022-03-29 13:00 UTC, ph00lt0 commented
Good to see this moved into a page!

2022-03-29 13:04 UTC, ph00lt0 requested changes

2022-03-29 13:04 UTC, ph00lt0 commented on _data/software/multi-factor-authentication-totp/2_ravio_otp.yml
> +  **Ravio OTP** is a native, lightweight and secure time-based (TOTP) & counter-based (HOTP) password client built for iOS.
We should add something saying about the backups to Icloud that this app supports. Users may not want this. I always recommend https://www.tofuauth.com/ instead, because they are not included in icloud backups.

2022-03-30 07:25 UTC, dngray commented on _data/hardware/multi-factor-authentication-security-key/2_nitrokey.yml
> +  **Nitrokey** make a security key capable of [Universal 2nd Factor (U2F)](https://en.wikipedia.org/wiki/Universal_2nd_Factor) called the **Nitrokey FIDO2**.
Yes you're 100% right.

2022-03-31 22:54 UTC, merged