Introduction to Passwords Knowledge Base Article
privacyguides/privacyguides.org pull request #1708
Opened 2022-08-31 18:02 UTC by matchboxbananasynergy

This is a work in progress article that will go over the basics of passwords, best practices and will talk about a lot of the pitfalls that a lot of people fall for when creating their passwords.

Closes: https://github.com/privacyguides/privacyguides.org/issues/1706

2022-09-01 00:55 UTC, jonaharagon commented on docs/basics/passwords-overview.en.md
> +icon: 'material-shield-key-outline'
```suggestion
icon: 'material/shield-key-outline'
```

2022-09-01 12:57 UTC, jonaharagon commented
Maybe this article could incorporate some of the information mentioned in #1609, since I don't think that's worth a full page about?

2022-09-02 11:22 UTC, purtual requested changes

2022-09-02 11:22 UTC, purtual commented on docs/basics/passwords-overview.en.md
> +Passwords are an essential part of of our everyday digital lives. We use them to protect our accounts, our devices and our secrets. Despite the fact that passwords are often the only thing between us
```suggestion
Passwords are an essential part of our everyday digital lives. We use them to protect our accounts, our devices and our secrets. Despite often being the only thing between us and someone who wants to access our private information, not a lot of thought is put into them, often leading to using passwords that can be easily guessed or brute-forced and thus jeopardizing your most important data.
```

2022-09-02 21:31 UTC, jonaharagon commented
FYSA: I would avoid merge commits like b70b931e5b6ff29cddc76fed15d928f73b2b0323 in PRs, they make them more difficult to manage locally.

2022-09-02 22:43 UTC, mfwmyfacewhen requested changes

2022-09-02 22:43 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +The best way to store your passwords is by using a password manager. They allow you to store your passwords in a file or in the cloud with the use of a master password. That way, you will only have t
```suggestion
The best way to store your passwords is by using a password manager. They allow you to store your passwords in a file or in the cloud and protect them with a single master password. That way, you will only have to remember one strong password, which lets you access the rest of them.
```

2022-09-02 22:43 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +There are many good options to choose from, both cloud-based and local. Choose one of our recommended password managers and use it to establish strong passwords across all of your accounts. We recomm
```suggestion
There are many good options to choose from, both cloud-based and local. Choose one of our recommended password managers and use it to establish strong passwords across all of your accounts. We recommend securing your password manager with a word [diceware](#diceware) passphrase comprised of at least 6 words.
```

2022-09-02 22:58 UTC, mfwmyfacewhen requested changes

2022-09-02 22:58 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +There are many good options to choose from, both cloud-based and local. Choose one of our recommended password managers and use it to establish strong passwords across all of your accounts. We recomm
```suggestion
There are many good options to choose from, both cloud-based and local. Choose one of our recommended password managers and use it to establish strong passwords across all of your accounts. We recommend securing your password manager with a [diceware](#diceware) passphrase comprised of at least 6 words.
```

2022-09-03 07:09 UTC, rusty-snake commented on docs/basics/passwords-overview.en.md
> +This is called [credential stuffing](https://en.wikipedia.org/wiki/Credential_stuffing) and it is one of the most common ways that your accounts can be compromised by bad actors. To avoid this, make
This can also be done by the owner of the service (https://xkcd.com/792/) which somehow feels more dangerous than a possible (but in fact no so unlikely) data breach.

2022-09-04 12:48 UTC, rusty-snake commented on docs/basics/passwords-overview.en.md
> +We recommend using [EFF's large wordlist](https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt) to generate your diceware passphrases, as it offers the exact same security as the original list
Outside of the scope of this PR, but what do you think about searching for and recommending non-english lists as well. This will make diceware easier and more accepted by non-native speakers.

2022-09-04 21:19 UTC, mfwmyfacewhen requested changes

2022-09-04 21:19 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +Passwords are an essential part of our everyday digital lives. We use them to protect our accounts, our devices and our secrets. Despite often being the only thing between us and and an adversary who
```suggestion
Passwords are an essential part of our everyday digital lives. We use them to protect our accounts, our devices and our secrets. Despite often being the only thing between us and an adversary who's after our private information, not a lot of thought is put into them which often leads to people using passwords that can be easily guessed or brute-forced.
```

2022-09-04 21:19 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +This is called [credential stuffing](https://en.wikipedia.org/wiki/Credential_stuffing) and it is one of the most common ways that your accounts can be compromised by bad actors. To avoid this, make
```suggestion
This is called [credential stuffing](https://en.wikipedia.org/wiki/Credential_stuffing) and it is one of the most common ways that your accounts can be compromised by bad actors. To avoid this, make sure that you never re-use your passwords.
```

2022-09-04 21:19 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +This is called [credential stuffing](https://en.wikipedia.org/wiki/Credential_stuffing) and it is one of the most common ways that your accounts can be compromised by bad actors. To avoid this, make
I think the original sentence is redundant.

2022-09-04 21:19 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +1. Roll a six-sided dice five times, noting the number after each roll.
```suggestion
1. Roll a six-sided die five times, noting the number after each roll.
```

2022-09-04 21:19 UTC, mfwmyfacewhen commented on docs/basics/passwords-overview.en.md
> +You should store an encrypted exported backup of your passwords or your password database itself on multiple storage devices. This can be useful if something happens to your primary device or the ser
```suggestion
You should store an encrypted, exported backup of your passwords or your password database itself on multiple storage devices. This can be useful if something happens to your primary device or the service you are using.
```

2022-09-04 21:45 UTC, blacklight447 approved these changes
Just read through this it it looks great. Everything is straight to the point  and comes with examples, great work!

2022-09-05 07:17 UTC, purtual requested changes

2022-09-05 07:17 UTC, purtual commented on docs/basics/passwords-overview.en.md
> +We recommend using [EFF's large wordlist](https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt) to generate your diceware passphrases, as it offers the exact same security as the original list
```suggestion
We recommend using [EFF's large wordlist](https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt) to generate your diceware passphrases, as it offers the exact same security as the original list, while containing words that are easier to memorize. There are also other wordlists in different languages, if you do not want your passphrase to be in English.
```

2022-09-05 07:17 UTC, purtual commented on docs/basics/passwords-overview.en.md
> +    If you're using TOTP as a [multi-factor authentication](../multi-factor-authentication.md) method for any of your accounts, do not store these tokens, any backup codes for them, or the TOTP secre
```suggestion
    If you're using TOTP as a [multi-factor authentication](../multi-factor-authentication.md) method for any of your accounts, do not store these tokens, any backup codes for them, or the TOTP secrets themselves in your password manager, as that negates the benefit of multi-factor authentication. You should use a dedicated [TOTP app](../multi-factor-authentication.md/#authenticator-apps) instead.
```

2022-09-06 07:16 UTC, purtual requested changes

2022-09-06 07:16 UTC, purtual commented on docs/basics/passwords-overview.en.md
> +Passwords are an essential part of our everyday digital lives. We use them to protect our accounts, our devices and our secrets. Despite often being the only thing between us and an adversary who's a
```suggestion
Passwords are an essential part of our everyday digital lives. We use them to protect our accounts, our devices and our secrets. Despite often being the only thing between us and an adversary who's after our private information, not a lot of thought is put into them, which often leads to people using passwords that can be easily guessed or brute-forced.
```

2022-09-06 07:16 UTC, purtual commented on docs/basics/passwords-overview.en.md
> +This is called [credential stuffing](https://en.wikipedia.org/wiki/Credential_stuffing) and it is one of the most common ways that your accounts can be compromised by bad actors. To avoid this, make
```suggestion
This is called [credential stuffing](https://en.wikipedia.org/wiki/Credential_stuffing), and it is one of the most common ways that your accounts can be compromised by bad actors. To avoid this, make sure that you never re-use your passwords.
```

2022-09-06 07:16 UTC, purtual commented on docs/basics/passwords-overview.en.md
> +When it comes to passwords that you don't have to remember (such as passwords stored inside your password manager), if your [threat model](threat-modeling.md) calls for it, we recommend going through
```suggestion
When it comes to passwords that you don't have to remember (such as passwords stored inside your password manager), if your [threat model](threat-modeling.md) calls for it, we recommend going through important accounts (especially accounts that don't use multi-factor authentication) and changing their password every couple of months, in case they have been compromised in a data breach that hasn't become public yet. Most password managers allow you to set an expiry date for your password to make this easier to manage.
```

2022-09-06 07:16 UTC, purtual commented on docs/basics/passwords-overview.en.md
> +??? Note "Explanation of entropy and stregth of diceware passphrases"
```suggestion
??? Note "Explanation of entropy and strength of diceware passphrases"
```

2022-09-06 15:14 UTC, merged