Pr ios
privacyguides/privacyguides.org pull request #1750
Opened 2022-09-11 18:17 UTC by mfwmyfacewhen

Add iOS #697

2022-09-13 14:55 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +icon: material/material-toggle-switch
```suggestion
icon: material/toggle-switch
```

2022-09-13 23:32 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.
We don't recommend Private Relay (beta) nor Hide My Mail (not in our Email Aliasing providers section).

2022-09-13 23:32 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Send Last Location**
We should note that Find My is required for anti-theft (activation lock) functionality.

2022-09-13 23:32 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +
Are we duplicating a section we already have?

2022-09-14 16:29 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.
Yeah I think there's a use case, you don't have to make another account and can just use your Apple ID. Plus I just wanted to explain what they are so people can decide if they want to use them or not.

2022-09-16 16:58 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Send Last Location**
I need to do further testing, but I am able to disable Find My iPhone in Privacy > Location Services > System Services without disabling Find My in iCloud settings, which seems to keep Find My's remote deactivation, wipe, and activation lock features enabled while not sending location data to Apple. If this does work how this appears to, this method might be preferable to the method currently in the doc.

[This document](https://www.apple.com/legal/privacy/data/en/find-my/) also seems to claim Find My location is end-to-end encrypted as of iOS 15, which *may* also mitigate these concerns, but at a glance it's not super obvious to me which data is and isn't end-to-end encrypted, so I'll have to read through all these articles more thoroughly later.

2022-09-16 17:01 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Allow Siri When Locked**
I don't think we are (or should recommend) disabling on-device iOS features that don't transmit data to Apple or pose a security risk (like allowing Siri when locked). Thoughts?

If on-device ML functions in Siri are problematic for you I feel like you should just disable Siri entirely.

2022-09-16 17:07 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.
Then I might prefer something like:

> If you already use iCloud Mail, **Hide My Email** is Apple's first-party email aliasing feature included with a paid [**iCloud+**](https://support.apple.com/en-us/HT201318) subscription.

You could also include this if you feel it's relevant:

> If you use another mail provider, we recommend [other email aliasing services](https://www.privacyguides.org/email/#email-aliasing-services) over Hide My Email.

I would still recommend *against* Private Relay specifically.

2022-09-19 07:58 UTC, purtual requested changes

2022-09-19 07:58 UTC, purtual commented on docs/ios/configuration.en.md
> +**Private Relay** is a proxy service that relays your Safari traffic through two servers: one owned by Apple and one owned by Cloudflare. You must purchase [**iCloud+**](https://support.apple.com/en-
```suggestion
**Private Relay** is a proxy service that relays your Safari traffic through two servers: one owned by Apple and one owned by Cloudflare. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to use this feature.
```
#1710

2022-09-19 07:58 UTC, purtual commented on docs/ios/configuration.en.md
> +**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.
```suggestion
**Private Relay** is a proxy service that relays your Safari traffic through two servers: one owned by Apple and one owned by Cloudflare. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.

Select **Private Relay (Beta)**

- [x] Turn on **Private Relay (Beta)**

You can choose to either **Maintain your general location** to get more localized results, or just use your **country and time zone** to get a broader IP address location.

Select **IP Address Location**

- [x] Select **Use country and time zone**

**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to use this feature.
```
#1710

2022-09-19 13:31 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.
> I would still recommend against Private Relay specifically.

Why's that? The way I see it, it's something you can turn on if you already pay for iCloud+ and you weren't really planning on signing up for a VPN anyway.

2022-09-20 07:13 UTC, purtual requested changes

2022-09-20 07:13 UTC, purtual commented on docs/ios/configuration.en.md
> +**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.
```suggestion
**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to use this feature.
```

2022-10-12 05:55 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +**Hide My Email** is Apple's email aliasing service for iCloud mail. You must purchase [**iCloud+**](https://support.apple.com/en-us/HT201318) to utilize this feature.
@jonaharagon ok I changed the wording for this, let me know what you think.

2022-10-12 05:59 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Send Last Location**
It does say Apple can't see the location of your devices. I agree with ph00lt0 here, I think we should actually recommend enabling it to prevent someone getting access to your phone.

2022-10-12 06:06 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +
Should I link back to the other one or just not mention it?

2022-10-12 06:07 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Allow Siri When Locked**
As long as it doesn't leave the device it's not a concern imo.

2022-10-13 02:16 UTC, mfwmyfacewhen commented
hmm kind of thinking recommending people turn on the erase data after 10 failed attempts is actually a bad idea, I mean you can just wipe it remotely with find me. What do y'all think?

2022-10-13 06:11 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +
actually I think I decided since the safari rec might not always be there I'll just take this off fully.

2022-10-14 22:45 UTC, mfwmyfacewhen commented
Also thinking I might just not mention Private Relay instead of specifically saying to disable it, but what do yall think?

2022-10-16 02:42 UTC, jonaharagon requested changes

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [x] Select **Off**
```suggestion
**Background App Refresh** allows your apps to refresh their content while you're not using them. This may cause them to make unwanted connections. Turning this off can also save battery life, but it may affect an app's ability to receive updated information, particularly weather and messaging apps.

Select **Background App Refresh** and switch off any apps you don't want to allow refreshing in the background. If you don't want any apps to background refresh, you can select **Background App Refresh** again and turn it **Off**.
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### Touch ID & Passcode
```suggestion
### Face ID or Touch ID & Passcode
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Setting a strong password on your phone is probably the most important step you can take for security and privacy. You'll have to make tradeoffs here between security and convenience; a longer passwo
```suggestion
Setting a strong password on your phone is the most important step you can take for physical device security. You'll have to make tradeoffs here between security and convenience: A longer password will be annoying to type in every time, but a shorter password or pin will be easier to guess. Setting up Face ID or Touch ID along with a strong password can be a good compromise between usability and security.
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Select **Turn Passcode On** > **Passcode Options** > **Custom Alphanumeric Code**
```suggestion
Select **Turn Passcode On** or **Change Passcode** > **Passcode Options** > **Custom Alphanumeric Code**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Set a password that you won't forget. The longer, the better. It might be easier for you to string a few words together and break them up with numbers and symbols.
Do we have an existing password creation guide we can link to?

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Follow the onscreen prompts to set up Touch ID.
```suggestion
If you wish to use Face ID or Touch ID, you can go ahead and set it up now. Your phone will use the password you set up earlier as a fallback in case your biometric verification fails. Biometric unlock methods are primarily a convenience, although they do prevent surveillance cameras from watching you input your passcode.

If you use biometrics, you should know how to turn them off quickly in an emergency. Holding down the side/power button and either volume button until you see the Slide to Power Off slider will disable biometrics, requiring your passcode to unlock. Your passcode will also be required after device restarts. 

On some older devices, you may have to press the power button five times to disable biometrics instead, or for devices with Touch ID you may just have to hold down the power button and nothing else. Make sure you try this in advance so you know which method works for your device.
```

Really doxxing yourself, now we all know you have an old phone (or an SE) lol

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **USB Accessories**
```suggestion
**Allow Access When Locked** gives you options for what you can allow when your phone is locked. The more of these options you disable, the less someone without your password can do, but the less convenient it will be for you. Pick and choose which of these you don't want someone to have access to if they get their hands on your phone.

- [ ] Turn off **Today View and Search**
- [ ] Turn off **Notification Center**
- [ ] Turn off **Control Center**
- [ ] Turn off **Lock Screen Widgets**
- [ ] Turn off **Siri**
- [ ] Turn off **Reply with Message**
- [ ] Turn off **Home Control**
- [ ] Turn off **Wallet**
- [ ] Turn off **Return Missed Calls**
- [ ] Turn off **USB Accessories**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +
```suggestion
The iPhone is already resistant to brute-force attacks by making you wait long periods of time after multiple failed attempts, however historically there have been exploits to get around this. To be extra safe, you can set your phone to wipe itself after 10 failed passcode attempts.

!!! warning

    With this setting enabled, someone could intentionally wipe your phone by entering the wrong password many times. Make sure you have proper backups and only enable this setting if you feel comfortable with it.

- [x] Turn on **Erase Data**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Share iPhone Analytics**
```suggestion
**Safety Check** allows you to quickly view and revoke certain people and apps that might have permission to access your data. Here you can perform an **Emergency Reset**, immediately resetting permissions for all people and apps which might have access to device resources, and you can **Manage Sharing & Access** which allows you to go through and customize who and what has access to your device and account resources.

You should disable analytics if you do not wish to send Apple usage data. Select **Analytics & Improvements**:

- [ ] Turn off **Share iPhone Analytics** or **Share iPhone & Watch Analytics**
- [ ] Turn off **Share iCloud Analytics**
- [ ] Turn off **Improve Fitness+**
- [ ] Turn off **Improve Safety**
- [ ] Turn off **Improve Siri & Dictation**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Personalized Ads**
```suggestion
Disable **Personalized Ads** if you do not want targeted ads. Select **Apple Advertising**

- [ ] Turn off **Personalized Ads**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Location Services**
```suggestion
**Location Services** allows you to use features like Find My and Maps. If you do not need these features, you can disable Location Services. Alternatively, you can review and pick which apps can use your location here. Select **Location Services**

- [ ] Turn off **Location Services**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Allow Apps to Request to Track**
```suggestion
You can decide to allow apps to request to **track** you here. Disabling this disallows all apps from tracking you with your phone's advertising ID. Select **Tracking**:

- [ ] Turn off **Allow Apps to Request to Track**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Sensor & Usage Data Collection**
```suggestion
You should turn off **Research Sensor & Usage Data** if you do not wish to participate in studies. Select **Research Sensor & Usage Data**:

- [ ] Turn off **Sensor & Usage Data Collection**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +- [x] Select **Turn On App Privacy Report**
```suggestion
**App Privacy Report** is a built-in tool that allows you to see what permissions your apps are using. Select **App Privacy Report**:

- [x] Select **Turn On App Privacy Report**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Select **Turn On Lockdown Mode**
```suggestion
**Lockdown Mode** is a security setting you can enable to make your phone more resistant to attacks. Be aware that certain apps and features will not work as they do normally, you should view list of all the changes [here](https://support.apple.com/en-us/HT212650).

- [x] Select **Turn On Lockdown Mode**
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Under FaceTime, there is a camera icon and a phone handset icon. Select the camera to make a video call and the phone icon to make an audio-only call.
```suggestion
Normal phone calls made with the Phone app through your carrier are not E2EE. Both FaceTime Video and FaceTime Audio calls are E2EE, or you can use [another app](../real-time-communication.md) like Signal.
```

These instructions confused me initially because I've never initiated a FaceTime call in this way before, and I don't think we need to guide users on how to start a FaceTime call anyhow.

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +If either you or your messaging partner have iCloud backup enabled, the encryption key will be stored on Apple's servers, meaning they can access your messages. Disabling this setting will mean that
```suggestion
The color of the message bubble in the Messages app indicates whether your messages are E2EE or not. A blue bubble indicates that you are using iMessage with E2EE, while a green bubble indicates they are using the outdated SMS and MMS protocols. Currently, the only way to get E2EE in Messages is for both parties to be using iMessage on Apple devices.

If either you or your messaging partner have iCloud Backup enabled, the encryption key will be stored on Apple's servers, meaning they can access your messages. Additionally, iMessage's key exchange is not as secure as alternative implementations, like Signal (which allows you to view the recipients key and verify by QR code), so it should not be relied on for extra sensitive communications.
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +
I think this is covered above.

```suggestion
```

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +If you need to hide information in a photo, you can use Apple's built-in tools to do so. Open the photo you want to edit, press edit at the top right corner of the screen, then press the markup symbo
```suggestion
If you need to hide information in a photo, you can use Apple's built-in tools to do so. Open the photo you want to edit, press edit at the top right corner of the screen, then press the markup symbol at the top right. Press the plus at the bottom right of the screen, then press the rectangle icon. Now you can place a rectangle anywhere on the image. Make sure to press the shape icon at the bottom left and select the filled-in rectangle. Do **not** use the marker/highlighter to obfuscate information, because its opacity is not quite 100%.
```

https://ios.gadgethacks.com/how-to/warning-sensitive-info-you-black-out-images-can-be-revealed-with-few-quick-edits-your-iphone-0333975/

2022-10-16 02:42 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +--8<-- "includes/abbreviations.en.md"
```suggestion
### Installing Beta Versions of iOS

Apple always makes beta versions of iOS available early for those that wish to help find and report bugs. We do not recommend installing beta software on your phone. Beta releases are potentially unstable and could have undiscovered security vulnerabilities.

### Before First Unlock

If your threat model includes forensic tools and you want to minimize the chance of exploits being used to access your phone, you should restart your device frequently. The state *after* a reboot but *before* unlocking your device is referred to as "Before First Unlock," and when your device is in that state it makes it [significantly more difficult](https://belkasoft.com/checkm8_glossary) for forensic tools to exploit vulnerabilities to access your data. This BFU state allows you to receive notifications for calls, texts, and alarms, but most of the data on your device is still encrypted and inaccessible. This can be impractical, so consider whether these trade-offs make sense for your situation.
```

2022-10-16 03:15 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +Set a password that you won't forget. The longer, the better. It might be easier for you to string a few words together and break them up with numbers and symbols.
that we do

2022-10-16 03:19 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +Follow the onscreen prompts to set up Touch ID.
Now everyone knows I don't have the flagship 😭I'm ruined

2022-10-16 03:22 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +
I think this is a semicolon situation with however, and the having However, historically, sounds weird.

2022-10-16 03:24 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +Select **Turn On Lockdown Mode**
just noticed it should be "you should view a list of all the changes"

2022-10-16 03:25 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +If you need to hide information in a photo, you can use Apple's built-in tools to do so. Open the photo you want to edit, press edit at the top right corner of the screen, then press the markup symbo
Do you want to link that in the page?

2022-10-16 04:06 UTC, jonaharagon submitted a review, later dismissed

2022-10-16 04:06 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### iCloud
```suggestion
## iCloud
```

2022-10-16 04:06 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### Airplane Mode
```suggestion
## Airplane Mode
```

2022-10-16 04:06 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### Wi-Fi
```suggestion
## Wi-Fi
```

2022-10-16 04:06 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### Bluetooth
```suggestion
## Bluetooth
```

2022-10-16 04:06 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### General
```suggestion
## General
```

2022-10-16 04:06 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### Face ID or Touch ID & Passcode
```suggestion
## Face ID or Touch ID & Passcode
```

2022-10-16 04:06 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +### Privacy
```suggestion
## Privacy
```

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +At the top of the **Settings** app, you'll see your name and profile picture if you are signed in to iCloud. Select that, then **iCloud**, and turn off the switches for any services you don't want to
```suggestion
At the top of the **Settings** app, you'll see your name and profile picture if you are signed in to iCloud. Select that, then **iCloud**, and turn off the switches for any services you don't want to sync to iCloud. You may see third-party apps listed under **Show All** if they sync to iCloud, which you can disable here. For the purposes of this guide, we will only be covering first-party Apple iCloud services:
```

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +**Private Relay** is a proxy service which relays your Safari traffic through two servers: one owned by Apple and one owned by Cloudflare. You must purchase [**iCloud+**](https://support.apple.com/en
```suggestion
**Private Relay** is a paid ([**iCloud+**](https://support.apple.com/en-us/HT201318)) proxy service which relays your Safari traffic through two servers: one owned by Apple and one owned by Cloudflare. Because Private Relay is still in beta and it only covers the Safari browser, we recommend you choose a proper [VPN](../vpn.md) instead.
```

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +If you already use iCloud Mail, **Hide My Email** is Apple's first-party email aliasing feature included with a paid iCloud+ subscription. If you use any mail provider other than iCloud, we recommend
```suggestion
If you already use iCloud Mail, **Hide My Email** is Apple's first-party email aliasing feature. You can use email aliases with Sign In With Apple for free, or generate unlimited aliases with a paid iCloud+ plan. Hide My Email may be good for iCloud Mail users because it only requires trusting one party (Apple) with your emails, but if you use any other email provider we recommend [a standalone email aliasing service](../email.md#email-aliasing-services) instead.
```

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Select **AirPlay & Handoff** > **Automatically AirPlay to TVs**
```suggestion
**AirPlay** lets you seamlessly stream content from your iPhone to a TV; however, you might not always want this. Select **AirPlay & Handoff** > **Automatically AirPlay to TVs**:
```

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +Select **Software Update** > **Automatic Updates**
```suggestion
It is important to install **Software Updates** frequently to get the latest security fixes. You can enable **Automatic Updates** to keep your phone up-to-date without needing to constantly check for updates. Select **Software Update** > **Automatic Updates**:
```

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +We have a guide on making secure passwords [here](https://www.privacyguides.org/basics/passwords-overview/).
```suggestion
Select **Turn Passcode On** or **Change Passcode** > **Passcode Options** > **Custom Alphanumeric Code**. We have a guide on making secure passwords [here](../basics/passwords-overview.md).
```

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +If you wish to use Face ID or Touch ID, you can go ahead and set it up now. Your phone will use the password you set up earlier as a fallback in case your biometric verification fails. Biometric unlo
```suggestion
If you wish to use Face ID or Touch ID, you can go ahead and set it up now. Your phone will use the password you set up earlier as a fallback in case your biometric verification fails. Biometric unlock methods are primarily a convenience, although they do stop surveillance cameras or people over your shoulder from watching you input your passcode.
```
I think this was a good example that we removed from the section at the bottom of the page.

2022-10-16 04:17 UTC, jonaharagon commented on docs/ios/configuration.en.md
> +**Location Services** allows you to use features like Find My and Maps. If you do not need these features, you can disable Location Services. Alternatively, you can review and pick which apps can use
```suggestion
**Location Services** allows you to use features like Find My and Maps. If you do not need these features, you can disable Location Services. Alternatively, you can review and pick which apps can use your location here. Select **Location Services**:
```

2022-10-16 09:20 UTC, KaiTebay requested changes
This looks great so far! I've suggested some very minor changes (fixing a few sentences and preferring contractions, etc.)

I'm only halfway though: I'll continue later today, when I have time! :smile:

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +At the top of the **Settings** app, you'll see your name and profile picture if you are signed in to iCloud. Select that, then **iCloud**, and turn off the switches for any services you don't want to
```suggestion
At the top of the **Settings** app, you'll see your name and profile picture if you are signed in to iCloud. Select that, then **iCloud**, and disable the switches for any services you don't want to sync to iCloud. You may see third-party apps listed under **Show All** if they sync to iCloud, which you can disable here. For the purposes of this guide, we'll only be covering first-party Apple iCloud services:
```

Prefers a contraction and prefers "disable" (to be consistent).

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +**iCloud Backup** backs up your phone and app data to Apple's servers. Unfortunately, these backups are not E2EE,[^1] and having them enabled even removes E2EE from some other iCloud services like iM
```suggestion
**iCloud Backup** backs up your phone and app data to Apple's servers. Unfortunately, these backups are not E2EE,[^1] and having them enabled even removes E2EE from some other iCloud services (like iMessage). Instead of iCloud Backup, we recommend making an encrypted backup to your computer using iTunes (Windows) or Finder (macOS).
```

Adds parentheses for readability.

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Back Up This iPhone**
```suggestion
- [ ] Disable **Back Up This iPhone**
```

Prefers "disable" (for consistency).

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Private Relay (Beta)**
```suggestion
- [ ] Disable **Private Relay (Beta)**
```

Prefers "disable" (for consistency).

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +If you already use iCloud Mail, **Hide My Email** is Apple's first-party email aliasing feature. You can use email aliases with Sign In With Apple for free, or generate unlimited aliases with a paid
```suggestion
If you already use iCloud Mail, **Hide My Email** is Apple's first-party email aliasing feature. You can use email aliases with Sign In With Apple, for free, or generate unlimited aliases with a paid iCloud+ plan. Hide My Email may be good for iCloud Mail users because it only requires trusting one party (Apple) with your emails, but if you use any other email provider, we recommend [a standalone email aliasing service](../email.md#email-aliasing-services) instead.
```

Embeds "for free" (parenthetical). Adds a comma (the second part of the complex sentence starts with a [conditional](https://dictionary.cambridge.org/grammar/british-grammar/conditionals-if) that treats "if" as a [subordinating conjunction](https://languagetool.org/insights/post/style-conjunctions/)).

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Personalized Recommendations**
```suggestion
- [ ] Disable **Personalized Recommendations**
```

Prefers "disable" (consistency).

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +- [x] Turn on **Private Wi-Fi Address**
```suggestion
- [x] Enable **Private Wi-Fi Address**
```

Prefers "enable" (consistency with disable).

2022-10-16 09:20 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +You also have the option to **Limit IP Address Tracking**. This is similar to iCloud Private Relay but only affects connections to "known trackers." Because it only affects connections to potentially
```suggestion
You also have the option to **Limit IP Address Tracking**. This is similar to iCloud Private Relay but only affects connections to "known trackers." Because it only affects connections to potentially malicious servers, this setting is probably fine to leave enabled. But if you don't want *any* traffic to be routed through Apple's servers, you should turn it off.
```

Prefers a contraction. Fixes a comma splice using a new sentence (a semi-colon is also appropriate). Adds a comma for the if-clause (see previous example).

2022-10-16 09:56 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Back Up This iPhone**
For those I was trying to follow the [Microsoft style guide](https://learn.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui)

2022-10-19 19:17 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Back Up This iPhone**
That seems sensible. I only suggested these changes because [existing pages](https://www.privacyguides.org/desktop-browsers/#search-suggestions) are using "enable" and "disable". 

I think it would be best to use a consistent style, so perhaps just disregard these suggestions for now and we can make wider changes in a separate issue (unless others have input on this). :smile:

2022-10-19 20:15 UTC, KaiTebay requested changes
I've suggested a few minor grammatical and stylistic changes, but this looks great to me. I'm excited for its release!

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +**Location Services** allows you to use features like Find My and Maps. If you do not need these features, you can disable Location Services. Alternatively, you can review and pick which apps can use
```suggestion
**Location Services** allows you to use features like Find My and Maps. If you don't need these features, you can disable Location Services. Alternatively, you can review and pick which apps can use your location here. Select **Location Services**:
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +You should turn off **Research Sensor & Usage Data** if you do not wish to participate in studies. Select **Research Sensor & Usage Data**:
```suggestion
You should turn off **Research Sensor & Usage Data** if you don't wish to participate in studies. Select **Research Sensor & Usage Data**:
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +You should disable analytics if you do not wish to send Apple usage data. Select **Analytics & Improvements**:
```suggestion
You should disable analytics if you don't wish to send Apple usage data. Select **Analytics & Improvements**:
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +Disable **Personalized Ads** if you do not want targeted ads. Select **Apple Advertising**
```suggestion
Disable **Personalized Ads** if you don't want targeted ads. Select **Apple Advertising**
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +**App Privacy Report** is a built-in tool that allows you to see what permissions your apps are using. Select **App Privacy Report**:
```suggestion
**App Privacy Report** is a built-in tool that allows you to see which permissions your apps are using. Select **App Privacy Report**:
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +**Lockdown Mode** is a security setting you can enable to make your phone more resistant to attacks. Be aware that certain apps and features will not work as they do normally, you should view list of
```suggestion
**Lockdown Mode** is a security setting you can enable to make your phone more resistant to attacks. Be aware that certain apps and features won't work as they do normally: you should view [this](https://support.apple.com/en-us/HT212650) list of all the changes.
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +Jailbreaking an iPhone defeats its security and makes you vulnerable. Running untrusted, third-party software could cause your device to be infected with malware.
```suggestion
Jailbreaking an iPhone undermines its security and makes you vulnerable. Running untrusted, third-party software could cause your device to be infected with malware.
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +The color of the message bubble in the Messages app indicates whether your messages are E2EE or not. A blue bubble indicates that you are using iMessage with E2EE, while a green bubble indicates they
```suggestion
The color of the message bubble in the Messages app indicates whether your messages are E2EE or not. A blue bubble indicates that you're using iMessage with E2EE, while a green bubble indicates they're using the outdated SMS and MMS protocols. Currently, the only way to get E2EE in Messages is for both parties to be using iMessage on Apple devices.
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +If either you or your messaging partner have iCloud Backup enabled, the encryption key will be stored on Apple's servers, meaning they can access your messages. Additionally, iMessage's key exchange
```suggestion
If either you or your messaging partner have iCloud Backup enabled, the encryption key will be stored on Apple's servers, meaning they can access your messages. Additionally, iMessage's key exchange is not as secure as alternative implementations, like Signal (which allows you to view the recipients key and verify by QR code), so it shouldn't be relied on for particularly sensitive communications.
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +If you need to hide information in a photo, you can use Apple's built-in tools to do so. Open the photo you want to edit, press edit at the top right corner of the screen, then press the markup symbo
```suggestion
If you need to hide information in a photo, you can use Apple's built-in tools to do so. Open the photo you want to edit, press edit at the top right corner of the screen, then press the markup symbol at the top right. Press the plus at the bottom right of the screen, then press the rectangle icon. Now, you can place a rectangle anywhere on the image. Make sure to press the shape icon at the bottom left and select the filled-in rectangle. **Don't** use the highlighter to obfuscate information, because its opacity is not quite 100%.
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +Apple always makes beta versions of iOS available early for those that wish to help find and report bugs. We do not recommend installing beta software on your phone. Beta releases are potentially uns
```suggestion
Apple always makes beta versions of iOS available early for those that wish to help find and report bugs. We don't recommend installing beta software on your phone. Beta releases are potentially unstable and could have undiscovered security vulnerabilities.
```

2022-10-19 20:15 UTC, KaiTebay commented on docs/ios/configuration.en.md
> +If your threat model includes forensic tools and you want to minimize the chance of exploits being used to access your phone, you should restart your device frequently. The state *after* a reboot but
```suggestion
If your threat model includes forensic tools and you want to minimize the chance of exploits being used to access your phone, you should restart your device frequently. The state *after* a reboot but *before* unlocking your device is referred to as "Before First Unlock" (BFU), and when your device is in that state it makes it [significantly more difficult](https://belkasoft.com/checkm8_glossary) for forensic tools to exploit vulnerabilities to access your data. This BFU state allows you to receive notifications for calls, texts, and alarms, but most of the data on your device is still encrypted and inaccessible. This can be impractical, so consider whether these trade-offs make sense for your situation.
```

2022-10-20 12:19 UTC, mfwmyfacewhen commented on docs/ios/configuration.en.md
> +- [ ] Turn off **Back Up This iPhone**
Yeah we definitely need to go back through those and change it for sure

2022-10-20 13:10 UTC, KaiTebay approved these changes
LGTM! :+1:

2022-10-22 06:21 UTC, dngray requested changes

2022-10-22 06:21 UTC, dngray commented on docs/ios/configuration.en.md
> +Select **Turn Passcode On** or **Change Passcode** > **Passcode Options** > **Custom Alphanumeric Code**. We have a guide on making secure passwords [here](../basics/passwords-overview.md).
```suggestion
Select **Turn Passcode On** or **Change Passcode** > **Passcode Options** > **Custom Alphanumeric Code**. Make sure that you create a [secure password](../basics/passwords-overview.md).
```

2022-10-22 06:21 UTC, dngray commented on docs/ios/configuration.en.md
> +**Lockdown Mode** is a security setting you can enable to make your phone more resistant to attacks. Be aware that certain apps and features won't work as they do normally: you should view [this](htt
```suggestion
**Lockdown Mode** is a security setting you can enable to make your phone more resistant to attacks. Be aware that certain apps and features [won't work](https://support.apple.com/en-us/HT212650) as they do normally.
```

2022-10-22 06:23 UTC, dngray approved these changes

2022-10-22 06:29 UTC, merged