GrapheneOS/CalyxOS Comparison Page Improvements
privacyguides/privacyguides.org pull request #1753
Opened 2022-09-12 17:57 UTC by matchboxbananasynergy

This PR will add a couple of new sections and re-word some of the old ones to make them fit the page's new title better and hopefully provide clarity as to why we recommend GrapheneOS and not CalyxOS.

2022-09-12 18:06 UTC, rusty-snake commented on docs/android/grapheneos-vs-calyxos.en.md
> +GrapheneOS significantly improves [user profiles](overview.md#user-profiles) in [multiple ways](https://grapheneos.org/features#improved-user-profiles), such as increasing the limit of how many profi
Is it only me who read this first as "disabling […] notification forwarding"?

2022-09-13 14:38 UTC, mfwmyfacewhen requested changes

2022-09-13 14:38 UTC, mfwmyfacewhen commented on docs/android/grapheneos-vs-calyxos.en.md
> +On CalyxOS, the app comes installed by default (regardless of whether you choose to have microG or not) and cannot be opted out of. This means that Google still has access to your hardware identifier
```suggestion
On CalyxOS, the app comes installed by default (regardless of whether you choose to have microG or not) and you cannot opt out of it. This means that Google still has access to your hardware identifiers regardless of whether or not you need eSIM activation and they can be accessed persistently.
```

2022-09-13 15:49 UTC, mfwmyfacewhen approved these changes

2022-09-13 17:47 UTC, jonaharagon approved these changes

2022-09-13 17:47 UTC, jonaharagon commented on docs/android/grapheneos-vs-calyxos.en.md
> +On CalyxOS, the app comes installed by default (regardless of whether you choose to have microG or not) and you cannot opt out of it. This means that Google still has access to your hardware identifi
```suggestion
On CalyxOS, the app comes installed by default (regardless of whether you choose to have microG or not) and you cannot opt-out. This means that Google still has access to your hardware identifiers regardless of whether or not you need eSIM activation and they can be accessed persistently.
```

2022-09-13 17:54 UTC, merged