Add Real-Time Communication Category to Knowledge Base
privacyguides/privacyguides.org pull request #1770
Opened 2022-09-15 22:19 UTC by matchboxbananasynergy

This PR:

- Removes the "Types of Communication Networks" section from the Real-Time Communication page, as it seems to be information that's best suited for the Knowledge Base.
- Creates Real-Time Communication Knowledge base Menu
- Adds Signal Configuration and Hardening page under the Real-Time Communication menu as well

2022-09-15 23:29 UTC, mfwmyfacewhen approved these changes

2022-09-16 08:17 UTC, purtual requested changes

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +- Server software can be verified that it matches public source code, assuming you have access to the server or you trust the person who does (e.g., a family member).
```suggestion
- Server software can be verified that it matches public source code, assuming you have access to the server, or you trust the person who does (e.g., a family member).
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +- Adding new features is more complex, because these features need to be standardized and tested to ensure they work with all servers on the network.
```suggestion
- Adding new features is more complex because these features need to be standardized and tested to ensure they work with all servers on the network.
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +Clients (peers) usually find each other through the use of a [distributed computing](https://en.wikipedia.org/wiki/Distributed_computing) network. Examples of this include [Distributed Hash Tables](h
```suggestion
Clients (peers) usually find each other through the use of a [distributed computing](https://en.wikipedia.org/wiki/Distributed_computing) network. Examples of this include [Distributed Hash Tables](https://en.wikipedia.org/wiki/Distributed_hash_table) (DHT), used by [torrents](https://en.wikipedia.org/wiki/BitTorrent_(protocol)) and [IPFS](https://en.wikipedia.org/wiki/InterPlanetary_File_System) for example. Another approach is proximity-based networks, where a connection is established over Wi-Fi or Bluetooth (for example, Briar or the [Scuttlebutt](https://www.scuttlebutt.nz) social network protocol).
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +- Messages can only be sent when both peers are online, however, your client may store messages locally to wait for the contact to return online.
```suggestion
- Messages can only be sent when both peers are online; however, your client may store messages locally to wait for the contact to return online.
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +- Generally increases battery usage on mobile devices, because the client must stay connected to the distributed network to learn about who is online.
```suggestion
- Generally increases battery usage on mobile devices because the client must stay connected to the distributed network to learn about who is online.
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +A messenger using [anonymous routing](https://doi.org/10.1007/978-1-4419-5906-5_628) hides either the identity of the sender, the receiver or evidence that they have been communicating. Ideally, a me
```suggestion
A messenger using [anonymous routing](https://doi.org/10.1007/978-1-4419-5906-5_628) hides either the identity of the sender, the receiver, or evidence that they have been communicating. Ideally, a messenger should hide all three.
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +There are [many](https://doi.org/10.1145/3182658) different ways to implement anonymous routing. One of the most famous is [onion routing](https://en.wikipedia.org/wiki/Onion_routing) (i.e. [Tor](../
```suggestion
There are [many](https://doi.org/10.1145/3182658) different ways to implement anonymous routing. One of the most famous is [onion routing](https://en.wikipedia.org/wiki/Onion_routing) (i.e. [Tor](../basics/tor-overview.md)), which communicates encrypted messages through a virtual [overlay network](https://en.wikipedia.org/wiki/Overlay_network) that hides the location of each node as well as the recipient and sender of each message. The sender and recipient never interact directly and only meet through a secret rendezvous node so that there is no leak of IP addresses nor physical location. Nodes cannot decrypt messages, nor the final destination; only the recipient can. Each intermediary node can only decrypt a part that indicates where to send the still encrypted message next, until it arrives at the recipient who can fully decrypt it, hence the "onion layers."
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +- Often limited to fewer media types, mostly text since the network is slow.
```suggestion
- Often limited to fewer media types, mostly text, since the network is slow.
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +- More complex to get started as the creation and secured backup of a cryptographic private key is required.
```suggestion
- More complex to get started, as the creation and secured backup of a cryptographic private key is required.
```

2022-09-16 08:17 UTC, purtual commented on docs/real-time-communication/communication-network-types.md
> +- Just like other decentralized platforms, adding features is more complex for developers than on a centralized platform, hence features may be lacking or incompletely implemented, such as offline me
```suggestion
- Just like other decentralized platforms, adding features is more complex for developers than on a centralized platform. Hence, features may be lacking or incompletely implemented, such as offline message relaying or message deletion.
```

2022-09-16 13:49 UTC, dngray approved these changes

2022-09-16 13:49 UTC, merged