Add warning about Proton VPN killswitch Intel Macs
privacyguides/privacyguides.org pull request #1780
Opened 2022-09-16 19:21 UTC by ph00lt0

Resolves: https://github.com/privacyguides/privacyguides.org/issues/1769

2022-09-16 19:48 UTC, jonaharagon commented on docs/vpn.en.md
> +??? danger "Killswitch feature is broken on Intel-based Macs"
```suggestion
!!! danger "Killswitch feature is broken on Intel-based Macs"
```

I don't know whether this is important enough to have in a danger box at all though. This might only warrant adding a single sentence like:

> The killswitch feature of the Proton VPN client [is known](https://protonvpn.com/support/macos-t2-chip-kill-switch/) to sometimes cause CPU kernel panics on Intel-based Mac computers.

to either the additional functionality box or the clients box above.

2022-11-18 23:17 UTC, mfwmyfacewhen approved these changes

2022-11-20 07:52 UTC, mfwmyfacewhen commented
> Thanks for taking this up @mfwmyfacewhen I didn't think about it anymore and wasn't sure where to take it to. If something needs to be changed still lmk.

Sure thing, just waiting on one more approval and I think it can be merged.

2022-11-21 13:16 UTC, freddy-m approved these changes

2022-11-21 15:38 UTC, blacklight447 approved these changes

2022-11-22 05:43 UTC, dngray commented on docs/vpn.en.md
> +??? danger "Killswitch feature is broken on Intel-based Macs"
I'm inclined to agree with @jonaharagon on this, we don't need to reproduce the [whole of that article](https://protonvpn.com/support/macos-t2-chip-kill-switch/) in the warning box

2022-11-22 05:44 UTC, dngray requested changes

2022-11-22 05:44 UTC, dngray commented on docs/vpn.en.md
> +    The killswitch feature of the Proton VPN client can cause CPU kernel panics on Intel-based Mac computers. The driver error can result in the Mac randomly shutting down after hibernation. Proton,
See https://github.com/privacyguides/privacyguides.org/pull/1780#discussion_r1028859807

2022-11-25 11:38 UTC, dngray approved these changes

2022-11-25 11:39 UTC, merged

2022-11-25 11:39 UTC, dngray approved these changes