Standardize download sections
privacyguides/privacyguides.org pull request #1826
Opened 2022-09-30 16:09 UTC by KaiTebay

### Addresses #1727

I've standardized the download sections according to @matchboxbananasynergy's order:

> 1. Play Store
> 2. App Store (this works for iOS, macOS and iPadOS)
> 3. GitHub/GitLab/Codeberg (or other alternatives, provided that they have a "Releases" section with downloads)
> 4. Windows (traditional .exe files)
> 5. macOS (this would be download links to .dmg files)
> 6. Linux (typically a link to .deb, .rpm files or instructions on how to add a repo for your distribution)
> 7. [PWAs/Extensions] (Browser name for extensions and either PWA or "Web" for PWAs)
> 8. FreeBSD
> 9. OpenBSD
> 10. NetBSD

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to publish your work under the [Creative Commons Attribution-NoDerivatives 4.0 International](https://github.com/privacyguides/privacyguides.org/blob/main/LICENSE) license, and to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform and distribute your contribution as part of our project.

2022-09-30 17:05 UTC, KaiTebay commented
**Points of Note**
- Included Cryptomator [Android](https://cryptomator.org/android) (I don't know whether it auto-updates).
- Included Signal [Android](https://signal.org/android/apk/) (because it auto-updates).
- Included Tor [Android](https://www.torproject.org/download/#android) (unsure).

- Included Docker Hub links for tools which already had them. There might be more tools where it makes sense to link to Docker Hub.
    - [EteSync](https://hub.docker.com/r/victorrds/etesync)
    - [Psono](https://hub.docker.com/r/psono/psono-client)

2022-09-30 17:52 UTC, jonaharagon requested changes
I think we should treat Flathub as another app store, so Flatpak links should be renamed to Flathub links, and any Flatpaks that aren't on Flathub should be labeled as a generic "Linux" download instead of Flatpak, if that makes sense.

2022-09-30 17:52 UTC, jonaharagon commented on docs/productivity.en.md
>          - [:simple-flathub: Flatpak](https://www.libreoffice.org/download/download/)
```suggestion
        - [:simple-flathub: Flathub](https://flathub.org/apps/details/org.libreoffice.LibreOffice)
```

2022-09-30 17:52 UTC, jonaharagon commented on docs/real-time-communication.en.md
> +        - [:simple-flathub: Flatpak](https://flathub.org/apps/details/org.briarproject.Briar)
```suggestion
        - [:simple-flathub: Flathub](https://flathub.org/apps/details/org.briarproject.Briar)
```

2022-09-30 17:52 UTC, jonaharagon commented on docs/calendar-contacts.en.md
>          - [:simple-flathub: Flatpak](https://flathub.org/apps/details/com.tutanota.Tutanota)
```suggestion
        - [:simple-flathub: Flathub](https://flathub.org/apps/details/com.tutanota.Tutanota)
```

2022-09-30 17:52 UTC, jonaharagon commented on docs/encryption.en.md
>          - [:simple-flathub: Flatpak](https://flathub.org/apps/details/org.cryptomator.Cryptomator)
```suggestion
        - [:simple-flathub: Flathub](https://flathub.org/apps/details/org.cryptomator.Cryptomator)
```

2022-09-30 17:52 UTC, jonaharagon commented on docs/passwords.en.md
>          - [:simple-flathub: Flatpak](https://flathub.org/apps/details/com.bitwarden.desktop)
```suggestion
        - [:simple-flathub: Flathub](https://flathub.org/apps/details/com.bitwarden.desktop)
```

2022-10-01 10:58 UTC, KaiTebay commented
> Another note is that since we're keeping Flathub links, we should comb through all of the tools we recommend and add missing flatpaks for them too. KeePassXC comes to mind. Also, should we only list official flatpaks, or are community maintained ones valid as well?

I'll update all of the tools with Flathub links and mark whether they're maintained officially or by the community so that we can decide.

2022-10-11 05:55 UTC, dngray approved these changes

2022-10-11 05:59 UTC, merged