Writing review of common-threats.en.md
privacyguides/privacyguides.org pull request #1836
Opened 2022-10-13 13:35 UTC by KaiTebay

**Notes**

Need citation:
> The best example of this is trusting data to Google who, given their scale, have had few security incidents by employing industry-leading security experts to secure their infrastructure.

> Generally, mobile operating systems have better application sandboxing than desktop operating systems: Apps cannot obtain root access, and require permission for access to system resources.

> Linux tends to not submit information to system vendors, but it has poor protection against exploits and malicious apps.

> Governments often justify mass surveillance programs as necessary means to combat terrorism and prevent crime.

> However it is most often used to disproportionately target minorities, political dissidents, and many other groups to create a chilling effect on free speech.

> Pervasive ad networks, like those operated by Google and Facebook, span the internet far beyond just the sites they control, tracking your actions along the way.

> Censorship on corporate platforms is increasingly common, as platforms like Twitter and Facebook give in to public demand, market pressures, and pressures from government agencies.

> the Chinese government requiring companies to adhere to a strict regime of censorship.

> For example, you may want to avoid Google Drive, which gives Google access to all of your data.

> This pseudonym isn't anonymous because—if monitored for long enough—details about the owner can reveal further information, such as the way they write, their general knowledge about topics of interest, etc.

> It is also worth noting that greater anonymity is possible through asynchronous communication: Real-time communication is vulnerable to analysis of typing patterns (i.e. more than a paragraph of text, distributed on a forum, via email, etc.)

References (with further information) would be helpful:
> Pluggable transports can help you evade firewalls that block common VPN protocols or Tor, but your circumvention attempts can still be detected by methods like probing :warning: or deep packet inspection. :heavy_check_mark:

> Employing alt-coin shifting may also help disguise where your currency originated.

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to publish your work under the [Creative Commons Attribution-NoDerivatives 4.0 International](https://github.com/privacyguides/privacyguides.org/blob/main/LICENSE) license, and to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform and distribute your contribution as part of our project.

2022-10-13 14:31 UTC, jonaharagon reviewed
.

2022-10-13 16:37 UTC, jonaharagon requested changes
These re-wordings generally LGTM. I think there's a lot of comma over-use in this PR, and I suggested a few other minor changes as well.

2022-10-13 16:37 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +2. And, you should still use other techniques, like E2EE, to protect your data completely. Merely distrusting one provider to trust another is not securing your data.
I don't know which of these is the proper way to write this, but I don't like list items beginning with "and."

```suggestion
1. You must exercise caution when choosing a provider to shift trust to; and
2. You should still use other techniques, like E2EE, to protect your data completely. Merely distrusting one provider to trust another is not securing your data.
```

```suggestion
1. You must exercise caution when choosing a provider to shift trust to;
2. You should still use other techniques, like E2EE, to protect your data completely. Merely distrusting one provider to trust another is not securing your data.
```

```suggestion
1. You must exercise caution when choosing a provider to shift trust to.
2. You should still use other techniques, like E2EE, to protect your data completely. Merely distrusting one provider to trust another is not securing your data.
```

2022-10-13 16:37 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +Focusing solely on the privacy policies and marketing of a tool or provider can blind you to its weaknesses. When you're looking for a more private solution, you should determine what the underlying
```suggestion
Focusing solely on the privacy policies and marketing of a tool or provider can blind you to its weaknesses. When you're looking for a more private solution, you should determine what the underlying problem is and find technical solutions to that problem. For example, you may want to avoid Google Drive, which gives Google access to all of your data. The underlying problem in this case is lack of E2EE, so you should make sure that the provider you switch to actually implements E2EE, or use a tool (like [Cryptomator](encryption.md#cryptomator-cloud)) which provides E2EE on any cloud provider. Switching to a "privacy-focused" provider (that doesn't implement E2EE) doesn't solve your problem: it just shifts trust from Google to that provider.
```

2022-10-13 16:37 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +1. **Known identity** - A known identity is used for things where you must declare your name. There are many legal documents and contracts where a legal identity is required. This could range from op
```suggestion
1. **Known identity** - A known identity is used for things where you must declare your name. There are many legal documents and contracts where a legal identity is required. This could range from opening a bank account, signing a property lease, obtaining a passport, customs declarations when importing items, or otherwise dealing with your Government. These things will usually lead to credentials such as credit cards, credit rating checks, account numbers, and possibly physical addresses.
```

2022-10-13 16:37 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +    You may wish to use a VPN for this, to mask your IP address. Financial transactions are more difficult and, for this, we suggest using anonymous cryptocurrencies, such as [Monero](https://www.get
```suggestion
    You may wish to use a VPN for this, to mask your IP address. Financial transactions are more difficult to mask: You could consider using anonymous cryptocurrencies, such as [Monero](https://www.getmonero.org/). Employing altcoin shifting may also help to disguise where your currency originated. Typically, exchanges require KYC (know your customer) to be completed before they'll allow you to exchange fiat currency into any kind of cryptocurrency. Local meet-up options may also be a solution; however, those are often more expensive and sometimes also require KYC.
```

2022-10-13 17:23 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +Some of these threats may be more important to you than others, depending on your specific concerns. For example, a software developer with access to valuable or critical data may be primarily concer
"Beyond that" is an embedded clause, so this one is necessary.

2022-10-13 17:25 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +    By design, **web browsers**, **email clients**, and **office applications** typically run untrusted code, sent to you from third parties. Running multiple virtual machines—to separate application
Similarly, "on Windows" is an embedded clause, so the commas are necessary.

2022-10-13 17:37 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +We live in a world where almost everything is connected to the internet. Our messages, emails, and social interactions are typically stored on a server, somewhere. Generally, when you send someone a
Sounds good! I'll retain "private" message.

"when you send someone a message" is an embedded clause, though, so comma is necessary.

The second part should be revised to either retain the comma and embed the conditional phrase:

> it's then stored on a server, and, when your friend wants to read the message, the server will show it to them.

Or, it should use a semi-colon and have the conditional phrase become a subordinate clause:

> it's then stored on a server; when your friend wants to read the message, the server will show it to them.

2022-10-13 18:42 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +Focusing solely on the privacy policies and marketing of a tool or provider can blind you to its weaknesses. When you're looking for a more private solution, you should determine what the underlying
"in this case" is parenthetical, so it should either be an embedded clause or using other punctuation, like parentheses.

2022-10-13 18:43 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +2. And, you should still use other techniques, like E2EE, to protect your data completely. Merely distrusting one provider to trust another is not securing your data.
If that's the stylistic preference, then I think the last suggestion makes the most sense—I'll commit the changes.

2022-10-13 18:48 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +People concerned with the threat of censorship can use technologies like [Tor](basics/tor-overview.md) to circumvent it, and support platforms which provide censorship-resistant communication, such a
Since the last clause is parenthetical and has "Matrix" as its object (i.e. "such as Matrix" isn't an embedded clause), I think an em dash is most appropriate here. 

Perhaps clearer phrasing is better, instead.

2022-10-15 04:19 UTC, dngray approved these changes
I went through this, and I think it's a vast improvement on readability.

2022-10-15 04:22 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +Focusing solely on the privacy policies and marketing of a tool or provider can blind you to its weaknesses. When you're looking for a more private solution, you should determine what the underlying
I don't think you are correct, "in this case" is a restrictive clause because it is necessary to the meaning of the sentence. For the reader to know where the problem exists and what the solution is, they need to be aware of the example case referenced in the preceding sentence about Google Drive.

If you write it in the way you are suggesting, the sentence would have to make sense in a context in which the example doesn't exist, like so:

> When you're looking for a more private solution, you should determine what the underlying problem is and find technical solutions to that problem. ~~For example, you may want to avoid Google Drive, which gives Google access to all of your data.~~ The underlying problem ~~in this case~~ is lack of E2EE, so you should make sure that the provider you switch to actually implements E2EE [...]

> When you're looking for a more private solution, you should determine what the underlying problem is and find technical solutions to that problem. The underlying problem is lack of E2EE, so you should make sure that the provider you switch to actually implements E2EE [...]

However, this paragraph clearly does *not* make sense, because "lack of E2EE" is a problem specific to providers like Google Drive and not *the* only problem to consider.

https://en.wikipedia.org/wiki/Dependent_clause#Punctuation

2022-10-15 04:35 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +People concerned with the threat of censorship can use technologies like [Tor](basics/tor-overview.md) to circumvent it, and support platforms which provide censorship-resistant communication, such a
I think clearer phrasing would be better. As I read this I also wonder if "which doesn't have a centralized account authority that can close accounts arbitrarily." could be removed entirely, since we explain how Matrix works in the linked listing. Maybe:

> [...] and support communication platforms without centralized authorities that can close accounts and block content arbitrarily, like Matrix.

2022-10-15 04:37 UTC, dngray commented on docs/basics/common-threats.en.md
> +Focusing solely on the privacy policies and marketing of a tool or provider can blind you to its weaknesses. When you're looking for a more private solution, you should determine what the underlying
> in this case

Maybe it should be "in that case"?

2022-10-15 04:41 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +    On the other hand, web-based E2EE implementations, such as ProtonMail's webmail or Bitwarden's *Web Vault*, rely on the server dynamically serving JavaScript code to the browser to handle cryptog
@dngray's getting a little trigger-happy with that "commit suggestion" button https://github.com/privacyguides/privacyguides.org/pull/1836#discussion_r994945666 :)

```suggestion
    On the other hand, web-based E2EE implementations, such as Proton Mail's webmail or Bitwarden's *Web Vault*, rely on the server dynamically serving JavaScript code to the browser to handle cryptography. A malicious server can target you and send you malicious JavaScript code to steal your encryption key (and it would be extremely hard to notice). Because the server can choose to serve different web clients to different people—even if you noticed the attack—it would be incredibly hard to prove the provider's guilt.
```

2022-10-15 04:41 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +We live in a world where almost everything is connected to the internet. Our messages, emails, and social interactions are typically stored on a server, somewhere. Generally, when you send someone a
I disagree, but this is the same issue as https://github.com/privacyguides/privacyguides.org/pull/1836#discussion_r996249862 I think?

2022-10-15 04:44 UTC, jonaharagon submitted a review, later dismissed

2022-10-15 04:44 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +Some of these threats may be more important to you than others, depending on your specific concerns. For example, a software developer with access to valuable or critical data may be primarily concer
```suggestion
Some of these threats may be more important to you than others, depending on your specific concerns. For example, a software developer with access to valuable or critical data may be primarily concerned with <span class="pg-red">:material-target-account: Targeted Attacks</span>, but they probably still want to protect their personal data from being swept up in <span class="pg-blue">:material-eye-outline: Mass Surveillance</span> programs. Similarly, many people may be primarily concerned with <span class="pg-green">:material-account-search: Public Exposure</span> of their personal data, but they should still be wary of security-focused issues, such as <span class="pg-orange">:material-bug-outline: Passive Attacks</span>—like malware affecting their devices.
```

Not sure I agree with https://github.com/privacyguides/privacyguides.org/pull/1836#discussion_r994926735 but I think this is a better solution anyways.

2022-10-15 04:50 UTC, jonaharagon commented on docs/basics/common-threats.en.md
> +People concerned with the threat of censorship can use technologies like [Tor](tor-overview.md) to circumvent it, and support platforms which provide censorship-resistant communication, such as [Matr
Suggestion from https://github.com/privacyguides/privacyguides.org/pull/1836#discussion_r996251190

```suggestion
People concerned with the threat of censorship can use technologies like [Tor](tor-overview.md) to circumvent it, and support communication platforms without centralized authorities that can close accounts and block content arbitrarily, like [Matrix](../real-time-communication.md#element).
```

Although, I think this might make even more sense:

```suggestion
People concerned with the threat of censorship can use technologies like [Tor](tor-overview.md) to circumvent it, and support censorship-resistant communication platforms like [Matrix](../real-time-communication.md#element), which doesn't have a centralized account authority that can close accounts arbitrarily.
```

2022-10-15 08:55 UTC, dngray commented on docs/basics/common-threats.en.md
> +    On the other hand, web-based E2EE implementations, such as ProtonMail's webmail or Bitwarden's *Web Vault*, rely on the server dynamically serving JavaScript code to the browser to handle cryptog
> @dngray's getting a little trigger-happy with that "commit suggestion" button https://github.com/privacyguides/privacyguides.org/pull/1836#discussion_r994945666 :)

Oops. I missed that one.

2022-10-15 08:59 UTC, dngray commented on docs/basics/common-threats.en.md
> +Some of these threats may be more important to you than others, depending on your specific concerns. For example, a software developer with access to valuable or critical data may be primarily concer
Yes, i really don't like superfluous words like "beyond that". Pretty sure when this page was originally written i didn't get to check thoroughly.

2022-10-15 09:00 UTC, dngray commented on docs/basics/common-threats.en.md
> +People concerned with the threat of censorship can use technologies like [Tor](tor-overview.md) to circumvent it, and support platforms which provide censorship-resistant communication, such as [Matr
I like the last one, sounds less "wordy".

2022-10-15 11:45 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +Focusing solely on the privacy policies and marketing of a tool or provider can blind you to its weaknesses. When you're looking for a more private solution, you should determine what the underlying
That's a fair point, and I understand what you mean. I felt that the context of the previous sentence clarified the object (i.e. "the underlying problem" refers to the example), so the "in this case" is non-restrictive. Hence, it's parenthetical.

**But**, I agree: I don't think the relationship is as clear as I thought, so erring on the side of caution (i.e. reading it in a restrictive sense) seems like good practice. Unnecessary is definitely best avoided! :smile:

2022-10-15 12:37 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +People concerned with the threat of censorship can use technologies like [Tor](tor-overview.md) to circumvent it, and support platforms which provide censorship-resistant communication, such as [Matr
Yeah these suggestions are much more readable, imo. I'll merge the last one!

2022-10-15 12:49 UTC, KaiTebay commented on docs/basics/common-threats.en.md
> +We live in a world where almost everything is connected to the internet. Our messages, emails, and social interactions are typically stored on a server, somewhere. Generally, when you send someone a
It looks like this has been overwritten, but this one is tricky.

Despite "generally" acting as the [introductory phrase](https://dictionary.cambridge.org/us/example/english/generally), "when you send someone a message" uses "when" as a conjunction and precedes an independent clause, so [it does need a comma](https://dictionary.cambridge.org/grammar/british-grammar/when). [These](https://www.pristineword.com/comma-when/) are some good examples. This is also true for "when your friend wants to read the message, the server..."

It's weird because you're right in that they *are* both restrictive dependent clauses, but it's just a thing with when-clauses.

Finally, the comma before and is fine, since it [bridges a complex sentence](https://www.grammarly.com/blog/comma-in-complex-sentences/). 

I don't actually know whether a comma is needed *after* "and" (i.e. to introduce the when-clause"), but I think it's clear either way! :smile: 

Note: I don't think any of these rules are different for American English, but just lmk if they are!

2022-10-15 14:44 UTC, merged