Add Send & ffsend to File Sharing page
privacyguides/privacyguides.org pull request #1837
Opened 2022-10-13 22:54 UTC by matchboxbananasynergy

This PR adds Send and ffsend to the File Sharing section after the discussion which took place on our forum:
https://discuss.privacyguides.org/t/add-send-firefox-send-fork-to-the-file-sharing-and-sync-page/

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to publish your work under the [Creative Commons Attribution-NoDerivatives 4.0 International](https://github.com/privacyguides/privacyguides.org/blob/main/LICENSE) license, and to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform and distribute your contribution as part of our project.

2022-10-13 23:01 UTC, jonaharagon commented on docs/file-sharing.en.md
> +`ffsend upload --host https://send.vis.ee/ FILE`
I can't figure out how to make a GitHub suggestion with this change because it interferes with the Markdown syntax, but this should be a code block like with <code>```</code> above and below it.

2022-10-13 23:02 UTC, jonaharagon commented on docs/file-sharing.en.md
> +`ffsend upload --host https://send.vis.ee/ FILE`
````suggestion
```
ffsend upload --host https://send.vis.ee/ FILE
```
````

2022-10-13 23:36 UTC, jonaharagon approved these changes

2022-10-13 23:38 UTC, jonaharagon commented on docs/file-sharing.en.md
> +     **Send** is a fork of Mozilla’s discontinued Firefox Send service which allows you to send files to others with a link. Files are encrypted on your device so that they cannot be read by the serv
```suggestion
    **Send** is a fork of Mozilla’s discontinued Firefox Send service which allows you to send files to others with a link. Files are encrypted on your device so that they cannot be read by the server, and they can be optionally password-protected as well. The maintainer of Send hosts a [public instance](https://send.vis.ee/). You can use other public instances, or you can host Send yourself.
```

2022-10-14 07:44 UTC, KaiTebay requested changes
I've suggested a minor abbreviation edit; otherwise, it looks great!

2022-10-14 07:44 UTC, KaiTebay commented on docs/file-sharing.en.md
> +Send can be used via its web interface or via [ffsend](https://github.com/timvisee/ffsend), a command-line client. If you are familiar with the command-line and send files frequently, we recommend us
```suggestion
Send can be used via its web interface or via [ffsend](https://github.com/timvisee/ffsend), a CLI. 
```

There's an abbreviation for "CLI" in abbreviations.en.md, so it could be worth just shortening this (unless that shifts the meaning too much)?

2022-10-14 15:26 UTC, dngray approved these changes

2022-10-14 15:38 UTC, jonaharagon commented on docs/file-sharing.en.md
> +```text
Instead of https://github.com/privacyguides/privacyguides.org/pull/1837#discussion_r995448697? Also pretty sure this should be `bash` not `text` as a shell command.

````suggestion
Send can be used via its web interface or via the [ffsend](https://github.com/timvisee/ffsend) CLI. If you are familiar with the command-line and send files frequently, we recommend using the CLI client to avoid JavaScript-based encryption. You can specify the `--host` flag to use a specific server:

```bash
````

2022-10-14 15:39 UTC, jonaharagon commented on docs/file-sharing.en.md
> +Send can be used via its web interface or via [ffsend](https://github.com/timvisee/ffsend), a command-line client. If you are familiar with the command-line and send files frequently, we recommend us
https://github.com/privacyguides/privacyguides.org/pull/1837#discussion_r995893881

2022-10-14 15:56 UTC, dngray commented on docs/file-sharing.en.md
> +Send can be used via its web interface or via [ffsend](https://github.com/timvisee/ffsend), a command-line client. If you are familiar with the command-line and send files frequently, we recommend us
Hmm, i think removing this warning would be a bad idea.

Maybe an admonishment would be best.

2022-10-14 17:09 UTC, merged