KB Cleanup
privacyguides/privacyguides.org pull request #1848
Opened 2022-10-18 20:43 UTC by jonaharagon

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to publish your work under the [Creative Commons Attribution-NoDerivatives 4.0 International](https://github.com/privacyguides/privacyguides.org/blob/main/LICENSE) license, and to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform and distribute your contribution as part of our project.

2022-10-19 05:45 UTC, mfwmyfacewhen requested changes

2022-10-19 05:45 UTC, mfwmyfacewhen commented on docs/basics/common-misconceptions.en.md
> +Focusing solely on the privacy policies and marketing of a tool or provider can blind you to its weaknesses. When you're looking for a more private solution, you should determine what the underlying
Google Drive seems to actually have [optional E2EE](https://support.google.com/docs/answer/10519333?hl=en). Maybe iCloud would be a better example.

2022-10-19 05:45 UTC, mfwmyfacewhen commented on docs/basics/common-misconceptions.en.md
> +1. **Known identity** - A known identity is used for things where you must declare your name. There are many legal documents and contracts where a legal identity is required. This could range from op
```suggestion
1. **Known identity** - A known identity is used for things where you must declare your name. There are many legal documents and contracts where a legal identity is required. This could range from opening a bank account, signing a property lease, obtaining a passport, customs declarations when importing items, or otherwise dealing with your government. These things will usually lead to credentials such as credit cards, credit rating checks, account numbers, and possibly physical addresses.
```

2022-10-19 05:45 UTC, mfwmyfacewhen commented on docs/basics/common-misconceptions.en.md
> +    Using Tor can help with this. It is also worth noting that greater anonymity is possible through asynchronous communication: Real-time communication is vulnerable to analysis of typing patterns (
```suggestion
    Using Tor can help with this. It is also worth noting that greater anonymity is possible through asynchronous communication; real-time communication is vulnerable to analysis of typing patterns (i.e. more than a paragraph of text, distributed on a forum, via email, etc.)
```

2022-10-20 10:25 UTC, KaiTebay approved these changes
Changes look good. I really like the restructuring: from the preview, I think it's much clearer!

2022-10-20 23:07 UTC, jonaharagon commented on docs/basics/common-misconceptions.en.md
> +    Using Tor can help with this. It is also worth noting that greater anonymity is possible through asynchronous communication: Real-time communication is vulnerable to analysis of typing patterns (
I think it makes more sense as-is.

2022-10-21 05:26 UTC, mfwmyfacewhen approved these changes

2022-10-22 05:56 UTC, merged