Clarify email criteria
privacyguides/privacyguides.org pull request #1873
Opened 2022-10-25 15:44 UTC by jonaharagon

https://discuss.privacyguides.org/t/relaxing-email-tls-requirements-on-smtp-port-25/1938/6?u=jonah

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

2022-10-26 02:41 UTC, dngray approved these changes

2022-10-27 07:33 UTC, KaiTebay requested changes
Suggested minor grammatical fixes. Otherwise, :+1:

2022-10-27 07:33 UTC, KaiTebay commented on docs/email.en.md
> +- No TLS errors or vulnerabilities when being profiled by tools such as [Hardenize](https://www.hardenize.com/), [testssl.sh](https://testssl.sh/) or [Qualys SSL Labs](https://www.ssllabs.com/ssltest
```suggestion
- No TLS errors or vulnerabilities when being profiled by tools such as [Hardenize](https://www.hardenize.com/), [testssl.sh](https://testssl.sh/), or [Qualys SSL Labs](https://www.ssllabs.com/ssltest); this includes certificate related errors and weak DH parameters, such as those that led to [Logjam](https://en.wikipedia.org/wiki/Logjam_(computer_security)).
```

Just fixes a comma splice and some minor details.

2022-10-31 12:29 UTC, mfwmyfacewhen approved these changes

2022-10-31 13:49 UTC, KaiTebay approved these changes
LGTM!

2022-11-01 21:55 UTC, merged