About category changes
privacyguides/privacyguides.org pull request #1875
Opened 2022-10-26 00:24 UTC by jonaharagon

Related to https://discuss.privacyguides.org/t/github-wiki/6207

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

2022-10-26 12:26 UTC, freddy-m approved these changes
LGTM! Will this exist along with a GitHub wiki, or will that be shelved?

2022-10-31 12:29 UTC, mfwmyfacewhen approved these changes

2022-10-31 21:59 UTC, blacklight447 reviewed
It looks great, but wouldn't we want to add profile pictures as well?

2022-10-31 22:06 UTC, freddy-m commented
Not sure PFPs are needed, but website links could be cool 👀

2022-10-31 22:14 UTC, blacklight447 approved these changes

2022-10-31 22:26 UTC, mfwmyfacewhen requested changes

2022-10-31 22:26 UTC, mfwmyfacewhen commented on docs/about/index.md
> +    - [:simple-github: GitHub](https://github.com/mfwmyfacewhen "@mfwmyfacewhen")
```suggestion
    - [:simple-github: GitHub](https://github.com/mfwmyfacewhen "@mfwmyfacewhen")
    -[:fontawesome-solid-house: Homepage](https://mfw.omg.lol)
```

2022-11-01 08:52 UTC, mfwmyfacewhen approved these changes

2022-11-01 09:45 UTC, blacklight447 approved these changes

2022-11-01 21:42 UTC, KaiTebay commented on docs/about/index.md
> +    - [:simple-github: GitHub](https://github.com/KaiTebay "@KaiTebay")
```suggestion
    - [:simple-github: GitHub](https://github.com/KaiTebay "@KaiTebay")
    - [:fontawesome-solid-house: Homepage](https://kaitebay.com) 
```

2022-11-01 21:54 UTC, merged