Add SimpleX Chat
privacyguides/privacyguides.org pull request #1893
Opened 2022-11-16 12:53 UTC by dngray

Discussed in https://github.com/privacyguides/privacyguides.org/discussions/454

We've decided to add this after some preliminary testing, and the audit was released https://simplex.chat/blog/20221108-simplex-chat-v4.2-security-audit-new-website.html

2022-11-16 13:19 UTC, mfwmyfacewhen requested changes

2022-11-21 13:18 UTC, freddy-m approved these changes

2022-11-21 20:44 UTC, mfwmyfacewhen approved these changes

2022-11-25 10:43 UTC, merged

2022-11-25 13:02 UTC, epoberezkin commented
Thank you!!! This is big for us, we really appreciate the support