Recommend against Nextcloud E2EE
privacyguides/privacyguides.org pull request #1901
Opened 2022-11-30 11:02 UTC by dngray

This is something we should have recommended against some time ago:

- https://discuss.privacyguides.net/t/remove-nextcloud-e2e-recommendation/10352/7
- https://github.com/privacyguides/privacyguides.org/discussions/1484

It doesn't look like it's made a whole lot of progress either:

- https://github.com/privacytools/privacytools.io/issues/2054
- https://github.com/privacytools/privacytools.io/issues/197

2022-11-30 22:18 UTC, mfwmyfacewhen requested changes

2022-11-30 22:18 UTC, mfwmyfacewhen commented on docs/cloud.en.md
> +    We don't recommend the use of the [E2EE App](https://apps.nextcloud.com/apps/end_to_end_encryption) for Nextcloud as it may lead to data loss, is highly experimental and not production quality.
```suggestion
    We don't recommend the use of the [E2EE App](https://apps.nextcloud.com/apps/end_to_end_encryption) for Nextcloud as it may lead to data loss; it is highly experimental and not production quality.
```

2022-12-01 07:50 UTC, mfwmyfacewhen approved these changes

2022-12-02 00:25 UTC, freddy-m approved these changes

2022-12-02 00:26 UTC, merged