Add ProxiTok
privacyguides/privacyguides.org pull request #1926
Opened 2023-01-05 09:50 UTC by dngray

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

This came up in the discussion thread https://discuss.privacyguides.net/t/add-proxitok-to-frontends-in-software/11370

It could be useful, when wanting to view a TikTok through Tor.

2023-01-05 12:08 UTC, freddy-m commented
> It could be useful

It if only _could_ be useful and we're unsure how stable it is then we shouldn't rush into adding it.

2023-01-05 12:34 UTC, freddy-m approved these changes
LGTM

2023-01-05 12:41 UTC, freddy-m commented on docs/frontends.en.md
> +## Tik Tok
Good spot!

2023-01-05 13:04 UTC, mfwmyfacewhen requested changes

2023-01-05 13:04 UTC, mfwmyfacewhen commented on docs/frontends.en.md
> +When you are using an ProxiTok instance, make sure to read the privacy policy of that specific instance. ProxiTok instances can be modified by their owners and therefore may not reflect their associa
```suggestion
When you are using a ProxiTok instance, make sure to read the privacy policy of that specific instance. ProxiTok instances can be modified by their owners and therefore may not reflect their associated privacy policy. Some instances have Tor .onion addresses which may grant some privacy as long as your search queries don't contain PII.
```

2023-01-05 13:15 UTC, dngray commented
> Is it stable/robust nowadays? I'd tried it a while ago to see if it could be considered, but it was inconsistent.

Well I was using it before, to [view](https://proxitok.pabloferreiro.es/%40polarbearsinternational/video/7168992335559363886) [some](https://proxitok.pabloferreiro.es/%40polarbearsinternational/video/7171515750316821802) [videos](https://proxitok.pabloferreiro.es/%40polarbearsinternational/video/7184475705768414506).

2023-01-05 13:17 UTC, mfwmyfacewhen approved these changes

2023-01-06 17:19 UTC, merged

2023-01-07 14:58 UTC, dngray commented
bleh i should have made this a draft, as I was waiting on a SVG from the author, which I now have.