Mention "Atlas of Surveillance" in the "Mass Surveillance" section
privacyguides/privacyguides.org pull request #1951
Opened 2023-01-22 16:09 UTC by Kefaku

Added a mention of the Atlas of Surveillance to the Mass Surveillance section, since that might be a useful/interesting resource for some people.

- [X] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [X] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [X] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

2023-01-29 22:49 UTC, mfwmyfacewhen requested changes

2023-01-29 22:49 UTC, mfwmyfacewhen commented on docs/basics/common-threats.en.md
> +    If you want to learn more about surveillance methods and their usage you can also take a look at the [Atlas of Surveillance](https://atlasofsurveillance.org/) by the [Electronic Frontier Foundati
```suggestion
    If you want to learn more about surveillance methods and how they're implemented in your city you can also take a look at the [Atlas of Surveillance](https://atlasofsurveillance.org/) by the [Electronic Frontier Foundation](https://www.eff.org/).
```

2023-01-30 05:49 UTC, mfwmyfacewhen approved these changes

2023-02-06 08:40 UTC, dngray approved these changes

2023-02-06 08:40 UTC, merged