Adds Yattee to "Frontends"
privacyguides/privacyguides.org pull request #1955
Opened 2023-01-26 17:32 UTC by gonzoknows

Adds Yattee to "Frontends" 

Note:
I'm unable to upload .svg so currently set the logo to the remote GitHub URL to pull the image from. 

- closes #1954 and #457

- [ ] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [ ] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [ ] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

2023-02-03 22:30 UTC, mfwmyfacewhen commented
I downloaded Yattee to try it out and it's not loading any videos for me for some reason.

2023-02-04 01:39 UTC, gonzoknows commented
> I downloaded Yattee to try it out and it's not loading any videos for me for some reason.

You need to add a piped or invidious instance to custom locations

2023-02-04 02:57 UTC, gonzoknows commented
> I downloaded Yattee to try it out and it's not loading any videos for me for some reason.

Also, I would currently recommend using piped instances as invidious recently updated their API so Yattee still has to push an update as shown in this issue 
https://github.com/yattee/yattee/issues/391

2023-02-04 03:36 UTC, mfwmyfacewhen commented
Thanks, I got it to work with your guide. Might link to that if that's ok with you, it's very helpful.

2023-02-04 03:40 UTC, gonzoknows commented
> Thanks, I got it to work with your guide. Might link to that if that's ok with you, it's very helpful.

Definitely! I would appreciate that a lot, thanks.

2023-02-06 08:46 UTC, dngray requested changes

2023-02-06 08:46 UTC, dngray commented on docs/frontends.en.md
> +    ![Yattee logo](https://camo.githubusercontent.com/5acbbe712241861ba5c9fd0011e702f577b661f499f1fc7ffbcca32f37f4320c/68747470733a2f2f722e7961747465652e73747265616d2f69636f6e732f7961747465652d313530
We don't do third party images for the logo.

Is there a SVG image of this logo?

2023-02-06 09:00 UTC, mfwmyfacewhen commented on docs/frontends.en.md
> +    ![Yattee logo](https://camo.githubusercontent.com/5acbbe712241861ba5c9fd0011e702f577b661f499f1fc7ffbcca32f37f4320c/68747470733a2f2f722e7961747465652e73747265616d2f69636f6e732f7961747465652d313530
Couldn't find one yet, that's why it's still a draft. Was meaning to ask the dev.

2023-02-06 09:22 UTC, dngray commented on docs/frontends.en.md
> +    ![Yattee logo](https://camo.githubusercontent.com/5acbbe712241861ba5c9fd0011e702f577b661f499f1fc7ffbcca32f37f4320c/68747470733a2f2f722e7961747465652e73747265616d2f69636f6e732f7961747465652d313530
I've emailed the main developer, maybe they will have one for us.

2023-02-12 18:33 UTC, arekf commented on docs/frontends.en.md
> +    ![Yattee logo](https://camo.githubusercontent.com/5acbbe712241861ba5c9fd0011e702f577b661f499f1fc7ffbcca32f37f4320c/68747470733a2f2f722e7961747465652e73747265616d2f69636f6e732f7961747465652d313530
Sorry, but I don't have this logo in SVG. What is more is that Apple has problem with it and was rejecting some App Store submissions with it so I will need to change it to something else.

I can let you know once I have a new logo in SVG in the future.

2023-02-12 20:47 UTC, gonzoknows commented on docs/frontends.en.md
> +    ![Yattee logo](https://camo.githubusercontent.com/5acbbe712241861ba5c9fd0011e702f577b661f499f1fc7ffbcca32f37f4320c/68747470733a2f2f722e7961747465652e73747265616d2f69636f6e732f7961747465652d313530
> Sorry, but I don't have this logo in SVG. What is more is that Apple has problem with it and was rejecting some App Store submissions with it so I will need to change it to something else.
> 
> I can let you know once I have a new logo in SVG in the future.

Thank you, once you have a .svg feel free to add it to this thread or email back a copy

2023-02-13 07:26 UTC, dngray commented on docs/frontends.en.md
> +    ![Yattee logo](https://camo.githubusercontent.com/5acbbe712241861ba5c9fd0011e702f577b661f499f1fc7ffbcca32f37f4320c/68747470733a2f2f722e7961747465652e73747265616d2f69636f6e732f7961747465652d313530
@arekf 

I recreated your logo as a SVG, was simple enough, looks pretty close to the original except maybe for the fillet radius on the outer object:

![svg](https://user-images.githubusercontent.com/48640805/218395965-7102f460-3835-4d8b-80ad-23c1c192111d.png)

Here's the SVG

![yattee](https://user-images.githubusercontent.com/48640805/218396085-ee30c148-d5db-4a8a-bb9a-7b57f7e65adc.svg)

2023-02-14 15:48 UTC, dngray approved these changes

2023-02-14 16:02 UTC, jonaharagon approved these changes

2023-02-14 16:03 UTC, jonaharagon requested changes
you reverted the fix

2023-02-14 16:09 UTC, jonaharagon approved these changes

2023-02-14 16:10 UTC, merged

2023-02-14 16:17 UTC, arekf commented
Thanks to everyone for featuring Yattee on Privacy Guides ☺️ Especially to @dngray for taking effort to replicate the logo in SVG.