Define criteria on all recommendation pages
privacyguides/privacyguides.org pull request #1980
Opened 2023-02-14 20:21 UTC by jonaharagon

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

2023-02-14 22:49 UTC, jonaharagon commented on docs/cloud.en.md
> +- Must offer a free plan or trial period for testing.
Because it does not exclude our current recommendation, and it does not exclude the providers we are currently considering. If there are plenty of options which can meet a requirement we don't need to consider ones that can't.

2023-02-14 23:13 UTC, jonaharagon commented on docs/calendar-contacts.en.md
> +- Must sync and store information with E2EE to ensure data is not visible to the service provider.
Now that EteSync was removed I don't think a "Calendar/Contacts" page makes sense, I think I'm going to rename this to "Calendar Sync" instead. If we bring back EteSync or find a different contact manager we can have a separate "Contacts Sync" page as well, but our current recommendations are clearly calendar-focused.

2023-02-14 23:21 UTC, jonaharagon commented on docs/data-redaction.en.md
> +- Apps developed for open-source operating systems must be open-source.
To work around the current recommendations. It's also a pretty common development practice ([for example](https://tailscale.com/blog/opensource/)), this applies to multiple categories.

2023-02-15 03:10 UTC, mfwmyfacewhen commented on docs/desktop-browsers.en.md
> +- Should not be Chromium-based.
I don't really agree with this. There's nothing wrong with Chromium. I understand the monopoly argument, but that doesn't affect the actual functionality of the browser and this implies that a Chromium-based browser is somehow less private that a non-Chromium one.

2023-02-15 03:17 UTC, jonaharagon commented on docs/desktop-browsers.en.md
> +- Should not be Chromium-based.
If it was a privacy concern it would be part of the minimum requirements. The best-case more describes what we would want to see from a perfect product in this category. On the email provider page for example, we have best-case criteria that **no** providers meet: It doesn't imply that our recommendations aren't private, it merely describes our vision. 

I don't feel strongly about keeping this in our best-case criteria at all, but I also don't feel like this is a very strong argument to remove it either.

2023-02-15 07:42 UTC, dngray commented on docs/desktop-browsers.en.md
> +- Should not be Chromium-based.
I think I'd remove it, because it infers that Chromium engine has something to do with privacy.

2023-02-15 07:45 UTC, dngray commented on docs/cloud.en.md
> +    Nextcloud is [still a recommended tool](productivity.md) for self-hosting a file management suite, however we do not recommend third-party Nextcloud storage providers at the moment, because we do
"home users", maybe "inexperienced users" sounds better?

2023-02-15 12:29 UTC, dngray commented
Looking good. I checked over:

- https://github.com/privacyguides/privacyguides.org/discussions/351
- https://github.com/privacyguides/privacyguides.org/discussions/983
- https://github.com/privacyguides/privacyguides.org/discussions/1227
- https://github.com/privacyguides/privacyguides.org/discussions/147

And I don't think we missed anything.

2023-02-15 13:47 UTC, jonaharagon commented on docs/cloud.en.md
> +    Nextcloud is [still a recommended tool](productivity.md) for self-hosting a file management suite, however we do not recommend third-party Nextcloud storage providers at the moment, because we do
I used this specific term because of this discussion, but I'm not sure what our opinion on it really is:

> E2EE will certainly work reliably in several large customer setups with the benefit of our support and fortune 500 companies are surprisingly unwilling to risk data loss, but I know the multitude of use cases home and SMB users have takes longer to stabilise. So perhaps mid 2023 we can have a conversation again about how likely it is a normal private user can run a Nextcloud E2EE setup without risk.

https://discuss.privacyguides.net/t/dont-recommend-nextcloud-e2ee/10352/29?u=jonah

2023-02-15 15:05 UTC, jonaharagon commented on docs/desktop-browsers.en.md
> +- Should not be Chromium-based.
Just updated the best-case section to better reflect our opinions on Brave and FF.

2023-02-15 15:41 UTC, blacklight447 commented on docs/cloud.en.md
> +    Nextcloud is [still a recommended tool](productivity.md) for self-hosting a file management suite, however we do not recommend third-party Nextcloud storage providers at the moment, because we do
We could even give a out right anti recommendation for nextclouds e2ee. Its alpha quality software which i wouldt trust to reliably back up my data. Let alone the security aspect.

2023-02-15 16:08 UTC, blacklight447 reviewed
Left some comments.

2023-02-15 16:08 UTC, blacklight447 commented on docs/passwords.en.md
> +- Must have been audited by a reputable independent third-party.
Do we want to require the audit results to be published?

2023-02-15 16:08 UTC, blacklight447 commented on docs/passwords.en.md
> +- Telemetry must be at least entirely opt-out.
I think you mean opt in here? Or able to completely opt out?

2023-02-15 16:08 UTC, blacklight447 commented on docs/productivity.en.md
> +- Makes files accessible via WebDAV unless impossible due to E2EE.
Should "it is" be inserted between "unless" and "impossible" here?

2023-02-15 16:10 UTC, jonaharagon commented on docs/passwords.en.md
> +- Must have been audited by a reputable independent third-party.
I think this is implied, because we wouldn't be taking claims at face value when evaluating a service anyways. How would you reword this?

2023-02-15 16:10 UTC, jonaharagon commented on docs/passwords.en.md
> +- Telemetry must be at least entirely opt-out.
How about
```suggestion
- All non-essential telemetry must be optional.
```

2023-02-15 16:11 UTC, blacklight447 commented on docs/passwords.en.md
> +- Telemetry must be at least entirely opt-out.
Looks great!

2023-02-15 16:13 UTC, blacklight447 commented on docs/passwords.en.md
> +- Must have been audited by a reputable independent third-party.
Could be as simple as adding "and have their findings published" to the back of it. That we we leave no room for confusion.

2023-02-15 16:13 UTC, jonaharagon commented on docs/mobile-browsers.en.md
> +- Must receive engine updates in 0-1 days from upstream release.
IMO we should leave it as-is and cross that bridge when we come to it.

We've removed browsers for this in the past, and our argument against most browser forks has always been that most dev teams don't have the capacity to immediately process upstream browser updates, which is a security concern.

I also don't think active monitoring is implied by any of our criteria, but if it was reported to us then we'd have to consider it.

2023-02-15 16:15 UTC, jonaharagon commented on docs/encryption.en.md
> +- Operating System (FDE) encryption apps should utilize hardware security such as a TPM or Secure Enclave.
We do recommend Veracrypt FDE for external drives, and we currently don't recommend it for OS drives, so this doesn't change anything: https://www.privacyguides.org/encryption/#os-full-disk-encryption

2023-02-15 16:16 UTC, jonaharagon commented on docs/email-clients.en.md
> +- Must not collect telemetry, or have an easy way to disable all telemetry.
Only if it is transmitted to the developer, do you have an app in mind?

2023-02-15 16:18 UTC, jonaharagon commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
I'm very confused about where this "recommend against" talk is coming from in general, this PR is not making any anti-recommendations anywhere.

FYI- This page only applies to desktop browsers.

2023-02-15 16:18 UTC, jonaharagon commented on docs/desktop.en.md
> +- Must support [Wayland](os/linux-overview.md#Wayland).
Good point.
```suggestion
- Linux distributions must support [Wayland](os/linux-overview.md#Wayland).
```

2023-02-15 16:22 UTC, blacklight447 commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
I was talking about the "should not be chromium based" part. In retrospective its indeed rather weird to talk about graphene in the desktop section. 


But what I mostly meant that chromium based options should still be recommended when they are a good option, instead of being excluded from PG for being chromium based :p

2023-02-15 16:48 UTC, jonaharagon commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
Yes. The entirety of Privacy Guides' recommendation section is an opinion, that's what recommendations are.

That being said, I do still think this clearly has some objective relation to privacy, which is what the added explanation in the latest commit tries to convey.

2023-02-15 17:15 UTC, jonaharagon commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
You're disagreeing with a strawman, the privacy of someone improving because they're not using Chromium is not an argument anyone has ever made in this thread.

Also see: https://matrix.to/#/!XobthiyrsXshZCJPxh:privacyguides.org/$ujnrH-qLKRCB-MQKJ5L-XaRoV53tZmI0AhYNhIDD2LY?via=matrix.org&via=privacyguides.org&via=polarbear.army

> I'm saying something **doesn't have to be directly better for the end-user's privacy** to be better for privacy in general. Ultimately only having a single browser engine will harm user choice in the long-term, which is an actual privacy concern.

2023-02-15 17:56 UTC, mfwmyfacewhen requested changes

2023-02-15 17:56 UTC, mfwmyfacewhen commented on docs/real-time-communication.en.md
> +- Must have been independently audited.
```suggestion
- Must have been independently audited.
- Must support PFS.
```

2023-02-15 17:56 UTC, mfwmyfacewhen commented on docs/real-time-communication.en.md
> +- Must have been independently audited.
Would like to make this a requirement, y'all could let me know what you think.

2023-02-15 18:34 UTC, blacklight447 commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
But i don't really see how it will help privacy overall? It has the potential to become a problem, but we don't yet know if it will.

2023-02-15 19:00 UTC, freddy-m commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
> The entirety of Privacy Guides' recommendation section is an opinion

Is it though? Hopefully because we test things against our criteria (and are generally pragmatic) our recommendations are more than just opinion. I guess what we put in our guidelines is what our opinion of a good [xyz]...

2023-02-15 19:02 UTC, freddy-m commented on docs/dns.en.md
> +!!! example "This section is new"
At what point do we remove the 'This section is new' labels? Should we set an arbitary period of time, like 2 months or something?

2023-02-15 19:04 UTC, jonaharagon commented on docs/dns.en.md
> +!!! example "This section is new"
Yeah, we're going to gauge it based on discussions this generates.

2023-02-15 19:07 UTC, jonaharagon commented on docs/real-time-communication.en.md
> +- Must have been independently audited.
This change wasn't made in this PR precisely because this PR is not intended to change any of our recommendations. We'll discuss this separately at #1994 and if/when that is merged we'll make this change there instead.

2023-02-15 19:08 UTC, freddy-m commented on docs/multi-factor-authentication.en.md
> +- Devices which cost over $35 must support handling OpenPGP and S/MIME.
Any particular reason why its $35? FWIW I think its a good figure but wondered if there was a particular reason?

2023-02-15 19:10 UTC, freddy-m commented on docs/productivity.en.md
> +- Makes files accessible via WebDAV unless impossible due to E2EE.
'unless impossible' is functional, but stylistically its not that great.

2023-02-15 19:12 UTC, jonaharagon commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
...yes? **All** of these criteria themselves are our opinions of what we think software should be. Opinions aren't inherently bad, and we're not striving to be unopinionated or unbiased, we're striving to be **consistent** with our opinions.

2023-02-15 19:14 UTC, freddy-m commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
Our recommendations aren't fact, they're opninions based on fact. Makes sense.

2023-02-15 19:17 UTC, mfwmyfacewhen commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
> You're disagreeing with a strawman, the privacy of someone improving because they're not using Chromium is not an argument anyone has ever made in this thread.
> 
> Also see: https://matrix.to/#/!XobthiyrsXshZCJPxh:privacyguides.org/$ujnrH-qLKRCB-MQKJ5L-XaRoV53tZmI0AhYNhIDD2LY?via=matrix.org&via=privacyguides.org&via=polarbear.army
> 
> > I'm saying something **doesn't have to be directly better for the end-user's privacy** to be better for privacy in general. Ultimately only having a single browser engine will harm user choice in the long-term, which is an actual privacy concern.

I actually don't agree that it's worse for privacy overall to have a single browser engine. Even if all other browsers died off somehow, which I think is unlikely, I don't know what would change then that would hurt privacy. You would still have Brave etc.

2023-02-15 19:25 UTC, jonaharagon commented on docs/multi-factor-authentication.en.md
> +- Devices which cost over $35 must support handling OpenPGP and S/MIME.
It was mostly to leave the door open to products like SoloKey, although we aren't really considering that right now for other reasons so it doesn't really matter: https://discuss.privacyguides.net/t/solokey-hardware-security-key/11585

The Google Titan security key is also $35, and while we aren't currently recommending them either, between those two products $35 seems to be about the going rate for a bog-standard FIDO2-only security key.

2023-02-15 19:25 UTC, jonaharagon commented on docs/multi-factor-authentication.en.md
> +- Devices which cost over $35 must support handling OpenPGP and S/MIME.
The NitroKey FIDO2 is also 29 EUR.

2023-02-15 20:30 UTC, blacklight447 commented on docs/cloud.en.md
> +    Nextcloud is [still a recommended tool](productivity.md) for self-hosting a file management suite, however we do not recommend third-party Nextcloud storage providers at the moment, because we do
Ah, I forgot, then im fine.

2023-02-16 04:01 UTC, dngray commented on docs/real-time-communication.en.md
> +- Must have been independently audited.
I made a comment there https://github.com/privacyguides/privacyguides.org/pull/1994#issuecomment-1432452903 about that.

2023-02-16 10:55 UTC, blacklight447 commented on docs/desktop-browsers.en.md
> +  Chromium represents the vast majority of desktop browser market-share, but a monoculture in the browser engine space will eventually lead to reduced user choice, which could have privacy impacts in
I think this discussion has concluded, we will take this out of criteria for now so the PR can move forward, and discuss it further on the forum. @jonah will you make to commit to alter it?

2023-02-16 15:25 UTC, blacklight447 approved these changes
Looks ready to me!

2023-02-16 15:50 UTC, dngray approved these changes

2023-02-16 16:04 UTC, mfwmyfacewhen approved these changes

2023-02-16 16:07 UTC, merged