Add LanguageTool
privacyguides/privacyguides.org pull request #2013
Opened 2023-02-18 10:13 UTC by dngray

Discussion: https://github.com/privacyguides/privacyguides.org/discussions/800

I think this is actually a promising tool, self-hostable, and also keeps your data local.

2023-02-19 17:17 UTC, jonaharagon requested changes
This should be rebased on main, and I think if we add an additional category to this page we should come up with criteria for it. 

Another tool that could fit a new Language Tools section even though it doesn't do the same thing as this might be LibreTranslate, for example.

2023-02-20 03:32 UTC, dngray commented
> Another tool that could fit a new Language Tools section even though it doesn't do the same thing as this might be LibreTranslate, for example.

Yeah I rather like that. In fact I think I might try it and see how it works.

2023-02-24 18:35 UTC, jonaharagon commented
@dngray you can try a self-hosted LibreTranslate out at https://lt.neat.computer/ - I use the API from this on my Mastodon instance and it works well so I can personally recommend it :)

2023-03-03 12:54 UTC, mfwmyfacewhen requested changes

2023-03-05 03:01 UTC, mfwmyfacewhen approved these changes

2023-04-12 14:31 UTC, dngray commented
> I use the API from this on my Mastodon instance and it works well so I can personally recommend it :)

Nice. I had been meaning to deploy it myself, but other things came up.

2024-04-14 06:11 UTC, jonaharagon approved these changes

2024-04-14 14:36 UTC, redoomed1 requested changes

2024-04-14 14:36 UTC, redoomed1 commented on docs/productivity.md
> +[:octicons-info-16:](https://languagetool.org/dev){ .card-link title=Documentation}
```suggestion
[:octicons-info-16:](https://languagetooler.freshdesk.com/en/support/solutions){ .card-link title=Documentation}
```

2024-04-14 14:36 UTC, redoomed1 commented on docs/productivity.md
> +[:octicons-home-16: Homepage](https://languagetool.org){ .md-button .md-button--primary }
```suggestion
[:octicons-home-16: Homepage](https://languagetool.org){ .md-button .md-button--primary }
[:octicons-eye-16:](https://languagetool.org/legal/privacy){ .card-link title="Privacy Policy" }
```

2024-04-14 14:36 UTC, redoomed1 commented on docs/productivity.md
> +- [:simple-firefoxbrowser: Firefox](https://addons.mozilla.org/firefox/addon/languagetool/)
```suggestion
- [:simple-firefoxbrowser: Firefox](https://addons.mozilla.org/firefox/addon/languagetool)
```

2024-04-14 14:43 UTC, redoomed1 commented
> I think if we add an additional category to this page we should come up with criteria for it.

Are you still thinking about doing this? I think that the [criteria established for Paste services](https://www.privacyguides.org/en/productivity/#minimum-requirements) don't apply to LanguageTool:

> Must implement "zero-trust" end-to-end encryption.

LanguageTool, on its homepage (under the "Create your free account" heading), claims "Texts are securely stored," but I could not find anything about E2EE.

> Must support password-protected files.

I don't think LanguageTool has this feature.

2024-04-15 03:46 UTC, dngray commented
The intention was to put this in it's own language section. This tool can be self hosted, and the content was going to be advising that this could be an alternative to DeepL/Google Translate.

Further testing was required.

2024-04-15 03:59 UTC, redoomed1 commented
> The intention was to put this in it's own language section. This tool can be self hosted, and the content was going to be advising that this could be an alternative to DeepL/Google Translate.

Ah, I see. Thanks for the clarification. I was just a little confused since the criteria for paste services is placed under the LanguageTool card (and Language services section) in the GH actions preview.

2024-04-15 04:05 UTC, dngray commented
> advising that this could be an alternative to DeepL/Google Translate.

My confusion there I meant LibreTranslate. This is a grammar tool but same principle applies, it's self hostable and much more privacy friendly. Jonah kindly tested LibreTranslate over at https://lt.neat.computer

2024-04-15 05:18 UTC, jonaharagon commented
There was criteria on the productivity page when this PR was created, it was the same that it is now IIRC.

I don't think this needs a separate page, this is basically just a FOSS Grammarly? It seems only useful for writing documents which falls squarely within productivity IMO.

We _should_ modify the productivity criteria to add info about this though.

I think we should add this, and worry about other language-related tools at some future time. LibreTranslate, while I do think it could be added to the site for sure, is actually an entirely different sort of tool. I didn't intend to block adding this tool while we wait to figure out what we want to do with every other language tool out there.

2024-04-16 10:17 UTC, dngray commented
> I don't think this needs a separate page, this is basically just a FOSS Grammarly? It seems only useful for writing documents which falls squarely within productivity IMO.

That's fair I guess a language tools heading under productivity page would be sufficient.

2024-04-16 10:37 UTC, merged