Add page descriptions to docs
privacyguides/privacyguides.org pull request #2075
Opened 2023-03-07 14:53 UTC by jonaharagon

Closes #2067 

- [x] Please check this box to confirm you have disclosed any relevant conflicts of interest in your post.
- [x] Please check this box to confirm your agreement to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute your contribution as part of our project.
- [x] Please check this box to confirm you are the sole author of this work, or that any additional authors will also reply to this PR on GitHub confirming their agreement to these terms.

2023-03-08 06:27 UTC, dngray approved these changes

2023-03-09 06:28 UTC, mfwmyfacewhen requested changes

2023-03-09 06:28 UTC, mfwmyfacewhen commented on docs/email.md
> +description: These email providers provide a great place to store your emails securely, and many offer interoperable OpenPGP encryption with other providers.
```suggestion
description: These email providers offer a great place to store your emails securely, and many offer interoperable OpenPGP encryption with other providers.
```

2023-03-09 06:28 UTC, mfwmyfacewhen commented on docs/notebooks.md
> +description: These encrypted notetaking apps apps let you keep track of your notes without giving them to a third-party.
```suggestion
description: These encrypted note-taking apps let you keep track of your notes without giving them to a third-party.
```

2023-03-09 06:28 UTC, mfwmyfacewhen commented on docs/vpn.md
> +description: These are the best VPN services for protecting your privacy and security online. Find a provider here who isn’t out to spy on you.
```suggestion
description: These are the best VPN services for protecting your privacy and security online. Find a provider here that isn’t out to spy on you.
```

2023-03-10 16:11 UTC, merged