fix Readme dead/non-existing links
privacyguides/privacyguides.org pull request #2112
Opened 2023-04-05 15:26 UTC by jermanuts

Changes proposed in this PR:

- 

- [ ] I have disclosed any relevant conflicts of interest in my post.
- [ ] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [ ] I am the sole author of this work. 
- [ ] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-04-05 17:51 UTC, jonaharagon commented on README.md
> +  - View more contribution tips on our [page](https://www.privacyguides.org/en/about/donate/)
```suggestion
```

2023-04-05 17:55 UTC, jonaharagon submitted a review, later dismissed

2023-04-07 05:30 UTC, blacklight447 approved these changes

2023-04-07 18:43 UTC, jonaharagon commented
The changes from your original PR were merged in https://github.com/privacyguides/privacyguides.org/commit/b074ed9401b13204569d12c49246aaf5bfbbe372 - I don't think that these additional links really add substance to the site, and I don't think we could consider many of them to really be "reliable sources."

2023-04-07 18:44 UTC, jonaharagon requested changes
The changes from your original PR were merged in https://github.com/privacyguides/privacyguides.org/commit/b074ed9401b13204569d12c49246aaf5bfbbe372 - I don't think that these additional links really add substance to the site, and I don't think we could consider many of them to really be "reliable sources."

2023-04-07 20:34 UTC, jermanuts commented
> I don't think we could consider many of them to really be "reliable sources."
Could you be more specific?

I picked articles where there is no security vulnerability to be patched, but rather insecurity by design. Specifically, Pass and deterministic password managers (there's an [issue](https://github.com/privacyguides/privacyguides.org/issues/1859) opened for it)

>It's important to note that these financial services are not anonymous and are subject to "Know Your Customer" (KYC) laws and may require your ID or other identifying information. 

"Privacy”.com–Yeah Right" proves cases where privacy.com ask for your ID (which happens too often).

2023-04-08 08:23 UTC, dngray commented on docs/basics/email-security.md
> +- [The PGP Problem](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html)
I really dislike these Latacora articles, because they labor about "email security" and suggest things which are not email.

This is not helpful when you want email-styled/compatible providers. We cover enough of that with the warning at the top of the page.

As far as email encryption across multiple providers go, PGP **is** and **remains** currently the only option, unless you opt for "form" based emails on the provider's server.

2023-04-08 16:34 UTC, jonaharagon commented
> proves cases where privacy.com ask for your ID

We already say this is the case on the website, so I don't know what value this adds. @dngray mentioned an issue with the other articles about email. In terms of reliability, these seem to be mostly blogs which are either non-independent or just generally can't be trusted: anyone can claim to be an expert on their blog.

Generally speaking though, after talking this through with the team I think we want to move away from "related links" sections and clean up or remove the ones we do have, not add additional ones. **If information is important, we should be adding it to the site directly.**

2023-04-08 16:34 UTC, closed without merging

2023-04-08 17:10 UTC, dngray commented on docs/basics/passwords-overview.md
> +- [4 fatal flaws in deterministic password managers](https://tonyarcieri.com/4-fatal-flaws-in-deterministic-password-managers)
We don't list any of these currently, and they by far are not very popular. IMHO not worth mentioning.

2023-04-08 17:11 UTC, dngray commented on docs/basics/passwords-overview.md
> +- [(In)Security of the "Pass" password manager](https://rot256.dev/post/pass/)
We don't recommend pass, but we do recommend gopass. While this does have some of the issues mentioned,  its rather obvious. We mention this is still useful as a very cut-down manager for scripting applications.

2023-04-08 17:11 UTC, dngray commented on docs/basics/vpn-overview.md
> +- [Who owns your data? A VPN Relationship Map](https://blog.windscribe.com/the-vpn-relationship-map/)
I do think this is one we could incorporate into the page.

2023-04-08 17:13 UTC, dngray commented
> We already say this is the case on the website, so I don't know what value this adds.

Indeed. Don't think this is worth adding. Privacy.com is not intended to make your purchases anonymous simply shield your credit card number from merchants. Financial industry does have regulation, especially payment providers like Visa and Mastercard, so this is to be expected. I do not think that blog article is worth adding.