Add Accrescent & Play Store Link For IVPN
privacyguides/privacyguides.org pull request #2139
Opened 2023-04-19 21:12 UTC by matchboxbananasynergy

Changes proposed in this PR:

This PR replaces https://www.ivpn.net/apps-android/ link with direct Play Store and Accrescent download links. Direct Play Store link was chosen for consistency with other entries across the site, and Accrescent was added as IVPN made it onto the store.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-04-19 22:40 UTC, mfwmyfacewhen approved these changes

2023-04-20 02:20 UTC, jonaharagon requested changes
Accrescent isn't a recommended app store, it shouldn't have been added in #1957 either.

2023-04-20 13:51 UTC, jonaharagon approved these changes
We're going to [open a forum discussion](https://discuss.privacyguides.net/t/accrescent/12410) about just recommending Accrescent in general 👍

I've changed my mind about this, it does make sense if the download link is recommended by the developer.

2023-04-20 13:52 UTC, dngray commented
I've added a [discussion thread for Accrescent](https://discuss.privacyguides.net/t/accrescent/12410). While we may not list this specifically on the Android page, I think it's okay to still list downloads for the few applications where installation with Accrescent is possible as it does make updating those apps hugely more convenient (if you don't want to get them from Google Play) or bother with the RSS feed method.

2023-04-21 02:31 UTC, mfwmyfacewhen approved these changes

2023-04-21 10:25 UTC, dngray approved these changes

2023-04-21 10:26 UTC, merged