Clean up tor page
privacyguides/privacyguides.org pull request #2142
Opened 2023-04-25 06:34 UTC by mfwmyfacewhen

Changes proposed in this PR:

- Remove link to unofficial download for FreeBSD
- Remove broken Snowflake iframe

- [ ] I have disclosed any relevant conflicts of interest in my post.
- [ ] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [ ] I am the sole author of this work. 
- [ ] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-04-26 13:11 UTC, blacklight447 commented
Have we already figuired out what broke the snowflake iframe?

2023-04-26 13:12 UTC, mfwmyfacewhen commented
> Have we already figuired out what broke the snowflake iframe?

My understanding is the sites's CSP makes it so iframes don't work properly, which is why Jonah replaced the YouTube iframes.

2023-04-26 13:20 UTC, jonaharagon requested changes
The Snowflake iFrame isn't broken, so I'm not sure why this change has to be made.

2023-04-26 14:47 UTC, blacklight447 approved these changes

2023-05-10 09:25 UTC, dngray approved these changes

2023-05-10 10:14 UTC, merged