Add offline paid subcription for Standard Notes
privacyguides/privacyguides.org pull request #2149
Opened 2023-04-29 12:41 UTC by d4rklynk

2023-04-29 16:58 UTC, mfwmyfacewhen approved these changes

2023-04-29 16:58 UTC, mfwmyfacewhen commented on docs/notebooks.md
> +You still need to pay an [offline subscription](https://standardnotes.com/help/self-hosting/subscriptions) to be able to use premium features for self-hosting. The payement is done by paying monthly
```suggestion
You still need to pay an [offline subscription](https://standardnotes.com/help/self-hosting/subscriptions) to be able to use premium features for self-hosting.
```

2023-04-29 16:59 UTC, mfwmyfacewhen commented on docs/notebooks.md
> +You still need to pay an [offline subscription](https://standardnotes.com/help/self-hosting/subscriptions) to be able to use premium features for self-hosting. The payement is done by paying monthly
No reason to list the specific prices/pricing model imo since those can change and not everyone uses USD.

2023-04-29 17:09 UTC, d4rklynk commented on docs/notebooks.md
> +You still need to pay an [offline subscription](https://standardnotes.com/help/self-hosting/subscriptions) to be able to use premium features for self-hosting. The payement is done by paying monthly
I just thought it was important since the prices are completely different between monthly and yearly.

2023-04-30 17:19 UTC, freddy-m commented
> Standard Notes requires an [offline subscription](https://standardnotes.com/help/self-hosting/subscriptions) for self-hosting.

This seems friendlier, and more to-the-point, to me...

2023-05-02 14:24 UTC, jonaharagon requested changes
This isn't strictly true, because you can install community extensions that replicate premium features, e.g. https://github.com/jonhadfield/awesome-standard-notes

I would rather not mention this one way or the other personally, I don't see it being super relevant here.

2023-05-02 14:25 UTC, mfwmyfacewhen commented
> This isn't strictly true, because you can install community extensions that replicate premium features, e.g. https://github.com/jonhadfield/awesome-standard-notes
> 
> I would rather not mention this one way or the other personally, I don't see it being super relevant here.

Yeah fair, I think I'll just close this then.

2023-05-02 14:25 UTC, closed without merging