Add macOS overview
privacyguides/privacyguides.org pull request #2150
Opened 2023-04-29 17:24 UTC by mfwmyfacewhen

Changes proposed in this PR:

- Adds macOS overview

closes #1858 

- [ ] I have disclosed any relevant conflicts of interest in my post.
- [ ] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [ ] I am the sole author of this work. 
- [ ] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-04-29 18:52 UTC, noClaps commented on docs/os/macos-overview.md
> +Apple's newer hardware always has the best security; you should check to make sure the Mac you're buying has at least their M1 chip, as their intel Macs are vulnerable to the [checkm8](https://www.th
```suggestion
Apple's newer hardware always has the best security; you should check to make sure the Mac you're buying has at least their M1 chip, as their Intel Macs are vulnerable to the [checkm8](https://www.theiphonewiki.com/wiki/Checkm8_Exploit) exploit.
```

2023-04-29 18:52 UTC, noClaps commented on docs/os/macos-overview.md
> +If you use bluetooth accessories such as a keyboard, we recommend that you use official Apple ones as their firmware will automatically be updated for you by macOS. Using third party accessories is f
```suggestion
If you use Bluetooth accessories such as a keyboard, we recommend that you use official Apple ones as their firmware will automatically be updated for you by macOS. Using third party accessories is fine, but you should remember to install firmware updates for them regularly.
```

2023-04-29 18:52 UTC, noClaps commented on docs/os/macos-overview.md
> +Apple's SoC's focus on minimizing attack surface by religating security functions to dedicated hardware with limited functionality.
```suggestion
Apple's SoCs focus on minimizing attack surface by relegating security functions to dedicated hardware with limited functionality.
```

2023-04-29 18:52 UTC, noClaps commented on docs/os/macos-overview.md
> +macOS prevents malware persistence by only allowing official Apple software to run at boot time; this is known as secure boot. Macs verify this with a bit of Read-Only Memory on the SoC called the Bo
```suggestion
macOS prevents malware persistence by only allowing official Apple software to run at boot time; this is known as Secure Boot. Macs verify this with a bit of Read-Only Memory on the SoC called the Boot ROM, which is laid down during the manufacturing of the chip.
```

2023-04-29 18:56 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +macOS prevents malware persistence by only allowing official Apple software to run at boot time; this is known as secure boot. Macs verify this with a bit of Read-Only Memory on the SoC called the Bo
Apple's official documentation actually doesn't capitalize this so I'll follow that

2023-04-29 19:01 UTC, noClaps commented on docs/os/macos-overview.md
> +macOS prevents malware persistence by only allowing official Apple software to run at boot time; this is known as secure boot. Macs verify this with a bit of Read-Only Memory on the SoC called the Bo
https://support.apple.com/en-us/HT208198

They do, actually.

2023-05-01 12:39 UTC, noClaps commented on docs/os/macos-overview.md
> +Many security features in macOS like secure boot rely on Apple's hardware to function properly. For this reason, we recommend you only run it on Macs and avoid hackintoshes.
```suggestion
Many security features in macOS like Secure Boot rely on Apple's hardware to function properly. For this reason, we recommend you only run it on Macs and avoid Hackintoshes.
```

Apple's documentation uses the capitalised forms: https://support.apple.com/en-us/HT208198

2023-05-01 12:39 UTC, noClaps commented on docs/os/macos-overview.md
> +macOS prevents malware persistence by only allowing official Apple software to run at boot time; this is known as secure boot. Macs verify this with a bit of Read-Only Memory on the SoC called the Bo
```suggestion
macOS prevents malware persistence by only allowing official Apple software to run at boot time; this is known as secure boot. Macs verify this with a bit of read-only memory on the SoC called the boot ROM, which is laid down during the manufacturing of the chip.
```

2023-05-01 12:39 UTC, noClaps commented on docs/os/macos-overview.md
> +The Boot ROM forms the hardware root of trust. This ensures that malware cannot tamper with the boot process. When your Mac boots up, the boot ROM is the first thing that runs, forming the first link
```suggestion
The boot ROM forms the hardware root of trust. This ensures that malware cannot tamper with the boot process. When your Mac boots up, the boot ROM is the first thing that runs, forming the first link in the chain of trust.
```

2023-05-01 13:43 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +Many security features in macOS like secure boot rely on Apple's hardware to function properly. For this reason, we recommend you only run it on Macs and avoid hackintoshes.
Oh that's funny, they're not consistent about it

2023-05-01 13:45 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +Macs can be configured to boot in three security modes: *Full Security*, *Reduced Security*, and *Permissive Security*. You should ideally be using Full Security mode, but using things like kernel ex
Yeah I specifically wanted to mention how they reduce the security of your system, maybe I didn't communicate that.

2023-05-03 11:11 UTC, mfwmyfacewhen commented
> I think it is also best to recommend to usefirst party apps (like pages, numbers, slides, reminders, notes) over third party ones. Since they are classified as "preinstalled apps" the app data is protected by SIP. Note: Apps installed through App Store are also protected by SIP.
> It is also best to recommend to use Safari if you are using Lockdown mode for better security or private relay for better privacy. Safari is also protected by SIP.

If all App Store apps are protected by SIP then I'll probably just recommend only installing from the App Store, unless preinstalled apps have some other benefit.

You're right I'll mention that you should use Safari with lockdown mode.

2023-05-20 01:19 UTC, mfwmyfacewhen commented
> > unless preinstalled apps have some other benefit.
> 
> I can't think of anything other than helping to reduce attack surface. App Store only permit webkit browsers so only webkit based browsers are protected by SIP. Most of the apps recommend by Privacy Guides also seems to available on App Store (except Joplin) or can be accessed via Web App.
> 
> Another thing that can be mentioned is Time Machine for encrypted local backup. It might also fit here: #1721

The documentations says "System Integrity Protection restricts components to read-only in specific critical file system locations to help prevent malicious code from modifying them." So it protects your core system files and it will do that unless you disable it manually. Not sure it's accurate to say that only App Store apps are protected by SIP. It is true that only App Store apps are required to use the App Sandbox.

2023-05-29 12:53 UTC, mfwmyfacewhen commented
Note to self to add how to randomize MAC address.

2023-05-30 09:24 UTC, mfwmyfacewhen commented
> For developers and other people who actually need admin rights in their main account: https://github.com/SAP/macOS-enterprise-privileges This is a far easier solution.

I might need you to write that, I'm not familiar.

2023-06-04 05:05 UTC, mfwmyfacewhen commented
> > For developers and other people who actually need admin rights in their main account: https://github.com/SAP/macOS-enterprise-privileges This is a far easier solution.
> 
> Using this comes down to the debate of whether you should create a normal user account for day to day use. However, I don't think this practice is necessary anymore.
> 
> Here is a good article about this: https://eclecticlight.co/2023/01/24/is-it-more-secure-to-be-a-normal-or-admin-user/ and conclude
> 
> > If you’re more comfortable with the more restricted privileges of a normal user account, then why not use one. But don’t think it’s going to improve security or privacy.

[Apple](https://support.apple.com/guide/mac-help/set-up-your-mac-to-be-secure-flvlt003/mac#mchlp6f0f578) recommends using a normal user account for security so that's why I mentioned it.

2023-06-29 05:19 UTC, mfwmyfacewhen commented
> Are there any considerations to bring up iWork now that it's no longer recommended?
> related: [#1979 (comment)](https://github.com/privacyguides/privacyguides.org/pull/1979#issuecomment-1431894244)

I'm not sure if it's covered by SIP. That would be the only reason I could see to recommend it really.

2023-06-29 23:31 UTC, jonaharagon requested changes

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +macOS comes with built-in antivirus software called XProtect. ==We recommend that you **do not** install third-party antivirus software, as it is a major privacy and security concern.==
```suggestion
macOS comes with two forms of malware defense:

1. Protection against launching malware in the first place is provided by the App Store's review process for App Store applications, or *Notarization* (part of *Gatekeeper*), a process where third-party apps are scanned for known malware by Apple before they are allowed to run.
2. Protection against other malware and remediation from existing malware on your system is provided by *XProtect*, a more traditional antivirus software built-in to macOS.

We recommend against installing third-party antivirus software as they typically do not have the system-level access required to properly function anyways, because of Apple's limitations on third-party apps, and because granting the high levels of access they do ask for often poses an even greater security and privacy risk to your computer.
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +
```suggestion
```

This isn't really core OS functionality, and is better covered in the settings section above I think, so I merged some of this with my suggestion there.

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +macOS comes with automatic backup software called [Time Machine](https://support.apple.com/en-us/HT201250) so you can create encrypted backups to an external drive in the event of corrupted/deleted f
```suggestion
macOS comes with automatic backup software called [Time Machine](https://support.apple.com/en-us/HT201250) so you can create encrypted backups to an external or network drive in the event of corrupted/deleted files.
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Apple's newer hardware always has the [best security](https://support.apple.com/guide/security/apple-soc-security-sec87716a080/1/web/1); you should check to make sure the Mac you're buying has at lea
This isn't strictly true, since OpenCore should have security for Hackintoshes on par with Intel Macs. It would be more accurate to simply recommend Apple Silicon, since both official Intel Macs and Hackintoshes fall short in comparison.

```suggestion
Many modern security features in macOS—such as modern Secure Boot, hardware-level exploit mitigation, OS integrity checks, and file-based encryption—rely on Apple Silicon, and Apple's newer hardware always has the [best security](https://support.apple.com/guide/security/apple-soc-security-sec87716a080/1/web/1). We only encourage the use of Apple Silicon devices with macOS, and not older Intel Macs or Hackintoshes.

Some of these modern security features are available on older Intel Macs with the Apple T2 chip, but that chip is susceptible to the *checkm8* exploit which could compromise its security,
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +The Secure Enclave is a security chip built into Apple's devices that's responsible for storing and generating encryption keys for data at reast as well as Face ID and Touch ID data. It contains its
```suggestion
The Secure Enclave is a security chip built into devices with Apple Silicon which is responsible for storing and generating encryption keys for data at rest as well as Face ID and Touch ID data. It contains its own separate boot ROM.
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +You can think of the Secure Enclave as your device's security hub: it has an AES encryption engine and a mechanism to securely store your encryption keys.
```suggestion
You can think of the Secure Enclave as your device's security hub: it has an AES encryption engine and a mechanism to securely store your encryption keys, and it's separated from the rest of the system, so even if the main processor is compromised, it should still be safe.
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +All Apple silicon MacBooks feature a hardware disconnect for the inbuilt microphone whenever the lid is closed. This means that there is no way for an attacker to listen to your Mac's microphone even
```suggestion
All laptops with Apple Silicon feature a hardware disconnect for the built-in microphone whenever the lid is closed. This means that there is no way for an attacker to listen to your Mac's microphone even if the operating system is compromised.
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +- doesn't run known bad firmware
```suggestion
- ensures known bad firmware is properly revoked
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Apple silicon SoCs contain an IOMMU to separate each component that requires direct memory access. For example, a Thunderbolt port can't access memory designated for the kernel.
```suggestion
Apple Silicon firewalls each component that requires direct memory access apart from each other. For example, a Thunderbolt port can't access memory designated for the kernel.
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Click the small **i** icon next to **Automatic Updates**
```suggestion
Click the small :material-information-outline: icon next to **Automatic Updates**
```

2023-06-29 23:31 UTC, jonaharagon commented on docs/os/macos-overview.md
> +macOS provides great security out-of-the-box. With some tweaks, you can tailor it to your privacy needs.
I want to add more introductory content here before we merge this, stuff that answers questions like: _who is macOS useful for?_ and _are there privacy concerns with macOS?_

Relatedly, while we are covering macOS's security advantages here, I don't think we touch enough on privacy _problems_ with macOS, stuff like an internet connection now being required for the initial install, apps being scanned by Apple when they're launched, and the difficulty in auditing macOS for security researchers.

macOS to me is a pretty solid _middle ground_, but the middle ground is not always the best choice for people with advanced requirements, which should be addressed.

2023-06-29 23:55 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +- [ ] Uncheck **Share with app developers**
It's not there for me and I'm signed in to iCloud

2023-06-29 23:59 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +Apple silicon SoCs contain an IOMMU to separate each component that requires direct memory access. For example, a Thunderbolt port can't access memory designated for the kernel.
Is firewall the right word to use here? I want to keep the technical lingo accurate.

2023-06-30 00:04 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +macOS provides great security out-of-the-box. With some tweaks, you can tailor it to your privacy needs.
For scanning apps, do you mean XProtect? I thought that just worked off signatures. Have you tested installing it without an internet connection? Wasn't aware it required that. Never heard that macOS is difficult for security researchers, would probably need some kind of source for that.

2023-06-30 00:06 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +Rosetta is a translation layer that lets you run programs for Intel Macs on Apple silicon Macs. Installing Rosetta increases your attack surface, so you should only do so if you really need it.
Well it lets you run programs for Intel Macs, which means it's technically true. But it's probably not worth mentioning tbh.

2023-06-30 00:10 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +macOS comes with built-in antivirus software called XProtect. ==We recommend that you **do not** install third-party antivirus software, as it is a major privacy and security concern.==
This is wrong, developers submit their apps to be scanned by Apple, they aren't scanned on your machine. (At least that's what it sounds like you're implying here.)

2023-06-30 00:29 UTC, mfwmyfacewhen commented
> > Not sure it's accurate to say that only App Store apps are protected by SIP. It is true that only App Store apps are required to use the App Sandbox. It seems like this is an advantage to using the preinstalled apps, since those appear to be protected by SIP while App Store apps aren't.
> 
> It seems that sandbox is more restrictive than SIP.
> 
> > If your app is distributed through the Mac App Store, System Integrity Protection has no impact because App Sandbox security policies are more restrictive.
> 
> https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/Introduction/Introduction.html

That link goes to an archive that is outdated.

2023-06-30 02:06 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +macOS comes with built-in antivirus software called XProtect. ==We recommend that you **do not** install third-party antivirus software, as it is a major privacy and security concern.==
Does it actually send anything to apple?

2023-06-30 03:44 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +Apple silicon SoCs contain an IOMMU to separate each component that requires direct memory access. For example, a Thunderbolt port can't access memory designated for the kernel.
Yeah my understanding is firewall is purely a networking term.

2023-06-30 09:57 UTC, mfwmyfacewhen commented
> > Not sure it's accurate to say that only App Store apps are protected by SIP. It is true that only App Store apps are required to use the App Sandbox. It seems like this is an advantage to using the preinstalled apps, since those appear to be protected by SIP while App Store apps aren't.
> 
> It seems that sandbox is more restrictive than SIP.
> 
> > If your app is distributed through the Mac App Store, System Integrity Protection has no impact because App Sandbox security policies are more restrictive.
> 
> https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/Introduction/Introduction.html

I recommend avoiding non-app store apps and thus non-sandboxed apps in the page already.

2023-06-30 09:59 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +All laptops with Apple Silicon feature a hardware disconnect for the built-in microphone whenever the lid is closed. This means that there is no way for an attacker to listen to your Mac's microphone
Fixed

2023-06-30 10:06 UTC, mfwmyfacewhen commented
> macOS also have defence in depth that is lacking in other Operating System based on linux or windows. Obtaining root privileges in linux based distros or admins permission in windows can easily undermine the security of the system. macOS prevent this by layering it defences. <img alt="image" width="508" src="https://user-images.githubusercontent.com/41659980/249978502-0ad03fd4-61f6-4722-bccb-6dc059a46569.png"> https://developer.apple.com/videos/play/wwdc2019/701/
> 
> This can be also mentioned.

I'm not really sure what specifically you want me to cover, I'd rather avoid making this a giant wall of text and repeating things. If there's something you think is missing currently then maybe you can let me know where you think I should add that info specifically.

2023-06-30 13:33 UTC, jonaharagon commented on docs/os/macos-overview.md
> +- [ ] Uncheck **Share with app developers**
Sources indicate this was added in macOS 10.12, so I don’t think I’m seeing this just because I’m on the Sonoma beta. Not sure why you aren’t?

https://www.idownloadblog.com/2017/03/30/how-to-stop-sharing-icloud-analytics-data/

2023-06-30 18:52 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +macOS provides great security out-of-the-box. With some tweaks, you can tailor it to your privacy needs.
I think OCSP probably isn't a big deal but we could mention it. 

With notarization, I'm still unclear if anything is ever actually sent to Apple, I think that would be the only reason to even mention it as a privacy concern. 

I do remember having to activate my Mac the first time I did the setup so yeah I think you're right, but this can be easily mitigated by setting it up at Starbucks or something (maybe I'll mention that).

That article is a bit old now, I think maybe a direct link to a writeup by a security researcher or something might be better if you have that.

2023-06-30 18:55 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +- [ ] Uncheck **Share with app developers**
What version of macOS are you on? I'm on Ventura 13.4.1

2023-07-01 02:26 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +- [ ] Uncheck **Share with app developers**
So I guess it's there for some people. I'll just merge this then.

2023-07-01 02:58 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +macOS provides great security out-of-the-box. With some tweaks, you can tailor it to your privacy needs.
Hmm yeah we could mention it then.

2023-07-02 01:50 UTC, jonaharagon commented on docs/os/macos-overview.md
> +
Do we think we could elaborate on what these defenses actually are? Defense in depth is just a basic security practice for things that companies like Apple develop, it’s not particularly notable that they layer their security defenses, but their specific implementation probably is.

2023-07-02 08:02 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +
So basically he's talking about Gatekeeper in the presentation, that seems to be what he means by defense in depth.

2023-07-02 22:32 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +As part of macOS's security model, the first time a program is run it will be subject to a malware scane and a signature check to make sure it's not malware.
It's not an issue for me really.

2023-07-03 00:02 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +As part of macOS's security model, the first time a program is run it will be subject to a malware scane and a signature check to make sure it's not malware.
Was trying to implement @jonaharagon 's suggestion

2023-07-03 00:05 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +The first time you set up your new Mac, you'll need an internet connection so you can activate it on Apple's servers.
That might be it actually.

2023-07-04 18:12 UTC, jonaharagon commented on docs/os/macos-overview.md
> +## Software
#2222 reminds me: we should add something about not running Public/Developer Betas. Besides just being _betas_ that are not suitable for regular use, they also have increased unnecessary analytics enabled by default (possibly mandatory like on Windows Insider builds? I’d have to double-check).

2023-07-04 18:20 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +## Software
Yes good idea.

2023-07-07 06:14 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +
I'm not really sure where to put this, my original idea was to follow the structure in the Apple Platform Security docs but I would have to reformat the whole thing to follow this structure.

2023-07-13 00:19 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Your account when you first set up your Mac will be an Administrator account, which has higher privileges than a Standard user account. It is considered [best practice](https://support.apple.com/guid
I missed that comment. Let me look into it more and double-check, but that goes against Apple’s recommendations in this area.

2023-07-13 00:48 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +Your account when you first set up your Mac will be an Administrator account, which has higher privileges than a Standard user account. It is considered [best practice](https://support.apple.com/guid
Yeah I thought so

2023-07-13 00:48 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +This guide should situate most people for adequate privacy on their Mac. If you desire a more in-depth configuration, @drduh's [MacOS Security and Privacy Guide](https://github.com/drduh/macOS-Securi
I read through that link a bit and I'm not really a fan. Among the recommendations are using OpenBSD for government adversaries, fear mongering about macOS becoming iOS, recommendations to install lots of third party software including some that requires kernel extensions, disabling SIP to modify some system services, and using the hosts file to block malware.

2023-07-13 00:54 UTC, jonaharagon commented on docs/os/macos-overview.md
> +The majority of privacy and security concerns with Apple products are related to their *cloud services*, not their hardware or software. When you use Apple services like iCloud, most of your informat
> most of your information

> implies that Apple has access to the every information

I don't think so?

2023-07-13 01:09 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Your account when you first set up your Mac will be an Administrator account, which has higher privileges than a Standard user account. It is considered [best practice](https://support.apple.com/guid
Updated 👍

2023-07-13 01:56 UTC, jonaharagon approved these changes

2023-07-13 02:16 UTC, lavndor reviewed
Hi, first time contributing here. I came across this article draft and wanted to contribute. I only had time to review a small portion, but so far it looks good!

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +**macOS** is a Unix-based operating system developed by Apple for their Mac computers. If you have a Mac already, you can increase your privacy by disabling some built-in telemetry features, and hard
```suggestion
**macOS** is a Unix-based operating system developed by Apple for their Mac computers. To enhance privacy on macOS, you can disable telemetry features and harden existing privacy and security settings.
```

The previous wording felt a bit clunky.

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +We wouldn't suggest using macOS with any hardware other than modern Apple Silicon machines. Older Intel-based Macs and Hackintoshes are missing a number of fundamental security features that macOS re
```suggestion
Older Intel-based Macs and Hackintoshes do not support all the security features that macOS offers. To enhance data security, we recommend using a newer Mac with [Apple silicon](https://support.apple.com/en-us/HT211814).
```

"We wouldn't suggest using macOS with any hardware other than modern Apple Silicon machines." I think this would dissuade Intel-based Mac owners from continuing through the guide. There is still a number of subjects that apply to all Macs.

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +Brand new Apple Silicon devices can be set up without an internet connection. However, recovering or resetting your Mac will **require** an internet connection to Apple's servers to check against the
```suggestion
Brand new Apple silicon devices can be set up without an internet connection. However, recovering or resetting your Mac will **require** an internet connection to Apple's servers to check against the Activation Lock database of lost or stolen devices.
```

Apple doesn't capitalize "silicon" in any instances.

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +On modern devices with a Secure Enclave (Apple T2 Security Chip, Apple Silicon), your data is always encrypted, but is decrypted automatically by a hardware key if your device doesn't detect it's bee
```suggestion
On modern devices with a Secure Enclave (Apple T2 Security Chip, Apple silicon), your data is always encrypted, but is decrypted automatically by a hardware key if your device doesn't detect it's been tampered with. Enabling FileVault additionally requires your password to decrypt your data, greatly improving security, especially when powered off or before the first login after powering on.
```

Apple doesn't capitalize "silicon" in any instances.

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +Many modern security features in macOS—such as modern Secure Boot, hardware-level exploit mitigation, OS integrity checks, and file-based encryption—rely on Apple Silicon, and Apple's newer hardware
```suggestion
Many modern security features in macOS—such as modern Secure Boot, hardware-level exploit mitigation, OS integrity checks, and file-based encryption—rely on Apple silicon, and Apple's newer hardware always has the [best security](https://support.apple.com/guide/security/apple-soc-security-sec87716a080/1/web/1). We only encourage the use of Apple silicon, and not older Intel-based Mac computers or Hackintoshes.
```

Apple doesn't capitalize "silicon" in any instances.

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +The Secure Enclave is a security chip built into devices with Apple Silicon which is responsible for storing and generating encryption keys for data at rest as well as Face ID and Touch ID data. It c
```suggestion
The Secure Enclave is a security chip built into devices with Apple silicon which is responsible for storing and generating encryption keys for data at rest as well as Face ID and Touch ID data. It contains its own separate boot ROM.
```

Apple doesn't capitalize "silicon" in any instances.

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +All laptops with Apple Silicon or the T2 chip feature a hardware disconnect for the built-in microphone whenever the lid is closed. This means that there is no way for an attacker to listen to your M
```suggestion
All laptops with Apple silicon or the T2 chip feature a hardware disconnect for the built-in microphone whenever the lid is closed. This means that there is no way for an attacker to listen to your Mac's microphone even if the operating system is compromised.
```

Apple doesn't capitalize "silicon" in any instances.

2023-07-13 02:16 UTC, lavndor commented on docs/os/macos-overview.md
> +Apple Silicon separates each component that requires direct memory access. For example, a Thunderbolt port can't access memory designated for the kernel.
```suggestion
Apple silicon separates each component that requires direct memory access. For example, a Thunderbolt port can't access memory designated for the kernel.
```

Apple doesn't capitalize "silicon" in any instances.

2023-07-13 02:22 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Brand new Apple Silicon devices can be set up without an internet connection. However, recovering or resetting your Mac will **require** an internet connection to Apple's servers to check against the
Mandela effect moment lol

2023-07-13 03:51 UTC, jonaharagon commented on docs/os/macos-overview.md
> +The majority of privacy and security concerns with Apple products are related to their *cloud services*, not their hardware or software. When you use Apple services like iCloud, most of your informat
I don’t think so, Apple using iCloud backups as a psuedo-backdoor is more commonly reported as a security problem in the media than similar services from other companies, probably because the way iCloud works is less obviously problematic (even though in reality it’s equally problematic). It’s also a common misconception that your Apple device *itself* or your iMessages *themselves* are unsafe, simply because Apple’s iCloud implementation is unsafe, so clearing that up specifically here reduces confusion.

I also don’t agree that it is a misrepresentation to say that most iCloud data is unencrypted by default when that is a true statement. The fact that your HomeKit data and stuff like that is E2EE is irrelevant *relative to* the fact that your photos, messages, device backups, etc. are *not* E2EE.

2023-07-13 04:09 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +We wouldn't suggest using macOS with any hardware other than modern Apple Silicon machines. Older Intel-based Macs and Hackintoshes are missing a number of fundamental security features that macOS re
Yeah it sort of makes it sound like if you have an Intel Mac you should install something else.

2023-07-13 04:21 UTC, mfwmyfacewhen commented on docs/os/macos-overview.md
> +However, exploits in protective utilities like `sudo` have been [discovered in the past](https://bogner.sh/2014/03/another-mac-os-x-sudo-password-bypass/). If you want to avoid the possibility that p
I'm not sure I agree with this article. A standard account won't let you use sudo. sudo can do some real damage regardless of SIP, so I think it's worth mentioning. You're right that it doesn't matter for the Admin prompts since they're the same no matter what, although you have to also type the name of an administrator so that adds a very slight bit of extra security.

2023-07-13 05:17 UTC, jonaharagon commented on docs/os/macos-overview.md
> +**macOS** is a Unix-based operating system developed by Apple for their Mac computers. To enhance privacy on macOS, you can disable telemetry features and harden existing privacy and security setting
```suggestion
**macOS** is a Unix operating system developed by Apple for their Mac computers. To enhance privacy on macOS, you can disable telemetry features and harden existing privacy and security settings.
```

2023-07-14 22:17 UTC, merged