Remove mention of Brave wallet setting
privacyguides/privacyguides.org pull request #2164
Opened 2023-05-18 21:44 UTC by mfwmyfacewhen

Changes proposed in this PR:

- Remove outdated settings

closes #2163 

- [ ] I have disclosed any relevant conflicts of interest in my post.
- [ ] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [ ] I am the sole author of this work. 
- [ ] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-05-19 03:41 UTC, dngray approved these changes

2023-05-19 15:50 UTC, jonaharagon requested changes
I think that **Extensions (no fallback)** is the new name for **None**, based on what my settings for Brave currently look like. Logically this makes sense, because if your default Ethereum wallet is set to use a browser extension with no Brave fallback, and you don't have an Ethereum browser extension, this is functionally disabling ETH support (which is what we want).

2023-05-19 18:00 UTC, mfwmyfacewhen commented
> I think that **Extensions (no fallback)** is the new name for **None**, based on what my settings for Brave currently look like. Logically this makes sense, because if your default Ethereum wallet is set to use a browser extension with no Brave fallback, and you don't have an Ethereum browser extension, this is functionally disabling ETH support (which is what we want).

Alright I added those settings.

2023-05-22 10:07 UTC, dngray approved these changes

2023-05-22 10:08 UTC, dngray commented
Checked. LGTM. I checked the other settings while I was there.

2023-05-22 10:11 UTC, merged