Add static 404 page
privacyguides/privacyguides.org pull request #2199
Opened 2023-06-16 16:24 UTC by jonaharagon

Fixes #2084

2023-06-16 23:14 UTC, mfwmyfacewhen requested changes

2023-06-16 23:14 UTC, mfwmyfacewhen commented on static/i18n/404.en.html
> +  </div>
```suggestion
<style type="text/css">@font-face{font-family:FSEX300;src:url(data:application/x-font-ttf;charset=utf-8;base64,AAEAAAAKAIAAAwAgT1MvMlysuCIAAACsAAAAYGNtYXBnwSHmAAABDAAAAXpnbHlmFAN22gAAAogAAA3gaGVhZPkv95UAABBoAAAANmhoZWEA1AA0AAAQoAAAACRobXR4AcwBcgAAEMQAAACKbG9jYXk4deYAABFQAAAAim1heHAASAAmAAAR3AAAACBuYW1loxsDLAAAEfwAAAO6cG9zdAdqB1sAABW4AAAAqgAEAFABkAAFAAAAcABoAAAAFgBwAGgAAABMAAoAKAgKAgsGAAcHAgQCBOUQLv8QAAAAAALNHAAAAABQT09QAEAAIQB6AIL/4gAAAIIAHmARAf///wAAAEYAWgAAACAAAAAAAAMAAAADAAAAHAABAAAAAAB0AAMAAQAAABwABABYAAAAEgAQAAMAAgAhACkALAAuADkAWgB6/////wAAACEAKAAsAC4AMABBAGH//////+D/2v/Y/9f/1v/P/8kAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAABBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAIDAAAEAAUABgcICQoLDA0ODwAAAAAAAAAQERITFBUWFxgZGhscHR4fICEiIyQlJicoKQAAAAAAACorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAFAAAADwAWgALAA8AADcjFSM1IzUzNTMVMwcjNTM8ChQKChQKChQUMhQUHgoKUBQAAAABABT/7AA8AFoAEwAAFyM1IzUjNTM1MzUzFSMVIxUzFTM8FAoKCgoUCgoKChQKFDIUCgoUMhQAAAEAFP/sADwAWgATAAA3IxUjFSM1MzUzNSM1IzUzFTMVMzwKChQKCgoKFAoKChQKChQyFAoKFAAAAQAe/+wAPAAUAAkAABcjFSM1MzUjNTM8ChQKCh4KCgoKFAAAAQAeAAAAPAAUAAMAADcjNTM8Hh4AFAAAAgAUAAAAUABaAAsAFwAANyMVIzUjNTM1MxUzBzUjNTM1IxUzFSMVUAooCgooChQKChQKCgoKCkYKCkYoFAooFAoAAAABAAoAAAA8AFoACQAANyM1IzUzNTM1MzwUHhQKFAA8CgoKAAABAAoAAABGAFoAHQAANyM1MzUzNTM1MzUjFSM1MzUzFTMVIxUjFSMVIxUzRjwKCgoKFBQKKAoKCgoKKAAUCgoKHhQUCgoeCgoKCgAAAQAKAAAARgBaABsAADcjFSM1IzUzFTM1IzUzNSMVIzUzNTMVMxUjFTNGCigKFBQUFBQUCigKCgoKCgoUFB4KHhQUCgoeCgAAAQAKAAAAUABaABEAADcjFSM1IzUzNTMVIxUzNTMVM1AKFCgKFAoUFAoUFBQUMjIKKCgAAAEACgAAAEYAWgATAAA3IxUjFSM1MzUzNSM1MxUjFTMVM0YKCigeCig8KB4KFAoKCgoUMgoeCgAAAgAKAAAARgBaABMAFwAANyMVIzUjNTM1MzUzFSMVIxUzFTMHNSMVRgooCgoKHgoKFAoUFAoKCjIKFAoKCgooKCgAAAABAAoAAABGAFoAEQAANyMVIxUjFSM1MzUzNTM1IzUzRgoKChQKCgooPEYUFB4eFBQKCgAAAwAKAAAARgBaABMAGQAfAAA3IxUjNSM1MzUjNTM1MxUzFSMVMyc1IxUzFRc1IzUjFUYKKAoKCgooCgoKFBQKCgoKCgoKHgoeCgoeCgoeFAooFAoeAAAAAAIACgAAAEYAWgATABcAADcjFSMVIzUzNTM1IzUjNTM1MxUzBzUjFUYKCh4KChQKCigKFBQeChQKCgoKKAoKKCgoAAAAAgAKAAAARgBaAA8AEwAANyM1IxUjNTM1MzUzFTMVMwc1IxVGFBQUCgoUCgoUFAAeHkYKCgoKHh4eAAAAAwAKAAAARgBaAAsADwATAAA3IxUjNTMVMxUjFTMnNSMVFzUjFUYKMjIKCgoUFBQUCgpaCh4KCh4eKB4eAAAAAAEACgAAAEYAWgATAAA3IxUjNSM1MzUzFTMVIzUjFTM1M0YKKAoKKAoUFBQUCgoKRgoKFBRGFAAAAgAKAAAARgBaAAsAEwAANyMVIxUjNTMVMxUzBzUjNSMVMzVGCgooKAoKFAoKChQKCloKCjIyCkYKAAAAAQAKAAAARgBaAAsAADcjNTMVIxUzFSMVM0Y8PCgeHigAWgoeCh4AAAEACgAAAEYAWgAJAAA3IxUzFSMVIzUzRigeHhQ8UB4KKFoAAAEACgAAAEYAWgATAAA3IzUjNTM1MxUzFSM1IxUzNSM1M0YyCgooChQUFAoeAApGCgoUFEYUCgAAAQAKAAAARgBaAAsAADcjNSMVIzUzFTM1M0YUFBQUFBQAKChaKCgAAAEAFAAAADwAWgALAAA3IzUzNSM1MxUjFTM8KAoKKAoKAApGCgpGAAABAAoAAABGAFoACwAANyMVIzUjNTMVMzUzRgooChQUFAoKChQUUAAAAQAKAAAARgBaABcAADcjNSM1IxUjNTMVMzUzNTMVIxUjFTMVM0YUCgoUFAoKFAoKCgoAFBQoWigUFBQUChQAAAEACgAAAEYAWgAFAAA3IzUzFTNGPBQoAFpQAAABAAoAAABQAFoAEwAANyM1IxUjNSMVIzUzFTMVMzUzNTNQFAoKChQUCgoKFAA8Hh48WhQKChQAAAEACgAAAFAAWgATAAA3IzUjNSM1IxUjNTMVMxUzFTM1M1AUCgoKFBQKCgoUAB4KCjJaFAoKKAAAAgAKAAAARgBaAAsADwAANyMVIzUjNTM1MxUzBzUjFUYKKAoKKAoUFAoKCkYKCkZGRgAAAAIACgAAAEYAWgAJAA0AADcjFSMVIzUzFTMHNSMVRgoeFDIKFBQyCihaCh4eHgAAAAIACv/sAEYAWgARABUAABcjNSM1IzUjNTM1MxUzFSMVMyc1IxVGFAoUCgooCgoKFBQUCgoKRgoKRhQURkYAAAACAAoAAABGAFoADwATAAA3IzUjNSMVIzUzFTMVIxUzJzUjFUYUCgoUMgoKChQUAB4KKFoKHhQUHh4AAAABAAoAAABGAFoAIwAANyMVIzUjNTMVMzUjNSM1IzUjNTM1MxUzFSM1IxUzFTMVMxUzRgooChQUCgoKCgooChQUCgoKCgoKCgoKFAoKChQKCgoKFAoKCgAAAQAKAAAARgBaAAcAADcjFSM1IzUzRhQUFDxQUFAKAAABAAoAAABGAFoACwAANyMVIzUjNTMVMzUzRgooChQUFAoKClBQUAAAAQAKAAAARgBaAA8AADcjFSMVIzUjNSM1MxUzNTNGCgoUCgoUFBQUCgoKCkZGRgAAAQAKAAAAUABaABMAADcjFSM1IxUjNSM1MxUzNTMVMzUzUAoUChQKFAoKChQeHh4eHjw8Hh48AAABAAoAAABGAFoAHwAANyM1IzUjFSM1MzUzNSM1IzUzFTMVMzUzFSMVIxUzFTNGFAoKFAoKCgoUCgoUCgoKCgAeCigeChQKFBQKHhQKFAoAAAEACgAAAEYAWgAPAAA3IxUjFSM1IzUjNTMVMzUzRgoKFAoKFBQUMgooKAooKCgAAAEACgAAAEYAWgAXAAA3IzUzNTM1MzUzNSM1MxUjFSMVIxUjFTNGPAoKCgooPAoKCgooAB4KCgoUCh4KCgoUAAACAAoAAABGAEYADQARAAA3IzUjNTM1MzUjNTMVMwc1IxVGMgoKHh4oChQUAAoUChQKCjIUFAAAAAIACgAAAEYAWgAJAA0AADcjFSM1MxUzFTMHNSMVRgoyFB4KFBQKCloUCjIyMgAAAAEACgAAAEYARgATAAA3IxUjNSM1MzUzFTMVIzUjFTM1M0YKKAoKKAoUFBQUCgoKMgoKCgoyCgAAAgAKAAAARgBaAAkADQAANyM1IzUzNTM1Mwc1IxVGMgoKHhQUFAAKMgoUUDIyAAAAAgAKAAAARgBGAA0AEQAANyMVMxUjNSM1MzUzFTMHNSMVRigeKAoKKAoUFB4UCgoyCgoUFBQAAAABAAoAAABGAFoADwAANyMVIzUjNTM1MzUzFSMVM0YeFAoKCigeHigoKAoeCgoeAAACAAr/4gBGAEYADQARAAAXIxUjNTM1IzUjNTM1Mwc1IxVGCjIoHgoKMhQUFAoKFAoyCjwyMgAAAAEACgAAAEYAWgALAAA3IzUjFSM1MxUzFTNGFBQUFB4KADw8WhQKAAACAAoAAABGAGQAAwANAAA3IzUzFyM1MzUjNTMVMzIUFBQ8FBQoFFAUZAoyCjwAAAACAAr/4gA8AGQAAwANAAA3IzUzFSMVIzUzNSM1MzwUFAooHhQoUBR4CgpQCgAAAAABAAoAAABGAFoAFwAANyM1IzUjFSM1MxUzNTM1MxUjFSMVMxUzRhQKChQUCgoUCgoKCgAUCh5aMgoUFAoKCgAAAQAKAAAARgBaAAkAADcjNTM1IzUzFTNGPBQUKBQACkYKUAAAAQAKAAAAUABGAA0AADcjNSMVIzUjFSM1MxUzUBQKCgoUPAoAPDIyPEYKAAABAAoAAABGAEYACQAANyM1IxUjNTMVM0YUFBQyCgA8PEYKAAACAAoAAABGAEYACwAPAAA3IxUjNSM1MzUzFTMHNSMVRgooCgooChQUCgoKMgoKMjIyAAAAAgAK/+IARgBGAAkADQAANyMVIxUjNTMVMwc1IxVGCh4UMgoUFAoKHmQKMjIyAAAAAgAK/+IARgBGAAkADQAAFyM1IzUjNTM1Mwc1IxVGFB4KCjIUFB4eCjIKPDIyAAAAAQAKAAAARgBGAA0AADcjFSMVIzUzFTM1MzUzRh4KFBQKChQyCihGFAoKAAABAAoAAABGAEYAEwAANyMVIzUzNSM1IzUzNTMVIxUzFTNGCjIoHgoKMigeCgoKChQKFAoKFAoAAAEACgAAAEYAWgAPAAA3IzUjNSM1MzUzFTMVIxUzRigKCgoUHh4eAAoyChQUCjIAAAEACgAAAEYARgAJAAA3IzUjNTMVMzUzRjIKFBQUAAo8PDwAAAEACgAAAEYARgAPAAA3IxUjFSM1IzUjNTMVMzUzRgoKFAoKFBQUFAoKCgoyMjIAAAEACgAAAFAARgATAAA3IxUjNSMVIzUjNTMVMzUzFTM1M1AKFAoUChQKCgoUFBQUFBQyMigoMgAAAQAKAAAARgBGABsAADcjNSMVIzUzNTM1IzUjNTMVMzUzFSMVIxUzFTNGFBQUCgoKChQUFAoKCgoAFBQUCgoKFBQUFAoKCgAAAQAA/+IARgBGABUAADcjFSMVIxUjNTM1MzUjNSM1MxUzNTNGCgoKKB4KFAoUFBQKFAoKCgoKCjw8PAAAAQAKAAAARgBGABcAADcjNTM1MzUzNTM1IzUzFSMVIxUjFSMVM0Y8CgoKCig8CgoKCigAFAoKCgoKFAoKCgoAAAEAAAADAo+1CoEzXw889QAJAKAAAAAAwhEUhAAAAADXr6KeAAD/4gBQAGQAAAAJAAIAAAAAAAAAAQAAAIL/4gAAAFAAAAAAAFAAAQAAAAAAAAAAAAAAAAAAAAEAUAAAABQAFAAUAB4AHgAUAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAUAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAKAAoACgAAAAoAAAAAAAAAGgA2AFIAZABwAJIApADKAO4BCAEkAUYBYAGMAa4BzAHsAggCJgI6AkwCaAJ8ApACpALEAtIC7gMKAyQDPANcA3oDpgO2A8oD4gP+BCYEPgReBHoEkgSuBMYE4gT6BRYFKgVCBVoFegWMBaIFtAXOBeYF/gYUBjAGSAZaBnIGjgayBtAG8AAAAAEAAABEACQAAwAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAUAPYAAQAAAAAAAQAXAAAAAQAAAAAAAgAHABcAAQAAAAAAAwAuAB4AAQAAAAAABAAXAEwAAQAAAAAABQASAGMAAQAAAAAABgAVAHUAAQAAAAAACAAQAIoAAQAAAAAACQAQAJoAAQAAAAAACwAhAKoAAQAAAAAADAAhAMsAAwABBAkAAQAuAOwAAwABBAkAAgAOARoAAwABBAkAAwBcASgAAwABBAkABAAuAYQAAwABBAkABQAkAbIAAwABBAkABgAqAdYAAwABBAkACAAgAgAAAwABBAkACQAgAiAAAwABBAkACwBCAkAAAwABBAkADABCAoJGaXhlZHN5cyBFeGNlbHNpb3IgMy4wMVJlZ3VsYXJEYXJpZW5WYWxlbnRpbmU6IEZpeGVkc3lzIEV4Y2Vsc2lvciAzLjAxOiAyMDA3Rml4ZWRzeXMgRXhjZWxzaW9yIDMuMDFWZXJzaW9uIDMuMDEwIDIwMDdGaXhlZHN5c0V4Y2Vsc2lvcklJSWJEYXJpZW4gVmFsZW50aW5lRGFyaWVuIFZhbGVudGluZWh0dHA6Ly93d3cuZml4ZWRzeXNleGNlbHNpb3IuY29tL2h0dHA6Ly93d3cuZml4ZWRzeXNleGNlbHNpb3IuY29tLwBGAGkAeABlAGQAcwB5AHMAIABFAHgAYwBlAGwAcwBpAG8AcgAgADMALgAwADEAUgBlAGcAdQBsAGEAcgBEAGEAcgBpAGUAbgBWAGEAbABlAG4AdABpAG4AZQA6ACAARgBpAHgAZQBkAHMAeQBzACAARQB4AGMAZQBsAHMAaQBvAHIAIAAzAC4AMAAxADoAIAAyADAAMAA3AEYAaQB4AGUAZABzAHkAcwAgAEUAeABjAGUAbABzAGkAbwByACAAMwAuADAAMQBWAGUAcgBzAGkAbwBuACAAMwAuADAAMQAwACAAMgAwADAANwBGAGkAeABlAGQAcwB5AHMARQB4AGMAZQBsAHMAaQBvAHIASQBJAEkAYgBEAGEAcgBpAGUAbgAgAFYAYQBsAGUAbgB0AGkAbgBlAEQAYQByAGkAZQBuACAAVgBhAGwAZQBuAHQAaQBuAGUAaAB0AHQAcAA6AC8ALwB3AHcAdwAuAGYAaQB4AGUAZABzAHkAcwBlAHgAYwBlAGwAcwBpAG8AcgAuAGMAbwBtAC8AaAB0AHQAcAA6AC8ALwB3AHcAdwAuAGYAaQB4AGUAZABzAHkAcwBlAHgAYwBlAGwAcwBpAG8AcgAuAGMAbwBtAC8AAAACAAAAAAAA//EACgAAAAAAAAAAAAAAAAAAAAAAAABEAEQAAAAEAAsADAAPABEAEwAUABUAFgAXABgAGQAaABsAHAAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0ARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAAA=) format("truetype"),url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxkZWZzPjxmb250IGlkPSJmb250ZWRpdG9yIiBob3Jpei1hZHYteD0iODAiPjxmb250LWZhY2UgZm9udC1mYW1pbHk9IkZpeGVkc3lzIEV4Y2Vsc2lvciAzLjAxIiBm [...]

2023-06-16 23:14 UTC, mfwmyfacewhen commented on static/i18n/404.en.html
> +  </div>
I had to

2023-06-17 07:59 UTC, dngray commented
Is there some reason we went with a 404 page that looks completely different to the rest of the page:

![2096103703](https://github.com/privacyguides/privacyguides.org/assets/48640805/6e52218b-157b-4eda-acf0-815511071ac1)

Not complaining, I think the nostalgic look is cool, but it isn't all that consistent.

2023-06-19 01:22 UTC, dngray approved these changes

2023-06-19 01:25 UTC, mfwmyfacewhen approved these changes

2023-06-19 01:33 UTC, dngray commented
This was merged in

2023-06-19 01:34 UTC, dngray commented
Think we'll need to fix that check:

❌ No sources found for '/static/*.en.*' pattern. Check the source paths in your configuration file
✔️  No obsolete files were found
✔️  No obsolete directories found
❌ Current execution finished with errors

2023-06-19 18:00 UTC, merged