Translation page
privacyguides/privacyguides.org pull request #2224
Opened 2023-07-06 12:03 UTC by dngray

Changes proposed in this PR:

By including this page hopefully translators will notice what might have been [buried in the blog article](https://blog.privacyguides.org/2023/02/26/i18n-announcement). 

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-07-07 04:52 UTC, mfwmyfacewhen requested changes

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +# Admonitions
```suggestion
## Admonitions
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +Throughout the site we use MkDocs's [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage), to show information to readers about the products such as `example`, `warn
```suggestion
Throughout the site we use MkDocs's [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage), to show information to readers. They come in a few different flavors such as `example`, `warning`, `tip`, etc.
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +By default when admonitions are used they will have an English string on the site. This can be [customized](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#changing-the-title), wit
```suggestion
By default when admonitions are used they will have an English string on the site. This can be [customized](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#changing-the-title), without too much effort. For example, if you were translating an admonition of type [`warning`](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#type:warning) to Dutch, this is how you would write it:
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +Downloads are a [custom admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions) that we use and you would write that like:
```suggestion
Downloads are a [custom admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions) which is written as follows:
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +The same goes for other types, such as `tip`, `example`, `warning`, `danger` etc. Recommendations are also admonitions, but they do not need overriding, because the default has no text, so they are a
```suggestion
The same goes for other types, such as `tip`, `example`, `warning`, `danger` etc. Recommendations are also admonitions, but they do not need overriding. Because the default has no text, they are always written like this:
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +Translation software gets the translation quite reliable however, attention does need to be given that the translated string is correct.
```suggestion
Translation software gets the translation quite accurate; however, you need to make sure translated string is correct.
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +We have sometimes found that the syntax for inserting an image like above was missing the `![` or an extra space was placed between the text and the path, eg `](`. If a translation string is clearly
```suggestion
We have sometimes found that the syntax for inserting an image like above was missing the `![` or an extra space was placed between the text and the path, e.g. `](`. If a translation string is clearly not correct, we encourage you to **delete** it by pressing the trash icon [or vote](https://support.crowdin.com/enterprise/getting-started-for-volunteers/#voting-view) on which one you think sounds best. When invalid strings are deleted, they are removed from the organization's [translation memory](https://support.crowdin.com/enterprise/translation-memory), meaning that when the source string is seen again, it won't suggest the incorrect translation.
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +For examples like the above admonitions inverted commas, eg: `" "` must be used to specify string text. MkDocs will not correctly interpret other symbols ie, `「 」` or `« »`. They work fine within the
```suggestion
For examples like the above admonitions quotation marks, eg: `" "` must be used to specify string text. MkDocs will not correctly interpret other symbols ie, `「 」` or `« »`. They work fine within the text, for the translation though.
```
Americans call those quotation marks, dunno if it matters too much but we agreed on American English.

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +# Translation output
```suggestion
## Translation output
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +We'd like to thank the [translation team](https://crowdin.com/project/privacyguides/reports/top-members) who spent many hours on translating the content, that we now have. We're going to launch in Du
```suggestion
We'd like to thank the [translation team](https://crowdin.com/project/privacyguides/reports/top-members) who spent many hours on translating the content of the site. We're going to launch in Dutch, French and Hebrew.
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +# Brackets
```suggestion
## Brackets
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +For links these must regular brackets ie `( )` CJK style brackets such as `（ ）` will not work for links.
```suggestion
For links, these must regular brackets i.e. `( )`. CJK style brackets such as `（ ）` will not work for links.
```

2023-07-07 04:52 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +Please note that the English version of the site is the primary version, meaning changes occur there first. This means it is still possible that specific languages may be behind. If you notice such a
```suggestion
Please note that the English version of the site is the primary version, meaning changes occur there first. If you notice a language falling behind the English version, please help out. We cannot guarantee the accuracy of all our translations. If you have a suggestion about content specific to your region, please open an issue or pull request to our [main repository](https://github.com/privacyguides/privacyguides.org).
```

2023-07-07 05:52 UTC, jonaharagon commented on docs/meta/translations.md
> +We'd like to thank the [translation team](https://crowdin.com/project/privacyguides/reports/top-members) who spent many hours on translating the content, that we now have. We're going to launch in Du
No need to include ”timely” information from the blog post like “we’re going to launch…” etc., this meta page should strictly be for translation policies/guides.

2023-07-07 05:53 UTC, jonaharagon commented on docs/meta/translations.md
> +For examples like the above admonitions inverted commas, eg: `" "` must be used to specify string text. MkDocs will not correctly interpret other symbols ie, `「 」` or `« »`. They work fine within the
This section is also a bit confusing. Does this **only** apply to admonitions (I think so?) or are there other areas where MkDocs is interpreting things as strings? If this is only for admonitions it should be moved to that section I think, or can you give another example of where this applies?

2023-07-07 12:52 UTC, dngray commented on docs/meta/translations.md
> +The same goes for other types, such as `tip`, `example`, `warning`, `danger` etc. Recommendations are also admonitions, but they do not need overriding, because the default has no text, so they are a
I was always taught to never start a sentence with because

2023-07-07 12:54 UTC, dngray commented on docs/meta/translations.md
> +For examples like the above admonitions inverted commas, eg: `" "` must be used to specify string text. MkDocs will not correctly interpret other symbols ie, `「 」` or `« »`. They work fine within the
Only admonitions, because they are customizable by translators and need to remain so.

2023-07-07 12:56 UTC, dngray commented on docs/meta/translations.md
> +We'd like to thank the [translation team](https://crowdin.com/project/privacyguides/reports/top-members) who spent many hours on translating the content, that we now have. We're going to launch in Du
Yes it should be that might have been my mistake from copying it over from the blog article.

2023-07-07 12:58 UTC, mfwmyfacewhen commented on docs/meta/translations.md
> +The same goes for other types, such as `tip`, `example`, `warning`, `danger` etc. Recommendations are also admonitions, but they do not need overriding, because the default has no text, so they are a
It's fine in this [case](https://www.quickanddirtytips.com/articles/can-you-start-a-sentence-with-because/) since there's an independent clause following it.

2023-07-07 13:09 UTC, dngray commented on docs/meta/translations.md
> +The same goes for other types, such as `tip`, `example`, `warning`, `danger` etc. Recommendations are also admonitions, but they do not need overriding, because the default has no text, so they are a
I think I re worded this so it won't be a fragment.

2023-07-07 13:49 UTC, blacklight447 approved these changes

2023-07-10 11:36 UTC, freddy-m approved these changes

2023-07-10 16:54 UTC, jonaharagon commented on config/mkdocs.en.yml
> +        - 'meta/translations.md'
When you add a page you have to add it to every file in `/config`, not just English. I'm pushing a commit to make this change now, then it LGTM.

2023-07-10 16:54 UTC, jonaharagon approved these changes

2023-07-11 04:51 UTC, dngray commented on config/mkdocs.en.yml
> +        - 'meta/translations.md'
Ah yes, i forgot about that.

2023-07-11 04:58 UTC, merged