Update Qubes Overview and Desktop/PC pages: use qube not VM
privacyguides/privacyguides.org pull request #2257
Opened 2023-07-31 04:20 UTC by nopeitsnothing

Changes proposed in this PR:

- Update terminology used to refer to ***qubes***

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-07-31 17:25 UTC, mfwmyfacewhen approved these changes

2023-08-01 07:06 UTC, dngray requested changes
The rest looks good to me

2023-08-01 07:06 UTC, dngray commented on docs/os/qubes-overview.md
> +[**Qubes OS**](../desktop.md#qubes-os) is an open-source operating system which uses the [Xen](https://en.wikipedia.org/wiki/Xen) hypervisor to provide strong security for desktop computing through i
I think we should say that a Qube is a VM at least once.

```suggestion
[**Qubes OS**](../desktop.md#qubes-os) is an open-source operating system which uses the [Xen](https://en.wikipedia.org/wiki/Xen) hypervisor to provide strong security for desktop computing through isolated *qubes*, which are Virtual Machines. You can assign each *qube* a level of trust based on its purpose. Qubes OS provides security by using isolation. It only permits actions on a per-case basis and therefore is the opposite of [badness enumeration](https://www.ranum.com/security/computer_security/editorials/dumb/).
```

2023-08-01 19:17 UTC, dngray approved these changes

2023-08-01 19:20 UTC, dngray approved these changes

2023-08-01 19:30 UTC, merged