AnonAddy rebranded as addy.io
privacyguides/privacyguides.org pull request #2263
Opened 2023-08-10 22:56 UTC by freddy-m

https://addy.io/blog/anonaddy-has-rebranded-as-addy-io/

Changes proposed in this PR:

- 

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-08-11 13:14 UTC, willbrowningme commented
Thanks, I was just about to make my own PR.

The free plan is now limited to `10 Shared Aliases` and `1 Recipient Mailbox`.

A new SVG logo that you can use can be found here - [https://addy.io/icon.svg](https://addy.io/icon.svg), it should work on the light and dark backgrounds.

Let me know if you need anything else.

2023-08-16 07:18 UTC, dngray commented
@willbrowningme does that look right to you?

2023-08-16 07:23 UTC, willbrowningme commented on docs/email.md
> +- ![Addy logo](assets/img/email/addy.svg#only-light){ .twemoji }![Addy logo](assets/img/email/addy-dark.svg#only-dark){ .twemoji } [AnonAddy](email.md#addy)
Update `AnonAddy` to `addy.io` at the end of the line inside the square brackets.

2023-08-16 07:24 UTC, willbrowningme commented on docs/email.md
> +    **addy.io** lets you create 10 domain aliases on a shared domain for free, or unlimited "standard" aliases which are less anonymous and require a Lite or Pro plan.
Remove addition of `and require a Lite or Pro plan.`, you can still create unlimited "standard" aliases on the Free plan.

2023-08-16 07:25 UTC, willbrowningme commented on docs/email.md
> +        - [:simple-android: Android](https://addy.io//faq/#is-there-an-android-app)
Remove extra forward slash in URL `//faq` on this line and the line below.

2023-08-16 07:28 UTC, willbrowningme commented on docs/email.md
> +The number of shared aliases (which end in a shared domain like @addy.io) that you can create is limited to 10 on addy.io's free plan, 50 on their €1/month plan and unlimited on the €3/month plan. Yo
The currency can be chosen as $, £ or € at checkout (it just defaults to the user's location on the landing page) so it makes sense to leave this in dollars since that is where the majority of customers are from.

2023-08-16 07:28 UTC, willbrowningme commented on docs/email.md
>  - [x] 2 Recipient Mailboxes
Update to 1 Recipient Mailbox.

2023-08-16 07:29 UTC, dngray commented on docs/email.md
> +The number of shared aliases (which end in a shared domain like @addy.io) that you can create is limited to 10 on addy.io's free plan, 50 on their €1/month plan and unlimited on the €3/month plan. Yo
Okay that's weird i thought I updated these things.

2023-08-16 07:32 UTC, dngray commented on docs/email.md
> +The number of shared aliases (which end in a shared domain like @addy.io) that you can create is limited to 10 on addy.io's free plan, 50 on their €1/month plan and unlimited on the €3/month plan. Yo
Is there a way to force it to a particular currency?

2023-08-16 07:34 UTC, dngray commented on docs/email.md
> +- ![Addy logo](assets/img/email/addy.svg#only-light){ .twemoji }![Addy logo](assets/img/email/addy-dark.svg#only-dark){ .twemoji } [AnonAddy](email.md#addy)
Are you planning on renaming your github org?

2023-08-16 07:39 UTC, dngray commented on docs/email.md
> +The number of shared aliases (which end in a shared domain like @addy.io) that you can create is limited to 10 on addy.io's free plan, 50 on their €1/month plan and unlimited on the €3/month plan. Yo
Okay I changed, the pricing back to $, that should be good now.

2023-08-17 05:34 UTC, dngray approved these changes

2023-08-17 06:44 UTC, willbrowningme requested changes
Line 278 of email.md needs updating to:

`- ![addy.io logo](assets/img/email/addy.svg#only-light){ .twemoji }![addy.io logo](assets/img/email/addy-dark.svg#only-dark){ .twemoji } [addy.io](email.md#addyio)`

Line 326 to:

`- [x] 10 Shared Aliases`

Line 133 of tools.md to:

`- ![addy.io logo](assets/img/email/addy.svg#only-light){ .twemoji }![addy.io logo](assets/img/email/addy-dark.svg#only-dark){ .twemoji } [addy.io](email.md#addyio)`

2023-08-17 21:12 UTC, freddy-m commented on docs/email.md
> +- ![Addy logo](assets/img/email/addy.svg#only-light){ .twemoji }![Addy logo](assets/img/email/addy-dark.svg#only-dark){ .twemoji } [Addy.io](email.md#addy)
I agree, cc @dngray

2023-08-22 04:08 UTC, dngray commented
@willbrowningme think we're done with this now. I made a mini logo for the tools page.

2023-08-22 06:36 UTC, willbrowningme commented
@dngray Yep all looks good to me, thank you!

2023-08-22 12:11 UTC, merged