Fix inaccurate info in macOS
privacyguides/privacyguides.org pull request #2266
Opened 2023-08-17 05:57 UTC by dngray

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-10-04 20:20 UTC, jonaharagon requested changes
These changes are based on some random messages on Matrix, sent by somebody who has 0 knowledge in this area. I'll provide additional information about our information here and make any changes that do turn out to be necessary later today.

2023-10-04 21:35 UTC, jonaharagon requested changes
The only changes I see in this PR that would improve this guide are removing [L120-L125](https://github.com/privacyguides/privacyguides.org/pull/2266/files#diff-fab019238d4e754539587953bf8fda9b5bab7a7dcd3d210450e47c930040fd5fL120-L125) and changing the MAC address randomization command slightly. I've included detailed notes below.

2023-10-04 21:35 UTC, jonaharagon commented on docs/os/macos-overview.md
> -This will be reset on reboot.
Given that we cover MAC randomization on other platforms (Linux), removing this section doesn't seem necessary for people who are interested in doing so.

However, this command could be improved as follows:

```
openssl rand -hex 6 | sed 's/^\(.\{1\}\)./\12/; s/\(..\)/\1:/g; s/.$//' | xargs sudo ifconfig en1 ether
```

This would set the second character in the generated MAC address to `2`, denoting it as a randomized MAC address and preventing collisions. Setting the first 3 octets to an existing OUI, as suggested on Matrix, is less preferable (this is the behavior many hypervisors will use to generate a MAC address) because it does not match how iOS and Android generate random MAC addresses, nor the spec.

Technically the second character could be `2`, `6`, `A`, or `E` to denote a locally administered unicast MAC address, but I don't think a single unrandomized bit will affect anyone's privacy.

2023-10-04 21:35 UTC, jonaharagon commented on docs/os/macos-overview.md
> -If you choose to also allow applications from identified developers, be careful about the apps you run and where you obtain them.
I'm okay with removing this section, not because it is bad advice, but because configuring a computer for a less technical user "such as children" might be out of scope for Privacy Guides. Do we think we should be including advice for bubble-wrapping other people's devices on the site?

2023-10-04 21:35 UTC, jonaharagon commented on docs/os/macos-overview.md
> +macOS apps downloaded from the App Store are required to use the [App Sandbox](https://developer.apple.com/documentation/security/app_sandbox). You should avoid non-App Store software as much as poss
Rearranging these sections doesn't seem to serve a purpose except to create additional work for translators, and the heading levels here just seem to be wrong (h3 on App Revocation Checks underneath an h4)

2023-10-10 05:27 UTC, jonaharagon commented
mm why don't we merge #2303 ASAP, and then we can discuss the rest of the changes here further.

2023-11-01 14:33 UTC, freddy-m commented
@privacyguides/team / @jonaharagon should we have another look at this now that #2303 is merged?

2023-11-13 08:49 UTC, jonaharagon commented
The review comments I added [above](https://github.com/privacyguides/privacyguides.org/pull/2266#pullrequestreview-1658446125) still need to be addressed. If nobody disagrees with what I said there, then no further changes need to be made and this PR can be closed. LMK.

2023-11-13 09:07 UTC, closed without merging