Add hardware section
privacyguides/privacyguides.org pull request #2268
Opened 2023-08-17 06:01 UTC by dngray

Resolves #1899, resolves #1989, resolves #1864

- [x] Laptop vendors shipping malware/adware
- [x] Hardware keys
- [x] Dead man switches
- [x] USB "condoms"
- [x] TPM's/hardware security chips
- [x] Biometrics
- [x] Webcam/microphone blocking
- [x] Privacy screens
- [x] Routers/Networking devices
- [x] Encrypted Drives
- [x] Anti-Interdiction

See previous discussion: https://github.com/privacyguides/privacyguides.org/pull/1939

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-08-17 10:05 UTC, blacklight447 commented
Regarding hardware switches for laptops, should we put a notice that some switches in laptop are purely a software based switch which technically give you a false sense of security, since malware can turn it on?


Other then that, this seems all very comprehensive and correct, great job guys.

2023-08-17 12:54 UTC, maltfield commented
> The best way to prevent a targeted attack against you before a device is in your possession is to purchase a device in a physical store, rather than ordering it to your address.

Unfortunately, I tried doing this recently and found that no stores sold high-quality (business-grade) laptops. They only sold shitty cheap consumer-grade hardware in-store, and said that all their business-class laptops were only available on their website. I think this is something that was exacerbated during the pandemic, when purchases online shot through the roof.

Maybe it's a good idea to mention proxyshops here as a means to buy hardware online anonymously.

Amazon has lockers that technically would allow you to ship hardware to yourself anonymously, but if you create a new account and load it with an anonymously-purchased giftcard, they'll close your account citing fraud. But there is a proxy shop in the US that accepts Monero and will order a hardware on your behalf (they originally were created to buy cryptocurrency hardware wallets) and ship it to an amazon locker.

 * https://anonshop.app/

There's also another great proxy shop in Germany that will accept crypto- or fiat-currency and either forward the item to you via post or let you pick it up at their location Leipzig.

 * https://proxysto.re

I think it would be worthwhile to mention proxyshops for users who live in a country where they cannot buy the security hardware that they need at a physical brick-and-mortar, yet need to purchase it anonymously to avoid a targeted interdiction attack.

2023-08-17 13:01 UTC, maltfield commented
The `Hardware Security Programs` has one paragraph about Windows and one paragraph about Mac.

I think we should add a third paragraph mentioning Linux machines, with specific focus on distros that are designed for security. I think it would be wise to mention QubesOS in this section, and to include a link to the PrivacyGuides.org article on Qubes

 * https://www.privacyguides.org/en/os/qubes-overview/

As this is a section on hardware, I think it would be good to also link to Qubes' Hardware Compatibility List

 * https://www.qubes-os.org/hcl/

2023-08-18 08:43 UTC, blacklight447 commented
One more thought, should we mention the possibility of using speakers as a microphone, there is rrsearch out there showing its possible, but i would guess its a very unlikely thing to happen even to niche very high threatmodels.

2023-08-19 17:01 UTC, namazso commented
@blacklight447 can you link any such research? While electrically microphones and speakers are the same, as soon as you plug them into a chip that only does one of ADC or DAC that feature is completely lost.

2023-11-27 09:14 UTC, dngray commented
@habibm1361 i removed your comment for spam.

Nothing privacy friendly about a notebook that is bundled with ChatGPT. ChatGPT literally works on the premise of sending data away to a remote server.

2024-03-21 12:19 UTC, inson1 commented
Why there is no info about coreboot and open hardware?

2024-03-21 12:26 UTC, inson1 commented
Anyway I think its still improvment, why it isnt merged?

2024-03-21 15:44 UTC, maltfield commented
@inson1 see
 * https://github.com/privacyguides/privacyguides.org/pull/1939
 * https://github.com/privacyguides/privacyguides.org/issues/1899

It looks like the first PR was merged. Both are called "Add hardware section"

I know there was [some hesitation](https://github.com/privacyguides/privacyguides.org/issues/1899#issuecomment-1404078852) to recommend devices with coreboot (due to it mostly being old devices), but the vendors putting it on newer devices were OK'd for listing. And imho it would benefit this guide to recommend those vendors specifically and why coreboot is necessary (though not sufficient) for privacy hardware.

2024-03-24 15:34 UTC, maltfield commented
> maybe add an anti-theft recommendation

I think "Dead man switches" (like [BusKill](https://github.com/buskill/buskill-app)) *are* the anti-theft recommendation. Or did you have something else in mind?

2024-04-01 17:57 UTC, rollsicecream requested changes

2024-04-01 17:57 UTC, rollsicecream commented on docs/basics/hardware.md
> +If you build your own PC, you may need to manually update your motherboard's firmware by downloading it from your OEM's website.
Should we mention the use of `fwupd` if the user that wants to check firmware updates uses Linux?

```suggestion
If you build your own PC, you may need to manually update your motherboard's firmware by downloading it from your OEM's website. If you use Linux, consider using the built-in `fwupd` tool that will let update any firmware updates.
```

2024-04-15 23:16 UTC, redoomed1 requested changes
Mostly grammar and fixes for `warning` admonitions so that they appear yellow instead of the generic blue in the GH actions preview

2024-04-15 23:16 UTC, redoomed1 commented on docs/basics/hardware.md
> +It's not normally necessary to do this if the manufacturer of the hardware also develops the operating system, such as with Apple devices, Microsoft Surface line or Android based devices such as the
```suggestion
It's not normally necessary to do this if the manufacturer of the hardware also develops the operating system, such as with Apple devices, the Microsoft Surface line or Android-based devices such as Chromebooks.
```

2024-04-15 23:16 UTC, redoomed1 commented on docs/basics/hardware.md
> +<div class="admonition Warning" markdown>
```suggestion
<div class="admonition warning" markdown>
```

2024-04-15 23:16 UTC, redoomed1 commented on docs/basics/hardware.md
> +Android defines three [security classes](https://source.android.com/docs/security/features/biometric/measure#biometric-classes) for biometrics; you should check that your device is class 3 before ena
```suggestion
Android defines three [security classes](https://source.android.com/docs/security/features/biometric/measure#biometric-classes) for biometrics; you should check that your device is Class 3 before enabling biometrics.
```

2024-04-15 23:16 UTC, redoomed1 commented on docs/basics/hardware.md
> +<div class="admonition Warning" markdown>
```suggestion
<div class="admonition warning" markdown>
```

2024-04-15 23:16 UTC, redoomed1 commented on docs/basics/hardware.md
> +Similarly, for your microphone, you'll just need to trust your OS's built-in permission controls. Alternatively, buy a device that doesn't have a built-in microphone and use an external microphone th
```suggestion
Similarly, for your microphone, you'll just need to trust your OS's built-in permission controls. Alternatively, buy a device that doesn't have a built-in microphone and use an external microphone that you can unplug when you're done using it. Some devices, like a [MacBook or an iPad](https://support.apple.com/guide/security/hardware-microphone-disconnect-secbbd20b00b/web), feature a hardware disconnect for the microphone when you close the lid. Many PC BIOSes have the option to disable camera and Microphone. When disabled there, the hardware won't even appear as a device on a booted system.
```

2024-04-15 23:16 UTC, redoomed1 commented on docs/basics/hardware.md
> +Most consumer routers allow you to do this by enabling a separate "guest" network that can't talk to your main network. All untrusted devices can go here, including IoT devices like your smart fridge
```suggestion
Most consumer routers allow you to do this by enabling a separate "guest" network that can't talk to your main network. All untrusted devices can go here, including IoT devices like your smart fridge, thermostat, TV, etc.
```

2024-04-28 14:50 UTC, redoomed1 requested changes

2024-04-28 14:50 UTC, redoomed1 commented on docs/basics/hardware.md
> +If you build your own PC, you may need to manually update your motherboard's firmware by downloading it from your OEM's website. If you use Linux, consider using the built-in [`fwupd`](https://fwupd.
```suggestion
If you build your own PC, you may need to manually update your motherboard's firmware by downloading it from your OEM's website. If you use Linux, consider using the built-in [`fwupd`](https://fwupd.org) tool that will let you check for and apply any firmware updates available for your motherboard.
```
Another wording suggestion for clarity: "update [...] updates" sounds a little awkward

2024-06-03 02:24 UTC, redoomed1 requested changes

2024-06-03 02:24 UTC, redoomed1 commented on docs/hardware.md
> +- macOS running on an Apple SoC takes advantage of [hardware security](../os/macos-overview.md#hardware-security) which may not be available with third party operating systems.
Fix for now-broken link as a result of moving the page; more in the next suggestions
```suggestion
- macOS running on an Apple SoC takes advantage of [hardware security](os/macos-overview.md#hardware-security) which may not be available with third party operating systems.
```

2024-06-03 02:24 UTC, redoomed1 commented on docs/hardware.md
> +If your device is [encrypted](../encryption.md), your data is most secure when your device is completely powered off (as opposed to merely asleep), i.e. before you've entered your encryption key or l
```suggestion
If your device is [encrypted](encryption.md), your data is most secure when your device is completely powered off (as opposed to merely asleep), i.e. before you've entered your encryption key or lock screen password for the first time. On phones, this state of higher security is referred to as "Before First Unlock" (BFU), and "After First Unlock" (AFU) once you enter the correct password after a reboot/power-on. AFU is considerably less secure against digital forensics toolkits and other exploits, compared to BFU. Therefore, if you are concerned about an attacker with physical access to your device, you should turn it off fully whenever you aren't using it.
```

2024-06-03 02:24 UTC, redoomed1 commented on docs/hardware.md
> +### Hardware Keys
```suggestion
### Hardware Security Keys
```

2024-06-03 02:24 UTC, redoomed1 commented on docs/hardware.md
> +[More Info :material-arrow-right-drop-circle:](../multi-factor-authentication/#hardware-security-keys){ .md-button }
Since there's now a separate page for hardware key recommendations...
```suggestion
[More Info on hardware keys :material-arrow-right-drop-circle:](basics/multi-factor-authentication.md#hardware-security-keys)

[Recommended hardware keys](security-keys.md){ .md-button }
```

2024-06-03 02:24 UTC, redoomed1 commented on docs/hardware.md
> +Many consumer-grade routers aren't supported for very long. If your router isn't supported by the manufacturer anymore, you can check if it's supported by [FOSS firmware](../router.md). You can also
```suggestion
Many consumer-grade routers aren't supported for very long. If your router isn't supported by the manufacturer anymore, you can check if it's supported by [FOSS firmware](router.md). You can also buy routers that come with FOSS firmware installed by default; these tend to be supported longer than most routers.
```

2024-06-03 05:30 UTC, dngray commented on docs/hardware.md
> +[More Info :material-arrow-right-drop-circle:](../multi-factor-authentication/#hardware-security-keys){ .md-button }
Yeah I hadn't gotten around to doing that but we can do that.

2024-06-03 06:02 UTC, dngray commented on docs/hardware.md
> +- macOS running on an Apple SoC takes advantage of [hardware security](../os/macos-overview.md#hardware-security) which may not be available with third party operating systems.
Oh I fixed this one.

2024-06-04 03:52 UTC, redoomed1 requested changes

2024-06-04 03:52 UTC, redoomed1 commented on docs/hardware.md
> +[More Info on hardware keys :material-arrow-right-drop-circle:](basics/multi-factor-authentication.md#hardware-security-keys)
```suggestion
[Learn more about hardware keys](basics/multi-factor-authentication.md#hardware-security-keys){ .md-button }
```
The way I styled this in my last review looks ugly in the GH actions preview, so I'm changing it back to a button (both links here are buttons with this change).

2024-06-04 04:00 UTC, redoomed1 requested changes

2024-06-04 04:00 UTC, redoomed1 commented on docs/hardware.md
> +[Recommended hardware keys](security-keys.md){ .md-button }
```suggestion
- [Learn more about hardware keys :material-arrow-right-drop-circle:](basics/multi-factor-authentication.md#hardware-security-keys)

- [Recommended hardware keys :material-arrow-right-drop-circle:](security-keys.md)
```
Having each link styled differently imo looks ugly in the GH actions preview. The changes here make them have the same style and add bullet points; since it's one link after the other, two buttons would take too much space.

2024-07-20 20:59 UTC, jonaharagon requested changes
I pushed a commit to move this to the KB instead, and renamed the page. Otherwise just a few small changes I'd still make here.

2024-07-20 20:59 UTC, jonaharagon commented on docs/basics/hardware.md
> +It's not necessary to do this if the manufacturer of the hardware also develops the operating system, such as with Apple devices, the Microsoft Surface line or Android-based devices such as Chromeboo
I don't think this is true, the stock image on Macs (and AFAIK Surfaces) is different from the standard OS installation, and it's often recommended to reinstall from a fresh copy even in this case. Also Chromebooks are not Android-based.

```suggestion
```

2024-07-20 20:59 UTC, jonaharagon commented on docs/basics/hardware.md
> +
```suggestion

Even if you don't use these operating systems, participation in these programs may indicate that the manufacturer is following best practices when it comes to hardware security and updates.

```

2024-07-20 20:59 UTC, jonaharagon commented on docs/basics/hardware.md
> +Hardware keys are devices that use strong cryptography to authenticate you to a device or account, the idea being that it functions similarly to a regular key; you need to have it in order gain acces
```suggestion
Hardware keys are devices that use strong cryptography to authenticate you to a device or account. The idea is that because they can not be copied, you can use them to secure accounts in such a way that they can only be accessed with physical possession of the key, eliminating many remote attacks.
```

2024-07-20 20:59 UTC, jonaharagon commented on docs/basics/hardware.md
> +Similarly, for your microphone, you'll just need to trust your OS's built-in permission controls. Alternatively, buy a device that doesn't have a built-in microphone and use an external microphone th
```suggestion
For microphone access, in most cases you will need to trust your OS's built-in permission controls. Alternatively, buy a device that doesn't have a built-in microphone and use an external microphone that you can unplug when you're done using it. Some devices, like a [MacBook or an iPad](https://support.apple.com/guide/security/hardware-microphone-disconnect-secbbd20b00b/web), feature a hardware disconnect for the microphone when you close the lid.

Many computers have a BIOS option to disable the camera and microphone. When disabled there, the hardware won't even appear as a device on a booted system.
```

2024-07-20 20:59 UTC, jonaharagon commented on docs/basics/hardware.md
> +A dead man's switch stops a piece of machinery from operating without the presence of a human operator. Originally, these were meant as a safety measure; however, the same concept can be applied to a
```suggestion
A dead man's switch stops a piece of machinery from operating without the presence of a human operator. Originally, these were meant as a safety measure, but the same concept can be applied to an electronic device to lock it when you're not present.
```

We like semicolons too much lol

2024-07-20 20:59 UTC, jonaharagon commented on docs/basics/hardware.md
> +As the saying goes, "less is more". The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date. Many of these d
```suggestion
As the saying goes, "less is more". The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date. Many of these devices run outdated software and have short support cycles. When possible, prefer IoT devices with no network connectivity or only bluetooth.
```

2024-07-20 21:14 UTC, jonaharagon commented on docs/basics/hardware.md
> +Some laptops are able to detect when you're present and can lock automatically when you aren't sitting in front of the screen. You should check the settings in your OS to see if your computer support
```suggestion
Some laptops are able to [detect](https://support.microsoft.com/en-us/windows/managing-presence-sensing-settings-in-windows-11-82285c93-440c-4e15-9081-c9e38c1290bb) when you're present and can lock automatically when you aren't sitting in front of the screen. You should check the settings in your OS to see if your computer supports this feature.
```

2024-07-20 21:22 UTC, redoomed1 commented on docs/basics/hardware.md
> +As the saying goes, "less is more". The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date. Many of these d
Also, "bluetooth" should be capitalized.

2024-07-21 06:41 UTC, jonaharagon commented on docs/basics/hardware.md
> +As the saying goes, "less is more". The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date. Many of these d
Oh that's an excellent question. We can avoid it entirely:

```suggestion
As the saying goes, "less is more". The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date. Many of these devices run outdated software and have short support cycles. When possible, prefer IoT devices which use a local-only mesh like Zigbee without access to the internet.
```

2024-07-21 07:02 UTC, jonaharagon commented on docs/basics/hardware.md
> +As the saying goes, "less is more". The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date. Many of these d
```suggestion
As the saying goes, "less is more". Every internet-connected device you add to your network increases your potential attack surface. The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date.
```

2024-07-21 07:05 UTC, jonaharagon approved these changes

2024-07-21 23:17 UTC, redoomed1 commented on docs/basics/hardware.md
> +As the saying goes, "less is more". The fewer devices you have on your network, the less attack surface you'll have and the less work it will be to make sure they all stay up-to-date. Many of these d
> Every internet-connected device you add to your network increases your potential attack surface.

> The fewer devices you have on your network, the less attack surface you'll have

These two statements are kind of redundant, no? :smile:

2024-07-22 00:03 UTC, redoomed1 requested changes

2024-07-22 00:03 UTC, redoomed1 commented on docs/basics/hardware.md
> +As the saying goes, "less is more". Every internet-connected device you add to your network increases your potential attack surface. The fewer devices you have on your network, the less attack surfac
```suggestion
As the saying goes, "less is more". The fewer devices you have connected to your network, the less potential attack surface you'll have and the less work it will be to make sure they all stay up-to-date.
```
I think that the second sentence is kind of redundant with this part of the third sentence:

> The fewer devices you have on your network, the less attack surface you'll have

So I integrated some parts of the redundant sentence into the aforementioned statement about minimalism

2024-07-28 01:47 UTC, merged

2024-07-28 11:13 UTC, jermanuts commented
At https://www.privacyguides.org/en/basics/hardware/#routers could you emphasis how bad ISP provided routers are? Here's a good resource https://www.routersecurity.org/ISProuters.php. The same author written another article about consumer routers https://routersecurity.org/consumerrouters.php.