Update SimpleX chat now supports MacOS and Linux
privacyguides/privacyguides.org pull request #2283
Opened 2023-09-26 13:35 UTC by xiaoyu2006

Changes proposed in this PR:

- Update SimpleX chat client support [status](https://simplex.chat/downloads/#desktop-app) ([archived](https://web.archive.org/web/20230926133413/https://simplex.chat/downloads/#desktop-app))

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-09-30 13:16 UTC, freddy-m requested changes
Good spot, however the wording seems a bit off. @privacyguides/team any thoughts on what to change it to?

2023-10-04 11:33 UTC, blacklight447 approved these changes

2023-10-05 05:06 UTC, dngray approved these changes

2023-10-05 09:28 UTC, freddy-m approved these changes
LGTM

2023-10-05 09:31 UTC, merged