Reorganize DNS recommendations
privacyguides/privacyguides.org pull request #2330
Opened 2023-11-15 04:03 UTC by jonaharagon

Changes proposed in this PR:

- https://discuss.privacyguides.net/t/split-dns-recommendations-into-secure-non-filtering-providers-and-filtering-saas-providers/15026?u=jonah

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2024-03-14 04:06 UTC, Mikaela commented
You are missing signed profiles at least for DNS0 and Mullvad if I am reading this correctly on mobile.

- https://github.com/mullvad/encrypted-dns-profiles
- https://dns0.eu lists them for all options
  - https://docs.dns0.eu/apple-configuration-profile/advanced-profile-api allows customizing the profile

2024-03-14 04:07 UTC, Mikaela commented
Why not have a field in the table for Apple support actually?

2024-03-14 11:30 UTC, dngray approved these changes

2024-03-14 11:48 UTC, dngray commented
> Remove NextDNS until their privacy policy reflects their current defaults: https://discuss.privacyguides.net/t/nextdns-logging-is-opt-out-not-opt-in-as-stated-on-pgs-dns-resolvers-recommendations-page/17206/31

I think that's a bit hasty to be honest as I pointed out here: https://discuss.privacyguides.net/t/nextdns-logging-is-opt-out-not-opt-in-as-stated-on-pgs-dns-resolvers-recommendations-page/17206/32

2024-03-14 13:24 UTC, dngray requested changes

2024-03-14 13:24 UTC, dngray commented on docs/dns.md
> +| [**NextDNS**](https://nextdns.io) | [:octicons-link-external-24:](https://nextdns.io/privacy) | Cleartext <br> DoH/3 <br> DoT <br> DoQ | Optional[^5] | Optional | Based on personal configuration. |
> Remove NextDNS until their privacy policy reflects their current defaults: https://discuss.privacyguides.net/t/nextdns-logging-is-opt-out-not-opt-in-as-stated-on-pgs-dns-resolvers-recommendations-page/17206/31

I really want to avoid removing things and re-adding them. I've gotten in contact with them waiting on a reply. I don't think they're doing anything [nefarious](https://discuss.privacyguides.net/t/nextdns-logging-is-opt-out-not-opt-in-as-stated-on-pgs-dns-resolvers-recommendations-page/17206/32) as they don't sell the data to third parties.

2024-03-15 14:04 UTC, jonaharagon commented on docs/dns.md
> +| [**NextDNS**](https://nextdns.io) | [:octicons-link-external-24:](https://nextdns.io/privacy) | Cleartext <br> DoH/3 <br> DoT <br> DoQ | Optional[^5] | Optional | Based on personal configuration. |
Removing NextDNS from this table is intentional regardless of their privacy policy update btw. It isn't really a good public/free DNS provider no matter how you look at it, but the dns0.eu project (run by them) is, so dns0 is intended to replace them entirely here.

If we list NextDNS, it would go in the other section under Control D.

2024-03-16 07:25 UTC, dngray commented on docs/dns.md
> +| [**NextDNS**](https://nextdns.io) | [:octicons-link-external-24:](https://nextdns.io/privacy) | Cleartext <br> DoH/3 <br> DoT <br> DoQ | Optional[^5] | Optional | Based on personal configuration. |
It does seem the same people are involved, and making commits to NextDNS related repos.

In any case NextDNS is used by both Firefox and Chrome as an alternative DNS provider. The PP related concerns only related to the default for account based usage (not people directly using dns.nextdns.io etc.

I have reached out to them for comment though.

2024-03-16 07:25 UTC, dngray approved these changes

2024-03-30 09:55 UTC, merged