Update Safari settings for iOS 17
privacyguides/privacyguides.org pull request #2338
Opened 2023-11-20 18:31 UTC by kimg45

Changes proposed in this PR:

- Updated the settings for Safari to reflect changes in iOS 17

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-12-02 09:19 UTC, jonaharagon requested changes
Headers here should correspond w/ headers on the settings page, I think these suggestions all match.

2023-12-02 09:19 UTC, jonaharagon commented on docs/mobile-browsers.md
> +- [x] Enable **Require Face ID to Unlock Private Browsing**
```suggestion
##### Privacy & Security

- [x] Enable **Prevent Cross-Site Tracking**

    This enables WebKit's [Intelligent Tracking Protection](https://webkit.org/tracking-prevention/#intelligent-tracking-prevention-itp). The feature helps protect against unwanted tracking by using on-device machine learning to stop trackers. ITP protects against many common threats, but it does not block all tracking avenues because it is designed to not interfere with website usability.

- [x] Enable **Require Face ID to Unlock Private Browsing**

    This setting allows you to lock your private tabs behind biometrics/PIN when not in use.
```

2024-01-31 15:20 UTC, jonaharagon approved these changes

2024-02-10 15:02 UTC, dngray approved these changes

2024-02-10 15:14 UTC, dngray approved these changes

2024-02-10 15:14 UTC, merged