update!: Add Forward Email to email service providers
privacyguides/privacyguides.org pull request #2358
Opened 2023-12-24 06:03 UTC by titanism

**Disclosure:** We are the maintainers and owners of this business, which has been around since 2017 and is the only 100% open-source email service.

**Changes proposed in this PR:**

Hi there! :wave:  We have added our service [Forward Email](https://forwardemail.net) to the list of email service providers.  It supports both SMTP, IMAP, POP3, API, webhooks, catch-alls, regular expressions, aliases, and email forwarding.  We've been around since 2017 and support ~250,000 domain names right now, reject 30M+ spam emails daily, and deliver 1M+ emails daily.  To highlight a few users, we're used by The National Association for Amateur Radio (ARRL), Disney Ad Sales, Google's Flutter dev team, and Tufts University.

Unlike Proton Mail <sup><a href="https://old.reddit.com/r/ProtonMail/comments/b847n7/it_has_been_7_months_since_protonmail_said_we_are/ejysilb/">1</a></sup>, Skiff <sup><a href="https://old.reddit.com/r/Skiff/comments/10yn8a5/are_all_parts_of_skiff_opensource/j811jki/">2</a></sup>, and Tuta <sup><a href="https://old.reddit.com/r/tutanota/comments/10hghin/tutanota_opens_backend_server_side/j5in1wp/">3</a></sup>, we are actually [100% open-source](https://github.com/forwardemail) on GitHub (@forwardemail is our org).

Happy to make any changes to the docs as necessary for this PR to get merged!  Let us know if you have any questions or if we can clarify anything else further.  Our [FAQ](https://forwardemail.net/faq) is pretty extensive.

To keep your site Privacy Guides tidy and optimized, we also ran `svgo` to compress the `svg` icon files we added in this PR:

```sh
❯ svgo --multipass forward-email.svg -o forward-email.svg

forward-email.svg:
Done in 57 ms!
23.645 KiB - 58% = 9.932 KiB
```

P.S. Happy holidays and happy new year 🎉 

---

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work.
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2023-12-24 07:50 UTC, dngray commented
Looks like an interesting product, generally though we would request you open a thread [on our forums](https://discuss.privacyguides.net/c/privacy/showcase/13) for inclusion/discussion.

If you could do that, I'll mark this one as *needs discussion*.

2023-12-24 14:17 UTC, rollsicecream commented on docs/email.md
> +- [x] [Available in BitWarden](https://bitwarden.com/blog/add-privacy-and-security-using-email-aliases-with-bitwarden/) as of [2030.7.0 release](https://bitwarden.com/help/releasenotes/#2023-7-0)
Also, I did find a problem on the pull request.

2023-12-24 14:22 UTC, rollsicecream commented on docs/email.md
> +- [x] [Available in BitWarden](https://bitwarden.com/blog/add-privacy-and-security-using-email-aliases-with-bitwarden/) as of [2030.7.0 release](https://bitwarden.com/help/releasenotes/#2023-7-0)
I found a typo : It's not '2030.7.0' for the BW release but '2023.7.0'

2023-12-24 14:31 UTC, rollsicecream commented
https://github.com/privacyguides/privacyguides.org/pull/2358/commits/c505fa9173432391f4f4d06d89dd5e6b94a34c75#diff-9c19f9ef799b2ec64977c409149199e48d9fc26f01e9313366ed607f5fe54909R196

I found a typo : it shouldn't be version '2030.7.0' but '2023.7.0' of BW release

2023-12-24 14:49 UTC, rollsicecream commented on docs/email.md
> +- [x] [Available in BitWarden](https://bitwarden.com/blog/add-privacy-and-security-using-email-aliases-with-bitwarden/) as of [2030.7.0 release](https://bitwarden.com/help/releasenotes/#2023-7-0)
I found a typo : the BW release shouldn't be '2030.7.0' but it should be '2023.7.0'

2023-12-24 14:50 UTC, rollsicecream commented on docs/email.md
> +- [x] [Available in BitWarden](https://bitwarden.com/blog/add-privacy-and-security-using-email-aliases-with-bitwarden/) as of [2030.7.0 release](https://bitwarden.com/help/releasenotes/#2023-7-0)
I found a typo : the BW release shouldn't be '2030.7.0' but it should be '2023.7.0'

2023-12-25 00:27 UTC, dngray commented
@rollsicecream

Just let them do it when they are ready

@titanism, make sure to link this PR in your post and it will provide a backlink to the forum automatically.

2023-12-28 20:01 UTC, rollsicecream commented
Hello! I am not a team member of PrivacyGuides, so I cannot grant you the developer badge to let post in the forum. Sorry!

2024-04-10 11:34 UTC, freddy-m commented on docs/email.md
> +You can create unlimited custom domains, aliases, catch-alls, regex-based aliases, and more with Forward Email.
This reads too much like an advert.

2024-04-10 11:37 UTC, freddy-m commented on docs/email.md
> +Forward Email doesn't accept any cryptocurrencies as a result of [issues](https://github.com/forwardemail/forwardemail.net/commit/04c9f6f4c9c6279232e9fe18d7105ec83204f255) with BitPay and Coinbase Co
This is a bit too much of a listicle of payment methods, especially given we don't exactly [recommend](https://www.privacyguides.org/en/advanced/payments/#additional-considerations) them all. Something like this would suffice:

> 'However, they do accept PayPal, Visa, Mastercard and a variety of other payment methods.'

2024-04-10 13:42 UTC, dngray commented on docs/email.md
> +Forward Email doesn't accept any cryptocurrencies as a result of [issues](https://github.com/forwardemail/forwardemail.net/commit/04c9f6f4c9c6279232e9fe18d7105ec83204f255) with BitPay and Coinbase Co
Ideally Forwardmail would have a page where they do say what services they support and we'd link on the "variety of other methods" part.

2024-04-10 13:42 UTC, dngray commented on docs/email.md
> +You can create unlimited custom domains, aliases, catch-alls, regex-based aliases, and more with Forward Email.
We would delete the:

> , and more with Forward Email.

Part because it's obviously Forward Email it's their card.

2024-04-16 05:21 UTC, TechFanTheo commented on docs/email.md
> +Forward Email doesn't accept any cryptocurrencies as a result of [issues](https://github.com/forwardemail/forwardemail.net/commit/04c9f6f4c9c6279232e9fe18d7105ec83204f255) with BitPay and Coinbase Co
I believe the reason they don't accept crypto is irrelevant or not necessary. We should also see wheter they accept cash(they don't) and prepaid cards (they seem to do).

'Forward Mail do not accept cryptocurrency or cash payments. However, they do accept PayPal, Visa, Mastercard and a variety of other payment methods.'

2024-04-24 05:02 UTC, dngray commented on docs/email.md
> +Forward Email doesn't accept any cryptocurrencies as a result of [issues](https://github.com/forwardemail/forwardemail.net/commit/04c9f6f4c9c6279232e9fe18d7105ec83204f255) with BitPay and Coinbase Co
We wouldn't be marking this one as green though because the benefit of cryptocurrency like monero/cash is anonymous purchasing.

2024-07-27 04:30 UTC, jonaharagon commented
Neat! Good question. I'm going to put this next on my to-do list to review personally, but unfortunately I don't have any time until around the 4th of August to do so. Maybe dngray is able to get to it sooner, otherwise I should be able to that week or so :)

2024-08-07 20:10 UTC, MrSuddenJoy commented
Hi all, wojciechxtx here. As of now, Im against adding this service to PG.

2024-08-09 13:28 UTC, rollsicecream requested changes
Switching to HTML admonitions instead of the old syntax.

2024-08-09 13:28 UTC, rollsicecream commented on docs/email.md
> +        - [:octicons-terminal-16: Terminal](https://forwardemail.net/blog/open-source/terminal-email-clients)
```suggestion
### Forward Email

<div class="admonition recommendation" markdown>

![Forward Email logo](assets/img/email/forward-email.svg){ align=right }

**Forward Email** is 100% open-source and is focused on privacy, encryption, and security. They have been in operation since **2017**. Forward Email is based in the United States. All plans including the free plan include support for unlimited domains and aliases. Accounts start with 10 GB of pooled storage with their Enhanced Protection paid plan for $3/month.

[:octicons-home-16: Homepage](https://forwardemail.net){ .md-button .md-button--primary }

[:octicons-eye-16:](https://forwardemail.net/privacy){ .card-link title="Privacy Policy" }

[:octicons-info-16:](https://forwardemail.net/faq){ .card-link title=Documentation}

[:octicons-code-16:](https://github.com/forwardemail/forwardemail.net){ .card-link title="Source Code" }

<details class="downloads" markdown>
<summary>Downloads</summary>

- [:simple-apple: macOS](https://forwardemail.net/blog/open-source/apple-email-clients)
- [:simple-windows11: Windows](https://forwardemail.net/blog/open-source/windows-email-clients)
- [:material-apple-ios: iOS](https://forwardemail.net/blog/open-source/apple-i-os-email-clients)
- [:simple-android: Android](https://forwardemail.net/blog/open-source/android-email-clients)
- [:simple-linux: Linux](https://forwardemail.net/blog/open-source/linux-email-clients)
- [:simple-safari: Safari](https://forwardemail.net/blog/open-source/safari-email-clients)
- [:simple-googlechrome: Chrome](https://forwardemail.net/blog/open-source/google-chrome-email-clients)
- [:simple-firefoxbrowser: Firefox](https://forwardemail.net/blog/open-source/web-email-clients)
- [:octicons-browser-16: Web](https://forwardemail.net/en/blog/open-source/web-email-clients)
- [:octicons-terminal-16: Terminal](https://forwardemail.net/blog/open-source/terminal-email-clients)

</details>

</div>
```

2025-06-24 22:52 UTC, closed without merging

2025-06-24 23:07 UTC, titanism commented
# Privacy Guides Forum Analysis - Toxic Behavior Against Forward Email

## Post 1: Email Service Recommendations (Forward Email RFI x Re-evaluation of Existing Services)
URL: https://discuss.privacyguides.net/t/email-service-recommendations-forward-email-rfi-x-re-evaluation-of-existing-services/28576

### Key Findings:

#### Evidence of Toxic Behavior and Poor Moderation:
1. **Post Flagging and Censorship**: The main post from Forward Email founder was "flagged by the community and is temporarily hidden" - clear evidence of coordinated harassment
2. **Hostile Accusations**: User Catalyst2422 immediately attacked Forward Email with accusations of "PR rather than genuine engagement" instead of constructive discussion

#### Biased Treatment:
1. **Double Standards**: Forward Email is held to impossible standards while existing providers with clear flaws (closed source backends, backdoors, vendor lock-in) remain recommended
2. **Moving Goalposts**: Despite Forward Email addressing every concern and implementing requested features, they continue to be rejected
3. **Coordinated Opposition**: Multiple users appear to be working together to discredit Forward Email through flagging and negative comments

#### Forward Email's Professional Response:
1. **Detailed Technical Explanations**: Provided comprehensive responses about their enterprise customers with proper verification methods
2. **Transparency**: Offered source code and technical details that other providers don't provide
3. **Patience**: Continued to engage professionally despite hostile treatment

#### Evidence of Existing Provider Issues:
- Proton: Vendor lock-in, no standard protocols, closed source backend
- Tuta: No standard protocols, forced backdoor implementation under German law, closed source backend  
- Mailbox.org: No encryption, requires private key storage on servers, operates under same jurisdiction that forced Tuta backdoor




## Post 2: Forward Email (email provider) - Original Request Thread
URL: https://discuss.privacyguides.net/t/forward-email-email-provider/13370

### Key Findings:

#### Evidence of Vote Suppression:
1. **Zero Votes Displayed**: Despite 16.6k views and 422 likes, the thread shows "0 votes" - clear evidence of vote manipulation or suppression
2. **Thread Buried**: Original request was moved to "Tool Suggestions" category, effectively burying it from main visibility

#### Dismissive Treatment by Privacy Guides Team:
1. **ph00lt0 (Team Member)**: Immediately dismissed Forward Email saying "Does not support GPG as of yet. Not sure what would be the advantage of this tool. I feel like this is a saturated market."
2. **Moving Goalposts**: Even after Forward Email implemented GPG support, they continued to find new reasons for rejection
3. **Bias Against Innovation**: Dismissed Forward Email's unique features like individually encrypted SQLite mailboxes as unimportant

#### Forward Email's Superior Technical Offering:
1. **True Open Source**: Unlike Proton, Tuta, and others, Forward Email is 100% open source including backend
2. **Standard Protocols**: Supports SMTP, IMAP, POP3, CalDAV, CardDAV - unlike competitors who force proprietary solutions
3. **Massive Scale**: 550,000+ custom domains (more than Proton Mail and Fastmail combined)
4. **Enterprise Adoption**: Used by Netflix, Linux Foundation, PHP Foundation, major universities, government entities
5. **Advanced Security**: Individual encrypted SQLite mailboxes with ChaCha20-Poly1305 encryption
6. **No Vendor Lock-in**: Works with standard email clients, no proprietary bridge required

#### Double Standards in Evaluation:
1. **Existing Providers Get Free Pass**: Proton, Tuta, Mailbox.org remain recommended despite:
   - Closed source backends
   - Vendor lock-in
   - Forced backdoors (Tuta under German law)
   - No standard protocol support
   - Requiring private key storage on servers (Mailbox.org)
2. **Forward Email Held to Impossible Standards**: Despite meeting and exceeding all technical requirements, continuously rejected


## Post 3: What about Forward email? - Another Suppressed Thread
URL: https://discuss.privacyguides.net/t/what-about-forward-email/28293

### Key Findings:
1. **More Post Flagging**: Another post "flagged by the community and is temporarily hidden"
2. **Thread Closure**: Thread was closed and marked as duplicate, preventing discussion
3. **Hostile Comments**: securitybrahh attacked Forward Email's marketing as "confusingAF"
4. **Coordinated Suppression**: Pattern of flagging and closing any positive discussion about Forward Email

## Post 4: Forward Email (new features) - Long-term Harassment
URL: https://discuss.privacyguides.net/t/forward-email-new-features/24845/80

### Key Findings:
1. **Sustained Professional Updates**: Forward Email consistently shared technical updates, case studies, and improvements
2. **FUD Campaigns**: Users spreading "FUD" (Fear, Uncertainty, Doubt) with comments like "And here comes the FUD. I was going to try it, but I'm glad I've never even tried the service"
3. **Dismissive Team Responses**: ph00lt0 making dismissive comments even when Forward Email provided requested features
4. **Technical Achievements Ignored**: Despite releasing whitepapers, self-hosting capabilities, and enterprise case studies, Privacy Guides team remained hostile

## GitHub Pull Request #2358: Bureaucratic Gatekeeping and Bias
URL: https://github.com/privacyguides/privacyguides.org/pull/2358

### Key Findings:

#### Immediate Bureaucratic Obstacles:
1. **Gatekeeping**: dngray immediately labeled PR as "pr:missing discussion" requiring forum discussion first
2. **Moving Goalposts**: Even after Forward Email complied with every request, new obstacles were created
3. **Double Standards**: Skiff Mail PR #2353 was merged while Forward Email was rejected

#### Forward Email's Compliance Efforts:
1. **Rapid Feature Implementation**: Added OpenPGP/WKD support within days of request
2. **Technical Documentation**: Provided screenshots and detailed implementation evidence
3. **Professional Engagement**: Responded to every request promptly and professionally
4. **Future Roadmap**: Announced calendar, contacts, and newsletter support (and implemented them)

#### Evidence of Bias:
1. **Skiff Favoritism**: Skiff Mail was approved and merged despite having similar or fewer features
2. **Ignored Without Reason**: PR was ultimately ignored without clear technical justification
3. **Ignored Compliance**: Despite meeting all stated requirements, Forward Email was still rejected

## Summary of Toxic Behavior Patterns:

### Coordinated Harassment:
- Multiple posts flagged and hidden by "community" (likely coordinated group)
- Threads locked and closed to prevent positive discussion
- Vote suppression (0 votes despite massive engagement)

### Privacy Guides Team Misconduct:
- **ph00lt0**: Consistently dismissive, moving goalposts, unprofessional responses
- **dngray**: Bureaucratic gatekeeping, creating unnecessary obstacles
- **Catalyst2422**: Hostile accusations, spreading misinformation
- **securitybrahh**: Attacking Forward Email's marketing and credibility

### Systemic Bias:
- Inferior services (Proton, Tuta, Mailbox.org) remain recommended despite major flaws
- Superior service (Forward Email) rejected despite meeting all criteria
- Double standards in evaluation process
- Favoritism toward certain providers (Skiff approved, Forward Email rejected)

### Poor Forum Management:
- Allowing toxic users to dominate discussions
- Failing to moderate harassment and coordinated attacks
- Enabling vote manipulation and post suppression
- Team members participating in unprofessional behavior rather than moderating it

2025-06-25 01:15 UTC, I-I-IT commented
You seem to believe you have a right to be featured on Privacy Guides. You definitely do not. Companies being able to submit requests for inclusion is a privilege, not a right. It's up to the community to evaluate things, and not all products that meet the criteria are featured (see IronFox).

2025-06-25 08:52 UTC, eylenburg commented
So what exactly is blocking ForwardEmail from being featured? Don't they meet the criteria?

2025-06-25 09:20 UTC, ph00lt0 commented
> So what exactly is blocking ForwardEmail from being featured? Don't they meet the criteria?

see: https://discuss.privacyguides.net/t/forward-email-new-features/24845/95

The forum is the place to discuss things.