Clarify meaning of sentence in threat modeling guide
privacyguides/privacyguides.org pull request #2375
Opened 2024-01-27 14:37 UTC by feni-brian

Writing error : 
Missing some words in the modified paragraph where the sentence could end like this "...after you're done writing / with it."

Changes proposed in this PR:

- 

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2024-01-27 15:12 UTC, rollsicecream commented
Hmm. Why are all the boxes in the issue are unchecked here?

@feni-brian Please check all of those. Thanks!

2024-01-28 01:39 UTC, jonaharagon requested changes

2024-01-28 01:39 UTC, jonaharagon commented on docs/basics/threat-modeling.md
> +Depending on who your adversaries are, under some circumstances, this list might be something you want to destroy after you're done writing it.
This doesn't have the same meaning as the original text though. It's probably something more like:

```suggestion
Depending on who your adversaries are, this list might be something you want to destroy after you've finished developing your threat model.
```

2024-01-28 12:06 UTC, dngray approved these changes

2024-01-30 16:56 UTC, freddy-m approved these changes
LGTM

2024-02-01 05:36 UTC, jonaharagon approved these changes

2024-02-01 05:41 UTC, merged