Add Cromite to Mobile Browsers
privacyguides/privacyguides.org pull request #2381
Opened 2024-01-30 03:51 UTC by austinhuang0131

Changes proposed in this PR:

- add Cromite back. Logo (svg) is my own reproduction of the official logo (which is in png).

- [x] I have disclosed any relevant conflicts of interest in my post. (none other than being a user of it)
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

---

Criteria:

> Must support automatic updates.

yes

> Must receive engine updates in 0-1 days from upstream release.

0-1 days is a bit too strict for a one-person project. DivestOS claims it's "within a week," my personal observation is usually 1~3 days. Maybe we can ask the maintainer for this

> Any changes required to make the browser more privacy-respecting should not negatively impact user experience.

doesn't appear to

> Android browsers must use the Chromium engine.

yes

2024-01-30 07:24 UTC, dngray commented
Discussion thread for this https://discuss.privacyguides.net/t/cromite-bromite-fork/13274

2024-02-01 05:45 UTC, jonaharagon requested changes
> > Must receive engine updates in 0-1 days from upstream release.
> 
> 0-1 days is a bit too strict for a one-person project. [DivestOS claims it's "within a week,"](https://divestos.org/pages/browsers#chromium-based) my personal observation is usually 1 day, occasionally up to 3. Maybe we can ask the maintainer for this

we also have to change the criteria at the bottom of this page if we add a recommendation which doesn't match them.

2024-02-01 05:48 UTC, austinhuang0131 commented
or should we ask the dev about their release schedule? since referring to the chromium release blog is not the best idea since not every version is an exact match

2024-02-02 20:41 UTC, rollsicecream requested changes
Hmm. Seems like it doesn't uses HTML admonitions that should now be used on the website. Of course, there's no rush for this but we will need to convert this page later on to the new admonitions.

Also, speaking of this PR, seems like the "homepage button" for Cromite isn't here! There's cromite.org available but it redirects to the GitHub page. So, what we could do here is : Display the "homepage" button that contains cromite.org or the GH page. Something like this should be added : 

`[:octicons-home-16: Homepage](https://cromite.org){ .md-button .md-button--primary }`

2024-02-08 07:52 UTC, uazo commented
Sorry to intrude.
first of all, thank you for taking cromite into consideration, that pleases me.

but, if it is possible, i would ask you to be patient with your publication, until issue https://github.com/uazo/cromite/issues/710 is resolved.
to date I have some doubts about the legality of the distribution of my executables, regarding the support of aac and h264, due to the lack of a licence that it will not be possible for me to purchase it due to the high costs
Although I am not aware of how many installations my browser has, under 100,000 I can be comfortable, but a higher spread that might happen after your change. could bring me legal problems.

thank you for your consideration.
I remain at your disposal if you have any questions.

another thing, and please excuse me, I don't think those recommendations are good as default for cromite, but I don't want to sound cheeky and I might be wrong after all.

2024-02-11 04:58 UTC, jonaharagon commented on docs/mobile-browsers.md
> +- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**
what does this do and why should we do it?

2024-02-12 16:06 UTC, omicaeld commented on docs/mobile-browsers.md
> +- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**
Legacy Adblock is basically Bromite's ad blocking feature. Cromite implements Adblock Plus, but they keep both enabled by default.

If it should be a recommendation, I really don't know.

2024-02-12 16:07 UTC, austinhuang0131 commented on docs/mobile-browsers.md
> +- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**
since bromite is dead, the old bromite filter is no longer updated, so i thought to reduce call-home (sure it's github but eh)

2024-03-12 09:21 UTC, uazo commented
if you want I can tell you what I think the defaults should be, actually I plan to include them when I try to put cromite on the google store, which I will only do after I have written the privacy policy (which are not easy to write because, it is true, unlike other browsers, I do not send myself any data, ever, but the browser collects a lot locally).

2024-03-12 11:30 UTC, austinhuang0131 commented
the recommendations were copied from the ones used for Bromite which appears to be written some time (2+ years) ago

personally i don't really agree with them either but eh

2024-04-14 17:40 UTC, uazo commented
> Cromite [won’t 7](https://github.com/privacyguides/privacyguides.org/pull/2381#issuecomment-1933529540) be added until its maintainer allows us to.

I apologise, really! [that point has been closed](https://github.com/uazo/cromite/issues/710), the issue is only open for the linux version. I'm sorry I didn't tell you @jonaharagon

2024-04-14 17:47 UTC, jonaharagon commented
@uazo I wasn't sure if you wanted to wait until that was resolved for Linux as well, or if you didn't want us to share it until it was on mainstream platforms like Google Play.

But if you're happy with it then I'm happy with it 👍

2024-04-14 17:52 UTC, uazo commented
> I wasn't sure if you wanted to wait until that was resolved for Linux as well,

unfortunately I still don't know how to solve it, that's the problem. the only way is to force the user to recompile ffmpeg, but that's a solution I don't like.

>  or if you didn't want us to share it until it was on mainstream platforms like Google Play.

no, really, I forgot, sorry.

2024-04-14 17:53 UTC, austinhuang0131 commented
i still think the recommended measures should be reviewed (I just copied whatever's written for Bromite before), particularly regarding whether one should always use incognito

2024-04-14 18:12 UTC, uazo commented
> i still think the recommended measures should be reviewed

I agree, is one of the points I would like to address.

> particularly regarding whether one should always use incognito

do you mean the always incognito?
has its merits, but I don't think it is suitable for the average user, for whom the 'open external links in incognito' option is more suitable.
I think in particular that the default automatic wipe of data at start-up should be by default, and that it is essential to add the option to clean tabs links at startup, which is not there. regarding the latter i would like to include some other opensource project in cromite as a java library... 4 years from bromite were not enough :) but there is time, slowly I will do it all!

2024-04-14 18:32 UTC, uazo commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
> and some fingerprinting randomization.

some because I never detailed them, correct?
do you think it is right for me to do so, i.e. to detail what has been implemented and what I think is missing?
do you happen to have a list of those implemented in brave as a comparison?

2024-04-15 03:59 UTC, dngray commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
>  do you think it is right for me to do so, i.e. to detail what has been implemented and what I think is missing?

I would like that then I would directly link to it.

>  do you happen to have a list of those implemented in brave as a comparison?

There are various [blog articles](https://brave.com/privacy-updates/) that I think one would have to go through. [This](https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections) however might be more relevant as it discusses what is randomized and what is blocked.

2024-04-15 05:20 UTC, jonaharagon commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
Also I think has to do with testing at https://privacytests.org/android

2024-04-19 07:51 UTC, uazo commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
>  https://privacytests.org/android 

ah I didn't even know @arthuredelstein added cromite!

>  where it seems to cover similar things to Brave but less than Mull

let's talk about it if you want. the results of each test should be interpreted.
But I don't think cromite is necessarily better than others: what cromite lacks is testing (and spread :) and I am okay with the fact that there are excellent sites like that and the duck duck test site because I use them to check regressions.
too bad there is no site that compare the same browser on different devices, not so much on functionality, but on how it looks to the Web sites.
creepjs, my reference website, has something similar, but it is hidden very well in the code.

> Not that I think Cromite should go as far as Mull does necessarily, to be clear. 

Unfortunately, I don't know Mull so I can't answer that.

> I don't think Cromite intends to go as far as Firefox RFP?

I don't know that one either.
I can tell you that my goal is to make all devices as similar as possible, as Tor does.

2024-08-09 09:36 UTC, rollsicecream commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
Does Cromite also have a tracker blocker? If yes, this should be mentioned.

2024-08-09 18:56 UTC, austinhuang0131 commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
AdBlock Plus is mentioned, and you can certainly use it to block trackers, but there isn't really a specific thing that blocks trackers out of the box.

2024-08-18 15:58 UTC, redoomed1 commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
> I would like that then I would directly link to it [documentation on how Cromite's fingerprinting randomization techniques].

It looks like @uazo very recently updated the documentation for Cromite to neatly show a list of the anti-fingerprinting techniques Cromite employs.

https://github.com/uazo/cromite/blob/master/docs/FEATURES.md#anti-fingerprinting

2024-08-18 16:06 UTC, austinhuang0131 commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with privacy and security enhancements, built-in ad blocking, and some fingerprinting randomization. It is the continuation of Bromite.
Link is added.

2024-11-09 21:16 UTC, austinhuang0131 commented
Since the criteria is now just "Must receive engine updates from upstream releases quickly." it should now qualify

2024-11-12 01:11 UTC, jonaharagon commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with [privacy and security enhancements, built-in ad blocking, and some fingerprinting protection](https://github.com/uazo/cromite/blob/master/docs/FEATURES.md
```suggestion
**Cromite** is a Chromium-based browser with [privacy and security enhancements, built-in ad blocking, and some fingerprinting protections](https://github.com/uazo/cromite/blob/master/docs/FEATURES.md). It is a fork of the discontinued **Bromite** browser.
```

No need to link to dead projects.

2024-11-12 01:13 UTC, jonaharagon commented on docs/mobile-browsers.md
> +### Cromite (Android)
```suggestion
## Cromite (Android)
```

2024-11-12 01:14 UTC, jonaharagon commented on docs/mobile-browsers.md
> +##### Adblock Plus
```suggestion
### Recommended Configuration

These options can be found in :material-menu: → :gear: **Settings**.

#### HTTPS-Only Mode

- [x] Select **Always use secure connections** in **Privacy and security**

This prevents you from unintentionally connecting to a website in plain-text HTTP. The HTTP protocol is extremely uncommon nowadays, so this should have little to no impact on your day to day browsing.

#### Always-on Incognito Mode

The following are in **Privacy and security**.

- [x] Select **Always open links in incognito** in the **Always incognito mode** menu
- [x] Select **Close all open tabs on exit**
- [x] Select **Open external links in incognito**

#### Disable legacy adblock

- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**

#### Adblock Plus
```

correct header levels

2024-11-12 01:17 UTC, jonaharagon commented on docs/tools.md
> +- ![Cromite logo](assets/img/browsers/cromite.svg){ .lg .middle .twemoji } **Cromite**
```suggestion
- ![Cromite logo](assets/img/browsers/cromite.svg){ .lg .middle .twemoji } **Cromite (Android)**
```
match mull/safari listings

2024-11-12 01:17 UTC, jonaharagon commented on docs/tools.md
> +    **Cromite** is a Chromium fork with ad blocking and [privacy enhancements](https://github.com/uazo/cromite/blob/master/docs/FEATURES.md).
```suggestion
    **Cromite** is a Chromium-based Android browser with built-in ad-blocking and [privacy enhancements](https://github.com/uazo/cromite/blob/master/docs/FEATURES.md). It is a fork of the popular, now-discontinued Bromite browser.
```
more descriptive listing

2024-11-12 01:36 UTC, austinhuang0131 commented on docs/tools.md
> +- ![Cromite logo](assets/img/browsers/cromite.svg){ .lg .middle .twemoji } **Cromite**
Cromite isn't strictly Android-only though (even if it does mainly target Android)

2024-11-12 01:42 UTC, redoomed1 commented on docs/mobile-browsers.md
> +These options can be found in :material-menu: → :gear: **Settings**.
```suggestion
These options can be found in :material-menu: → :gear: **Settings** → **Privacy and security**.
```

2024-11-12 01:42 UTC, redoomed1 commented on docs/mobile-browsers.md
> +#### HTTPS-Only Mode
```suggestion
#### Security
```

2024-11-12 01:42 UTC, redoomed1 commented on docs/mobile-browsers.md
> +- [x] Select **Always use secure connections** in **Privacy and security**
```suggestion
- [x] Select **Always use secure connections**
```

2024-11-12 01:42 UTC, redoomed1 commented on docs/mobile-browsers.md
> +#### Disable legacy adblock
```suggestion
#### Legacy Adblock settings

These options can be found in :material-menu: → :gear: **Settings** → **Legacy Adblock settings**.
```

2024-11-12 01:42 UTC, redoomed1 commented on docs/mobile-browsers.md
> +- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**
```suggestion
- [ ] Check **Autoupdate disabled**

This setting disables update checks for the unmaintained Bromite adblock filter.
```

2024-11-12 01:42 UTC, redoomed1 commented on docs/mobile-browsers.md
> +- [x] Select **Enable anti-circumvention and snippets**
To be consistent with recommendations for other browsers that allow for adding more filter lists (e.g., [Brave](https://www.privacyguides.org/en/mobile-browsers/#brave-shields-global-defaults)), I'm not sure if this should be included.

2024-11-12 01:47 UTC, redoomed1 commented on docs/tools.md
> +- ![Cromite logo](assets/img/browsers/cromite.svg){ .lg .middle .twemoji } **Cromite**
In the context of the Mobile Browsers page, though, it is just for Android (like Mull).

2024-11-12 01:54 UTC, jonaharagon commented on docs/mobile-browsers.md
> +- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**
```suggestion
- [x] Check **Autoupdate disabled**
This setting disables update checks for the unmaintained Bromite adblock filter.
```
if it's checked it should be [x] right?

2024-11-12 01:56 UTC, austinhuang0131 commented on docs/mobile-browsers.md
> +- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**
It becomes "autoupdate disabled" with off switch, the opposite is "autoupdate enabled" with on switch, so I suggest keeping it as-is

2024-11-12 02:01 UTC, redoomed1 commented on docs/mobile-browsers.md
> +- [ ] Uncheck **autoupdate** in **Legacy Adblock settings**
Ah I just checked and the setting description does change when toggled.
```suggestion
- [ ] Unselect the autoupdate setting
```
This wording should avoid the setting-specific text.

2024-11-12 02:32 UTC, austinhuang0131 commented on docs/mobile-browsers.md
> +- [x] Select **Enable anti-circumvention and snippets**
You can just

```suggestion
#### Adblock Plus

Cromite contains a customized version of Adblock Plus. In **Adblock Plus settings**,

- [x] Select appropriate options in **Filter lists**
- [x] Select **Enable anti-circumvention and snippets**
```

Because the problem is that Cromite does not select any filters by default

2024-11-12 03:01 UTC, austinhuang0131 commented on docs/mobile-browsers.md
> +- [x] Select **Enable anti-circumvention and snippets**
o rly maybe i forgor

then i guess you can remove the entire section

2024-11-12 03:03 UTC, redoomed1 commented on docs/mobile-browsers.md
> +- [x] Select **Enable anti-circumvention and snippets**
I think we can keep the section and add the typical warnings about performance hits and potential increased attack surface.

2024-11-12 03:40 UTC, redoomed1 commented on docs/mobile-browsers.md
> +- [x] Select **Enable anti-circumvention and snippets**
How about this?
```suggestion
#### Adblock Plus settings

Cromite contains a customized version of Adblock Plus with EasyList enabled by default, as well as options to select more filter lists within the **FIlter lists** menu.

Using extra lists will make you stand out from other Cromite users and may also increase attack surface if a malicious rule is added to one of the lists you use.

- [x] (Optional) Select **Enable anti-circumvention and snippets**

This setting adds an additional Adblock Plus list that may increase the effectiveness of Cromite's content blocking, but the same warning above applies here as well.
```

2024-11-12 05:10 UTC, redoomed1 commented on docs/mobile-browsers.md
> +**Cromite** is a Chromium-based browser with [privacy and security enhancements, built-in ad blocking, and some fingerprinting protections](https://github.com/uazo/cromite/blob/master/docs/FEATURES.m
```suggestion
**Cromite** is a Chromium-based browser with built-in ad blocking, fingerprinting protections, and other [privacy and security enhancements](https://github.com/uazo/cromite/blob/master/docs/FEATURES.md). It is a fork of the discontinued **Bromite** browser.
```
Changed this part so that there isn't an excessively long hyperlink

2024-11-12 05:10 UTC, redoomed1 commented on docs/mobile-browsers.md
> +The following are in **Privacy and security**.
```suggestion
#### Incognito Mode
```

2024-11-12 05:43 UTC, jonaharagon approved these changes

2024-11-12 19:42 UTC, austinhuang0131 commented on docs/mobile-browsers.md
> +- [x] Select **Open external links in incognito**
opening external links in incognito could be useful to restore WebView-like behaviour before Chrome custom tabs, but it is not strictly necessary either. also see dev response https://github.com/privacyguides/privacyguides.org/pull/2381#issuecomment-2054138460

```suggestion
#### Always-on Incognito Mode

The following are in **Privacy and security**.

- [x] Select **Close all open tabs on exit**
- [x] Select **Open external links in incognito**
```

2024-11-12 20:48 UTC, redoomed1 commented on docs/mobile-browsers.md
> +#### Security
```suggestion
#### Browsing data

- [x] Select **Close all open tabs on exit**

#### Incognito mode

- [x] Select **Open external links in incognito**

#### Security
```

2024-11-12 20:48 UTC, redoomed1 commented on docs/mobile-browsers.md
> +
```suggestion
```

2024-11-12 20:48 UTC, redoomed1 commented on docs/mobile-browsers.md
> +
```suggestion

#### Legacy Adblock settings

These options can be found in :material-menu: → :gear: **Settings** → **Legacy Adblock settings**.

- [ ] Uncheck the autoupdate setting

This disables update checks for the unmaintained Bromite adblock filter.

```

2024-11-12 20:49 UTC, redoomed1 commented on docs/mobile-browsers.md
> +- [x] Select **Open external links in incognito**
Added recommendations for both settings: https://github.com/privacyguides/privacyguides.org/pull/2381#discussion_r1838747671

2024-11-12 20:49 UTC, redoomed1 commented on docs/mobile-browsers.md
> +
Rearranging sections in the order they appear in Cromite's settings

2024-11-12 20:58 UTC, redoomed1 commented on docs/mobile-browsers.md
> +Cromite contains a customized version of Adblock Plus with EasyList enabled by default, as well as options to select more filter lists within the **FIlter lists** menu.
```suggestion
These options can be found in :material-menu: → :gear: **Settings** → **Adblock Plus settings**.

Cromite contains a customized version of Adblock Plus with EasyList enabled by default, as well as options to select more filter lists within the **FIlter lists** menu.
```

2024-11-12 21:03 UTC, redoomed1 commented on docs/mobile-browsers.md
> +
```suggestion
```

2024-11-14 19:37 UTC, merged