Add Peergos in Cloud Storage section
privacyguides/privacyguides.org pull request #2429
Opened 2024-03-08 12:30 UTC by rollsicecream

Changes proposed in this PR:

- Add Peergos in the Cloud Storage and Productivity section

https://discuss.privacyguides.net/t/peergos-private-storage-sharing-social-media-and-application-platform/11825

@ianopolous If you want something to be changed, don't hesitate to reach me out!

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/en/code_of_conduct/).

2024-03-08 13:29 UTC, rollsicecream commented
@dngray Should we also add it to the "Productivity" section?

2024-03-09 19:03 UTC, rollsicecream commented
Just fixed a merge conflict.

2024-03-09 19:28 UTC, ianopolous commented
Looks great to me! Thank you @rollsicecream

2024-03-13 14:52 UTC, dngray commented
> @dngray It can now be merged.

Not sure what you changed, i fixed merge conflict and rebased on master/replaced svg

There was no copy in cloud.md

2024-03-13 14:57 UTC, rollsicecream commented
> Did you forget to pull before making changes?

Yeah.... You're right. I should have [better Git habits](https://www.privacyguides.org/en/meta/git-recommendations) lol

2024-03-16 11:12 UTC, dngray approved these changes

2024-03-23 17:19 UTC, rollsicecream commented
Any updates?

2024-03-28 07:00 UTC, jonaharagon requested changes
doesn't meet https://www.privacyguides.org/en/productivity/#criteria

2024-03-28 18:17 UTC, jonaharagon requested changes
Thanks @rollsicecream! Just want to collect thoughts on a couple things below before merging.

2024-03-28 18:17 UTC, jonaharagon commented on docs/cloud.md
> +</div>
```suggestion
Peergos is primarily a web app, but you can self-host the server either as a local cache for your remote Peergos account, or as a standalone storage server negating the need to register for a remote account and subscription. The Peergos server is a `.jar` file, which means the Java 17+ Runtime Environment ([OpenJDK download](https://www.azul.com/downloads/)) should be installed on your machine to get it working.

Running a local version of Peergos alongside a registered account on their paid, hosted service allows you to access your Peergos storage without any reliance on DNS or TLS certificate authorities, and keep a copy of your data backed up to their cloud. The user experience should be the same whether you run their desktop server or just use their hosted web interface.
```

- Peergos requires Java >= 17, so the JRE 8 download probably wouldn't work here, and I'd rather not use Oracle's Java anyways.
- I want to include info on why you might run this
- Removing note about document collaboration since none of the services on this page support it

Not merging this suggestion immediately because I want to ask: @ianopolous have you tested this with any particular OpenJDK distro, and/or do you have a preference? I tend to use Zulu (which is why I'm linking to it) which _seems_ to work fine, and I'm not sure if it makes a difference at all. If it doesn't matter we can stick with this.

2024-03-28 18:17 UTC, jonaharagon commented on docs/cloud.md
> +Peergos has made an [audit](https://cure53.de/pentest-report_peergos.pdf) in September 2019 and the results were pretty good. All found issues were fixed.
```suggestion
Peergos was [audited](https://cure53.de/pentest-report_peergos.pdf) by Cure53 in September 2019, and all found issues were subsequently fixed.
```

2024-03-28 18:17 UTC, jonaharagon commented on docs/cloud.md
> +- [:simple-linux: Linux](https://github.com/Peergos/web-ui/releases)
Kind of curious whether we think a single `:material-language-java: Java` download link makes more sense for Java applications like this, since they are inherently cross-platform, and they require a separate runtime environment, so it's almost its own platform itself. Thoughts?

- Pro: Readers can immediately tell that something will require a separate Java install and won't just run natively.
- Con: Not sure if everyone will read "Java" and understand it will probably work regardless of OS. Is that common knowledge among average computer-using adults? Feels like it might be because of e.g. games like Minecraft, but idk.

2024-03-28 18:47 UTC, ianopolous commented on docs/cloud.md
> +</div>
We normally use openjdk (e.g via https://adoptium.net/), but it is fine with any JVM. 

We are close to having static native builds working for windows/mac/linux which would remove the need for a JVM. But we can revisit that once they are working.

2024-03-28 18:50 UTC, ianopolous commented on docs/cloud.md
> +- [:simple-linux: Linux](https://github.com/Peergos/web-ui/releases)
We have previously had static native builds for each platform there as well, and we hope to return to that in either the next release or the one after. I think requiring most people to install java is too much.

2024-03-28 20:57 UTC, jonaharagon approved these changes
@dngray lmk what you think about https://github.com/privacyguides/privacyguides.org/pull/2429#discussion_r1543422820 and if we don't want to change anything I'm good to merge this.

2024-04-02 12:38 UTC, dngray commented
> @dngray lmk what you think about [#2429 (comment)](https://github.com/privacyguides/privacyguides.org/pull/2429#discussion_r1543422820) and if we don't want to change anything I'm good to merge this.

If they're going to return next build them I'm happy to leave as is.

2024-04-02 13:11 UTC, dngray commented
> I think there might be a dangling link to productivity in tools.md?

Yes giving this another look over now.

2024-04-02 14:14 UTC, merged