Revamp full disk encryption section
privacyguides/privacyguides.org pull request #2437
Opened 2024-03-15 04:07 UTC by typejade

Changes proposed in this PR:

todo

---
- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work.
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-03-15 05:26 UTC, typejade commented on docs/encryption.md
> +While BitLocker is not officially supported on Windows Home, it can be enabled on Home editions with a few extra steps.
Good question, I did see that issue. To me it read as if it worked except they accidentally did the process on a non-boot drive since their drive letters were weird.

Which is why I added:
```diff
+ This guide assumes the drive letter of your operating system drive is "C". If it is not, replace `c:` with the correct drive letter in the following commands.
```

Though maybe I'm interpreting what they're saying wrong.

2024-03-15 14:41 UTC, dngray commented on docs/encryption.md
> +While BitLocker is not officially supported on Windows Home, it can be enabled on Home editions with a few extra steps.
There was also a thread https://discuss.privacyguides.net/t/enabling-bitlocker-on-the-windows-11-home-edition/13303/ about it. could just check in a VM

2024-03-15 19:21 UTC, typejade commented on docs/encryption.md
> +While BitLocker is not officially supported on Windows Home, it can be enabled on Home editions with a few extra steps.
I went through the guide on a VM and it worked for me. I updated the instructions based on what I experienced (i.e., saving the recovery key to a .txt file didn't work for me).

![Device encryption enabled in a Windows 11 Home virtual machine.](https://github.com/privacyguides/privacyguides.org/assets/140852203/b9e3c454-cb7e-4d36-b5e0-26d423168fac)

2024-03-16 11:02 UTC, rollsicecream commented on docs/encryption.md
> +Built into Windows and a proprietary solution, **BitLocker** provides full volume encryption to protect data at rest. BitLocker [leverages](https://learn.microsoft.com/en-us/windows/security/hardware
```suggestion
**BitLocker**, a proprietary solution built into Windows, provides full volume encryption to protect data at rest. BitLocker [leverages](https://learn.microsoft.com/en-us/windows/security/hardware-security/tpm/how-windows-uses-the-tpm#tpm-overview) the Trusted Platform Module (TPM) for hardware-based security, provided one is present in your device. BitLocker is only officially supported on Pro, Enterprise and Education editions of Windows.

2024-03-16 15:24 UTC, rollsicecream commented on docs/encryption.md
> +Built into Windows and a proprietary solution, **BitLocker** provides full volume encryption to protect data at rest. BitLocker [leverages](https://learn.microsoft.com/en-us/windows/security/hardware
This will be a better wording.

2024-03-16 17:39 UTC, typejade commented on docs/encryption.md
> +Built into Windows and a proprietary solution, **BitLocker** provides full volume encryption to protect data at rest. BitLocker [leverages](https://learn.microsoft.com/en-us/windows/security/hardware
Thanks, that is more consistent with the rest of the site.

2024-03-16 17:45 UTC, rollsicecream commented on docs/encryption.md
> +Built into Windows and a proprietary solution, **BitLocker** provides full volume encryption to protect data at rest. BitLocker [leverages](https://learn.microsoft.com/en-us/windows/security/hardware
Hmm. But that's doesn't seem what I asked about. Please follow my 'suggested change'

2024-03-31 13:31 UTC, SkewedZeppelin commented
maybe worth nothing: latest cryptsetup 2.7.0 adds SED support: https://mirrors.edge.kernel.org/pub/linux/utils/cryptsetup/v2.7/v2.7.0-ReleaseNotes

so it can automatically layer both hw+sw encryption without any extra steps, might as well use it if you have it

2024-04-01 04:07 UTC, typejade commented
> maybe worth nothing: latest cryptsetup 2.7.0 adds SED support

Thanks for sharing, though I'm not knowledgeable enough on LUKS/Linux to feel comfortable writing about that. If you feel it's good information to add then I would encourage you to add on to this PR @SkewedZeppelin

2024-04-01 17:12 UTC, dngray commented
> I assume this will eventually be moved to https://github.com/privacyguides/privacyguides.org/pull/1659, but it's important so might as well get the info out now

Yes it will. We consolodating that PR with https://github.com/privacyguides/privacyguides.org/pull/2452 and then I intend to add original author as co-author. I want to get that one merged as they've worked quite hard on it.

Initially the plan was to wait until we did research on LGPO policies that would make relevant privacy improvements. I've decided against that for the time being because it will require considerable resources and can always be added later by someone with specific knowledge in that area.

The intention is then to merge this PR after the Windows one though. I think that makes logical sense to do it in that order so we don't have to move things around later and annoy the translators.

2024-07-13 13:02 UTC, rollsicecream requested changes
Here are some little things to fix:

2024-07-13 13:02 UTC, rollsicecream commented on docs/encryption.md
> +**FileVault**, a proprietary solution integrated into macOS, offers on-the-fly volume encryption to secure all data at rest. On Macs with Apple silicon or a T2 Security Chip, FileVault [leverages](ht
```suggestion
**FileVault**, a proprietary solution integrated into macOS, offers on-the-fly volume encryption to secure all data at rest. On Macs with Apple Silicon or a T2 Security Chip, FileVault [leverages](https://support.apple.com/guide/security/volume-encryption-with-filevault-sec4c6dc1b6e/web) the [Secure Enclave](https://support.apple.com/en-us/guide/security/sec59b0b31ff/web) and its hardware security capabilities.
```

2024-07-15 03:34 UTC, in-the-trees commented on docs/encryption.md
> +Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cry
Perhaps mentioning it in a shorter fashion would be better since the sentence is already on the edge of being verbose. Maybe "(e.g., a TPM)"

2024-07-15 03:35 UTC, in-the-trees commented on docs/encryption.md
> +**FileVault**, a proprietary solution integrated into macOS, offers on-the-fly volume encryption to secure all data at rest. On Macs with Apple silicon or a T2 Security Chip, FileVault [leverages](ht
Apple doesn't capitalize "silicon" in their own documentation

2024-07-15 08:59 UTC, rollsicecream commented on docs/encryption.md
> +Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cry
Here are the corrected changes with your suggestion: 

```suggestion
Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cryptoprocessor](https://en.wikipedia.org/wiki/Secure_cryptoprocessor) (e.g., a [TPM](https://en.wikipedia.org/wiki/Trusted_Platform_Module)). Therefore, we recommend using the built-in FDE solutions for your operating system. For external drives, however, we still recommend open-source tools for additional flexibility and to avoid vendor lock-in.
```

2024-07-15 09:02 UTC, rollsicecream commented on docs/encryption.md
> +**FileVault**, a proprietary solution integrated into macOS, offers on-the-fly volume encryption to secure all data at rest. On Macs with Apple silicon or a T2 Security Chip, FileVault [leverages](ht
```suggestion
**FileVault**, a proprietary solution integrated into macOS, offers on-the-fly volume encryption to secure all data at rest. On Macs with Apple silicon or a T2 Security Chip, FileVault [leverages](https://support.apple.com/guide/security/volume-encryption-with-filevault-sec4c6dc1b6e/web) the [Secure Enclave](https://support.apple.com/en-us/guide/security/sec59b0b31ff/web) and its hardware security capabilities.
```

2024-07-26 18:17 UTC, IDON-TEXIST commented on docs/encryption.md
> +While BitLocker is not officially supported on Windows Home, it can be enabled on Home editions with a few extra steps.
or we could just point home users to MAS.

2024-07-26 18:18 UTC, IDON-TEXIST commented
I'm not sure whether the comments I've made create notifications, so check [this](https://github.com/privacyguides/privacyguides.org/pull/2437/files#r1693003621).

2024-07-27 21:20 UTC, in-the-trees commented on docs/encryption.md
> +While BitLocker is not officially supported on Windows Home, it can be enabled on Home editions with a few extra steps.
> The guide worked, my problem was that the drive letters were _switched_ in the troubleshooter command prompt. I think the addition should explicitly mention the possibility of this.

Where should this be mentioned? It's been a few months since I went through the guide, so I'm admittedly not too familiar with it anymore.

> or we could just point home users to MAS.

MAS works well — there's no denying that. Though I think it's more of a iykyk thing rather than something to be recommend.

2024-07-28 04:32 UTC, IDON-TEXIST requested changes

2024-07-28 04:32 UTC, IDON-TEXIST commented on docs/encryption.md
> +While BitLocker is not officially supported on Windows Home, it can be enabled on Home editions with a few extra steps.
> MAS works well — there's no denying that. Though I think it's more of a iykyk thing rather than something to be recommend.

Is what we're suggesting any less illegal?

2024-07-28 04:32 UTC, IDON-TEXIST commented on docs/encryption.md
> +- This guide also assumes your operating system drive letter is "**C**". If it is not, you may need to replace `c:` with the correct drive letter.
```suggestion
+ If your computer has multiple drives, you will need to take a few extra steps to determine the correct drive letter, because it is **not** necessarily the same between when your operating system is booted and while in the recovery environment (see step 3 below).
+ <details class="info" markdown>
+ <summary>Determining the correct drive letter</summary>
+ 1. Run, and accept the elevation prompt:
+      ```powershell
+      diskpart
+      ```
+ 2. In the new window that appears, run:
+      ```powershell
+      list volume
+      ```
+      Remember the volume number your operating system boots on (check the "ltr" column).
+ 3. Follow the below instructions until and including step 3.
+ 4. Run the commands in the above steps 1 and 2 again.
+ 5. For steps 4-7 in the below instructions, use the drive letter that corresponds with the aforementioned volume number.
+ </details>
```

2024-07-30 02:00 UTC, in-the-trees commented on docs/encryption.md
> +- This guide also assumes your operating system drive letter is "**C**". If it is not, you may need to replace `c:` with the correct drive letter.
Thanks for writing out these instructions

2024-07-30 15:34 UTC, redoomed1 reviewed
Thanks for the improvements on the BitLocker guide!

2024-07-30 15:34 UTC, redoomed1 commented on docs/encryption.md
> +Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cry
For the last sentence in the introductory paragraph, I'm not sure source availability is _that_ relevant here. I think that cross-/multi-platform might be more apt with respect to the considerations mentioned ("for additional flexibility and to avoid vendor lock-in").
```suggestion
Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cryptoprocessor](https://en.wikipedia.org/wiki/Secure_cryptoprocessor) (e.g., a [TPM](https://en.wikipedia.org/wiki/Trusted_Platform_Module)). Therefore, we recommend using the built-in FDE solutions for your operating system. For external drives, however, we still recommend [cross-platform tools](#multi-platform) for additional flexibility and to avoid vendor lock-in.
```
There's already a section for cross-platform tools on this recommendation page anyway, so I embedded an internal link.

2024-07-30 15:39 UTC, redoomed1 commented on docs/encryption.md
> +Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cry
For the last sentence in the introductory paragraph, I'm not sure source availability is _that_ relevant here. I think that cross-/multi-platform might be more apt with respect to the considerations mentioned ("for additional flexibility and to avoid vendor lock-in").
```suggestion
Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cryptoprocessor](https://en.wikipedia.org/wiki/Secure_cryptoprocessor) (e.g., a [TPM](https://en.wikipedia.org/wiki/Trusted_Platform_Module)). Therefore, we recommend using the built-in FDE solutions for your operating system. For external drives, however, we still recommend [cross-platform tools](#multi-platform) for additional flexibility and to avoid vendor lock-in.
```
There's already a section for cross-platform tools on this recommendation page anyway, so I embedded an internal link.

2024-07-31 02:45 UTC, IDON-TEXIST commented
I think it might make more sense to move the group policy stuff to this page. We wouldn't want readers to gloss over it and then decide to unencrypt and reencrypt their drives because they realize they want AES-256.

2024-08-05 16:29 UTC, redoomed1 commented
> Those policies don't make much sense to enable unless you're using or planning to use Bitlocker, anyway.

On further reflection, I agree.

On that note, I recently reviewed the large Windows PR (#1659) and saw that there was a dedicated section for enabling BitLocker security policies. If you can spare the time and if it's not too much trouble, could you please go over this section and see if there's anything worth adding to the BitLocker instructions in this PR?

Link: https://1659--glowing-salamander-8d7127.netlify.app/en/os/windows/hardening/#security-policies-for-bitlocker

Tagging @in-the-trees since you're the author of this PR and @IDON-TEXIST since you brought forth the idea of bringing all the BitLocker policy to this page (and since both of you contributed substantially to the work to update this section of the site)

2024-08-08 23:21 UTC, rollsicecream requested changes
Some things to fix.

2024-08-08 23:21 UTC, rollsicecream commented on docs/encryption.md
> +In addition to the TPM, BitLocker can lock the normal startup process until the user supplies a pin or inserts a USB flash drive containing a startup key. Preboot authentication is designed to preven
```suggestion
In addition to the TPM, BitLocker can lock the normal startup process until the user supplies a pin or inserts a USB flash drive containing a startup key. Pre-boot authentication is designed to prevent the encryption keys from being loaded to system memory without the trusted user supplying another authentication factor. This feature helps mitigate direct memory access and memory remanence attacks.
```
https://en.m.wikipedia.org/wiki/Pre-boot_authentication

2024-08-08 23:21 UTC, rollsicecream commented on docs/encryption.md
> +2. Allow for preboot authentication:
```suggestion
2. Allow for pre-boot authentication:
```
https://en.m.wikipedia.org/wiki/Pre-boot_authentication

2024-08-08 23:21 UTC, rollsicecream commented on docs/encryption.md
> +    2. Check whether "**TPM and Pin**" is listed under "**Key Protectors**."
```suggestion
    2. Check whether "**TPM and PIN**" is listed under "**Key Protectors**."
```
PIN: https://en.m.wikipedia.org/wiki/Personal_identification_number

2024-08-08 23:21 UTC, rollsicecream commented on docs/encryption.md
> +While BitLocker is not officially supported on Windows Home, it can be enabled on Home editions with a few extra steps.
```suggestion
While BitLocker is not officially supported on Windows Home, it can be enabled with a few extra steps.
```
I removed that part since it's just a repetition on the same sentence.

2024-08-08 23:21 UTC, rollsicecream commented on docs/encryption.md
> +- You may need to [disable the non-Bitlocker "Device encryption" functionality](https://discuss.privacyguides.net/t/enabling-bitlocker-on-the-windows-11-home-edition/13303/5) if it is enabled.
```suggestion
- You may need to [disable the non-BitLocker "Device encryption" functionality](https://discuss.privacyguides.net/t/enabling-bitlocker-on-the-windows-11-home-edition/13303/5) if it is enabled.
```
Just added a capital L to "BitLocker" to stay consistant on this page. Also, Microsoft writes their product name with that capital L.

2024-08-09 12:44 UTC, rollsicecream requested changes
Other things to fix...

2024-08-09 12:44 UTC, rollsicecream commented on docs/encryption.md
> +In addition to the TPM, BitLocker can lock the normal startup process until the user supplies a pin or inserts a USB flash drive containing a startup key. Pre-boot authentication is designed to preve
```suggestion
In addition to the TPM, BitLocker can lock the normal startup process until the user supplies a PIN or inserts a USB flash drive containing a startup key. Pre-boot authentication is designed to prevent the encryption keys from being loaded to system memory without the trusted user supplying another authentication factor. This feature helps mitigate direct memory access and memory remanence attacks.
```

2024-08-09 12:44 UTC, rollsicecream commented on docs/encryption.md
> +<summary>Enabling preboot authentication</summary>
```suggestion
<summary>Enabling pre-boot authentication</summary>
```

2024-08-09 12:44 UTC, rollsicecream commented on docs/encryption.md
> +- To remove the preboot pin:
```suggestion
- To remove the pre-boot pin:
```

2024-09-21 06:29 UTC, kimg45 requested changes

2024-09-21 06:29 UTC, kimg45 commented on docs/encryption.md
> +Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cry
Nothing about FDE inherently has anything to do with using a TPM, the original point was to use built-in solutions instead of third party ones since those more likely take advantage of hardware security features. Also I don't like how this implies that encrypting the operating system necessarily makes it more secure, this isn't always the case especially when the operating system is protected by a good secure boot or verified boot.

2024-09-21 06:29 UTC, kimg45 commented on docs/encryption.md
> +Note the terms full *disk* encryption and full *volume* encryption are often used interchangeably.
These aren't the same though. Full disk implies the entire disk is encrypted and Full Volume encryption just means a volume on the disk is encrypted. I think we should probably avoid using either of these terms and just call it encryption.

2024-09-21 06:29 UTC, kimg45 commented on theme/assets/img/encryption-software/filevault.png
The one you deleted still shows up in [Apple's marketing materials](https://www.apple.com/macos/security/) so I think we can leave it.

2024-10-28 19:35 UTC, friadev requested changes

2024-10-28 19:35 UTC, friadev commented on docs/encryption.md
> +Full disk encryption (FDE) is a comprehensive data encryption solution, encompassing the operating system and system files. FDE principally leverages hardware security features, such as a [secure cry
```suggestion
Built-in OS encryption solutions generally leverage hardware security features, such as a [secure cryptoprocessor](https://en.wikipedia.org/wiki/Secure_cryptoprocessor). Therefore, we recommend using the built-in encryption solutions for your operating system. For cross-platform encryption, we still recommend [cross-platform tools](#multi-platform) for additional flexibility and to avoid vendor lock-in.
```

2024-10-28 19:35 UTC, friadev commented on docs/encryption.md
>  ## OS Full Disk Encryption
```suggestion
## OS Encryption
```

2024-10-28 19:35 UTC, friadev commented on docs/encryption.md
> +To learn more about BitLocker and TPM, see "[Understanding BitLocker TPM Protection](https://blog.elcomsoft.com/2021/01/understanding-BitLocker-tpm-protection)" by ElcomSoft, a forensics company.
```suggestion
```

2024-11-07 01:41 UTC, vandorsx commented
Thanks to those who provided feedback and changes to this PR. I’m closing it as the scope of these changes is too large, making it difficult to review and merge. If anyone more active in contributing to Privacy Guides would like to carry forward parts of these changes in a new PR, feel free to do so.

2024-11-07 01:41 UTC, closed without merging