Remove Brave's Flatpak footnote
privacyguides/privacyguides.org pull request #2455
Opened 2024-03-29 20:32 UTC by rollsicecream

Changes proposed in this PR:

- Remove Brave's Flatpak footnote as it is now verified/endorsed by Brave themselves: https://flathub.org/apps/com.brave.Browser

[Related forum post](https://discuss.privacyguides.net/t/revisit-footnote-next-to-braves-linux-download-link/17575)

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-03-29 20:38 UTC, jonaharagon approved these changes

2024-03-29 20:52 UTC, redoomed1 requested changes

2024-03-29 20:52 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [:simple-linux: Linux](https://brave.com/linux)
```suggestion
- [:simple-linux: Linux](https://brave.com/linux)
- [:simple-flathub: Flathub](https://flathub.org/apps/com.brave.Browser)
```

2024-03-29 20:52 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [:simple-linux: Linux](https://brave.com/linux)
https://discuss.privacyguides.net/t/revisit-footnote-next-to-braves-linux-download-link/17575/2

2024-03-29 20:53 UTC, rollsicecream commented on docs/desktop-browsers.md
> +- [:simple-linux: Linux](https://brave.com/linux)
Oh, just forgot about that. Thanks :+1:

2024-03-30 05:08 UTC, dngray approved these changes

2024-03-30 05:09 UTC, merged