Update Password Management page
privacyguides/privacyguides.org pull request #2459
Opened 2024-03-30 22:08 UTC by rollsicecream

Changes proposed in this PR:

- Update Password Management page: 

   - Update Recommendations cards of Bitwarden and 1Password to reflect new download platforms (e.g. Safari) and passkey management.
   
   - Recommends Proton Pass (as the [relevant forum post](https://discuss.privacyguides.net/t/proton-pass-password-manager/12416) has been approved).

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-03-31 03:49 UTC, jonaharagon approved these changes
Awesome, thanks!

2024-03-31 04:20 UTC, redoomed1 requested changes

2024-03-31 04:20 UTC, redoomed1 commented on docs/passwords.md
> +- [:simple-firefoxbrowser: Firefox](https://addons.mozilla.org/en-US/firefox/addon/proton-pass/)
```suggestion
- [:simple-googleplay: Google Play](https://play.google.com/store/apps/details?id=proton.android.pass&utm_source=Web&utm_medium=appbutton&utm_content=downloadpage)
- [:simple-appstore: App Store](https://apps.apple.com/us/app/proton-pass-password-manager/id6443490629?ct=appbutton_download_page)
- [:simple-windows11: Windows](https://proton.me/pass/download)
- [:simple-firefoxbrowser: Firefox](https://addons.mozilla.org/en-US/firefox/addon/proton-pass/)
```

2024-03-31 04:20 UTC, redoomed1 commented on docs/passwords.md
> +- [:simple-firefoxbrowser: Firefox](https://addons.mozilla.org/en-US/firefox/addon/proton-pass/)
Download links for the Android and iOS apps are from here: https://proton.me/pass/download

2024-03-31 04:20 UTC, redoomed1 commented on docs/passwords.md
> +[:octicons-info-16:](https://proton.me/support/pass){ .card-link title="Documentation"}
```suggestion
[:octicons-info-16:](https://proton.me/support/pass){ .card-link title="Documentation"}
[:octicons-code-16:](https://github.com/protonpass/){ .card-link title="Source Code" }
```

2024-03-31 04:20 UTC, redoomed1 commented on docs/passwords.md
> +[:octicons-info-16:](https://proton.me/support/pass){ .card-link title="Documentation"}
Link to the GitHub repo is from here (the link next to `(Apps)`): https://proton.me/community/open-source

2024-03-31 09:25 UTC, rollsicecream commented
I think it's all good now, should I make any changes?

2024-03-31 14:49 UTC, redoomed1 requested changes
Thanks for writing this description, @rollsicecream ! I just have a few notes on formatting and wording.

2024-03-31 14:49 UTC, redoomed1 commented on docs/passwords.md
> +With the acquisition of SimpleLogin in April 2022, Proton has offered an "Hide My Email" that lets you create 10 aliases (free plan) or unlimited aliases (paid plans).
```suggestion
With the acquisition of SimpleLogin in April 2022, Proton has offered a "hide-my-email" feature that lets you create 10 aliases (free plan) or unlimited aliases (paid plans).
```

2024-03-31 14:49 UTC, redoomed1 commented on docs/passwords.md
> +With the acquisition of SimpleLogin in April 2022, Proton has offered an "Hide My Email" that lets you create 10 aliases (free plan) or unlimited aliases (paid plans).
Slight change to reflect wording from this support article from Proton: https://proton.me/support/aliases-mail

2024-03-31 14:49 UTC, redoomed1 commented on docs/passwords.md
> +Proton Pass currently doesn't have any "master password" functionnality, meaning that your vault is protected with your Proton's account password and 2FA/U2F (if you have enabled it, which is what we
```suggestion
Proton Pass currently doesn't have any "master password" functionality, which means that your vault is protected with the password for your Proton account and any of their supported [two factor authentication](https://proton.me/support/two-factor-authentication-2fa) methods.
```

2024-03-31 14:49 UTC, redoomed1 commented on docs/passwords.md
> +Proton Pass's apps underwent an audit performed by Cure53 through out May and June of 2023. The security analysis company has said that "Proton Pass apps and components leave a rather positive impres
```suggestion
The Proton Pass mobile apps and browser extension underwent an audit performed by Cure53 throughout May and June of 2023. The security analysis company concluded:

> Proton Pass apps and components leave a rather positive impression in terms of security.

All issues were addressed and fixed shortly after the [report](https://res.cloudinary.com/dbulfrlrz/images/v1707561557/wp-pme/Cure53-proton-pass-20230717/Cure53-proton-pass-20230717.pdf).
```

2024-03-31 14:49 UTC, redoomed1 commented on docs/passwords.md
> +Proton Pass's apps underwent an audit performed by Cure53 through out May and June of 2023. The security analysis company has said that "Proton Pass apps and components leave a rather positive impres
Changed the quote from Cure53 to a block quote to match formatting of audits elsewhere on the site. For example, https://www.privacyguides.org/en/vpn/?h=audit#independently-audited_2

2024-03-31 14:53 UTC, rollsicecream commented on docs/passwords.md
> +Proton Pass's apps underwent an audit performed by Cure53 through out May and June of 2023. The security analysis company has said that "Proton Pass apps and components leave a rather positive impres
Thanks again!

2024-03-31 14:53 UTC, redoomed1 commented on docs/passwords.md
> +Proton Pass has an desktop application for Windows but not for macOS and Linux, they should all be coming soon.
I'm not sure if this line is necessary since the "Downloads" toggle already lists all available downloads.

2024-03-31 14:54 UTC, jonaharagon commented on docs/passwords.md
> +Proton Pass currently doesn't have any "master password" functionnality, meaning that your vault is protected with your Proton's account password and 2FA/U2F (if you have enabled it, which is what we
I'm wondering if we should have a preference for internal links, and that should link to the MFA knowledge base article instead?

2024-03-31 14:54 UTC, rollsicecream commented on docs/passwords.md
> +Proton Pass has an desktop application for Windows but not for macOS and Linux, they should all be coming soon.
You're right. Will remove that part soon.

2024-03-31 14:57 UTC, redoomed1 commented on docs/passwords.md
> +Proton Pass currently doesn't have any "master password" functionnality, meaning that your vault is protected with your Proton's account password and 2FA/U2F (if you have enabled it, which is what we
That's a valid question, @jonaharagon . I used this page on the site, https://www.privacyguides.org/en/email/#account-security, as a reference for my suggestion.

2024-03-31 15:11 UTC, jonaharagon commented on docs/passwords.md
> +Proton Pass currently doesn't have any "master password" functionnality, meaning that your vault is protected with your Proton's account password and 2FA/U2F (if you have enabled it, which is what we
👍 if the new link previews on hover in #2451 get added to the site, those internal links will become a lot more useful at a glance anyways.

2024-03-31 15:22 UTC, rollsicecream commented on docs/passwords.md
> +Proton Pass currently doesn't have any "master password" functionnality, meaning that your vault is protected with your Proton's account password and 2FA/U2F (if you have enabled it, which is what we
[6b67c17](https://github.com/privacyguides/privacyguides.org/pull/2459/commits/6b67c1713df1f913f7081a0d968e6bf4df22f75e)

2024-03-31 15:23 UTC, rollsicecream commented
Oof, that was a lot of great changes thanks to @redoomed1. Normally, everything should be good.

2024-04-03 04:47 UTC, jonaharagon commented on docs/passwords.md
> +Proton Pass currently doesn't have any "master password" functionality, which means that your vault is protected with the password for your Proton account and any of their supported [two factor authe
```suggestion
Proton Pass currently doesn't have any "master password" functionality, which means that your vault is protected with the password for your Proton account and any of their supported [two factor authentication](basics/multi-factor-authentication.md) methods.
```

2024-04-08 15:44 UTC, freddy-m commented on docs/passwords.md
> +Proton Pass is an open-source, end-to-end encrypted password manager developed by Proton, the team behind the world's largest encrypted email service, Proton Mail. It securely stores your login crede
This could just say 'the team behind Proton Mail' - but perhaps thats a bit bland.

2024-04-08 15:51 UTC, freddy-m approved these changes
LGTM - thanks for the PR!

2024-04-10 05:49 UTC, jonaharagon commented on docs/passwords.md
> +Proton Pass is an open-source, end-to-end encrypted password manager developed by Proton, the team behind the world's largest encrypted email service, Proton Mail. It securely stores your login crede
```suggestion
Proton Pass is an open-source, end-to-end encrypted password manager developed by Proton, the team behind [Proton Mail](email.md#proton-mail). It securely stores your login credentials, generates unique email aliases, supports and stores passkeys, and offers a community-funded, Swiss-based service with strict data privacy laws.
```

2024-04-10 05:56 UTC, merged