Separate browser extensions page
privacyguides/privacyguides.org pull request #2461
Opened 2024-03-30 23:17 UTC by jonaharagon

Changes proposed in this PR:

- Create new "Browser Extensions" page

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-03-31 09:30 UTC, rollsicecream commented
Since it's a new page, should we put it in `config/mkdocs-[LANGUAGE].yml` files?

2024-03-31 09:31 UTC, jonaharagon commented
The layout of the config files has changed in https://github.com/privacyguides/privacyguides.org/commit/fc19f44c186a699949a409374d3f9619e38d83ee

2024-03-31 09:33 UTC, rollsicecream commented
Oh, haven't noticed, btw now that we have Netlify and GitHub actions together, they spam me every time via E-Mail lol.

2024-04-02 15:35 UTC, redoomed1 requested changes

2024-04-02 15:35 UTC, redoomed1 commented on docs/browser-extensions.md
> +However, some provide functionality which can outweighs these downsides in certain situations, particularly when it comes to [content blocking](basics/common-threats.md#mass-surveillance-programs).
```suggestion
However, some provide functionality which can outweigh these downsides in certain situations, particularly when it comes to [content blocking](basics/common-threats.md#mass-surveillance-programs).
```

2024-04-02 15:35 UTC, redoomed1 commented on docs/browser-extensions.md
> +Be particular about the extensions on this page you choose to install, and don't install anything which duplicates the functionality of another tool/extension you're already using, or don't immediate
```suggestion
Be particular about the extensions on this page you choose to install. Don't install extensions which you don't immediately have a need for, or ones that duplicate the functionality of another tool/extension you're already using. For example, [Brave](desktop-browsers.md#brave) users don't need to install uBlock Origin, because Brave Shields already provides the same functionality.
```
I find the original syntax a little awkward (i.e., "don't install anything which [...] don't immediately have a need for").

2024-04-03 09:50 UTC, dngray commented on docs/browser-extensions.md
> +Be particular about the extensions on this page you choose to install, and don't install anything which duplicates the functionality of another tool/extension you're already using, or don't immediate
I think we can do better here to be honest I don't really like "Be particular about the extensions on this page you choose to install" because what does that even mean?

2024-04-03 12:24 UTC, dngray approved these changes

2024-04-03 12:34 UTC, merged