Common Threats: Supply chain attacks
privacyguides/privacyguides.org pull request #2467
Opened 2024-03-31 09:11 UTC by dngray

Changes proposed in this PR:

- https://discuss.privacyguides.net/t/add-supply-chain-attacks-to-common-threats-page/17595

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-03-31 14:41 UTC, jonaharagon requested changes
I'll have to read this tomorrow, but I'll just note quick that new colors should be checked against https://webaim.org/resources/contrastchecker/

2024-04-01 11:37 UTC, dngray commented
Yes i should have marked this as a draft, it might require editorial editing to make it nice.

2024-04-02 15:30 UTC, zyansheep requested changes
Have some ideas for some small changes :)

2024-04-02 15:30 UTC, zyansheep commented on docs/basics/common-threats.md
> +2. Automated build infrastructure for released binary code reduces the attack surface such as, a compromised developer workstation or breached server. It provides accountability to others involved in
Is this recommending automated build infrastructure over local developer workstations / breached servers? If so, I think it could be rewritten better:
```suggestion
2. Make sure software you use builds released binaries with widely-used, trusted build infrastructure platforms (i.e. GitHub workflows) as opposed to developer workstations or self-hosted servers. This is in order to reduce the attack surface and give confidence that the binaries produced are in fact produced correctly.
```
Imo, the best strategy is reproducible builds cross-checked from multiple parties (more reason to adopt nixos lol) but I think relying on centralized build infrastructure is also a good strategy for people without the time or compute.

2024-04-02 15:30 UTC, zyansheep commented on docs/basics/common-threats.md
> +4. In open source projects the code should have commit messages which are explain exactly what the associated code does. This makes it easier for external parties to verify and detect if the code doe
Not sure how relevant commit messages are. They are useful for devs for git hygiene, but for security, I imagine any external party is gonna read the code anyway. (poor commit messages don't necessarily mean bad security). 

Maybe I'm just projecting tho :sweat_smile:

2024-04-02 23:58 UTC, jonaharagon requested changes

2024-04-02 23:58 UTC, jonaharagon commented on docs/basics/common-threats.md
> +2. Automated build infrastructure for released binary code reduces the attack surface such as, a compromised developer workstation or breached server. It provides accountability to others involved in
This advice is interesting, because it is advocating for the exact thing which hid the `xz` problem 😅 

I mean I suppose not all vulnerabilities are going to be on that level of sophistication, but right now this list doesn't mention compiling from source yourself at all, and it probably should.

2024-04-02 23:58 UTC, jonaharagon commented on docs/basics/common-threats.md
> +6. Economical pressure that would occur if a company was involved with negligent behavior that enabled malicious code to be added. This may very well mean software developed by "Big Tech" has more sc
```suggestion
5. The number of contributors or maintainers, a lone developer may be more susceptible to being coerced or forced into adding malicious code by an external party.
6. Economical pressure that would occur if a company was involved with negligent behavior that enabled malicious code to be added. This may very well mean software developed by "Big Tech" has more scrutiny than a lone developer who doesn't answer to anyone.
```

So... do these say the same thing though? Feels like we could go like this instead:

```suggestion
5. Noting the number of contributors or maintainers a program has. A lone developer may be more susceptible to being coerced into adding malicious code by an external party, or to negligently enable undesirable behavior.
```

2024-04-02 23:58 UTC, jonaharagon commented on docs/basics/common-threats.md
> +1. A contributor or employee might work their way into a position of power within an organization and then abuse that position to add some malicious code.
```suggestion
1. A contributor or employee might work their way into a position of power within a project or organization, then abuse that position by adding malicious code.
```

2024-04-02 23:58 UTC, jonaharagon commented on docs/basics/common-misconceptions.md
> +[^1]: Malicious code was discovered in the upstream tarballs of xz a popular compression library. The backdoor was intended to give malicious actors remote access via SSH if they possessed a special
```suggestion
[^1]: A notable supply chain attack occurred in March 2024, when a malicious maintainer added a obfuscated backdoor into `xz`, a popular compression library. The backdoor ([CVE-2024-3094](https://www.cve.org/CVERecord?id=CVE-2024-3094)) was intended to give an unknown party remote access to most Linux servers via SSH, but it was discovered before it had been widely deployed.
```
I kinda like the old phrasing of footnote because it flows from the footnote link better.

2024-04-02 23:58 UTC, jonaharagon commented on docs/basics/common-threats.md
> +Supply chain attacks are a type of <span class="pg-orange">:material-bug-outline: Passive Attack</span> which can be part of a larger <span class="pg-red">:material-target-account: Targeted Attack</s
I think there are many more cases of these being targeted attacks than the other way round.

```suggestion
Supply chain attacks are frequently a form of <span class="pg-red">:material-target-account: Targeted Attack</span> towards businesses, governments, and activists, although they can end up compromising the public at large as well.

<div class="admonition example" markdown>
<p class="admonition-title">Example</p>

A notable example of this occurred in 2017 when M.E.Doc, a popular accounting software in Ukraine, was infected with the *NotPetya* virus, subsequently infecting people who downloaded that software with ransomware. NotPetya itself was a ransomware attack which impacted 2000+ companies in various countries, and was based on the *EternalBlue* exploit developed by the NSA to attack Windows computers over the network.

</div>
```

2024-04-02 23:58 UTC, jonaharagon commented on docs/basics/common-threats.md
> +<span class="pg-amber">:material-package-variant-closed-remove: Supply Chain</span>
I'm wondering if, instead of placing this here, we add a new section at the bottom of the page: "Advanced Persistent Threats" where we cover larger-scale issues like this. Thoughts?

2024-04-03 05:27 UTC, dngray commented on docs/basics/common-threats.md
> +2. Automated build infrastructure for released binary code reduces the attack surface such as, a compromised developer workstation or breached server. It provides accountability to others involved in
> This advice is interesting, because it is advocating for the exact thing which hid the `xz` problem 😅

Its supposed to read as the opposite to that. Ideally tarballs aren't offered only tagged releases that come from a git source.

2024-04-03 05:28 UTC, dngray commented on docs/basics/common-threats.md
> +4. In open source projects the code should have commit messages which are explain exactly what the associated code does. This makes it easier for external parties to verify and detect if the code doe
That's the thing they've won't. I've noticed a clear pattern where projects with a heap of commits that just say "fix" basically get no external attention. Nobody really cares about those projects.

2024-04-03 14:26 UTC, dngray commented on docs/basics/common-threats.md
> +<span class="pg-amber">:material-package-variant-closed-remove: Supply Chain</span>
I kind of like that idea.

2024-04-03 23:08 UTC, freddy-m commented on docs/basics/common-threats.md
> +6. Economical pressure that would occur if a company was involved with negligent behavior that enabled malicious code to be added. This may very well mean software developed by "Big Tech" has more sc
I feel as though it could be worth keeping this sentence:

> This may very well mean software developed by "Big Tech" has more scrutiny than a lone developer who doesn't answer to anyone.

Otherwise the combined paragraph is better.

2024-04-10 14:01 UTC, dngray commented on docs/basics/common-threats.md
> +Supply chain attacks are a type of <span class="pg-orange">:material-bug-outline: Passive Attack</span> which can be part of a larger <span class="pg-red">:material-target-account: Targeted Attack</s
> these being targeted attacks than the other way round

I guess it depends on how you look at it. Targeted in respect to a library, or piece of software. Passive in the definition that it's supposed to target a lot of people.

But now I think about it I like your definition better.

2024-04-10 14:04 UTC, dngray commented on docs/basics/common-threats.md
> +2. Automated build infrastructure for released binary code reduces the attack surface such as, a compromised developer workstation or breached server. It provides accountability to others involved in
Yes, going to approve this because we do value [reproducible builds](https://reproducible-builds.org/) elsewhere on the site.

2024-04-10 14:05 UTC, dngray commented
> I'll have to read this tomorrow, but I'll just note quick that new colors should be checked against https://webaim.org/resources/contrastchecker/

We should probably make a note in the https://www.privacyguides.org/en/meta/writing-style guide about this maybe under accessibility. Or just have an accessibility meta page?

2024-04-10 14:57 UTC, dngray commented on docs/basics/common-threats.md
> +6. Economical pressure that would occur if a company was involved with negligent behavior that enabled malicious code to be added. This may very well mean software developed by "Big Tech" has more sc
I do as well, the reason being is because we see a lot of people thinking they are increasing privacy by shifting to a small service that may not be very mature, instead of one which is well developed, or resourced or even has E2EE.

2024-04-10 15:11 UTC, dngray commented on docs/basics/common-threats.md
> +4. In open source projects the code should have commit messages which are explain exactly what the associated code does. This makes it easier for external parties to verify and detect if the code doe
I reworded this to "audit", because we do use that word a lot.

The easier it is for outsiders to get an understanding of how things are implemented better. This might also mean it's easier to track a regression that is actually a cleverly designed exploit.

2024-04-10 15:21 UTC, dngray commented on docs/basics/common-threats.md
> +<span class="pg-amber">:material-package-variant-closed-remove: Supply Chain</span>
I'm wondering whether this actually is a good idea at all.

Supply chain attacks don't necessarily have to come from an APT. For example in the case of naming similar nodejs libs that are often typo'ed or uploading some crappy crypto wallet to a store, these are not done by an APT.

2024-04-10 15:24 UTC, dngray commented on docs/basics/common-threats.md
> +6. Economical pressure that would occur if a company was involved with negligent behavior that enabled malicious code to be added. This may very well mean software developed by "Big Tech" has more sc
Applied what both @freddy-m and @jonaharagon wrote.

2024-04-11 00:33 UTC, jonaharagon commented on docs/basics/common-misconceptions.md
> +Open-source software *can* be audited by third-parties, and is often more transparent about potential vulnerabilities than proprietary counterparts. It also allows you to review the code and disable
```suggestion
Open-source software *can* be audited by third-parties, and is often more transparent about potential vulnerabilities than proprietary counterparts. It also allows you to review the code and disable any suspicious functionality you find yourself. However, *unless you do so*, there is no guarantee that code has ever been evaluated, especially with smaller software projects. The open development process has also sometimes been exploited to introduce new vulnerabilities known as <span class="pg-viridian">:material-package-variant-closed-remove: Supply Chain Attacks</span>, which are discussed further in our [Common Threats](common-threats.md) page.[^1]
```

2024-04-11 00:51 UTC, jonaharagon commented on docs/basics/common-threats.md
> +<span class="pg-viridian">:material-package-variant-closed-remove: Supply Chain</span>
```suggestion
<span class="pg-viridian">:material-package-variant-closed-remove: Supply Chain Attacks</span>
```

2024-04-11 05:45 UTC, jonaharagon requested changes

2024-04-11 05:45 UTC, jonaharagon commented on docs/basics/common-threats.md
> +1. Only adopting popular software that has been around for a while. The more interest in a project the, the greater likelihood that external parties will notice malicious changes. A malicious actor w
```suggestion
1. Only adopting popular software that has been around for a while. The more interest in a project the greater likelihood that external parties will notice malicious changes. A malicious actor will also need to spend more time gaining community trust with meaningful contributions.
```

2024-04-11 05:45 UTC, jonaharagon commented on docs/basics/common-threats.md
> +2. Make sure software you use builds released binaries with widely-used, trusted build infrastructure platforms (i.e. GitHub workflows) as opposed to developer workstations or self-hosted servers. Th
```suggestion
2. Finding software which releases binaries with widely-used, trusted build infrastructure platforms, as opposed to developer workstations or self-hosted servers. Some systems like GitHub Actions let you inspect the build script that runs publicly for extra confidence. This lessens the likelihood that malware on a developer's machine could infect their packages, and gives confidence that the binaries produced are in fact produced correctly.
```

i think this is worded weird; also added info on why workflows are cool

2024-04-11 05:45 UTC, jonaharagon commented on docs/basics/common-threats.md
> +3. Code signing on individual commits and releases increases an auditable trail of who did what. For example: Was the malicious code in the software repository? Which developer added it? Was it added
```suggestion
3. Looking for code signing on individual source code commits and releases, which creates an auditable trail of who did what. For example: Was the malicious code in the software repository? Which developer added it? Was it added during the build process?
```

All of these bullet points should be worded as if they finish the sentence "...and makes an effort to reduce risk by:" because that is how the list begins. Like if you read it out loud, "reduce risk by looking for code signing..." etc.

2024-04-11 05:45 UTC, jonaharagon commented on docs/basics/common-threats.md
> +4. In open source projects the code should have meaningful commit messages (such as [conventional commits](https://conventionalcommits.org)) which explain what the change is supposed accomplish. Clea
```suggestion
4. Checking whether the source code has meaningful commit messages (such as [conventional commits](https://conventionalcommits.org)) which explain what the change is supposed to accomplish. Clear messages can make it easier for outsiders to the project to verify, audit, and find bugs.
```

2024-04-11 09:32 UTC, dngray commented on docs/basics/common-threats.md
> +3. Code signing on individual commits and releases increases an auditable trail of who did what. For example: Was the malicious code in the software repository? Which developer added it? Was it added
I do agree on that, i think i had bullet points originally but couldn't figure out how to indent it properly to be a sublist.

2024-04-11 17:23 UTC, jonaharagon approved these changes

2024-04-11 18:08 UTC, merged