Add Coinsbee to financial services
privacyguides/privacyguides.org pull request #2482
Opened 2024-04-03 13:30 UTC by tacolopo

Need to add logo to asset, the forked repository doesn't have the assets/img/financial-services folder.

Coinsbee accepts XMR and does not require any verification for orders less than 1000 euros. They accept ephemeral emails and allow VPNs. I have no association to Coinsbee.

Changes proposed in this PR:

-

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-04-03 14:18 UTC, rollsicecream requested changes
In addition to what @redoomed1 said....

2024-04-03 14:18 UTC, rollsicecream commented on docs/financial-services.md
> +**Coinsbee** (available worldwide) allows you to purchase gift cards for 2,500 merchants in 185 countries. No verification is required for orders less than €1,000.
Better wording:

```suggestion
**Coinsbee** (available worldwide) allows you to purchase gift cards from 2,500 merchants in 185 countries. No verification is required for orders less than €1,000.
```

2024-04-03 14:18 UTC, rollsicecream commented on docs/financial-services.md
> +![Coinsbee logo](assets/img/financial-services/coincards.svg){ align=right }
You are pointing the recommendation card to the CoinCards SVG image, which is a different service recommended on this page....

```suggestion
![Coinsbee logo](assets/img/financial-services/coinsbee.svg){ align=right }
```
The SVG image that you will add should have that filename, of course.

2024-04-03 14:21 UTC, rollsicecream requested changes

2024-04-03 14:21 UTC, rollsicecream commented on docs/financial-services.md
> +**Coinsbee** (available worldwide) allows you to purchase gift cards from 2,500 merchants in 185 countries. No verification is required for orders less than €1,000.
Another better wording: 

```suggestion
**Coinsbee** (available worldwide) allows you to purchase gift cards from 2,500 merchants across 185 countries. No verification is required for orders less than €1,000.
```

2024-04-03 16:46 UTC, tacolopo commented
Thanks to @rollsicecream for starting the forum discussion. My apologies for butchering the process.

2024-04-10 23:39 UTC, jonaharagon commented
> Need to add logo to asset, the forked repository doesn't have the assets/img/financial-services folder.

https://github.com/tacolopo/privacyguides.org/tree/main/theme/assets/img/financial-services

2024-08-29 14:41 UTC, closed without merging

2024-08-29 14:42 UTC, tacolopo commented
Privacy guides has proved so immensely slow with an inane contribution process that it is not worth contributing to. Nor is it relevant for anyone seeking up-to-date privacy tools.