Add a Reddit frontend
privacyguides/privacyguides.org pull request #2495
Opened 2024-04-06 07:59 UTC by TechFanTheo

Changes proposed in this PR:

Add Redlib 
![image](https://github.com/privacyguides/privacyguides.org/assets/78900789/b64354f7-9527-4d6c-83e0-c0a3b222e628) and a warning against Old Reddit

- [OK ] I have disclosed any relevant conflicts of interest in my post.
- [ OK] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [OK ] I am the sole author of this work. 
- [OK ] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-04-06 08:21 UTC, jonaharagon commented
Related discussion for reference: https://discuss.privacyguides.net/t/recommend-redlib-in-frontends-section/17184

2024-04-07 13:06 UTC, dngray approved these changes

2024-04-07 13:11 UTC, TechFanTheo commented on docs/frontends.md
> +[Old Reddit](htpps://old.reddit.com) does not provide more privacy than New Reddit by itself. It also blocks connection from VPNs, and uses Javascript. It will also sometimes redirect you to New Redd
That's good. About Old Reddit Onion, it is essentially broken from my testing.

2024-04-07 14:18 UTC, redoomed1 requested changes

2024-04-07 16:38 UTC, dngray commented on docs/frontends.md
> +The [Old Reddit](https://old.reddit.com) website doesn't require as much JavaScript as the new Reddit website but it has more common in recent times for it to block public VPNs. You can use Old Reddi
yeah that does sound better imo

2024-04-10 15:15 UTC, freddy-m approved these changes

2024-04-10 15:47 UTC, merged