Add initial foundation for email services table, clarify Proton free …
privacyguides/privacyguides.org pull request #2518
Opened 2024-04-11 16:16 UTC by redoomed1

Changes proposed in this PR:

- Add comparison table for the Email Services page
  - As marked on GitHub, this is a draft PR as wording and formatting is not set in stone. I'm unsure of what to rearrange, add, or remove, so any feedback is welcome. Here is a question as a starting point:
    - **Table Columns**: Are there any criteria that should be added to or removed from the current table?
- Alter wording about Proton and Tuta's free plans for [clarity](https://github.com/privacyguides/privacyguides.org/pull/2512#discussion_r1560439458)
- Update Proton Unlimited description in the "Additional Functionality" section under the Proton Mail recommendation

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-04-11 19:49 UTC, redoomed1 commented
Changes made before marking PR as ready for review:

- Add "Recommended Providers" second-level heading
- Add sentence referencing the detailed criteria on the page (same as the one [introducing the VPN table](https://www.privacyguides.org/en/vpn/#recommended-providers))
- Remove space between number and unit (e.g., "500MB") to match other [instances](https://www.privacyguides.org/en/photo-management/#stingle) on the site
- Update instructions for disabling Proton Mail crash reporting
- Remove pricing information for Proton Unlimited and embed link to detailed support article about the paid plan instead
- Make minor grammatical changes

2024-04-13 10:47 UTC, dngray approved these changes

2024-04-13 14:41 UTC, jonaharagon requested changes

2024-04-13 14:41 UTC, jonaharagon commented on docs/email.md
> +## Recommended Providers
I don't think this header is necessary is it?

2024-04-13 14:43 UTC, redoomed1 commented on docs/email.md
> +## Recommended Providers
Eh, perhaps it isn't. I just added it here to keep this page uniform with the other provider pages with tables.

2024-04-13 14:44 UTC, jonaharagon commented on docs/email.md
> +## Recommended Providers
I see that this header is consistent with the other ones, although I think that the one on the VPN page is a mistake as well, now that I'm thinking about it.

It makes sense for DNS and search engine where we have 2-3 different types of recommendations on the page, but it should be removed from this page and VPN page where there aren't recommendation sub-categories I think.

2024-04-13 14:46 UTC, jonaharagon commented on docs/email.md
> +## Recommended Providers
Hm... I guess we do have two different types of recommendations here too lol, although in this case we're including both in the same table so it's not the same.

2024-04-13 14:58 UTC, redoomed1 commented on docs/email.md
> +## Recommended Providers
> two different types of recommendations here too lol, although in this case we're including both in the same table so it's not the same.

Are they really two _different types_ of recommendations in the same sense as the search engines page (primary search + metasearch) or the DNS resolvers page (self-hosted, cloud-based, and encrypted proxies)?

In the case of the email services page, I think the only distinguishing trait for the difference is that Tuta doesn't support OpenPGP (correct me if I'm wrong).

2024-04-14 00:15 UTC, jonaharagon approved these changes
changed my mind, LGTM 👍

2024-04-14 05:26 UTC, merged