More detailed Session description
privacyguides/privacyguides.org pull request #2519
Opened 2024-04-11 16:18 UTC by jermanuts

Changes proposed in this PR:

Explain how Session open group works. Current one is vague and lacking.

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-04-11 16:19 UTC, jermanuts commented
Should we recommend also disabling Link previews as mentioned here https://discuss.privacyguides.net/t/critical-flaws-in-desktop-session-messenger/16674 ?

2024-04-11 16:47 UTC, dngray approved these changes

2024-04-11 16:47 UTC, dngray reviewed
Wouldn't start a sentence with "however".

2024-04-11 17:50 UTC, dngray requested changes

2024-04-11 17:51 UTC, jonaharagon requested changes
> However, they are not as private as one-on-one chats or closed groups.

can we link to a resource which explains why this is the case in more detail? or explain why ourselves

2024-04-11 17:51 UTC, dngray commented
> can we link to a resource which explains why this is the case in more detail? or explain why ourselves

that might be a better idea.

2024-04-11 19:26 UTC, jermanuts commented
I got it from https://getsession.org/lightpaper/pdf. Their docs pretty lacking tbh.

2024-05-22 06:11 UTC, jonaharagon requested changes

2024-05-22 06:11 UTC, jonaharagon commented on docs/real-time-communication.md
> +Session allows for E2EE in one-on-one chats or closed groups which allow for up to 100 members. Open groups have no restriction on the number of members, they are hosted on federated servers operated
```suggestion
Session allows for E2EE in one-on-one chats or closed groups which allow for up to 100 members. It is also possible to [host](https://docs.oxen.io/oxen-docs/products-built-on-oxen/session/guides/open-group-setup) or join an open group which can host thousands of members, but messages in these open groups are **not** end-to-end encrypted between participants.
```

2024-11-11 19:44 UTC, friadev requested changes

2024-11-11 19:44 UTC, friadev commented on docs/real-time-communication.md
> +
```suggestion
```

2024-11-11 19:45 UTC, friadev approved these changes

2024-11-11 19:54 UTC, redoomed1 submitted a review, later dismissed
Just a tiny suggestion to change wording so that it reads a little smoother but otherwise LGTM

2024-11-11 19:56 UTC, redoomed1 approved these changes
Just a tiny suggestion to change wording so that it reads a little smoother but otherwise LGTM

2024-11-11 19:56 UTC, redoomed1 commented on docs/real-time-communication.md
> +Session allows for E2EE in one-on-one chats or closed groups which allow for up to 100 members. It is also possible to [host](https://docs.oxen.io/oxen-docs/products-built-on-oxen/session/guides/open
```suggestion
Session allows for E2EE in one-on-one chats or closed groups which allow for up to 100 members. It is also possible to [set up](https://docs.oxen.io/oxen-docs/products-built-on-oxen/session/guides/open-group-setup) or join open groups which can host thousands of members, but messages in these open groups are **not** end-to-end encrypted between participants.
```

2024-11-12 01:33 UTC, jonaharagon approved these changes

2024-11-12 01:40 UTC, merged