Create ai-chatbots.md
privacyguides/privacyguides.org pull request #2525
Opened 2024-04-14 07:14 UTC by TechFanTheo

Need feedback on criteria, including reasonable rate limit. For the header, I will try to find how to upload the assets.

Feel free to add how to run AI models locally, with LM studio for example.

Changes proposed in this PR:

-

- [X] I have disclosed any relevant conflicts of interest in my post.
- [X] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [ X] I am the sole author of this work. 
- [ X] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-04-16 05:12 UTC, TechFanTheo commented
Relevant discussion : https://discuss.privacyguides.net/t/ai-tool/14347/16

2024-04-24 11:56 UTC, rollsicecream requested changes

2024-04-24 12:35 UTC, TechFanTheo commented on docs/ai-chatbots.md
> +cover:file/file
I just think we should change the name of this category **AI Chat** as it is the standard name used by every AI product. Also, I personally prefer this image as it is more clear that this is "talking robots "
https://unsplash.com/photos/a-white-robot-with-blue-eyes-and-a-laptop--0xMiYQmk8g

2024-04-24 20:20 UTC, rollsicecream requested changes
I don't know why but the page is entirely broken for me.
![Capture d’écran du 2024-04-24 22-20-00](https://github.com/privacyguides/privacyguides.org/assets/153316540/fce6a9c0-27a0-4f28-9314-5046aeec144a)
![Capture d’écran du 2024-04-24 22-20-06](https://github.com/privacyguides/privacyguides.org/assets/153316540/a133fee3-7536-4e30-95df-c4a00a9556f4)
![Capture d’écran du 2024-04-24 22-20-11](https://github.com/privacyguides/privacyguides.org/assets/153316540/9a264e38-8b93-4564-8551-80ff47caea50)

2024-04-27 04:41 UTC, TechFanTheo commented
![Screenshot Recommended AI Chatbots Private ChatGPT Alternatives - Privacy Guides](https://github.com/privacyguides/privacyguides.org/assets/78900789/c3501d10-44ae-4f06-bd35-f10cb59b8af5)
I commited a patch, it seem to work, although we still have to add logo, add the Kobold icon to the PG assets repo. I also have some concerns, that I outline on the [forum post](https://discuss.privacyguides.net/t/ai-tool/14347/29)

2024-05-29 16:57 UTC, navalspectator commented on docs/ai-chatbots.md
> +
We can divide this into two parts: Cloud-based models and local models.

2024-05-29 17:07 UTC, navalspectator commented on docs/ai-chatbots.md
> +
GPT4ALL
Website: https://gpt4all.io/
GPT4All is an awesome free-to-use, locally running, privacy-aware chatbot developed by nomic.ai. After you install the app and download the models you want to use, it does not require access to the internet. Depending on your device RAM and storage, you can use a variety of open source models. It is available on Linux, Windows, and MacOS.

Telemetry, and the use of your chats for training purposes are opt-in and we do not suggest to activate those.

There is also LLamaChat, but apart from its UI, I dont see any reason to suggest it: https://www.llamachat.app/

2024-06-06 22:21 UTC, freddy-m commented
Closing this PR until the discussion is approved, cc @privacyguides/team

2024-06-07 12:07 UTC, I-I-IT commented
> Closing this PR until the discussion is approved, cc @privacyguides/team

??? There is a discussion, and we are drafting this. I don't see need to close this PR.  Other, like this one https://github.com/privacyguides/privacyguides.org/pull/2381, are also not approved yet.

2024-06-09 11:37 UTC, dngray commented
This was mistakenly closed.

2024-06-09 13:03 UTC, I-I-IT commented
Thanks

2024-09-01 16:48 UTC, I-I-IT commented
I have made a lot of modfications and I believe it is now a good quality for wide release.

2024-09-02 21:23 UTC, xe-3 requested changes
This review pertains only to the introduction and the 'hosted providers' section. I did not have time to review the local models section, but I plan to.

Most of the changes I've suggested are relate to consistency between sections, rewordings, or small typos and grammar corrections.

2024-09-02 21:23 UTC, xe-3 commented on docs/ai-chatbots.md
> +Anthropic and OpenAI stores chats for up to 30 days. Do not use those models for anything you wouldn't want the World to know about.
Changes to the language to make this admonition more consistent with the Anthropic admonition in the Brave Leo section:

```suggestion
We recommend against using the proprietary models from Anthropic or OpenAI because those providers keep chat history for up to 30 days.
```

2024-09-02 21:23 UTC, xe-3 commented on docs/ai-chatbots.md
> +We recommend against using Anthropic's Claude models because the company keeps a chat history for 30 days.
Changes to make this admonition more consistent with the admonition in the Duckduckgo section:

```suggestion
We recommend against using Anthropic's proprietary Claude models because Anthropic keeps chat history for up to 30 days.
```

2024-09-02 21:23 UTC, xe-3 commented on docs/ai-chatbots.md
> +<p class="admonition-title">Claude chats are kept for 30 days </p>
```suggestion
<p class="admonition-title">Proprietary model providers retain your chats</p>
```

2024-09-02 22:04 UTC, I-I-IT commented
Thanks @xe-3 
I messed up with this [commit](https://github.com/privacyguides/privacyguides.org/pull/2525/commits/95db16724f4646046cb340aa84b1004a0779ef9d) cause I needed to edit your recommendation, not create a new individual commit.

2024-09-16 17:55 UTC, I-I-IT commented
@xe-3 Dix you look at the rest ?

2024-09-16 22:10 UTC, xe-3 commented
> @xe-3 Dix you look at the rest ?

Sorryl. I was holding off briefly because some developments on the local side have been happening in recent weeks, and then I just got distracted and dropped the ball. No promises, but I think I can look it over today.

2024-09-17 00:25 UTC, xe-3 requested changes
Some changes for you to consider, plus one typo.

2024-09-17 00:25 UTC, xe-3 commented on docs/ai-chatbots.md
> + But what language models can you run ? Meta and Mistral release their best model under an "open" license, while Google and Microsoft only release small, less capable models. The two leaders in the f
Suggested (optional) rewrite:
```suggestion
There are many permissively licensed models available which can be run locally. [Hugging Face](https://huggingface.co/models?library=gguf) is a platform which lets you browse, research, and download models in common formats like GGUF. In addition to big names like Mistral, Meta, Microsoft, and Google, there are many community models and 'fine-tunes' to choose from. For consumer grade hardware, it is generally recommended to use [quantized models](https://huggingface.co/docs/optimum/en/concept_guides/quantization) for the best balance between model quality and performance.
```

2024-10-20 16:46 UTC, rollsicecream commented
> @rollsicecream could you look at the current preview ? It is quite good now, compared to a few months ago.

Yeah, you're right on that! Though just 3 things to fix: 

- The DuckDuckGo AI PNG doesn't seem like to have the best image quality on the world lol
- Same thing for Ollama
- On the DuckDuckGo AI recommendation card, "search engine providers" should be rendered as a link with Markdown but doesn't seem to be the case here. Seems like a formatting problem.

2024-10-21 15:17 UTC, I-I-IT commented
Thank you for your answers. Let me know what are the future steps that I will need to take.

> * The DuckDuckGo AI PNG doesn't seem like to have the best image quality on the world lol
> * Same thing for Ollama

Both are fixed, I think it was my png to svg comversion that compressed them. I now just put them in png.
> * On the DuckDuckGo AI recommendation card, "search engine providers" should be rendered as a link with Markdown but doesn't seem to be the case here. Seems like a formatting problem.
Is fixed

2024-10-22 05:35 UTC, kimg45 requested changes

2024-10-22 05:35 UTC, kimg45 commented on docs/ai-chatbots.md
> +Since the release of **ChatGPT** in 2022, talking with **Large Language Models** (*LLMs*) has become common. **LLMs can help us** write better, understand unfamiliar subjects or answer a wide range o
```suggestion
Since the release of **ChatGPT** in 2022, talking with **Large Language Models** (*LLMs*) has become common. **LLMs can help us** write better, understand unfamiliar subjects or answer a wide range of questions. However, the developers of those models **need data to improve their models**. Unfortunately, this often **includes your conversations** with the AI. Those private conversations must be stored, which introduces a risk of data breaches. Furthermore, there is a real possibility the LLM will leak your private information in future conversations with other users.
```

2024-10-22 05:52 UTC, kimg45 requested changes

2024-10-22 05:52 UTC, kimg45 commented on docs/ai-chatbots.md
> +meta_title: "Recommended AI Chatbots : Private ChatGPT Alternatives - Privacy Guides"
```suggestion
meta_title: "Recommended AI Chats : Private ChatGPT Alternatives - Privacy Guides"
```

2024-10-22 05:52 UTC, kimg45 commented on docs/ai-chatbots.md
> +When using cloud-based AI chatbots, be mindful of the personal information you share. Even if a service doesn't store your conversations, there's still a risk of sensitive data being exposed or misus
```suggestion
When using cloud-based AI chats, be mindful of the personal information you share. Even if a service doesn't store your conversations, there's still a risk of sensitive data being exposed or misused. **Do not share sensitive information** related to health, finance, or other highly personal matters to protect your privacy and security.
```

2024-10-22 05:52 UTC, kimg45 commented on docs/tools.md
> +### AI chatbots
```suggestion
### AI Chats
```

2024-10-24 11:54 UTC, I-I-IT commented
So I changed ai-chatbots/ai-chats to AI chat per Google Trends 
The files are now ai-chat, and the appeation is AI chat tools
![google-trends-ai](https://github.com/user-attachments/assets/ffd86988-c449-4131-8fe2-4b32af6b4ad5)

@rollsicecream I fixed the issues you told me. Is it good for you nows?

2024-10-28 21:53 UTC, I-I-IT commented
@ph00lt0 thanks for your suggestions. Please note that I have been working on a few changes to make the recommendations more digest and easy to understand for newcomers. It might be a couple of days before I push it, then I will review your changes.

2024-10-31 12:14 UTC, I-I-IT commented
@jonaharagon could you review this PR ? I have spent a lot of times working on this.

2024-10-31 18:22 UTC, rollsicecream commented on docs/ai-chat.md
> +- Providers should only have open-weight models that they self-host.
You can see the definition of that word by hovering over it with a computer mouse: "An open-weights model is an AI model that anyone can download and use, but for which the underlying training data and/or algorithms are proprietary."

2024-11-01 20:34 UTC, rollsicecream commented
> @rollsicecream I fixed the issues you told me. Is it good for you now?

That's pretty good :+1:

2024-11-01 20:36 UTC, rollsicecream commented on docs/ai-chat.md
> +- Should not be rate-limited.
Should be noted that Brave Leo, in its free plan, is rate-limited (5 msgs only I guess last time I checked)

2024-11-10 03:44 UTC, friadev requested changes

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-info-16:](https://help.duckduckgo.com){ .card-link title=Documentation}
```suggestion
[:octicons-info-16:](https://help.duckduckgo.com){ .card-link title="Documentation" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +It is available directly on [DuckDuckGo](https://duckduckgo.com), [duck.ai](https://duck.ai) or [DuckDuckGo onion site](https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/chat).
```suggestion
It is available directly on [DuckDuckGo](https://duckduckgo.com), [duck.ai](https://duck.ai), or [DuckDuckGo onion site](https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/chat).
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +![Brave Logo](assets/img/ai-chat/leo.svg){align=right}
```suggestion
![Brave Logo](assets/img/ai-chat/leo.svg){ align="right" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-info-16:](https://github.com/brave/brave-browser/wiki/Brave-Leo){ .card-link title=Documentation}
```suggestion
[:octicons-info-16:](https://github.com/brave/brave-browser/wiki/Brave-Leo){ .card-link title="Documentation" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +**Running AI models locally** offer a more private and secure alternative to cloud-based solutions, as **your data never leaves your device** and is therefore never shared with third-party providers.
```suggestion
**Running AI models locally** offers a more private and secure alternative to cloud-based solutions, as **your data never leaves your device** and is therefore never shared with third-party providers. This provides peace of mind and **allows you to share sensitive information**.
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +![Kobold.cpp Logo](assets/img/ai-chat/kobold.svg){align=right}
```suggestion
![Kobold.cpp Logo](assets/img/ai-chat/kobold.svg){ align="right" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +In addition to supporting a large range of text models, Kobold.cpp also has a suports an image generators such as [Stable Diffusion](https://stability.ai/stable-image), and automatic speech recogniti
```suggestion
In addition to supporting a large range of text models, Kobold.cpp also supports image generators such as [Stable Diffusion](https://stability.ai/stable-image), and automatic speech recognition tools, such as [Whisper](https://github.com/ggerganov/whisper.cpp).
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-info-16:](https://github.com/LostRuins/koboldcpp/wiki){ .card-link title=Documentation}
```suggestion
[:octicons-info-16:](https://github.com/LostRuins/koboldcpp/wiki){ .card-link title="Documentation" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +Kobold shines best when you are looking for heavy customisation and tweaking, such as for roleplaying purposed. It allows you to modify the model temperature,the context window. It also supports crea
```suggestion
Kobold shines best when you are looking for heavy customization and tweaking, such as for roleplaying purposes. It allows you to modify the model temperature from the context window. It also supports creating a network tunnel to access AI models from other devices, such as your phone.
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +
```suggestion
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +
```suggestion
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +![Ollama Logo](assets/img/ai-chat/ollama.png){align=right}
```suggestion
![Ollama Logo](assets/img/ai-chat/ollama.png){ align="right" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +In addition to supporting a wide range of text models, Ollama also supports [LLaVA](https://github.com/haotian-liu/LLaVA) models and has *experimental* support for Meta's[Llama vision capabilities](h
```suggestion
In addition to supporting a wide range of text models, Ollama also supports [LLaVA](https://github.com/haotian-liu/LLaVA) models and has *experimental* support for Meta's [Llama vision capabilities](https://huggingface.co/blog/llama32#what-is-llama-32-vision).
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-info-16:](https://github.com/ollama/ollama){ .card-link title=Documentation}
```suggestion
[:octicons-info-16:](https://github.com/ollama/ollama){ .card-link title="Documentation" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +Ollama shines best when you are looking for an AI client that has great compatibility and ease of use. It runs on all desktop platforms and doesn't involve any manual setup, while still using inferen
```suggestion
Ollama shines best when you're looking for an AI client that has great compatibility and ease of use. It runs on all desktop platforms and doesn't involve any manual setup, while still using inference and other techniques to make outputs faster.
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +It also simplifies the process of setting up a Local AI chat setup, as it downloads the AI model you want to use automatically. For example "ollama run llama3.2" will automatically download and run t
```suggestion
It also simplifies the process of setting up a local AI chat, as it downloads the AI model you want to use automatically. For example "ollama run llama3.2" will automatically download and run the Llama 3.2 model.
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +![Llamafile Logo](assets/img/ai-chat/llamafile.svg){align=right}
```suggestion
![Llamafile Logo](assets/img/ai-chat/llamafile.svg){ align="right" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +The Mozilla-run project also supports LLaVA. However, it does not support speech recognition or image generation. Finally, it is very lightweight and compatible.
```suggestion
Llamafile is a single-file executable that allows users to run large language models locally on their own computers, without any setup involved. It is available on Linux, macOS, and Windows.

The Mozilla-run project also supports LLaVA. However, it does not support speech recognition or image generation. It's also very lightweight and compatible.
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-info-16:](https://github.com/Mozilla-Ocho/llamafile/?tab=readme-ov-file#llamafile){ .card-link title=Documentation}
```suggestion
[:octicons-info-16:](https://github.com/Mozilla-Ocho/llamafile/?tab=readme-ov-file#llamafile){ .card-link title="Documentation" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-code-16:](https://github.com/ollama/ollama){ .card-link title="Source Code"}
```suggestion
[:octicons-code-16:](https://github.com/ollama/ollama){ .card-link title="Source Code" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-lock-16:](https://github.com/Mozilla-Ocho/llamafile?tab=readme-ov-file#security){ .card-link title="Security Policy"}
```suggestion
[:octicons-lock-16:](https://github.com/Mozilla-Ocho/llamafile?tab=readme-ov-file#security){ .card-link title="Security Policy" }
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +Mozilla has only made available llamafiles for some Llama and Mistral models, while there are few third-party llamafiles available. Another issue is that Windows limits .exe files to 4GB size, and mo
```suggestion
Mozilla has only made llamafiles available for some Llama and Mistral models, while there are few third-party llamafiles available. Another issue is that Windows limits .exe files to 4GB, and most models are larger than that. To fix both of those issues, you can load external weights, as detailed [here](https://github.com/Mozilla-Ocho/llamafile?tab=readme-ov-file#using-llamafile-with-external-weights).
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +- The provider or third-parties they use must not use your chats for training
```suggestion
- The provider or third-parties they use must not use your chats for training.
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +- Must be open-source
```suggestion
- Must be open-source.
```

2024-11-10 03:44 UTC, friadev commented on docs/ai-chat.md
> +- Should be easy to download and setup, such as having a one-click install process.
```suggestion
- Should be easy to download and set up, such as having a one-click install process.
```

2024-11-10 03:44 UTC, friadev commented on docs/tools.md
> +- ![Duck AI logo](assets/img/ai-chat/duckai.png){ .twemoji loading=lazy }[Duck AI](ai-chat.md#duckduckgo-ai-chat)
```suggestion
- ![Duck AI logo](assets/img/ai-chat/duckai.png){ .twemoji loading="lazy" }[Duck AI](ai-chat.md#duckduckgo-ai-chat)
```

2024-11-10 03:44 UTC, friadev commented on docs/tools.md
> +- ![Leo AI logo](assets/img/ai-chat/leo.svg){ .twemoji loading=lazy }[Brave Leo](ai-chat.md#brave-leo)
```suggestion
- ![Leo AI logo](assets/img/ai-chat/leo.svg){ .twemoji loading="lazy" }[Brave Leo](ai-chat.md#brave-leo)
```

2024-11-10 03:44 UTC, friadev commented on docs/tools.md
> +- ![Kobold logo](assets/img/ai-chat/kobold.svg){ .twemoji loading=lazy }[Kobold.cpp](ai-chat.md#koboldcpp)
```suggestion
- ![Kobold logo](assets/img/ai-chat/kobold.svg){ .twemoji loading="lazy" }[Kobold.cpp](ai-chat.md#koboldcpp)
```

2024-11-10 03:44 UTC, friadev commented on docs/tools.md
> +- ![Llamafile logo](assets/img/ai-chat/llamafile.svg){ .twemoji loading=lazy }[Llamafile](ai-chat.md#llamafile)
```suggestion
- ![Llamafile logo](assets/img/ai-chat/llamafile.svg){ .twemoji loading="lazy" }[Llamafile](ai-chat.md#llamafile)
```

2024-11-10 03:44 UTC, friadev commented on docs/tools.md
> +- ![Ollama logo](assets/img/ai-chat/ollama.png){ .twemoji loading=lazy }[Ollama](ai-chat.md#ollama)
```suggestion
- ![Ollama logo](assets/img/ai-chat/ollama.png){ .twemoji loading="lazy" }[Ollama](ai-chat.md#ollama)
```

2024-11-10 03:44 UTC, friadev commented on includes/abbreviations.en.txt
>  *[ATA]: Advanced Technology Attachment
```suggestion
*[ADB]: Android Debug Bridge
*[AI]: Artificial Intelligence
*[AOSP]: Android Open Source Project
*[ATA]: Advanced Technology Attachment
```

2024-11-10 03:44 UTC, friadev commented on includes/abbreviations.en.txt
> +*[rate limits]:Rate limits are restrictions that a service imposes on the number of times a user can access their services within a specified period of time.
```suggestion
*[rate limits]: Rate limits are restrictions that a service imposes on the number of times a user can access their services within a specified period of time.
```

2024-11-10 23:18 UTC, I-I-IT commented
Thanks @friadev for suggestions. I implemented most of them, and commented for those I don't think are needed. BTW, I also added a table to quickly glance at the different AI chats.

2024-11-10 23:27 UTC, friadev commented on docs/ai-chat.md
> +Kobold shines best when you are looking for heavy customisation and tweaking, such as for roleplaying purposed. It allows you to modify parameters such as the AI model temperature and the AI chat's s
```suggestion
Kobold shines best when you are looking for heavy customization and tweaking, such as for roleplaying purposes. It allows you to modify parameters such as the AI model temperature and the AI chat's system prompt. It also supports creating a network tunnel to access AI models from other devices, such as your phone.
```

2024-11-11 05:10 UTC, friadev requested changes

2024-11-11 05:10 UTC, friadev commented on docs/tools.md
> +
```suggestion
```

2024-11-12 00:40 UTC, friadev requested changes

2024-11-12 00:40 UTC, friadev commented on includes/abbreviations.en.txt
> +*[open-weights]: An open weights model is an AI model that anyone can download and use, but for which the underlying training data and/or algorithms are proprietary.
```suggestion
*[open-weights]: An open weights-model is an AI model that anyone can download and use, but for which the underlying training data and/or algorithms are proprietary.
```

2024-11-12 00:50 UTC, jonaharagon requested changes

2024-11-12 00:50 UTC, jonaharagon commented on theme/assets/img/cover/ai-chatbots.webp
Where is this image from? We need a source link and licensing information to publish it.

2024-11-12 03:49 UTC, friadev commented
It's from unsplash: https://unsplash.com/photos/a-white-robot-with-blue-eyes-and-a-laptop--0xMiYQmk8g

2024-11-12 04:53 UTC, jonaharagon requested changes

2024-11-12 04:53 UTC, jonaharagon commented on theme/assets/img/ai-chat/ollama.svg
This isn't an actual SVG image, it appears to be a PNG embedded in an SVG file. This is not going to be well compatible with browsers (and is also just bad), so we need to replace it with the official https://ollama.com/public/ollama.png, or find a real vector file, or make our own (which I think @dngray has done before and knows how to do?)

2024-11-12 05:23 UTC, jonaharagon commented
Thanks for the PR @I-I-IT! These changes are now going to be tracked separately here:

- #2810 
- #2811

2024-11-12 05:23 UTC, closed without merging