Remove mention of ProtonVPN Linux clients not having 2FA
privacyguides/privacyguides.org pull request #2539
Opened 2024-04-15 10:10 UTC by jordan-warne

Changes proposed in this PR:

- Remove mention of ProtonVPN Linux clients not having 2FA

They have released a new Linux client which supports 2FA using TOTP.

https://protonvpn.com/blog/vpn-linux-app/

- [x] I have disclosed any relevant conflicts of interest in my post.
- [x] I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
- [x] I am the sole author of this work. 
- [x] I agree to the [Community Code of Conduct](https://www.privacyguides.org/coc).

2024-04-15 15:13 UTC, redoomed1 requested changes
The [same section under the IVPN recommendation](https://www.privacyguides.org/en/vpn/#additional-notes_1) mentions the IVPN clients supporting 2FA, so I think removing just the "except Linux at the moment" part is preferable.

2024-04-15 18:08 UTC, jonaharagon commented on docs/vpn.md
> +Proton VPN has their own servers and datacenters in Switzerland, Iceland and Sweden. They offer content blocking and known-malware blocking with their DNS service. Additionally, Proton VPN also offer
```suggestion
Proton VPN clients support two factor authentication on all platforms. Proton VPN has their own servers and datacenters in Switzerland, Iceland and Sweden. They offer content blocking and known-malware blocking with their DNS service. Additionally, Proton VPN also offers "Tor" servers allowing you to easily connect to onion sites, but we still strongly recommend using [the official Tor Browser](tor.md#tor-browser) for this purpose.
```

2024-04-15 18:09 UTC, jonaharagon commented on docs/vpn.md
>  #### :material-alert-outline:{ .pg-orange } Additional Notes
```suggestion
#### :material-information-outline:{ .pg-blue } Additional Notes
```

I suppose this would also no longer be a warning

2024-04-15 18:10 UTC, jonaharagon approved these changes
Epic, thanks! - @all-contributors add @jordan-warne for doc

2024-04-16 06:54 UTC, dngray approved these changes

2024-04-16 07:09 UTC, merged