Update vpn.md
privacyguides/privacyguides.org pull request #2563
Opened 2024-05-07 09:58 UTC by akosnikhazy

mention of prepaid cards at Mullvad

Changes proposed in this PR:

-

<summary>

- [ ] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-05-10 11:03 UTC, rollsicecream requested changes

2024-05-10 11:03 UTC, rollsicecream commented on docs/vpn.md
> +Mullvad, in addition to accepting credit/debit cards and PayPal, accepts Bitcoin, Bitcoin Cash, **Monero** and **cash/local currency** as anonymous forms of payment, prepaid card with redeem code are
```suggestion
Mullvad, in addition to accepting credit/debit cards and PayPal, accepts Bitcoin, Bitcoin Cash, **Monero** and **cash/local currency** as anonymous forms of payment, prepaid card with redeem codes are also available. They also accept Swish and bank wire transfers.
```
Aside of that, looks good to me.

2024-05-12 13:41 UTC, WayTooWill commented on docs/vpn.md
> +Mullvad, in addition to accepting credit/debit cards and PayPal, accepts Bitcoin, Bitcoin Cash, **Monero** and **cash/local currency** as anonymous forms of payment, prepaid card with redeem code are
Could just be me but there may also need to be a change from "prepaid card" to prepaid cards".

2024-05-12 13:42 UTC, WayTooWill reviewed
Could just be me but there may also need to be a change from "prepaid card" to prepaid cards".

2024-05-12 16:08 UTC, rollsicecream commented
> Could just be me but there may also need to be a change from "prepaid card" to prepaid cards".

Yeah, you're right, I just updated my changes to reflect that :+1:

2024-05-13 12:08 UTC, dngray approved these changes

2024-05-13 12:08 UTC, merged