warning for yubikey MFA for Windows
privacyguides/privacyguides.org pull request #2566
Opened 2024-05-08 05:28 UTC by oppressor1761

Changes proposed in this PR:

- Point out the potential risks of using third-party software to modify the operating system login process.

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-05-10 22:24 UTC, jonaharagon requested changes
Thanks for the PR!

I don't think we need to explicitly say "consider your threat model" on the site though. We could just as well say it under every single recommendation. This is kind of implied...

2024-05-13 12:01 UTC, dngray approved these changes

2024-05-22 05:46 UTC, jonaharagon requested changes

2024-05-22 05:46 UTC, jonaharagon commented on docs/basics/multi-factor-authentication.md
> +Yubico has a dedicated [Credential Provider](https://learn.microsoft.com/windows/win32/secauthn/credential-providers-in-windows) that adds Challenge-Response authentication for the username + passwor
This sentence refers to the same thing as the sentence that was removed, so this should be removed entirely if we don't want to recommend this behavior.

Adding information about Windows Hello instead could be a good alternative to add here, instead of removing this Windows section entirely, but I haven't tested a Yubikey with Windows Hello myself. Does it work for logging in in lieu of a password?

2024-05-22 05:52 UTC, jonaharagon commented
Actually, I disagree with the premise that this could lead to account compromise in the first place. The app only adds a second factor in addition to the existing username+password security. In the unlikely event that the app fails, you should not be _worse off_ than single-factor authentication.

Windows Hello would _replace_ a password I believe, which is not necessarily desirable behavior here.

2024-05-24 00:43 UTC, jonaharagon approved these changes
Sorry I double checked later and you're right. These changes LGTM now 👍

2024-05-26 14:58 UTC, closed without merging