remove broken invidious embeds
privacyguides/privacyguides.org pull request #2585
Opened 2024-05-26 18:02 UTC by kimg45

Changes proposed in this PR:

- remove broken invidious embeds and replace with YouTube links

Closes #2564 

<summary>

- [ ] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-05-27 03:32 UTC, dngray commented
We should probably investigate to see if these can be fixed first before reverting.

2024-08-02 02:39 UTC, jonaharagon approved these changes

2024-08-02 02:39 UTC, jonaharagon commented
I don't think this can be fixed long-term, following Google's changes to YouTube around July 7th.

2024-08-02 04:22 UTC, redoomed1 requested changes
I think the presentation of the YouTube links here should be consistent with the way they're presented here: https://www.privacyguides.org/en/advanced/tor-overview/#additional-resources

There are also advantages of signaling that these are YouTube videos rather than embedding them in-text:

1. Indicating the link is a YouTube link avoids surprising readers in case they don't mouse over the link for the browser tooltip or long-press on the link on mobile
2. As a corollary, it gives readers the freedom of using a YouTube frontend once they see that it's a YouTube link.

2024-08-02 04:22 UTC, redoomed1 commented on docs/basics/multi-factor-authentication.md
> +This [presentation](https://youtu.be/aMo4ZlWznao) discusses the history of password authentication, the pitfalls (such as password reuse), and discussion of FIDO2 and [WebAuthn](https://webauthn.guid
```suggestion
This presentation discusses the history of password authentication, the pitfalls (such as password reuse), and the standards for FIDO2 and [WebAuthn](https://webauthn.guide):

- [How FIDO2 and WebAuthn Stop Account Takeovers](https://youtu.be/aMo4ZlWznao) <small>(YouTube)</small>
```

2024-08-02 04:22 UTC, redoomed1 commented on docs/os/linux-overview.md
> +We don’t believe holding packages back and applying interim patches is a good idea, as it diverges from the way the developer might have intended the software to work.
```suggestion
We don’t believe holding packages back and applying interim patches is a good idea, as it diverges from the way the developer might have intended the software to work. [Richard Brown](https://rootco.de/aboutme) has a presentation about this:

- [Regular Releases are Wrong, Roll for your life](https://youtu.be/i8c0mg_mS7U) <small>(YouTube)</small>
```

2024-08-02 04:22 UTC, redoomed1 commented on docs/os/linux-overview.md
> +The Atomic update method is used for [distributions](../desktop.md#atomic-distributions) like Silverblue, Tumbleweed, and NixOS and can achieve reliability with this model. [Adam Šamalík](https://twi
```suggestion
The Atomic update method is used for [distributions](../desktop.md#atomic-distributions) like Silverblue, Tumbleweed, and NixOS and can achieve reliability with this model. [Adam Šamalík](https://twitter.com/adsamalik) provided a [presentation](https://youtu.be/-hpV5l-gJnQ) on how `rpm-ostree` works with Silverblue.

- [Let's try Fedora Silverblue — an immutable desktop OS! - Adam Šamalik](https://youtu.be/aMo4ZlWznao) <small>(YouTube)</small>
```

2024-08-02 23:04 UTC, redoomed1 approved these changes
LGTM

(Also, sorry for the [merge commit](https://github.com/privacyguides/privacyguides.org/pull/2585/commits/726a9c0c7f8a47fb4f59add4b9b7e18047113a92), I should've rebased first to avoid a merge conflict :pensive: )

2024-08-03 00:51 UTC, merged