Update information for ente Photos
privacyguides/privacyguides.org pull request #2587
Opened 2024-05-27 04:49 UTC by tedgravlin

Changes proposed in this PR:

- Change the name from 'ente' to 'ente Photos' to better reflect the difference from other ente products
- Update the free tier storage info from 1GB to 5GB [[Source]](https://mstdn.social/@ente/112428405587772437)

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-05-27 05:00 UTC, jonaharagon requested changes
While we're at it, let's capitalize the E in Ente for consistency, and do the same for Ente Auth on the MFA page as well. 

They seem to use a capital E everywhere besides their logo (I don't remember if that's always been the case or if that's new), and even ignoring their preference, I think we should capitalize the first word of a sentence in all cases anyways, just as a part of our own style guide.

2024-05-27 05:12 UTC, tedgravlin commented
> While we're at it, let's capitalize the E in Ente for consistency, and do the same for Ente Auth on the MFA page as well.

Done :)

> They seem to use a capital E everywhere besides their logo

Their [press kit ](https://github.com/privacyguides/privacyguides.org/pull/2587) recommends styling their products as 'Ente Photos' but still shows a banner where it's styled as 'ente Photos'. That's why I initially left the original styling, but this makes a lot more sense! Having 'Ente' capitalized certainly looks much better on the site. Thanks!

2024-05-27 05:30 UTC, jonaharagon approved these changes
Sweet, thanks for the PR and the quick change! LGTM

2024-05-28 04:50 UTC, dngray approved these changes

2024-05-28 04:51 UTC, merged