Create new "Hardware" section
privacyguides/privacyguides.org pull request #2594
Opened 2024-05-30 11:09 UTC by jonaharagon

Changes proposed in this PR:

-

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-05-30 14:36 UTC, redoomed1 requested changes
Aside from the suggestions below, I have another trivial suggestion not related to the content in the PR: modifying the PR title to differentiate this PR from #2268 (or vice versa).

2024-05-30 14:36 UTC, redoomed1 commented on docs/basics/passwords-overview.md
> +When using TOTP codes as [multi-factor authentication](../multi-factor-authentication.md), the best security practice is to keep your TOTP codes in a [separate app](../multi-factor-authentication.md)
```suggestion
When using [TOTP codes as multi-factor authentication](multi-factor-authentication.md#time-based-one-time-password-totp), the best security practice is to keep your TOTP codes in a [separate app](../multi-factor-authentication.md).
```

2024-05-30 14:36 UTC, redoomed1 commented on docs/multi-factor-authentication.md
> +[Hardware security key recommendations](security-keys.md) have been moved to their own category here.
```suggestion
[Hardware security key recommendations](security-keys.md) have been moved to their own category.
```

2024-05-30 14:43 UTC, redoomed1 commented
Also, thoughts on moving the Google Pixel recommendation to this new section (in a different page, of course)? It is currently housed in a section titled ["Android Devices"](https://www.privacyguides.org/en/android/#android-devices), and there is already [separate criteria for Android devices](https://www.privacyguides.org/en/android/#devices). (This change would happen in a separate PR and require that this PR be merged first.)

2024-05-30 18:22 UTC, kimg45 commented
> Also, thoughts on moving the Google Pixel recommendation to this new section (in a different page, of course)? It is currently housed in a section titled ["Android Devices"](https://www.privacyguides.org/en/android/#android-devices), and there is already [separate criteria for Android devices](https://www.privacyguides.org/en/android/#devices). (This change would happen in a separate PR and require that this PR be merged first.)

Yes that would be awesome

2024-05-30 23:29 UTC, jonaharagon commented
I think that this PR will be merged before #2268 so _that one_ will have to be refactored and renamed, but I'll do that after this one is merged.

I think a Mobile Phone page in this new section is a good idea.

2024-05-31 07:49 UTC, dngray approved these changes

2024-05-31 07:50 UTC, dngray commented
> I think that this PR will be merged before #2268 so _that one_ will have to be refactored and renamed, but I'll do that after this one is merged.

Certainly, this change makes a lot of sense.

2024-05-31 13:22 UTC, redoomed1 approved these changes
LGTM. Merging this PR also closes #2551.

2024-06-01 05:52 UTC, merged