update: Add commit messages meta page
privacyguides/privacyguides.org pull request #2604
Opened 2024-06-02 03:32 UTC by dngray

Changes proposed in this PR:

-

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-06-02 11:58 UTC, jonaharagon approved these changes
I wonder if we can find some GitHub workflow to enforce conventional commit names 🤔

2024-06-02 12:18 UTC, rollsicecream approved these changes
LGTM

2024-06-02 17:16 UTC, redoomed1 requested changes

2024-06-02 17:16 UTC, redoomed1 commented on docs/meta/commit-messages.md
> +This example is for a software removal (but could be used for an addition), you may elaborate why it was removed in the commit paragraph below. It can also be used for any new pages that were added.
```suggestion
This example is for a removal of an item (but could also be used for an addition); you may elaborate why it was removed in the commit paragraph below. It can also be used for the addition of any new pages.
```
This change might not be needed, but I think that "software" should be removed from the sentence to make this commit recommendation a more general one. After all, there was recent discussion on the forum about removing Nitrokey.

2024-06-02 17:16 UTC, redoomed1 commented on docs/meta/commit-messages.md
> +For new features or enhancements to the site, e.g. where we've used the `enhancements` label it may be appropriate to signify these with:
```suggestion
For new features or enhancements to the site, e.g. things that have the `enhancements` label on GitHub, it may be appropriate to signify these with:
```
This changes the wording so that it is consistent with the "Commit message with correct" tip.

2024-06-03 04:05 UTC, dngray reviewed
Agreed LGTM.

2024-06-03 04:08 UTC, merged