fix: Opening on Windows page
privacyguides/privacyguides.org pull request #2606
Opened 2024-06-02 08:50 UTC by dngray

Changes proposed in this PR:

-

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-06-02 10:21 UTC, dngray commented on docs/os/windows/index.md
> -If you have the choice between Windows 10 and Windows 11, we would recommend using Windows 10 for as long as possible. Windows 10 will be supported until October 2025. However, no current version of
I don't really want to add that, because it will age. 2025 is not too long away.

2024-06-02 10:23 UTC, dngray commented on docs/os/windows/index.md
> +Microsoft Windows, particularly those aimed at consumers like the **Home** edition often don't prioritize privacy friendly features [by default](https://www.theguardian.com/technology/2015/jul/31/win
Not sure how I feel about linking to news articles if we can avoid that it would be good.

2024-06-02 10:26 UTC, dngray reviewed
Added a few comments for discussion

2024-06-02 11:18 UTC, rollsicecream requested changes
Some fixes here and there.

2024-06-02 11:18 UTC, rollsicecream commented on docs/os/windows/index.md
> +**Microsoft Windows** is common OS shipped with many PCs by default. With the below guides we am to provide some ways to improve improve privacy and reduce the default telemetry and data stored that
```suggestion
**Microsoft Windows** is a common OS shipped with many PCs by default. With the below guides we aim to provide some ways to improve privacy and reduce the default telemetry and data stored that is present by disabling some not-so necessary features. Microsoft over time, adds features to the OS which can sometimes rely on cloud-based services. These features will often require various usage activity. Sometimes this activity is sent to remote servers for processing.
```

2024-06-02 11:18 UTC, rollsicecream commented on docs/os/windows/index.md
> +One of the newest features called **Recall**, a part of the Copilot AI feature set. Recall aims to screenshot anything you've seen on your PC in order to show it to you at a later date. A lot of thes
```suggestion
One of the newest features called **Recall**, a part of the Copilot AI feature set, aims to screenshot anything you've seen on your PC in order to show it to you at a later date. A lot of these "helpful" features create considerable metadata which can be forensically analyzed. In most cases browsing history is going to be sufficient and this feature can be safely disabled.
```

2024-06-02 11:18 UTC, rollsicecream commented on docs/os/windows/index.md
> +One of the main concerns with Recall is that the data is stored in a local database that is decrypted when your device is powered on, meaning it is an easy target for hackers should the device ever b
```suggestion
One of the main concerns with Recall is that the data is stored in a local database that is decrypted when your device is powered on, meaning it is an easy target for hackers if the device ever become infected with malware. Recall will not redact sensitive information like copied passwords or financial information from the database, but it does protect against making screenshots of any copyrighted content protected by digital rights management (DRM) systems. Unfortunately, this feature was added without too much thought about the privacy implications of having such a feature enabled by default.
```

2024-06-02 11:18 UTC, rollsicecream commented on docs/os/windows/index.md
>  It is not recommended to use forks or modified versions of Windows such as Windows AME. Since modified versions of Windows like Windows AME don't receive updates, security features and antivirus defi
```suggestion
It is not recommended to use forks or modified versions of Windows such as Windows AME. Since modified versions of Windows like Windows AME don't receive updates, security features and antivirus definitions in Windows Defender will fall behind the current threat landscape, opening you up to attacks, thus making you even less secure.
```

2024-06-02 11:57 UTC, jonaharagon requested changes
Going to give this some thought. I don't think these changes capture the original intent of the Windows guides being added though, and omit some key details. This almost reads as if Windows is recommended.

2024-06-02 12:52 UTC, dngray commented
> This almost reads as if Windows is recommended, which I don't think is our goal.

I don't think it does that at all, it tones down the language a bit and brings it more in line with the other content. The main thing people will care about is the guides that we actually provide (which are currently marked as "coming soon").

2024-06-03 04:45 UTC, kekkoudesu commented on docs/os/windows/index.md
> +One of the main concerns with Recall is that the data is stored in a local database that is decrypted when your device is powered on, meaning it is an easy target for hackers if the device ever becom
> meaning it is an easy target for hackers if the device ever become infected with malware.

Typo—it should say `becomes`.

2024-06-03 04:57 UTC, redoomed1 requested changes

2024-06-03 04:57 UTC, redoomed1 commented on docs/os/windows/index.md
> +**Microsoft Windows** is a common OS shipped with many PCs by default. The following guides aim to provide some ways to improve privacy and reduce the default telemetry and data stored by disabling s
```suggestion
**Microsoft Windows** is a common OS shipped with many PCs by default. The following guides aim to provide some ways to improve privacy and reduce the default telemetry and data stored by disabling some unnecessary features. Over time, Microsoft adds features to the OS which can sometimes rely on cloud-based services. These features will often require certain types such as the [optional data](https://privacy.microsoft.com/data-collection-windows) that is sometimes sent to remote servers for processing.
```
"certain types" of what?

2024-06-03 04:57 UTC, redoomed1 commented on docs/os/windows/index.md
> +One of the main concerns with Recall is that the data is stored in a local database that is decrypted when your device is powered on, meaning it is an easy target for hackers if the device ever becom
```suggestion
One of the main concerns with Recall is that the data is stored in a local database that is decrypted when your device is powered on, meaning it is an easy target for hackers if the device ever becomes infected with malware. Recall will not redact sensitive information like copied passwords or financial information from the database, but it does protect against making screenshots of any copyrighted content protected by digital rights management (DRM) systems. Unfortunately, this feature was added without too much thought about the privacy implications of having such a feature enabled by default.
```

2024-06-03 04:57 UTC, redoomed1 commented on docs/os/windows/index.md
> +## Privacy History
```suggestion
## Privacy Notes
```
I'm proposing a heading change to make it consistent with the same intro heading as the [MacOS Overview](https://www.privacyguides.org/en/os/macos-overview/#privacy-notes), and there is not that much history with the changed text (in green on the GitHub web editor).

2024-06-03 04:57 UTC, redoomed1 commented on docs/os/windows/index.md
> +- Making the default browser always default to Edge, or switch back to Edge.
```suggestion
- Setting the default browser always to Edge, or reverting to Edge if it's changed.
```

2024-06-03 04:57 UTC, redoomed1 commented on docs/os/windows/index.md
> +Microsoft often uses the automatic updates feature to add new functionality to your device and make changes that collect your data and is enabled by default. Some [privacy features](https://blogs.win
```suggestion
Microsoft often uses the automatic updates feature to add new functionality to your device and make changes that collect your data and are enabled by default. Some [privacy features](https://blogs.windows.com/windows-insider/2023/11/16/previewing-changes-in-windows-to-comply-with-the-digital-markets-act-in-the-european-economic-area) such as the option to *opt out* of syncing an online Microsoft account with Windows, require you to select a country in the EEA (European Economic Area) during installation. It can be changed to your real country after Windows is installed.
```

2024-06-03 04:57 UTC, redoomed1 commented on docs/os/windows/index.md
> +Students and teachers may be able to obtain a Windows **Education** (equivalent to Enterprise) or **Pro Education** edition (equivalent to Pro) for free (including on personal devices) from their edu
```suggestion
Students and teachers may be able to obtain a Windows **Education** (equivalent to Enterprise) or **Pro Education** license (equivalent to Pro) for free, including on personal devices, from their educational institution. Many schools partner with Microsoft via OnTheHub or Microsoft Azure for Education, so you can check those sites or your school's benefits page to see if you qualify. Whether or not you are able to get these licenses depends entirely on your institution. This may be the best way for many people to obtain an Enterprise-level edition of Windows for personal use. There are no additional privacy or security risks associated with using an Education license compared to the retail versions.
```

2024-06-03 04:57 UTC, redoomed1 commented on docs/os/windows/index.md
> +- Unnecessarily storing sensitive data. Even data which is stored locally and not sent to Microsoft is still a target for hackers or malware on your device.
I think that the "dark patterns" term introduced in this PR can be integrated here, but I'll leave that choice to the author.

2024-06-04 03:35 UTC, dngray commented on docs/os/windows/index.md
> +**Microsoft Windows** is a common OS shipped with many PCs by default. The following guides aim to provide some ways to improve privacy and reduce the default telemetry and data stored by disabling s
That one should be *certain types of optional data*.

2024-06-04 03:36 UTC, dngray commented on docs/os/windows/index.md
> +- Unnecessarily storing sensitive data. Even data which is stored locally and not sent to Microsoft is still a target for hackers or malware on your device.
It was intended to be used there but, I reworded something and we didn't end up using it.

2024-06-04 03:44 UTC, dngray commented on docs/os/windows/index.md
> +One of the main concerns with Recall is that the data is stored in a local database that is decrypted when your device is powered on, meaning it is an easy target for hackers if the device ever becom
Done

2024-07-13 13:28 UTC, rollsicecream requested changes

2024-07-13 13:28 UTC, rollsicecream commented on docs/security-keys.md
> +The Yubikey 5 series has FIDO Level 1 certification, which is the most common. However, some governments or other organizations may require a key with Level 2 certification, in which case you'll have
```suggestion
The Yubikey 5 series has the FIDO Level 1 certification, which is the most common. However, some governments or other organizations may require a key with Level 2 certification, in which case you'll have to purchase a [Yubikey 5 **FIPS** series](https://www.yubico.com/products/yubikey-fips) key, or a [Yubico Security Key](#yubico-security-key). Most people do not have to worry about this distinction.
```

2024-07-13 13:28 UTC, rollsicecream commented on docs/os/windows/index.md
> +The official [Media Creation tool](https://microsoft.com/software-download/windows10) is the best way to put a Windows installer on a USB flash drive. Third-party tools like Rufus or Etcher may unexp
I modified the Media Creation Tool link from Windows 10's ISO to Windows 11's ISO page, as W10 is going to be EOL pretty soon.

```suggestion
The official [Media Creation Tool](https://microsoft.com/software-download/windows11) is the best way to put a Windows installer on a USB flash drive. Third-party tools like Rufus or Etcher may unexpectedly modify the files, which could lead to boot issues or other troubles when installing.
```

2024-07-13 13:28 UTC, rollsicecream commented on docs/os/windows/index.md
> +If you are installing an **Education** license then you will typically have a private download that will be provided alongside your license key when you obtain it from your institution's benefits por
```suggestion
If you are installing an **Education** license then you will typically have a private download link that will be provided alongside your license key when you obtain it from your institution's benefits portal.
```

2024-07-14 17:35 UTC, dngray reviewed
Minor changes

2024-07-14 17:40 UTC, dngray commented on docs/os/windows/index.md
> +The official [Media Creation tool](https://microsoft.com/software-download/windows10) is the best way to put a Windows installer on a USB flash drive. Third-party tools like Rufus or Etcher may unexp
Certainly.

2024-07-14 18:22 UTC, redoomed1 requested changes

2024-07-14 18:22 UTC, redoomed1 commented on docs/os/windows/index.md
> +Unfortunately, this feature was added without too much thought about the privacy implications of having such a feature enabled by default (which it now [no longer is](https://wired.com/story/microsof
```suggestion
Unfortunately, this feature was added without too much thought about the privacy implications of having such a feature enabled by default (which it now [no longer is](https://wired.com/story/microsoft-recall-off-default-security-concerns)). It is not an isolated example, however; another one was Microsoft automatically [enabling folder backups to OneDrive](https://neowin.net/news/windows-11-is-now-automatically-enabling-onedrive-folder-backup-without-asking-permission) on new Windows 11 installations without asking for permission.
```

2024-07-20 20:31 UTC, jonaharagon requested changes
Looks good, just some minor suggestions mostly around wording and breaking large paragraphs into smaller ones for readability.

2024-07-20 20:31 UTC, jonaharagon commented on docs/os/windows/index.md
> +Microsoft Windows, particularly those versions aimed at consumers like the **Home** version often don't prioritize privacy friendly features by [default](https://www.theguardian.com/technology/2015/j
```suggestion
Especially since Windows 8, Microsoft Windows often includes privacy-unfriendly features by [default](https://www.theguardian.com/technology/2015/jul/31/windows-10-microsoft-faces-criticism-over-privacy-default-settings). As a result we often see more [data collection](https://en.wikipedia.org/wiki/Criticism_of_Microsoft#Telemetry_and_data_collection) than necessary, without any real warnings that this is the default behavior.

For example, in an attempt to compete with Google in the advertising space, [Cortana](https://en.wikipedia.org/wiki/Cortana_(virtual_assistant)) has included unique identifiers such as an "advertising ID" in order to correlate usage and assist advertisers in targeted advertising. At launch, telemetry could not be disabled in non-enterprise editions of Windows 10. It still cannot be disabled, but Microsoft added the ability to [reduce](https://www.extremetech.com/computing/243079-upcoming-windows-update-reduces-spying-microsoft-still-mum-data-collects) the data that is sent to them.
```

The _defaults_ for non-Home editions are not any better, so it isn't limited there.

2024-07-20 20:31 UTC, jonaharagon commented on docs/os/windows/index.md
> +Microsoft often uses the automatic updates feature to add new functionality to your device and make changes that collect your data and are enabled by default. Some [privacy features](https://blogs.wi
I have not seen evidence from anyone outside the EEA that this actually works, and haven't been able to reproduce it myself.

2024-07-20 20:31 UTC, jonaharagon commented on docs/os/windows/index.md
> +The best version available for *retail* purchase is Windows **Pro** as it has nearly all of the features you'll want to use to secure your device, including Bitlocker, Hyper-V, etc. The only thing mi
```suggestion
The best version available for *retail* purchase is Windows **Pro** as it has nearly all of the features you'll want to use to secure your device, including Bitlocker, Hyper-V, etc. However, this version does not allow you to set some of the most restrictive limitations on Microsoft's telemetry.
```

2024-07-20 20:31 UTC, jonaharagon commented on docs/os/windows/index.md
> +Students and teachers may be able to obtain a Windows **Education** (equivalent to Enterprise) or **Pro Education** license (equivalent to Pro) for free, including on personal devices, from their edu
```suggestion
Students and teachers may be able to obtain a Windows **Education** (equivalent to Enterprise) or **Pro Education** license (equivalent to Pro) for free, including for use on personal devices, from their educational institution. Many schools partner with Microsoft via OnTheHub or Microsoft Azure for Education, so you can check those sites or your school's benefits page to see if you qualify. Whether or not you are able to get these licenses depends entirely on your institution. This may be the best way for many people to obtain an Enterprise-level edition of Windows for personal use. There are no additional privacy or security risks associated with using an Education license compared to the retail versions.
```

2024-07-20 20:31 UTC, jonaharagon commented on docs/os/windows/index.md
> +It is not recommended to use third party modified versions of Windows such as Windows AME. Since modified versions of Windows like Windows AME don't receive updates, security features and antivirus d
```suggestion
It is not recommended to use third party modified versions of Windows such as Windows AME. Since modified versions of Windows like Windows AME don't receive updates, security features and antivirus definitions in Windows Defender will fall behind the current threat landscape, which lowers your security by opening you up to more attacks.
```
too many commas

2024-07-20 20:31 UTC, jonaharagon commented on docs/os/index.md
```suggestion
We publish configuration guides for the major operating systems, because you can generally improve the amount of data that is collected about you on any option, especially if you use privacy tools like our [recommended web browsers](../desktop-browsers.md) in place of native tools where appropriate. However, some operating systems will be more privacy-respecting inherently, and it will be much harder to achieve an equivalent level of privacy on other choices.

- [Recommended Linux Distros :material-arrow-right-drop-circle:](../desktop.md)
- [Recommended Android Distros :material-arrow-right-drop-circle:](../android.md)
```

For various reasons I want to use internal links frequently, mainly to make navigation easier since our OS recommendations are in an entirely different section (i.e. 2 clicks away, which can be reduced to 1 since it is pertinent for readers of this page).

2024-07-20 20:31 UTC, jonaharagon commented on docs/os/windows/index.md
> +One of the newest examples was called **Recall**, a part of the Copilot AI feature set. Recall periodically screenshots anything you've seen on your PC in order to show it to you at a later date. The
```suggestion
One of the newest examples was called **Recall**, a part of the Copilot AI feature set. Recall periodically screenshots anything you've seen on your PC in order to show it to you at a later date. These "helpful" features create considerable metadata which can be forensically analyzed. In most cases browsing history is sufficient and this feature can be safely disabled.

The main concerns with Recall was that the data is stored in a local database that is decrypted when your device is powered on, meaning it is an easy target for hackers if the device ever becomes infected with malware. Recall will not redact sensitive information like copied passwords or financial information from the database, but it does protect against making screenshots of any copyrighted content protected by digital rights management (DRM) systems.
```

2024-07-20 20:34 UTC, jonaharagon commented on docs/os/windows/index.md
> +Microsoft often uses the automatic updates feature to add new functionality to your device and make changes that collect your data and are enabled by default. Some [privacy features](https://blogs.wi
```suggestion
Microsoft often uses the automatic updates feature to add new functionality to your device and make changes that collect your data and are enabled by default. Some [privacy features](https://blogs.windows.com/windows-insider/2023/11/16/previewing-changes-in-windows-to-comply-with-the-digital-markets-act-in-the-european-economic-area) such as the option to *opt out* of syncing an online Microsoft account with Windows, are only available to users in the EEA (European Economic Area).
```

Unless anyone can prove this works I'd be okay with this change and just leaving it for the user to figure out themselves.

2024-07-24 14:44 UTC, dngray reviewed
Those changes look good to me.

2024-07-24 14:45 UTC, dngray commented on docs/os/windows/index.md
> +Microsoft often uses the automatic updates feature to add new functionality to your device and make changes that collect your data and are enabled by default. Some [privacy features](https://blogs.wi
That's fair, this was a discussion on Matrix and I haven't verified that myself.

2024-07-24 15:52 UTC, jonaharagon approved these changes

2024-07-25 07:09 UTC, merged

2024-07-29 02:32 UTC, ave9858 commented
I still don't think "The official [Media Creation Tool](https://microsoft.com/software-download/windows11) is the best way to put a Windows installer on a USB flash drive. Third-party tools like Rufus or Etcher may unexpectedly modify the files, which could lead to boot issues or other troubles when installing." is accurate. Etcher doesn't even work for Windows ISOs because it only copies raw data, and rufus won't make any modifications that the user doesn't approve of and is probably safer than using the media creation tool

2024-07-29 03:46 UTC, jonaharagon commented
> and rufus [...] is probably safer than using the media creation tool

why's this?

2024-07-29 10:37 UTC, dngray commented
<details>
  <summary>You can do it without any tools at all if you like :smile: </summary>

Assuming:
J:\ = USB stick
V:\ = Mounted ISO.

1. Open up `cmd.exe` and start `DISKPART`

   ```text
   C:\Users\user>Start DISKPART
   Microsoft DiskPart version 6.1.7601
   Copyright (C) 1999-2008 Microsoft Corporation.
   On computer: DESKTOP-PC
   DISKPART> LIST DISK
     Disk ###  Status         Size     Free     Dyn  Gpt
     --------  -------------  -------  -------  ---  ---
     Disk 0    Online          119 GB      0 B
     Disk 1    Online         2794 GB      0 B        *
     Disk 2    Online          111 GB  1024 KB
     Disk 3    Online          698 GB  1024 KB        *
     Disk 4    No Media           0 B      0 B
     Disk 5    No Media           0 B      0 B
     Disk 6    Online           29 GB      0 B
   ```

2. Select a disk

   ```text
   DISKPART> SELECT DISK 6
   Disk 6 is now the selected disk.
   ```

3. Clean disk

   ```text
   DISKPART> CLEAN
   DiskPart succeeded in cleaning the disk.
   ```

4. Create a primary partition

    ```text
    DISKPART> CREATE PARTITION PRIMARY
    DiskPart succeeded in creating the specified partition.
    ```

5. Select it

    ```text
    DISKPART> SELECT PARTITION 1
    Partition 1 is now the selected partition.
    ```

6. Make the boot portion active

    ```text
    DISKPART> ACTIVE
    DiskPart marked the current partition as active.
    ```

7. Format the disk ready for use

    ```text
    DISKPART> FORMAT FS=NTFS QUICK
      100 percent completed
    DiskPart successfully formatted the volume.
    ```

8. Set disk as active

    ```text
    DISKPART> ACTIVE
    DiskPart marked the current partition as active.
    ```

9. Run `cmd.exe` as Administrator:

10. Mount Windows .iso

11. Create a `BOOT` directory

12. Create a boot sector on `V:`

    ```text
    C:\Windows\system32>cd V:\BOOT
    C:\Windows\system32>V:
    V:\boot>BOOTSECT /NT60 J:
    Target volumes will be updated with BOOTMGR compatible bootcode.
    J: (\\?\Volume{9dffb40d-f33e-11e1-896c-abac436880d7})
        Successfully updated NTFS filesystem bootcode.
    Bootcode was successfully updated on all targeted volumes.
    ```

13. Copy files to `V:`

    ```text
    V:\boot>XCOPY V:\ J:\ /S/E
    ```
</details>

Been doing that from windows 7, 8, 10 & 11.

2024-07-29 18:38 UTC, ave9858 commented
> why's this?

Rufus can be used with ISOs download from Microsoft, which can be hashed to check integrity and also has features to guard against bad USB hardware like bad block checking and the new runtime UEFI media validation. Rufus is also FOSS and is even recommended by Microsoft in some of their documentation, gives the user more control, and has some QOL features.