update!: Split up Android recommendation page into separate pages
privacyguides/privacyguides.org pull request #2620
Opened 2024-06-20 01:44 UTC by redoomed1

Changes proposed in this PR:

- Split up Android page into separate pages and add an Android index page (full proposal [here](https://github.com/privacyguides/privacyguides.org/issues/2611))
  - The chief benefit of this change is that it would allow for more detailed entries for each section without worrying about making the Android page too long. For example, Jonah, on the forum, floated the idea of [refreshing the custom Android operating system sections](https://discuss.privacyguides.net/t/note-privacy-implications-of-grapheneos-proxy-services/18735/8) so that they provide more substantial explanations.
  - No major changes to the content ported from the original Android page
    - Updated link to AOSP source code
    - Added internal link to Google Pixel card in the description under the GrapheneOS card
    - Changed GrapheneOS docs links under the DivestOS card to more specific links
    - Changed external links to internal ones in the GrapheneOS App Store section
  - Changes for the new pages
    - Added introductions for the "Obtaining Android Apps" and "Mobile Phones" pages
    - Updated image file paths and internal links
    - Changed admonition about EOL devices from Note to Warning on the Mobile Phones page
    - Added buttons to the intro to the Mobile Phones page that point to the Custom Android OSes page and the Android Overview page
- Modify `tools.md` to reflect the above changes
- Delete original Android page

Closes #2611

## To Do
<details>
<summary>All done!</summary>

- [x] Fix images and internal links in all newly created pages
- [x] Fix internal links outside of the Android section that point to the original Android page
- [x] Add introductions for the Obtaining Android Apps page and the Mobile Phones page
- [x] Modify `tools.md` to reflect the above changes
</details>

---

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-06-21 08:51 UTC, jonaharagon requested changes
hmmmmmm interesting. Yes I think this seems like a good idea 👍

2024-06-21 08:51 UTC, jonaharagon commented on docs/android/custom-os.md
> +meta_title: "Android Recommendations: GrapheneOS and DivestOS - Privacy Guides"
```suggestion
meta_title: "The Best Android Custom ROM (Operating System) - Privacy Guides"
```

Would prefer Custom ROM here for SEO purposes.

2024-06-21 08:51 UTC, jonaharagon commented on docs/android/custom-os.md
> +title: "Custom Operating Systems"
I don't like "Custom Operating Systems" under the "Operating Systems" header in the sidebar.

```suggestion
title: "Alternative Distributions"
```

2024-06-21 08:51 UTC, jonaharagon commented on docs/android/custom-os.md
> +We recommend installing one of these custom Android operating systems on your device, listed in order of preference, depending on your device's compatibility with these operating systems.
I'm beginning to prefer Wikipedia's style where they bold the name of the page in the lead sentence, and I think we should do so as we rewrite more pages: https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Lead_section#MOS:BOLDALTNAMES

```suggestion
A custom **Android-based operating system** (often known as a **Custom ROM**) is a popular way to achieve higher levels of privacy and security on your device. This is in contrast to the "stock" version of Android which comes with your phone from the factory, and is often highly integrated with Google Play Services.

We recommend installing one of these custom Android operating systems on your device, listed in order of preference, depending on your device's compatibility with these operating systems.
```

Also generally I would like pages to have more than 1 explaining sentence if possible.

2024-06-21 08:51 UTC, jonaharagon commented on mkdocs.yml
> +              - "android/general-apps.md"
Note I am also suggesting renaming `custom-os.md` to `distributions.md` (in line with previous title suggestions) — this change might have to be made in other files too.

```suggestion
              - "android/distributions.md"
              - "android/general-apps.md"
              - "android/obtaining-apps.md"
```

(also, alphabetical ordering here)

2024-06-21 08:51 UTC, jonaharagon commented on docs/android/obtaining-apps.md
> +We recommend the following methods of obtaining applications on Android, listed in order of preference.
```suggestion
There are many ways to obtain Android apps privately, even from the Play Store, without interacting with Google Play Services. We recommend the following methods of obtaining applications on Android, listed in order of preference.
```

2024-06-21 08:51 UTC, jonaharagon commented on docs/android/custom-os.md
> +
```suggestion
```

Might as well drop this since it is outdated, and we no longer reference CalyxOS anyways, so new readers would have no idea why this comparison even mattered.

2024-06-21 15:41 UTC, redoomed1 commented on docs/mobile-phones.md
> +End-of-life devices (such as GrapheneOS's "extended support" devices) do not have full security patches (firmware updates) due to the OEM discontinuing support. These devices cannot be considered com
Thanks for your detailed review, @jonaharagon! In addition to the changes you suggested, I added another explanatory sentence to this introduction based on your feedback. What do you think of it (starting at line 22)?

Admittedly, it is somewhat redundant, as similar ideas are expressed in the admonition below it.

2024-06-24 11:56 UTC, dngray commented on docs/android/custom-os.md
> +meta_title: "Android Recommendations: GrapheneOS and DivestOS - Privacy Guides"
Yes, I think we've referred to them as custom OSes.

2024-07-08 03:29 UTC, dngray commented on docs/android/custom-os.md
> +meta_title: "Android Recommendations: GrapheneOS and DivestOS - Privacy Guides"
perhaps we could do custom OS, ROM or somehow specify both seeing as this is a metadata heading.

2024-07-13 13:40 UTC, rollsicecream requested changes

2024-07-13 13:40 UTC, rollsicecream commented on docs/android/index.md
> +The **Android Open Source Project** is an open-source mobile operating system led by Google which powers the majority of the world's mobile devices. Most phones sold with Android are modified to incl
```suggestion
The **Android Open Source Project (or AOSP)**  is an open-source mobile operating system led by Google which powers the majority of the world's mobile devices. Most phones sold with Android are modified to include invasive integrations and apps such as Google Play Services, so you can significantly improve your privacy on your mobile device by replacing your phone's default installation with a version of Android without these invasive features.
```

2024-07-13 13:40 UTC, rollsicecream commented on docs/android/obtaining-apps.md
> +==We only recommend F-Droid as a way to obtain apps which cannot be obtained via the means above.== F-Droid is often recommended as an alternative to Google Play, particularly in the privacy communit
```suggestion
==We only recommend F-Droid as a way to obtain apps which cannot be obtained via the means above.== F-Droid is often recommended as an alternative to Google Play, particularly within the privacy community. The option to add third-party repositories and not be confined to Google's walled garden has led to its popularity. F-Droid additionally has [reproducible builds](https://f-droid.org/en/docs/Reproducible_Builds) for some applications and is dedicated to free and open-source software. However, there are some security-related downsides to how F-Droid builds, signs, and delivers packages:
```

2024-07-13 13:40 UTC, rollsicecream commented on docs/android/obtaining-apps.md
> +Due to their process of building apps, apps in the official F-Droid repository often fall behind on updates. F-Droid maintainers also reuse package IDs while signing apps with their own keys, which i
```suggestion
Due to their process of building apps, apps in the *official* F-Droid repository often fall behind on updates. F-Droid maintainers also reuse package IDs while signing apps with their own keys, which is not ideal as it gives the F-Droid team ultimate trust. Additionally, the requirements for an app to be included in the official F-Droid repo are less strict than other app stores like Google Play, meaning that F-Droid tends to host a lot more apps which are older, unmaintained, or otherwise no longer meet [modern security standards](https://developer.android.com/google/play/requirements/target-sdk).
```

2024-07-14 15:34 UTC, dngray approved these changes
LGTM, thanks for this!

2024-07-14 18:10 UTC, redoomed1 commented
@jonaharagon I tried to format the schema entries (introduced in https://github.com/privacyguides/privacyguides.org/pull/2106) that are now spread across different pages; feel free to correct any of them as you see fit.

2024-07-15 17:19 UTC, rollsicecream requested changes
There's an extra exclamation mark in the title of this PR.

2024-07-15 18:04 UTC, redoomed1 commented
> extra exclamation mark

Per the [updated Git commit message guidelines](https://github.com/privacyguides/privacyguides.org/blob/main/docs/meta/commit-messages.md?plain=1#L15-L25), the addition of pages calls for the extra `!` to draw attention to major changes. In this case, the restructuring of the Android recommendations and the addition of a new Mobile Phones recommendation page.

2024-07-21 15:50 UTC, dngray approved these changes
LGTM, this does make things a bit less busy on that page.

2024-07-21 16:03 UTC, merged