feat: add information about Firefox's "privacy-preserving" ad measurement
privacyguides/privacyguides.org pull request #2632
Opened 2024-07-10 10:01 UTC by rollsicecream

Changes proposed in this PR:

- https://discuss.privacyguides.net/t/suggest-disabling-privacy-preserving-ad-measurement-on-firefox/19372/9

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-07-10 14:33 UTC, redoomed1 requested changes

2024-07-10 14:33 UTC, redoomed1 commented on docs/desktop-browsers.md
> +With the release of Firefox 128, a new setting for “privacy-preserving ad measurement” has been added and enabled by default. As we are also guiding people to disable that feature in Safari, we also
I don't think it's accurate to reference the "reasons for [disabling PPA] in Safari" here as they are not applicable to Firefox AFAIK.

---
Here's what the Safari recommendation says:

> The feature has little privacy concerns on its own, so while you can choose to leave it on, we consider the fact that it's _automatically disabled in Private Browsing_ to be an indicator for disabling the feature.[^1]

The WebKit blog post embedded in this section makes the feature's disablement in Private Browsing abundantly clear in its FAQ section:

> Is PCM enabled in Private Browsing Mode? No.

---
On the other hand, Firefox does not state something similar in its documentation on [their implementation of PPA](https://support.mozilla.org/kb/privacy-preserving-attribution). Therefore, this section **cannot** just state that the reasons for Safari are also applicable to Firefox.

[^1]: Emphasis mine

2024-07-10 14:46 UTC, rollsicecream commented on docs/desktop-browsers.md
> +With the release of Firefox 128, a new setting for “privacy-preserving ad measurement” has been added and enabled by default. As we are also guiding people to disable that feature in Safari, we also
Thanks for the correction :+1:

2024-07-10 23:43 UTC, freddy-m approved these changes
Changed the wording to match the other page but happy to revert back to what it was if @privacyguides/team would like?

2024-07-11 00:52 UTC, redoomed1 requested changes

2024-07-11 00:52 UTC, redoomed1 commented on docs/desktop-browsers.md
> +The feature has little privacy concerns on its own, so while you can choose to leave it on, we consider the fact that it's automatically disabled in Private Browsing to be an indicator for disabling
```suggestion
With the release of Firefox 128, a new setting for [Privacy-Preserving Attribution](https://support.mozilla.org/kb/privacy-preserving-attribution) (PPA) has been added and enabled by default. Ad click measurement has traditionally used tracking technology that infringes on user privacy. PPA is a feature and proposed web standard aimed towards allowing advertisers to measure the effectiveness of web campaigns without compromising on user privacy.

The feature has little privacy concerns on its own, so while you can choose to leave it on, we consider the fact that this user-facing setting is disabled in Arkenfox to be an indicator for disabling the feature.
```
As I mentioned in a previous [comment](https://github.com/privacyguides/privacyguides.org/pull/2632#discussion_r1672402509), this setting isn't disabled in Firefox private windows.

Also, asserting that the feature being disabled in _(mobile) Safari_ Private Browsing informs the recommendation for _desktop Firefox_—if this is what this sentence is saying—is in my opinion tenuous. I think that using Arkenfox as an indicator for disabling the feature would be more relevant in this case. Arkenfox disabled this setting in this [commit](https://github.com/arkenfox/user.js/pull/1862/commits/7c1d549de11f54c9231cdfeece678927bb28a8f5#diff-417e8f625f16252f8ace3b0791d24c9b073d7394e9216c7b5d14a516d2572277R194-R197).

---
PPA is described as a proposed standard [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1900929#c0).

2024-07-11 22:18 UTC, blacklight447 approved these changes

2024-07-13 12:22 UTC, rollsicecream commented on docs/desktop-browsers.md
> +The feature has little privacy concerns on its own, so while you can choose to leave it on, we consider the fact that it's automatically disabled in Private Browsing to be an indicator for disabling
Thank you again for your suggestions!

2024-07-14 07:34 UTC, nopeitsnothing commented
Is this abandoned?

2024-07-14 10:00 UTC, rollsicecream commented
> Is this abandoned?

This PR? No.

2024-07-14 14:59 UTC, jonaharagon requested changes
As written this reads as if PPA is indeed privacy-preserving, which is not the impression I think we should give.

2024-07-14 14:59 UTC, jonaharagon commented on docs/desktop-browsers.md
> +
Not really true, because PPA is not private by technical design, it is private by social measures. Your data is not sent to advertisers, but **is** sent to Mozilla/ISRG.

> Our DAP deployment is jointly run by Mozilla and ISRG. Privacy is lost if the two organizations collude

I have **drafted** a blog post regarding this feature: https://blog.privacyguides.org/p/eea2d508-2249-4df7-855f-4e6ac6b2db85/

```suggestion
With the release of Firefox 128, a new setting for [privacy-preserving attribution](https://support.mozilla.org/kb/privacy-preserving-attribution) (PPA) has been added and [enabled by default](https://blog.privacyguides.org/p/eea2d508-2249-4df7-855f-4e6ac6b2db85/). PPA allows advertisers to use your web browser to measure the effectiveness of web campaigns, instead of using traditional website tracking code. We consider this behavior to be outside the scope of a user agent's responsibilities, and the fact that it is disabled by default in Arkenfox is an additional indicator for disabling this feature.

```

2024-07-14 15:20 UTC, dngray approved these changes

2024-07-14 15:22 UTC, dngray requested changes

2024-07-14 15:22 UTC, dngray commented on docs/desktop-browsers.md
> +With the release of Firefox 128, a new setting for [privacy-preserving attribution](https://support.mozilla.org/kb/privacy-preserving-attribution) (PPA) has been added and [enabled by default](https:
I think we should replace this with the final version of the blog post.

2024-07-14 15:45 UTC, jonaharagon approved these changes

2024-07-14 16:59 UTC, jonaharagon commented on docs/desktop-browsers.md
> +With the release of Firefox 128, a new setting for [privacy-preserving attribution](https://support.mozilla.org/kb/privacy-preserving-attribution) (PPA) has been added and [enabled by default](https:
It does redirect FWIW, but...

```suggestion
With the release of Firefox 128, a new setting for [privacy-preserving attribution](https://support.mozilla.org/kb/privacy-preserving-attribution) (PPA) has been added and [enabled by default](https://blog.privacyguides.org/2024/07/14/mozilla-disappoints-us-yet-again-2/). PPA allows advertisers to use your web browser to measure the effectiveness of web campaigns, instead of using traditional JavaScript-based tracking. We consider this behavior to be outside the scope of a user agent's responsibilities, and the fact that it is disabled by default in Arkenfox is an additional indicator for disabling this feature.
```

2024-07-14 17:41 UTC, dngray approved these changes

2024-07-15 04:34 UTC, merged