update: Update Privacy.com and Coincards description
privacyguides/privacyguides.org pull request #2643
Opened 2024-07-16 04:31 UTC by redoomed1

Changes proposed in this PR:

- Update the description of Privacy.com's paid plans in light of the recent introduction of a new paid plan: https://privacy.com/blog/introducing-privacy-plus-plan
  - Cashback isn't available in this new plan, so I deleted the mention of it altogether
- Coincards
  - Remove the information about country availability in the card description (as the service is available in countries other than U.S. and Canada now) and replace it with a sentence that directs readers to the service's homepage which provides this information at a glance
  - Change all instances of "CoinCards" to "Coincards" based on how the service stylizes its name across their website
- Make minor grammar changes otherwise not noted above

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-07-16 10:38 UTC, rollsicecream requested changes

2024-07-16 10:38 UTC, rollsicecream commented on docs/financial-services.md
> +**Privacy.com**'s free plan allows you to create up to 12 virtual cards per month, set spend limits on those cards, and shut off cards instantly. Their paid plans provide higher limits to the number
I think it will be better to use "on" instead of "to". 

```suggestion
**Privacy.com**'s free plan allows you to create up to 12 virtual cards per month, set spend limits on those cards, and shut off cards instantly. Their paid plans provide higher limits on the number of cards that can be created each month and the option to hide transaction information from your bank.
```

2024-07-16 10:38 UTC, rollsicecream commented on docs/financial-services.md
> +**Coincards** allows you to purchase gift cards for a large variety of merchants. Their homepage has a complete listing of the various countries where their service is available.
```suggestion
**Coincards** allows you to purchase gift cards from a large variety of merchants. Their homepage has a complete listing of the various countries where their service is available.
```

2024-07-16 10:38 UTC, rollsicecream commented on docs/financial-services.md
>  These services allow you to purchase gift cards for a variety of merchants online with [cryptocurrency](cryptocurrency.md). Some of these services offer ID verification options for higher limits, but
```suggestion
These services allow you to purchase gift cards from a variety of merchants online with [cryptocurrencies](cryptocurrency.md). Some of these services offer ID verification options for higher limits, but they also allow accounts with just an email address. Basic limits typically start at $5,000-10,000 a day for basic accounts, and significantly higher limits for ID verified accounts (if offered).
```

2024-07-16 17:01 UTC, redoomed1 commented on docs/financial-services.md
> +**Coincards** allows you to purchase gift cards for a large variety of merchants. Their homepage has a complete listing of the various countries where their service is available.
According to Coincard's [About](https://coincards.com/about-us/) page

> most major vendors did not want to take the risk associated with holding or even trading in BTC as a currency. The need from the crypto community to be able to use their cryptocurrencies as a currency, however, remained a real issue

> Coincards [sic] vision is to help the cryptocurrency industry spend their cryptocurrencies at all retailers, using those retailers existing Gift Card infrastructure.

This service is designed for purchasing gift cards so that they can used on e-commerce sites, so I think that the original wording is correct.

2024-07-16 17:01 UTC, redoomed1 commented on docs/financial-services.md
>  These services allow you to purchase gift cards for a variety of merchants online with [cryptocurrency](cryptocurrency.md). Some of these services offer ID verification options for higher limits, but
https://github.com/privacyguides/privacyguides.org/pull/2643#discussion_r1679764036

2024-07-19 18:03 UTC, jonaharagon reviewed
I do work for someone who (independently) also works for Cake Wallet. This is not a conflict of interest under our policies, but I'm going to leave the approvals for other team members to do regardless, since I also don't think _my input specifically_ is necessary.

2024-07-21 06:21 UTC, jonaharagon approved these changes

2024-07-21 15:25 UTC, merged