Update Ente Auth logo
privacyguides/privacyguides.org pull request #2644
Opened 2024-07-16 11:59 UTC by dnred

Changes proposed in this PR:

- Update Ente Auth logo

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-07-16 13:12 UTC, rollsicecream approved these changes

2024-07-19 05:44 UTC, dngray requested changes
We wouldn't be approving a PNG version of this logo when we had an SVG in the past.

2024-07-20 14:02 UTC, dngray commented
I've had a look around and couldn't find one so I've reached out to @vishnukvmd to see if we can do something here.

2024-07-20 14:09 UTC, vishnukvmd commented
Hi @dngray, thanks for reaching out, perhaps you missed my response. [Here's the icon in SVG](https://github.com/user-attachments/assets/79efffca-80cb-4ac5-95dd-fe65eb3d98fe).

2024-07-21 14:43 UTC, closed without merging