Update obsolete Brave info (strict fingerprinting and pkg on macOS)
privacyguides/privacyguides.org pull request #2647
Opened 2024-07-17 19:48 UTC by fmarier

Changes proposed in this PR:

- Remove [obsolete](https://github.com/brave/brave-browser/issues/32316) warning about PKG on macOS
- Remove anti-fingerprinting mode which [no longer exists](https://brave.com/privacy-updates/28-sunsetting-strict-fingerprinting-mode/)

Conflict of interest statement: I work for Brave Software.

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-07-19 07:05 UTC, dngray commented
I'm curious to know what version of Brave you have, because this option still seems to be in the Linux version https://github.com/privacyguides/privacyguides.org/pull/2641#pullrequestreview-2187368837

2024-07-19 17:13 UTC, fmarier commented
> I'm curious to know what version of Brave you have, because this option still seems to be in the Linux version [#2641 (review)](https://github.com/privacyguides/privacyguides.org/pull/2641#pullrequestreview-2187368837)

Latest version in the official .deb repo:
```
Brave	1.67.123 Chromium: 126.0.6478.126 (Official build) (64 bits) 
Revision	fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS	Linux
```

2024-07-19 18:03 UTC, fmarier commented
I'll rebase this once https://github.com/privacyguides/privacyguides.org/pull/2641 lands to remove the fingerprinting commit.

2024-07-19 18:08 UTC, jonaharagon requested changes
Thanks for the PR! Dang, glad they made this change to macOS downloads.

2024-07-19 18:08 UTC, jonaharagon commented on docs/desktop-browsers.md
>  - [x] Check **Forget me when I close this site** (2)
This setting does still exist as a boolean.

```suggestion
- [x] Check **Block fingerprinting**
- [x] Check **Forget me when I close this site** (2)
```

2024-07-19 18:09 UTC, jonaharagon commented on docs/desktop-browsers.md
>  - [x] Check **Forget me when I close this site** (2)
Oh I see this was separately proposed in #2641, ignore :)

2024-07-20 12:06 UTC, dngray commented
> Latest version in the official .deb repo:

That's interesting because I was using the latest one from the fedora repo in the release channel. Version 1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit). I installed beta 1.69.117-1, now shows Version 1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (64-bit) and it still has that option as strict.

2024-07-20 21:00 UTC, jonaharagon reviewed
If you wouldn't mind rebasing then I'll approve :)

2024-07-20 21:47 UTC, fmarier commented
@jonaharagon Rebased.

2024-07-20 21:48 UTC, jonaharagon approved these changes
LGTM thank you!

2024-07-20 21:49 UTC, fmarier commented
> That's interesting because I was using the latest one from the fedora repo in the release channel. Version 1.67.134 Chromium: 126.0.6478.186 (Official Build) (64-bit). I installed beta 1.69.117-1, now shows Version 1.69.117 Chromium: 127.0.6533.57 (Official Build) beta (64-bit) and it still has that option as strict.

Even after you restart the browser? If so, are you blocking https://variations.brave.com/ by any chance? That's where the flag settings file (called a `seed`) is downloaded from.  If that doesn't get downloaded for you, then you're not getting the intended configuration. You may be behind on some features we're only enabling via that mechanism.

2024-07-21 05:12 UTC, kimg45 approved these changes

2024-07-21 06:19 UTC, merged