fix: Update brave browser settings
privacyguides/privacyguides.org pull request #2658
Opened 2024-07-21 19:41 UTC by kimg45

Changes proposed in this PR:

- update brave's settings to align with the current layout

closes #2657 

<summary>

- [ ] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-07-23 04:33 UTC, jonaharagon submitted a review, later dismissed

2024-07-24 04:12 UTC, redoomed1 requested changes
Checked in Brave 1.67.134 Chromium 126.0.6478.186 and the ordering of the sections is fine

I'm very confused by the complete 180 on the Brave with Tor section (https://github.com/privacyguides/privacyguides.org/pull/2658/commits/37386b9262d740f366600cdf8b94ed77cdac9475) and the removal of the "Sanitizing on close" section (https://github.com/privacyguides/privacyguides.org/pull/2658/commits/8fde2666968531255fae8a9ac5e1a78e0a30e86f)

2024-07-24 04:12 UTC, redoomed1 commented on docs/desktop-browsers.md
>  ##### Web3
```suggestion
#### Web3
```

2024-07-24 04:12 UTC, redoomed1 commented on docs/desktop-browsers.md
> +##### Extensions
```suggestion
#### Extensions
```

2024-07-24 04:12 UTC, redoomed1 commented on docs/desktop-browsers.md
>  ##### System
```suggestion
#### System
```

2024-07-24 04:13 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [x] Select **Don't allow sites to use the V8 optimizer** under *Security* -> *Manage V8 security*
Inline note suggested [here](https://github.com/privacyguides/privacyguides.org/pull/2658#discussion_r1689064048)

2024-07-24 04:14 UTC, redoomed1 commented on docs/desktop-browsers.md
>  ##### Web3
See https://github.com/privacyguides/privacyguides.org/pull/2658#discussion_r1689012985

2024-07-24 04:14 UTC, redoomed1 commented on docs/desktop-browsers.md
> +##### Extensions
See https://github.com/privacyguides/privacyguides.org/pull/2658#discussion_r1689012985

2024-07-24 04:14 UTC, redoomed1 commented on docs/desktop-browsers.md
>  ##### System
See https://github.com/privacyguides/privacyguides.org/pull/2658#discussion_r1689012985

2024-07-24 22:49 UTC, kimg45 commented on docs/desktop-browsers.md
That seems in line with the setting's description. It reduces performance and makes it more resistant to attacks. Unfortunately it doesn't actually fully disable JIT.

2024-07-24 23:01 UTC, kimg45 commented on docs/desktop-browsers.md
> +- [ ] Uncheck **Send a "Do Not Track" request with your browsing traffic**
Yeah but it's the kind of thing someone might turn on not realizing it's actually bad for privacy. Probably should mention it in the Firefox one as well.

2024-07-24 23:09 UTC, kimg45 commented on docs/desktop-browsers.md
> +- [x] Select **Only resolve .onion addresses in Tor windows**
I really don't see downside of using it vs a standard incognito mode window. Sure you won't blend in with Tor browser users, but it hides your IP address and lets you access .onion sites. I don't think anyone is under the illusion that it'll make you anonymous like Tor browser. Seems like a privacy improvement with no downsides to me.

2024-07-24 23:19 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [x] Select **Only resolve .onion addresses in Tor windows**
Fair point. The documentation for Brave with Tor also gives a similar disclaimer at the top:

> _Note that Private Windows with Tor Connectivity in Brave are just regular private windows that use Tor as a proxy. Brave does NOT implement most of the privacy protections from [Tor Browser](https://www.torproject.org/)_.

In which case, I don't think there should be a recommendation to select/unselect the settings for the "Tor window" section. Rather, there could be a short explanation similar to what you wrote in its own section, similar to the [Brave Rewards and Wallet section](https://www.privacyguides.org/en/desktop-browsers/#brave-rewards-and-wallet). Whether these settings should be changed (the default is on for both) can be an exercise for the reader.

2024-07-24 23:23 UTC, kimg45 commented on docs/desktop-browsers.md
> +- [x] Select **Only resolve .onion addresses in Tor windows**
Fair enough, sounds like the best way to do it.

2024-07-24 23:36 UTC, redoomed1 commented on docs/desktop-browsers.md
Thanks for the link to the illuminating post!

I guess my reason for wanting to add a clarifying note here is that I'm imagining a scenario in which a reader of the site goes through the configuration steps for Brave and takes the "Reduces performance but makes V8 more resistant to attacks" description at face value without knowing about JIT. They might ask, "Why would I enable a setting that makes something more resistant to attacks?"

Also, in the Vanadium release notes linked in the Mastodon post chain, there is the following line:

> restore fully disabling the JavaScript JIT compiler by default since Chromium changed the definition of disabling the JIT compiler into only disabling the 2 higher tiers of JIT compilation without disabling baseline JIT compilation which _does not avoid dynamically creating executable native code_[^1]

This makes me question the value of Chromium's V8 setting.

[^1]: Emphasis mine

2024-07-24 23:39 UTC, kimg45 commented on docs/desktop-browsers.md
It does disable some parts so it still reduces the attack surface it's just not as robust as Vanadium's or Edge's yet, hopefully it will be in the future once they add a separate WASM interpreter.

2024-07-24 23:46 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [ ] Uncheck **Send a "Do Not Track" request with your browsing traffic**
> it's actually bad for privacy

Could you please elaborate on this?

2024-07-24 23:48 UTC, kimg45 commented on docs/desktop-browsers.md
> +- [ ] Set *Method to resolve IPFS resources* to **Disabled**
Fixed

2024-07-24 23:50 UTC, kimg45 commented on docs/desktop-browsers.md
> +- [ ] Uncheck **Send a "Do Not Track" request with your browsing traffic**
The DNT flag is one extra bit of tracking, there's two groups of users: those who have it enabled and those who have it disabled. Websites can clearly see this by design. Also most users don't toggle it on, so if you do you will be part of the smaller group.

2024-07-24 23:52 UTC, redoomed1 commented on docs/desktop-browsers.md
What about this?

```suggestion

</div>

1. Disabling the V8 optimizer reduces your attack surface by disabling [some](https://grapheneos.social/@GrapheneOS/112708049232710156) parts of JavaScript Just-In-Time (JIT) compilation.

<div class="admonition tip" markdown>
<p class="admonition-title">Sanitizing on close</p>

- [x] Select **Delete data sites have saved to your device when you close all windows** under *Sites and Shields Settings* → *Content* → *Additional content settings* → *On-device site data*.

If you wish to stay logged in to a particular site you visit often, you can set exceptions on a per-site basis under the *Customized behaviors* section.

</div>
```

2024-07-24 23:56 UTC, redoomed1 commented on docs/desktop-browsers.md
How about this?

```suggestion
- [ ] Uncheck **Send a "Do Not Track" request with your browsing traffic**

</div>

1. Disabling the V8 optimizer reduces your attack surface by disabling [*some*](https://grapheneos.social/@GrapheneOS/112708049232710156) parts of JavaScript Just-In-Time (JIT) compilation.

<div class="admonition tip" markdown>
<p class="admonition-title">Sanitizing on close</p>

- [x] Select **Delete data sites have saved to your device when you close all windows** under *Sites and Shields Settings* → *Content* → *Additional content settings* → *On-device site data*.

If you wish to stay logged in to a particular site you visit often, you can set exceptions on a per-site basis under the *Customized behaviors* section.

</div>
```

2024-07-25 00:11 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [x] Select **Only resolve .onion addresses in Tor windows**
Thoughts on this explanation?

```suggestion
[**Private Window with Tor**](https://support.brave.com/hc/articles/360018121491-What-is-a-Private-Window-with-Tor-Connectivity) allows you to connect to .onion services within Private Windows on Brave using the Tor network, which may be useful in some cases. However, Brave is **not** as resistant to fingerprinting as the Tor Browser and far fewer people use Brave with Tor, so you will stand out. If your threat model requires strong anonymity, use the [Tor Browser](tor.md#tor-browser).
```

2024-07-25 00:15 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [x] Select **Only resolve .onion addresses in Tor windows**
https://github.com/privacyguides/privacyguides.org/pull/2658#discussion_r1690610542

2024-07-25 00:26 UTC, kimg45 commented on docs/desktop-browsers.md
> +- [x] Select **Only resolve .onion addresses in Tor windows**
I think I would change "allows you connect to .onion services" to "allows you to route your traffic through the Tor network in Private Windows" since clearnet sites will also be routed through Tor.

2024-07-25 00:30 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [x] Select **Only resolve .onion addresses in Tor windows**
```suggestion
[**Private Window with Tor**](https://support.brave.com/hc/articles/360018121491-What-is-a-Private-Window-with-Tor-Connectivity) allows you to route your traffic through the Tor network in Private Windows and access .onion services, which may be useful in some cases. However, Brave is **not** as resistant to fingerprinting as the Tor Browser and far fewer people use Brave with Tor, so you will stand out. If your threat model requires strong anonymity, use the [Tor Browser](tor.md#tor-browser).
```

2024-07-25 00:39 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- [ ] Uncheck **Send a "Do Not Track" request with your browsing traffic**
> Probably should mention it in the Firefox one as well.

Not relevant to this PR, but just wanted to note: someone on the forum noted that DNT is enabled by default when Enhanced Tracking Protection is set to Strict, so there is less of a fingerprinting risk on Firefox than on Brave since ETP Strict is recommended on this page.

2024-07-25 00:46 UTC, kimg45 commented on docs/desktop-browsers.md
> +- [ ] Uncheck **Send a "Do Not Track" request with your browsing traffic**
Maybe best not to mention at all then or recommend not to touch it.

2024-07-25 01:07 UTC, redoomed1 requested changes

2024-07-25 01:07 UTC, redoomed1 commented on docs/desktop-browsers.md
> +- Select **Extensions (no fallback)** under *Default Solana wallet*
Duplicate here

```suggestion
```

2024-07-25 01:09 UTC, kimg45 commented on docs/desktop-browsers.md
> +- Select **Extensions (no fallback)** under *Default Solana wallet*
I think there should be two separate lines since it's like that in the settings.

2024-07-25 07:16 UTC, dngray approved these changes

2024-07-25 11:37 UTC, jonaharagon approved these changes

2024-07-28 01:04 UTC, merged