update: Revert Atomic Desktops back to Silverblue and add GNOME security section
privacyguides/privacyguides.org pull request #2690
Opened 2024-08-03 04:45 UTC by redoomed1

Changes proposed in this PR:

- Desktop/PC recommendation page
  - Revert Fedora Atomic Desktops recommendation back to Fedora Silverblue
    - Reason 1: I don't think it's particularly useful to list all the Wayland-supported desktop environments and their spins, as it adds another point of maintenance should more DEs roll out Wayland support in the future (Xfce, Budgie) or more Wayland-supportive DEs emerge (Cosmic).
    - Reason 2: As this [section](https://www.privacyguides.org/en/os/linux-overview/#choosing-your-distribution) of the Linux Overview outlines, "[o]ur Linux recommendation page is not meant to be an authoritative source on which distribution you should use," so excluding atomic spins does not mean we recommend against them.
    - Reason 3: I think it's helpful to bring forward (again) Silverblue as a recommendation in light of the next section about GNOME's security advantages.
- Linux Overview page
  - Simplify the Wayland section by removing unneeded information (e.g., the Phoronix article about X11 in maintenance mode)
    - Stating that X11 is Wayland's less secure predecessor should be enough, along with linking to its Wikipedia page that shows that its last (significant) stable release was in 2012.
  - Add new section about GNOME's security edge in terms of permission prompts for third-party screen capture applications
    - This section is **not** meant to serve as anti-recommendation against KDE and Sway, but it offers something else for readers to consider when choosing their distribution and DE.
  - Rename section from "Wayland" to "Wayland and Desktop Environments"

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-03 05:27 UTC, dngray requested changes
I wouldn't revert the atomic listing to Silverblue. We have a soft recommendation on the permission control factor, ultimately we're not saying that KDE is bad or you shouldn't use it. Some people prefer it, and unless your system is compromised already or you've got a lot of untrusted software it is unlikely to matter too much.

> * Stating that X11 is Wayland's less secure predecessor should be enough, along with linking to its Wikipedia page that shows that its last (significant) stable release was in 2012.

I'm thinking we might just remove the wayland subheading, particularly in relation to that old qubes os article. It is good enough to simply say it is less secure and unmaintained on it's own.

> Add new section about GNOME's security edge in terms of permission prompts for third-party screen capture applications
> 
> * This section is **not** meant to serve as anti-recommendation against KDE and Sway, but it offers something else for readers to consider when choosing their distribution and DE.

This might be a nice addition, with a screenshot of what that prompt looks like.

> * Rename section from "Wayland" to "Wayland and Desktop Environments"

I think I'd remove this entirely.

2024-08-03 05:34 UTC, jonaharagon commented
> along with linking to its Wikipedia page that shows that its last (significant) stable release was in 2012.

I have an... *unofficial preference* against linking to Wikipedia articles generally, and I've been working on removing such links and writing out the relevant information instead over the last few months. I feel like in this case we could simply state that X11's last release was 12 years ago. It's not like that information is going to change at any point.

We should aim to have all information a reader would need to understand a concept directly on the site rather than on external resources.

2024-08-03 16:26 UTC, redoomed1 commented
Major changes made after internal discussion:

- Desktop/PC
  - Simplify the description under the Fedora Atomic Desktops card
  - Mention the advantage of NixOS's reproducible builds against supply chain attacks and embed a threat model label and internal link to the explanation of Supply Chain Attacks
    - The icon and the link won't be viridian in the preview until #2686 is merged.
  - Expand on "Avoids X11" criterion by mentioning its legacy nature
  - Embed Qubes article from the now-removed Wayland section to the section about Qubes being an exception
- Linux Overview
  - Remove the Wayland section due to internal discussion about the superfluity of this section
  - Add new section about GNOME's security edge in terms of permission prompts for third-party screen capture applications, making sure to conclude with a reminder about threat modeling when considering whether GNOME's security edge (or the lack thereof in other DEs and WMs) matters.

2024-08-05 02:16 UTC, jonaharagon commented on docs/os/linux-overview.md
> +</figure>
```suggestion
<figure markdown>
  ![Screenshot permissions](../assets/img/linux/screenshot_permission.png){ width="450" }
  <figcaption>GNOME's screenshot permission dialog</figcaption>
</figure>
```

2024-08-05 02:24 UTC, dngray approved these changes

2024-08-05 02:54 UTC, jonaharagon requested changes

2024-08-05 02:54 UTC, jonaharagon commented on docs/os/linux-overview.md
> +Desktop environments (DEs) that support the [Wayland](https://wayland.freedesktop.org) display protocol are overall improvements [security-wise](https://lwn.net/Articles/589147) over those that suppo
"overall improvements security-wise" - bit of a mouthful

```suggestion
Desktop environments (DEs) that support the [Wayland](https://wayland.freedesktop.org) display protocol are [more secure](https://lwn.net/Articles/589147) than those that only support X11. However, not all DEs take full advantage of Wayland's architectural security improvements.
```

2024-08-05 02:54 UTC, jonaharagon commented on docs/os/linux-overview.md
> +For example, GNOME has a notable edge in security compared to other DEs by implementing [permission controls](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1970) for third-party softwar
- The merge request description at the first link is overly technical I think, I'm not sure what the value is.
- Why are we linking to this specific application?

```suggestion
For example, GNOME has a notable edge in security compared to other DEs by implementing permission controls for third-party software that tries to [capture your screen](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3943). That is, when a third-party application attempts to capture your screen, you are prompted for your permission to share your screen with the app.
```

2024-08-05 02:54 UTC, jonaharagon commented on docs/os/linux-overview.md
> +For other DEs and window managers like [KDE](https://kde.org) and [Sway](https://swaywm.org), permission controls for such privileged actions [do not yet exist](https://invent.kde.org/plasma/xdg-desk
```suggestion
Many alternatives don't provide these same permission controls yet,[^1] while some are waiting for Wayland protocol to implement these controls upstream.[^2]

[^1]: KDE currently has an open proposal to add controls for screen captures: <https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/issues/7>
[^2]: Sway is waiting to add specific security controls until they "know how security as a whole is going to play out" in Wayland: <https://github.com/swaywm/sway/issues/5118#issuecomment-600054496>
```

- Regarding threat modeling, does this have to be stated? It feels redundant.
- Linking to product homepages in this context feels extraneous, we shouldn't direct readers to links that don't provide direct relevance to the sentence they're reading. Also note we didn't link to GNOME above either anyways.

2024-08-05 03:08 UTC, redoomed1 commented on docs/os/linux-overview.md
> +For other DEs and window managers like [KDE](https://kde.org) and [Sway](https://swaywm.org), permission controls for such privileged actions [do not yet exist](https://invent.kde.org/plasma/xdg-desk
> Linking to product homepages in this context feels extraneous, we shouldn't direct readers to links that don't provide direct relevance to the sentence they're reading.

Yeah, that makes a lot of sense :+1: will keep this in mind moving forward

2024-08-05 03:14 UTC, jonaharagon approved these changes

2024-08-05 03:18 UTC, merged

2024-08-07 19:16 UTC, Pointedstick commented on docs/os/linux-overview.md
> +For example, GNOME has a notable edge in security compared to other DEs by implementing permission controls for third-party software that tries to [capture your screen](https://gitlab.gnome.org/GNOME
JFYI this isn't quite accurate. We have this as well in KWin, for 3rd-party apps using the portal API. The only place it's not used is for Spectacle, which is our own 1st party screenshot app. Spectacle bypasses the portal API because its UX isn't compatible with the UX assumptions made by the designers of the portal API. This is the part that's an open topic of discussion.

2024-08-09 14:49 UTC, Pointedstick commented on docs/os/linux-overview.md
> +For example, GNOME has a notable edge in security compared to other DEs by implementing permission controls for third-party software that tries to [capture your screen](https://gitlab.gnome.org/GNOME
Upon further review of our code, it seems that you were right and I was wrong. This does indeed seem to be something we should improve. Sorry for the noise.

2025-08-27 16:56 UTC, RoyalOughtness commented
@redoomed1 FYI, this is out of date now