docs: Add employee information
privacyguides/privacyguides.org pull request #2692
Opened 2024-08-03 15:48 UTC by jonaharagon

Changes proposed in this PR:

- https://github.com/MAGICGrants/MagicGrants.org/pull/2

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-03 15:51 UTC, jonaharagon commented on theme/main.html
> +{% endif %}
We could wait to do this ask until we have a platform other than GitHub Sponsors maybe, I'm not sure. What do you think?

2024-08-04 01:53 UTC, SamsungGalaxyPlayer commented on docs/about/jobs.md
> +*We do not have any job openings at the moment.*
Do you want to ask for people to send in their resumes/interest in advance so you have a head start later?

2024-08-04 07:26 UTC, freddy-m commented on docs/about.md
>  The project executive committee consists of five volunteers charged with management of the [MAGIC Privacy Guides Fund](https://magicgrants.org/funds/privacy_guides), making most critical project-rela
I know one volunteers to be on the excutive committee, but I feel that people could get confused by the fact that there is a paid member of it to. Not sure how you would make this clearer with the wording though

2024-08-04 07:27 UTC, freddy-m commented on docs/about/jobs.md
> +*We do not have any job openings at the moment.*
Not for now I don't think, but perhaps we can add that nearer to if/when we want to take anyone else on

2024-08-04 07:29 UTC, freddy-m commented on theme/main.html
> +{% endif %}
I think a fair few people don't like GitHub Sponsors, so that woulnd't be the worst idea. I'm not too bothered by it all, but if we aren't going to have Sponsors as our main way of recieving donations then perhaps we shouldn't push it too much? Probably doesn't matter idk

2024-08-04 08:33 UTC, freddy-m commented on theme/main.html
> +{% endif %}
On a different note, I much prefer the word 'helps' to 'matters'. 'It really helps' sounds kinder whereas 'it really matters' sounds a bit like a plea to me

2024-08-04 17:16 UTC, jonaharagon commented on docs/about.md
>  The project executive committee consists of five volunteers charged with management of the [MAGIC Privacy Guides Fund](https://magicgrants.org/funds/privacy_guides), making most critical project-rela
My work on the committee would fall outside of paid hours, I think it legally has to in fact, so it is still a volunteer position.

2024-08-04 17:17 UTC, jonaharagon commented on theme/main.html
> +{% endif %}
I definitely half-stole this wording from Wikipedia's campaigns which is why it probably sounds a bit as desperate as they typically do lol

2024-08-05 15:03 UTC, rollsicecream requested changes
Just something to fix, otherwise LGTM.

2024-08-05 15:03 UTC, rollsicecream commented on docs/about.md
> +[**Jonah Aragon**](https://www.jonaharagon.com) is the Project Director and staff writer at *Privacy Guides*. His role includes researching and writing for this website, system administration, creati
```suggestion
[**Jonah Aragon**](https://www.jonaharagon.com) is the Project Director and staff writer at *Privacy Guides*. His role includes researching and writing for this website, system administration, creating the *Privacy Guides Online Learning* course content, reviewing the products recommended here, and most other day-to-day tasks.
```

2024-08-08 16:02 UTC, redoomed1 commented on docs/about.md
> +[**Jonah Aragon**](https://www.jonaharagon.com) is the Project Director and staff writer at *Privacy Guides*. His role includes researching and writing for this website, system administration, creati
Not sure if this change is needed, IMO, since "_Privacy Guides Online Learning_" simply modifies "course content," so if we remove the modifier and look at the basic clause

> His role includes [...] creating course content

It reads fine

2024-08-08 16:07 UTC, redoomed1 commented on theme/main.html
> +      If you've received $3 worth of knowledge here, please donate today if you're able, it really helps.
```suggestion
      <strong>We don't run ads, we don't use affiliate links, and we don't have paywalls.</strong> We rely on our readers to build this community and spread the word.<br>
      If you've received $3 worth of knowledge here, please donate today if you're able to. It really helps!
```

2024-08-12 18:08 UTC, redoomed1 approved these changes

2024-08-19 15:23 UTC, merged