Update macOS Section
privacyguides/privacyguides.org pull request #2702
Opened 2024-08-07 20:56 UTC by kimg45

Changes proposed in this PR:

- remove information about previous versions of macOS and future promises that haven't been implemented so as to only focus on the current state of the software

<summary>

- [ ] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-07 21:14 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Apple's OCSP service uses HTTPS encryption, so only they are able to see which apps you open. They've [posted information](https://support.apple.com/HT202491) about their logging policy for this serv
> as to only focus on the current state of the software

This doesn't seem like a justification to remove, since the reason it's mentioned is to explicitly call out a privacy-related function that is _missing_ from the current state of the software.

The absence _is_ the current state, so I'd be fine with the first change (removing outdated, historical information) while keeping the last sentence as-is:

```suggestion
Apple's OCSP service uses HTTPS encryption, so only they are able to see which apps you open. They've [posted information](https://support.apple.com/HT202491) about their logging policy for this service. They additionally promised to add a mechanism for people to opt-out of this online check, but this has not been added to macOS as of August 2024.
```

2024-08-07 21:20 UTC, kimg45 commented on docs/os/macos-overview.md
> +Apple's OCSP service uses HTTPS encryption, so only they are able to see which apps you open. They've [posted information](https://support.apple.com/HT202491) about their logging policy for this serv
Maybe "there isn't currently a mechanism to opt out of these checks"? I don't really care about promises, they mean nothing until it's actually in the OS.

2024-08-07 23:17 UTC, jonaharagon commented on docs/os/macos-overview.md
> +##### Hardened Runtime
This and the sandboxing section feel a little unnecessary to me. If the results are no, as they will be in most cases, what is the reader supposed to do about that?

We should try to add actionable advice in both of these sections.

2024-08-07 23:20 UTC, kimg45 commented on docs/os/macos-overview.md
> +##### Hardened Runtime
hmm? They should know if it's sandboxed or not. Then they can decide if they want to run it, run in a VM, etc.

2024-08-08 05:16 UTC, kimg45 commented
Note to self: possibly mention .pkg vs .dmg for app installs

2024-08-08 15:52 UTC, redoomed1 reviewed
I'm going to be busy when the new macOS version releases (late Sept or Oct?), so I thought to add my suggestions here while they're still fresh in our minds.

2024-08-08 15:52 UTC, redoomed1 commented on docs/os/macos-overview.md
> +Software downloaded from outside the official App Store is not required to be sandboxed.
```suggestion
Software downloaded from outside the official App Store is not required to be sandboxed. If your threat model prioritizes defending against [:material-bug-outline: Passive Attacks](basics/common-threats.md#security-and-privacy){ .pg-orange }, then you may want to check if the software you download outside the App Store is sandboxed, which is up to the developer to *opt-in*.
```

2024-08-08 15:52 UTC, redoomed1 commented on docs/os/macos-overview.md
> +You can check apps before you run them with the command
```suggestion
Alternatively, you can check apps before you run them by running this command in the terminal:
```
You can replace "terminal" with the proper name of the console on macOS.

2024-08-08 15:52 UTC, redoomed1 commented on docs/os/macos-overview.md
> +
```suggestion

If you find that the app you want to run is not sandboxed, then you may employ [methods of compartmentalization](../basics/common-threats.md#security-and-privacy) such as virtual machines or separate devices, use a similar app that is sandboxed, or choose to not use the unsandboxed app altogether.
```

2024-08-08 15:52 UTC, redoomed1 commented on docs/os/macos-overview.md
>  While you [can](https://eclecticlight.co/2021/02/23/how-to-run-apps-in-private) manually opt out of this check relatively easily, we recommend against doing so unless you would be badly compromised b
In the team chat, you emphasized the importance of OCSP checks to block malicious apps for which Apple revoked their certificates.

I think that this sentence can start out with talking about the importance of this feature, then you can mention the edge case for disabling the check.

> badly compromised by the revocation checks

Because I'm not sure what this concretely entails

2024-08-08 15:52 UTC, redoomed1 commented on docs/os/macos-overview.md
> +You can check if an app uses the Hardened Runtime using the command
Not sure if this section needs to be here after our last convo, unless there's an obvious footgun that allows people to disable this, which you would like to emphasize **not to do**

> However gatekeeper enforces hardened runtime
People are less likely to run an app when gatekeeper blocks them
And it’s not something you have to go out of you’ll way to check
In fact really it doesn’t apply on second thought
It’s enforced by gatekeeper my bad
In the same way the app store enforces the sandbox

2024-08-08 15:52 UTC, redoomed1 commented on docs/os/macos-overview.md
> +On macOS, whether an app is sandboxed is determnined by the developer when they sign it. The App Sandbox protects against vulnerabilities in the apps you run by limiting what a malicious actor can do
> limiting what a malicious actor can do

I think you expanded on this in the team chat and it should be put on the page

> For one sandboxed apps can’t access external data without user permission
> It [malicious apps] can just do whatever it wants basically outside of certain things protected by TCC like the camera
And like certain folders like documents and desktop

https://developer.apple.com/documentation/security/app_sandbox/protecting_user_data_with_app_sandbox

This can also be linked in the Further Reading/Sources section.

2024-08-09 21:42 UTC, kimg45 commented on docs/os/macos-overview.md
> +You can check apps before you run them with the command
It is called the terminal in macOS

2024-08-09 21:45 UTC, redoomed1 commented on docs/os/macos-overview.md
> +Software downloaded from outside the official App Store is not required to be sandboxed. If your threat model prioritizes defending against [:material-bug-outline: Passive Attacks](basics/common-thre
```suggestion
Software downloaded from outside the official App Store is not required to be sandboxed. If your threat model prioritizes defending against [:material-bug-outline: Passive Attacks](../basics/common-threats.md#security-and-privacy){ .pg-orange }, then you may want to check if the software you download outside the App Store is sandboxed, which is up to the developer to *opt-in*.
```

2024-08-09 21:46 UTC, kimg45 commented on docs/os/macos-overview.md
>  While you [can](https://eclecticlight.co/2021/02/23/how-to-run-apps-in-private) manually opt out of this check relatively easily, we recommend against doing so unless you would be badly compromised b
Basically just means there's a longer period of time before your system would recognize the app as malicious.

2024-08-09 21:47 UTC, kimg45 commented on docs/os/macos-overview.md
> +You can check if an app uses the Hardened Runtime using the command
Yeah Gatekeeper is easily by passable as it is now, I think in the beta they're taking about the easy bypass and giving you a setting to disable it. So I'd like to keep this part in, maybe elaborate on that a bit. Also it only applies to apps and not other binaries.

2024-08-09 22:23 UTC, redoomed1 commented on docs/os/macos-overview.md
> +Software downloaded from outside the official App Store is not required to be sandboxed. If your threat model prioritizes defending against [:material-bug-outline: Passive Attacks](../basics/common-t
```suggestion
Software downloaded from outside the official App Store is not required to be sandboxed. If your threat model prioritizes defending against [:material-bug-outline: Passive Attacks](../basics/common-threats.md#security-and-privacy){ .pg-orange }, then you may want to check if the software you download outside the App Store is sandboxed, which is up to the developer to *opt in*.
```

2024-09-18 23:39 UTC, jonaharagon requested changes
This PR looks great :)

I just want your opinion on the MAC address thing below.

2024-09-18 23:39 UTC, jonaharagon commented on docs/os/macos-overview.md
> +Go to **System Settings** > **Network** > **Wi-Fi** > **Details** and set **Private Wi-FI address** to either **Fixed** if you want a fixed random address for each network or **Rotating** if you want
```suggestion
Go to **System Settings** > **Network** > **Wi-Fi** > **Details** and set **Private Wi-FI address** to either **Fixed** if you want a fixed but unique address for the network you're connected to, or **Rotating** if you want it to change over time.
```

AFAIK this is set on a per network basis, you're not setting a default.

Whether it _defaults_ to Fixed or Rotating (or possibly even Off) [seems to depend on the network](https://arstechnica.com/gadgets/2024/09/macos-15-sequoia-the-ars-technica-review/18/#:~:text=Apple%20says%20that%20the%20default%20settings%20are%20%22based%20on%20the%20type%20of%20network%20a%20device%20is%20connected%20to.%22) according to some Apple magic that is unclear to me.

I don't know if we want to note that fact?

2024-09-18 23:39 UTC, jonaharagon commented on docs/os/macos-overview.md
> +On macOS, whether an app is sandboxed is determined by the developer when they sign it. The App Sandbox protects against vulnerabilities in the apps you run by limiting what a malicious actor can do
```suggestion
On macOS, whether an app is sandboxed is determined by the developer when they sign it. The App Sandbox protects against vulnerabilities in the apps you run by limiting what a malicious actor can do in the event that the app is exploited. The App Sandbox *alone* can't protect against [:material-package-variant-closed-remove: Supply Chain Attacks](../basics/common-threats.md#attacks-against-certain-organizations){ .pg-viridian } by malicious developers. For that, sandboxing needs to be enforced by someone other than the developer themselves, as it is on the App Store.
```

this is maybe more clear?

2024-09-18 23:39 UTC, jonaharagon commented on docs/os/macos-overview.md
> +##### Hardened Runtime
```suggestion
If you find that the app you want to run is not sandboxed, then you may employ methods of [compartmentalization](../basics/common-threats.md#security-and-privacy) such as virtual machines or separate devices, use a similar app that is sandboxed, or choose to not use the unsandboxed app altogether.

##### Hardened Runtime
```

2024-09-18 23:58 UTC, jonaharagon approved these changes

2024-10-24 04:21 UTC, dngray approved these changes

2024-10-24 05:22 UTC, dngray approved these changes

2024-10-24 18:10 UTC, redoomed1 commented on docs/os/macos-overview.md
> +You can check if apps that are already running are sandboxed using the [Activity Monitor](https://developer.apple.com/documentation/security/app_sandbox/protecting_user_data_with_app_sandbox#4098972)
```suggestion
You can check if apps that are already running are sandboxed using the [Activity Monitor](https://developer.apple.com/documentation/security/protecting-user-data-with-app-sandbox#Verify-that-your-app-uses-App-Sandbox).
```
The suggested link brings readers directly to the section pertaining to Activity Monitor which includes a helpful graphic.

2024-10-26 11:31 UTC, merged