Recommend Argon2id when using Bitwarden
privacyguides/privacyguides.org pull request #2713
Opened 2024-08-17 03:45 UTC by IDON-TEXIST

Changes proposed in this PR:

- Recommend switching to Argon2id when using Bitwarden
 - Relevant threads: [[1]](https://discuss.privacyguides.net/t/bitwarden-new-argon2id-kdf/11826) [[2]](https://discuss.privacyguides.net/t/suggest-changing-kdf-in-the-bitwarden-recommendation/11854)

This is just a draft until the preview deploys because I didn't bother to test locally.

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

Side note: legally speaking, what is the "Privacy Guides" mentioned in the contribution terms?

2024-08-19 15:06 UTC, redoomed1 requested changes
Thanks for the PR!

Recently, we're aiming to try  to avoid linking to Wikipedia articles as a general rule for the reasons expressed [here](https://github.com/privacyguides/privacyguides.org/pull/2690#issuecomment-2266387815).

Give that Bitwarden's documentation provides a nice overview of both KDF algorithms, I think it makes more sense to link to those.

2024-08-19 15:06 UTC, redoomed1 commented on docs/passwords.md
> +Bitwarden uses [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2) as its key derivation function by default. It also offers [Argon2](https://en.wikipedia.org/wiki/Argon2), which is more secure, as an alt
```suggestion
Bitwarden uses [PBKDF2](https://bitwarden.com/help/kdf-algorithms/#pbkdf2) as its key derivation function by default. It also offers [Argon2](https://bitwarden.com/help/kdf-algorithms/#argon2id), which is more secure, as an alternative.
```

2024-08-19 23:18 UTC, redoomed1 approved these changes
LGTM. Thanks again!

2024-08-20 14:19 UTC, blacklight447 approved these changes

2024-08-20 14:27 UTC, merged