update!: Remove iVerify Basic
privacyguides/privacyguides.org pull request #2715
Opened 2024-08-18 14:40 UTC by ph00lt0

Changes proposed in this PR:
Remove iVerify Basic

Discussion: https://discuss.privacyguides.net/t/remove-iverify-basic/20133

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-18 14:51 UTC, redoomed1 commented
@ph00lt0 You should remove the iVerify Basic entry from `tools.md` as well. Otherwise, the deploy preview will not be built.

2024-08-18 15:10 UTC, redoomed1 approved these changes
LGTM

2024-08-19 03:52 UTC, jonaharagon requested changes
https://discuss.privacyguides.net/t/remove-iverify-basic/20133/11

2024-08-19 06:34 UTC, dngray approved these changes

2024-08-22 10:53 UTC, kimg45 approved these changes

2024-10-29 17:35 UTC, merged