Add Grayjay to frontends
privacyguides/privacyguides.org pull request #2720
Opened 2024-08-20 18:03 UTC by I-I-IT

Changes proposed in this PR:

-
Add Grayjay. It has proved to be a reliable way to watch Youtube videos, but it is much more than that.

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-20 18:11 UTC, I-I-IT commented
The grayjay icon : https://grayjay.app/images/Vectors-Wrapper_7.svg

2024-08-21 21:47 UTC, I-I-IT commented
> @I-I-IT please see https://github.com/privacyguides/privacyguides.org/actions/runs/10486072648/job/29043519580?pr=2720

I saw the build failed, but I dont understand why.

2024-08-21 22:39 UTC, redoomed1 commented
> I saw the build failed, but I dont understand why.

Well, if you're adding a new tool to this page, an entry should be added to the appropriate section in `tools.md` as well.

Also, the svg canvas size should be 128x128, per the [contributor guidelines](https://www.privacyguides.org/en/meta/uploading-images/#images).

2024-08-21 23:01 UTC, redoomed1 requested changes
Given the conclusion reached in the recent [discussion](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/28) on the definition of open source, the criteria for frontends must also be changed if this tool is going to be added to this page.

2024-11-12 05:45 UTC, jonaharagon commented on theme/assets/img/frontends/grajay.svg
does grayjay have an alt logo which works on a light background?

2025-02-28 17:44 UTC, dngray commented
Closing, cha

2025-02-28 17:44 UTC, closed without merging

2025-02-28 17:45 UTC, dngray commented
Criteria change not  planned.