docs: Elaborate on open source preference and add developer submission process
privacyguides/privacyguides.org pull request #2727
Opened 2024-08-22 01:56 UTC by redoomed1

Changes proposed in this PR:

- Expand a bit on why open source projects are preferred over proprietary alternatives
  - This was mostly spurred by the recent [forum discussion](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230) started by @blacklight447.
- Add participation in the developer self-submission process (aka [Project Showcase](https://discuss.privacyguides.net/t/about-the-project-showcase-category/114)) as a requirement
  - It was briefly mentioned in the WIP [volunteer's handbook](https://github.com/privacyguides/privacyguides.org/pull/2700/files#diff-6f3b626aafb1ea347b16df5d199d2969f81a21a5f6d7c220e205d2f9078e69faR53-R59), but I think it's pertinent to mention on the General Criteria page as well.
- Add internal link to the Common Threats page to provide inspiration for developers when formulating the exact threat model for their projects
  - Given the increased emphasis on threat modeling with the addition of threat model labels on a majority of tool pages, it might be good to nudge prospective developers into thinking about their projects through this framework as well.
- Make a variety of grammar and wording changes

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-22 03:23 UTC, jonaharagon requested changes

2024-08-22 03:23 UTC, jonaharagon commented on docs/about/criteria.md
> +- **Source Availability**: Open-source projects are generally preferred over equivalent proprietary alternatives due to the transparency provided by code that lives in a public repository, allowing f
If this change is based on the forum discussion, the reason you've stated here _is_ the reason @dngray gave [[1](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/3)] and @ph00lt0 agrees with [[2](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/15)], but @blacklight447 [[3](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/4)] and I [[4](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/23)] both *additionally* argued that we prefer open-source projects because it acts as an indicator of the long-term viability of the software.

I also count at least 3 community members in that thread who say they consider multiple factors besides mere development transparency as well. [[5](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/2)] [[6](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/7)] [[7](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/9)]

Not to say that anyone here is right or wrong, just that we should reach a consensus on this first.

2024-08-22 03:23 UTC, jonaharagon commented on docs/about/criteria.md
>      - Why should anyone use it over the alternatives?
The meaning of these two statements are not the same, the deleted line implies that it is not necessary to solve an entirely new problem (albeit while _suggesting_ that it probably should), the added line implies it is.

The way I see it, _currently_ a new tool could not solve a _new_ problem but still provide tangible benefits over the alternatives, and is therefore worthy of consideration.

So I guess I am just wondering if the change in meaning is intentional.

2024-08-22 03:27 UTC, jonaharagon commented on docs/about/criteria.md
> +- **Source Availability**: Open-source projects are generally preferred over equivalent proprietary alternatives due to the transparency provided by code that lives in a public repository, allowing f
Something I think we should consider is that _I believe_ the intent of this criteria page is to provide a general overview to readers of what we're thinking about, not to act as a rubric for us or community reviewers to follow.

It might be better to keep our descriptions here pretty generalized, and add detailed specifics about what we're looking for to a "reviewer's guide" in the volunteer handbook instead?

2024-08-22 03:29 UTC, redoomed1 commented on docs/about/criteria.md
>      - Why should anyone use it over the alternatives?
> if the change in meaning is intentional

Yes, I thought that the "what" question would be more productive than the "yes or no"-type question, but you raise a good point about it being okay that a new tool doesn't solve a new problem.

2024-08-22 03:30 UTC, jonaharagon commented on docs/about/criteria.md
>      - Why should anyone use it over the alternatives?
If you want to change the wording while keeping the meaning the same, I suppose it could simply be "what new problem(s), **if any,** does it solve?"

2024-08-22 03:37 UTC, redoomed1 commented on docs/about/criteria.md
> +- **Source Availability**: Open-source projects are generally preferred over equivalent proprietary alternatives due to the transparency provided by code that lives in a public repository, allowing f
> It might be better to keep our descriptions here pretty generalized

I agree with the overall sentiment. I guess my reason for this addition is that the other general criteria on this page are pretty straightforward (of course recommended tools should be easy-to-use and actively developed). I think that the open source preference is not so straightforward or leaves the reader having to fill in the blanks. To say it another way, I feel like there should be a "because..." after the statement.

That's my two cents at least. I would love to hear other people's take.

2024-08-22 04:07 UTC, redoomed1 commented on docs/about/criteria.md
> +- **Source Availability**: Open-source projects are generally preferred over equivalent proprietary alternatives due to the transparency provided by code that lives in a public repository, allowing f
On second thought, I'm fine with not changing this line because of the suggestion you gave here:

> add detailed specifics about what we're looking for to a "reviewer's guide" in the volunteer handbook instead

If needed, we could link to whatever relevant page in the volunteer handbook if any page on the site calls for an extended explanation of the preference for open source.

2024-08-23 03:41 UTC, jonaharagon approved these changes

2024-08-23 12:16 UTC, blacklight447 commented
Did we double check that all recommendations that  need it do in fact have a publicily accessible security whitepaper?

2024-08-25 04:54 UTC, dngray commented
@blacklight447 good point, we should do that before merging.

2024-08-25 18:08 UTC, redoomed1 commented on docs/about/criteria.md
> +- Must have a security whitepaper if it is a project that involves the handling of sensitive information like a messenger, password manager, encrypted cloud storage, etc.
@blacklight447 @dngray Here's a list of all the tools under the listed categories and their whitepaper[^1] status.

## Messengers

- Signal: :white_check_mark: [Technical information: Specifications and software libraries for developers](https://signal.org/docs/)
- SimpleX Chat: :white_check_mark: [SimpleX whitepaper](https://github.com/simplex-chat/simplexmq/blob/master/protocol/overview-tjr.md)
- Briar: :white_check_mark: [Protocol](https://code.briarproject.org/briar/briar/-/wikis/home#protocol) & [Architecture](https://code.briarproject.org/briar/briar/-/wikis/home#architecture)
- Element: :white_check_mark: [Matrix Specification](https://spec.matrix.org/latest)
- Session: :white_check_mark: [Session Whitepaper](https://getsession.org/whitepaper)

## Password Managers

- Bitwarden: :white_check_mark: [Bitwarden Security Whitepaper](https://bitwarden.com/help/bitwarden-security-white-paper/)
- Proton Pass: :white_check_mark: [The Proton Pass security model (blog post)](https://proton.me/blog/proton-pass-security-model)
- 1Password: :white_check_mark: [Security Design white paper (PDF)](https://1passwordstatic.com/files/security/1password-white-paper.pdf)
- Psono: Maybe, [Security: How we protect your passwords](https://psono.com/security)
- KeePassXC: Maybe, [KeePass Memory Security](https://keepassxc.org/blog/2019-02-21-memory-security/)
- KeePassDX: No
- Strongbox: No
- gopass: :white_check_mark: [Security, Known Limitations, and Caveats](https://github.com/gopasspw/gopass/blob/master/docs/security.md)

## Cloud Storage

- Proton Drive: :white_check_mark: [The Proton Drive security model (blog post)](https://proton.me/blog/protondrive-security)
- Tresorit: :white_check_mark: [Incident management, business continuity, disaster recovery](https://support.tresorit.com/hc/en-us/articles/4407206932114-Incident-management-business-continuity-disaster-recovery)
- Peergos: :white_check_mark: [Security (docs)](https://book.peergos.org/security/security.html)

[^1]: I took into consideration @blacklight447's personal definition of a security whitepaper expressed in the team chat: "a document which explains how a product is designed for what threat model with a description of how it does it." @ph00lt0 added an additional requirement for a whitepaper: "it should also include the measures taken, aka what cryptography you use, etc."

2024-08-31 05:20 UTC, dngray commented on docs/about/criteria.md
> +- Must have a security whitepaper if it is a project that involves the handling of sensitive information like a messenger, password manager, encrypted cloud storage, etc.
Hmm, yeah i disagree with removing KeepassDX/Strongbox on just this requirement though.

2024-09-09 07:51 UTC, jonaharagon commented on docs/about/criteria.md
> +- Must have a security whitepaper if it is a project that involves the handling of sensitive information like a messenger, password manager, encrypted cloud storage, etc.
@dngray for what it's worth, this is criteria for developer self-submissions, not criteria to be listed. Whether we should require this for all projects including ones already listed could be a separate discussion but it doesn't have to hold up this PR.

2024-09-09 07:52 UTC, jonaharagon approved these changes

2024-09-11 00:57 UTC, dngray approved these changes

2024-09-11 00:57 UTC, merged

2024-10-08 20:23 UTC, freddy-m commented on docs/about/criteria.md
> +- **Source Availability**: Open-source projects are generally preferred over equivalent proprietary alternatives due to the transparency provided by code that lives in a public repository, allowing f
@jonaharagon, for the record, I agree with your comment on the forum [here](https://discuss.privacyguides.net/t/what-does-privacy-guides-see-as-opensource/20230/23).

> It might be better to keep our descriptions here pretty generalized, and add detailed specifics about what we're looking for to a "reviewer's guide" in the volunteer handbook instead?

This also seems sensible to me 👍