update!: Move Molly from blog post to listing under Signal
privacyguides/privacyguides.org pull request #2729
Opened 2024-08-22 18:12 UTC by redoomed1

Changes proposed in this PR:

- Move the Molly listing from the Signal Configuration and Hardening blog post to a listing under the Signal recommendation
  - Relevant discussion: https://discuss.privacyguides.net/t/recommend-molly-instead-of-signal/17597/8
- Signal Config and Hardening post
  - Remove parts about Molly in the Signal blog post that were ported to the RTC recommendation page
  - Remove the Endpoint Security section
    - Reason: IMO, the advice given here is somewhat redundant with the advice given elsewhere on the website regarding mobile OSes.
  - Remove the Caveats section in the Molly section and move any relevant parts of it to more appropriate places
- Sharpen some parts of both pages by including threat model labels and relevant links to the Common Threats page

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-23 03:37 UTC, jonaharagon commented on docs/real-time-communication.md
> +- [:simple-github: GitHub](https://github.com/mollyim/mollyim-android/releases)
```suggestion
- [:simple-fdroid: F-Droid](https://molly.im/fdroid)
- [:octicons-moon-16: Accrescent](https://accrescent.app/app/im.molly.app)
- [:simple-github: GitHub](https://github.com/mollyim/mollyim-android/releases)
```

2024-08-23 03:45 UTC, redoomed1 commented on docs/real-time-communication.md
> +- [:simple-github: GitHub](https://github.com/mollyim/mollyim-android/releases)
I thought there was an unspoken rule to not include F-Droid download links unless the software is only distributed through there (a prominent example being Mull).

2024-08-23 04:39 UTC, jonaharagon commented on docs/real-time-communication.md
> +- [:simple-github: GitHub](https://github.com/mollyim/mollyim-android/releases)
I believe it can/should be linked when they are using a developer-operated repository.

Regardless, I don't think Accrescent can be the *only* app store download for a listing when the app also recommends other app stores (F-Droid in this case), given that we intentionally exclude Accrescent from https://www.privacyguides.org/en/android/obtaining-apps/.

2024-08-23 04:39 UTC, jonaharagon requested changes
If you're editing the blog post then the date on [line 4](https://github.com/privacyguides/privacyguides.org/pull/2729/files#diff-e385ecabf50338ececcfecc99e5f2591bba6528cbbdc87d9d8b3cf4ef6831471R4) should be updated.

2024-08-24 03:13 UTC, jonaharagon commented on docs/real-time-communication.md
> +**Molly** is an alternative app that uses the Signal network and offers additional security features, including locking the app at rest, securely shredding unused RAM data, routing via Tor, and [more
I feel like for people who don't pay attention to heading levels it is not _immediately_ clear that this is an alternative client and not a separate service. Maybe an introduction along these lines?

```suggestion

If you use Android and your threat model requires protecting against [:material-target-account: Targeted Attacks](basics/common-threats.md#attacks-against-specific-individuals){ .pg-red  } you may consider using this alternative app, which features a number of security and usability improvements, to access the Signal network.

<div class="admonition recommendation" markdown>

![Molly logo](assets/img/messengers/molly.svg){ align=right }

**Molly** is an alternative Signal client for Android which allows you to encrypt the local database with a passphrase at rest, to have unused RAM data securely shredded, to route your connection via Tor, and [more](https://blog.privacyguides.org/2022/07/07/signal-configuration-and-hardening#privacy-and-security-features). It also has usability improvements including scheduled backups, automatic locking, and the ability to use your Android phone as a linked device instead of the primary device for a Signal account.
```

2024-08-24 03:27 UTC, jonaharagon approved these changes
Looks great, 2 minor thoughts:

2024-08-24 03:27 UTC, jonaharagon commented on blog/posts/signal-configuration-and-hardening.md
> +If your threat model calls for protecting against [:material-bug-outline: Passive Attacks](https://www.privacyguides.org/en/basics/common-threats/#security-and-privacy){ .pg-orange }, then avoid link
```suggestion
Avoid linking your Signal account to a desktop device to reduce your attack surface, if your threat model calls for protecting against [:material-bug-outline: Passive Attacks](https://www.privacyguides.org/en/basics/common-threats/#security-and-privacy){ .pg-orange }.
```

2024-08-24 03:27 UTC, jonaharagon commented on docs/real-time-communication.md
> +Note that by using Molly, you are extending your trust to another party, as you now need to trust the Molly team as well as the Signal team.
is this comma necessary? idk looks off to me

```suggestion
Note that by using Molly you are extending your trust to another party, as you now need to trust the Molly team as well as the Signal team.
```

could also be:

```suggestion
Note that you are trusting multiple parties by using Molly, as you now need to trust the Signal team *and* the Molly team to deliver safe updates.
```

2024-08-24 03:32 UTC, redoomed1 commented on docs/real-time-communication.md
> +Note that by using Molly, you are extending your trust to another party, as you now need to trust the Molly team as well as the Signal team.
:+1:  I like the emphasis on "and" in your second suggestion.

2024-08-24 03:42 UTC, jonaharagon commented on docs/real-time-communication.md
> +
I think we could probably mention this on this page as well:

```suggestion

There is a version of Molly called **Molly-FOSS** which removes proprietary code like the Google services used by both Signal and Molly, at the expense of some features like push notifications. There is also a version called [**Molly-UP**](https://github.com/mollyim/mollyim-android/tree/main?tab=readme-ov-file#unifiedpush) which is based on Molly-FOSS and adds back support for push notifications with UnifiedPush, but it requires self-hosting a program on a separate computer to function. All three versions of Molly provide the same security improvements.

```

(not linking to Molly-FOSS because the download links are the same as Molly's)

2024-08-24 03:48 UTC, redoomed1 commented on docs/real-time-communication.md
> +
Good idea. I even think that the line about reproducible builds can be moved here.

I was hesitant to do that before due to the length of the listing, but since Molly's occupying a subheading, I guess that's not too much of a concern.

2024-08-24 04:14 UTC, jonaharagon commented
Regarding https://github.com/privacyguides/privacyguides.org/pull/2729/commits/99c5afe86339fed8974812d2c47da6c806cc5d6d I'll note that I don't think it's absolutely _necessary_ to remove parts from the blog post to add here, we can have some duplicate information in multiple locations (i.e. wherever people are likely to read). I think either way works though, whatever you think reads best 👍

2024-08-24 04:20 UTC, redoomed1 commented
> we can have some duplicate information in multiple locations (i.e. wherever people are likely to read)

:+1: Understood. I think that the info about reproducible builds and Molly versions should just be under the listing on the RTC page, since it's relevant if/when the reader chooses to install the app.

I will keep your rule of thumb mind and catch myself whenever I feel like I'm on a de-duplication spree :smile:

2024-08-25 04:35 UTC, dngray approved these changes

2024-08-25 04:37 UTC, dngray approved these changes

2024-08-25 04:49 UTC, merged

2024-08-25 12:10 UTC, I-I-IT commented
Sorry, but why are those changes made with little prior consultation ? 
Only 4 people approved the change...