update: Add note about YouTube's changes and reorder YT frontends
privacyguides/privacyguides.org pull request #2735
Opened 2024-08-25 02:29 UTC by redoomed1

Changes proposed in this PR:

- YouTube frontends
  - Add note to the YouTube section of the Frontends page that briefly summarizes YouTube's changes and suggests what readers can do if they find that one frontend is unreliable
    - Relevant discussion: [[1](https://discuss.privacyguides.net/t/remove-libretube/20087/55)] [[2](https://discuss.privacyguides.net/t/remove-libretube/20087/64)]
    - I think that this is the best way to move forward if one YouTube frontend exhibits reliability issues. The threat of YouTube making more changes to its API are a looming presence for these frontends, and frontend maintainers are just doing their best. Rather than remove a frontend because it doesn't work at the moment, I think it's more reasonable to ask readers to switch to another one. In fact, that's what most of the community members in the linked thread did when LibreTube exhibited issues.
  - For FreeTube and Yattee, mention the APIs they use to extract information from YouTube
  - Reorder the YouTube frontends from cross-platform to platform-specific
    - Invidious and Piped (accessible from any web browser) :arrow_right: FreeTube (desktop) :arrow_right: Yattee (Apple OSes) :arrow_right: LibreTube and NewPipe (Android only)
  - Remove mention that you can log in to a Piped instance on LibreTube to sync subscriptions and playlists
    - Reason: The warning admonition under the Piped card advises readers to not log in to any accounts. This should apply to LibreTube as well.
- For ProxiTok and Invidious, mention that there are some I2P instances
- Remove mention of Tor instances in the Redlib card, as the list of instances only shows clearnet instances
- Swap the positions of the two lists of criteria
  - Reason: I think it makes more sense to first present criteria that explains why certain sites are not considered for frontends, then present criteria for evaluating the frontends for sites which do have a reason for using such a tool.
- Add threat model label to this page

<summary>

- [x] I agree to the terms listed below:
  <details><summary>Contribution terms (click to expand)</summary>
  1) I am the sole author of this work.
  2) I agree to grant Privacy Guides a perpetual, worldwide, non-exclusive, transferable, royalty-free, irrevocable license with the right to sublicense such rights through multiple tiers of sublicensees, to reproduce, modify, display, perform, relicense, and distribute my contribution as part of this project.
  3) I have disclosed any relevant conflicts of interest in my post.
  4) I agree to the Community Code of Conduct.
  </details>

2024-08-25 05:01 UTC, dngray approved these changes

2024-09-08 02:25 UTC, kimg45 requested changes

2024-09-08 02:25 UTC, kimg45 commented on docs/frontends.md
> +Piped is useful if you want to use [SponsorBlock](https://sponsor.ajay.app) without installing an extension or to access age-restricted content without an account. It does not provide privacy by itse
```suggestion
Piped is useful if you want to use [SponsorBlock](https://sponsor.ajay.app) without installing an extension. It does not provide privacy by itself, and we don’t recommend logging into any accounts.
```

2024-09-08 02:25 UTC, kimg45 commented on docs/frontends.md
> +Piped is useful if you want to use [SponsorBlock](https://sponsor.ajay.app) without installing an extension or to access age-restricted content without an account. It does not provide privacy by itse
Age restricted content doesn't seem to work anymore, even methods like using embeds are broken now. Seems Youtube has cracked down on that.

2024-10-04 17:54 UTC, kimg45 approved these changes

2024-10-24 04:52 UTC, merged

2024-10-24 04:52 UTC, dngray approved these changes