update: Note beta status of GPG Suite on macOS Sonoma
privacyguides/privacyguides.org pull request #2738
Opened 2024-08-27 17:22 UTC by redoomed1

List of changes proposed in this PR:

- Add admonition mentioning that GPG Tools does not yet have a stable release for macOS Sonoma, which directly affects the Apple Mail (macOS) recommendation
  - Relevant discussion: https://discuss.privacyguides.net/t/apple-mail-no-longer-meets-minimum-criteria/14950
  - This note is initially intentionally conservative because I'm not sure if there should be an actionable suggestion for this. Would it make sense to advise macOS Sonoma users to use Thunderbird instead?

2024-08-29 15:02 UTC, kimg45 commented
GPG Suite is also in the Encryption Software so might be good to add the warning there too. Honestly the requirement to support OpenPGP specifically is strange to me. Apple Mail supports E2EE mail through S/MIME.

2024-08-29 15:22 UTC, kimg45 requested changes
Add the same message to the Encryption Software section.

2024-08-29 15:58 UTC, kimg45 approved these changes

2024-08-31 05:07 UTC, dngray commented
> OpenPGP specifically is strange to me. Apple Mail supports E2EE mail through S/MIME.

The main reason I think is S/MIME isn't really used, requires you to pay for a certificate and your provider needs to [trust the CA](https://kb.mailbox.org/en/private/security-privacy-article/s-mime-encryption/#smime-certificates-compatible-with-mailboxorg) chosen.

2024-09-02 01:39 UTC, dngray approved these changes

2024-09-02 01:41 UTC, merged