docs: Transfer security criteria from developer reqs to specific criteria
privacyguides/privacyguides.org pull request #2747
Opened 2024-09-02 17:51 UTC by redoomed1

List of changes proposed in this PR:

This PR sprang from the discussion in https://github.com/privacyguides/privacyguides.org/pull/2727#issuecomment-2306972391 and some discussion in the team chat.

- General Criteria meta page
  - Remove the security whitepaper requirement from the developer self-submission requirements
    - Reason: In the current wording, this req only applies to certain categories of tools: "a project that involves handling of sensitive information like a messenger, password manager, encrypted cloud storage, etc." As such, I don't think it makes much sense to mention the req here. Rather, I think it is better to lay out this requirement in the specific criteria of tool categories where it applies (e.g., the criteria for cloud-based password managers).
  - Remove the line about third-party audit status
    - Reason: Like the whitepaper req, this only applies to certain categories of tools, so it's somewhat misplaced on this page. 
    - Moreover, requesting a developer for information about whether they have an audit lined up doesn't make much sense to me. The *promise* of a *future* audit shouldn't be taken into account when they are evaluated for inclusion on the site. **Either they have one at the time of evaluation, or they don't.** A developer putting it out to the world that they have requested a third-party audit is tantamount to not having one.
- Cloud Storage page
  - Add security whitepaper minimum req to criteria to cover the first change in the previous section
- Messengers page
  - Add security whitepaper minimum req to criteria to cover the first change in the General Criteria section
  - Apply specific [guidance about the language for requirements](https://www.privacyguides.org/en/meta/writing-style/#use-must-for-requirements) from the Writing Style page to the criteria

2024-09-09 07:57 UTC, jonaharagon requested changes

2024-09-09 07:57 UTC, jonaharagon commented on docs/real-time-communication.md
> +- Must have thoroughly documented encryption and security practices.
As I've just pointed out at https://github.com/privacyguides/privacyguides.org/pull/2727#discussion_r1749748853 I think it might be intentional that this is only a stated requirement for developer self-submissions, and not as a requirement to be recommended.

The logic being: There may be ways for us to evaluate the security practices of a tool without this documentation, but if a developer is going to ask us to look at their project directly then there is a heightened expectation of work they should be putting in to make their project clear to us.

I am "requesting changes" to block this for now because **if** we do decide we actually want this to be our criteria, then we would have to remove some tools as pointed out in the other PR.

2024-09-19 20:40 UTC, blacklight447 approved these changes

2024-10-28 02:40 UTC, kimg45 commented on docs/real-time-communication.md
> +- Must have thoroughly documented encryption and security practices.
Yeah especially since we're requiring a third party audit as well. I think someone like trail of bits is going to be able to do a much deeper analysis of it than we ever could anyway.

2024-10-29 02:23 UTC, redoomed1 commented on docs/real-time-communication.md
> +- Must have thoroughly documented encryption and security practices.
> The logic being: There may be ways for us to evaluate the security practices of a tool without this documentation, but if a developer is going to ask us to look at their project directly then there is a heightened expectation of work they should be putting in to make their project clear to us.

Thank you for the explanation! It really clears up why the security whitepaper requirement and 3p audit status is just for developer self-submissions. In that case, it makes sense that they remain on the General Criteria page.

I also understand that the General Criteria should be kept as succinct as possible, so maybe the explanation you wrote here could be something to include in the Volunteer Handbook.

2024-10-29 02:23 UTC, closed without merging