Correct AdGuard Description
privacyguides/privacyguides.org pull request #2762
Opened 2024-09-15 20:41 UTC by kimg45

List of changes proposed in this PR:

- Updated description since Safari already blocks tracker by default

2024-09-15 21:58 UTC, jonaharagon requested changes
changes in `mobile-browsers.md` lgtm

2024-09-15 21:58 UTC, jonaharagon commented on docs/tools.md
> +    We recommend **Safari** due to its [anti-fingerprinting](https://webkit.org/blog/15697/private-browsing-2-0/) features and default tracker blocking. It also separates your cookies in private brow
We link to AdGuard in this situation because Safari requires a unique solution to content blocking relative to other browsers, because our typical recommendation is unavailable in Safari.

We also should avoid linking to external resources without context like this. Maybe we can write about the relevant anti-fingerprinting features in a section on the mobile browsers page, or we can just remove this link here because we can link to it on the mobile browsers page in a paragraph that provides more context.

2024-09-16 01:48 UTC, kimg45 commented on docs/tools.md
> +    We recommend **Safari** due to its [anti-fingerprinting](https://webkit.org/blog/15697/private-browsing-2-0/) features and default tracker blocking. It also separates your cookies in private brow
Yeah I was just trying to make it look more like the Firefox one where it links to the Mozilla resource on their feature.

2024-09-16 04:18 UTC, jonaharagon commented on docs/tools.md
> +    We recommend **Safari** due to its [anti-fingerprinting](https://webkit.org/blog/15697/private-browsing-2-0/) features and default tracker blocking. It also separates your cookies in private brow
Oh, that's a good point. Hm now I don't know, I kind of don't like the Firefox one either, but I'll see if someone else wants to chime in on this.

2024-09-19 20:42 UTC, blacklight447 commented on docs/tools.md
> +    We recommend **Safari** due to its [anti-fingerprinting](https://webkit.org/blog/15697/private-browsing-2-0/) features and default tracker blocking. It also separates your cookies in private brow
Honestly this looks fine as is to me.

2024-09-19 20:42 UTC, blacklight447 approved these changes

2024-09-19 21:08 UTC, jonaharagon approved these changes

2024-09-19 21:30 UTC, merged