update: iOS Overview
privacyguides/privacyguides.org pull request #2782
Opened 2024-10-19 19:12 UTC by redoomed1

List of changes proposed in this PR:

- Replace all instances of "Apple ID" with "Apple Account" to reflect the [change](https://account.apple.com/faq) in iOS 18
- Update Wi-Fi section to reflect new MAC randomization setting
- Note Bluetooth behavior after system updates
- Update names of settings that have changed
- Add more switches in Analytics & Improvements section

2024-10-23 16:32 UTC, kimg45 approved these changes

2024-10-28 02:28 UTC, kimg45 requested changes

2024-10-28 02:28 UTC, kimg45 commented on docs/os/ios-overview.md
> +Rather than allow an app to access all the photos on your device, you can allow it to only access to whichever photos you choose by tapping on the "Select Photos..." option in the permission dialog.
```suggestion
Rather than allow an app to access all the photos on your device, you can allow it to only access whichever photos you choose by tapping on the "Select Photos..." option in the permission dialog. You can change photo access permissions at any time by navigating to **Settings** → **Privacy & Security** → **Photos**.
```

2024-10-28 02:28 UTC, kimg45 commented on docs/os/ios-overview.md
> +In addition to locking apps behind biometrics, you can also hide apps so that they don't appear on the Home Screen, App Library, the app list in **Settings**, etc. While hiding apps may be useful in
```suggestion
In addition to locking apps behind biometrics, you can also hide apps so that they don't appear on the Home Screen, App Library, the app list in **Settings**, etc. While hiding apps may be useful in situations where you have to hand your unlocked phone to someone else, the concealment provided by the feature is not absolute, as a hidden app is still visible in some places such as the battery usage list.
```

Redundant since hiding an app requires you to lock it first.

2024-10-28 02:38 UTC, redoomed1 commented on docs/os/ios-overview.md
> +In addition to locking apps behind biometrics, you can also hide apps so that they don't appear on the Home Screen, App Library, the app list in **Settings**, etc. While hiding apps may be useful in
I'm not following. Locking an app with biometrics doesn't block notifications; it just obscures its contents. I think that there's a palpable difference between the two—receiving a notification likely will get you to unlock and check the app—which is the reason for this sentence.

2024-10-28 03:02 UTC, kimg45 approved these changes

2024-10-29 18:07 UTC, friadev requested changes

2024-10-29 18:15 UTC, friadev approved these changes

2024-10-30 07:20 UTC, friadev approved these changes

2024-10-30 19:11 UTC, friadev requested changes

2024-10-30 19:11 UTC, friadev commented on docs/os/ios-overview.md
> +iOS offers the ability to lock most apps behind Touch ID/Face ID or your passcode, which can be useful for protecting sensitive content in apps which do not provide the option themselves. You can loc
```suggestion
iOS offers the ability to lock most apps behind Touch ID/Face ID or your passcode, which can be useful for protecting sensitive content in apps which do not provide the option themselves. You can lock an app by long-pressing on it and selecting **Require Face ID/Touch ID**. Any app locked in this way requires biometric authentication whenever opening it or accessing its contents in other apps. Also, notification previews for locked apps will not be shown.
```

2024-10-30 19:11 UTC, friadev commented on docs/os/ios-overview.md
> +iOS offers the ability to lock most apps behind Touch ID/Face ID or your passcode, which can be useful for protecting sensitive content in apps which do not provide the option themselves. You can loc
Apple officially calls it a long-press https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/handling_uikit_gestures/handling_long-press_gestures

2024-10-30 19:11 UTC, friadev commented on docs/os/ios-overview.md
> +You can hide an app by long tapping on it and selecting **Require Face ID/Touch ID** → **Hide and Require Face ID/Touch ID**. Note that pre-installed Apple apps, as well as the default web browser an
```suggestion
You can hide an app by long-pressing on it and selecting **Require Face ID/Touch ID** → **Hide and Require Face ID/Touch ID**. Note that pre-installed Apple apps, as well as the default web browser and email app, cannot be hidden. Hidden apps reside in a **Hidden** folder at the bottom of the App Library, which can be unlocked using biometrics. This folder appears in the App Library whether you hid any apps or not, which provides you a degree of plausible deniability.
```

2024-10-30 22:01 UTC, friadev approved these changes

2024-11-02 23:08 UTC, dngray approved these changes

2024-11-02 23:09 UTC, merged