Update VPN section info,  complete it and add some criterias
privacyguides/privacyguides.org pull request #2788
Opened 2024-10-27 19:43 UTC by I-I-IT

List of changes proposed in this PR:

-It adds much needed information about Mullvad's new obfuscation tech, fixes a few quirks and add some info. More importantly, I introduced new criterias that all current VPN providers meet. Of course, those might need discussion in the forum.

Original changelog:

Justifcation for a few of the changes. First, while Proton technically has ipv6 support on Linux, it didn't work for me, so I didn't include it. Second, the requirements for FDE/ram servers make sense to prevent logging by malicious employees. Mullvad/IVPN are ram-only while Proton has FDE. Third, the requirements for the jurisdiction is to prevent cases like RiseUP VPN (https://riseup.net/en/about-us/press/canary-statement).

2024-10-28 01:53 UTC, kimg45 requested changes

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +Proton [now supports IPv6](https://protonvpn.com/support/prevent-ipv6-vpn-leaks/) in their browser extension but only 80% of their servers are IPv6-compatible. On the other platforms, the Proton VPN
```suggestion
Proton [now supports IPv6](https://protonvpn.com/support/prevent-ipv6-vpn-leaks/) in their browser extension and Linux client. On the other platforms, the Proton VPN applications will block all outgoing IPv6 traffic, so you don't have to worry about your IPv6 address being leaked, but you will not be able to connect to any IPv6-only sites, and you will not be able to connect to Proton VPN from an IPv6-only network.
```

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +Proton [now supports IPv6](https://protonvpn.com/support/prevent-ipv6-vpn-leaks/) in their browser extension but only 80% of their servers are IPv6-compatible. On the other platforms, the Proton VPN
I think stating the exact percentage of servers that offer IPv6 support isn't as important as saying which platforms support it. Plus it'll get outdated quickly anyway.

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
>  #### :material-alert-outline:{ .pg-orange } No IPv6 Support
```suggestion
#### :material-alert-outline:{ .pg-orange } Limited IPv6 Support
```

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
```suggestion
```

Not very helpful since it doesn't specify what backup method to use. I'd rather just keep this focused on Proton's feature.

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
```suggestion
```

Same as above

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +IVPN has obfuscation modes using the [v2ray](https://v2ray.com/en/index.html) protocol which helps in situations where VPN protocols like OpenVPN or Wireguard are blocked. Currently this feature is o
```suggestion
IVPN has obfuscation modes using the [v2ray](https://v2ray.com/en/index.html) project which helps in situations where VPN protocols like OpenVPN or Wireguard are blocked. Currently this feature is only available on Desktop and [iOS](https://ivpn.net/knowledgebase/ios/v2ray). It has two modes where it can use [VMess](https://guide.v2fly.org/en_US/basics/vmess.html) over QUIC or TCP connections. QUIC is a modern protocol with better congestion control and therefore may be faster with reduced latency. The TCP mode makes your data appear as regular HTTP traffic.
```

I can't find anywhere in the v2ray documentation where they refer to it as a protocol.

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +**Mullvad** is a fast and inexpensive VPN with a serious focus on transparency and security. They have been in operation since 2009. Mullvad is based in Sweden and offers a 30-day money-back guarante
```suggestion
**Mullvad** is a fast and inexpensive VPN with a serious focus on transparency and security. They have been in operation since 2009. Mullvad is based in Sweden and offers a 30-day money-back guarantee for payment methods that allow it.
```

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +Mullvad, in addition to accepting credit/debit cards and PayPal, accepts Bitcoin, Bitcoin Cash, **Monero** and **cash/local currency** as anonymous forms of payment. Prepaid cards with redeem codes a
```suggestion
Mullvad, in addition to accepting credit/debit cards and PayPal, accepts Bitcoin, Bitcoin Cash, **Monero** and **cash/local currency** as anonymous forms of payment. Prepaid cards with redeem codes are also available. Mullvad also accepts Swish and bank wire transfers, as well as a few European payment systems.
```

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
```suggestion
```

Same as above.

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +-Basic censorship resistance that can bypass firewalls without DPI.
```suggestion
- Basic censorship resistance that can bypass firewalls without DPI.
```

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +While not strictly requirements, there are some factors we looked into when determining which providers to recommend. These include content blocking functionality, warrant canaries, excellent custome
```suggestion
While not strictly requirements, there are some factors we looked into when determining which providers to recommend. These include content blocking functionality, warrant canaries, multi-hop connections, excellent customer support, the number of allowed simultaneous connections, etc.
```

2024-10-28 01:53 UTC, kimg45 commented on docs/vpn.md
> +While not strictly requirements, there are some factors we looked into when determining which providers to recommend. These include content blocking functionality, warrant canaries, excellent custome
Not sure why this was removed?

2024-10-28 01:53 UTC, kimg45 commented on includes/abbreviations.en.txt
> +*[DPI]: Deep Packet Inspection identifies and blocks packet with specific payloads. It is used by advanced censorship systems, such as China's Great Firewall (GFW).
```suggestion
*[DPI]: Deep Packet Inspection
```

2024-10-28 10:17 UTC, I-I-IT commented on docs/vpn.md
> +Proton [now supports IPv6](https://protonvpn.com/support/prevent-ipv6-vpn-leaks/) in their browser extension but only 80% of their servers are IPv6-compatible. On the other platforms, the Proton VPN
About the Linux client supporting ipv6, I purposely didn't mention it, because in my testing it didn't work (they had the ipv6 kill-switch enabled despite ipv6 being enabled in their app...)

2024-10-28 10:19 UTC, I-I-IT commented on docs/vpn.md
> +IVPN has obfuscation modes using the [v2ray](https://v2ray.com/en/index.html) protocol which helps in situations where VPN protocols like OpenVPN or Wireguard are blocked. Currently this feature is o
![2630](https://github.com/user-attachments/assets/5659413a-46b5-4440-b1b1-1953d6d6f90a)
Saying that you can use a project doesn't really make sense IMO. But I will not fight over it.

2024-10-28 10:24 UTC, I-I-IT commented on docs/vpn.md
> +While not strictly requirements, there are some factors we looked into when determining which providers to recommend. These include content blocking functionality, warrant canaries, excellent custome
Because it is already a criteria, so it is a duplicate to put it here.

2024-10-28 10:27 UTC, I-I-IT commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
This is important so people have for example two VPNs. But maybe this could be clearer.

2024-10-28 10:29 UTC, I-I-IT commented on includes/abbreviations.en.txt
> +*[DPI]: Deep Packet Inspection identifies and blocks packet with specific payloads. It is used by advanced censorship systems, such as China's Great Firewall (GFW).
Let's keep the first sentence, but not the example about China GFW. The goal of definitions is to explain terms that people aren't familiar with, and Deep Packet Inspection isn't self explanatory.

2024-10-28 15:54 UTC, kimg45 commented on docs/vpn.md
> +IVPN has obfuscation modes using the [v2ray](https://v2ray.com/en/index.html) protocol which helps in situations where VPN protocols like OpenVPN or Wireguard are blocked. Currently this feature is o
How about just saying "using v2ray"?

2024-10-28 16:36 UTC, kimg45 commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
I think just leave it out, maybe it could go somewhere else.

2024-10-28 18:08 UTC, kimg45 commented on includes/abbreviations.en.txt
> +*[DPI]: Deep Packet Inspection identifies and blocks packet with specific payloads. It is used by advanced censorship systems, such as China's Great Firewall (GFW).
Is this version better?

2024-10-28 20:09 UTC, jonaharagon reviewed
I'm happy with all of @friadev's suggested changes here.

2024-10-28 20:09 UTC, jonaharagon commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
> https://github.com/net4people/bbs/issues/384#issue-2461515121

Has anyone posted about this on our forum? It'd be nice if we talked about this topic there, where people would be able to seek assistance or ask questions.

2024-10-28 21:39 UTC, I-I-IT commented on includes/abbreviations.en.txt
> +*[DPI]: Deep Packet Inspection identifies and blocks packet with specific payloads. It is used by advanced censorship systems, such as China's Great Firewall (GFW).
LGTM

2024-10-28 21:40 UTC, I-I-IT commented on docs/vpn.md
> +IVPN has obfuscation modes using the [v2ray](https://v2ray.com/en/index.html) protocol which helps in situations where VPN protocols like OpenVPN or Wireguard are blocked. Currently this feature is o
Make sense

2024-10-28 21:47 UTC, I-I-IT commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
github.com/net4people/bbs is already a forum about censorship circumvention. Unfortunately, our audience isn´t very large in highly-censored countries AFAIK. There was a[ topic about censorship evasion](https://discuss.privacyguides.net/t/do-mullvad-and-ivpn-have-any-censorship-resistant-technologies/21462/17), but it didn´t get much traction.

I think it is better to link to BBS, as they are more up to date with censorship.

> I think just leave it out, maybe it could go somewhere else. It's also pretty repetitive having the same thing three times.

Could it be put in the introduction?

2024-10-28 21:51 UTC, friadev commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
Yeah I think it would fit better there.

2024-10-29 03:02 UTC, redoomed1 requested changes
Thanks for the PR!

<del>In addition to the changes I suggested below, the IPv6 entry for Proton VPN in the randomized table should be updated as well.</del> | Done here: https://github.com/privacyguides/privacyguides.org/pull/2788/commits/25fcc8cdc236b572fc2a486070e7cb78d824260d

2024-10-29 04:25 UTC, jonaharagon commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
I wonder if it would fit better as informational content on [`basics/vpn-overview.md`](https://github.com/privacyguides/privacyguides.org/blob/main/docs/basics/vpn-overview.md) instead of this page.

2024-10-29 15:13 UTC, I-I-IT commented on docs/vpn.md
> +- Obfuscation technology which camouflage the true nature of the internet traffic, allowing user to circumvent advanced internet censorship with DPI.
This thought, is not completely correct. (Sorry to be nitpicky). 
"Regular internet traffic" is ambiguous, and can go from HTTP(S) traffic to video calling. Shadowsocks specifically disguise VPN traffic as HTTP traffic.
Also, I would rather say users than customers.

2024-10-29 15:17 UTC, I-I-IT commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
I was thinking anti-censorship might deserve a separate page in Basics. Thoughts?

2024-10-29 15:18 UTC, I-I-IT commented on docs/vpn.md
> +Mullvad is very transparent about which nodes they [own or rent](https://mullvad.net/en/servers). They use [ShadowSocks](https://shadowsocks.org) in their ShadowSocks + OpenVPN (Desktop) and Wireguar
I agree, it is a bit of a duplicate. Do I approved this change and then modify it, or would you rather modify you suggestion?

2024-10-29 15:19 UTC, redoomed1 commented on docs/vpn.md
> +- Obfuscation technology which camouflage the true nature of the internet traffic, allowing user to circumvent advanced internet censorship with DPI.
No need to apologize. In that case, my suggestion for this part is just for typos.

2024-10-29 15:22 UTC, redoomed1 commented on docs/vpn.md
> +Mullvad is very transparent about which nodes they [own or rent](https://mullvad.net/en/servers). They use [ShadowSocks](https://shadowsocks.org) in their ShadowSocks + OpenVPN (Desktop) and Wireguar
Yeah, I can modify this suggestion, and then you can go over it to see if the information is correct (since you have more knowledge than I do about Shadowsocks and DAITA, given that you've talked about both on the forum).

2024-10-29 15:25 UTC, I-I-IT commented on docs/vpn.md
> +Mullvad is very transparent about which nodes they [own or rent](https://mullvad.net/en/servers). They use [ShadowSocks](https://shadowsocks.org) in their ShadowSocks + OpenVPN (Desktop) and Wireguar
Seems good to me.

2024-10-29 16:18 UTC, redoomed1 commented on docs/vpn.md
> +* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: "UDP-over-TCP" and ["Wireguard over Shadowsocks"](https://mullvad.net/en/blog/introducing-shadowsocks-obfuscation-for-wireguard).
Also see https://github.com/privacyguides/privacyguides.org/pull/2788#discussion_r1820000693 for the updated section that includes a short description of DAITA

2024-10-29 18:11 UTC, I-I-IT commented on docs/vpn.md
> +* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: "UDP-over-TCP" and ["Wireguard over Shadowsocks"](https://mullvad.net/en/blog/introducing-shadowsocks-obfuscation-for-wireguard).
> I couldn't find much info about "UDP-over-TCP" in the Mullvad docs, but I think it's the same as Shadowsocks + OpenVPN?

No, it's a different option, and is only available for Wireguard. It was the only option on mobile before they introduced Wireguard (WG) over Shadowsocks.

>Other anti-censorship techniques by Proton VPN and IVPN? 
Yes, mainly toward Proton as IVPN has some V2RAY.
>Is the content in the linked GitHub issue still relevant?
Mostly, but China actually doesn't block Shadowsocks, although this doesn't mean it couldn't happen.

2024-10-29 18:20 UTC, redoomed1 commented on docs/vpn.md
> +* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: "UDP-over-TCP" and ["Wireguard over Shadowsocks"](https://mullvad.net/en/blog/introducing-shadowsocks-obfuscation-for-wireguard).
> No, it's a different option, and is only available for Wireguard. It was the only option on mobile before they introduced Wireguard (WG) over Shadowsocks.

Ahh, now I think I see it. The "Obfuscation" mode is UDP-over-TCP, while "Bridge mode" is OpenVPN through Shadowsocks. Thanks for the clarification.

2024-10-29 18:41 UTC, redoomed1 commented on docs/vpn.md
> +* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: "UDP-over-TCP" and ["Wireguard over Shadowsocks"](https://mullvad.net/en/blog/introducing-shadowsocks-obfuscation-for-wireguard).
@I-I-IT I updated my suggestion based on your feedback.

I decided to leave out the bit about Mullvad's obfuscation methods being more effective than Proton's, since there's already a section in the Proton anti-censorship section which disclaims that Stealth isn't as effective as circumventing sophisticated filtering. I also included the paper you linked as a replacement for the GitHub issue.

2024-10-29 21:59 UTC, I-I-IT commented on docs/vpn.md
> +* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: "UDP-over-TCP" and ["Wireguard over Shadowsocks"](https://mullvad.net/en/blog/introducing-shadowsocks-obfuscation-for-wireguard).
>* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: UDP-over-TCP (the "Obfuscation" option), OpenVPN via Shadowsocks (the "Bridge mode" option only available on their desktop apps), 

Let me take screenshots so you see better how those modes are.
On mobile:
![2647](https://github.com/user-attachments/assets/2c08280d-19bd-4b5b-8703-7a85883373d4)

2024-10-29 22:24 UTC, redoomed1 commented on docs/vpn.md
> +* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: "UDP-over-TCP" and ["Wireguard over Shadowsocks"](https://mullvad.net/en/blog/introducing-shadowsocks-obfuscation-for-wireguard).
Thanks for all the helpful screenshots! I just reverted this section back to the original + updated and added the last line. I'll defer to you for what more info to include and how to format it. Feel free to change it as you see fit.

2024-10-30 09:56 UTC, I-I-IT commented on docs/vpn.md
> +* **Obfuscation modes**: Mullvad has two built-in obfuscation modes: "UDP-over-TCP" and ["Wireguard over Shadowsocks"](https://mullvad.net/en/blog/introducing-shadowsocks-obfuscation-for-wireguard).
Actually, how can I edit your suggestion while keeping you as a coauthor?

2024-10-30 10:06 UTC, friadev commented on docs/vpn.md
> +Always have a backup method, in case [censors break your current technique](https://github.com/net4people/bbs/issues/384#issue-2461515121).
Maybe. This should go on a page like that I think rather than here.

2024-10-30 22:41 UTC, friadev approved these changes

2024-11-01 03:45 UTC, redoomed1 approved these changes
Thanks for all your work incorporating all of our feedback! I suggest some changes below for consistency reasons (making most of the criteria noun phrases), but the PR overall looks good to me.

2024-11-01 03:45 UTC, redoomed1 commented on docs/vpn.md
> +| [Proton](#proton-vpn) | 112+ | :material-check:{ .pg-green } | :material-information-outline:{ .pg-blue } Partial Support | :material-information-outline:{ .pg-blue } Partial Support | Cash
```suggestion
| [Proton](#proton-vpn) | 112+ | :material-check:{ .pg-green } | :material-alert-outline:{ .pg-orange } Partial Support | :material-information-outline:{ .pg-blue } Limited Support | Cash
```

2024-11-01 03:45 UTC, redoomed1 commented on docs/vpn.md
> +- Obfuscation technology which camouflages the true nature of internet traffic, allowing users to circumvent advanced internet censorship through methods like DPI.
```suggestion
- Obfuscation technology which camouflages the true nature of internet traffic, allowing users to circumvent advanced internet censorship methods like DPI.
```

2024-11-01 03:45 UTC, redoomed1 commented on docs/vpn.md
> +- VPN servers have full-disk encryption or are RAM-only.
```suggestion
- VPN servers that use full-disk encryption or are RAM-only.
```

2024-11-01 03:45 UTC, redoomed1 commented on docs/vpn.md
> +- VPN servers are RAM-only.
```suggestion
- RAM-only VPN servers.
```

2024-11-01 03:45 UTC, redoomed1 commented on docs/vpn.md
> +- The company is based in a jurisdiction where it cannot be forced to do secret logging.
```suggestion
- Company based in a jurisdiction where it cannot be forced to do secret logging.
```

2024-11-01 03:45 UTC, redoomed1 commented on docs/vpn.md
>  - Supports [IPv6](https://en.wikipedia.org/wiki/IPv6). We expect that servers will allow incoming connections via IPv6 and allow you to access services hosted on IPv6 addresses.
```suggestion
- [IPv6](https://en.wikipedia.org/wiki/IPv6) support. We expect that servers will allow incoming connections via IPv6 and allow you to access services hosted on IPv6 addresses.
```

2024-11-01 10:02 UTC, I-I-IT commented
> Thanks for all your work incorporating all of our feedback! I suggest some changes below for consistency reasons (making most of the criteria noun phrases), but the PR overall looks good to me.

You are welcome, I'm glad we can quickly update sections because it is important for PG credibility. I take this opportunity to ask you to please review my [Pull Request ](github.com/privacyguides/privacyguides.org/pull/2525) about private AI chat ([preview](https://2525--glowing-salamander-8d7127.netlify.app/en/ai-chat/#duckduckgo-ai-chat))

2024-11-01 10:22 UTC, friadev requested changes

2024-11-01 10:22 UTC, friadev commented on docs/vpn.md
> +- Basic censorship resistance that can bypass firewalls without DPI.
```suggestion
- Censorship resistance features
```
I don't think we can prove whether these features can bypass any given firewall with or without DPI so I think we should just broaden it a bit to just include anti-censorship features.

2024-11-01 10:22 UTC, friadev commented on docs/vpn.md
> +- Obfuscation technology which camouflages the true nature of internet traffic, allowing users to circumvent advanced internet censorship methods like DPI.
```suggestion
- Obfuscation technology which camouflages the true nature of internet traffic.
```
Same here, I don't know how we can prove it can bypass any given firewall or DPI implementation.

2024-11-05 20:05 UTC, friadev approved these changes

2024-11-10 08:13 UTC, dngray approved these changes

2024-11-10 08:33 UTC, dngray approved these changes

2024-11-10 08:33 UTC, merged