Thunderbird Mobile's Stable version is now available
privacyguides/privacyguides.org pull request #2795
Opened 2024-10-30 14:52 UTC by Guru-25

List of changes proposed in this PR:

- Thunderbird released its [stable](https://github.com/thunderbird/thunderbird-android/releases/latest) version for Android
- Changed K-9 Mail to Thunderbird in Email Clients

2024-10-30 17:01 UTC, redoomed1 requested changes
Thanks for the PR! Very exciting news!

Since Thunderbird Mobile retains the same branding as the desktop version of Thunderbird and is has its own page on the [official website](https://thunderbird.net/mobile), I don't think that the Android version of Thunderbird needs its own card.

The GitHub releases link can be added to the Downloads section of the cross-platform Thunderbird card, and everything related to K-9 Mail can be removed, including its entry in `tools.md`.

2024-10-30 17:59 UTC, Guru-25 reviewed
- Added Google Play Store link and GitHub releases link for Thunderbird Android in the Downloads section of the cross-platform Thunderbird card.
- Removed K-9 Mail.

2024-10-30 18:22 UTC, redoomed1 approved these changes
Thanks for the swift changes! I suggest some other changes below for consistency reasons, but the PR overall looks good to me.

2024-10-30 18:22 UTC, redoomed1 commented on docs/email-clients.md
> +</div>
Admonitions, particularly the warning type, should be moved to below the card before the "Recommended Configuration" heading since admonitions presumably contain information that should demand the attention of the reader.

See the Brave desktop listing for an example: https://www.privacyguides.org/en/desktop-browsers/#brave

2024-10-30 18:22 UTC, redoomed1 commented on docs/email-clients.md
> +- [:simple-github: GitHub](https://github.com/thunderbird/thunderbird-android/releases)
The Google Play and GitHub releases links should go before the Windows link. See the links under the Download toggle in the Mullvad card for an example: https://www.privacyguides.org/en/vpn/#mullvad

2024-10-30 18:36 UTC, Guru-25 reviewed
- Moved mailing list warning before the "Recommended Configuration" heading.
- Moved the Google Play and GitHub releases links before the Windows link.

2024-10-30 22:40 UTC, friadev approved these changes

2024-11-02 23:16 UTC, dngray approved these changes

2024-11-03 00:13 UTC, merged

2024-11-03 00:13 UTC, dngray approved these changes