update: iOS 18 Browser Recommendations Improvements
privacyguides/privacyguides.org pull request #2802
Opened 2024-11-04 17:14 UTC by friadev

List of changes proposed in this PR:

- added suggestions for new options and reevaluated old ones
- fix Safari intro sentence to reflect that Brave is now recommended on iOS

closes #2797

2024-11-05 04:44 UTC, redoomed1 requested changes

2024-11-05 04:44 UTC, redoomed1 commented on docs/mobile-browsers.md
> +This setting sends your search queries before you press enter, which might cause you to send data you didn't intend to.
```suggestion
This setting sends whatever you type in the address bar to the search engine set in Safari. Disabling search suggestions allows you to more precisely control what data you send to your search engine provider.
```

2024-11-05 04:44 UTC, redoomed1 commented on docs/mobile-browsers.md
> +This setting uses Google Safe Browsing (or Tencent Safe Browsing for users in mainland China or Hong Kong) to protect you while you browse. Disabling this setting is more private but you will sacrifi
```suggestion
This setting uses Google Safe Browsing (or Tencent Safe Browsing for users in mainland China or Hong Kong) to protect you while you browse. As such, your IP address may be logged by your Safe Browsing provider. Disabling this setting will disable this logging, but you will sacrifice some security.
```

2024-11-05 04:44 UTC, redoomed1 commented on docs/mobile-browsers.md
> +>When visiting a webpage, Safari may send information calculated from the webpage address to Apple over OHTTP to determine if relevant highlights are available.
```suggestion
Apple's privacy policy for Safari states:

> When visiting a webpage, Safari may send information calculated from the webpage address to Apple over OHTTP to determine if relevant highlights are available.
```

2024-11-05 04:44 UTC, redoomed1 commented on docs/mobile-browsers.md
> +-[Apple](https://www.apple.com/legal/privacy/data/en/safari/)
```suggestion
```
With my suggestion above to introduce the quote, I don't think it's necessary to link the privacy policy (it's already in the card).

2024-11-05 04:44 UTC, redoomed1 commented on docs/mobile-browsers.md
> +These settings are important so that websites can't access your camera, microphone, and location whenever they want.
```suggestion
These settings ensure that websites can only access your camera, microphone, or location after you explicitly grant them access.
```

2024-11-05 16:44 UTC, redoomed1 approved these changes
Aside from the suggestions below to clarify some parts, LGTM

2024-11-05 16:44 UTC, redoomed1 commented on docs/mobile-browsers.md
> +On iOS, any app that can browse the web is [restricted](https://developer.apple.com/app-store/review/guidelines) to using an Apple-provided [WebKit framework](https://developer.apple.com/documentatio
```suggestion
On iOS, any app that can browse the web is [restricted](https://developer.apple.com/app-store/review/guidelines) to using an Apple-provided [WebKit framework](https://developer.apple.com/documentation/webkit), so a browser like [Brave](#brave) does not use the Chromium engine like its counterparts on other operating systems.
```
Suggesting to expand the abbreviation since it's the first instance of the term on the page

2024-11-05 16:44 UTC, redoomed1 commented on docs/mobile-browsers.md
> +This setting uses Google Safe Browsing (or Tencent Safe Browsing for users in mainland China or Hong Kong) to protect you while you browse. As such, your IP address may be logged by your Safe Browsin
```suggestion
This setting uses Google Safe Browsing (or Tencent Safe Browsing for users in mainland China or Hong Kong) to protect you while you browse. As such, your IP address may be logged by your Safe Browsing provider. Disabling this setting will disable this logging, but you might be more vulnerable to known phishing sites.
```
I think it's better to be more specific about the security trade-off of turning off FWW.

2024-11-10 07:37 UTC, merged

2024-11-10 07:37 UTC, dngray approved these changes