update!: Add local AI chat recommendations
privacyguides/privacyguides.org pull request #2810
Opened 2024-11-12 05:13 UTC by jonaharagon

2024-11-12 05:26 UTC, jonaharagon commented on theme/assets/img/ai-chat/ollama.svg
This isn't an actual SVG image, it appears to be a PNG embedded in an SVG file. This is not going to be well compatible with browsers (and is also just bad), so we need to replace it with the official https://ollama.com/public/ollama.png, or find a real vector file, or make our own (which I think @dngray has done before and knows how to do?)

(from https://github.com/privacyguides/privacyguides.org/pull/2525#discussion_r1837479798)

2024-11-12 05:26 UTC, jonaharagon commented on docs/ai-chat.md
> +[Ethical concerns](https://www.thelancet.com/journals/landig/article/PIIS2588-7500(24)00061-X/fulltext) about AI range from their impact on climate to their potential for discrimination.
@redoomed1:

> The journal doesn't show on the page of the provided link.

https://github.com/privacyguides/privacyguides.org/pull/2525#discussion_r1837474597

2024-11-12 05:27 UTC, jonaharagon commented on theme/assets/img/ai-chat/ollama.svg
Also we need a version of this that works in dark mode

2024-11-12 05:40 UTC, jonaharagon reviewed
I think there are probably too many admonitions on this page

2024-11-12 05:40 UTC, jonaharagon commented on docs/ai-chat.md
> +- [:material-close-outline: Censorship](basics/common-threats.md#avoiding-censorship){ .pg-blue-gray }
Does it? (Especially this last one, what is the censorship connection here?)

2024-11-12 05:40 UTC, jonaharagon commented on docs/ai-chat.md
> +AI models have been trained on massive amounts of public *and* private data. If you are concerned about these practices, you can either refuse to use AI or use [truly open-source models](https://prot
```suggestion
AI models have been trained on massive amounts of public *and* private data. If you are concerned about these practices, you can either refuse to use AI, or use [truly open-source models](https://proton.me/blog/how-to-build-privacy-first-ai) which publicly release and allow you to inspect their training datasets. One such model is [Olmoe](https://allenai.org/blog/olmoe) made by [Allenai](https://allenai.org/open-data).
```

The conclusion drawn after "therefore" I don't think is necessarily inherent to open source models. Like, an open source model _could_ have private/crawled datasets right?

2024-11-12 05:40 UTC, jonaharagon commented on docs/ai-chat.md
> +To help you choose a model that fit your needs, you can look at leaderboards and benchmarks. The most widely-used leaderboard is [LM Arena](https://lmarena.ai/), a "Community-driven Evaluation for Be
```suggestion

To help you choose a model that fits your needs, you can look at leaderboards and benchmarks. The most widely-used leaderboard is [LM Arena](https://lmarena.ai/), a "Community-driven Evaluation for Best AI chatbots". There is also the [OpenLLM Leaderboard](https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard), which focus on the performance of open-weights models on common benchmarks like MMLU-PRO.  However, there are also specialized benchmarks which measure factors like [emotional intelligence](https://eqbench.com/), ["uncensored general intelligence"](https://huggingface.co/spaces/DontPlanToEnd/UGI-Leaderboard), and many [others](https://www.nebuly.com/blog/llm-leaderboards).
```

2024-11-12 05:40 UTC, jonaharagon commented on docs/ai-chat.md
> +Kobold shines best when you are looking for heavy customization and tweaking, such as for roleplaying purposes. It allows you to modify parameters such as the AI model temperature and the AI chat's s
```suggestion
Kobold is best if you are looking for heavy customization and tweaking. It allows you to modify parameters such as the AI model temperature and the AI chat's system prompt. It also supports creating a network tunnel to access AI models from other devices, such as your phone.
```

Not sure if we need to mention roleplaying or other specific use-cases. Can we have an explanation of what temperature is?

2024-11-12 05:40 UTC, jonaharagon commented on docs/ai-chat.md
> +</div>
```suggestion
<p class="admonition-title">Compatibility Issues</p>

Kobold.cpp might not run on computers without AVX/AVX2 support.

</div>
```

2024-11-12 05:40 UTC, jonaharagon commented on docs/ai-chat.md
> +Ollama shines best when you're looking for an AI client that has great compatibility and ease of use. It runs on all desktop platforms and doesn't involve any manual setup, while still using inferenc
```suggestion
Ollama is best if you're looking for an AI client that has great compatibility and ease of use. It runs on all desktop platforms and doesn't involve any manual setup, while still using inference and other techniques to make outputs faster.
```

2024-11-12 05:40 UTC, jonaharagon commented on docs/ai-chat.md
> +<details class="downloads" markdown>
```suggestion

<details class="downloads" markdown>
```

2024-11-12 14:52 UTC, I-I-IT commented on theme/assets/img/ai-chat/ollama.svg
Isn't a PNG file is reasonable if there is no official SVG?

2024-11-12 14:56 UTC, I-I-IT commented on docs/ai-chat.md
> +- [:material-close-outline: Censorship](basics/common-threats.md#avoiding-censorship){ .pg-blue-gray }
Maybe this need some explanation somewhere. Basically, it is useful for anti-censorship for a couple reasons:
1) Offline "data-base" : if your access to a Free internet is cut off, you can have access to world knowledge with just an offline chatbot.
2)"Ghosting" information: nowadays, some 'democratic' countries like India, have tool to order *worldwide* deletion of certain content. But with an AI chat-bot, you have more difficulty suppressing this information.
3)Using local AI models has less censorship because you can modify the system prompt.

2024-11-12 14:57 UTC, I-I-IT commented on docs/ai-chat.md
> +AI models have been trained on massive amounts of public *and* private data. If you are concerned about these practices, you can either refuse to use AI or use [truly open-source models](https://prot
It could defintely have semi-private data like "Your 3AM post on your one subscriber Twitter account".

2024-11-12 16:25 UTC, I-I-IT commented on docs/ai-chat.md
> +Kobold shines best when you are looking for heavy customization and tweaking, such as for roleplaying purposes. It allows you to modify parameters such as the AI model temperature and the AI chat's s
The temperature is defined in abreviations (it change the model creativity/randomness). We could explicitely define it, but it isn't recommended to change it, except for specifi use cases such as roleplaying (where you don't want your model to write a story about a princess every time...)

I think it is useful to mention use-cases to help user choose the ai client that best fit their needs.

2024-11-12 16:28 UTC, I-I-IT commented on docs/ai-chat.md
> +</details>
This is about choosing models -not clients- so it doesn't belong in the client part.This is not recommending hardware, merely informing users what models their system is capable of running.

2024-11-12 16:51 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
Ah, thanks for the clarification. I think my issue here is that this excerpt starts out with a recommendation of a type of RAM. Perhaps its better to invert the order in which the paragraph is presented.

```suggestion
Local models are also fairly accessible as it is possible to run smaller models on modest hardware. A computer with at least 8GB of RAM will be sufficient to run smaller models at lower speeds. Using beefier hardware such as a dedicated GPU with sufficient VRAM or a modern system with fast LPDDR5X memory will offer the best experience. Below is a table with more precise information :

<details class="admonition info" markdown>
<summary>Hardware Requirements for Local Models</summary>

Here are typical requirements for different model sizes:

- 7B parameter models: 8GB RAM minimum, 16GB recommended
- 13B parameter models: 16GB RAM minimum, 32GB recommended
- 70B parameter models: Dedicated GPU with 24GB+ VRAM recommended
- Quantized models (4-bit): Can run with roughly half these requirements

</details>
```
Also, to follow up on Jonah's observation of admonition overuse, the hardware requirements can probably do without the admonition and just be a 3x4 table.

2024-11-12 17:06 UTC, I-I-IT commented on docs/ai-chat.md
> +</details>
Seem right. Yup we can just do a table now that we have split local and cloud providers

2024-11-12 17:11 UTC, redoomed1 commented on docs/ai-chat.md
> +cover: ai-chatbots.webp
```suggestion
cover: ai-chatbots.webp
global:
 - [randomize-element, "table tbody"]
```
Randomizes the table for the local clients; might need to swap the columns and rows

2024-11-12 17:45 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
On second thought, this info can be kept as a list since I added randomization for the tables on this page (for the local clients table). Randomizing this info is not ideal IMO.

2024-11-12 18:00 UTC, jonaharagon commented on docs/ai-chat.md
> +</details>
We can figure out a way to only randomize a specific table too, if we prefer? I don't remember how the random JS works but we can easily modify it if it doesn't support that.

2024-11-12 18:01 UTC, jonaharagon commented on docs/ai-chat.md
> +- [:material-close-outline: Censorship](basics/common-threats.md#avoiding-censorship){ .pg-blue-gray }
I see, I suppose that's fair enough.

2024-11-12 18:03 UTC, jonaharagon commented on theme/assets/img/ai-chat/ollama.svg
A PNG is fine, the problem is that this PNG is embedded in an SVG file which isn't fine. If we replace it with a regular PNG that could work.

We'll probably want to invert this logo and use it for dark mode, which should be fine as it's a simple image.

2024-11-12 18:03 UTC, redoomed1 reviewed
Another effort to cut down admonition use on this page

2024-11-12 18:03 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
```suggestion
Since the release of ChatGPT in 2022, interactions with Large Language Models (LLMs) have become increasingly common. LLMs can help us write better, understand unfamiliar subjects, or answer a wide range of questions. They can statistically predict the next word based on a vast amount of data scraped from the web.

## Ethical and Privacy Concerns about LLMs

Data used to train AI models, however, include a massive amount of _private_ data. Developers of AI software often use [Reinforcement Learning from Human Feedback](https://en.wikipedia.org/wiki/Reinforcement_learning_from_human_feedback) (RLHF) to improve the quality of LLMs, which entails the possibility of AI companies reading your private AI chats as well as storing them. This practice also introduces a risk of data breaches. Furthermore, there is a real possibility that an LLM will leak your private chat information in future conversations with other users.

The popularity of LLMs after the release of ChatGPT has sparked widespread discussion about [ethical concerns](https://www.thelancet.com/journals/landig/article/PIIS2588-7500(24)00061-X/fulltext) surrounding the technology. These range from their impact on climate to their potential for discrimination.

If you are concerned about these practices, you can either refuse to use AI, or use [truly open-source models](https://proton.me/blog/how-to-build-privacy-first-ai) which publicly release and allow you to inspect their training datasets. One such model is [Olmoe](https://allenai.org/blog/olmoe) made by [Allenai](https://allenai.org/open-data).

Alternatively, you can run AI models locally so your data never leaves your device.
```

2024-11-12 18:06 UTC, redoomed1 commented on docs/ai-chat.md
> +- [:material-close-outline: Censorship](basics/common-threats.md#avoiding-censorship){ .pg-blue-gray }
```suggestion
<small>Protects against the following threat(s):</small>

- [:material-server-network: Service Providers](basics/common-threats.md#privacy-from-service-providers){ .pg-teal }
- [:material-account-cash: Surveillance Capitalism](basics/common-threats.md#surveillance-as-a-business-model){ .pg-brown }
- [:material-close-outline: Censorship](basics/common-threats.md#avoiding-censorship){ .pg-blue-gray }
```
As with the other tools that are meant for local/on-device use, I'm adding the service providers label here.

2024-11-12 18:10 UTC, I-I-IT commented
@redoomed1 I am curently doing some changes, so I will try to push them. They add a new table for hardware requirements of AI models and rearrange some sections.

2024-11-12 20:05 UTC, I-I-IT commented on docs/ai-chat.md
> +</details>
Tables are only randomised if you put some randomise flag like on VPN page.

2024-11-12 20:09 UTC, I-I-IT commented on docs/ai-chat.md
> +| Multi-platform | :material-check:{ .pg-green } | :material-check:{ .pg-green } | :material-alert-outline:{ .pg-orange } Size limitations on Windows |
Honestly I just put it for Llamafile because I am not 100% sure you can modify parameters, I think you can from what I remember, but I am not sure.

2024-11-12 20:12 UTC, I-I-IT commented on docs/ai-chat.md
> +[Ethical concerns](https://www.thelancet.com/journals/landig/article/PIIS2588-7500(24)00061-X/fulltext) about AI range from their impact on climate to their potential for discrimination.
We can replace with another link, and I provided it in my comment here https://github.com/privacyguides/privacyguides.org/pull/2810#issuecomment-2471239940

2024-11-12 20:39 UTC, redoomed1 commented
Thanks @I-I-IT ! I'll go over your changes later and tag you as co-author in the commit.

2024-11-12 22:15 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
```suggestion
## Hardware for Local AI Models

Local models are also fairly accessible as it is possible to run smaller models on modest hardware. A computer with at least 8GB of RAM will be sufficient to run smaller models at lower speeds. Using more powerful hardware such as a dedicated GPU with sufficient VRAM or a modern system with fast LPDDR5X memory will offer the best experience.

LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below 6.7B parameters are only good for basic tasks like text summaries, while models between 7B and 13B are a great compromise between quality and speed. Models with advanced reasoning capabilities are generally around 70B.

For consumer-grade hardware, it is generally recommended to use [quantized models](https://huggingface.co/docs/optimum/en/concept_guides/quantization) for the best balance between model quality and performance. Check out the list below for more precise information about the typical requirements for different sizes of quantized models.

| Model Size (in Parameters) | Minimum RAM | Minimum Processor |
|---|---|---|
| 7B | 8GB | Modern CPU (AVX2 support) |
| 13B | 16GB | Modern CPU (AVX2 support) |
| 70B | 72GB | GPU with VRAM |
```
Latest suggestion based on @I-I-IT's provided changes (I condensed some things and added some explanatory sentences based on what I inferred from reading)

Please let me know if anything in it needs to be corrected.

2024-11-12 22:41 UTC, redoomed1 reviewed
All of these suggestions are from @I-I-IT's suggestions in the markdown file they provided. I made some changes to improve readability and condense sections without stripping out any information.

2024-11-12 22:41 UTC, redoomed1 commented on docs/ai-chat.md
> +To run AI locally, you need both an AI client and an AI model.
```suggestion
To run AI locally, you need both an AI model and an AI client.
```
Swapping order to reflect the order of sections

2024-11-12 22:41 UTC, redoomed1 commented on docs/ai-chat.md
> +## Downloading AI models
```suggestion
## AI Models

### Find and Choose a Model
```

2024-11-12 22:41 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
```suggestion
### Model Security

When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama) and [Llamafile](#llamafile)), you should download it from there. If you want to download other models, or use an AI client without their library, you should follow their official documentation.

We advise downloading the files from Hugging Face, as it has several features to verify that your download is genuine and safe to use.

To check the authenticity and safety of the model, look for:

- Model cards with clear documentation
- A verified organization badge
- Community reviews and usage statistics

When available, make sure to verify the file checksum, a type of anti-tampering fingerprint. On Hugging Face, you can find the hash by clicking on a model file and looking for the **Copy SHA256** button below it. You should compare this checksum with the one from the file you downloaded. You can use tools like `sha256sum` on Linux and macOS, or `certutil -hashfile file SHA256` on Windows to generate the downloaded file's checksum.

A downloaded model is generally safe if they satisfy all of the above checks.
```

2024-11-12 22:58 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
```suggestion
### Model Security

When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama) and [Llamafile](#llamafile)), you should download it from there. If you want to download other models, or use an AI client without their library, you should follow their official documentation.

We recommend downloading model files from Hugging Face, as it provides several features to verify that your download is genuine and safe to use.

To check the authenticity and safety of the model, look for:

- Model cards with clear documentation
- A verified organization badge
- Community reviews and usage statistics
- Matching checksums[^1]
  - On Hugging Face, you can find the hash by clicking on a model file and looking for the **Copy SHA256** button below it. You should compare this checksum with the one from the file you downloaded.

A downloaded model is generally safe if they satisfy all of the above checks.
```

2024-11-12 22:58 UTC, redoomed1 commented on docs/ai-chat.md
> +- Should be customizable (the user can modify the LLM paramaters, such as its system prompt or its temperature).
```suggestion
- Should be customizable (the user can modify the LLM paramaters, such as its system prompt or its temperature).

[^1]: A file checksum is a type of anti-tampering fingerprint. A developer usually provides a checksum in a text file that can be downloaded separately, or on the download page itself. Verifying that the checksum of the file you downloaded matches the one provided by the developer helps ensure that the file is genuine and wasn't tampered with in transit. You can use commands like `sha256sum` on Linux and macOS, or `certutil -hashfile file SHA256` on Windows to generate the downloaded file's checksum.
```

2024-11-12 23:01 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
```suggestion
### Model Security

When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama) and [Llamafile](#llamafile)), you should download it from there. If you want to download other models, or use an AI client without their library, you should follow their official documentation.

We recommend downloading model files from Hugging Face, as it provides several features to verify that your download is genuine and safe to use.

To check the authenticity and safety of the model, look for:

- Model cards with clear documentation
- A verified organization badge
- Community reviews and usage statistics
- Matching checksums
  - On Hugging Face, you can find the hash by clicking on a model file and looking for the **Copy SHA256** button below it. You should compare this checksum with the one from the file you downloaded.

A downloaded model is generally safe if they satisfy all of the above checks.
```

2024-11-12 23:02 UTC, redoomed1 commented on docs/ai-chat.md
> +- Should be customizable (the user can modify the LLM paramaters, such as its system prompt or its temperature).
Companion to https://github.com/privacyguides/privacyguides.org/pull/2810#discussion_r1838925870

2024-11-12 23:11 UTC, I-I-IT commented on docs/ai-chat.md
> +</details>
Why did you remove the 'Safe' badge from Hugging Face. This seam pretty important.

2024-11-12 23:13 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
Oh oops, that was a complete oversight by me. I just forgot to copy it here.

2024-11-12 23:14 UTC, I-I-IT commented
> Thanks @I-I-IT ! I'll go over your changes later and tag you as co-author in the commit.
You are welcome! I commented on a few questions/suggestions.

2024-11-12 23:20 UTC, I-I-IT commented on docs/ai-chat.md
> +</details>
>When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama) and [Llamafile](#llamafile)), you should download it from there. If you want to download other models, or use an AI client without their library, you should follow their official documentation.

I think this is a bit unclear. Yes, you should follow their documentation on how to import models, but the point was to introduce when you should or should not "side-load" the models. I think this slightly tweaked version reflects this better.

When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama) and [Llamafile](#llamafile)), you should download it from there.  But if you want to download models not present in their library, or use an AI client that doesn't maintain its library (such as [Kobold.cpp](#koboldcpp), you will need to take extra steps to ensure it's a safe and legit AI model.

2024-11-12 23:24 UTC, redoomed1 commented on docs/ai-chat.md
> +</details>
Ah, thanks for the clarification. Yes, when I was reading your proposed revisions, I was confused by this part:

> If you want to download other models, or use an AI client without their library, you should follow **those steps**.

2024-11-12 23:43 UTC, redoomed1 commented on docs/ai-chat.md
> +AI models that are run locally offer a more private and secure alternative to cloud-based solutions, as your data never leaves your device and is therefore never shared with third-party providers. Th
```suggestion
Alternatively, you can run AI models locally as a more private and secure alternative to cloud-based solutions, as your data never leaves your device and is therefore never shared with third parties. This provides peace of mind and allows you to share sensitive information to the local model.
```
Deduplication

2024-11-12 23:46 UTC, redoomed1 commented on docs/ai-chat.md
> +## AI chat clients
```suggestion
## AI Chat Clients
```

2024-11-12 23:46 UTC, redoomed1 commented on docs/ai-chat.md
> +For consumer-grade hardware, it is generally recommended to use [quantized models](https://huggingface.co/docs/optimum/en/concept_guides/quantization) for the best balance between model quality and p
```suggestion
For consumer-grade hardware, it is generally recommended to use [quantized models](https://huggingface.co/docs/optimum/en/concept_guides/quantization) for the best balance between model quality and performance. Check out the table below for more precise information about the typical requirements for different sizes of quantized models.
```

2024-11-13 00:24 UTC, redoomed1 reviewed
Ollama suggestions

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +### Ollama
```suggestion
### Ollama (CLI)
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +[:octicons-code-16:](https://github.com/ollama/ollama){ .card-link title="Source Code"}
```suggestion
[:octicons-info-16:](https://github.com/ollama/ollama#readme){ .card-link title="Documentation" }
[:octicons-code-16:](https://github.com/ollama/ollama){ .card-link title="Source Code" }
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +Ollama is an easy-to-use command-line AI assistant that is available on macOS, Linux, and Windows.
```suggestion
Ollama is a command-line AI assistant that is available on macOS, Linux, and Windows. Ollama is a great choice if you're looking for an AI client that's easy-to-use and widely compatible. It also doesn't involve any manual setup, while still using inference and other techniques to make outputs faster.
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +In addition to supporting a wide range of text models, Ollama also supports [LLaVA](https://github.com/haotian-liu/LLaVA) models and has *experimental* support for Meta's [Llama vision capabilities](
```suggestion
In addition to supporting a wide range of text models, Ollama also supports [LLaVA](https://github.com/haotian-liu/LLaVA) models and has experimental support for Meta's [Llama vision capabilities](https://huggingface.co/blog/llama32#what-is-llama-32-vision).
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +
```suggestion
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +It also simplifies the process of setting up a local AI chat, as it downloads the AI model you want to use automatically. For example, running `ollama run llama3.2` will automatically download and ru
```suggestion
Ollama simplifies the process of setting up a local AI chat, as it downloads the AI model you want to use automatically. For example, running `ollama run llama3.2` will automatically download and run the Llama 3.2 model. Furthermore, Ollama maintains their own [model library](https://ollama.com/library) where they host the files of various AI models. This ensures models are vetted for both performance and security, eliminating the need to manually verify model authenticity.
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/tools.md
> +- ![Ollama logo](assets/img/ai-chat/ollama.svg){ .twemoji loading=lazy }[Ollama](ai-chat.md#ollama)
```suggestion
- ![Ollama logo](assets/img/ai-chat/ollama.svg){ .twemoji loading=lazy }[Ollama](ai-chat.md#ollama-cli)
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +There are many permissively licensed **models available to download**. **[Hugging Face](https://huggingface.co/models?library=gguf)** is a platform that lets you browse, research, and download models
```suggestion
There are many permissively licensed models available to download. **[Hugging Face](https://huggingface.co/models?library=gguf)** is a platform that lets you browse, research, and download models in common formats like GGUF. Companies that provide good open-weights models include big names like Mistral, Meta, Microsoft, and Google. But there are also many community models and 'fine-tunes' available. For consumer-grade hardware, it is generally recommended to use [quantized models](https://huggingface.co/docs/optimum/en/concept_guides/quantization) for the best balance between model quality and performance.
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +| [Ollama](#ollama) | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-close:{ .pg-red } | :material-check:{ .pg-green } | :material-close:{ .pg-red } |
```suggestion
| [Ollama](#ollama-cli) | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-close:{ .pg-red } | :material-check:{ .pg-green } | :material-close:{ .pg-red } |
```

2024-11-13 00:24 UTC, redoomed1 commented on docs/ai-chat.md
> +When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama) and [Llam
```suggestion
When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama-cli) and [Llamafile](#llamafile)), you should download it from there. However, if you want to download models not present in their library, or use an AI client that doesn't maintain its library (such as [Kobold.cpp](#koboldcpp)), you will need to take extra steps to ensure that the AI model you download is safe and legitimate.
```

2024-11-13 02:08 UTC, redoomed1 commented on docs/ai-chat.md
> +[:octicons-home-16: Homepage](https://github.com/Mozilla-Ocho/llamafile/){ .md-button .md-button--primary }
```suggestion
[:octicons-home-16: Homepage](https://github.com/Mozilla-Ocho/llamafile){ .md-button .md-button--primary }
```

2024-11-13 02:08 UTC, redoomed1 commented on docs/ai-chat.md
> +Llamafile is a single-file executable that allows users to run large language models locally on their own computers, without any setup involved. It is available on Linux, macOS, and Windows.
```suggestion
Llamafile is a lightweight single-file executable that allows users to run large language models locally on their own computers without any setup involved. It is [backed by Mozilla](https://hacks.mozilla.org/2023/11/introducing-llamafile) and available on Linux, macOS, and Windows.
```

2024-11-13 02:08 UTC, redoomed1 commented on docs/ai-chat.md
> +The Mozilla-run project also supports LLaVA. However, it does not support speech recognition or image generation. It's also very lightweight and compatible.
```suggestion
Llamafile also supports LLaVA. However, it does not support speech recognition or image generation.
```

2024-11-13 02:08 UTC, redoomed1 commented on docs/ai-chat.md
> +[:octicons-lock-16:](https://github.com/Mozilla-Ocho/llamafile?tab=readme-ov-file#security){ .card-link title="Security Policy" }
```suggestion
[:octicons-lock-16:](https://github.com/Mozilla-Ocho/llamafile#security){ .card-link title="Security Policy" }
```

2024-11-13 02:08 UTC, redoomed1 commented on docs/ai-chat.md
> +- Should be easy to download and set up, such as having a one-click install process.
```suggestion
- Should be easy to download and set up, e.g. with a one-click install process.
```

2024-11-13 02:08 UTC, redoomed1 commented on docs/ai-chat.md
> +- Should be customizable (the user can modify the LLM paramaters, such as its system prompt or its temperature).
```suggestion
- The user should be able to modify the LLM parameters, such as its system prompt or temperature.
```

2024-11-13 02:08 UTC, redoomed1 commented on includes/abbreviations.en.txt
> +*[system prompt]: The system prompt of an AI chat is the general instructions given by human to guide how it should operate.
```suggestion
*[system prompt]: The system prompt of an AI chat is the general instructions given by a human to guide how it should operate.
```

2024-11-13 02:23 UTC, redoomed1 commented on docs/ai-chat.md
> +:   - On Hugging Face, you can find the hash by clicking on a model file and looking for the **Copy SHA256** button below it. You should compare this checksum with the one from the model file you dow
```suggestion
    - On Hugging Face, you can find the hash by clicking on a model file and looking for the **Copy SHA256** button below it. You should compare this checksum with the one from the model file you downloaded.
```

2024-11-13 02:34 UTC, redoomed1 commented on docs/ai-chat.md
> +A downloaded model is generally safe if they satisfy all of the above checks.
```suggestion
A downloaded model is generally safe if it satisfies all of the above checks.
```

2024-11-13 05:19 UTC, redoomed1 commented on docs/ai-chat.md
> +If you are concerned about these practices, you can either refuse to use AI, or use [truly open-source models](https://proton.me/blog/how-to-build-privacy-first-ai) which publicly release and allow y
```suggestion
If you are concerned about these practices, you can either refuse to use AI, or use [truly open-source models](https://proton.me/blog/how-to-build-privacy-first-ai) which publicly release and allow you to inspect their training datasets. One such model is [Olmoe](https://allenai.org/blog/olmoe) made by [Ai2](https://allenai.org/open-data).
```

2024-11-13 05:19 UTC, redoomed1 commented on docs/ai-chat.md
> +When you have found an AI model of your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama-cli) and [
```suggestion
When you have found an AI model to your liking, you should download it in a safe manner. When you use an AI client that maintains their own library of model files (such as [Ollama](#ollama-cli) and [Llamafile](#llamafile)), you should download it from there. However, if you want to download models not present in their library, or use an AI client that doesn't maintain its library (such as [Kobold.cpp](#koboldcpp)), you will need to take extra steps to ensure that the AI model you download is safe and legitimate.
```

2024-11-13 05:19 UTC, redoomed1 commented on docs/ai-chat.md
> +In addition to supporting a large range of text models, Kobold.cpp also supports image generators such as [Stable Diffusion](https://stability.ai/stable-image), and automatic speech recognition tools
```suggestion
In addition to supporting a large range of text models, Kobold.cpp also supports image generators such as [Stable Diffusion](https://stability.ai/stable-image) and automatic speech recognition tools such as [Whisper](https://github.com/ggerganov/whisper.cpp).
```

2024-11-13 05:19 UTC, redoomed1 commented on docs/ai-chat.md
> +Ollama is a command-line AI assistant that is available on macOS, Linux, and Windows. Ollama is a great choice if you're looking for an AI client that's easy-to-use and widely compatible. It also doe
```suggestion
Ollama is a command-line AI assistant that is available on macOS, Linux, and Windows. Ollama is a great choice if you're looking for an AI client that's easy-to-use, widely compatible, and fast due to its use of inference and other techniques. It also doesn't involve any manual setup.
```

2024-11-13 05:19 UTC, redoomed1 commented on docs/ai-chat.md
> +Ollama simplifies the process of setting up a local AI chat, as it downloads the AI model you want to use automatically. For example, running `ollama run llama3.2` will automatically download and run
```suggestion
Ollama simplifies the process of setting up a local AI chat, as it downloads the AI model you want to use automatically. For example, running `ollama run llama3.2` will automatically download and run the Llama 3.2 model. Furthermore, Ollama maintains their own [model library](https://ollama.com/library) where they host the files of various AI models. This ensures that models are vetted for both performance and security, eliminating the need to manually verify model authenticity.
```

2024-11-13 05:19 UTC, redoomed1 commented on docs/ai-chat.md
> +[:octicons-info-16:](https://github.com/Mozilla-Ocho/llamafile/?tab=readme-ov-file#llamafile){ .card-link title="Documentation" }
```suggestion
[:octicons-info-16:](https://github.com/Mozilla-Ocho/llamafile#llamafile){ .card-link title="Documentation" }
```

2024-11-13 05:19 UTC, redoomed1 commented on docs/ai-chat.md
> +If you use Llamafile on Windows, be aware that Windows limits `.exe` files to 4GB, and most models are larger than that. To work around this restriction, you can [load external weights](https://githu
```suggestion
Mozilla has made llamafiles available for only some Llama and Mistral models, while there are few third-party llamafiles available. Moreover, Windows limits `.exe` files to 4GB, and most models are larger than that.

To circumvent these issues, you can [load external weights](https://github.com/Mozilla-Ocho/llamafile#using-llamafile-with-external-weights).
```

2024-11-13 11:11 UTC, I-I-IT requested changes
Just a few minor suggestions.

2024-11-13 11:11 UTC, I-I-IT commented on docs/ai-chat.md
> +| Local Client | GPU Support | Image Generation | Speech Recognition | Automatically Downloaded Models | Custom Parameters |
The problem with this format is that it is mobile-unfriendly, as you have to scroll right to see all the info. Could we either revert it back, or change the format when we detect mobile screen size ?

2024-11-13 11:11 UTC, I-I-IT commented on docs/ai-chat.md
> +### Ollama (CLI)
I think we could mention that ollama also has GUI community variants.  https://github.com/ollama/ollama?tab=readme-ov-file#web--desktop

2024-11-13 15:04 UTC, I-I-IT commented
@jonaharagon for Ollama dark mode icon, the closest I could find is this one. (Notice it is a square with white surrounding the llama icon)
![ollama-dark](https://github.com/user-attachments/assets/43b705b9-d047-4b7a-9b1d-5b61bdd4e0bd)

2024-11-13 16:30 UTC, friadev commented
They have an icon that would look good in dark and light mode on their GitHub README
![254932576-0d0b44e2-8f4a-4e99-9b52-a5c1c741c8f7](https://github.com/user-attachments/assets/9b4a2016-6aa3-415d-a503-b86eb689978f)

2024-11-14 16:33 UTC, redoomed1 commented on docs/ai-chat.md
> +If you are concerned about these practices, you can either refuse to use AI, or use [truly open-source models](https://proton.me/blog/how-to-build-privacy-first-ai) which publicly release and allow y
```suggestion
If you are concerned about these practices, you can either refuse to use AI, or use [truly open-source models](https://proton.me/blog/how-to-build-privacy-first-ai) which publicly release and allow you to inspect their training datasets. One such model is [OLMoE](https://allenai.org/blog/olmoe-an-open-small-and-state-of-the-art-mixture-of-experts-model-c258432d0514) made by [Ai2](https://allenai.org/open-data).
```

2024-11-14 16:33 UTC, redoomed1 commented on docs/ai-chat.md
> +description: Unlike OpenAI's ChatGPT and its Big Tech competitors, these AI tools do not train their models using your conversations.
```suggestion
description: Unlike OpenAI's ChatGPT and its Big Tech competitors, these AI tools run locally so your data never leaves your device.
```

2024-11-14 16:33 UTC, redoomed1 commented on docs/ai-chat.md
> +![Ollama Logo](assets/img/ai-chat/ollama.svg){align=right}
```suggestion
![Ollama Logo](assets/img/ai-chat/ollama.png){align=right}
```

2024-11-14 16:33 UTC, redoomed1 commented on docs/tools.md
> +- ![Ollama logo](assets/img/ai-chat/ollama.svg){ .twemoji loading=lazy }[Ollama](ai-chat.md#ollama-cli)
```suggestion
- ![Ollama logo](assets/img/ai-chat/ollama.png){ .twemoji loading=lazy }[Ollama](ai-chat.md#ollama-cli)
```

2024-11-14 16:40 UTC, redoomed1 commented on docs/tools.md
> +- ![Ollama logo](assets/img/ai-chat/ollama.png){ .twemoji loading=lazy }[Ollama](ai-chat.md#ollama-cli)
```suggestion
- ![Kobold logo](assets/img/ai-chat/kobold.png){ .twemoji loading=lazy } [Kobold.cpp](ai-chat.md#koboldcpp)
- ![Llamafile logo](assets/img/ai-chat/llamafile.svg){ .twemoji loading=lazy } [Llamafile](ai-chat.md#llamafile)
- ![Ollama logo](assets/img/ai-chat/ollama.png){ .twemoji loading=lazy } [Ollama](ai-chat.md#ollama-cli)
```
Consistency

2024-11-14 16:46 UTC, redoomed1 commented on docs/tools.md
> +- ![Ollama logo](assets/img/ai-chat/ollama.png){ .twemoji loading=lazy } [Ollama](ai-chat.md#ollama-cli)
```suggestion
- ![Ollama logo](assets/img/ai-chat/ollama.png){ .twemoji loading=lazy } [Ollama (CLI)](ai-chat.md#ollama-cli)
```

2024-11-14 20:08 UTC, friadev requested changes

2024-11-14 20:08 UTC, friadev commented on docs/ai-chat.md
> +title: "AI Chat"
```suggestion
title: "Local AI Chat"
```

2024-11-14 20:08 UTC, friadev commented on docs/tools.md
> +### AI Chat
```suggestion
### Local AI Chat
```

2024-11-14 20:23 UTC, friadev requested changes

2024-11-14 20:23 UTC, friadev commented on docs/ai-chat.md
> +Data used to train AI models, however, include a massive amount of _private_ data. Developers of AI software often use [Reinforcement Learning from Human Feedback](https://en.wikipedia.org/wiki/Reinf
```suggestion
Data used to train AI models, however, include a massive amount of publicly available data scraped from the web. Developers of cloud-based AI software often collect your inputs, meaning your chats are not private from them. This practice also introduces a risk of data breaches. Furthermore, there is a real possibility that an LLM will leak your private chat information in future conversations with other users.
```

2024-11-14 20:46 UTC, friadev requested changes

2024-11-14 20:46 UTC, friadev commented on docs/ai-chat.md
> +Local models are also fairly accessible as it is possible to run smaller models on modest hardware. A computer with at least 8GB of RAM will be sufficient to run smaller models at lower speeds. Using
```suggestion
Local models are also fairly accessible. It's possible to run smaller models at lower speeds on as little as 8GB of RAM. Using more powerful hardware such as a dedicated GPU with sufficient VRAM or a modern system with fast LPDDR5X memory will offer the best experience.
```

2024-11-14 20:51 UTC, friadev requested changes

2024-11-14 20:51 UTC, friadev commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below
```suggestion
The higher the number of parameters, the higher the LLM's capabilities. For example, models below 6.7B parameters are only good for basic tasks like text summaries, while models between 7B and 13B are a great compromise between quality and speed. Models with advanced reasoning capabilities are generally around 70B.
```

2024-11-14 20:51 UTC, friadev commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below
This doesn't seem to be [true](https://cmte.ieee.org/futuredirections/2023/11/14/llms-hitting-2-trillions-parameters/).

2024-11-14 21:11 UTC, I-I-IT commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below
If yoh want to be complete, then you should say "LLMs can vary from millions of a parameters to trillions, but models that a consumer-grade can run and are ysefuk are between 6.7B and 80B."

But I am.talkimg about open source models here, sure they are bigger models, but no one can download them.

I am a bit angry cause arguing on such details is pointless, the point of this is NOT to be a science article about LLMs, but rather a brief introduction.

2024-11-14 21:13 UTC, I-I-IT commented on docs/ai-chat.md
> +Data used to train AI models, however, include a massive amount of _private_ data. Developers of AI software often use [Reinforcement Learning from Human Feedback](https://en.wikipedia.org/wiki/Reinf
Sorry, but that's just and understatement. The

2024-11-14 21:18 UTC, friadev commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below
I just want it to be accurate

2024-11-14 22:06 UTC, I-I-IT commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below
No I understand. But also, I think the broader message is more important than details. So when you say  " The higher the number of parameters, the higher the LLM's capabilities." , this isn't totally true. We have seen in [leaderboards](https://lmarena.ai/) than a 405B model doesn't perform much better than a 70B.

> I don't really think it matters what the minimum and maximum amount of parameters is anyway for the purposes of this page.

It was to give a ballpark of what model size are availables, and which you can actually run.

2024-11-14 22:10 UTC, I-I-IT commented
@redoomed1 I still don't understand why the table format was changed to a format that is now totally non-intuitive on mobile.

2024-11-14 22:15 UTC, redoomed1 commented on docs/ai-chat.md
> +| Local Client | GPU Support | Image Generation | Speech Recognition | Automatically Downloaded Models | Custom Parameters |
The table's rows and columns were swapped to match how tables are presented elsewhere on the site (VPN, DNS, Search Engines). Also, the randomization logic for tables only applies to rows.

If we revert it to the previous format, then the features would be randomized, which is not that useful. I'm not sure what the original purpose of randomizing the tables was, but the effect it has is that there is no perceived order to the recommended tools, which allows readers to see the places where certain tools shine, and conversely, where the fall short.

2024-11-14 22:22 UTC, redoomed1 commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters. The higher the number of parameters, the higher the LLM's capabilities. For example, models below 6.7B parameters are only good for bas
```suggestion
LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B for open-source models available for end users. For example, models below 6.7B parameters are only good for basic tasks like text summaries, while models around 70B have advanced reasoning capabilities. Generally, models between 7B and 13B are a great compromise between quality and speed.
```
@I-I-IT To continue the discussion from https://github.com/privacyguides/privacyguides.org/pull/2810#discussion_r1842944857, what do you think of this revision?

2024-11-14 22:27 UTC, friadev commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below
Well I didn't write that, maybe that should be changed.

2024-11-14 22:28 UTC, redoomed1 commented on docs/ai-chat.md
> +| Local Client | GPU Support | Image Generation | Speech Recognition | Automatically Downloaded Models | Custom Parameters |
I wouldn't be opposed to reverting the table format *if* the randomization logic is also changed so that columns are randomized instead. This would make it so you wouldn't have to scroll horizontally, but you'd probably need to scroll vertically instead. I think this is a good idea for the tables which have three or fewer tools for comparison (all but the DNS table).  It would have no effect on the DNS table (or even negative effects due to text wrapping).

2024-11-14 22:29 UTC, redoomed1 commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters, which can vary between 1.3B to 405B. The higher the number of parameters, the higher the LLM's capabilities. For example, models below
Yeah that was my bad. It was removed in the latest revision of this part.

2024-11-14 22:34 UTC, redoomed1 commented on docs/ai-chat.md
> +### Ollama (CLI)
I'm not sure about linking to this since there are so many community *integrations* listed. And some of them are extensions for apps like Discord or VSCode.

2024-11-14 22:36 UTC, redoomed1 commented
> I still don't understand why the table format was changed to a format that is now totally non-intuitive on mobile.

See https://github.com/privacyguides/privacyguides.org/pull/2810#discussion_r1842952492

2024-11-14 22:44 UTC, friadev commented on docs/ai-chat.md
> +| Local Client | GPU Support | Image Generation | Speech Recognition | Automatically Downloaded Models | Custom Parameters |
I think we also need to make sure the table is in the proper format for accessibility reasons as well. It might just be an unavoidable thing.

2024-11-15 08:12 UTC, I-I-IT commented on docs/ai-chat.md
> +| Local Client | GPU Support | Image Generation | Speech Recognition | Automatically Downloaded Models | Custom Parameters |
>The table's rows and columns were swapped to match how tables are presented elsewhere on the site (VPN, DNS, Search Engines). The tables on these pages also have the same "problem" of scrolling that you mentioned. Also, the randomization logic for tables only applies to rows.

I am aware than it is the same format as other table, but just because bad design has been implemented elsewhere, doesn't mean we should stick with it. Isn't there a way to just disable randomisation?

2024-11-15 08:16 UTC, I-I-IT commented on docs/ai-chat.md
> +LLMs can usually be differentiated by the number of parameters. The higher the number of parameters, the higher the LLM's capabilities. For example, models below 6.7B parameters are only good for bas
It's good but we should keep "models of 70B ..." at the end cause it make more sense to go in ascending order (we don't want to hype people up about 70B parameters models they probably can't run.

2024-11-15 17:02 UTC, redoomed1 commented on docs/ai-chat.md
> +Kobold shines best when you are looking for heavy customization and tweaking, such as for roleplaying purposes. It allows you to modify parameters such as the AI model temperature and the AI chat's s
```suggestion
Kobold.cpp allows you to modify parameters such as the AI model temperature and the AI chat's system prompt. It also supports creating a network tunnel to access AI models from other devices such as your phone.
```

2024-11-15 17:02 UTC, redoomed1 commented on docs/ai-chat.md
> +Kobold.cpp is an AI client that runs locally on your Windows, Mac, or Linux computer.
```suggestion
Kobold.cpp is an AI client that runs locally on your Windows, Mac, or Linux computer. It is an excellent choice if you are looking for heavy customization and tweaking, such as for role-playing purposes.
```

2024-11-15 17:08 UTC, redoomed1 commented on docs/ai-chat.md
> + - [randomize-element, "table tbody"]
```suggestion
```

2024-11-15 17:08 UTC, redoomed1 commented on docs/ai-chat.md
> +| [Llamafile](#llamafile) | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-close:{ .pg-red } | :material-alert-outline:{ .pg-orange } Few models available | :material-alert-o
```suggestion
| Feature | [Kobold.cpp](#koboldcpp) | [Ollama](#ollama-cli) | [Llamafile](#llamafile) |
|---|---|---|---|
| GPU Support | :material-check:{ .pg-green } | :material-check:{ .pg-green } | :material-check:{ .pg-green } |
| Image Generation | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-close:{ .pg-red } |
| Speech Recognition | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-close:{ .pg-red } |
| Auto-download Models | :material-close:{ .pg-red } | :material-check:{ .pg-green } | :material-alert-outline:{ .pg-orange } Few models available |
| Custom Parameters | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-alert-outline:{ .pg-orange } |
| Multi-platform | :material-check:{ .pg-green } | :material-check:{ .pg-green } | :material-alert-outline:{ .pg-orange } Size limitations on Windows |
```

2024-11-15 17:14 UTC, redoomed1 commented on docs/ai-chat.md
> +Local models are also fairly accessible. It's possible to run smaller models at lower speeds on as little as 8GB of RAM. Using more powerful hardware such as a dedicated GPU with sufficient VRAM or a
```suggestion
Local models are also fairly accessible. It's possible to run smaller models at lower speeds on as little as 8GB of RAM. Using more powerful hardware such as a dedicated GPU with sufficient VRAM or a modern system with fast LPDDR5X memory offers the best experience.
```

2024-11-15 17:58 UTC, redoomed1 commented on docs/ai-chat.md
> +| Local Client | GPU Support | Image Generation | Speech Recognition | Automatically Downloaded Models | Custom Parameters |
I disabled table randomization on this page and reverted the table format: https://github.com/privacyguides/privacyguides.org/pull/2810/commits/f095b510dcc597c58ccb3a7d13cd1ac5c6683620

2024-11-15 23:03 UTC, jonaharagon commented on docs/ai-chat.md
> +## Privacy Concerns about LLMs
What do we think about moving this section and the hardware section to be at the bottom (in between the AI Chat Clients section and the Criteria section) instead?

2024-11-15 23:50 UTC, I-I-IT commented on docs/ai-chat.md
> +## Privacy Concerns about LLMs
This wouldnt make sense. If you don't think explaining LLMs is needed, then it's better to just not include it.

And the hardware section obv. need to be before AI clients cause it is so.people know wich AI models they can download.

2024-11-17 06:15 UTC, jonaharagon commented on docs/ai-chat.md
> +## Privacy Concerns about LLMs
Hm. I guess my question is, do you need to choose a model before you choose a client? It feels like this heading order would make just as much sense:

1. Privacy Concerns about LLMs
1. AI Chat Clients
2. Hardware for Local AI Models
3. AI Models
   a. Find and Choose a Model
   b. Model Security

Actually, maybe we'd even do:

1. Privacy Concerns about LLMs
2. AI Chat Clients
3. AI Models
   a. Hardware Requirements
   b. Choosing a Model
   c. Model Security

2024-11-17 11:30 UTC, I-I-IT commented on docs/ai-chat.md
> +## Privacy Concerns about LLMs
For Llamafile, you directly download a model, so not explaining which model is your machine capable of running will be odd.

But we could do
1.Privacy Concerns about LLMS
2.AI models
a. Hardware requirements
b. Choosing a model
3.AI clients
(explain how to use models with Llamafile & Ollama)
4.Download models
"If you use Kobold or want AI models not in your AI client Library, follow those steps" :
(Explain how to download&securely do so)

2024-11-17 18:14 UTC, redoomed1 commented on docs/ai-chat.md
> +## Privacy Concerns about LLMs
https://github.com/privacyguides/privacyguides.org/pull/2810/commits/71f638a2a6383d7d8da3f6a7d5cf004ef325f480 I rearranged the headings based on your suggestion, @I-I-IT. Feel free to suggest additional explanations or other changes!

2024-11-17 18:20 UTC, redoomed1 commented on docs/ai-chat.md
> +However, if you want to download models not present in their library, or use an AI client that doesn't maintain its library (such as [Kobold.cpp](#koboldcpp)), you will need to take extra steps to en
```suggestion
If you use an AI client that maintains their own library of model files (such as [Ollama](#ollama-cli) and [Llamafile](#llamafile)), you should download it from there. However, if you want to download models not present in their library, or use an AI client that doesn't maintain its library (such as [Kobold.cpp](#koboldcpp)), you will need to take extra steps to ensure that the AI model you download is safe and legitimate.
```

2024-11-18 17:05 UTC, friadev requested changes

2024-11-18 17:05 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-code-16:](https://github.com/ollama/ollama){ .card-link title="Source Code" }
```suggestion
[:octicons-code-16:](https://github.com/ollama/ollama){ .card-link title="Source Code" }
[:octicons-lock-16:](https://github.com/ollama/ollama/blob/a14f76491d694b2f5a0dec6473514b7f93beeea0/SECURITY.md){ .card-link title="Security Policy" }
```

2024-11-18 17:05 UTC, friadev commented on docs/ai-chat.md
> +- [:fontawesome-brands-windows: Windows](https://ollama.com/download/linux)
```suggestion
- [:fontawesome-brands-windows: Windows](https://ollama.com/download/windows)
```

2024-11-18 17:05 UTC, friadev commented on docs/ai-chat.md
> +[:octicons-code-16:](https://github.com/ollama/ollama){ .card-link title="Source Code" }
```suggestion
[:octicons-code-16:](https://github.com/Mozilla-Ocho/llamafile){ .card-link title="Source Code" }
```

2024-11-19 15:37 UTC, friadev commented on docs/ai-chat.md
> +Data used to train AI models, however, include a massive amount of publicly available data scraped from the web, which can include sensitive information like names and addresses. Developers of cloud-
```suggestion
Data used to train AI models, however, includes a massive amount of publicly available data scraped from the web, which can include sensitive information like names and addresses. Cloud-based AI software often [collects your inputs](https://openai.com/policies/row-privacy-policy/), meaning your chats are not private from them. This practice also introduces a risk of data breaches. Furthermore, there is a real possibility that an LLM will leak your private chat information in future conversations with other users.
```

2024-11-19 15:40 UTC, friadev commented on docs/ai-chat.md
> +There are many permissively licensed models available to download. **[Hugging Face](https://huggingface.co/models)** is a platform that lets you browse, research, and download models in common format
```suggestion
There are many permissively licensed models available to download. [Hugging Face](https://huggingface.co/models) is a platform that lets you browse, research, and download models in common formats like [GGUF](https://huggingface.co/docs/hub/en/gguf). Companies that provide good open-weights models include big names like Mistral, Meta, Microsoft, and Google. However, there are also many community models and 'fine-tunes' available. As mentioned above, quantized models offer the best balance between model quality and performance for those using consumer-grade hardware.
```

2024-11-19 15:42 UTC, friadev commented on docs/ai-chat.md
> +To help you choose a model that fits your needs, you can look at leaderboards and benchmarks, of which there are many kinds. The most widely-used leaderboard is the community-driven [LM Arena](https:
```suggestion
To help you choose a model that fits your needs, you can look at leaderboards and benchmarks. The most widely-used leaderboard is the community-driven [LM Arena](https://lmarena.ai). Additionally, the [OpenLLM Leaderboard](https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard) focuses on the performance of open-weights models on common benchmarks like [MMLU-Pro](https://arxiv.org/abs/2406.01574).  There are also specialized benchmarks which measure factors like [emotional intelligence](https://eqbench.com), ["uncensored general intelligence"](https://huggingface.co/spaces/DontPlanToEnd/UGI-Leaderboard), and [many others](https://www.nebuly.com/blog/llm-leaderboards).
```

2024-11-19 15:43 UTC, friadev commented on docs/ai-chat.md
> +Kobold.cpp is an AI client that runs locally on your Windows, Mac, or Linux computer. It is an excellent choice if you are looking for heavy customization and tweaking, such as for role-playing purpo
```suggestion
Kobold.cpp is an AI client that runs locally on your Windows, Mac, or Linux computer. It's an excellent choice if you are looking for heavy customization and tweaking, such as for role-playing purposes.
```

2024-11-19 15:44 UTC, friadev commented on docs/ai-chat.md
> +Ollama simplifies the process of setting up a local AI chat, as it downloads the AI model you want to use automatically. For example, running `ollama run llama3.2` will automatically download and run
```suggestion
Ollama simplifies the process of setting up a local AI chat by downloading the AI model you want to use automatically. For example, running `ollama run llama3.2` will automatically download and run the Llama 3.2 model. Furthermore, Ollama maintains their own [model library](https://ollama.com/library) where they host the files of various AI models. This ensures that models are vetted for both performance and security, eliminating the need to manually verify model authenticity.
```

2024-11-19 15:46 UTC, friadev commented on docs/ai-chat.md
> +Llamafile is a lightweight single-file executable that allows users to run large language models locally on their own computers without any setup involved. It is [backed by Mozilla](https://hacks.moz
```suggestion
Llamafile is a lightweight single-file executable that allows users to run LLMs locally on their own computers without any setup involved. It is [backed by Mozilla](https://hacks.mozilla.org/2023/11/introducing-llamafile) and available on Linux, macOS, and Windows.
```

2024-11-19 15:46 UTC, friadev commented on docs/ai-chat.md
> +Llamafile also supports LLaVA. However, it does not support speech recognition or image generation.
```suggestion
Llamafile also supports LLaVA. However, it doesn't support speech recognition or image generation.
```

2024-11-19 15:47 UTC, friadev commented on docs/ai-chat.md
> +We recommend downloading model files from Hugging Face, as it provides several features to verify that your download is genuine and safe to use.
```suggestion
We recommend downloading model files from Hugging Face since it provides several features to verify that your download is genuine and safe to use.
```

2024-11-20 12:08 UTC, friadev commented on docs/ai-chat.md
> +| Multi-platform | :material-check:{ .pg-green } | :material-check:{ .pg-green } | :material-alert-outline:{ .pg-orange } Size limitations on Windows |
Their documentation mentions external weights:

>Even though our example llamafiles have the weights built-in, you don't have to use llamafile that way. Instead, you can download just the llamafile software (without any weights included) from our releases page. You can then use it alongside any external weights you may have on hand.

Is that the same thing?

2024-11-20 15:13 UTC, friadev commented on docs/ai-chat.md
> +| Multi-platform | :material-check:{ .pg-green } | :material-check:{ .pg-green } | :material-alert-outline:{ .pg-orange } Size limitations on Windows |
They let you edit parameters in their interface.

2024-11-20 15:14 UTC, friadev requested changes

2024-11-20 15:14 UTC, friadev commented on docs/ai-chat.md
> +| Custom Parameters | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-alert-outline:{ .pg-orange } |
```suggestion
| Custom Parameters | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-check:{ .pg-green } |
```

2024-11-20 15:26 UTC, friadev approved these changes

2024-11-20 16:28 UTC, I-I-IT commented on docs/ai-chat.md
> +| Custom Parameters | :material-check:{ .pg-green } | :material-close:{ .pg-red } | :material-alert-outline:{ .pg-orange } |
I checked and they indeed allow you to very easily change your "settings" 
![llamafile-screenshot](https://github.com/user-attachments/assets/3714f6fa-f5d6-4325-91df-b4de6d2695a5)

2024-11-21 03:34 UTC, redoomed1 approved these changes

2024-11-21 03:34 UTC, redoomed1 commented on docs/ai-chat.md
> +Data used to train AI models, however, includes a massive amount of publicly available data scraped from the web, which can include sensitive information like names and addresses. Cloud-based AI soft
```suggestion
Data used to train AI models, however, includes a massive amount of publicly available data scraped from the web, which can include sensitive information like names and addresses. Cloud-based AI software often [collects your inputs](https://openai.com/policies/row-privacy-policy), meaning your chats are not private from them. This practice also introduces a risk of data breaches. Furthermore, there is a real possibility that an LLM will leak your private chat information in future conversations with other users.
```

2024-11-21 03:34 UTC, redoomed1 commented on docs/ai-chat.md
> +- Must not send personal data, including chat data.
```suggestion
- Must not transmit personal data, including chat data.
```

2024-11-21 03:52 UTC, friadev approved these changes

2024-11-24 21:55 UTC, I-I-IT commented
@jonaharagon anything blocking this from moving to production?

2024-11-26 22:22 UTC, merged