update!: Add article on MPRs
privacyguides/privacyguides.org pull request #2813
Opened 2024-11-13 20:12 UTC by friadev

List of changes proposed in this PR:

- added an article wrote to the blog

2024-11-15 22:45 UTC, jonaharagon reviewed
I'll wait to approve until I get back to my laptop and can review it more thoroughly (and fix the blog builds on forks), but reading on my phone I really like this post and it LGTM 👍

2024-11-16 06:16 UTC, jonaharagon requested changes
I opened https://github.com/friadev/privacyguides.org/pull/1 with suggested changes.

I don't think anything in my suggestions should change the meaning of the content, it was mainly just that I wanted to rearrange some of the sections, which was too annoying to do with GitHub web comments.

edit: also to add some graphics

2024-11-16 15:30 UTC, redoomed1 reviewed
Aside from the intro, all of my suggestions are minor. No notes about the content, since the article is already super clear and digestible.

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +Multi-Party Relays are a technology that aims to provide better privacy protections than VPNs do. They show a lot of promise, but years later there are fewer options than ever. What happened?<!-- mor
The second intro sentence is kinda awkward IMO because of the tenses:

> They show a lot of promise, but **years later** there are fewer options than ever.

The "years later" should accompany a past tense in the previous clause.

```suggestion
Multi-Party Relays (MPRs) are a technology that aims to provide better privacy protections than VPNs do. MPRs showed a lot of promise when they first emerged, but years later there are fewer options than ever. What happened?<!-- more -->
```
Is this suggestion consistent with what you wanted to communicate in the original?

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +The original purpose of Virtual Private Networks was to access a network privately when you're not physically there, with encryption in between, so you can securely access your files or manage your n
```suggestion
The original purpose of Virtual Private Networks (VPNs) was to access a network privately when you're not physically there, with encryption in between, so you can securely access your files or manage your network from wherever you are. It extends the security you'd expect from being physically at your LAN to anywhere you are.
```

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +[Commercial VPNs](https://www.privacyguides.org/en/basics/vpn-overview/) like ProtonVPN use this technology to allow you to connect to *their* network, and then connect to your destination. This keep
```suggestion
[Commercial VPNs](https://www.privacyguides.org/en/basics/vpn-overview/) like Proton VPN use this technology to allow you to connect to *their* network, and then connect to your destination. This keeps sites and services you connect to from knowing your real IP address and using it as a metric to track you. But there's a problem here: you now need to fully trust your VPN provider in the same way you need to trust your ISP with all your internet traffic. This "shifting trust" problem has haunted VPNs for as long as they've been marketed as a privacy product. It's clear that a better solution is needed.
```

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +Mix networks like [Tor](https://www.privacyguides.org/en/advanced/tor-overview/) have solved this problem by decoupling the sender from the destination. No relay along the path has all the informatio
```suggestion
Mix networks like [Tor](https://www.privacyguides.org/en/advanced/tor-overview) have solved this problem by decoupling the sender from the destination. No relay along the path has all the information: the entry (or *guard*) relay knows who you are but not where you're going, the middle relay knows the other two relays, and the exit relay knows the destination but not the sender. There's also separate encryption between each relay.
```

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +Mix networks like [Tor](https://www.privacyguides.org/en/advanced/tor-overview/) have solved this problem by decoupling the sender from the destination. No relay along the path has all the informatio
```suggestion
Mix networks like [Tor](https://www.privacyguides.org/en/advanced/tor-overview) have solved this problem by decoupling the sender from the destination. No relay along the path has all the information: the entry (or *guard*) relay knows who you are but not where you're going, the middle relay knows the other two relays, and the exit relay knows the destination but not the sender. There's also separate encryption between each relay.
```

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +Tor provides great privacy properties, but the relays are run by volunteers and as such it can be extremely slow and unreliable. Anyone who's tried to download a file on it knows how painful it can b
```suggestion
Tor provides great privacy properties, but the relays are run by volunteers, so they can be extremely slow and unreliable. Anyone who's tried to download a file while connected to Tor knows how painful it can be. Even normal browsing can be slow, with potentially minutes collectively wasted on loading times in any given browsing session. Tor is hands down the most private way to [browse the web](https://www.privacyguides.org/en/tor), and if your threat model calls for it there is no substitute. But for VPN users who want better privacy, an obvious next step is a paid solution where you have access to fast and reliable servers like on a VPN, and *also* separation between who you are and what you're connecting to.
```

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +That leaves [iCloud Private Relay](https://support.apple.com/en-us/102602) as the only commercial offering that I'm aware of, but it's limited to Apple devices only. Great for Apple users, but everyo
```suggestion
That leaves [iCloud Private Relay](https://support.apple.com/en-us/102602) as the only commercial offering that I'm aware of, but it's limited to Apple devices only. Great for Apple users, but everyone else is left high and dry. As is Apple's way, they didn't want any extra inconvenience from using their service, so they restrict you to your real country and timezone. You don't have the same freedom to choose a server wherever in the world you want like a [traditional VPN service](https://www.privacyguides.org/en/vpn) would allow.
```

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +There is one more honorary mention: [OHTTP](https://blog.cloudflare.com/stronger-than-a-promise-proving-oblivious-http-privacy-properties/). It's a new protocol with a design based on the same princi
```suggestion
There is one more honorary mention: [OHTTP](https://blog.cloudflare.com/stronger-than-a-promise-proving-oblivious-http-privacy-properties). It's a new protocol with a design based on the same principles as those of MPRs: two servers, a relay and a gateway, that decouple the sender from the destination. It's already seeing use by large companies to maintain user privacy for things like Google's Safe Browsing and Apple's new Safari Highlights feature. Unfortunately, it's not quite comparable to MPRs. According to Cloudflare:
```

2024-11-16 15:30 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +It really is a shame to see such a promising technology go so underutilized. Perhaps the VPN companies could make their own MPR product and fill the gap in the market, only time will tell.
```suggestion
It really is a shame to see such a promising technology go so underutilized. Perhaps VPN companies could make their own MPR product and fill the gap in the market. Only time will tell.
```

2024-11-16 17:09 UTC, jonaharagon commented on blog/posts/where-are-all-the-mprs.md
> +There is one more honorary mention: [OHTTP](https://blog.cloudflare.com/stronger-than-a-promise-proving-oblivious-http-privacy-properties/). It's a new protocol with a design based on the same princi
What about "as an MPR"?

2024-11-16 17:10 UTC, jonaharagon approved these changes
If you could review the other suggestions here too then I'll merge this today 👍

2024-11-17 01:39 UTC, redoomed1 approved these changes
LGTM

2024-11-17 01:39 UTC, redoomed1 commented on blog/posts/where-are-all-the-mprs.md
> +[Commercial VPNs](https://www.privacyguides.org/en/basics/vpn-overview/) like Proton VPN use this technology to allow you to connect to *their* network, and then connect to your destination. This kee
```suggestion
[Commercial VPNs](https://www.privacyguides.org/en/basics/vpn-overview) like Proton VPN use this technology to allow you to connect to *their* network, and then connect to your destination. This keeps sites and services you connect to from knowing your real IP address and using it as a metric to track you. But there's a problem here: you now need to fully trust your VPN provider in the same way you need to trust your ISP with all your internet traffic. This "shifting trust" problem has haunted VPNs for as long as they've been marketed as a privacy product. It's clear that a better solution is needed.
```

2024-11-17 05:14 UTC, merged