update: IzzyOnDroid subsection on Obtaining Android Apps page
privacyguides/privacyguides.org pull request #2818
Opened 2024-11-17 04:04 UTC by redoomed1

List of changes proposed in this PR:

- Update the subsection about IzzyOnDroid, as it is [no longer true](https://apt.izzysoft.de/fdroid/index/info#delete) that apps in the aforementioned repository are automatically removed if they are also included in F-Droid's main repo
- Add information about IoD offering reproducible builds
- Make minor wording changes

2024-11-17 05:10 UTC, jonaharagon approved these changes

2024-11-17 08:20 UTC, blacklight447 approved these changes

2024-11-17 14:59 UTC, friadev requested changes
Maybe this would be a compromise?

2024-11-17 14:59 UTC, friadev commented on docs/android/obtaining-apps.md
> +Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from GitHub
```suggestion
Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from GitHub and is the next best thing to the developers' own repositories. They also offer [reproducible builds](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) for some applications and have developers who verify the reproducibility of developer-signed APKs. Note that apps might get [removed](https://apt.izzysoft.de/fdroid/index/info#delete) if they are added to the official F-Droid repository and are close to or over their size limit.
```

2024-11-17 17:59 UTC, jonaharagon commented on docs/android/obtaining-apps.md
> +Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from GitHub
I reached out to them for clarification on this policy, waiting to hear back.

2024-11-18 05:43 UTC, dngray commented on docs/android/obtaining-apps.md
> +That said, the [F-Droid](https://f-droid.org/en/packages) and [IzzyOnDroid](https://apt.izzysoft.de/fdroid) repositories are home to countless apps, so they can be useful places to search for and dis
```suggestion
The [F-Droid](https://f-droid.org/en/packages) and [IzzyOnDroid](https://apt.izzysoft.de/fdroid) repositories are home to countless apps, so they can be useful places to search for and discover open-source apps that you can then download through other means such as the Play Store, Aurora Store, or by getting the APK directly from the developer. You should use your best judgment when looking for new apps via this method, and keep an eye on how frequently the app is updated. Outdated apps may rely on unsupported libraries, among other things, posing a potential security risk.
```

Try to avoid starting sentences with superfluous joining words I think.

2024-11-20 11:54 UTC, friadev commented on docs/android/obtaining-apps.md
> +Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from GitHub
Any word back?

2024-11-29 19:21 UTC, IzzySoft commented on docs/android/obtaining-apps.md
> +Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from GitHub
Apologies for the delay, was busy at `$dayjob`…

> if they are added to the official F-Droid repository

That is no longer true for about a year already, see [Are apps removed from the repo – and when does that happen?](https://gitlab.com/IzzyOnDroid/repo#are-apps-removed-from-the-repo--and-when-does-that-happen) Also take a closer look at the section of the info page you linked to, quote:

> Another reason for an app getting removed from my repo is if it was added to the „official F-Droid repository“ **when its APKs were already close to (or even beyond) the size limits here**

(emphasis added) – saying exactly the same: usually they stay at IoD, and are only removed if they got to the "size limit". Reading between the lines (and reflecting the facts) is that we're usually "lenient" when an app grows to that limit (though we usually do not accept to **add** apps which are already beyond, so you can basically even ignore the "already close to").

While we're on it, if you want to make it more precise:

> The IzzyOnDroid repository pulls builds directly from GitHub

matches 80..90% of the apps. We also pull them from GitLab (.com or self-hosted), Codeberg.org or self-hosted Gitea/Forgejo instances, if developers provide them there. Preferably from their tagged releases, as that enables us to establish reproducible builds, see [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) which you already link (number of RBs as of this writing: 357 apps (29.3%)).

Also worth mentioning might be our additional security scans, see [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks). To give you an idea how that looks in "daily business", today's scan report just came in:

```
! repo/com.afaneca.myfin_23000.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
! repo/com.cominatyou.batterytile_13.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
! repo/com.hifnawy.caffeinate_31.apk declares sensitive permission(s): android.permission.SYSTEM_ALERT_WINDOW
? repo/org.kiwix.kiwixmobile_5231235.apk no longer carries sensitive permission(s): android.permission.ACCESS_COARSE_LOCATION
! repo/org.kiwix.kiwixmobile_5231235.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
! repo/se.nullable.flickboard_50.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
juniojsv.minimum_1155.apk|3 malware alerts|22 libs
com.jinweijie.notifyme_140.apk|3 malware alerts|27 libs
! com.github.gouravkhunger.quotesapp: needs SelfUpdater
```

Which then means to reach out to developers for clarification/fixes ("needs xxx" refers to anti-features; in case of `com.github.gouravkhunger.quotesapp` you can see an [example here](https://github.com/gouravkhunger/QuotesApp/issues/22). And things like "no longer carries sensitive permission(s)" are usually a result of our "reaching out", making apps even more privacy-friendly. Those "malware alerts" refer to VirusTotal (here: 3 out of currently 66 engines reported "something" – in most cases those are "false positives" luckily).

And yes, those details are made transparent:

![image](https://github.com/user-attachments/assets/2ccf9ce4-a7c5-4551-b070-58357823857b)

I hope I could answer your questions. If there are more, just ask them and I try to clarify them as well.

2024-11-29 23:47 UTC, blacklight447 approved these changes

2024-11-29 23:50 UTC, redoomed1 commented on docs/android/obtaining-apps.md
> +Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from GitHub
```suggestion
Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from code forges (GitHub, GitLab, etc.) and is the next best thing to the developers' own repositories. They also offer [reproducible builds](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) for some applications and have developers who verify the reproducibility of developer-signed APKs. Furthermore, the developers behind the IzzyOnDroid conduct [additional security scans](https://android.izzysoft.de/articles/named/iod-scan-apkchecks) of apps housed in the repo, which usually result in a collaborative process between them and other app developers toward privacy improvements in these apps. Note that apps may be removed from the IzzyOnDroid repo in [certain circumstances](https://gitlab.com/IzzyOnDroid/repo#are-apps-removed-from-the-repo--and-when-does-that-happen).
```
I worked in the generous feedback offered by @IzzySoft above. What do y'all think of this latest revision?

2024-11-30 00:28 UTC, redoomed1 commented on docs/android/obtaining-apps.md
https://github.com/privacyguides/privacyguides.org/pull/2818#discussion_r1863997438

2024-11-30 00:33 UTC, IzzySoft commented on docs/android/obtaining-apps.md
> +Other popular third-party repositories for F-Droid such as [IzzyOnDroid](https://apt.izzysoft.de/fdroid) alleviate some of these concerns. The IzzyOnDroid repository pulls builds directly from GitHub
Thanks @redoomed1! May I suggest "upgrading" the "[RBs] for some applications" to "for many applications" (or at least "for hundreds of"), as almost every third app is covered meanwhile (numbers still climbing, we hope to cross the 30% mark this year at least)? More and more of our apps are added to our "RB program" constantly. As RBs run on a separate track with our configuration, they don't require "re-signing" or something: we always ship the APKs signed by their resp. devs, and just "independently" confirm whether they're RB.

Speaking of "independent", one of the builders is even run by an independent party, who is not part of the IoD team – and we welcome such independents and value them high. Our Wiki has an article for those considering to establish such a [Verification Builder](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Verification-Builder). In our eyes this adds to trust: 3 different parties (dev, IoD, independent builder) agreeing is more than two :stuck_out_tongue_winking_eye:

> and have developers who verify the reproducibility

That will also soon be made more transparent (working on a little overhaul of the relevant documentation currently, the above mentioned wiki page will move then when the structure is updated). You can e.g. use [rbtlui](https://apt.izzysoft.de/packages/dev.bg.rbtlui) to investigate/visualize them.

> QuotesApp/issues/22

Not sure if that link should go into the "public documentation", it was just an example I randomly picked (as it showed up in today's report). But it indeed covers multiple cases. Maybe it should be made clear it's just an example? Idk, maybe I'm just a bit too sensible there… So your choice, I'm just thinking aloud here.

Apart from that it looks great, thanks again!

2024-11-30 01:36 UTC, IzzySoft approved these changes

2024-11-30 01:36 UTC, IzzySoft commented
Thanks a lot to all of you! :heart_eyes:

2024-11-30 04:51 UTC, dngray approved these changes

2024-11-30 04:52 UTC, merged