Draft: tidying up the Monero section and recommending some places to buy it from
privacyguides/privacyguides.org pull request #2823
Opened 2024-11-27 14:37 UTC by eylenburg

List of changes proposed in this PR:

-

The main change is adding some recommendations for where to buy Monero. This a list of various reputable places with different requirements (Kraken: KYC ok; Cake Wallet: avoid KYC; RetoSwap: P2P and no country restrictions).

I also added some sub-headings for wallets and nodes and put the comments about Monero's resilience in a summary+detail box.

Finally, some cross-linking between the advanced/payments.md and the cryptocurrency.md pages.

I have just written this in Markdown so hopefully the end result will render correctly. Also happy for to make changes, this is just a first draft.

2024-11-27 14:51 UTC, eylenburg commented
Seems like the geographical restrictions admonition box and the footnotes are not formatted correctly. How do I fix it?

2024-11-29 14:21 UTC, SamsungGalaxyPlayer submitted a review, later dismissed
Thank you for your suggestions! I kindly request that we wait until MAGIC Grants can do a legal review of proposed money/cryptocurrency PRs before merging, due to the sensitivity of some related laws. This is something we should get to this weekend or early next week. Thank you for your understanding!

2024-11-29 14:24 UTC, eylenburg commented
Thank you that's absolutely no problem. 

By the way, Kraken and Cake Wallet are mentioned on the website currently (in advanced/payments.md and cryptocurrency.md respectively). Only Reto is new but seems to be the "go-to" recommendation in the Monero community since LocalMonero shut down.

2024-11-30 03:28 UTC, SamsungGalaxyPlayer commented
@eylenburg please check to see if you have any questions or concerns with the changes. Thanks!

2024-11-30 04:35 UTC, redoomed1 requested changes
The internal links for the Notices and Disclaimers page on each edited page are broken, which need to be corrected before merging.

2024-11-30 04:35 UTC, redoomed1 commented on docs/cryptocurrency.md
> +- [Cake Wallet](https://cakewallet.com): A self-custody cross-platform wallet for Monero and other cryptocurrencies. You can buy Monero directly in the app using card payments or bank transfers (thro
```suggestion
- [Cake Wallet](https://cakewallet.com): A self-custody cross-platform wallet for Monero and other cryptocurrencies. You can buy Monero directly in the app using card payments or bank transfers (through third-party providers such as [Guardarian](https://guardarian.com) or [DFX](https://dfx.swiss)). KYC is usually not required, but it depends on your country and the amount you are purchasing. In countries where directly purchasing Monero is not possible, you can also use a provider within Cake Wallet to first buy another cryptocurrency such as Bitcoin, Bitcoin Cash, or Litecoin and then exchange it to Monero in-app.
```

2024-11-30 04:35 UTC, redoomed1 commented on docs/cryptocurrency.md
> +- [RetoSwap](https://haveno-reto.com/) (formerly known as Haveno-Reto) is a self-custody, decentralized P2P exchange platform based on the [Haveno](https://haveno.exchange/) project which is availabl
```suggestion
- [RetoSwap](https://haveno-reto.com) (formerly known as Haveno-Reto) is a self-custody, decentralized P2P exchange platform based on the [Haveno](https://haveno.exchange) project which is available for Linux, Windows, and macOS. Monero can be bought and sold with maximum privacy, since most trading counterparties do not require KYC, trades are made directly between users (P2P), and all connections run through the Tor network. It is possible to buy Monero via bank transfer, Paypal, or even by paying in cash (meeting in person or sending by mail). Arbitrators can step in to resolve disputes between buyer and seller, but be careful when sharing your bank account or other sensitive information with your trading counterparty. Trading with some accounts may be against those accounts' terms of service.
```

2024-11-30 04:35 UTC, redoomed1 commented on docs/cryptocurrency.md
> +</details>
This suggestion attempts to make the content in the admonition less visually overwhelming by adding bullet points for each line where appropriate and containing the information in line 106 to [annotations](https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-admonitions), similar to those for country count on the VPN page.
```suggestion
<details class="warning annotate" markdown>
<summary>Geographical restrictions when buying Monero</summary>

Kraken does **not** allow the purchase of Monero for customers from (1):

- _Europe_: European Union member countries, United Kingdom, Norway, Iceland, Russia, Belarus

- _Asia_: Japan, North Korea, Iran, Iraq, Syria, Afghanistan

- _Other_: Australia, Cuba, DR Congo

Cake Wallet and Monero.com **only** allow the direct purchase of Monero (through third-party providers) for customers from (2):

- _Europe_: European Union member countries, Bosnia-Herzegovina, Iceland, Moldova, Montenegro, Norway, Switzerland, Ukraine, United Kingdom (not on Monero.com)

- _North America_: Costa Rica, Dominican Republic, El Salvador, Grenada, Guatemala, Honduras, Mexico, United States

- _South America_: Argentina, Brazil, Chile, Colombia, Ecuador, Paraguay, Peru, Uruguay

- _Asia_: Armenia, Azerbaijan, Kazakhstan, Kyrgyzstan, Israel (not on Monero.com), Lebanon, Maldives, South Korea, Sri Lanka, Tajikistan, Thailand, Turkey, Turkmenistan, Uzbekistan

- _Africa_: Algeria, Angola, Central African Republic, Kenya, Niger, Republic of the Congo, Seychelles, Sudan, Tunisia, Zambia, Zimbabwe

- _Oceania_: New Zealand

</details>

1. Last checked: November 2024. Country lists: [[1]](https://support.kraken.com/hc/en-us/articles/360001368823-Where-can-I-use-Kraken-) [[2]](https://support.kraken.com/hc/en-us/articles/support-for-monero-xmr-in-europe)
2. Last checked: November 2024. Country lists: [[1]](https://guardarian.freshdesk.com/support/solutions/articles/80001151826-what-are-the-supported-countries-regions-) [[2]](https://docs.dfx.swiss/en/faq.html#which-countries-are-served-by-dfx)
```

2024-11-30 04:35 UTC, redoomed1 commented on docs/cryptocurrency.md
> +The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check wi
```suggestion
The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check with a professional to confirm that these recommendations are legal and available in your jurisdiction. [See all notices](about/notices.md).
```

2024-11-30 04:35 UTC, redoomed1 commented on docs/financial-services.md
> +The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check wi
```suggestion
The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check with a professional to confirm that these recommendations are legal and available in your jurisdiction. [See all notices](about/notices.md).
```

2024-11-30 04:35 UTC, redoomed1 commented on docs/advanced/payments.md
> +The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check wi
```suggestion
The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check with a professional to confirm that these recommendations are legal and available in your jurisdiction. [See all notices](about/notices.md).
```

2024-11-30 14:36 UTC, redoomed1 commented on docs/advanced/payments.md
> +The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check wi
```suggestion
The content here is not legal or financial advice. We do not endorse or encourage illicit activities, and we do not endorse or encourage anything which violates a company's terms of service. Check with a professional to confirm that these recommendations are legal and available in your jurisdiction. [See all notices](../about/notices.md).
```

2024-11-30 17:19 UTC, eylenburg commented
New website for Retoswap is online now: https://retoswap.com/

2024-12-10 04:20 UTC, dngray approved these changes

2024-12-12 15:42 UTC, friadev approved these changes

2024-12-13 03:08 UTC, jonaharagon commented on docs/cryptocurrency.md
> +2. Last checked: November 2024. Country lists: [[1]](https://guardarian.freshdesk.com/support/solutions/articles/80001151826-what-are-the-supported-countries-regions-) [[2]](https://docs.dfx.swiss/en
Is this really something we want to maintain a list of on the site?

2024-12-13 04:52 UTC, friadev commented on docs/cryptocurrency.md
> +2. Last checked: November 2024. Country lists: [[1]](https://guardarian.freshdesk.com/support/solutions/articles/80001151826-what-are-the-supported-countries-regions-) [[2]](https://docs.dfx.swiss/en
Yeah good point, might remove that part.

2024-12-21 15:00 UTC, redoomed1 reviewed
These suggested changes attempt to streamline the info about geographical restrictions and avoid unnecessary maintenance burden as hinted by Jonah [here](https://github.com/privacyguides/privacyguides.org/pull/2823#discussion_r1883186751).

2024-12-21 15:34 UTC, eylenburg commented on docs/cryptocurrency.md
> +2. Last checked: November 2024. Country lists: [[1]](https://guardarian.freshdesk.com/support/solutions/articles/80001151826-what-are-the-supported-countries-regions-) [[2]](https://docs.dfx.swiss/en
Agreed due to the maintenance burden

2024-12-24 14:16 UTC, merged

2025-02-09 17:13 UTC, Anvil5465 commented
Could we specifically recommend trading crypto with Kraken Pro rather than Kraken's instant buy/sell feature? It's less intuitive but the fees are much, much lower than the regular Kraken website. With crypto trades made via Kraken Pro, fees [range from 0-0.4%](https://support.kraken.com/hc/en-us/articles/201893638-How-trading-fees-work-on-Kraken) compared with a flat 1.5% fee if you use regular Kraken's instant buy/sell feature.

2025-02-09 21:03 UTC, jermanuts commented
interesting, thanks for sharing @Anvil5465 this is somehow the first time hearing of Kraken Pro, have you personally tried it? Seems like process is straight forward and you don't have to subscribe or do anything more other than switching to https://pro.kraken.com/ if you are buying through the web.

Is it only useful if you are buying or selling large amounts as shown https://www.kraken.com/features/fee-schedule#spot-crypto

2025-02-09 21:17 UTC, Anvil5465 commented
> Is it only useful if you are buying or selling large amounts as shown https://www.kraken.com/features/fee-schedule#spot-crypto ?

@jermanuts Nope, I just tried it today and bought $10 worth of monero. It charged me 4 cents in fees which makes sense given the fee schedule. As you say, I didn't have to subscribe or do anything other than use the Kraken Pro website.

2025-02-09 23:05 UTC, Anvil5465 commented
Just realized this was merged 2 months ago so maybe I'll open a discussion in the forum