update!(blog): Biometrics article
privacyguides/privacyguides.org pull request #2826
Opened 2024-12-01 04:15 UTC by friadev

List of changes proposed in this PR:

-added article on biometrics

2024-12-29 18:27 UTC, friadev commented
Image source: https://images.unsplash.com/photo-1585079374502-415f8516dcc3?q=80&w=2370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D

2025-01-14 18:32 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +An optical sensor works just like you'd think it would: by taking a picture of your fingerprint and turning it into data. These are the cheapest and least secure option. They're potentially vulnerabl
An optical sensor works by capturing a picture of your fingerprint and turning it into data. They are the cheapest and least secure option. Since optical sensors capture a two-dimensional image, an attacker may simply take a picture of this fingerprint to gain access.

2025-01-14 18:35 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Fingerprint authentication will protect you against someone filming you surreptitiously while typing in your password or shoulder surfing. This is an especially relevant attack if your threat model i
```
Fingerprint authentication will protect you against someone filming you surreptitiously while typing in your password or shoulder surfing. This is an especially relevant attack if your threat model includes thieves as a common attack is watching you type your passcode in and then stealing your phone.
```

2025-01-14 18:37 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +An optical sensor works just like you'd think it would: by taking a picture of your fingerprint and turning it into data. These are the cheapest and least secure option. They're potentially vulnerabl
```suggestion
An optical sensor works by taking a picture of your fingerprint and turning it into data. They are the cheapest and least secure option. Since optical sensors capture two-dimensional images, an attacker may gain access by simply taking a picture of your fingerprint.
```

2025-01-14 18:38 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +One downside is that you lose the protection against dead tissue that capacitive sensors offer, but this is not relevant for most people.
If you're dead, I guess that wouldn't be the most pressing concern haha

2025-01-14 18:41 UTC, friadev commented on blog/posts/biometrics-explained.md
> +One downside is that you lose the protection against dead tissue that capacitive sensors offer, but this is not relevant for most people.
True haha just thought it was interesting to mention.

2025-01-14 18:41 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Capacitive sensors measure the electrical conductivity of your finger. These are much more secure than optical sensors since they can't be fooled with an image. They're also tough to fool with prosth
```suggestion
Capacitive sensors measure the electrical conductivity of your finger. These are more secure than optical sensors since they cannot be fooled with an image. They are less likely to be fooled by prosthetics since they utilize materials with different electrical properties.
```

2025-01-14 18:43 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +You'll likely want an implementation with some protection against another person pointing your phone at your face to unlock it. iOS allows you to enable a setting where you need to be looking at the
```suggestion
You will likely want some protection against another person pointing your phone at your face to unlock it. iOS allows you to enable a setting where you need to be looking at the phone before it will unlock, look for a similar feature when shopping for a device.
```

2025-01-14 18:43 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +A spy movie classic but newcomer in the consumer electronics field, iris sensors offer authentication via the unique properties of your eyes. The Apple Vision Pro is the most notable example with its
```suggestion
A spy movie classic but a recent addition in the consumer electronics field, iris sensors relies on the unique properties of your eyes. The Apple Vision Pro is the most notable example with its [Optic ID](https://support.apple.com/en-us/118483).
```

2025-01-14 18:46 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +The stated usecase is 2FA and continuous authentication for employee devices. Likely you'll only encounter this technology on work devices, especially since this type of biometrics will be affected b
```suggestion
Their stated usage case focuses on two-factor and continuous authentication for employee devices.You may only encounter this technology on work devices, especially since this type of authentication will be affected by the keyboard you're using. This authentication type works best on specific devices that are used often, such as a work laptop.
```

2025-01-14 18:50 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Possibly the most insidious of the biometrics in widespread use is gait recognition. Yes, you can be uniquely identified just by how you walk. Combined with the huge network of cameras deployed in mo
```suggestion
Gait recognition is possibly the most infamous biometric authentication method, where someone can be identified based on their walking behavior. Combined with the huge network of cameras deployed in most cities, you could be identified and tracked around with a covered face.
```

2025-01-14 18:52 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +This type of biometric is mainly useful for surveillance purposes rather than authentication but it's good to be aware of since it will likely be used against you in any highly populated area.
```suggestion
This biometric type is mainly useful for surveillance purposes rather than authentication; especially as it can be used against you in urban centers.
```

2025-01-14 18:54 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +  ![Example of finger minutiae including forks (where one line splits into mulitple lines), ends (where a line ends), islands (isolated dots), and inclosures (lines that split into two and then recon
You may want to explain what a finger minutiae. For the layperson, they may think it is a typo rather than an actual term!

2025-01-14 18:56 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +This is the most expensive type of sensor but it produces the most accurate readings with the highest reliability. It doesn't matter if your finger is a bit dirty or wet, it will still work unlike op
```suggestion
Ultrasonic sensors are the most expensive but produce accurate readings with the highest reliability. It will function with dirty or wet fingers unlike optical or capacitive sensors.
```

2025-01-14 18:58 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Fingerprint unlock will inherently be vulnerable to someone forcing you to put your finger on the sensor to unlock your device, so keep this in mind when threat modeling.
```suggestion
Fingerprint unlock is vulnerable to external threats. An attacker may unlock your device by forcibly placing your finger on the sensor. Make sure to consider this factor when building your threat model. 
```

2025-01-14 19:00 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +They also won't work with gloves and sometimes screen protectors can interfere, so make sure that the sensor is uncovered and making direct contact with your actual finger.
```suggestion
They can be challenging to use with gloves or certain types of screen protectors. To prevent this, keep the fingerprint sensor uncovered and make direct contact with your finger.
```

2025-01-14 19:04 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Fingerprint authentication will protect you against someone filming you surreptitiously while typing in your password or shoulder surfing. This is an especially relevant attack if your threat model i
```suggestion
Fingerprint authentication could also protect you from shoulder-surfing attacks — where someone candidly films or observes a victim typing in their password. This is particularly relevant if your threat model includes physical adversaries such as thieves or police officers.
```

2025-01-14 19:09 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +The potential of this technology truly shines when 2D face unlock is combined with an infrared flood illuminator. These are able to shine thousands of invisible infrared dots on your face and record
```suggestion
The technology truly shines when 2D face unlock is combined with an infrared flood illuminator. They shine thousands of invisible infrared dots on your face, recording the distance of each one to create a 3D map of your face. This tech takes up a lot of space and adds additional cost to the device, as well as explaining the noticble "notch" on iPhones. This drawback might be worth the privacy benefits according to [Apple](https://support.apple.com/en-us/102381):
```

2025-01-14 19:12 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +You'll likely want an implementation with some protection against another person pointing your phone at your face to unlock it. iOS allows you to enable a setting where you need to be looking at the
You may also want to write the name of the feature

2025-01-14 19:13 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +All forms of biometric authentication rely on proper hardware such as a secure element in order to be secure. The secure element provides a secure and tamper-resistant place to store your biometric d
```suggestion
All forms of biometric authentication rely on proper hardware such as a secure element in order to be secure. The secure element provides a secure and tamper-resistant place to store your biometric data so it can't be easily extracted. Examples include Apple's [Secure Enclave](https://support.apple.com/guide/security/secure-enclave-sec59b0b31ff/web) and Google's [Titan M](https://security.googleblog.com/2021/10/pixel-6-setting-new-standard-for-mobile.html) series of chips. You should avoid devices that lack a secure element; they cannot ensure proper biometric security without one.
```

2025-01-14 19:20 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +If you're relying on a plain 2D image, then there's always the possibility that it could be fooled by a regular photo. Someone getting in to your phone because they have a picture of your face is a s
```suggestion
If you are relying on a 2D image, there is a chance that it could be fooled by a regular photo. Someone accessing your phone because of a publicly-available picture is a security nightmare scenario. Unfortunately, the only thing stopping it is at the whims of the algorithm programmed into your phone.
```

2025-01-14 19:22 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Conveniently they also don't require a light source under them to work, although they will struggle in the presence of moisture.
```suggestion
They do not require a light source under them to work, although they will struggle in the presence of moisture.
```

2025-01-14 19:27 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Capacitive sensors won't work if the [tissue is dead](https://www.livescience.com/62393-dead-fingerprint-unlock-phone.html), since dead tissue loses all electical charge. So morbid worries about some
```suggestion
Capacitive sensors cannot work if the [tissue is dead](https://www.livescience.com/62393-dead-fingerprint-unlock-phone.html) since it loses all electrical charge. If the information you are protecting cannot be exposed at all costs, this sensor type could work for you.

2025-01-14 19:28 UTC, kpham42 commented on blog/posts/biometrics-explained.md
> +Ultrasonic fingerprint sensors use sound to create a detailed 3D representation of your fingerprint using ultrasound waves (sound waves with a frequency greater than 20khz). It's a similar concept to
```suggestion
Ultrasonic fingerprint sensors use sound to create a detailed 3D representation of your fingerprint using ultrasound waves (sound waves with a frequency greater than 20khz). It is a similar to the methodology used to map the ocean floor: sound is emitted from transducers and bounces off your skin. By measuring the time it takes for the sound to reach the microphones, your phone can create a detailed map of the ridges and valleys in your finger.
```

2025-01-29 22:52 UTC, jonaharagon requested changes
Would you mind using the image credit format from this PR? 🙏 https://github.com/privacyguides/privacyguides.org/pull/2859

2025-01-30 21:16 UTC, friadev commented
> Would you mind using the image credit format from this PR? 🙏 #2859

All images or just the cover image?

2025-02-13 16:47 UTC, jonaharagon commented on blog/posts/biometrics-explained.md
> +All forms of biometric authentication rely on proper hardware such as a secure element in order to be secure. The secure element provides a secure and tamper-resistant place to store your biometric d
To tie this article into _privacy_ more, I would like it if you could expand a bit on locally stored biometrics versus the biometrics being used by, for example, Delta airlines or the TSA where they scan your face and match it with a central database.

Clearly we consider Face ID to be private, but the same technology used in situations like this would not be, and I don't think the article covers this in enough detail.

2025-02-13 19:09 UTC, jonaharagon approved these changes

2025-02-13 20:04 UTC, merged