Add page for Map/Navigation apps
privacyguides/privacyguides.org pull request #2827
Opened 2024-12-02 11:26 UTC by eylenburg

List of changes proposed in this PR:

Added another page recommending privacy-respecting maps apps.

The title photo is from Unsplash. Logos were optimized with scour and optipng.

Also I removed the F-Droid link for Organic Maps as it is not an external repo provided by the developers, however they link to F-Droid on their website so I'm not completely sure if this kind of endorsement means we should still add the F-Droid link.

2024-12-03 05:05 UTC, friadev requested changes
The forum post needs to be approved before this can be merged.

2025-01-04 15:03 UTC, eylenburg commented on docs/maps.md
> +### HERE WeGo
I think this comment is useful: https://discuss.privacyguides.net/t/add-navigation-gps-tools/13669/45

2025-01-07 08:49 UTC, eylenburg commented on docs/maps.md
> +### HERE WeGo
Is this something I need to change from my side or can you amend the PR to only include these two?

2025-01-07 18:33 UTC, friadev commented on docs/maps.md
> +### HERE WeGo
> Is this something I need to change from my side or can you amend the PR to only include these two?

Just waiting for OsmAnd to be approved on the forum first.

2025-02-03 21:23 UTC, jermanuts requested changes

2025-02-03 21:23 UTC, jermanuts commented on docs/maps.md
> +| [Magic Earth](#magic-earth) | [OpenStreetMap](https://https://www.openstreetmap.org/) | :material-check:{ .pg-green } | Anonymized[^1] | Proprietary |
Magic Earth link is broken

2025-02-03 23:29 UTC, friadev requested changes

2025-02-03 23:29 UTC, friadev commented on docs/maps.md
> +| [Magic Earth](#magic-earth) | [OpenStreetMap](https://https://www.openstreetmap.org/) | :material-check:{ .pg-green } | Anonymized[^1] | Proprietary |
```suggestion
| [Magic Earth](#magic-earth) | [OpenStreetMap](https://www.openstreetmap.org/) | :material-check:{ .pg-green } | Anonymized[^1] | Proprietary |
```

2025-02-04 18:58 UTC, friadev requested changes

2025-02-04 18:58 UTC, friadev commented on docs/maps.md
> +[^2]: Some opt-in features such as live traffic data require sending user data such as location and speed to HERE. This data is collected in a way that does not identify the user personally according
```suggestion
```

2025-02-04 18:58 UTC, friadev commented on docs/maps.md
> +Unlike the previous recommendations, HERE WeGo uses its own proprietary map data and is therefore a good option for users who live in regions where OpenStreetMap is insufficient. In fact, HERE's map
```suggestion
### HERE WeGo

<div class="admonition recommendation" markdown>

![HERE WeGo logo](assets/img/maps/here.png){ align=right }

**HERE WeGo** is a proprietary app made by HERE Technologies, a company owned by a consortium of multiple German automakers as well as Intel. The app's features include turn-by-turn navigation for walking, cycling and driving as well as using public transport, live traffic information, speed camera warnings, terrain and satellite maps, the ability to download maps for offline use, and shop info such as opening times or Yelp reviews.

The app can send your location data in order to provide real-time traffic information, but this is an opt-in feature and the data is anonymized (not linked to your personal identity). 

[:octicons-home-16: Homepage](https://www.here.com/products/wego){ .md-button .md-button--primary }
[:octicons-eye-16:](https://legal.here.com/en-gb/privacy/here-wego-here-application-or-here-maps-privacy-supplement-updated){ .card-link title="Privacy Policy" }

<details class="downloads" markdown>
<summary>Downloads</summary>

- [:simple-googleplay: Google Play](https://play.google.com/store/apps/details?id=com.here.app.maps&pli=1)
- [:simple-appstore: App Store](https://apps.apple.com/us/app/here-wego-maps-navigation/id955837609)
- [:octicons-browser-16: Web](https://wego.here.com/)

</details>

</div>

Unlike the previous recommendations, HERE WeGo uses its own proprietary map data and is therefore a good option for users who live in regions where OpenStreetMap is insufficient. In fact, HERE's map data is used by several car manufacturers for their built-in navigation systems.
```

2025-02-04 18:58 UTC, friadev commented on docs/maps.md
> +
```suggestion
```

2025-02-04 19:00 UTC, friadev requested changes

2025-02-05 09:58 UTC, eylenburg commented
I have removed HERE and Magic Earth, so just Organic Maps and OSMand recommended for now. If this gets approved and merged, I will make separate PRs for those two that can be discussed separately on the forum and here

2025-02-05 22:55 UTC, friadev approved these changes

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> + - [randomize-element, "table tbody"]
```suggestion
```
See suggestion for lines 16 to 23

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +
```suggestion
```
With just two recommendations on this page at this moment, I don't think the table is very useful IMO. We can consider re-adding it if more recommendations are added to this page (like the other pages which include randomized tables).

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +
```suggestion
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +### Organic Maps
```suggestion
## Organic Maps
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +**Organic Maps** is an open source, community-developed map display and satnav-style navigation app for walkers, drivers, and cyclists. The app offers worldwide offline maps based on OpenStreetMap da
```suggestion
**Organic Maps** is an open source, community-developed map display and satnav-style navigation app for walkers, drivers, and cyclists. The app offers worldwide offline maps based on OpenStreetMap data, and navigation with privacy — no location tracking, no data collection, and no ads. The app can be used completely offline.
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +**OsmAnd** is an offline map and navigation application based on OpenStreetMap, offering turn-by-turn navigation for walking, cycling, driving as well as public transport. It is open-source and does
```suggestion
**OsmAnd** is an offline map and navigation application based on OpenStreetMap, offering turn-by-turn navigation for walking, cycling, driving, as well as public transport. It is open-source and does not collect any user data. Some features are paid if you download the app from the Play Store or Apple App Store, but a completely free (though unofficial) version is available on F-Droid.
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +- Should have advanced features (that users may expect coming from Google or Apple Maps) such as detailed shop/POI information and reviews, topographic maps, and satellite and streetview images.
```suggestion
- Should support advanced features such as detailed shop/POI information and reviews, topographic maps, and satellite and streetview images.
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +[:octicons-eye-16:](hhttps://organicmaps.app/privacy/){ .card-link title="Privacy Policy" }
```suggestion
[:octicons-home-16: Homepage](https://organicmaps.app){ .md-button .md-button--primary }
[:octicons-eye-16:](https://organicmaps.app/privacy){ .card-link title="Privacy Policy" }
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +[:octicons-eye-16:](https://osmand.net/docs/legal/privacy-policy/){ .card-link title="Privacy Policy" }
```suggestion
[:octicons-home-16: Homepage](https://osmand.net){ .md-button .md-button--primary }
[:octicons-eye-16:](https://osmand.net/docs/legal/privacy-policy){ .card-link title="Privacy Policy" }
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/maps.md
> +[:octicons-info-16:](https://osmand.net/docs/intro){ .card-link title=Documentation}
```suggestion
[:octicons-info-16:](https://osmand.net/docs/intro){ .card-link title="Documentation" }
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/tools.md
> +- ![OsmAnd logo](assets/img/maps/osmand.svg){ .twemoji loading=lazy }[OsmAnd](maps.md#osmand)
```suggestion
- ![Organic Maps logo](assets/img/maps/organic-maps.svg){ .twemoji loading=lazy } [Organic Maps](maps.md#organic-maps)
- ![OsmAnd logo](assets/img/maps/osmand.svg){ .twemoji loading=lazy } [OsmAnd](maps.md#osmand)
```

2025-02-06 03:53 UTC, redoomed1 commented on docs/tools.md
> +[Learn more :material-arrow-right-drop-circle:](language-tools.md)
```suggestion
[Learn more :material-arrow-right-drop-circle:](maps.md)
```

2025-02-06 03:54 UTC, redoomed1 commented on docs/maps.md
> +### OsmAnd
```suggestion
## OsmAnd
```

2025-02-07 03:35 UTC, redoomed1 commented on docs/maps.md
> +- Maps can be downloaded and the app used entirely offline.
```suggestion
- Must retain core functionality when offline and allow users to download maps for offline use.
```
This is a suggestion to reword this sentence to conform to this [writing guideline](https://www.privacyguides.org/en/meta/writing-style/#use-must-for-requirements). Feel free to reword as you see fit.

2025-02-08 03:37 UTC, redoomed1 commented on docs/maps.md
> +Compared to Organic Maps, OsmAnd has more [features](https://wiki.openstreetmap.org/wiki/OsmAnd#Features) but is also more complicated to use. One noteworthy feature is the ability to overlay or unde
```suggestion
Compared to Organic Maps, OsmAnd has more [features](https://wiki.openstreetmap.org/wiki/OsmAnd#Features) but is also more complicated to use. One noteworthy feature is the ability to overlay or underlay external map data, such as satellite images from Microsoft or [traffic data](https://web.archive.org/web/20211203063453/http://themm.net/public/osmand_traffic) from Google, although the latter is ignored by the automatic route planning. OsmAnd also has an optional integration of streetview images provided by [Mapillary](https://www.mapillary.com).
```

2025-02-09 15:28 UTC, redoomed1 commented on docs/maps.md
> +- [:simple-googleplay: Google Play](https://play.google.com/store/apps/details?id=net.osmand)
```suggestion
- [:simple-googleplay: Google Play](https://play.google.com/store/apps/details?id=net.osmand)
- [:simple-android: Android](https://osmand.net/docs/versions/free-versions)
```
Per @I-I-IT's first suggestion

2025-02-10 15:03 UTC, dngray approved these changes

2025-03-02 19:15 UTC, redoomed1 requested changes

2025-03-02 19:15 UTC, redoomed1 commented on docs/maps.md
> +**OsmAnd** is an offline map and navigation application based on OpenStreetMap, offering turn-by-turn navigation for walking, cycling, driving, as well as public transport. It is open-source and does
```suggestion
**OsmAnd** is an offline map and navigation application based on OpenStreetMap, offering turn-by-turn navigation for walking, cycling, driving, as well as public transport. It is open-source and does not collect any user data.
```
After thinking about this for a little while, I think it would wise to not endorse the unofficial, albeit fully-featured, F-Droid version for two reasons.

1. End users may encounter a lack of support when it comes to this particular version. They may have to reach out to the maintainer(s) of the F-Droid build or the F-Droid developers themselves if any of the OsmAnd maintainers can't help them with their issue due to them using a version that's not officially supported. Here's an example of this: https://github.com/osmandapp/OsmAnd/issues/20597#issuecomment-2288208892.
2. People using the unofficial F-Droid version may have to wait longer for bug fixes than those using the Play Store version. For version 4.9.10, the Google Play version of OsmAnd (free) and OsmAnd+ (paid) were updated on 2024/12/12 and 2024/12/14, respectively. Meanwhile, the F-Droid build was updated on 2024/12/29 (_more than 2 weeks later_) for the same version.

2025-03-02 19:15 UTC, redoomed1 commented on docs/maps.md
> +Compared to Organic Maps, OsmAnd has more [features](https://wiki.openstreetmap.org/wiki/OsmAnd#Features) but is also more complicated to use. One noteworthy feature is the ability to overlay or unde
```suggestion
Compared to Organic Maps, OsmAnd has more [features](https://wiki.openstreetmap.org/wiki/OsmAnd#Features) but is also more complicated to use. One noteworthy feature is the ability to overlay or underlay external map data, such as satellite images from Microsoft or [traffic data](https://web.archive.org/web/20211203063453/http://themm.net/public/osmand_traffic) from Google, although the latter is ignored by the automatic route planning. OsmAnd also has an optional integration of streetview images provided by [Mapillary](https://mapillary.com).
```

2025-03-02 19:19 UTC, redoomed1 commented on docs/maps.md
> +- Should support advanced features such as detailed shop/POI information and reviews, topographic maps, and satellite and streetview images.
```suggestion
- Should support advanced features such as detailed shop/point of interest (POI) information and reviews, topographic maps, and satellite and streetview images.
```
This suggestion adds the long form of the abbreviation here since it wasn't explained previously.

2025-03-07 11:35 UTC, eylenburg commented
Are there any more suggestions of objections to getting it merged with just Osmand and Organic for now?

2025-03-08 11:07 UTC, merged