UnifiedPush now part of all Molly apps, Molly-UP app deprecated
privacyguides/privacyguides.org pull request #2829
Opened 2024-12-03 10:06 UTC by eylenburg

https://github.com/mollyim/mollyim-android/releases/tag/v7.26.1-1

Molly and Molly-FOSS now support UnifiedPush; Molly-UP is now deprecated and shows a banner telling users to migrate to another Molly app.

2024-12-03 16:53 UTC, jonaharagon requested changes
This is cool news, thanks for the update. Only making this as requesting changes because I want to take the time later to read though that kuketz blog before merging, since I've never heard of a public mollysocket server or whether that's something safe/secure to recommend people generally use like this

2024-12-03 16:53 UTC, jonaharagon commented on docs/real-time-communication.md
> +There is a version of Molly called **Molly-FOSS** which removes proprietary code like the Google services used by both Signal and Molly, at the expense of some features like battery-saving push notif
```suggestion
There is a version of Molly called **Molly-FOSS** which removes proprietary code like the Google services used by both Signal and Molly, at the expense of some features like battery-saving push notifications via Google Play Services. You can regain push notifications without Google Play Services in either version of Molly with [UnifiedPush](https://unifiedpush.org), but it requires running a separate program called [Mollysocket](https://github.com/mollyim/mollysocket) on another device to function. Mollysocket can either be self-hosted on a separate computer or server (VPS), or alternatively a public Mollysocket instance can be used ([step-by-step tutorial, in German](https://kuketz-blog.de/messenger-wechsel-von-signal-zu-molly-unifiedpush-mollysocket-ntfy)).
```

2025-01-14 07:29 UTC, jonaharagon approved these changes

2025-01-17 02:45 UTC, dngray approved these changes

2025-01-17 12:35 UTC, merged