Update calendar-contacts-sync.html
privacyguides/privacyguides.org pull request #283
Opened 2021-11-10 19:53 UTC by TheNoobWar

## Description

Resolves: Added a warning badge to Fruux under the Worth Mentioning section as it is a proprietary application.

2021-11-11 06:59 UTC, dngray commented
I'm actually wondering if this should even be on PrivacyGuides at all.

From what I can tell it was always there and never open source. It is not encrypted at rest either.

2021-11-11 10:14 UTC, Mikaela requested changes

2021-11-11 10:14 UTC, Mikaela commented on _includes/legacy/sections/calendar-contacts-sync.html
> +    tooltip="The source programming code for Fruux is not available. Fruux is a proprietary application."
```suggestion
    tooltip="The source code for Fruux is not available. Fruux is a proprietary application."
```

The word "programming" in the middle here looks a bit strange for me

2021-11-11 12:29 UTC, Mikaela approved these changes
Approving for now unless a delisting PR happens.

2021-11-12 10:52 UTC, freddy-m commented
> I'm actually wondering if this should even be on PrivacyGuides at all.

@dngray I don't think it should be either.

2021-11-12 11:01 UTC, Mikaela approved these changes
I think it should possibly be in a different PR that says `Resolves: #283` 🤷🏻

2021-11-12 11:03 UTC, freddy-m commented
> I think it should possibly be in a different PR that says Resolves: #283 🤷🏻

Nevermind

2021-11-12 11:06 UTC, merged