update: Update/fix information in Android distributions page
privacyguides/privacyguides.org pull request #2844
Opened 2024-12-28 01:13 UTC by friadev

List of changes proposed in this PR:

- remove “custom ROM” as it’s an inaccurate term
- Remove AOSP derivatives as a category because they will all be AOSP derivatives anyway

2024-12-30 08:07 UTC, dngray approved these changes

2024-12-30 19:45 UTC, friadev commented on docs/android/distributions.md
> +- [weaker security]{android.md#install-a-custom-distribution}
Fixed

2024-12-31 04:12 UTC, redoomed1 reviewed
Below are a few wording improvements.

2024-12-31 04:12 UTC, redoomed1 commented on docs/android/distributions.md
> +We recommend installing GrapheneOS if you have a Google Pixel as it has improved security hardening and privacy features. The reason we don't list other devices or OSes is because they often have:
```suggestion
We recommend installing GrapheneOS if you have a Google Pixel as it has improved security hardening and privacy features. The reasons we don't list other devices or OSes are as follows:
```

2024-12-31 04:12 UTC, redoomed1 commented on docs/android/distributions.md
> +- few or no notable privacy or security features that make the move worthwhile
```suggestion
- These devices and/or OSes often have [weaker security](index.md#install-a-custom-distribution).
- Support for these devices and/or OSes may simply be dropped when the maintainer loses interest or upgrades their device, which is in contrast to the predictable [support cycle](https://grapheneos.org/faq#device-lifetime) that GrapheneOS follows.
- These OSes simply have few or no notable privacy or security features that make installing them worthwhile.
```

2024-12-31 04:45 UTC, friadev commented on docs/android/distributions.md
> +- few or no notable privacy or security features that make the move worthwhile
Seems like the plural of OS should be OS’s
https://www.grammar-monster.com/lessons/abbreviations_forming_plurals.htm

2025-01-06 02:01 UTC, redoomed1 approved these changes
LGTM

2025-01-13 19:47 UTC, jonaharagon requested changes
I don't particularly care for `OSes` or `OSs`, but I think `OS's` is strictly worse than either of those. If we don't like this ambiguity, I would prefer to avoid using the acronym entirely and just say `operating systems`.

Leaving Custom ROM in the first paragraph was an intentional decision we made the last time we updated this page to remove "Custom ROM" from every other paragraph, and we should continue to keep it because it is how they are referred to in the largest Android development community, and we should remain accessible to those outside the privacy/security space.

![2025-01-13 at 13 43 51](https://github.com/user-attachments/assets/1b2aebe2-bb64-455c-be97-45ba6766dbc2)

I'm fine with removing it from the title, but we will have to check our ranking for "private custom rom" and other similar search terms over the next few months if we do, and revert that change if it causes problems.

![2025-01-13 at 13 45 49](https://github.com/user-attachments/assets/ae798119-be0a-43b4-b628-91f5e87bd704)

2025-01-13 19:47 UTC, jonaharagon commented on docs/android/distributions.md
> +meta_title: "The Best Custom Android OS's - Privacy Guides"
```suggestion
meta_title: "The Best Custom Android Operating Systems - Privacy Guides"
```

2025-01-13 19:47 UTC, jonaharagon commented on docs/android/distributions.md
> +A **custom Android-based operating system** (often mistakenly called a ROM) can be a way to achieve a higher level of privacy and security on your device. This is in contrast to the "stock" version o
```suggestion
A **custom Android-based operating system** (sometimes referred to as a **custom ROM**) can be a way to achieve a higher level of privacy and security on your device. This is in contrast to the "stock" version of Android which comes with your phone from the factory, and is often deeply integrated with Google Play Services as well as other vendor software.
```

2025-01-13 19:47 UTC, jonaharagon commented on docs/android/distributions.md
> +We recommend installing GrapheneOS if you have a Google Pixel as it provides improved security hardening and additional privacy features. The reasons we don't list other OS's or devices are as follow
```suggestion
We recommend installing GrapheneOS if you have a Google Pixel as it provides improved security hardening and additional privacy features. The reasons we don't list other operating systems or devices are as follows:
```

2025-01-13 19:47 UTC, jonaharagon commented on docs/android/distributions.md
> +- These OS's simply have few or no notable privacy or security features that make installing them worthwhile.
```suggestion
- They often have [weaker security](index.md#install-a-custom-distribution).
- Support is frequently dropped when the maintainer loses interest or upgrades their device, which is in contrast to the predictable [support cycle](https://grapheneos.org/faq#device-lifetime) that GrapheneOS follows.
- They generally have few or no notable privacy or security improvements that make installing them worthwhile.
```

2025-01-13 19:47 UTC, jonaharagon commented on docs/mobile-phones.md
> +[Recommended Custom OS's :material-arrow-right-drop-circle:](android/distributions.md){ .md-button .md-button--primary } [Details about Android Security :material-arrow-right-drop-circle:](os/android
```suggestion
[Recommended Android Distributions :material-arrow-right-drop-circle:](android/distributions.md){ .md-button .md-button--primary } [Details about Android Security :material-arrow-right-drop-circle:](os/android-overview.md#security-protections){ .md-button }
```

2025-01-13 19:47 UTC, jonaharagon commented on docs/os/android-overview.md
> +On Android distributions with privileged Google Play Services (such as stock OS's), the setting may be in one of several locations. Check
```suggestion
On Android distributions with privileged Google Play Services (which includes the stock installation on most devices), the setting may be in one of several locations. Check
```

2025-01-13 19:51 UTC, jonaharagon commented on docs/android/distributions.md
> +A **custom Android-based operating system** (often mistakenly called a ROM) can be a way to achieve a higher level of privacy and security on your device. This is in contrast to the "stock" version o
FYI the original wording was based on https://en.wikipedia.org/wiki/List_of_custom_Android_distributions

> [Android](https://en.wikipedia.org/wiki/Android_(operating_system))-based [operating systems](https://en.wikipedia.org/wiki/Operating_system) (OS) commonly referred to as Custom ROMs or Android ROMs

2025-01-14 07:17 UTC, jonaharagon approved these changes

2025-01-14 07:20 UTC, merged