Add CTemplar
privacyguides/privacyguides.org pull request #292
Opened 2021-11-11 07:44 UTC by dngray

## Description

Resolves: # https://github.com/privacyguides/privacyguides.org/discussions/131
Resolves: # https://github.com/privacytools/privacytools.io/issues/1642

2021-11-11 10:19 UTC, Mikaela requested changes
This TBD line doesn't seem like it belongs here.

2021-11-11 10:19 UTC, Mikaela commented on _includes/legacy/sections/email-providers.html
> +    <p>TBD</p>
Should this be a draft PR?

2021-11-11 11:59 UTC, dngray commented on _includes/legacy/sections/email-providers.html
> +    <p>TBD</p>
Yes it is.

2021-11-11 17:16 UTC, pm4rcin commented
I have some problems with adding CTemplar.
1. They had no backup and data loss occurred. There was no e-mail or any information on the front page. I had only a few messages and didn't lose any but it was enough to close the account. I discovered that it happened accidentally by looking at privacytools Github. I wouldn't know about it otherwise. I really liked transparency like e.g. Gitlab did with their failure handling and this is completely opposite. Here's some info:
https://github.com/privacytools/privacytools.io/issues/1642#issuecomment-878255344
2. Regarding tor support they have disabled it today as reported on their twitter: [Ctemplar Twitter](https://nitter.net/RealCTemplar/status/1458775445202157570). I have checked it manually and when logging in it redirects to ctemplar.com.

2021-11-12 06:53 UTC, dngray commented
> They had no backup and data loss occurred. There was no e-mail or any information on the front page. I had only a few messages and didn't lose any but it was enough to close the account. I discovered that it happened accidentally by looking at privacytools Github. I wouldn't know about it otherwise. I really liked transparency like e.g. Gitlab did with their failure handling and this is completely opposite. Here's some info:
> https://github.com/privacytools/privacytools.io/issues/1642#issuecomment-878255344

We're aware of this issue and while it isn't ideal, it does seem that the company has taken some serious steps to make sure it never happens again https://github.com/privacyguides/privacyguides.org/discussions/131#discussioncomment-1581612

> Regarding tor support they have disabled it today as reported on their twitter: [Ctemplar Twitter](https://nitter.net/RealCTemplar/status/1458775445202157570). I have checked it manually and when logging in it redirects to ctemplar.com.

That is unfortunate.

2021-11-12 10:03 UTC, OneWhiteBird commented
[SVG.zip](https://github.com/privacyguides/privacyguides.org/files/7526684/SVG.zip)

Edited logos, as requested!

2021-12-01 13:20 UTC, dngray commented
> Regarding tor support they have disabled it today as reported on their twitter: [Ctemplar Twitter](https://nitter.net/RealCTemplar/status/1458775445202157570). I have checked it manually and when logging in it redirects to ctemplar.com.

Still seems to be the case
```
> GET / HTTP/1.1
> Host: mail.ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion
> User-Agent: curl/7.80.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Wed, 01 Dec 2021 13:15:40 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Location: https://mail.ctemplar.com/
<
```

Worth noting that Protonmail still has this enabled
```
> GET /login HTTP/1.1
> Host: protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion
> User-Agent: curl/7.80.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Wed, 01 Dec 2021 13:18:32 GMT
< last-modified: Sun, 31 Jan 2021 09:41:46 GMT
< accept-ranges: bytes
< content-length: 3309
< vary: Accept-Encoding
< cache-control: max-age=0, no-cache, no-store, must-revalidate
< expires: Wed, 11 Jan 1984 05:00:00 GMT
< set-cookie: Session-Id=Yad2KC3wGVsmJJPzMw5P0QAAAN0; Domain=protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion; Path=/; HttpOnly; Secure; Max-Age=7776000
< set-cookie: Version=default; Path=/; Secure; Max-Age=7776000
< pragma: no-cache
< content-type: text/html; charset=UTF-8
< content-security-policy: default-src 'self'; connect-src 'self' blob:; script-src 'self' blob: 'sha256-eAhF1Kdccp0BTXM6nMW7SYBdV0c3fZwzcC177TQ692g='; style-src 'self' 'unsafe-inline'; img-src http: https: data: blob: cid:; frame-src 'self' blob: https://secure.protonmail.com; object-src 'self' blob:; child-src 'self' data: blob:; report-uri https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api/reports/csp;
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< expect-ct: max-age=2592000, enforce, report-uri="https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api/reports/tls"
< x-frame-options: deny
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block; report=https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api/reports/csp
< referrer-policy: strict-origin-when-cross-origin
< x-permitted-cross-domain-policies: none
<
```

2021-12-01 13:36 UTC, OneWhiteBird commented
> > Regarding tor support they have disabled it today as reported on their twitter: [Ctemplar Twitter](https://nitter.net/RealCTemplar/status/1458775445202157570). I have checked it manually and when logging in it redirects to ctemplar.com.
> 
> Still seems to be the case
> 
> ```
> > GET / HTTP/1.1
> > Host: mail.ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion
> > User-Agent: curl/7.80.0
> > Accept: */*
> >
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 301 Moved Permanently
> < Server: nginx
> < Date: Wed, 01 Dec 2021 13:15:40 GMT
> < Content-Type: text/html
> < Content-Length: 178
> < Connection: keep-alive
> < Location: https://mail.ctemplar.com/
> <
> ```
> 
> Worth noting that Protonmail still has this enabled
> 
> ```
> > GET /login HTTP/1.1
> > Host: protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion
> > User-Agent: curl/7.80.0
> > Accept: */*
> >
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> * old SSL session ID is stale, removing
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 200 OK
> < date: Wed, 01 Dec 2021 13:18:32 GMT
> < last-modified: Sun, 31 Jan 2021 09:41:46 GMT
> < accept-ranges: bytes
> < content-length: 3309
> < vary: Accept-Encoding
> < cache-control: max-age=0, no-cache, no-store, must-revalidate
> < expires: Wed, 11 Jan 1984 05:00:00 GMT
> < set-cookie: Session-Id=Yad2KC3wGVsmJJPzMw5P0QAAAN0; Domain=protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion; Path=/; HttpOnly; Secure; Max-Age=7776000
> < set-cookie: Version=default; Path=/; Secure; Max-Age=7776000
> < pragma: no-cache
> < content-type: text/html; charset=UTF-8
> < content-security-policy: default-src 'self'; connect-src 'self' blob:; script-src 'self' blob: 'sha256-eAhF1Kdccp0BTXM6nMW7SYBdV0c3fZwzcC177TQ692g='; style-src 'self' 'unsafe-inline'; img-src http: https: data: blob: cid:; frame-src 'self' blob: https://secure.protonmail.com; object-src 'self' blob:; child-src 'self' data: blob:; report-uri https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api/reports/csp;
> < strict-transport-security: max-age=31536000; includeSubDomains; preload
> < expect-ct: max-age=2592000, enforce, report-uri="https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api/reports/tls"
> < x-frame-options: deny
> < x-content-type-options: nosniff
> < x-xss-protection: 1; mode=block; report=https://protonmailrmez3lotccipshtkleegetolb73fuirgj7r4o4vfu7ozyd.onion/api/reports/csp
> < referrer-policy: strict-origin-when-cross-origin
> < x-permitted-cross-domain-policies: none
> <
> ```

Regarding CTemplar, it is correct. Until the [CORS](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/32865) issue is fixed, all the API requests using Tor Browser through the .onion domain will not work. So we have decided to redirect the users to our clearnet domain, until it is fixed.

2021-12-01 13:50 UTC, dngray commented
I think this one is ready for review/merge.

2021-12-01 14:41 UTC, freddy-m approved these changes
LGTM!

2021-12-01 14:42 UTC, merged