(WIP) New Linux page
privacyguides/privacyguides.org pull request #491
Opened 2021-12-22 14:19 UTC by tommytran732

This is a WIP

2021-12-26 01:06 UTC, youdontneedtoknow22 commented
I'm still not really convinced of labeling Fedora as a beginner friendly distro, while the community itself describes it as a distro for developers. And people can easily notice that they're not targeting beginners with their bleading edge distro, their vanilla gnome and no non-free software up until Fedora 34/35. It's just not their philosophy.
I really think you should think again about what distro should you recommend as beginner friendly.

2021-12-26 01:32 UTC, tommytran732 commented
> I'm still not really convinced of labeling Fedora as a beginner friendly distro, while the community itself describes it as a distro for developers. And people can easily notice that they're not targeting beginners with their bleading edge distro, their vanilla gnome and no non-free software up until Fedora 34/35. It's just not their philosophy.
> I really think you should think again about what distro should you recommend as beginner friendly.

What would you recommend then?
Also the good thing about Fedora is that they stay close to upstream, so they can get updates really, really fast. I am not keen on distros with mostly frozen packages, especially on desktop

2021-12-27 05:49 UTC, Dyrimon commented on _data/operating-systems/linux-desktop-immutable/1_fedora-silverblue.yml
> +privacy_policy: 'https://wiki.archlinux.org/index.php/ArchWiki:Privacy_policy'
Silverblue privacy policy button points to archwiki privacy policy

2021-12-27 05:55 UTC, Dyrimon commented on collections/_evergreen/linux-desktop.html
> +<p><a href="https://blog.samalik.com/">Adam Samalik</a> has a great demonstration of how rpm-ostree and atomic updates work:</p>
Link to Adam Samalik's actual blog post explaining rpm-ostree and atomic updates instead of his general blog.

2021-12-30 19:42 UTC, tommytran732 commented on _data/operating-systems/linux-desktop-immutable/1_fedora-silverblue.yml
> +privacy_policy: 'https://wiki.archlinux.org/index.php/ArchWiki:Privacy_policy'
Fixed

2022-01-01 04:50 UTC, jonaharagon requested changes

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +description: "Linux distributions are commonly recommended for user freedom and privacy. This page will go over distribution selection and general configuration for privacy and security. This is not
```suggestion
description: "Linux distributions are commonly recommended for privacy protection and user freedom. This page will go over distribution selection and general privacy and security configuration. This is not a guide on how to use Linux."
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p>These distributions are recommended on the basis that they ship close to vanilla packages and stay very close to upstream, allowing them to get security features/bug fixes very quickly.</p>
```suggestion
<p>These distributions are recommended because they ship mostly unmodified applications, which allow them to receive security/bug fixes very quickly.</p>
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +{% endfor %}
I think I would swap the order here and do:

1. Traditional
2. Tor-focused
3. Immutable/Atomic

```suggestion
<h2 id="tor" class="anchor">
    <a href="#tor"><i class="fas fa-link anchor-icon"></i></a>
    Tor-focused distributions
</h2>

<p>These distributions are recommended because they focus on providing maximum anonymity using the Tor network.</p>

{% for item_hash in site.data.operating-systems.linux-desktop-tor %}
{% assign item = item_hash[1] %}

{% if item.type == "Recommendation" %}
{% include recommendation-card.html %}
{% endif %}

{% endfor %}

<h2 id="immutable" class="anchor">
    <a href="#immutable"><i class="fas fa-link anchor-icon"></i></a>
    Immutable distributions
</h2>

<p>These distributions are recommended because they are <a href="#atomic">atomic</a>, meaning users can update and modify their systems without fear of instability and breakage.</p>

{% for item_hash in site.data.operating-systems.linux-desktop-immutable %}
{% assign item = item_hash[1] %}

{% if item.type == "Recommendation" %}
{% include recommendation-card.html %}
{% endif %}

{% endfor %}
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Obviously this needs to not be a YouTube iFrame.

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p>Beyond just security, holding packages back and applying a bunch of backports fundamentally just does not work that well. <a href="https://rootco.de">Richard Brown</a> has a really great presentat
```suggestion
<p>Using a distribution that stays close to upstream is highly recommended. Avoid distributions with frozen packages, as they are often quite behind on security updates. For example, Debian famously fell behind on Firefox-ESR updates for <a href="https://tracker.debian.org/pkg/firefox-esr">2 months</a>, in one of which their version (78) was deemed end of life by Mozilla. They also cannot keep up with Chromium updates, leading to them having an outdated package with many <a href="https://tracker.debian.org/pkg/chromium">vulnerabilities</a>. Most notably, Debian <a href="https://www.debian.org/security/faq#handling">only</a> backports security fixes that have recieved a <a href="https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures">CVE</a>. A lot of security fixes <a href="https://arxiv.org/abs/2105.14565">do not</a> recieve a CVE at all, and do not make it to an LTS distribution with this patching model. Sometimes, minor security fixes are also held back until the next release of Debian.</p>
<p>Beyond security, holding packages back and applying a bunch of backports fundamentally just does not work that well. <a href="https://rootco.de">Richard Brown</a> has a great presentation about this:</p>
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +
Not needed for the purposes of this article.

```suggestion
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p>Other distributions like Kali Linux, Black Arch, Parrot OS, etc are penetration testing distributions. They are meant to be used as an attacker machine, not as a tool to protect you, the end user.
```suggestion
<h5>"Security-focused" distributions</h5>
<p>Distributions like Whonix and Tails are designed with your own security in mind. They are meant to protect you. If you are looking for security and anonymity, these are the distributions you should be using.</p>
<p>Other distributions like Kali Linux, Black Arch, Parrot OS, etc are penetration testing distributions. They are meant to be used as an attacker machine, not as a tool to protect you, the end user. This is a common misconception about these distributions among Linux newcomers. Avoid using these distributions as your daily driver.</p>
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p>The user is also expected to have sufficient Linux knowledge to properly set up security for their system such as enabling a mandatory access control system, doing firewalling, setting up kernel m
This section doesn't make sense as-is because you recommend Arch above, it should clarify this is referring to distros downstream of Arch, or it should be removed, or we should remove Arch from above recommendations.

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +    Atomic/Transactional update
```suggestion
    Atomic/Transactional Updates
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p>In a system with atomic update, and update is either applied fully or completely diregarded. An update cannot suddenly fail and be applied half way through. Typically, a system with atomic update
```suggestion
<p>In systems with atomic updates, an update is either applied fully or completely disregarded. An update cannot suddenly fail and be applied half way through. Typically, an atomic system will also provide an easy way to roll the system back to a previous state should a bug occur after an update as well. These features make them a great choice if you are not otherwise comfortable with fast-moving rolling-release distributions that can be prone to breakage.</p>
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/-hpV5l-gJnQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Again, YouTube allergy

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p>In a system with transactional update, a snapshot is of the system is created before and after the update is applied. Should something go wrong during or after the update is applied, the user can
```suggestion
<p>In an atomic system, a snapshot of the system is created before and after the update is applied. Should something go wrong during or after the update is applied, the user can easily roll the system back to its previous state.</p>
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p><a href="https://www.suse.com">SUSE</a> has a demonstration of a full system rollback with their transactional server:</p>
```suggestion
<p>SUSE has a demonstration of a full system rollback with their transactional server:</p>
```

2022-01-01 04:50 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<p>Overall, we believe that for desktop usage, it is better to use an up to date distribution with a rollback mechanism than holding onto an outdated "Frankenstein" distribution.</p>
```suggestion
```

2022-01-01 04:50 UTC, jonaharagon commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +title: Whonix
I don't know if I would ever recommend Whonix to anybody when not paired with Qubes, so I would lean towards this recommendation being Qubes instead. Thoughts?

2022-01-01 04:50 UTC, jonaharagon commented on _data/operating-systems/linux-desktop-immutable/1_fedora-silverblue.yml
> +title: Fedora Silverblue/Kinoite
Are Fedora "spins" considered to be high-quality releases? I know Silverblue is an official emerging Fedora release, I'm not sure if Kinoite meets that same standard, does it?

2022-01-01 10:42 UTC, dngray commented on _data/operating-systems/linux-desktop-immutable/1_fedora-silverblue.yml
> +title: Fedora Silverblue/Kinoite
Yes, Kionite is an official ostree

2022-01-01 10:44 UTC, dngray commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +title: Whonix
They do different things. Whonix can certainly be used with KVM and other Virtualization stacks.

Qubes doesn't inherently offer a Tor gateway, they work well together but one does not replace the other.

2022-01-01 11:12 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
I don't think there's any privacy issue here. We should not use specific invidious instances as they tend to be unstable. https://github.com/privacyguides/privacyguides.org/discussions/341

Using invidious doesn't "hide your IP from Google" anyway, as there are still requests to googlevideo.com, unless you use `&local=true` which not all Invidio instances support.

Users do have the options of using something like [yt2invidio](https://codeberg.org/izzy/userscripts/src/branch/master/yt2invidio.md)

2022-01-01 13:06 UTC, tommytran732 commented on collections/_evergreen/linux-desktop.html
> +<p>The user is also expected to have sufficient Linux knowledge to properly set up security for their system such as enabling a mandatory access control system, doing firewalling, setting up kernel m
I don't see how this does not make sense. This is stressing that Arch and Arch based distributions are not for new users. Arch is still highly recommended if you know what you are doing.

2022-01-01 13:07 UTC, tommytran732 commented on collections/_evergreen/linux-desktop.html
> +<p>In a system with transactional update, a snapshot is of the system is created before and after the update is applied. Should something go wrong during or after the update is applied, the user can
I am not committing this one because Transactional updates are different from Atomic updates

2022-01-01 13:10 UTC, tommytran732 commented on collections/_evergreen/linux-desktop.html
> +{% endfor %}
I think the current ordering makes more sense because the Tor Focused distributions are a lot different from the ones at the top

2022-01-01 13:12 UTC, tommytran732 commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +title: Whonix
Whonix is a 2 VM setup. The workstation VM has anonymity features like Kloak and whatnot. Whonix on Qubes is just the gateway to route traffic from other VMs. They are not comparable at all.

2022-01-01 13:13 UTC, tommytran732 commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
I agree with dngray here. I don't see how YouTube iframes are a problem at all.

2022-01-01 13:14 UTC, tommytran732 commented on collections/_evergreen/linux-desktop.html
> +    Atomic/Transactional update
This does not match the formatting of the rest of the page (and other pages too) because normally only the first character is capitalized.

2022-01-01 19:31 UTC, jonaharagon commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +title: Whonix
I'm not saying they are comparable, I am saying that I wouldn't recommend using Whonix outside of Qubes.

2022-01-01 19:33 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
🤔 You don't see how automatically connecting people to `youtube.com` is a problem? Privacy Guides does not make any third-party requests.

2022-01-01 19:34 UTC, jonaharagon commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
What we've done in the past is just hyperlink an image of the video thumbnail to invidious.

2022-01-01 20:32 UTC, ph00lt0 requested changes

2022-01-01 20:32 UTC, ph00lt0 commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Under GDPR are actually not allowed to do this, without permission of visitor because you place tracking cookies without consent.

2022-01-01 23:47 UTC, blacklight447 commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
I took a look at this and in my opinion, using a hyperlinked thumbnail is the best way forward.

We should aim to keep connections to thirdparty resources to a minimum.

2022-01-03 10:58 UTC, quantmint commented
I think that we should cite repology, considering that it can be used to rank distros by updated packages percentage. In particular when Fedora is claimed to be a very updated distro or in other places.
https://repology.org/repositories/statistics/pnewest
https://repology.org/repositories/graphs

2022-01-05 13:26 UTC, RandPotato commented on collections/_evergreen/linux-desktop.html
> +<p>The user is also expected to have sufficient Linux knowledge to properly set up security for their system such as enabling a mandatory access control system, doing firewalling, setting up kernel m
Maybe this can be merged with the Arch card, as it looks redundant to me

2022-01-19 11:45 UTC, Anish-M-code commented
@tommytran732 I think Qubes OS and Debian Unstable / sid could be a great addition to this list ( https://deploy-preview-491--privacyguides.netlify.app/linux-desktop/ ). I understand that Qubes OS is not a linux distribution but still it is highly secure by design and has features like disposable VMs which helps privacy.

2022-01-19 12:28 UTC, ph00lt0 commented
Is there a reason that QubesOS isn't listed in a card? I only see a mention of it under Whonix, while it has other purposes too.

2022-01-19 12:33 UTC, tommytran732 commented
> Is there a reason that QubesOS isn't listed in a card? I only see a mention of it under Whonix, while it has other purposes too.
> 
> Edit: i see @Anish-M-code already asked. Edit2: I was convinced QubesOS is based on Linux tho, are you sure it isn't @Anish-M-code?

Because its not Linux and it deserves its own page. My librem laptop should come soon and I would be able to use it. I will write a seperate page for it after a month or two.

2022-01-19 12:35 UTC, tommytran732 commented
> @tommytran732 I think Qubes OS and Debian Unstable / sid could be a great addition to this list ( https://deploy-preview-491--privacyguides.netlify.app/linux-desktop/ ). I understand that Qubes OS is not a linux distribution but still it is highly secure by design and has features like disposable VMs which helps privacy.

Qubes will have its own page. Debian sid isn't maintained by the Debian security team iirc and it still has a bunch of donstream patching.

2022-02-12 14:01 UTC, dngray commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +title: Whonix
> I am saying that I wouldn't recommend using Whonix outside of Qubes, which is an entirely different statement, because the security-model that you are inherently seeking by using Whonix cannot be met when using a less-secure host OS IMO.

"less-secure host OS", while that may be true it does depend on your threat model. Using Whonix via Virtualbox or KVM doesn't immediately mean you're wasting your time. It's worth noting the use of Qubes, requires a root disk to install the OS, which might not be too suitable if you've got things already set up, or are on Windows or a Mac.

2022-02-18 15:58 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
> What we've done in the past is just hyperlink an image of the video thumbnail to invidious.

There's no reason we couldn't do that actually.

2022-02-19 16:42 UTC, RandPotato commented
> GRSecurity is a set of kernel patches that substantially increase security in the Linux kernel. Unfortunately, it went **closed** in 2017. If you have access to the latest GRSecurity patches, it is highly recommended that you use them.

Do you mean by closed closed source/proprietary?
Maybe this could be written in a more clean form

2022-02-19 16:44 UTC, RandPotato commented
> On openSUSE, the user has a choice of AppArmor or SELinux during the installation process. We recommend sticking to the default for each variant (AppArmor for Tumbleweed and SELinux for MicroOS). openSUSE’s SELinux policies are derived from those from Fedora.

I see you removed MicroOS from recommendations, maybe just remove 

> SELinux for MicroOS

2022-02-19 16:58 UTC, Anish-M-code commented
> > GRSecurity is a set of kernel patches that substantially increase security in the Linux kernel. Unfortunately, it went **closed** in 2017. If you have access to the latest GRSecurity patches, it is highly recommended that you use them.
> 
> Do you mean by closed closed source/proprietary? Maybe this could be written in a more clean form

Grsecurity Patches are open source but it is not available for free to the public , it has to be purchased  and it seems Grsecurity hates customers who release their patches public because it is their hardwork but yes it shares source code patches with customers for private use within an organisation , so it is open source but closed in the sense it is not freely available for public / other open source community to use for unlimited distribution for public benefit. It seems the contributors might have meant this.

2022-02-20 20:58 UTC, tommytran732 commented
> > On openSUSE, the user has a choice of AppArmor or SELinux during the installation process. We recommend sticking to the default for each variant (AppArmor for Tumbleweed and SELinux for MicroOS). openSUSE’s SELinux policies are derived from those from Fedora.
> 
> I see you removed MicroOS from recommendations, maybe just remove
> 
> > SELinux for MicroOS

Eh well, we do give general recommendations even for distros that we don't recommend, so I think its fine

2022-02-21 06:36 UTC, Anish-M-code commented
@tommytran732 I dont know if this would be worthy addition to Linux Page but many people have misconception that full disk encryption will completely erase all data stored in disk and protect against Forensic recovery of data but it seems certain old data may be recovered and might help attackers determine how much and where on the partition data was written.

I think , we should advise people to fill devices with random data before full disk encryption.
Maybe using tools like Darik's Boot and Nuke before installing an OS and checking appropriate full disk encryption option in OS installer might help. Some Linux Distros like Debian Erase disk with Random data before full disk encryption while Fedora doesn't erase disk due to performance reasons.

References:-

https://unix.stackexchange.com/questions/64416/overwriting-disk-before-encryption
https://fedoraproject.org/wiki/Disk_Encryption_User_Guide#Limitations_of_Anaconda.27s_Block_Device_Encryption_Support
https://gitlab.com/cryptsetup/cryptsetup/-/wikis/FrequentlyAskedQuestions#5-security-aspects

2022-02-22 22:21 UTC, mfwmyfacewhen requested changes

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-immutable/1_fedora-silverblue.yml
> +  As an alternative to Flatpaks, there is the option of [Toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/) to create [Podman](https://podman.io) containers with a shared home
and mimic a traditional Fedora environment, this is a 

Replace the comma with a period and start a new sentence with "This".

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-immutable/2_nixos.yml
> +  NixOS also provides atomic updates: first it downloads (or builds) the packages and files for the new system generation and then switches to it. Switching to a new generation can be done in differe
NixOS also provides atomic updates: first it downloads

Replace the colon with a semicolon.

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-immutable/2_nixos.yml
> +  NixOS also provides atomic updates: first it downloads (or builds) the packages and files for the new system generation and then switches to it. Switching to a new generation can be done in differe
Same with the colon after ways

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-immutable/2_nixos.yml
> +  Nix the package manager uses a purely functional language - which is also called Nix - to define packages. Because of this [Nixpkgs](https://github.com/nixos/nixpkgs) (the main source of packages)
Replace the dashes with parentheses.

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-immutable/2_nixos.yml
> +  Nix is a source-based package manager - if there's no pre-built avalaible in the binary cache, Nix will just build the package from source using its definition. It builds each package in a sandboxe
Replace the dash after "manager" with a semicolon.

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +  **Whonix** is based on [Kicksecure](https://www.whonix.org/wiki/Kicksecure), security-focused fork of Debian. It aims to provide privacy, security and anonymity on the internet.
Whonix is based on [Kicksecure](https://www.whonix.org/wiki/Kicksecure), security-focused fork of Debian.

add an "a" after kicksecure

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +  Whonix is meant to run as two virtual machines, a "Workstation" and a Tor "Gateway". All communications from the Workstation has to go through the Tor gateway, and will be routed through the Tor Ne
Whonix is meant to run as two virtual machines, a "Workstation" and a Tor "Gateway".

Replace the comma with a colon.

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +  Some of its features include Tor Stream Isolation, [keystroke anonymization](https://www.whonix.org/wiki/Keystroke_Deanonymization#Kloak), [encrypted swap](https://github.com/Whonix/swap-file-creat
Add "and a" after "encrypted swap,"

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop-tor/2_tails.yml
> +  It can boot on almost any computer from a DVD, USB stick, or sdcard. It aims to preserve privacy and anonymity while circumventing censorship and leaving no trace of use on the computer.
Not sure about the "no trace of use," maybe say "no trace of itself" instead

2022-02-22 22:21 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop/1_fedora-workstation.yml
> +  Fedora generally adopts newer technologies before other distributions eg. [Wayland](https://wayland.freedesktop.org/), [PipeWire](https://pipewire.org), and soon, [FS-Verity](https://fedoraproject.
Fedora generally adopts newer technologies before other distributions eg. [Wayland](https://wayland.freedesktop.org/), [PipeWire](https://pipewire.org/), and soon, [FS-Verity](https://fedoraproject.org/wiki/Changes/FsVerityRPM).

Change "distributions eg." to "distributions, e.g., Wayland"

2022-02-22 22:46 UTC, mfwmyfacewhen requested changes

2022-02-22 22:46 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop/1_fedora-workstation.yml
> +  **Fedora Workstation** is our recommendation distribution for users new to Linux.
Change "recommendation" to "recommended"

2022-02-22 22:47 UTC, mfwmyfacewhen requested changes

2022-02-22 22:47 UTC, mfwmyfacewhen commented on _data/operating-systems/linux-desktop/2_opensuse-tumbleweed.yml
> +  **openSUSE Tumbleweed** stable [rolling release](https://en.wikipedia.org/wiki/Rolling_release) distribution.
add "is a" after Tumbleweed

2022-02-22 22:56 UTC, mfwmyfacewhen requested changes

2022-02-22 22:56 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +## Anonimity focused distributions
Change "Anonimity" to "Anonymity"

2022-02-23 04:27 UTC, mfwmyfacewhen requested changes

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Most container based solutions are not the ideal approach for app sandboxing, as they typically share the same kernel as the host for performance reasons. Vulnerabilities in the host's kernel could l
Change "leak" to "lead"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +If you are using Docker, it is highly recommended that you use the [gVisor](https://gvisor.dev) runtime which implements a pseudo kernel for each application container and limit their direct access t
Change "limit" to "limits"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Mandatory access control systems on Linux Desktop are largely ineffective policies/profiles, however, it is still worth it to keep them enabled.
Change ", however," to "; however,"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +On openSUSE, the user has a choice of AppArmor or SELinux during the installation process. We recommend sticking to the default for each variant (AppArmor for Tumbleweed and SELinux for MicroOS). ope
Remove "those from"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +For advanced users, you can make your own AppArmor profiles, SELinux policies, Bubblewrap profiles, Seccomp blacklist to have better confinement of applications. This is quite a tedious and complicat
add "and" before "seccomp"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +For advanced users, you can make your own AppArmor profiles, SELinux policies, Bubblewrap profiles, Seccomp blacklist to have better confinement of applications. This is quite a tedious and complicat
Change "detail of" to "detail about"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +## Additional Hardening
Change "Hardening" to be lower case for consistency, or change the other titles to be upper case

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +You should have an inbound Firewall to block connections to your computer at all times. Considering Red Hat's [documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/
Change "Considering" to "consider"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Fedora comes with Firewalld by default, however, their rules are very permissive by default. Consider closing port 1000-65535 with both TCP and UDP after the operating system installation. You should
Change ", however," to "; however,"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Consider following section [2.2](https://madaidans-insecurities.github.io/guides/linux-hardening.html#sysctl), [2.3](https://madaidans-insecurities.github.io/guides/linux-hardening.html#boot-paramete
Add a comma after 2.3

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Note that setting `kernel.unprivileged_userns_clone=0` will stop Flatpak, Podman, Docker, LXC containers from working. Do not set this flag if you are using those technologies.
Add "and" before LXC

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +SMT has been the cause of numerous hardware vulnerabilities, and subsequent patches for those vulnerabilities often come with performance penalties that negate most of the performance gain given by S
Change "disables" to "disable"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Certain distributions like Arch Linux comes with linux-hardended, a kernel package with hardening patches and more security concious defaults.
"hardended" should be "hardened"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Certain distributions like Arch Linux comes with linux-hardended, a kernel package with hardening patches and more security concious defaults.
change "security concious" to "security-conscious"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Linux-Hardened comes with `kernel.unprivileged_userns_clone=0` by default. If you are using Flatpak, Podman, Docker, LXC containers or other technologies that relies on unpriviledged user namespaces,
Add "or" before LXC

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +GRSecurity is a set of kernel patches that substantially increase security in the Linux kernel. Unfortunately, it went closed in 2017. If you have access to the latest GRSecurity patches, it is highl
Change "it went close in 2017" to "it effectively closed off in 2017"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Consider adding `nodev`, `noexec`, `nosuid` to mountpoints which do not need them. Typically, these could be applied to `/boot`, `/boot/efi`, `/home`, `/root`, `/var`.
add "and" before "nosuid"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Consider adding `nodev`, `noexec`, `nosuid` to mountpoints which do not need them. Typically, these could be applied to `/boot`, `/boot/efi`, `/home`, `/root`, `/var`.
add "and" before "/var"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +By default, UEFI secure boot on Linux distributions is rather ineffective. Besides the problems mentioned in Madaidan's guide as only the chainloader (shim), the boot loader (GRUB), and the kernel ar
Remove "as" and replace with a comma

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +A guide for converting a normal /boot partition into an encrypted one on Fedora Workstation (not Silverblue!) can be founded [here](https://mutschler.eu/linux/install-guides/fedora-btrfs-33/).
/boot should be `/boot`

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +A guide for converting a normal /boot partition into an encrypted one on Fedora Workstation (not Silverblue!) can be founded [here](https://mutschler.eu/linux/install-guides/fedora-btrfs-33/).
change "founded" to "found"

2022-02-23 04:27 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +After setting up Secure Boot, set a password on your firmware to prevent an adversary from just opening it and disabling Secure Boot.
Remove "just"

2022-02-23 07:16 UTC, dngray commented on _data/operating-systems/linux-desktop-immutable/1_fedora-silverblue.yml
> +  As an alternative to Flatpaks, there is the option of [Toolbox](https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/) to create [Podman](https://podman.io) containers with a shared home
I think which is a worthy substitute.

2022-02-23 09:12 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +It is often believed that [open source](https://en.wikipedia.org/wiki/Open-source_software) software is inherently secure because there is the expectation that verification occurs regularly. In reali
> Can add this link to "inherently secure" https://seirdy.one/2022/02/02/floss-security.html

Yes, it is a good quality piece of writing.

2022-02-23 09:45 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +Despite of these drawbacks, desktop GNU/Linux distributions are great if you want to
I think I made this a bit better by removing repetition "the lack of"

2022-02-23 20:56 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Despite of these drawbacks, desktop GNU/Linux distributions are great if you want to
agree

2022-02-26 13:50 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +It is often believed that [open source](https://en.wikipedia.org/wiki/Open-source_software) software is inherently secure because there is the expectation that verification occurs regularly. In reali
Do you like how that sentence sounds now @mfwmyfacewhen?

2022-02-26 14:29 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +An example of this example occured when Debian famously fell behind on Firefox-ESR updates for [2 months](https://tracker.debian.org/pkg/firefox-esr), in one of which their version (78) was deemed en
I'm actually going to remove that paragraph. The example doesn't really add anything, it will age and people will be "that was years ago".

2022-02-26 15:14 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +We don't believe holding packages back and applying a bunch of backports just does not work that well. [Richard Brown](https://rootco.de) has a great presentation about this:
I re-worded this sentence completely.

2022-02-26 23:02 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +An example of this example occured when Debian famously fell behind on Firefox-ESR updates for [2 months](https://tracker.debian.org/pkg/firefox-esr), in one of which their version (78) was deemed en
Sounds good to me

2022-02-27 03:56 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +It is often believed that [open source](https://en.wikipedia.org/wiki/Open-source_software) software is inherently secure because there is the expectation that verification occurs regularly. In reali
ah yes,  :)

2022-02-27 07:17 UTC, mfwmyfacewhen requested changes

2022-02-27 07:17 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +## Anonymity focused distributions
Change to "Anonymity-focused distributions"

2022-02-27 07:17 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +At the moment desktop GNU/Linux does have some areas that could be better improved when compared to their proprietary counterparts e.g:
Add comma after "moment"

2022-02-27 07:17 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +For frozen distributions package maintainers are expected to backport patches to fix vulnerabilities (Debian is one such [example](https://www.debian.org/security/faq#handling)) rather than bump the
Add comma after "For frozen distributions"

2022-02-27 07:19 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +At the moment desktop GNU/Linux does have some areas that could be better improved when compared to their proprietary counterparts e.g:
Add comma before e.g

2022-02-28 05:28 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<p>In a system with atomic update, and update is either applied fully or completely diregarded. An update cannot suddenly fail and be applied half way through. Typically, a system with atomic update
This has already been replaced.

2022-02-28 05:29 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<p>Overall, we believe that for desktop usage, it is better to use an up to date distribution with a rollback mechanism than holding onto an outdated "Frankenstein" distribution.</p>
Was applied.

2022-02-28 05:45 UTC, dngray commented on _data/operating-systems/linux-desktop-tor/1_whonix.yml
> +title: Whonix
Some other thoughts on this, using Qubes, while it does improve security there are situations where you may be unable to.

For example during testing I found that I could not install Qubes to a USB stick, and then use my USB ethernet dock at the same time. The reason for this is because I only have one USB controller and it keeps those separate https://forum.qubes-os.org/t/qubes-running-off-of-usb-how-to-add-usb-wifi-adapter/2431 so if I wanted to use Qubes on that laptop I'd have to pick one of these options:

- Use KVM/Virtualbox Whonix images on my Silverblue install
- Partition my single NVMe to allow dual boot with QubesOS
- Install QubesOS to sdxc card
- Use WiFi, and give up on using the usb-c dock.

2022-03-01 13:32 UTC, dngray commented
Currently using this GIF picture

![Let's try Fedora Silverblue — an immutable desktop OS! - Adam Šamalik  -hpV5l-gJnQ](https://user-images.githubusercontent.com/48640805/156177557-fcbc5090-fc78-48b4-aeeb-798f50a72d7f.gif)

But I really do want to replace this with an [animated](https://inkscape.org/learn/animation/) [SVG animation](https://en.wikipedia.org/wiki/SVG_animation).

2022-03-05 20:27 UTC, tommytran732 commented
> Currently using this GIF picture
> 
> ![Let's try Fedora Silverblue — an immutable desktop OS! - Adam Šamalik -hpV5l-gJnQ](https://user-images.githubusercontent.com/48640805/156177557-fcbc5090-fc78-48b4-aeeb-798f50a72d7f.gif)
> 
> But I really do want to replace this with an [animated](https://inkscape.org/learn/animation/) [SVG animation](https://en.wikipedia.org/wiki/SVG_animation).

It says orange but its actually yellow lol

2022-03-06 04:59 UTC, dngray commented
> It says orange but its actually yellow lol

It's a yellowy-orange, the plan is to replace that with an SVG afterwards, we might do that in a separate PR as I don't want to hold up merging this.

2022-03-06 05:22 UTC, dngray commented
> Along with your choice of a distribution, your choice of a desktop environment or window manager is integral to your Linux experience. However, there are a few things you should consider in regard to security and privacy.

> On Linux, the [Xorg](https://www.x.org/wiki/) display server is extremely problematic. It was never designed with access control in mind, and all Xorg windows can access all of the other Xorg windows. Effectively, this allows any app to keylog and record the user's screen without any permission.

> Nested X11 solutions like Xpra and Xephr can sandbox Xorg windows, but they come with a great performance cost and a lot of inconveniences.

> [Wayland](https://wayland.freedesktop.org/) solves this problem by isolating each window and requring apps to request permission for screen recording. Thus, we recommend using desktop environments/window managers that works with Wayland. As of now, the list of desktop environments/window managers that support Wayland includes [GNOME](https://www.gnome.org), [KDE](https://kde.org), and [Sway](https://swaywm.org).

I think I'm going to trim this significantly and not mention too much about X11 other than that it is less secure. This is **not** a disputed fact. It's not really maintained anymore: [Red Hat Expecting X.Org To "Go Into Hard Maintenance Mode Fairly Quickly (June 2019)"](https://www.phoronix.com/scan.php?page=news_item&px=X.Org-Maintenance-Mode-Quickly). Most of the devs that actually work on X11 are from Redhat.

We would never recommend nested approaches, (afaik no distribution is configured like that).

Progressively Wayland will be all that is available, now that the [NVIDIA proprietary driver supports GBM](https://9to5linux.com/nvidia-495-44-graphics-driver-adds-gbm-support-indicator-for-resizable-bar-support) and that [works with Sway](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-GBM-Works-With-Sway).

It's also looking like XFCE 4.18 will have [wayland support](https://wiki.xfce.org/releng/4.18/roadmap). Although it may take time even [Qubes OS](https://github.com/QubesOS/qubes-issues/issues/3366) will likely get there. Likely this will happen well after XFCE has support (their default DE, and they are usually based on a previous Fedora release.

2022-03-06 20:01 UTC, tommytran732 commented
Well a few things as discussed on Matrix:
1. There are still people sticking to DEs such as Cinnamon (on Linux Mint) which is still stuck on X11 and we should let them know how horrible it is. A lot of people say "okay its less secure but why?". It's also a good way to tell people to use Sway over I3 for example.
2. We will never recommend nested X11. That said, tools like Firejail still uses it, so its worth mention
3. Sure, we don't need to wait for the GIF. Getting the job done is more important.

2022-03-11 17:35 UTC, rusty-snake commented on collections/_evergreen/linux-desktop.md
> +Consider following section [14](https://madaidans-insecurities.github.io/guides/linux-hardening.html#pam) on [Madaidan's hardening guide](https://madaidans-insecurities.github.io/guides/linux-hardeni
For Fedora Linux you can

```
sudo authselect select <profile_id, default: sssd> with-faillock without-nullok with-pamaccess
```

2022-03-11 17:35 UTC, rusty-snake commented on collections/_evergreen/linux-desktop.md
> +Consider following the [Arch Wiki](https://wiki.archlinux.org/title/USBGuard) to set up USBGuard.
worth linking usbauth?
https://github.com/kochstefan/usbauth-all

2022-03-11 17:35 UTC, rusty-snake commented on collections/_evergreen/linux-desktop.md
> +The problem with Flatpak's lax high level permissions could be mitigated by using an application called [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal). Consider revoking the
> revoking its access to the X11 socket

and the ipc namespace which is only used for X11 features.

> Some sample overrides can be founded

Some more if you want: https://github.com/rusty-snake/kyst/tree/main/flatpak

2022-03-20 02:02 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
@ph00lt0 about what you mentioned https://github.com/privacyguides/privacyguides.org/pull/491#discussion_r777136398

What if we did something like https://stackoverflow.com/a/61630345 instead. The poster says that is GDPR compliant.

2022-03-20 02:32 UTC, mfwmyfacewhen requested changes

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +A transactional update system, creates a snapshot that is made before and after an update is applied. If an update fails part of the way through (perhaps because of a power failure), rolling the upda
remove comma after system

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +For fast-moving distributions like the [immutable desktop OS, Silverblue](https://www.youtube.com/watch?v=-hpV5l-gJnQ), Tumbleweed and NixOS reliability can be achieved with this model.
add oxford comma

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +There is often some confusion about "security-focused" distributions and "pentesting" distributions. A quick search for "the most secure Linux distribution" will often give results like Kali Linux, B
remove comma after distributions

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +For a secure system, the user is also expected to have sufficient Linux knowledge to properly set up security for their system such as adopting a [mandatory access control](https://en.wikipedia.org/w
add oxford comma

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Fedora based distributions [use ZRAM](https://fedoraproject.org/wiki/Changes/SwapOnZRAM), by default.
remove comma after ZRAM

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Fortunately common environments such as [GNOME](https://www.gnome.org), [KDE](https://kde.org) and the window manager [Sway](https://swaywm.org) have support for Wayland. Some distributions like Fedo
add comma after Fortunately

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Fortunately common environments such as [GNOME](https://www.gnome.org), [KDE](https://kde.org) and the window manager [Sway](https://swaywm.org) have support for Wayland. Some distributions like Fedo
add oxford comma

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +We recommend **against** using desktop environments or window managers that do not have Wayland support such as Cinnamon (default on Linux Mint), Pantheon (default on Elemetary OS) MATE, XFCE and i3.
add oxford comma

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Linux distributions such as those which are [Linux-libre](https://en.wikipedia.org/wiki/Linux-libre) or DIY (Archlinux), don't come with the proprietary [microcode](https://en.wikipedia.org/wiki/Micr
remove comma after DIY (Archlinux)

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Linux distributions such as those which are [Linux-libre](https://en.wikipedia.org/wiki/Linux-libre) or DIY (Archlinux), don't come with the proprietary [microcode](https://en.wikipedia.org/wiki/Micr
add oxford comma

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +openSUSE also uses a [unique ID](https://en.opensuse.org/openSUSE:Statistics) to count systems, and that can be disabled by deleting the `/var/lib/zypp/AnonymousUniqueId` file.
change "and that can be disabled" to "which can be disabled" and remove the comma

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +[Flatpak](https://flatpak.org) aims to be a universal package manager for Linux. One of it's main goals is to provide a universal package format which can be used in most Linux distributions. It prov
change it's to its

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Users can restrict applications further by issuing [flatpak overrides](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override) and this can be done with the commandline or
remove "and" and make the first sentence two separate sentences.

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Users can restrict applications further by issuing [flatpak overrides](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override) and this can be done with the commandline or
change "founded" to "found"

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +* `org.freedesktop.secrets` dbus (access to secrets stored on your keychain) for applications which do not need it.
remove the period here for consistency

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Hard-coded access to some kernel interfaces like [`/sys`](https://en.wikipedia.org/wiki/Sysfs) and [`/proc`](https://en.wikipedia.org/wiki/Procfs#Linux) and a weak [seccomp](https://en.wikipedia.org/
change "and a weak" to "and weak"

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +[Firejail](https://firejail.wordpress.com/) is another method of sandboxing. As it is a large [setuid](https://en.wikipedia.org/wiki/Setuid) binary it has a large [attack surface](https://en.wikipedi
add comma after binary

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +The main risk is that Firejail may make the system safer from processes confined by it, but make it also less safe from processes running outside of Firejail. We don't recommend the use of Firejail,
probably remove the and in the second sentence here and make it two sentences

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +[Docker](https://en.wikipedia.org/wiki/Docker_(software)) is the most popular container solution out there, however, it is not a proper sandbox due to the large kernel attack surface it exposes and i
change , however, to ; however,

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +[Docker](https://en.wikipedia.org/wiki/Docker_(software)) is the most popular container solution out there, however, it is not a proper sandbox due to the large kernel attack surface it exposes and i
this whole sentence is kind of clunky, how about "Docker is the most popular container solution out there; however, it is not a proper sandbox since it exposes a large kernel attack surface and runs a big daemon as root. If the daemon crashes, it will result in all of your containers crashing at the same time."

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +Redhat develops [Podman](https://docs.podman.io/en/latest/) and secures it with SELinux to [isolate](https://www.redhat.com/sysadmin/apparmor-selinux-isolation) containers from eachother. One of the
change "eachother" to "each other"

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +We would generally recommend that you only block incoming connections only, unless you're using an application firewall such as [OpenSnitch](https://github.com/evilsocket/opensnitch) or [Portmaster](
remove one of the only's

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +If you use Fedora consider removing the whitelist for for [smb](https://en.wikipedia.org/wiki/Server_Message_Block)-client and [mdns](https://en.wikipedia.org/wiki/Multicast_DNS) services if you do n
add comma after "Fedora"

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +All these firewalls use the [Netfilter](https://en.wikipedia.org/wiki/Netfilter) framework and therefore cannot protect against malicious programs running on the system. A malicious program could ins
change "o wn" to "own"

2022-03-20 02:32 UTC, mfwmyfacewhen commented on collections/_evergreen/linux-desktop.md
> +All these firewalls use the [Netfilter](https://en.wikipedia.org/wiki/Netfilter) framework and therefore cannot protect against malicious programs running on the system. A malicious program could ins
change "it's" to "its"

2022-03-20 02:32 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
if we're not happy with the no-cookie solution, maybe we could self host a player and use the data API: https://stackoverflow.com/a/24637811

> If you really want to get around all these methods and include video without any sort of iframe, then your best bet might be creating an HTML5 video player/app that can connect to the Youtube Data API (https://developers.google.com/youtube/v3/)

@jonaharagon this would mean the only connection would be to googlevideo.com which is what invidious does basically.

2022-03-20 03:12 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +[Docker](https://en.wikipedia.org/wiki/Docker_(software)) is the most popular container solution out there, however, it is not a proper sandbox due to the large kernel attack surface it exposes and i
I think i've fixed this one.

2022-03-20 03:38 UTC, dngray commented
Going to remove mention of grsecurity, it's not free, you need a subscription. I'm not really sure that it is relevant [these days](https://news.ycombinator.com/item?id=14633163).

2022-03-20 04:19 UTC, dngray commented
> > On systems where [pam_faillock](https://access.redhat.com/solutions/62949) is not available, consider using [pam_tally2](https://access.redhat.com/solutions/37687) instead.

Both of those are subscriber links so I'll try find alternatives.

2022-03-20 04:31 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +The problem with Flatpak's lax high level permissions could be mitigated by using an application called [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal). Consider revoking the
Done.

2022-03-20 04:56 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +## Additional Hardening
done, might also change this on the android page too.

2022-03-20 04:58 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +Consider following section [14](https://madaidans-insecurities.github.io/guides/linux-hardening.html#pam) on [Madaidan's hardening guide](https://madaidans-insecurities.github.io/guides/linux-hardeni
Done.

2022-03-20 05:03 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<p><a href="https://blog.samalik.com/">Adam Samalik</a> has a great demonstration of how rpm-ostree and atomic updates work:</p>
I changed this to his twitter handle, because that better describes who he is.

2022-03-20 05:09 UTC, dngray commented on collections/_evergreen/linux-desktop.md
> +Consider following the [Arch Wiki](https://wiki.archlinux.org/title/USBGuard) to set up USBGuard.
I think USBGuard might be better maintained?

2022-03-20 05:49 UTC, dngray commented
> If you are using openSUSE, your `/boot` partition should be encrypted by default should you enable drive encryption.

I'm not sure this is the case. https://en.opensuse.org/SDB:Encrypted_root_file_system

I have [completed encrypted boot on Archlinux](https://wiki.archlinux.org/title/GRUB#Encrypted_/boot) with GRUB, and let me tell you that it's not a pleasant experience. Your boot time will go to minutes. It also only supports LUKS1.

2022-03-20 05:49 UTC, dngray commented
> A guide for converting a normal `/boot` partition into an encrypted one on Fedora Workstation (not Silverblue!) can be found [here](https://mutschler.eu/linux/install-guides/fedora-btrfs-33/).

The other reason I'm reluctant to mention this is, that seems to be for Fedora 33, and this is going to become dated.

2022-03-20 07:17 UTC, dngray commented on collections/_evergreen/linux-desktop.html
> +<iframe width="731" height="411" src="https://www.youtube.com/embed/i8c0mg_mS7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyrosco
Hmm seems using the iframe is the preferred way https://stackoverflow.com/questions/12549252/should-i-use-object-or-iframe-for-loading-a-video

2022-03-20 11:24 UTC, rusty-snake commented on collections/_evergreen/linux-desktop.md
> +Consider following the [Arch Wiki](https://wiki.archlinux.org/title/USBGuard) to set up USBGuard.
Likely it is. However usbauth has finer control capabilities (unless usbguard has followed in the meantime) https://github.com/kochstefan/usbauth-all/issues/2.

2022-03-20 11:51 UTC, dngray commented
> @tommytran732 @dngray I dont know if this would be worthy addition to Linux Page but many people have misconception that full disk encryption will completely erase all data stored in disk and protect against Forensic recovery of data but it seems certain old data may be recovered and might help attackers determine how much and where on the partition data was written.

We should mention there that users should not use DBAN on SSDs or NVMe disks, and this should only be for magnetic hard drivies. For SSDs/NVMes Secure ATA command should be issued.

2022-03-20 14:30 UTC, merged