Adding Play Protect
privacyguides/privacyguides.org pull request #680
Opened 2022-03-07 03:18 UTC by tommytran732

Adding this to the Android page for now, as it does affect stock Android. When we discuss ChromeOS/ChromeOS Flex, or other Google products, we could consider making a page dedicated to recommendations with the Google Account and linking to that page instead.

2022-03-07 11:20 UTC, mfwmyfacewhen requested changes

2022-03-07 11:20 UTC, mfwmyfacewhen commented on collections/_evergreen/android.md
>  Evaluate whether the additional features in the F-Droid build is worth the slower updates or whether faster updates from the Google Play is worth the potential privacy issues in your [threat model](/
Maybe split this up into two sentences, like "Evaluate whether the additional features in the F-Droid build are worth the slower updates. Also think about whether faster updates from the Google Play Store are worth the potential privacy isues in your threat model."

2022-03-07 11:20 UTC, mfwmyfacewhen commented on collections/_evergreen/android.md
> +* Enforcing that U2F be used for two factor authentication. SMS, TOTP, and OATH are not allowed.
Either remove the periods at the end of each bullet point or add them for consistency

2022-03-07 15:30 UTC, ph00lt0 commented on collections/_evergreen/android.md
> +* Mandatory automatic device scanning with [Play Protect](https://support.google.com/googleplay/answer/2812853?hl=en#zippy=%2Chow-malware-protection-works%2Chow-privacy-alerts-work)
Although I like the advanced protection program, I really wouldn't encourage users who want privacy to enable this. That seems counter productive. 
Google will receive:
 - Your device's network connections 
 - Potentially harmful URLs 
 - Operating system, and apps installed on your device through Google Play or other sources.

2022-03-07 16:31 UTC, tommytran732 commented on collections/_evergreen/android.md
> +* Mandatory automatic device scanning with [Play Protect](https://support.google.com/googleplay/answer/2812853?hl=en#zippy=%2Chow-malware-protection-works%2Chow-privacy-alerts-work)
Doesn't matter, as Google already have all of that if you are using privileged Play Services. You do not get to choose whether to install the Play Services or not, the OS vendor does it for you.

If you are not using the privileged play service, Google cannot block app install or auto remove malicious apps, because it doesn't have the permission to do so.

2022-03-07 17:05 UTC, ph00lt0 commented on collections/_evergreen/android.md
> +* Mandatory automatic device scanning with [Play Protect](https://support.google.com/googleplay/answer/2812853?hl=en#zippy=%2Chow-malware-protection-works%2Chow-privacy-alerts-work)
Okay i see where your coming from. I agree using a different OS would be a much better idea, but saying that it doesn't make a difference is not true AFAIK.

It seems your implying that scanning isn't disabled when the users does disable play protect? I know it's enabled by default (at least it always was) but when the user disables the scanning from what I understand it stops the framework from reporting installed applications. The applications you use are often quite a unique pattern to identify users, as network activity can be as well.

Security wise I would fully agree with you, privacy however I am not sure if this is the best advice.

2022-03-07 17:11 UTC, tommytran732 commented on collections/_evergreen/android.md
> +* Mandatory automatic device scanning with [Play Protect](https://support.google.com/googleplay/answer/2812853?hl=en#zippy=%2Chow-malware-protection-works%2Chow-privacy-alerts-work)
> Okay i see where you're coming from. I agree using a different OS would be a much better idea, but saying that it doesn't make a difference is not true AFAIK.
> 
> It seems your implying that scanning isn't disabled when the users does disable play protect? I know it's enabled by default (at least it always was) but when the user disables the scanning from what I understand it stops the framework from reporting installed applications. The applications you use are often quite a unique pattern to identify users, as network activity can be as well.
> 
> Security wise I would fully agree with you, privacy however I am not sure if this is the best advice.

An app can check what other apps you have installed, privileged or not. In fact, yes, even with Play Protect off, Google still scans your installed app anyways. How do you think it does app updates? It has to know what you have installed, what version you have installed, then compare it to the latest version of those apps and pull the latest updates.

2022-03-07 17:20 UTC, ph00lt0 commented on collections/_evergreen/android.md
> +* Mandatory automatic device scanning with [Play Protect](https://support.google.com/googleplay/answer/2812853?hl=en#zippy=%2Chow-malware-protection-works%2Chow-privacy-alerts-work)
@tommytran732 you are probably right, didn't really think of that. Was hoping the data wouldn't be used in that way. Same goes for safe browsing, that also is a complex recommendation if your asking me.

2022-03-07 17:46 UTC, tommytran732 commented on collections/_evergreen/android.md
> +* Mandatory automatic device scanning with [Play Protect](https://support.google.com/googleplay/answer/2812853?hl=en#zippy=%2Chow-malware-protection-works%2Chow-privacy-alerts-work)
> @tommytran732 you are probably right, didn't really think of that. Was hoping the data wouldn't be used in that way. Same goes for safe browsing, that also is a complex recommendation if your asking me.

Safe Browsing is more nuanced than Play Services scanning.

In Chrome and various other forks, the data is sent directly through Google. Its not so great, but if you are using it anyways, you might as well want it to be aggressive like on the advanced protection program. If you don't want it, use a browser that lets you disable it (and iirc it can be disabled in Chrome as well).

If you are using Brave, then they proxy the requests through their server before sending it to Google. This is bette, but not idea.

With Firefox + additional configuration, you can make it do Safe Browsing checks locally only, which would be the best implementation of it.

2022-03-08 05:18 UTC, mfwmyfacewhen requested changes

2022-03-08 05:18 UTC, mfwmyfacewhen commented on collections/_evergreen/android.md
> +* Stricter two factor authentication; e.g. that [U2F](https://en.wikipedia.org/wiki/Universal_2nd_Factor) **must** be used and disallows the use of [SMS OTPs](https://en.wikipedia.org/wiki/One-time_p
add "and" before 0Auth

2022-03-08 05:20 UTC, dngray commented on collections/_evergreen/android.md
>  Evaluate whether the additional features in the F-Droid build is worth the slower updates or whether faster updates from the Google Play is worth the potential privacy issues in your [threat model](/
Agreed, I think that does sound a bit better.

2022-03-08 05:21 UTC, dngray commented on collections/_evergreen/android.md
> +* Enforcing that U2F be used for two factor authentication. SMS, TOTP, and OATH are not allowed.
Done.

2022-03-08 05:24 UTC, dngray commented on collections/_evergreen/android.md
> +* Stricter two factor authentication; e.g. that [U2F](https://en.wikipedia.org/wiki/Universal_2nd_Factor) **must** be used and disallows the use of [SMS OTPs](https://en.wikipedia.org/wiki/One-time_p
Done.

2022-03-08 05:36 UTC, merged