Add GrapheneOS's app store
privacyguides/privacyguides.org pull request #681
Opened 2022-03-07 04:04 UTC by tommytran732

2022-03-07 11:12 UTC, mfwmyfacewhen requested changes

2022-03-07 15:48 UTC, ph00lt0 commented
Not sure what the value is of this listening as it comes preinstalled with the OS?
We also don't recommend the inbuilt calculator app

2022-03-07 15:52 UTC, ph00lt0 commented on collections/_evergreen/android.md
>  F-Droid is often recommended as an alternative to Google Play, particularly in the privacy community. The option to add third party repositories and not be confined to Google's [walled garden](https:
You recommend to install it though the GoS app, but GrapheneOS actually blocks you from installing it through Google Play Store now see: https://grapheneos.org/releases#2022022818
"Sandboxed Google Play compatibility layer: prevent Play Store from trying to update Auditor, PDF Viewer, Google Services Framework, Google Play services and the Play Store since we'll be updating these via our own app repository client (we'll be regularly updating the mirror of Google Play in our repository once the staged rollouts reach our test devices and it passes basic testing)"

2022-03-07 15:56 UTC, ph00lt0 commented
@tommytran732 it may actually be a good idea to list the GoS camera app (also available for none GoS) users. This app strips meta data of pictures by default. I think that would be worth listing.

2022-03-07 16:28 UTC, tommytran732 commented
> Not sure what the value is of this listening as it comes preinstalled with the OS? We also don't recommend the inbuilt calculator app

The recommendation is for non-GOS OSes.

2022-03-08 00:05 UTC, tommytran732 commented on collections/_evergreen/android.md
>  F-Droid is often recommended as an alternative to Google Play, particularly in the privacy community. The option to add third party repositories and not be confined to Google's [walled garden](https:
> You recommend to install it though the GoS app, but GrapheneOS actually blocks you from installing it through Google Play Store now see: https://grapheneos.org/releases#2022022818 "Sandboxed Google Play compatibility layer: prevent Play Store from trying to update Auditor, PDF Viewer, Google Services Framework, Google Play services and the Play Store since we'll be updating these via our own app repository client (we'll be regularly updating the mirror of Google Play in our repository once the staged rollouts reach our test devices and it passes basic testing)"

Irrelevant, that is the Sandboxed Play Services on the OS doing it, not the appstore doing it.

2022-03-08 05:41 UTC, dngray commented on collections/_evergreen/android.md
> +GrapheneOS's app store is available on [GitHub](https://github.com/GrapheneOS/platform_external_Apps/tree/12/prebuilt). It supports Android 12 and above and is capable of self update. The app store s
Done.

2022-03-08 05:43 UTC, dngray commented on collections/_evergreen/android.md
>  F-Droid is often recommended as an alternative to Google Play, particularly in the privacy community. The option to add third party repositories and not be confined to Google's [walled garden](https:
I think these things are resolved now.

2022-03-08 06:42 UTC, merged