Revamping the Encrypted DNS page (#575)
privacyguides/privacyguides.org pull request #767
Opened 2022-03-22 07:50 UTC by dngray

## Revamping the DNS page to fix several issues that were discussed with the community.

This is a continuation of https://github.com/privacyguides/privacyguides.org/pull/575 which was a WIP.

## Resolves: Issues considered solved as per my knowledge:
- #572    
- #561  
- #543    
- #321 
 
## Recommendations considered:
- #556 
- #593 
- #197 
- #567 
- #241 
- #252 
- #111 

## Changes made:
- Added [when to use dns](https://github.com/dngray/encrypted-dns/blob/main/dns.svg) image by @dngray 
- Removed UncensoredDNS
- Added MullvadDNS
- Removed columns for Qname minimization and DNSSEC
- Added column for ECS
- Removed the warning of Android DNS being ineffective when using VPN
- Added definitions of Qname Minimization, DNSSEC and ECS
- Replaced Nebulo by a better project [RethinkDNS](https://rethinkdns.com/)
- Removed third party clients and suggest using native implementations instead

## Effected page: 
https://privacyguides.org/providers/dns/

2022-03-29 10:52 UTC, elitejake requested changes

2022-03-29 10:52 UTC, elitejake commented on collections/_evergreen/dns.md
> +Windows users can [turn on DoH](https://docs.microsoft.com/en-us/windows-server/networking/dns/doh-client-support), by accessing Windows settings in control panel.
Only Windows 11 and Windows Server 2022 have this feature.

2022-03-29 10:52 UTC, elitejake commented on collections/_evergreen/dns.md
> +[**DNSCrypt**](https://en.wikipedia.org/wiki/DNSCrypt) is one of the first methods of encrypting DNS queries. The [protocol](https://en.wikipedia.org/wiki/DNSCrypt#Protocol) operated on [port 443](ht
Changing `protocol` link to https://dnscrypt.info/protocol might be better.

2022-03-29 10:52 UTC, elitejake commented on collections/_evergreen/dns.md
> +   <pre class=terminal>openssl x509 -noout -ocsp_uri -in /tmp/pg_server.cert'</pre>
Trailing `'`

2022-03-29 10:52 UTC, elitejake commented on collections/_evergreen/dns.md
> +</picture>
Thoughts on aligning the flowchart to center?

2022-03-29 10:52 UTC, elitejake commented on collections/_evergreen/dns.md
> +`systemd-resolved` doesn't yet support [#8639](https://github.com/systemd/systemd/issues/8639), which many Linux distributions use to do their DNS lookups. This means you need to install a proxy like
Raw issue number (`#8639`) seems out of place here.

2022-03-29 10:52 UTC, elitejake commented on collections/_evergreen/dns.md
> +
"What is DNSSEC" is not properly addressed.

2022-03-29 10:52 UTC, elitejake commented on collections/_evergreen/dns.md
> +First, a QName is a "qualified name", simply put that would be `privacyguides.org`. QNAME minimisation reduces the amount of information sent from the DNS server to the [authoritive name server](http
`QName` should be in all caps.

2022-03-29 11:15 UTC, dngray commented on collections/_evergreen/dns.md
> +Windows users can [turn on DoH](https://docs.microsoft.com/en-us/windows-server/networking/dns/doh-client-support), by accessing Windows settings in control panel.
I don't think that's true https://www.bleepingcomputer.com/news/microsoft/how-to-enable-dns-over-https-doh-in-windows-10/

2022-03-29 11:16 UTC, dngray commented on collections/_evergreen/dns.md
> +[**DNS over TLS (DoT)**](https://en.wikipedia.org/wiki/DNS_over_TLS) is another method for encrypting DNS communication that was defined in [RFC 7868](https://datatracker.ietf.org/doc/html/rfc7858).
oops :+1:

2022-03-29 11:17 UTC, dngray commented on collections/_evergreen/dns.md
> +   <pre class=terminal>openssl x509 -noout -ocsp_uri -in /tmp/pg_server.cert'</pre>
:+1: well spotted, That must have been left over from the Liquid command.

2022-03-29 11:20 UTC, dngray commented on collections/_evergreen/dns.md
> +[**DNSCrypt**](https://en.wikipedia.org/wiki/DNSCrypt) is one of the first methods of encrypting DNS queries. The [protocol](https://en.wikipedia.org/wiki/DNSCrypt#Protocol) operated on [port 443](ht
I thought about that when I wrote it, but I thought the Wikipedia article provided a nicer "high level" description of it. What do you think?

2022-03-29 11:24 UTC, dngray commented on collections/_evergreen/dns.md
> +</picture>
Hmm, for some reason it isn't aligning in the center like the stylesheet says https://github.com/privacyguides/privacyguides.org/pull/767/files#diff-e32d4b74560376b05bc667c6f98ba7effc5544a0a66c04d40c635e19bba9b0f1 and https://github.com/privacyguides/privacyguides.org/pull/767/files#diff-c7e5a8e2025ed423df57a3efbc8f969f2a12d4a333721392bd8211ed369c19ee

2022-03-29 11:37 UTC, elitejake commented on collections/_evergreen/dns.md
> +Windows users can [turn on DoH](https://docs.microsoft.com/en-us/windows-server/networking/dns/doh-client-support), by accessing Windows settings in control panel.
> First and foremost, make sure that you are in the Dev Channel of the Windows Insider program and you've upgraded to Build 19628 or higher.
Oops, I missed that.

BTW, is it only available on Ethernet?

2022-03-29 11:45 UTC, dngray commented on collections/_evergreen/dns.md
> +Windows users can [turn on DoH](https://docs.microsoft.com/en-us/windows-server/networking/dns/doh-client-support), by accessing Windows settings in control panel.
No, works on WiFi too:

> For example, if you're connected to a public WiFi, you can use DoH....

2022-03-29 11:46 UTC, dngray commented on collections/_evergreen/dns.md
> +
What do you think about my changes?

2022-03-29 12:13 UTC, elitejake commented on collections/_evergreen/dns.md
> +[**DNSCrypt**](https://en.wikipedia.org/wiki/DNSCrypt) is one of the first methods of encrypting DNS queries. The [protocol](https://en.wikipedia.org/wiki/DNSCrypt#Protocol) operated on [port 443](ht
I agree with you on that. But DoT and DoH have their spec linked.

2022-03-29 17:42 UTC, elitejake commented on collections/_evergreen/dns.md
> +
All good.

2022-03-30 14:47 UTC, dngray commented on collections/_evergreen/dns.md
> +</picture>
I'm kind of [hoping we go with mkdocs-material](https://github.com/privacyguides/privacyguides.org/issues/802)..

Instead of including the SVG we might use the [diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/) support provided by [mermaid.js](https://mermaid-js.github.io/mermaid/#/flowchart)

2022-03-31 06:17 UTC, elitejake commented on collections/_evergreen/dns.md
> +</picture>
Should we wait until all the current PRs are merged before revamping the whole website?

2022-03-31 07:32 UTC, merged