Add iOS Page
privacyguides/privacyguides.org pull request #770
Opened 2022-03-22 12:32 UTC by dngray

Superseeds https://github.com/privacyguides/privacyguides.org/pull/766

Preview https://privacyguides-privacyguides-org-preview-pr-770.surge.sh/

2022-05-21 15:08 UTC, EdwardLangdon requested changes

2022-05-21 15:08 UTC, EdwardLangdon commented on docs/ios/overview.md
>  If you want to make use of Apple's digital assistan, be aware that Siri collects speech data, [^1] although Apple claims that only minimal data is sent.
```suggestion
If you want to make use of Apple's digital assistant, be aware that Siri collects speech data, [^1] although Apple claims that only minimal data is sent.
```

2022-05-21 15:13 UTC, EdwardLangdon commented on docs/ios/overview.md
> +If you want to make use of Apple's digital assistan, be aware that Siri collects speech data,[^1] although Apple claims that only minimal data is sent.
```suggestion
If you want to make use of Apple's digital assistan, be aware that Siri collects speech data ,[^1] although Apple claims that only minimal data is sent and as of iOS 15, Siri uses Machine Learning and totally uses Voice Data on Device to process things.
```

2022-05-21 15:15 UTC, EdwardLangdon commented on docs/ios/overview.md
> +If you want to make use of Apple's digital assistan, be aware that Siri collects speech data,[^1] although Apple claims that only minimal data is sent.
As it is totally On-Device, I think you should phrase it as, iOS sends data back to apple only when you opt-in for analytics or Speech Improvement services.

2022-05-21 15:21 UTC, EdwardLangdon requested changes

2022-05-21 15:21 UTC, EdwardLangdon commented on docs/ios/overview.md
> +If you want to make use of Apple's digital assistan, be aware that Siri collects speech data,[^1] although Apple claims that only minimal data is sent.
```suggestion
If you want to make use of Apple's digital assistant, be sure to make it only activate after the Device is unlocked to prevent unauthorized access via Utlrasonic Hacking techniques.

As of iOS 15, iOS uses Machine Learning & On-Device Proccessing to deliver things and your Vocie data never leaves your device. Unless you opt-in(or Opt-out **Not sure**) for Analytics or Speech Improvement services.
```

2022-05-21 15:21 UTC, EdwardLangdon commented on docs/ios/overview.md
> +[^1]: [Ask Siri, Dictation & Privacy](https://www.apple.com/legal/privacy/data/en/ask-siri-dictation/)
```suggestion

```

2022-07-01 23:00 UTC, mfwmyfacewhen commented on docs/ios/overview.en.md
> +### SIM PIN
Yeah true

2022-08-19 11:08 UTC, purtual requested changes

2022-08-19 11:08 UTC, purtual commented on docs/ios/overview.en.md
> +Enabling **Airplane Mode** will allow you to stop your phone from contacting cell towers. Obviously, you won't be able to use cellular data while it is enabled. You will still be able to connect to w
```suggestion
Enabling **Airplane Mode** will allow you to stop your phone from contacting cell towers. Obviously, you won't be able to use cellular data while it is enabled. You will still be able to connect to Wi-Fi and Bluetooth, so whenever you are connected to Wi-Fi you can turn this setting on.
```

2022-08-19 11:08 UTC, purtual commented on docs/ios/overview.en.md
> +It is important to install **Software Updates** frequently to get the latest security fixes. You can enable **Automatic Updates** to keep you phone up-to-date without needing to constantly check for
```suggestion
It is important to install **Software Updates** frequently to get the latest security fixes. You can enable **Automatic Updates** to keep your phone up-to-date without needing to constantly check for updates.
```

2022-08-19 11:08 UTC, purtual commented on docs/ios/overview.en.md
> +**AirPlay** lets you seemlessly stream content from your iPhone to a TV; however, you might not always want this.
```suggestion
**AirPlay** lets you seamlessly stream content from your iPhone to a TV; however, you might not always want this.
```

2022-08-19 11:08 UTC, purtual commented on docs/ios/overview.en.md
> +Setting a strong password on your phone is probably the most important step you can take for security and privacy. You'll have to make tradeoffs here between security and convenience; a longer passwo
```suggestion
Setting a strong password on your phone is probably the most important step you can take for security and privacy. You'll have to make tradeoffs here between security and convenience; a longer password will be annoying to type in every time, but a shorter password or pin will be easier to guess. Setting up Touch ID or Face ID along with a strong password can be a good compromise between usability and security.
```

2022-08-19 11:08 UTC, purtual commented on docs/ios/overview.en.md
> +Set a password that you won't forget. The longer the better. It might be easier for you to string a few words together and break them up with numbers and symbols.
```suggestion
Set a password that you won't forget. The longer, the better. It might be easier for you to string a few words together and break them up with numbers and symbols.
```

2022-08-19 11:08 UTC, purtual commented on docs/ios/overview.en.md
> +Do note that Private Browsing does not save cookies and website data, so it won't be possible to remain signed into sites. This may be an inconvenience.
```suggestion
Do note that Private Browsing does not save cookies and website data, so it won't be possible to remain signed in to sites. This may be an inconvenience.
```

2022-08-19 11:08 UTC, purtual commented on docs/ios/overview.en.md
> +Normal phone calls made with the Phone app are not e2ee. For e2ee audio and video calls, you can use Facetime or another app like Signal.
```suggestion
Normal phone calls made with the Phone app are not e2ee. For e2ee audio and video calls, you can use FaceTime or another app like Signal.
```

2022-08-19 11:21 UTC, ph00lt0 commented on docs/ios/overview.en.md
> +- [ ] Turn off **iCloud Drive**
This list is not very specific on what exactly you should turn off. The features or syncing? It currently would also contradict the advise for using apple health in the new health section.

2022-08-19 11:22 UTC, ph00lt0 requested changes

2022-08-19 11:22 UTC, ph00lt0 commented on docs/ios/overview.en.md
> +- [ ] Turn off **iCloud Drive**
This list is not very specific on what exactly you should turn off. The features or syncing? It currently would also contradict the advise for using apple health in the new health section.

2022-08-19 11:25 UTC, ph00lt0 commented on docs/ios/overview.en.md
> +Normal phone calls made with the Phone app are not e2ee. For e2ee audio and video calls, you can use Facetime or another app like Signal.
Using Facetime links you to your phone number to your Apple ID. I think that should be pointed out.

2022-08-19 11:27 UTC, ph00lt0 commented
Still missing:
- DNS profiles such as adguard's: https://adguard.com/en/blog/encrypted-dns-ios-14.html
- Lockdown mode

2022-09-11 04:34 UTC, mfwmyfacewhen commented on docs/ios/overview.en.md
> +Whether you choose to use TouchID/FaceID or just a regular password on your phone will be determined by your threatmodel. If you are worried about people accessing your phone without your knowledge w
yeah lets do that

2022-09-11 12:50 UTC, purtual requested changes

2022-09-11 12:50 UTC, purtual commented on docs/ios/overview.en.md
> +    With this setting enabled, someone could intentially wipe your phone by entering the wrong password many times. Make sure you have proper backups and only enable this setting if it fits your thre
```suggestion
    With this setting enabled, someone could intentionally wipe your phone by entering the wrong password many times. Make sure you have proper backups and only enable this setting if it fits your threat model.
```

2022-09-11 12:50 UTC, purtual commented on docs/ios/overview.en.md
> +### Password or TouchID/FaceID?
```suggestion
### Password or Touch ID/Face ID?
```

2022-09-11 12:50 UTC, purtual commented on docs/ios/overview.en.md
> +Whether you choose to use TouchID/FaceID or just a regular password on your phone will be determined by your threatmodel. If you are worried about people accessing your phone without your knowledge w
```suggestion
Whether you choose to use Touch ID/Face ID or just a regular password on your phone will be determined by your threatmodel. If you are worried about people accessing your phone without your knowledge who might use your fingerprint/face to unlock your phone, such as a roommate or a partner, then you should only use a regular password.
```

2022-09-11 18:14 UTC, closed without merging