File encryption migration
privacyguides/privacyguides.org pull request #822
Opened 2022-03-30 14:07 UTC by dngray

2022-03-30 15:10 UTC, samuel-lucas6 requested changes
Thanks for doing this!

> **Kryptor** is a free and open source file encryption tool that simplifies the use of [age](https://github.com/FiloSottile/age) and [minisign](https://jedisct1.github.io/minisign/).

Just wanted to point out that this may be misleading since Kryptor deliberately isn't compatible with either tool.

2022-03-31 01:22 UTC, EdwardLangdon commented
Why there is No Cloud Storage Providers in the list ?

2022-03-31 05:53 UTC, flexagoon commented
Why is the page heading "Cloud Storage" and not "File Encryption Software"?

2022-03-31 13:14 UTC, dngray commented
> Why is the page heading "Cloud Storage" and not "File Encryption Software"?

That might be an error. :grin: well spotted.

2022-03-31 23:11 UTC, merged

2022-04-01 08:53 UTC, samuel-lucas6 reviewed
@dngray Some spelling/grammar things, rewording, and additional information.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-browser-based/1_hat-sh.yml
> +  **Hat.sh** is a web application that provides secure client-side file encryption in your browser. It can also be selfhosted and is useful if you need to encrypt a file but cannot install any softwa
Change to self-hosted?

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-commandline/1_kryptor.yml
> +privacy_policy: ''
I have an informal privacy policy here: https://www.kryptor.co.uk/features#privacy.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-commandline/2_tomb.yml
> +  **Tomb** is an is a commandline shell wrapper around LUKS. It includes uses some [third party tools](https://github.com/dyne/Tomb#how-does-it-work) to provide [steganography](https://en.wikipedia.o
command-line or command line as two words. It 'includes and uses some third-party tools', one or the other, or 'it supports steganography via third-party tools'.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/1_veracrypt.yml
> +  **VeraCrypt** is a source-available freeware utility used for on-the-fly encryption. It can create a virtual encrypted disk within a file, encrypt a partition, or encrypt the entire storage device
Has there been more than one TrueCrypt audit?

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
'FileCrypt'. ' GnuPG is part of the Free Software Foundation's GNU Project and has received major funding from the German government.'

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/3_cryptomator.yml
> +  **Cryptomator** makes it easy for you to upload files to the cloud in a virtual encrypted filesystem. The software was [audited](https://cryptomator.org/open-source/) by [cure53](https://cryptomato
I'd change 'filesystem' to 'file system'. I still think it's misleading to claim the entire program has been audited when the report says the scope was limited to their cryptographic libraries:

> Scope
> • Cryptomator Crypto Libraries
> ◦ https://github.com/cryptomator/cryptolib
> ◦ https://github.com/cryptomator/cryptofs
> ◦ https://github.com/cryptomator/siv-mode
> ◦ https://github.com/cryptomator/cryptomator-objc-cryptor

I don't know whether Cryptomator exclusively uses these libraries for their crypto or if they do anything additionally in the clients.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/4_picocrypt.yml
> +  We think the best usecase for this is if you need to encrypt some files, or archives.
'if you need to encrypt some files or archives', although I would personally remove this sentence.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/4_picocrypt.yml
> +    url: 'https://github.com/HACKERALERT/Picocrypt/releases'
Is it worth changing these to https://github.com/HACKERALERT/Picocrypt/releases/latest?

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +title: Bitlocker
Should be spelt 'BitLocker' everywhere.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +  **Bitlocker** is the default full volume encryption that comes with Microsoft Windows. The main reason we recommend it is because of its [use of TPM](https://docs.microsoft.com/en-us/windows/securi
'ElcomSoft'.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-operating-system/2_filevault.yml
> +title: Filevault
Should be spelt 'FileVault' everywhere.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-operating-system/2_filevault.yml
> +  **Filevault** is the on-the-fly disk encryption that comes with MacOS. We recommend it because tightly intergrates with the [Apple T2 Security Chip](https://support.apple.com/guide/security/volume-
Should be 'macOS' since that's how it's written on Apple devices and their website. 'because it tightly integrates'.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-operating-system/3_luks.yml
> +  We recommend you always [backup your LUKS headers](https://wiki.archlinux.org/title/Dm-crypt/Device_encryption#Backup_and_restore) in case of partial drive failure. This can be done with:
'back up'.

2022-04-01 08:53 UTC, samuel-lucas6 commented on collections/_evergreen/cloud.md
> +  Consider reducing the need to trust your provider, by using an alternative below that supports [end-to-end encryption](https://wikipedia.org/wiki/End-to-end_encryption) (E2EE).
'trust your provider by using'. Remove the comma.

2022-04-01 08:53 UTC, samuel-lucas6 commented on collections/_evergreen/encryption-software.md
> +  Encryption of data is the only way to control who can access it. If you are currently not using encryption software for your hard disk, emails, or file archives, you should pick an option here.
'or files/archives' or just 'files'?

2022-04-01 08:53 UTC, samuel-lucas6 commented on collections/_evergreen/encryption-software.md
> +Web based encryption can be useful when you need to encrypt a file, and you cannot install software or apps on your device.
'Web-based' and 'encrypt a file, but you cannot'.

2022-04-01 08:53 UTC, samuel-lucas6 commented on collections/_evergreen/encryption-software.md
> +Tools with commandline interfaces are useful for intergrating [shell scripts](https://en.wikipedia.org/wiki/Shell_script).
'command-line' or 'command line'. Makes sense to use the dash if the heading does.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/1_veracrypt.yml
> +  **VeraCrypt** is a source-available freeware utility used for on-the-fly encryption. It can create a virtual encrypted disk within a file, encrypt a partition, or encrypt the entire storage device
Perhaps mention that SHA512 and AES should be used. The Russian algorithms may be backdoored.

2022-04-01 08:53 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
You could also link this summary of the limitations of PGP/GnuPG: https://latacora.micro.blog/2019/07/16/the-pgp-problem.html.

2022-04-01 16:46 UTC, HACKERALERT commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +  **Bitlocker** is the default full volume encryption that comes with Microsoft Windows. The main reason we recommend it is because of its [use of TPM](https://docs.microsoft.com/en-us/windows/securi
Would it be worth noting that the BL GUI is only available for W10/11 Pro? I have a W10 Pro and I can enable BL from the control panel. I also have a W11 Home, and I had to use the BL CLI to set it up.

2022-04-02 06:53 UTC, dngray commented
I'll give these a look over in a new PR now that the page has changed format.

2022-04-02 07:43 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
Like with VeraCrypt, there could be a warning saying don't use algorithms other than AES for symmetric encryption, etc.

2022-04-02 08:46 UTC, dngray commented on _data/software/encryption-browser-based/1_hat-sh.yml
> +  **Hat.sh** is a web application that provides secure client-side file encryption in your browser. It can also be selfhosted and is useful if you need to encrypt a file but cannot install any softwa
:+1:

2022-04-02 08:47 UTC, dngray commented on _data/software/encryption-commandline/1_kryptor.yml
> +privacy_policy: ''
:+1:

2022-04-02 08:49 UTC, dngray commented on _data/software/encryption-commandline/2_tomb.yml
> +  **Tomb** is an is a commandline shell wrapper around LUKS. It includes uses some [third party tools](https://github.com/dyne/Tomb#how-does-it-work) to provide [steganography](https://en.wikipedia.o
:+1:

2022-04-02 08:50 UTC, dngray commented on _data/software/encryption-multi-platform/1_veracrypt.yml
> +  **VeraCrypt** is a source-available freeware utility used for on-the-fly encryption. It can create a virtual encrypted disk within a file, encrypt a partition, or encrypt the entire storage device
Good point, that's something I've always done.

2022-04-02 08:59 UTC, dngray commented on _data/software/encryption-multi-platform/1_veracrypt.yml
> +  **VeraCrypt** is a source-available freeware utility used for on-the-fly encryption. It can create a virtual encrypted disk within a file, encrypt a partition, or encrypt the entire storage device
:+1:

2022-04-02 09:08 UTC, dngray commented on _data/software/encryption-multi-platform/3_cryptomator.yml
> +  **Cryptomator** makes it easy for you to upload files to the cloud in a virtual encrypted filesystem. The software was [audited](https://cryptomator.org/open-source/) by [cure53](https://cryptomato
Ah yes I meant to change this one. I did read the audit report https://github.com/privacyguides/privacyguides.org/discussions/24#discussioncomment-1751311

2022-04-02 09:08 UTC, dngray commented on _data/software/encryption-multi-platform/4_picocrypt.yml
> +  We think the best usecase for this is if you need to encrypt some files, or archives.
Yeah...

2022-04-02 09:10 UTC, dngray commented on _data/software/encryption-multi-platform/4_picocrypt.yml
> +    url: 'https://github.com/HACKERALERT/Picocrypt/releases'
Already done :+1:

2022-04-02 09:11 UTC, dngray commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +  **Bitlocker** is the default full volume encryption that comes with Microsoft Windows. The main reason we recommend it is because of its [use of TPM](https://docs.microsoft.com/en-us/windows/securi
> Would it be worth noting that the BL GUI is only available for W10/11 Pro? I have a W10 Pro and I can enable BL from the control panel. I also have a W11 Home, and I had to use the BL CLI to set it up.

Very good point, I don't have any home copies of Windows.

2022-04-02 09:13 UTC, dngray commented on _data/software/encryption-operating-system/2_filevault.yml
> +title: Filevault
:+1:

2022-04-02 09:13 UTC, dngray commented on _data/software/encryption-operating-system/3_luks.yml
> +  We recommend you always [backup your LUKS headers](https://wiki.archlinux.org/title/Dm-crypt/Device_encryption#Backup_and_restore) in case of partial drive failure. This can be done with:
:+1:

2022-04-02 09:15 UTC, dngray commented on collections/_evergreen/cloud.md
> +  Consider reducing the need to trust your provider, by using an alternative below that supports [end-to-end encryption](https://wikipedia.org/wiki/End-to-end_encryption) (E2EE).
:+1:

2022-04-02 09:17 UTC, dngray commented on collections/_evergreen/encryption-software.md
> +  Encryption of data is the only way to control who can access it. If you are currently not using encryption software for your hard disk, emails, or file archives, you should pick an option here.
:+1: yes, definitely

2022-04-02 09:18 UTC, dngray commented on collections/_evergreen/encryption-software.md
> +Web based encryption can be useful when you need to encrypt a file, and you cannot install software or apps on your device.
:+1:

2022-04-02 09:19 UTC, dngray commented on collections/_evergreen/encryption-software.md
> +Tools with commandline interfaces are useful for intergrating [shell scripts](https://en.wikipedia.org/wiki/Shell_script).
:+1:

2022-04-02 09:27 UTC, dngray commented on _data/software/encryption-operating-system/2_filevault.yml
> +  **Filevault** is the on-the-fly disk encryption that comes with MacOS. We recommend it because tightly intergrates with the [Apple T2 Security Chip](https://support.apple.com/guide/security/volume-
Yes, it should be

2022-04-02 09:28 UTC, dngray commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +title: Bitlocker
:+1: yes.

2022-04-02 10:59 UTC, dngray commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
Ah yes, i've read that article before. It's well written.

2022-04-02 11:19 UTC, dngray commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
I'm honestly not sure who wrote Veridis' Filecrypt there because I don't think i'd bother mentioning it. Looks to be some ancient software that I can't find anything about https://linuxsecurity.com/news/vendors-products/veridis-release-filecrypt-sdk-a-cross-platform-security-library their domain doesn't seem to resolve to anything either.

2022-04-02 11:25 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
Fair enough; I'd say remove it then.

2022-04-02 11:51 UTC, dngray commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
> Fair enough; I'd say remove it then.

i edited my reply, with something i remembered, so you may not agree and want to thumbs up me anymore.

2022-04-02 11:56 UTC, dngray commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
What do you think about the current card?

2022-04-02 12:05 UTC, dngray commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
I'm having another look at your https://github.com/privacyguides/privacyguides.org/discussions/24#discussioncomment-1751943 and I am inclined to agree, I would not use GnuPG for file encryption.

Signing maybe, there is the whole WoT thing, but with the SKS pool no longer really around you have to depend on centralized places like WKD, personal websites. I don't think crypto signing parties happen outside nerd culture.

2022-04-02 13:09 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
> i edited my reply, with something i remembered, so you may not agree and want to thumbs up me anymore.

I completely agree with you on Signal, although I also agree with him in that Signal is a much better option for anyone you know. I looked into all of the main messengers in a blog post a while back and concluded that Signal is the only one that should be used. I gave Element a good go, but I ran into numerous decryption issues over an extended period of time with multiple people to the point that it was an unusable solution as we couldn't communicate. Other than that, Session and Wire are probably the next best, but both have their own problems.

The problem with RFCs is that they kind of suck. There are many good and widely used solutions that haven't been officially standardised. Encrypt-then-MAC is used by Signal and was used in TLS, but there's not an generalised RFC. It has advantages over AEAD modes like ChaCha20-Poly1305 and AES-GCM, so it should be standardised. XChaCha20 has a draft that was never accepted after several years when there's no reason it shouldn't have been. The PASETO and generalised SIV drafts weren't accepted. Salsa20 and XSalsa20 became popular after the eSTREAM competition via the NaCl and libsodium libraries but never got an RFC. The RFC for ChaCha20 is different to the algorithm originally published. Argon2 was used well before the RFC was accepted. It seems like if you don't have commercial backing from a company like Google, your RFC will not get accepted, regardless of whether or not it's a good idea.

You're right that email isn't going anywhere, but it should really be viewed as an insecure medium no matter what you do.

2022-04-02 13:13 UTC, samuel-lucas6 commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
> What do you think about the current card?

I would remove the comma before 'and has received major funding'. Otherwise, I think that's a good way of putting it.

> I'm having another look at your #24 (reply in thread) and I am inclined to agree, I would not use GnuPG for file encryption.

Yep, the main use case is verifying signatures for software downloads since companies and most projects use GPG, probably due to it being on Linux and having an RFC again. There are numerous better file encryption tools.

2022-04-02 13:28 UTC, dngray commented on _data/software/encryption-multi-platform/2_gnupg.yml
> +  **GnuPG** is a GPL-licensed alternative to the PGP suite of cryptographic software. GnuPG is compliant with RFC 4880, which is the current IETF standards track specification of OpenPGP. Current ver
something to think about in another issue.

2022-04-02 13:45 UTC, dngray commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +  **Bitlocker** is the default full volume encryption that comes with Microsoft Windows. The main reason we recommend it is because of its [use of TPM](https://docs.microsoft.com/en-us/windows/securi
@HACKERALERT 
That command wouldn't happen to be:

```
manage-bde -on C: -RecoveryKey D: -RecoveryPassword
```

I haven't had a Home edition of any of Microsoft's OSes since like, forever.

2022-04-02 13:50 UTC, HACKERALERT commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +  **Bitlocker** is the default full volume encryption that comes with Microsoft Windows. The main reason we recommend it is because of its [use of TPM](https://docs.microsoft.com/en-us/windows/securi
If you are dngray@polarbear.army, then I've given you the link :). But for convenience: https://superuser.com/questions/1590289/how-to-enable-bitlocker-system-drive-encryption-on-windows-10-home

It's worth noting that you can make BL password only without a TPM.
`manage-bde c: -protectors -add -rp -tpm`
Means to add a recovery phrase and TPM to protect the encryption key. If you get rid of the two arguments and replace it with -passphrase ( I forget what it is exactly, but MS has docs), you can only unlock with password. So it's very flexible.

2022-04-02 13:54 UTC, HACKERALERT commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +  **Bitlocker** is the default full volume encryption that comes with Microsoft Windows. The main reason we recommend it is because of its [use of TPM](https://docs.microsoft.com/en-us/windows/securi
Also, BL uses AES-128-XTS by default. You have to configure the group policy to use AES-256-XTS.

2022-04-02 14:04 UTC, dngray commented on _data/software/encryption-operating-system/1_bitlocker.yml
> +  **Bitlocker** is the default full volume encryption that comes with Microsoft Windows. The main reason we recommend it is because of its [use of TPM](https://docs.microsoft.com/en-us/windows/securi
This looks good, https://superuser.com/questions/1590289/how-to-enable-bitlocker-system-drive-encryption-on-windows-10-home I don't have a home edition right here.