Feedback from https://github.com/privacyguides/privacyguides.org/pull…
privacyguides/privacyguides.org pull request #847
Opened 2022-04-02 09:31 UTC by dngray

https://privacyguides.org/encryption/

Feedback from https://github.com/privacyguides/privacyguides.org/pull/822

2022-04-02 09:45 UTC, samuel-lucas6 requested changes
A few corrections here.

2022-04-02 09:45 UTC, samuel-lucas6 commented on docs/encryption.md
> +        When encrypting with Veracrypt, the user has the option to [select from ](https://en.wikipedia.org/wiki/VeraCrypt#Encryption_scheme) different hash functions. We suggest users **only** select
'VeraCrypt', a space has crept in after 'select from', and I'd perhaps move the link to 'different hash functions'.

2022-04-02 09:45 UTC, samuel-lucas6 commented on docs/encryption.md
> +        When encrypting with Veracrypt, the user has the option to [select from ](https://en.wikipedia.org/wiki/VeraCrypt#Encryption_scheme) different hash functions. We suggest users **only** select
Please see the comment for the VeraCrypt message. This one shouldn't say VeraCrypt or link the VeraCrypt algorithms.

2022-04-02 09:45 UTC, samuel-lucas6 commented on docs/encryption.md
> +    Some of the Cryptomator Crypto Libraries have been [audited](https://cryptomator.org/open-source/) by [cure53](https://cryptomator.org/audits/2017-11-27%20crypto%20cure53.pdf).
'Cure53'. Missed this before.

2022-04-02 09:45 UTC, samuel-lucas6 commented on docs/encryption.md
> +Browser based encryption can be useful when you need to encrypt a file, cannot install software or apps on your device.
'Browser-based' to be consistent with the heading. I'd just switch ', and you' with 'but cannot' as it sounds nicer.

2022-04-02 09:59 UTC, dngray commented on docs/encryption.md
> +    Some of the Cryptomator Crypto Libraries have been [audited](https://cryptomator.org/open-source/) by [cure53](https://cryptomator.org/audits/2017-11-27%20crypto%20cure53.pdf).
I think I might have edited it after you reviewed but not pushed back to the main branch.

2022-04-02 10:01 UTC, dngray commented on docs/encryption.md
> +Browser based encryption can be useful when you need to encrypt a file, cannot install software or apps on your device.
:smile: yeah I was a bit sleepy on that one.

2022-04-02 11:10 UTC, dngray commented on docs/encryption.md
> +        When encrypting with Veracrypt, the user has the option to [select from ](https://en.wikipedia.org/wiki/VeraCrypt#Encryption_scheme) different hash functions. We suggest users **only** select
Funny you mention that I had 'different hash functions' originally linking to what a hash function [was](https://en.wikipedia.org/wiki/Cryptographic_hash_function), but this makes more sense because that is in the wikipedia article.

2022-04-02 11:12 UTC, dngray commented on docs/encryption.md
> +        When encrypting with Veracrypt, the user has the option to [select from ](https://en.wikipedia.org/wiki/VeraCrypt#Encryption_scheme) different hash functions. We suggest users **only** select
Indeed, i had not finished writing that, I went off to look at something else :grin:

2022-04-02 14:10 UTC, merged

2022-04-02 20:19 UTC, HACKERALERT commented
@dngray 
> BitLocker is [only supported](https://support.microsoft.com/en-us/windows/turn-on-device-encryption-0c453637-bc88-5f74-5105-741561aae838) on Pro, Enterprise, and Education editions of Windows. It can be enabled on Home editions provided that they meet the prequesites.

'prequesites' should be 'prerequisites'.

2022-04-03 09:18 UTC, dngray commented
> 'prequesites' should be 'prerequisites'.

Thanks for that fixed https://github.com/privacyguides/privacyguides.org/commit/f8c574d85684fcd140816424a524a0f0a5a89a9d#diff-d5adef5d64db7a4e7e6df01a42c56916690bec1289c2916de506ab4cd450b2d6R110