Add doineedavpn.com to Sources and Further Reading
privacyguides/privacyguides.org pull request #859
Opened 2022-04-02 20:39 UTC by NylaTheWolf

## Description

 

I added http://doineedavpn.com/ to the Sources and Further Reading section. It is a quiz by IVPN where the user chooses the issues they want to solve and benefits they look for in their VPN, and informs them whether or not a VPN would actually address any of these issues. 

I think that this website would be a great addition to the Further Reading section because it challenges the misconceptions surrounding VPNs, especially with the aggressive marketing from VPN companies, and helps users decide whether or not they actually need a VPN. It also tells the user if Tor would be a better solution for them. It certainly helped me when I was looking into getting a VPN!

I know that Privacy Guides already addresses these misconceptions, but I still think it's a fantastic source, especially if you wanted to share it with a friend.

2022-04-02 20:53 UTC, ph00lt0 commented
Looks good indeed, also nice to see they link to Privacy Guides :)

2022-04-03 00:19 UTC, lx-is requested changes
It's a good tool, should definitely be added. It might even be better to add it to the "When are VPNs useful?" section instead.

2022-04-03 00:19 UTC, lx-is commented on docs/vpn.md
> +6.  ["Do I Need a VPN?"](http://doineedavpn.com/), a tool by IVPN to explain what a VPN does and does not help with and help individual users decide if they need a VPN for their use case.
```suggestion
6.  ["Do I need a VPN?"](https://www.doineedavpn.com/), a tool developed by IVPN to challenge aggressive VPN marketing and help individuals decide if a VPN is right for them.
```

2022-04-03 14:22 UTC, dngray commented
I've had a look at this, and am happy to merge.

IVPN produces quality documentation from what I've seen. It's nice for a change, when so many VPN companies just hide behind false marketing.

2022-04-03 15:24 UTC, merged

2022-04-03 15:27 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
IVPN Does link to privacyguides but i get a 404 if i click on it

2022-04-04 18:21 UTC, NylaTheWolf commented
Thank you for approving! I'm happy to contribute! 🙂