Update the 2FA page (WIP)
privacyguides/privacyguides.org pull request #862
Opened 2022-04-02 21:55 UTC by tommytran732

2022-04-02 23:07 UTC, opheron commented
@tommytran732 Hey, just a heads up I recently submitted PR #861 which also makes significant changes the 2FA article.

2022-04-03 16:27 UTC, dngray commented on docs/android.md
> + - Evaluate whether the additional features in the F-Droid build are worth the slower updates. Also think about whether faster updates from the Google Play Store are worth the potential privacy isues
> isues

2022-04-03 16:29 UTC, dngray commented on docs/multi-factor-authentication.md
> +The idea behind 2FA is that even if a hacker is able to figure out your password (something you *know*), they will still need a device you own like your phone (something you *have*) in order to gener
I was pretty sure I edited this "strongest to weakest" thing, cos it sounds like email codes are the strongest and SMS codes are the second strongest.

2022-04-03 16:30 UTC, dngray commented on docs/multi-factor-authentication.md
> +==**Email** or **SMS 2FA** are better than nothing at all, but only marginally.== Getting a code over SMS or Email takes away from the "something you *have*" idea, because there are a variety of ways
Maybe we could use a link to https://en.wikipedia.org/wiki/SIM_swap_scam ?

2022-04-03 16:31 UTC, dngray commented on docs/multi-factor-authentication.md
> +To make matters worse, if a hacker gains access to your email, they typically would be able to use it to both reset your password and receive the second factor authentication code, giving them full a
Generally this is why we would recommend 2FA on an email too.

2022-04-03 16:35 UTC, dngray commented
Feedback on the MFA article, would be don't make it too verbose or complex, as it is an entry article.

2022-04-03 23:24 UTC, tommytran732 commented on docs/multi-factor-authentication.md
> +To make matters worse, if a hacker gains access to your email, they typically would be able to use it to both reset your password and receive the second factor authentication code, giving them full a
I will mention it briefly in the general recommendations section. I don't think it matters much though, the email is not completely in the user's control like say, a TOTP app or a Yubikey is. What if the email server gets hacked?

2022-04-03 23:25 UTC, tommytran732 commented on docs/multi-factor-authentication.md
> +==**Email** or **SMS 2FA** are better than nothing at all, but only marginally.== Getting a code over SMS or Email takes away from the "something you *have*" idea, because there are a variety of ways
How would you phrase it?

2022-04-03 23:26 UTC, tommytran732 commented on docs/multi-factor-authentication.md
> +The idea behind 2FA is that even if a hacker is able to figure out your password (something you *know*), they will still need a device you own like your phone (something you *have*) in order to gener
Fixed.

2022-04-04 10:20 UTC, elitejake requested changes

2022-04-04 10:20 UTC, elitejake commented on docs/multi-factor-authentication.md
> +    The [comparison table](https://www.yubico.com/store/compare/) shows the features and how the Yubikeykeys compare. We highly recommend that you select keys from the Yubikey 5 Series.
~~Yubikeykeys~~ to Yubikeys

2022-04-04 21:02 UTC, tommytran732 commented
> Feedback on the MFA article, would be don't make it too verbose or complex, as it is an entry article.

Do you wanna split it into 2 pages then?

2022-04-04 21:03 UTC, tommytran732 commented
IMO just recommending the Nitrokey and Yubikey and pretending that they are equal is not enough. Likewise, recommending hardware security keys over authenticator app is not great either. It depends heavily on which exact protocol is being used and how the secrets are stored.

2022-04-05 02:31 UTC, realguyman commented
It should be noted that TOTP-based authentication is _still_ vulnerable to phishing attacks.

And it should be noted that hardware security keys and services which adopt FIDO2/U2F are not vulnerable to phishing attacks.

2022-04-05 02:34 UTC, realguyman commented
If someone is going to purchase a hardware security key, it should be for FIDO2/U2F support.

Aegis Authenticator and other similar applications are secure enough for TOTP-based multi-factor authentication.

2022-04-05 10:48 UTC, tommytran732 commented
> If someone is going to purchase a hardware security key, it should be for FIDO2/U2F support.
> 
> Aegis Authenticator and other similar applications are secure enough for TOTP-based multi-factor authentication.

Depends. Yes, that is the most common use case, but it is not always applicable.
Take the Nitrokey storage 2 for example. It is an okay PGP smartcard, it has system integrity verification integration with heads (this is unique to Nitrokeys), and encrypted password storage. It stores HOTP and TOTP secrets as well, tho they are not encrypted.

For certain use cases, it is okay as a hardware security key despite of the fact that it does not support FIDO2/U2F.

2022-04-06 04:17 UTC, jonaharagon commented on docs/tools.md
> +- ![Nitrokey](/assets/img/multi-factor-authentication/nitrokey.jpg){ .twemoji } [Nitrokey](https://www.nitrokey.com/)
These images could be improved.

2022-04-10 14:13 UTC, merged