Add Apple Mail
privacyguides/privacyguides.org pull request #893
Opened 2022-04-04 13:17 UTC by dngray

2022-04-04 18:00 UTC, jonaharagon commented
GPG Mail from GPGTools is not free, it requires a ~$24 (roughly yearly) [support plan](https://gpgtools.org/support-plan) after a 30-day free trial.

2022-04-04 18:43 UTC, dngray commented
> GPG Mail from GPGTools is not free, it requires a ~$24 (roughly yearly) [support plan](https://gpgtools.org/support-plan) after a 30-day free trial. Don't know if this makes a difference for the recommendation. It _is_ open-source with [their own license](https://github.com/GPGTools/GPGMail/blob/dev/LICENSE.txt) which is very permissive at a glance.

Probably should mention that, but no we'd still list it, as it's the only implementation that does support Apple Mail, and integrates nicely.

2022-04-04 18:51 UTC, lx-is requested changes

2022-04-04 18:51 UTC, lx-is commented on docs/email-clients.md
> +        For iOS devices we suggest [Canary Mail](/email-clients/#canary-mail) as it has PGP support which means you can sen
This sentence isn't finished

2022-04-04 18:51 UTC, lx-is commented on docs/email-clients.md
> +Our recommended email clients list contains email clients that support both [OpenPGP](/encryption/#openpgp) and strong authentication such as [Open Authorization (OAuth)](https://en.wikipedia.org/wik
This sounded a bit convoluted

```suggestion
Our recommendation list contains email clients that support both [OpenPGP](/encryption/#openpgp) and strong authentication such as [Open Authorization (OAuth)](https://en.wikipedia.org/wiki/OAuth). OAuth allows you to use [Multi-Factor Authentication](/multi-factor-authentication) and prevent account theft.
```

2022-04-04 18:51 UTC, lx-is commented on docs/email-clients.md
> +    [Visit apple.com](https://support.apple.com/guide/mail/welcome/mac){ .md-button .md-button--primary }
Use the privacy policy linked on the Apple Mail App Store page

```suggestion
    [Visit apple.com](https://support.apple.com/guide/mail/welcome/mac){ .md-button .md-button--primary } [Privacy Policy](https://www.apple.com/legal/privacy/en-ww/){ .md-button }
```

2022-04-04 19:03 UTC, dngray commented on docs/email-clients.md
> +        For iOS devices we suggest [Canary Mail](/email-clients/#canary-mail) as it has PGP support which means you can sen
Oh, yeah must have got distracted.

2022-04-04 19:22 UTC, merged

2022-04-05 01:40 UTC, lx-is commented
> GPG Mail from GPGTools is not free

There is [Free-GPGMail](https://github.com/Free-GPGMail/Free-GPGMail) which removes the DRM. "While the seller of the commercial product has the right to charge for a support plan and place DRM into their product, it is still BSD and GPL licensed software which requires the source code to be available."