Add RSS page
privacyguides/privacyguides.org pull request #895
Opened 2022-04-04 15:49 UTC by dngray

2022-04-04 17:56 UTC, jonaharagon commented
Screenshots until I have our PR previews set up again:

![image](https://user-images.githubusercontent.com/3637842/161603094-3608d43d-94c0-46de-b7f1-df6e4396d6f8.png)

![image](https://user-images.githubusercontent.com/3637842/161603128-f4842f8b-c676-4dd0-9241-808151657d6f.png)

![image](https://user-images.githubusercontent.com/3637842/161603159-b7df66d4-cfcc-4201-b24a-ddc0cc5db8b0.png)

2022-04-04 17:57 UTC, jonaharagon approved these changes

2022-04-04 18:40 UTC, lx-is requested changes

2022-04-04 18:40 UTC, lx-is commented on docs/news-aggregators.md
> +    **NetNewsWire** a free and open-source feed reader for macOS and iOS. It supports [RSS](https://en.wikipedia.org/wiki/RSS), [Atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)), [JSON Feed](
This is the only recommendation that doesn't describe what sets it apart from other reader apps. 

```suggestion
    **NetNewsWire** a free and open-source feed reader for macOS and iOS with a focus on a native design and feature set. It supports the typical feed formats alongside built-in support for Twitter and Reddit feeds.
```

2022-04-04 18:40 UTC, lx-is commented on docs/news-aggregators.md
> +    - [:fontawesome-brands-apple: macos](https://apps.apple.com/us/app/netnewswire-rss-reader/id1480640210)
Wrong link

```suggestion
    - [:fontawesome-brands-apple: macOS](https://netnewswire.com)
```

2022-04-04 18:40 UTC, lx-is commented on docs/news-aggregators.md
> +    - [:fontawesome-brands-app-store: Mac App Store](https://apps.apple.com/us/app/netnewswire-rss-reader/id1480640210)
iOS not macOS

```suggestion
    - [:fontawesome-brands-app-store-ios: App Store](https://apps.apple.com/us/app/netnewswire-rss-reader/id1480640210)
```

2022-04-04 18:40 UTC, lx-is commented on docs/news-aggregators.md
> +    - [:fontawesome-brands-apple: macos](https://apps.apple.com/app/id1520907427)
Capitalization

```suggestion
    - [:fontawesome-brands-apple: macOS](https://apps.apple.com/app/id1520907427)
```

2022-04-04 18:40 UTC, lx-is commented on docs/news-aggregators.md
> +    [Visit netnewswire.com](https://netnewswire.com/){ .md-button .md-button--primary } [Privacy Policy](){ .md-button }
Missing privacy policy

```suggestion
    [Visit netnewswire.com](https://netnewswire.com/){ .md-button .md-button--primary } [Privacy Policy](https://netnewswire.com/privacypolicy){ .md-button }
```

2022-04-04 18:40 UTC, lx-is commented on docs/news-aggregators.md
> +    [Visit github.com](https://github.com/yanus171/Handy-News-Reader){ .md-button .md-button--primary }
Use the GH pages website instead of the repo

```suggestion
    [Visit github.com](http://yanus171.github.io/Handy-News-Reader/){ .md-button .md-button--primary }
```

2022-04-04 18:40 UTC, lx-is commented on docs/news-aggregators.md
> +    [Visit hyliu.me](https://hyliu.me/fluent-reader){ .md-button .md-button--primary } [Privacy Policy](){ .md-button }
Missing privacy policy

```suggestion
    [Visit hyliu.me](https://hyliu.me/fluent-reader){ .md-button .md-button--primary } [Privacy Policy](https://github.com/yang991178/fluent-reader/wiki/Privacy){ .md-button }
```

2022-04-04 19:03 UTC, elitejake requested changes

2022-04-05 01:02 UTC, lx-is requested changes

2022-04-05 01:02 UTC, lx-is commented on docs/tools.md
> +- ![NetNewsWire](/assets/img/news-aggregators/netnewswire.png){ .twemoji } [Newsboat](https://newsboat.org)
Fix NNW card

```suggestion
- ![NetNewsWire](/assets/img/news-aggregators/netnewswire.png){ .twemoji } [NetNewsWire](https://netnewswire.com)
```

2022-04-05 19:26 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Closes https://github.com/privacyguides/privacyguides.org/discussions/102

2022-04-05 19:36 UTC, efb4f5ff-1298-471a-8973-3d47447115dc commented
Would also like to see why these are being selected over other RSS readers

Related https://github.com/privacyguides/privacyguides.org/discussions/24

2022-04-06 02:34 UTC, EdwardLangdon commented
I know this is mostly about Open Source, How about Inoreader or Feedbin to the list ?

2022-04-08 08:53 UTC, darkvadd7 commented
After trying Handy News Reader, I think there are at least two better options for Android. First, it's impossible in Handy News Reader to directly open the link in a browser. Second, the UI is not really good and the images are not displaying until you open the article.

The two better options I recommand are [Feeder](https://f-droid.org/en/packages/com.nononsenseapps.feeder/) and [Flym DecSync](https://f-droid.org/en/packages/org.decsync.flym/). This two have great UI and you can directly open an article in the browser. Maybe less options and features than Handy News Reader, but a lot more usable.

2022-04-08 09:37 UTC, dngray commented
> [Feeder](https://f-droid.org/en/packages/com.nononsenseapps.feeder/) and 

I did use Feeder briefly, and found there was something I didn't like about it, I think it didn't support folders when importing from OPML.

I also tried https://f-droid.org/en/packages/com.readrops.app, but with that you couldn't refresh a single news feed.

[Flym DecSync](https://f-droid.org/en/packages/org.decsync.flym/).

That's only the Decsync plugin, upstream Flym is now unmaintained and Handy News Reader is a fork of Flym.

2022-04-08 09:45 UTC, darkvadd7 commented
> I did use Feeder briefly, and found there was something I didn't like about it, I think it didn't support folders when importing from OPML.
I'm using an OPML file with it, and I have my folders.
Maybe I have to try more Handy News Reader to get it work the way I want.

2022-04-10 10:55 UTC, dngray commented on docs/news-aggregators.md
> +[News aggregators](https://en.wikipedia.org/wiki/News_aggregator) are a a great way to keep an eye on your favourite blogs and places of news.
it is a bit, I'm sure i can come up with something better.

2022-04-11 02:36 UTC, lx-is approved these changes

2022-04-11 11:55 UTC, merged