Detail the DivestOS hardening
privacyguides/privacyguides.org pull request #904
Opened 2022-04-04 21:47 UTC by SkewedZeppelin

## Description

More thoroughly notes what features DivestOS includes.
- https://divestos.org/index.php?page=news
- https://divestos.org/index.php?page=technical_details

Also sadly removes the Bromite WebView option, for some unknown reason it causes the 15.1 branch to not boot.

2022-04-05 06:13 UTC, dngray requested changes

2022-04-05 06:13 UTC, dngray commented on docs/android.md
> +DivestOS has automated kernel vulnerability ([CVE](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures)) [patching](https://gitlab.com/divested-mobile/cve_checker), fewer proprietary b
> full page sanitization

I would have linked a link there, perhaps https://portswigger.net/daily-swig/google-and-mozilla-unveil-plans-to-bake-html-sanitization-into-their-browsers

https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API seems a bit too "terse" for this kind of reference.

> all ~22 Clang-compiled kernels have `-ftrivial-auto-var-init=zero` enabled

Would be good if we coudl find a source for that, that explains what it is.

2022-04-05 06:13 UTC, dngray commented on docs/android.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
> [exec-spawning](/android/#additional-hardening), JNI constification, and partial bionic hardening patchsets. 17.1 and 18.1 feature GrapheneOS's per-network full MAC randomization option, ptrace_scope control, and automatic reboot/Wi-Fi/Bluetooth timeout options. All branches additionally have a smattering of various miscellaneous patches courtesy of GrapheneOS.

I'm thinking this is getting a little "too complex" for this description here, maybe we should move them to [additional hardening of DivestOS](https://www.privacyguides.org/android/#additional-hardening-divestos), then describe what they are. This way it won't overwhelm readers of the recommendation, but if they *want to know more* the option is there, without having to do extensive research.

I would like to then see a source explaining:

- JNI constification
- partial bionic hardening patchsets (link to upstream?)
- `ptrace_scope` control (another one that could be moved down to additional hardening.
- automatic reboot/Wi-Fi/Bluetooth timeout options

2022-04-05 08:20 UTC, tommytran732 commented on docs/android.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
This is outside of the recommendation card, so I think it is fine. In fact, I'd cut off the recommendation card for CalyxOS and make it look more like GrapheneOS or DivestOS. The card can have a brief description of the recommendation, then anything outside of it can be used to explain it further.

It does not make sense to make an "additional hardening of DivestOS" if you are not going to make one for GrapheneOS and Calyx IMO.

2022-04-05 09:00 UTC, tommytran732 commented on docs/android.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
I added the link for ptrace and sanitization sanitation. The auto reboot/Wifi-/Bluetooth only has 1 mention on https://grapheneos.org/features, so I don't now if you even wanna link that.

I also split off the CalyxOS's card so it's consistent with GrapheneOS and DivestOS.

I think it's good for merge.

2022-04-05 11:07 UTC, SkewedZeppelin commented on docs/android.md
> +DivestOS has automated kernel vulnerability ([CVE](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures)) [patching](https://gitlab.com/divested-mobile/cve_checker), fewer proprietary b
page sanitization is zeroing of RAM, not browser

auto-var-init: https://reviews.llvm.org/D54604?id=174471

2022-04-05 12:07 UTC, qua3k commented on docs/android.md
> +DivestOS has automated kernel vulnerability ([CVE](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures)) [patching](https://gitlab.com/divested-mobile/cve_checker), fewer proprietary b
What is this? Zeroing pages on free with init_on_free=1 is unrelated to XSS sanitization. How is a browser feature related to the kernel?

2022-04-05 14:12 UTC, dngray commented on docs/android.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
> It does not make sense to make an "additional hardening of DivestOS" if you are not going to make one for GrapheneOS and Calyx IMO.

I'm inclined to agree with you.

> This is outside of the recommendation card, so I think it is fine. In fact, I'd cut off the recommendation card for CalyxOS and make it look more like GrapheneOS or DivestOS. The card can have a brief description of the recommendation, then anything outside of it can be used to explain it further.

Fair enough, that works too.



> I also split off the CalyxOS's card so it's consistent with GrapheneOS and DivestOS.

:+1:

2022-04-05 14:12 UTC, dngray commented on docs/android.md
> +DivestOS has automated kernel vulnerability ([CVE](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures)) [patching](https://gitlab.com/divested-mobile/cve_checker), fewer proprietary b
That was my bad, i added that link oops.

2022-04-06 06:57 UTC, dngray commented on docs/android.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
So I remember what JNI was from my Java days.

Just wondering if we can get a reference for:

- "constification", discussed within that paragraph.
- automatic reboot/Wi-Fi/Bluetooth timeout options

I don't think it would be clear what these things are.

2022-04-06 07:47 UTC, dngray commented on docs/android.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
I'm guess it has something to do with https://github.com/GrapheneOS/platform_frameworks_base/commit/b3a5c3db7fa158619656871ba3c5e3a73ee73725

2022-04-06 07:48 UTC, dngray commented on docs/android.md
> +DivestOS 16.0, 17.1, and 18.1 implements GrapheneOS's [`INTERNET`](https://developer.android.com/training/basics/network-ops/connecting) permission toggle, [hardened memory allocator](https://github.
A better reference would be https://en.wikipedia.org/wiki/Const_(computer_programming)

2022-04-06 07:53 UTC, merged