Integrating Metadata Removal
privacyguides/privacyguides.org pull request #919
Opened 2022-04-05 22:25 UTC by lx-is

I started researching how to integrate ExifTool into macOS's context menu for my own purposes, but somewhere along that path I thought it might serve as a cool guide.

I'm not sure if this type of content fits on the site, so feel free to close this PR. If that's the case I can just post it somewhere else, no big deal.

Scripting is a bit out of my comfort zone, so I'm sure there's room for improvement.

2022-04-07 08:56 UTC, tommytran732 approved these changes
If you ask me, this is the kind of content we want more of.

2022-04-07 09:28 UTC, elitejake commented
What if we make this into a Security Basics guide which is focused on metadata removal.

2022-04-07 12:25 UTC, dngray commented
> What if we make this into a Security Basics guide which is focused on metadata removal. An intro into what is metadata and how to remove them (not only on images) would be great.

That would be a good idea.

2022-04-07 13:43 UTC, ph00lt0 commented
@lx-is why are you not doing the MacOS version in shortcuts? You should be able to achieve the same there, and it is a little bit less complex.

2022-04-07 18:19 UTC, lx-is commented
> If you want me to update the PR with the explanation on how to do this let me know!

Yes, please do! That's much better.

2022-04-07 19:23 UTC, lx-is commented on docs/security/integrating-metadata-removal.md
> +You can check if ExifTool is installed by running `exiftool -ver`. You should see a version number. Next, confirm that ExifTool is installed at `/opt/homebrew/bin/exiftool` by running `which exiftool
I changed it to say:

> take note of where ExifTool is installed by running `which exiftool`.

and then later in the guide it says

> You should set your path to output of `which exiftool`.

2022-04-07 20:07 UTC, ph00lt0 commented
> > @lx-is why are you not doing the MacOS version in shortcuts? You should be able to achieve the same there, and it is a little bit less complex.
> 
> I went ahead and added it. Your solution is much simpler, thank you.

Prefect! You don't need to enable allow running scripts btw, it will prompt you and it will ask if you want to allow it once of any time, same goes for access to documents.

2022-04-07 20:09 UTC, ph00lt0 requested changes

2022-04-07 20:09 UTC, ph00lt0 commented on docs/security/integrating-metadata-removal.md
> +*Worth mentioning: the open source [ImageOptim](https://imageoptim.com/mac) app integrates into Finder's Services menu by default.*
this quote feels a bit out of place

2022-04-07 20:09 UTC, ph00lt0 commented on docs/security/integrating-metadata-removal.md
> +1. Ensure the shortcut is enabled by going to *System Preferences > Extensions > Finder* and enabling the shortcut you created.
You do not need to do this tho, you can much simpler just enable it within the shortcuts app :)

I use also the clipboard input if you don't just the quick action in finder will be enough. Saves a few steps opening the settings app as well. 
![image](https://user-images.githubusercontent.com/15004290/162287544-b61943bc-53a2-4e3f-8b3a-08b95a01665e.png)

2022-04-08 11:56 UTC, ph00lt0 approved these changes

2022-04-08 12:04 UTC, ph00lt0 commented
@lx-is I just noticed in the quick actions menu there is also this convert image option which allows stripping of meta data.
![image](https://user-images.githubusercontent.com/15004290/162431907-58bda661-7b64-4781-b340-07624be6217c.png)

Do you know if this is worse then the shortcut?

2022-04-08 13:37 UTC, ph00lt0 commented
@dngray the screenshot is currently not the same as the code in the snippet. The return line includes `return $@` in the screenshot and `return "$@"` in the snippet. I am not even sure if you need to return at all. My version needed this to support clipboard input, but I don't think it's needed if you don't want to include that.

2022-04-08 13:44 UTC, ph00lt0 requested changes

2022-04-08 13:44 UTC, ph00lt0 commented on docs/security/integrating-metadata-removal.md
> +    exiftoolPath=$(which exiftool)
This trick does not work and gives me an exemption. The path should be `/usr/local/bin/` using the path in the loop is not helping.

2022-04-08 13:44 UTC, ph00lt0 requested changes

2022-04-08 13:44 UTC, ph00lt0 commented on docs/security/integrating-metadata-removal.md
> +    return "$@"
@dngray the screenshot is currently not the same as the code in the snippet. The return line includes `return $@` in the screenshot and `return "$@"` in the snippet. I am not even sure if you need to return at all. My version needed this to support clipboard input, but I don't think it's needed if you don't want to include that.

2022-04-08 13:53 UTC, ph00lt0 commented on docs/security/integrating-metadata-removal.md
> +    exiftoolPath=$(which exiftool)
Found a way to fix this: https://github.com/lx-is/privacyguides.org/pull/1/files

2022-04-08 14:01 UTC, ph00lt0 commented on docs/security/integrating-metadata-removal.md
> +    return "$@"
Also removed in https://github.com/lx-is/privacyguides.org/pull/1 seems unnecessary.

2022-04-08 17:57 UTC, lx-is commented
> @lx-is I just noticed in the quick actions menu there is also this convert image option which allows stripping of meta data. ![image](https://user-images.githubusercontent.com/15004290/162431907-58bda661-7b64-4781-b340-07624be6217c.png)
> 
> Do you know if this is worse then the shortcut?

If it's anything like the Preserve Metadata option in Shortcuts then it's not as exhaustive. I haven't tried it myself though.

> Found a way to fix this: https://github.com/lx-is/privacyguides.org/pull/1/files

The script here is resulting in an error for me. Does it work for you? @ph00lt0

2022-04-08 20:10 UTC, ph00lt0 commented
> The script here is resulting in an error for me. Does it work for you? @ph00lt0


@lx-is do you mean my latest? PR or what dngray wrote? What is the error you are getting?

2022-04-08 20:35 UTC, lx-is commented
> @lx-is do you mean my latest? PR or what dngray wrote? What is the error you are getting?

Yours and dng's aren't working for me. His doesn't error out, but it doesn't do anything either. With yours I get a generic "Run Shell Script finished with an error" message.

2022-04-08 22:03 UTC, ph00lt0 commented
> Yours and dng's aren't working for me. His doesn't error out, but it doesn't do anything either. With yours I get a generic "Run Shell Script finished with an error" message.

If you get you should see a more detailed error in the shortcut app. Else what happens is you run these commands line by line? 

dng's didn't work for me either, because it won't execute from the wrong path. That's why I thought of using dirname to get the actual path, assuming that this would work on any set up.

2022-04-08 22:14 UTC, lx-is commented
> @lx-is If you get you should see a more detailed error in the shortcut app

![error](https://user-images.githubusercontent.com/100533118/162539895-5779a84a-3481-4383-8e02-ec1f605d4ad1.png)

2022-04-08 22:17 UTC, ph00lt0 commented
How odd @lx-is, if you execute $(which exiftool) does it return "/opt/homebrew/bin/exiftool" or something different?

2022-04-08 22:22 UTC, lx-is commented
> How odd @lx-is, if you execute `$ which exiftool` does it return `/opt/homebrew/bin/exiftool` or something different?

`/opt/homebrew/bin/exiftool`

2022-04-08 22:27 UTC, ph00lt0 commented
For me `dirname $(which exiftool) returns `/usr/local/bin` this is the path in which homebrew installs the tool, thus allowing it to work. I am surpised this doesn't for you as you used `/opt/homebrew/bin` also in your first version.

2022-04-08 22:28 UTC, lx-is commented
> For me `dirname $(which exiftool)` returns `/usr/local/bin` this is the path in which homebrew installs the tool, thus allowing it to work. I am surpised this doesn't for you as you used `/opt/homebrew/bin` also in your first version.

`dirname $(which exiftool)` returns `/opt/homebrew/bin` for me.

2022-04-08 22:33 UTC, ph00lt0 commented
> > For me `dirname $(which exiftool)` returns `/usr/local/bin` this is the path in which homebrew installs the tool, thus allowing it to work. I am surpised this doesn't for you as you used `/opt/homebrew/bin` also in your first version.
> 
> `dirname $(which exiftool)` returns `/opt/homebrew/bin` for me.

Yeah that's right.
Could you try this as script maybe instead?

```bash
for f in "$@"
do
    $(which exiftool) -overwrite_original -all= "$f";
done
```

2022-04-08 22:41 UTC, lx-is commented
> This works for me and saves a line, this this works for you it would be awesome.

I get the same type of error :/. This is so frustrating haha

So far, this is still what's worked best *for me*:

```BASH
#!/bin/sh
PATH=/opt/homebrew/bin
for f in "$@"
do
	exiftool -all= "$f";
done
return "$@"
```

2022-04-09 04:08 UTC, dngray commented on docs/security/integrating-metadata-removal.md
> +    return "$@"
Merged into this PR

2022-04-09 04:20 UTC, dngray commented
The reason `dirname $(which exiftool)` doesn't work is because that returns the path without the binary, ie `/opt/homebrew/bin/`.

What  error do you get when you have just `$(which exiftool)`, perhaps its because there's more than one result?

2022-04-09 04:22 UTC, dngray commented
> ```shell
> for f in "$@"
> do
>     $(which exiftool) -overwrite_original -all= "$f";
> done
> ```

There's no need to evaluate the binary's path each run of the loop.

2022-04-09 04:56 UTC, dngray commented
Does this not work?

```bash
#!/bin/sh
absExiftool=$(which exiftool)

for f in "$@"
do
    "$absExiftool" -all= "$f";
done
return "$@"
```

2022-04-09 08:07 UTC, merged

2022-04-09 09:16 UTC, dngray commented
@tommytran732 that's not going to work `PATH=dirname $(which exiftool)`.

At very least it would need to be `PATH=$(dirname $(which exiftool))`

2022-04-09 09:23 UTC, dngray commented
Another simpler approach is to get rid of `PATH` or `absExiftool` the homebrew path should already be in a user's path.

2022-04-09 11:34 UTC, ph00lt0 commented
> ```shell
> #!/bin/sh
> PATH=$(dirname $(which exiftool))
> for f in "$@"
> do
>   	exiftool -all= "$f";
> done
> return "$@"
> ```
>
> Do you get an error with either of these? I don't have a Mac so I can't check.

@dngray @tommytran732 this is the only one working for me.

2022-04-09 23:19 UTC, tommytran732 commented
> > ```shell
> > #!/bin/sh
> > PATH=$(dirname $(which exiftool))
> > for f in "$@"
> > do
> >   	exiftool -all= "$f";
> > done
> > return "$@"
> > ```
> >
> > Do you get an error with either of these? I don't have a Mac so I can't check.
> 
> @dngray @tommytran732 this is the only one working for me. Also looks the safest, it worked for me without the $() but I agree it's better to do it like this. What currently is on the website definitely does not work.

I tested without the PATH and it works fine for me