Removing Jurisdiction Requirements
privacyguides/privacyguides.org pull request #937
Opened 2022-04-07 15:16 UTC by freddy-m

## Description

See title.

2022-04-07 15:50 UTC, dngray commented
We probably want to write a blog post about this before we merge and also update the VPN page's criteria, it was discussed quite thoroughly https://github.com/privacytools/privacytools.io/issues/1437

2022-04-10 05:30 UTC, EdwardLangdon commented on docs/email.md
Considering adding Why removed the requirements and reason not to Consider about `Eyes` Countries.

2022-04-10 06:58 UTC, dngray commented on docs/email.md
I intend to write a blog post about it actually.

2022-04-10 08:50 UTC, EdwardLangdon commented on docs/email.md
Okay, Then Hyperlink your post after you have completed writing.

2022-04-14 00:30 UTC, jonaharagon requested changes
Needs to be removed on VPN.md as well.

2022-04-14 19:27 UTC, dngray commented
> Needs to be removed on VPN.md as well.

Yep, we're looking at https://github.com/privacyguides/privacyguides.org/pull/960#issuecomment-1097927203 first as i want to get some of the threat modeling stuff  done first, that way when we look at vpn/email we can refer to threat modeling page instead.

2022-05-24 07:57 UTC, dngray commented
> Needs to be removed on VPN.md as well.

Okay, done, now we've got the threat modeling page, this makes a bit more sense.

2022-05-24 08:00 UTC, dngray approved these changes

2022-05-24 08:00 UTC, merged