Remove-social-networks
privacyguides/privacyguides.org pull request #953
Opened 2022-04-08 08:47 UTC by tommytran732

This PR removed Social Networks and Social News Aggregators as discussed in https://github.com/privacyguides/privacyguides.org/discussions/949

Legacy 3rd party PNGs and SVGs are also removed. Other legacy PNGs and SVGs are not removed yet, as I don't know if they are still being used or not.

2022-04-08 14:06 UTC, dngray approved these changes
Based on what I wrote in that discussion thread, I approve, but I am a bit on the fence on this one.

When we define "privacy" who is the adversary?

In regard to commercial platforms these tightly integrate with adtech empires, while it's possible smaller instances could do that, at present they do not. It'd be a shame to see mastodon go, when this does actually have E2EE on private messages too.

In regard to Lemmy, from what i've used of it, it's a lot faster than Reddit, (more like old.reddit.com). As much as I use Reddit, I really do hate the "new reddit", it's clunky and horrible. I can fully foresee one day the company behind that product ruining it completely.

2022-04-08 16:16 UTC, dngray requested changes
I think we should definitely let everyone have an opportunity to speak on this before we merge/close.

2022-04-08 16:28 UTC, tommytran732 commented
> Based on what I wrote in that discussion thread, I would approve, but I am a bit on the fence on this one.
> 
> When we define "privacy" who is the adversary?
> 
> In regard to commercial platforms these tightly integrate with adtech empires, while it's possible smaller instances could do that, at present they do not. It'd be a shame to see mastodon go, when this does actually have E2EE on private messages too.
> 
> In regard to Lemmy, from what i've used of it, it's a lot faster than Reddit, (more like old.reddit.com). As much as I use Reddit, I really do hate the "new reddit", it's clunky and horrible. I can fully foresee one day the company behind that product ruining it completely.

If you want we can keep mastodon as the only recommendation. Do keep in mind that it is only good because of e2ee messages. The primary functions (tweets, retweets, comments) are not private and can never be private.

2022-04-08 16:56 UTC, dngray commented
What I am saying is they do offer some privacy in respect to not having to go through hoops to create an account (you don't need a phone number for example).

Privacy in terms of content? well, it's not, because its publicly broadcast, so I don't think E2EE is really the only factor you can use to evaluate this, that works for platforms where you want to restrict distribution to a few parties, but that's about it.

2022-04-08 19:05 UTC, realguyman commented
I don't think we should remove _all_ of the social media platforms. I've written my piece on #949.

2022-04-09 06:09 UTC, dngray commented
In an effort to keep this clean, all future posts should be in the discussion thread.

2022-04-11 17:45 UTC, realguyman commented
PrivacyGuides has gone a re-write/re-birth, so I see little reason to not purge social media and such. We're not preventing anyone from recommending them again, so I think it's safe to remove them for now.

@dngray I'll remove your "requested changes" so we can merge the pull request, assuming everything is OK to go.

2022-04-12 14:09 UTC, jonaharagon commented on docs/tools.md
> +
Missing a "learn more" link to the social media recommendations.

2022-04-13 06:41 UTC, merged

2022-04-14 00:33 UTC, bkil commented
I don't agree with this change (comments provided in the other issue)